.TH "__bnx2x_vlan_mac_h_read_lock" 9 "__bnx2x_vlan_mac_h_read_lock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__bnx2x_vlan_mac_h_read_lock \- lock the vlan mac head list reader lock
.SH SYNOPSIS
.B "int" __bnx2x_vlan_mac_h_read_lock
.BI "(struct bnx2x *bp "  ","
.BI "struct bnx2x_vlan_mac_obj *o "  ");"
.SH ARGUMENTS
.IP "bp" 12
device handle
.IP "o" 12
vlan_mac object
.SH "CONTEXT"
Should be called under the execution queue lock. May sleep. May
release and reclaim execution queue lock during its run.
