.TH "__cgroup_task_count" 9 "__cgroup_task_count" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__cgroup_task_count \- count the number of tasks in a cgroup. The caller is responsible for taking the css_set_lock.
.SH SYNOPSIS
.B "int" __cgroup_task_count
.BI "(const struct cgroup *cgrp "  ");"
.SH ARGUMENTS
.IP "cgrp" 12
the cgroup in question
