.TH "__check_agg_selection_timer" 9 "__check_agg_selection_timer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__check_agg_selection_timer \- check if the selection timer has expired
.SH SYNOPSIS
.B "int" __check_agg_selection_timer
.BI "(struct port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
the port we're looking at
