.TH "__drm_gem_cma_create" 9 "__drm_gem_cma_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__drm_gem_cma_create \- Create a GEM CMA object without allocating memory
.SH SYNOPSIS
.B "struct drm_gem_cma_object *" __drm_gem_cma_create
.BI "(struct drm_device *drm "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "drm" 12
DRM device
.IP "size" 12
size of the object to allocate
.SH "DESCRIPTION"
This function creates and initializes a GEM CMA object of the given size,
but doesn't allocate any memory to back the object.
.SH "RETURN"
A struct drm_gem_cma_object * on success or an \fBERR_PTR\fP-encoded negative
error code on failure.
