.TH "__drm_atomic_helper_plane_state_reset" 9 "__drm_atomic_helper_plane_state_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__drm_atomic_helper_plane_state_reset \- resets plane state to default values
.SH SYNOPSIS
.B "void" __drm_atomic_helper_plane_state_reset
.BI "(struct drm_plane_state *plane_state "  ","
.BI "struct drm_plane *plane "  ");"
.SH ARGUMENTS
.IP "plane_state" 12
atomic plane state, must not be NULL
.IP "plane" 12
plane object, must not be NULL
.SH "DESCRIPTION"
Initializes the newly allocated \fIplane_state\fP with default
values. This is useful for drivers that subclass the CRTC state.
