.TH "__drm_atomic_helper_bridge_duplicate_state" 9 "__drm_atomic_helper_bridge_duplicate_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__drm_atomic_helper_bridge_duplicate_state \- Copy atomic bridge state
.SH SYNOPSIS
.B "void" __drm_atomic_helper_bridge_duplicate_state
.BI "(struct drm_bridge *bridge "  ","
.BI "struct drm_bridge_state *state "  ");"
.SH ARGUMENTS
.IP "bridge" 12
bridge object
.IP "state" 12
atomic bridge state
.SH "DESCRIPTION"
Copies atomic state from a bridge's current state and resets inferred values.
This is useful for drivers that subclass the bridge state.
