.TH "__fnic_set_state_flags" 9 "__fnic_set_state_flags" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__fnic_set_state_flags \- 
.SH SYNOPSIS
.B "void" __fnic_set_state_flags
.BI "(struct fnic *fnic "  ","
.BI "unsigned long st_flags "  ","
.BI "unsigned long clearbits "  ");"
.SH ARGUMENTS
.IP "fnic" 12
-- undescribed --
.IP "st_flags" 12
-- undescribed --
.IP "clearbits" 12
-- undescribed --
.SH "DESCRIPTION"
Sets/Clears bits in fnic's state_flags
