.TH "__iio_str_to_fixpoint" 9 "__iio_str_to_fixpoint" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__iio_str_to_fixpoint \- Parse a fixed-point number from a string
.SH SYNOPSIS
.B "int" __iio_str_to_fixpoint
.BI "(const char *str "  ","
.BI "int fract_mult "  ","
.BI "int *integer "  ","
.BI "int *fract "  ","
.BI "bool scale_db "  ");"
.SH ARGUMENTS
.IP "str" 12
The string to parse
.IP "fract_mult" 12
Multiplier for the first decimal place, should be a power of 10
.IP "integer" 12
The integer part of the number
.IP "fract" 12
The fractional part of the number
.IP "scale_db" 12
True if this should parse as dB
.SH "DESCRIPTION"
Returns 0 on success, or a negative error code if the string could not be
parsed.
