.TH "__ipr_get_free_ipr_cmnd" 9 "__ipr_get_free_ipr_cmnd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__ipr_get_free_ipr_cmnd \- Get a free IPR Cmnd block
.SH SYNOPSIS
.B "struct ipr_cmnd *" __ipr_get_free_ipr_cmnd
.BI "(struct ipr_hrr_queue *hrrq "  ");"
.SH ARGUMENTS
.IP "hrrq" 12
hrr queue
.SH "DESCRIPTION"
Return value:
pointer to ipr command struct
