.TH "__irq_alloc_domain_generic_chips" 9 "__irq_alloc_domain_generic_chips" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__irq_alloc_domain_generic_chips \- Allocate generic chips for an irq domain
.SH SYNOPSIS
.B "int" __irq_alloc_domain_generic_chips
.BI "(struct irq_domain *d "  ","
.BI "int irqs_per_chip "  ","
.BI "int num_ct "  ","
.BI "const char *name "  ","
.BI "irq_flow_handler_t handler "  ","
.BI "unsigned int clr "  ","
.BI "unsigned int set "  ","
.BI "enum irq_gc_flags gcflags "  ");"
.SH ARGUMENTS
.IP "d" 12
irq domain for which to allocate chips
.IP "irqs_per_chip" 12
Number of interrupts each chip handles (max 32)
.IP "num_ct" 12
Number of irq_chip_type instances associated with this
.IP "name" 12
Name of the irq chip
.IP "handler" 12
Default flow handler associated with these chips
.IP "clr" 12
IRQ_* bits to clear in the mapping function
.IP "set" 12
IRQ_* bits to set in the mapping function
.IP "gcflags" 12
Generic chip specific setup flags
