.TH "__napi_schedule" 9 "__napi_schedule" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__napi_schedule \- schedule for receive
.SH SYNOPSIS
.B "void" __napi_schedule
.BI "(struct napi_struct *n "  ");"
.SH ARGUMENTS
.IP "n" 12
entry to schedule
.SH "DESCRIPTION"
The entry's receive function will be scheduled to run.
Consider using \fB__napi_schedule_irqoff\fP if hard irqs are masked.
