.TH "__nfp_eth_set_fec" 9 "__nfp_eth_set_fec" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__nfp_eth_set_fec \- set PHY forward error correction control bit
.SH SYNOPSIS
.B "int" __nfp_eth_set_fec
.BI "(struct nfp_nsp *nsp "  ","
.BI "enum nfp_eth_fec mode "  ");"
.SH ARGUMENTS
.IP "nsp" 12
NFP NSP handle returned from \fBnfp_eth_config_start\fP
.IP "mode" 12
Desired fec mode
.SH "DESCRIPTION"
Set the PHY module forward error correction mode.
Will write to hwinfo overrides in the flash (persistent config).
.SH "RETURN"
0 or -ERRNO.
