.TH "__pm_stay_awake" 9 "__pm_stay_awake" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__pm_stay_awake \- Notify the PM core of a wakeup event.
.SH SYNOPSIS
.B "void" __pm_stay_awake
.BI "(struct wakeup_source *ws "  ");"
.SH ARGUMENTS
.IP "ws" 12
Wakeup source object associated with the source of the event.
.SH "DESCRIPTION"
It is safe to call this function from interrupt context.
