.TH "__pm_runtime_use_autosuspend" 9 "__pm_runtime_use_autosuspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__pm_runtime_use_autosuspend \- Set a device's use_autosuspend flag.
.SH SYNOPSIS
.B "void" __pm_runtime_use_autosuspend
.BI "(struct device *dev "  ","
.BI "bool use "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to handle.
.IP "use" 12
New value for use_autosuspend.
.SH "DESCRIPTION"
Set the device's power.use_autosuspend flag, and allow or prevent runtime
suspends as needed.
