.TH "__prci_wrpll_write_cfg1" 9 "__prci_wrpll_write_cfg1" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__prci_wrpll_write_cfg1 \- write Clock enable/disable configuration into the PRCI
.SH SYNOPSIS
.B "void" __prci_wrpll_write_cfg1
.BI "(struct __prci_data *pd "  ","
.BI "struct __prci_wrpll_data *pwd "  ","
.BI "u32 enable "  ");"
.SH ARGUMENTS
.IP "pd" 12
PRCI context
.IP "pwd" 12
PRCI WRPLL metadata
.IP "enable" 12
Clock enable or disable value
