.TH "__rhashtable_walk_find_next" 9 "__rhashtable_walk_find_next" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__rhashtable_walk_find_next \- Find the next element in a table (or the first one in case of a new walk).
.SH SYNOPSIS
.B "void *" __rhashtable_walk_find_next
.BI "(struct rhashtable_iter *iter "  ");"
.SH ARGUMENTS
.IP "iter" 12
Hash table iterator
.SH "DESCRIPTION"
Returns the found object or NULL when the end of the table is reached.

Returns -EAGAIN if resize event occurred.
