.TH "__rpmsg_destroy_ept" 9 "__rpmsg_destroy_ept" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__rpmsg_destroy_ept \- destroy an existing rpmsg endpoint
.SH SYNOPSIS
.B "void" __rpmsg_destroy_ept
.BI "(struct virtproc_info *vrp "  ","
.BI "struct rpmsg_endpoint *ept "  ");"
.SH ARGUMENTS
.IP "vrp" 12
virtproc which owns this ept
.IP "ept" 12
endpoing to destroy
.SH "DESCRIPTION"
An internal function which destroy an ept without assuming it is
bound to an rpmsg channel. This is needed for handling the internal
name service endpoint, which isn't bound to an rpmsg channel.
See also \fB__rpmsg_create_ept\fP.
