.TH "__sdma_txclean" 9 "__sdma_txclean" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__sdma_txclean \- clean tx of mappings, descp *kmalloc's
.SH SYNOPSIS
.B "void" __sdma_txclean
.BI "(struct hfi1_devdata *dd "  ","
.BI "struct sdma_txreq *tx "  ");"
.SH ARGUMENTS
.IP "dd" 12
hfi1_devdata for unmapping
.IP "tx" 12
tx request to clean
.SH "DESCRIPTION"
This is used in the progress routine to clean the tx or
by the ULP to toss an in-process tx build.

The code can be called multiple times without issue.
