.TH "__trace_bputs" 9 "__trace_bputs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__trace_bputs \- write the pointer to a constant string into trace buffer
.SH SYNOPSIS
.B "int" __trace_bputs
.BI "(unsigned long ip "  ","
.BI "const char *str "  ");"
.SH ARGUMENTS
.IP "ip" 12
The address of the caller
.IP "str" 12
The constant string to write to the buffer to
