.TH "__ubifs_hash_get_desc" 9 "__ubifs_hash_get_desc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__ubifs_hash_get_desc \- get a descriptor suitable for hashing a node
.SH SYNOPSIS
.B "struct shash_desc *" __ubifs_hash_get_desc
.BI "(const struct ubifs_info *c "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.SH "DESCRIPTION"
This function returns a descriptor suitable for hashing a node. Free after use
with kfree.
