.TH "__v9fs_readpages_from_fscache" 9 "__v9fs_readpages_from_fscache" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__v9fs_readpages_from_fscache \- read multiple pages from cache
.SH SYNOPSIS
.B "int" __v9fs_readpages_from_fscache
.BI "(struct inode *inode "  ","
.BI "struct address_space *mapping "  ","
.BI "struct list_head *pages "  ","
.BI "unsigned *nr_pages "  ");"
.SH ARGUMENTS
.IP "inode" 12
-- undescribed --
.IP "mapping" 12
-- undescribed --
.IP "pages" 12
-- undescribed --
.IP "nr_pages" 12
-- undescribed --
.SH "DESCRIPTION"

Returns 0 if the pages are in cache and a BIO is submitted,
1 if the pages are not in cache and -error otherwise.
