.TH "_base_unmask_events" 9 "_base_unmask_events" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_base_unmask_events \- turn on notification for this event
.SH SYNOPSIS
.B "void" _base_unmask_events
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "u16 event "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "event" 12
firmware event
.SH "DESCRIPTION"
The mask is stored in ioc->event_masks.
