.TH "_base_build_sg_scmd_ieee" 9 "_base_build_sg_scmd_ieee" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_base_build_sg_scmd_ieee \- main sg creation routine for IEEE format
.SH SYNOPSIS
.B "int" _base_build_sg_scmd_ieee
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "struct scsi_cmnd *scmd "  ","
.BI "u16 smid "  ","
.BI "struct _pcie_device *pcie_device "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "scmd" 12
scsi command
.IP "smid" 12
system request message index
.IP "pcie_device" 12
Pointer to pcie_device. If set, the pcie native sgl will be
constructed on need.
.SH "CONTEXT"
none.
.SH "DESCRIPTION"
The main routine that builds scatter gather table from a given
scsi request sent via the .queuecommand main handler.
.SH "RETURN"
0 success, anything else error
