.TH "_clkdm_save_context" 9 "_clkdm_save_context" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_clkdm_save_context \- save the context for the control of this clkdm
.SH SYNOPSIS
.B "int" _clkdm_save_context
.BI "(struct clockdomain *clkdm "  ","
.BI "void *unused "  ");"
.SH ARGUMENTS
.IP "clkdm" 12
-- undescribed --
.IP "unused" 12
-- undescribed --
.SH "DESCRIPTION"

Due to a suspend or hibernation operation, the state of the registers
controlling this clkdm will be lost, save their context.
