.TH "_config_free_config_dma_memory" 9 "_config_free_config_dma_memory" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_config_free_config_dma_memory \- wrapper to free the memory
.SH SYNOPSIS
.B "void" _config_free_config_dma_memory
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "struct config_request *mem "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "mem" 12
struct config_request
.SH "DESCRIPTION"
A wrapper to free dma-able memory when using _config_alloc_config_dma_memory.
.SH "RETURN"
0 for success, non-zero for failure.
