.TH "_ctl_btdh_mapping" 9 "_ctl_btdh_mapping" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_ctl_btdh_mapping \- main handler for MPT3BTDHMAPPING opcode
.SH SYNOPSIS
.B "long" _ctl_btdh_mapping
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "void __user *arg "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "arg" 12
user space buffer containing ioctl content
