.TH "_ctl_diag_register" 9 "_ctl_diag_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_ctl_diag_register \- application register with driver
.SH SYNOPSIS
.B "long" _ctl_diag_register
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "void __user *arg "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "arg" 12
user space buffer containing ioctl content
.SH "DESCRIPTION"
This will allow the driver to setup any required buffers that will be
needed by firmware to communicate with the driver.
