.TH "_deny_idle" 9 "_deny_idle" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_deny_idle \- prevent DPLL from automatically idling
.SH SYNOPSIS
.B "void" _deny_idle
.BI "(struct clk_hw_omap *clk "  ");"
.SH ARGUMENTS
.IP "clk" 12
struct clk * of the DPLL to operate on
.SH "DESCRIPTION"
Disable DPLL automatic idle control.  No return value.
