.TH "_drm_lease_revoke" 9 "_drm_lease_revoke" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_drm_lease_revoke \- revoke access to all leased objects (idr_mutex held)
.SH SYNOPSIS
.B "void" _drm_lease_revoke
.BI "(struct drm_master *top "  ");"
.SH ARGUMENTS
.IP "top" 12
the master losing its lease
