.TH "_drm_has_leased" 9 "_drm_has_leased" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_drm_has_leased \- check to see if an object has been leased (idr_mutex held)
.SH SYNOPSIS
.B "bool" _drm_has_leased
.BI "(struct drm_master *master "  ","
.BI "int id "  ");"
.SH ARGUMENTS
.IP "master" 12
the master to check the lease status of
.IP "id" 12
the id to check
.SH "DESCRIPTION"
Checks if any lessee of 'master' holds a lease on 'id'. Return
value:

true            Some lessee holds a lease on the object.
false           No lessee has a lease on the object.
