.TH "_enable_clocks" 9 "_enable_clocks" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_enable_clocks \- enable hwmod main clock and interface clocks
.SH SYNOPSIS
.B "int" _enable_clocks
.BI "(struct omap_hwmod *oh "  ");"
.SH ARGUMENTS
.IP "oh" 12
struct omap_hwmod *
.SH "DESCRIPTION"
Enables all clocks necessary for register reads and writes to succeed
on the hwmod \fIoh\fP.  Returns 0.
