.TH "_ishtp_read_hdr" 9 "_ishtp_read_hdr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_ishtp_read_hdr \- Read message header
.SH SYNOPSIS
.B "uint32_t" _ishtp_read_hdr
.BI "(const struct ishtp_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
ISHTP device pointer
.SH "DESCRIPTION"
Read header of 32bit length
.SH "RETURN"
Read register value
