.TH "_scsih_block_io_all_device" 9 "_scsih_block_io_all_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_scsih_block_io_all_device \- set the device state to SDEV_BLOCK
.SH SYNOPSIS
.B "void" _scsih_block_io_all_device
.BI "(struct MPT3SAS_ADAPTER *ioc "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.SH "DESCRIPTION"
During device pull we need to appropriately set the sdev state.
