.TH "_scsih_sas_volume_delete" 9 "_scsih_sas_volume_delete" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_scsih_sas_volume_delete \- delete volume
.SH SYNOPSIS
.B "void" _scsih_sas_volume_delete
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "u16 handle "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "handle" 12
volume device handle
.SH "CONTEXT"
user.
