.TH "_scsih_raid_device_remove" 9 "_scsih_raid_device_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_scsih_raid_device_remove \- delete raid_device object
.SH SYNOPSIS
.B "void" _scsih_raid_device_remove
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "struct _raid_device *raid_device "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "raid_device" 12
raid_device object
