.TH "_set_slave_idlemode" 9 "_set_slave_idlemode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_set_slave_idlemode \- set the OCP_SYSCONFIG SIDLEMODE field in @v
.SH SYNOPSIS
.B "int" _set_slave_idlemode
.BI "(struct omap_hwmod *oh "  ","
.BI "u8 idlemode "  ","
.BI "u32 *v "  ");"
.SH ARGUMENTS
.IP "oh" 12
struct omap_hwmod *
.IP "idlemode" 12
SIDLEMODE field bits
.IP "v" 12
pointer to register contents to modify
.SH "DESCRIPTION"
Update the slave idle mode bits in \fIv\fP to be \fIidlemode\fP for the \fIoh\fP
hwmod.  Does not write to the hardware.  Returns -EINVAL upon error
or 0 upon success.
