.TH "_update_sysc_cache" 9 "_update_sysc_cache" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_update_sysc_cache \- return the module OCP_SYSCONFIG register, keep copy
.SH SYNOPSIS
.B "int" _update_sysc_cache
.BI "(struct omap_hwmod *oh "  ");"
.SH ARGUMENTS
.IP "oh" 12
struct omap_hwmod *
.SH "DESCRIPTION"
Load the current value of the hwmod OCP_SYSCONFIG register into the
struct omap_hwmod for later use.  Returns -EINVAL if the hwmod has no
OCP_SYSCONFIG register or 0 upon success.
