.TH "aa_may_ptrace" 9 "aa_may_ptrace" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aa_may_ptrace \- test if tracer task can trace the tracee
.SH SYNOPSIS
.B "int" aa_may_ptrace
.BI "(struct aa_label *tracer "  ","
.BI "struct aa_label *tracee "  ","
.BI "u32 request "  ");"
.SH ARGUMENTS
.IP "tracer" 12
label of the task doing the tracing  (NOT NULL)
.IP "tracee" 12
task label to be traced
.IP "request" 12
permission request
.SH "RETURN"
0 else error code if permission denied or error
