.TH "aa_update_label_name" 9 "aa_update_label_name" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aa_update_label_name \- update a label to have a stored name
.SH SYNOPSIS
.B "bool" aa_update_label_name
.BI "(struct aa_ns *ns "  ","
.BI "struct aa_label *label "  ","
.BI "gfp_t gfp "  ");"
.SH ARGUMENTS
.IP "ns" 12
ns being viewed from (NOT NULL)
.IP "label" 12
label to update (NOT NULL)
.IP "gfp" 12
type of memory allocation
.SH "DESCRIPTION"
Requires: labels_set(label) not locked in caller
.SH "NOTE"
only updates the label name if it does not have a name already
and if it is in the labelset
