.TH "aac_queuecommand" 9 "aac_queuecommand" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aac_queuecommand \- queue a SCSI command
.SH SYNOPSIS
.B "int" aac_queuecommand
.BI "(struct Scsi_Host *shost "  ","
.BI "struct scsi_cmnd *cmd "  ");"
.SH ARGUMENTS
.IP "shost" 12
Scsi host to queue command on
.IP "cmd" 12
SCSI command to queue

Queues a command for execution by the associated Host Adapter.

TODO: unify with \fBaac_scsi_cmd\fP.
