.TH "ab8500_btemp_templow_handler" 9 "ab8500_btemp_templow_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_btemp_templow_handler \- battery temp lower than 10 degrees
.SH SYNOPSIS
.B "irqreturn_t" ab8500_btemp_templow_handler
.BI "(int irq "  ","
.BI "void *_di "  ");"
.SH ARGUMENTS
.IP "irq" 12
interrupt number
.IP "_di" 12
void pointer that has to address of ab8500_btemp
.SH "DESCRIPTION"
Returns IRQ status(IRQ_HANDLED)
