.TH "ab8500_charger_get_ac_current" 9 "ab8500_charger_get_ac_current" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_charger_get_ac_current \- get ac charger current
.SH SYNOPSIS
.B "int" ab8500_charger_get_ac_current
.BI "(struct ab8500_charger *di "  ");"
.SH ARGUMENTS
.IP "di" 12
pointer to the ab8500_charger structure
.SH "DESCRIPTION"
This function returns the ac charger current.
Returns ac current (on success) and error code on failure.
