.TH "ab8500_fg_check_capacity_limits" 9 "ab8500_fg_check_capacity_limits" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_fg_check_capacity_limits \- Check if capacity has changed
.SH SYNOPSIS
.B "void" ab8500_fg_check_capacity_limits
.BI "(struct ab8500_fg *di "  ","
.BI "bool init "  ");"
.SH ARGUMENTS
.IP "di" 12
pointer to the ab8500_fg structure
.IP "init" 12
capacity is allowed to go up in init mode
.SH "DESCRIPTION"
Check if capacity or capacity limit has changed and notify the system
about it using the power_supply framework
