.TH "ab8500_btemp_periodic_work" 9 "ab8500_btemp_periodic_work" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_btemp_periodic_work \- Measuring the temperature periodically
.SH SYNOPSIS
.B "void" ab8500_btemp_periodic_work
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
pointer to the work_struct structure
.SH "DESCRIPTION"
Work function for measuring the temperature periodically
