.TH "ab8500_fg_inst_curr_done" 9 "ab8500_fg_inst_curr_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_fg_inst_curr_done \- check if fg conversion is done
.SH SYNOPSIS
.B "int" ab8500_fg_inst_curr_done
.BI "(struct ab8500_fg *di "  ");"
.SH ARGUMENTS
.IP "di" 12
pointer to the ab8500_fg structure
.SH "DESCRIPTION"
Returns 1 if conversion done, 0 if still waiting
