.TH "ab8500_fg_inst_curr_finalize" 9 "ab8500_fg_inst_curr_finalize" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_fg_inst_curr_finalize \- battery instantaneous current
.SH SYNOPSIS
.B "int" ab8500_fg_inst_curr_finalize
.BI "(struct ab8500_fg *di "  ","
.BI "int *res "  ");"
.SH ARGUMENTS
.IP "di" 12
pointer to the ab8500_fg structure
.IP "res" 12
battery instantenous current(on success)
.SH "DESCRIPTION"
Returns 0 or an error code
.SH "NOTE"
This is part "two" and has to be called at earliest 250 ms
after \fBab8500_fg_inst_curr_start\fP
