.TH "ab8500_btemp_id" 9 "ab8500_btemp_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_btemp_id \- Identify the connected battery
.SH SYNOPSIS
.B "int" ab8500_btemp_id
.BI "(struct ab8500_btemp *di "  ");"
.SH ARGUMENTS
.IP "di" 12
pointer to the ab8500_btemp structure
.SH "DESCRIPTION"
This function will try to identify the battery by reading the ID
resistor. Some brands use a combined ID resistor with a NTC resistor to
both be able to identify and to read the temperature of it.
