.TH "abx500_chargalg_hold_charging" 9 "abx500_chargalg_hold_charging" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
abx500_chargalg_hold_charging \- Pauses charging
.SH SYNOPSIS
.B "void" abx500_chargalg_hold_charging
.BI "(struct abx500_chargalg *di "  ");"
.SH ARGUMENTS
.IP "di" 12
pointer to the abx500_chargalg structure
.SH "DESCRIPTION"
This function is called in the case where maintenance charging has been
disabled and instead a battery voltage mode is entered to check when the
battery voltage has reached a certain recharge voltage
