.TH "abx500_chargalg_wd_work" 9 "abx500_chargalg_wd_work" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
abx500_chargalg_wd_work \- periodic work to kick the charger watchdog
.SH SYNOPSIS
.B "void" abx500_chargalg_wd_work
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
pointer to the work_struct structure
.SH "DESCRIPTION"
Work queue function for kicking the charger watchdog
