.TH "acpi_register_gsi" 9 "acpi_register_gsi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_register_gsi \- Map a GSI to a linux IRQ number
.SH SYNOPSIS
.B "int" acpi_register_gsi
.BI "(struct device *dev "  ","
.BI "u32 gsi "  ","
.BI "int trigger "  ","
.BI "int polarity "  ");"
.SH ARGUMENTS
.IP "dev" 12
device for which IRQ has to be mapped
.IP "gsi" 12
GSI IRQ number
.IP "trigger" 12
trigger type of the GSI number to be mapped
.IP "polarity" 12
polarity of the GSI to be mapped
.SH "RETURN"
a valid linux IRQ number on success
-EINVAL on failure
