.TH "acpi_idle_enter_bm" 9 "acpi_idle_enter_bm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_idle_enter_bm \- enters C3 with proper BM handling
.SH SYNOPSIS
.B "int" acpi_idle_enter_bm
.BI "(struct cpuidle_driver *drv "  ","
.BI "struct acpi_processor *pr "  ","
.BI "struct acpi_processor_cx *cx "  ","
.BI "int index "  ");"
.SH ARGUMENTS
.IP "drv" 12
cpuidle driver
.IP "pr" 12
Target processor
.IP "cx" 12
Target state context
.IP "index" 12
index of target state
