.TH "acpi_lpat_free_conversion_table" 9 "acpi_lpat_free_conversion_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_lpat_free_conversion_table \- Free LPAT table.
.SH SYNOPSIS
.B "void" acpi_lpat_free_conversion_table
.BI "(struct acpi_lpat_conversion_table *lpat_table "  ");"
.SH ARGUMENTS
.IP "lpat_table" 12
the temperature_raw mapping table structure
.SH "DESCRIPTION"
Frees the LPAT table previously allocated by a call to
acpi_lpat_get_conversion_table.
