.TH "acpi_dock_add" 9 "acpi_dock_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_dock_add \- Add a new dock station
.SH SYNOPSIS
.B "void" acpi_dock_add
.BI "(struct acpi_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
Dock station ACPI device object.
.SH "DESCRIPTION"
allocated and initialize a new dock station device.
