.TH "acpi_gtdt_c3stop" 9 "acpi_gtdt_c3stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_gtdt_c3stop \- Got c3stop info from GTDT according to the type of PPI.
.SH SYNOPSIS
.B "bool" acpi_gtdt_c3stop
.BI "(int type "  ");"
.SH ARGUMENTS
.IP "type" 12
the type of PPI.
.SH "RETURN"
true if the timer HW state is lost when a CPU enters an idle state,
false otherwise
