.TH "acpi_has_method" 9 "acpi_has_method" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_has_method \- Check whether @handle has a method named @name
.SH SYNOPSIS
.B "bool" acpi_has_method
.BI "(acpi_handle handle "  ","
.BI "char *name "  ");"
.SH ARGUMENTS
.IP "handle" 12
ACPI device handle
.IP "name" 12
name of object or method
.SH "DESCRIPTION"
Check whether \fIhandle\fP has a method named \fIname\fP.
