.TH "acpi_lpss_save_ctx" 9 "acpi_lpss_save_ctx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_lpss_save_ctx \- Save the private registers of LPSS device
.SH SYNOPSIS
.B "void" acpi_lpss_save_ctx
.BI "(struct device *dev "  ","
.BI "struct lpss_private_data *pdata "  ");"
.SH ARGUMENTS
.IP "dev" 12
LPSS device
.IP "pdata" 12
pointer to the private data of the LPSS device
.SH "DESCRIPTION"
Most LPSS devices have private registers which may loose their context when
the device is powered down. \fBacpi_lpss_save_ctx\fP saves those registers into
prv_reg_ctx array.
