.TH "acpi_set_irq_model" 9 "acpi_set_irq_model" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_set_irq_model \- Setup the GSI irqdomain information
.SH SYNOPSIS
.B "void" acpi_set_irq_model
.BI "(enum acpi_irq_model_id model "  ","
.BI "struct fwnode_handle *fwnode "  ");"
.SH ARGUMENTS
.IP "model" 12
the value assigned to acpi_irq_model
.IP "fwnode" 12
the irq_domain identifier for mapping and looking up
GSI interrupts
