.TH "acpi_device_fix_up_power" 9 "acpi_device_fix_up_power" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_device_fix_up_power \- Force device with missing _PSC into D0.
.SH SYNOPSIS
.B "int" acpi_device_fix_up_power
.BI "(struct acpi_device *device "  ");"
.SH ARGUMENTS
.IP "device" 12
Device object whose power state is to be fixed up.
.SH "DESCRIPTION"
Devices without power resources and _PSC, but having _PS0 and _PS3 defined,
are assumed to be put into D0 by the BIOS.  However, in some cases that may
not be the case and this function should be used then.
