.TH "ad_disable_collecting_distributing" 9 "ad_disable_collecting_distributing" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ad_disable_collecting_distributing \- disable a port's transmit/receive
.SH SYNOPSIS
.B "void" ad_disable_collecting_distributing
.BI "(struct port *port "  ","
.BI "bool *update_slave_arr "  ");"
.SH ARGUMENTS
.IP "port" 12
the port we're looking at
.IP "update_slave_arr" 12
Does slave array need update?
