.TH "adf_iov_putmsg" 9 "adf_iov_putmsg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
adf_iov_putmsg \- send PF2VF message
.SH SYNOPSIS
.B "int" adf_iov_putmsg
.BI "(struct adf_accel_dev *accel_dev "  ","
.BI "u32 msg "  ","
.BI "u8 vf_nr "  ");"
.SH ARGUMENTS
.IP "accel_dev" 12
Pointer to acceleration device.
.IP "msg" 12
Message to send
.IP "vf_nr" 12
VF number to which the message will be sent
.SH "DESCRIPTION"
Function sends a messge from the PF to a VF
.SH "RETURN"
0 on success, error code otherwise.
