.TH "aemif_get_hw_params" 9 "aemif_get_hw_params" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aemif_get_hw_params \- function to read hw register values
.SH SYNOPSIS
.B "void" aemif_get_hw_params
.BI "(struct platform_device *pdev "  ","
.BI "int csnum "  ");"
.SH ARGUMENTS
.IP "pdev" 12
platform device to read for
.IP "csnum" 12
aemif chip select number
.SH "DESCRIPTION"
This function reads the defaults from the registers and update
the timing values. Required for get/set commands and also for
the case when driver needs to use defaults in hardware.
