.TH "afu_dma_region_destroy" 9 "afu_dma_region_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
afu_dma_region_destroy \- destroy all regions in rbtree
.SH SYNOPSIS
.B "void" afu_dma_region_destroy
.BI "(struct dfl_feature_platform_data *pdata "  ");"
.SH ARGUMENTS
.IP "pdata" 12
feature device platform data
.SH "DESCRIPTION"
Needs to be called with pdata->lock heold.
