.TH "ahci_platform_resume_host" 9 "ahci_platform_resume_host" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ahci_platform_resume_host \- Resume an ahci-platform host
.SH SYNOPSIS
.B "int" ahci_platform_resume_host
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device pointer for the host
.SH "DESCRIPTION"
This function does all the usual steps needed to resume an ahci-platform
host, note any necessary resources (ie clks, phys, etc.)  must be
initialized / enabled before calling this.
.SH "RETURN"
0 on success otherwise a negative error code
