.TH "ahci_platform_enable_clks" 9 "ahci_platform_enable_clks" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ahci_platform_enable_clks \- Enable platform clocks
.SH SYNOPSIS
.B "int" ahci_platform_enable_clks
.BI "(struct ahci_host_priv *hpriv "  ");"
.SH ARGUMENTS
.IP "hpriv" 12
host private area to store config values
.SH "DESCRIPTION"
This function enables all the clks found in hpriv->clks, starting at
index 0. If any clk fails to enable it disables all the clks already
enabled in reverse order, and then returns an error.
.SH "RETURN"
0 on success otherwise a negative error code
