.TH "alarm_timer_try_to_cancel" 9 "alarm_timer_try_to_cancel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alarm_timer_try_to_cancel \- Posix timer callback to cancel a timer
.SH SYNOPSIS
.B "int" alarm_timer_try_to_cancel
.BI "(struct k_itimer *timr "  ");"
.SH ARGUMENTS
.IP "timr" 12
Pointer to the posixtimer data struct
