.TH "alarm_cancel" 9 "alarm_cancel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alarm_cancel \- Spins trying to cancel an alarm timer until it is done
.SH SYNOPSIS
.B "int" alarm_cancel
.BI "(struct alarm *alarm "  ");"
.SH ARGUMENTS
.IP "alarm" 12
ptr to alarm to be canceled
.SH "DESCRIPTION"
Returns 1 if the timer was canceled, 0 if it was not active.
