.TH "alarm_timer_create" 9 "alarm_timer_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alarm_timer_create \- posix timer_create interface
.SH SYNOPSIS
.B "int" alarm_timer_create
.BI "(struct k_itimer *new_timer "  ");"
.SH ARGUMENTS
.IP "new_timer" 12
k_itimer pointer to manage
.SH "DESCRIPTION"
Initializes the k_itimer structure.
