.TH "allocate_cgrp_cset_links" 9 "allocate_cgrp_cset_links" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
allocate_cgrp_cset_links \- allocate cgrp_cset_links
.SH SYNOPSIS
.B "int" allocate_cgrp_cset_links
.BI "(int count "  ","
.BI "struct list_head *tmp_links "  ");"
.SH ARGUMENTS
.IP "count" 12
the number of links to allocate
.IP "tmp_links" 12
list_head the allocated links are put on
.SH "DESCRIPTION"
Allocate \fIcount\fP cgrp_cset_link structures and chain them on \fItmp_links\fP
through ->cset_link.  Returns 0 on success or -errno.
