.TH "alloc_recv_msg" 9 "alloc_recv_msg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alloc_recv_msg \- allocate receive message memory
.SH SYNOPSIS
.B "int" alloc_recv_msg
.BI "(struct hinic_pf_to_mgmt *pf_to_mgmt "  ","
.BI "struct hinic_recv_msg *recv_msg "  ");"
.SH ARGUMENTS
.IP "pf_to_mgmt" 12
PF to MGMT channel
.IP "recv_msg" 12
pointer that will hold the allocated data
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
