.TH "alloc_mem" 9 "alloc_mem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alloc_mem \- allocates the AFU and its command pool
.SH SYNOPSIS
.B "int" alloc_mem
.BI "(struct cxlflash_cfg *cfg "  ");"
.SH ARGUMENTS
.IP "cfg" 12
Internal structure associated with the host.
.SH "DESCRIPTION"
A partially allocated state remains on failure.
.SH "RETURN"
0 on success
-ENOMEM on failure to allocate memory
