.TH "alloc_attributes_data" 9 "alloc_attributes_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alloc_attributes_data \- Allocate attributes data for a particular type
.SH SYNOPSIS
.B "int" alloc_attributes_data
.BI "(int attr_type "  ");"
.SH ARGUMENTS
.IP "attr_type" 12
Attribute type to allocate
