.TH "alloc_msi_entry" 9 "alloc_msi_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alloc_msi_entry \- Allocate an initialize msi_entry
.SH SYNOPSIS
.B "struct msi_desc *" alloc_msi_entry
.BI "(struct device *dev "  ","
.BI "int nvec "  ","
.BI "const struct irq_affinity_desc *affinity "  ");"
.SH ARGUMENTS
.IP "dev" 12
Pointer to the device for which this is allocated
.IP "nvec" 12
The number of vectors used in this entry
.IP "affinity" 12
Optional pointer to an affinity mask array size of \fInvec\fP
.SH "DESCRIPTION"
If \fIaffinity\fP is not NULL then an affinity array[\fInvec\fP] is allocated
and the affinity masks and flags from \fIaffinity\fP are copied.
