.TH "alloc_skb_for_msg" 9 "alloc_skb_for_msg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alloc_skb_for_msg \- allocate sk_buff to wrap frag list forming a msg
.SH SYNOPSIS
.B "struct sk_buff *" alloc_skb_for_msg
.BI "(struct sk_buff *first "  ");"
.SH ARGUMENTS
.IP "first" 12
first sk_buff of the msg
