.TH "altr_i2c_fill_tx_fifo" 9 "altr_i2c_fill_tx_fifo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
altr_i2c_fill_tx_fifo \- Fill TX FIFO from current message buffer.
.SH SYNOPSIS
.B "int" altr_i2c_fill_tx_fifo
.BI "(struct altr_i2c_dev *idev "  ");"
.SH ARGUMENTS
.IP "idev" 12
-- undescribed --
.SH "RETURN"
Number of bytes left to transfer.
