.TH "am33xx_cm_wait_module_idle" 9 "am33xx_cm_wait_module_idle" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
am33xx_cm_wait_module_idle \- wait for a module to be in 'disabled' state
.SH SYNOPSIS
.B "int" am33xx_cm_wait_module_idle
.BI "(u8 part "  ","
.BI "s16 inst "  ","
.BI "u16 clkctrl_offs "  ","
.BI "u8 bit_shift "  ");"
.SH ARGUMENTS
.IP "part" 12
CM partition, ignored for AM33xx
.IP "inst" 12
CM instance register offset (*_INST macro)
.IP "clkctrl_offs" 12
Module clock control register offset (*_CLKCTRL macro)
.IP "bit_shift" 12
bit shift for the register, ignored for AM33xx
.SH "DESCRIPTION"
Wait for the module IDLEST to be disabled. Some PRCM transition,
like reset assertion or parent clock de-activation must wait the
module to be fully disabled.
