.TH "am33xx_cm_is_clkdm_in_hwsup" 9 "am33xx_cm_is_clkdm_in_hwsup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
am33xx_cm_is_clkdm_in_hwsup \- is a clockdomain in hwsup idle mode?
.SH SYNOPSIS
.B "bool" am33xx_cm_is_clkdm_in_hwsup
.BI "(u16 inst "  ","
.BI "u16 cdoffs "  ");"
.SH ARGUMENTS
.IP "inst" 12
CM instance register offset (*_INST macro)
.IP "cdoffs" 12
Clockdomain register offset (*_CDOFFS macro)
.SH "DESCRIPTION"
Returns true if the clockdomain referred to by (\fIinst\fP, \fIcdoffs\fP)
is in hardware-supervised idle mode, or 0 otherwise.
