.TH "amdgpu_fence_wait_polling" 9 "amdgpu_fence_wait_polling" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_fence_wait_polling \- busy wait for givn sequence number
.SH SYNOPSIS
.B "signed long" amdgpu_fence_wait_polling
.BI "(struct amdgpu_ring *ring "  ","
.BI "uint32_t wait_seq "  ","
.BI "signed long timeout "  ");"
.SH ARGUMENTS
.IP "ring" 12
ring index the fence is associated with
.IP "wait_seq" 12
sequence number to wait
.IP "timeout" 12
the timeout for waiting in usecs
.SH "DESCRIPTION"
Wait for all fences on the requested ring to signal (all asics).
Returns left time if no timeout, 0 or minus if timeout.
