.TH "amdgpu_vram_mgr_free_sgt" 9 "amdgpu_vram_mgr_free_sgt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vram_mgr_free_sgt \- allocate and fill a sg table
.SH SYNOPSIS
.B "void" amdgpu_vram_mgr_free_sgt
.BI "(struct amdgpu_device *adev "  ","
.BI "struct device *dev "  ","
.BI "enum dma_data_direction dir "  ","
.BI "struct sg_table *sgt "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu device pointer
.IP "dev" 12
device pointer
.IP "dir" 12
data direction of resource to unmap
.IP "sgt" 12
sg table to free
.SH "DESCRIPTION"
Free a previously allocate sg table.
