.TH "amdgpu_irq_create_mapping" 9 "amdgpu_irq_create_mapping" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_irq_create_mapping \- create mapping between domain Linux IRQs
.SH SYNOPSIS
.B "unsigned" amdgpu_irq_create_mapping
.BI "(struct amdgpu_device *adev "  ","
.BI "unsigned src_id "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu device pointer
.IP "src_id" 12
IH source id
.SH "DESCRIPTION"
Creates mapping between a domain IRQ (GPU IH src id) and a Linux IRQ
Use this for components that generate a GPU interrupt, but are driven
by a different driver (e.g., ACP).
.SH "RETURN"
Linux IRQ
