.TH "amdgpu_gmc_vram_location" 9 "amdgpu_gmc_vram_location" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_gmc_vram_location \- try to find VRAM location
.SH SYNOPSIS
.B "void" amdgpu_gmc_vram_location
.BI "(struct amdgpu_device *adev "  ","
.BI "struct amdgpu_gmc *mc "  ","
.BI "u64 base "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu device structure holding all necessary information
.IP "mc" 12
memory controller structure holding memory information
.IP "base" 12
base address at which to put VRAM
.SH "DESCRIPTION"
Function will try to place VRAM at base address provided
as parameter.
