.TH "amdgpu_fence_wait_empty" 9 "amdgpu_fence_wait_empty" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_fence_wait_empty \- wait for all fences to signal
.SH SYNOPSIS
.B "int" amdgpu_fence_wait_empty
.BI "(struct amdgpu_ring *ring "  ");"
.SH ARGUMENTS
.IP "ring" 12
ring index the fence is associated with
.SH "DESCRIPTION"
Wait for all fences on the requested ring to signal (all asics).
Returns 0 if the fences have passed, error for all other cases.
