.TH "amdgpu_atif_get_notification_params" 9 "amdgpu_atif_get_notification_params" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_atif_get_notification_params \- determine notify configuration
.SH SYNOPSIS
.B "int" amdgpu_atif_get_notification_params
.BI "(struct amdgpu_atif *atif "  ");"
.SH ARGUMENTS
.IP "atif" 12
-- undescribed --
.SH "DESCRIPTION"
Execute the ATIF_FUNCTION_GET_SYSTEM_PARAMETERS ATIF function
to determine if a notifier is used and if so which one
(all asics).  This is either Notify(VGA, 0x81) or Notify(VGA, n)
where n is specified in the result if a notifier is used.
Returns 0 on success, error on failure.
