.TH "amdgpu_verify_access" 9 "amdgpu_verify_access" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_verify_access \- Verify access for a mmap call
.SH SYNOPSIS
.B "int" amdgpu_verify_access
.BI "(struct ttm_buffer_object *bo "  ","
.BI "struct file *filp "  ");"
.SH ARGUMENTS
.IP "bo" 12
The buffer object to map
.IP "filp" 12
The file pointer from the process performing the mmap
.SH "DESCRIPTION"
This is called by \fBttm_bo_mmap\fP to verify whether a process
has the right to mmap a BO to their process space.
