.TH "amdgpu_device_enable_virtual_display" 9 "amdgpu_device_enable_virtual_display" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_device_enable_virtual_display \- enable virtual display feature
.SH SYNOPSIS
.B "void" amdgpu_device_enable_virtual_display
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Enabled the virtual display feature if the user has enabled it via
the module parameter virtual_display.  This feature provides a virtual
display hardware on headless boards or in virtualized environments.
This function parses and validates the configuration string specified by
the user and configues the virtual display configuration (number of
virtual connectors, crtcs, etc.) specified.
