.TH "amdgpu_atpx_switchto" 9 "amdgpu_atpx_switchto" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_atpx_switchto \- switch to the requested GPU
.SH SYNOPSIS
.B "int" amdgpu_atpx_switchto
.BI "(enum vga_switcheroo_client_id id "  ");"
.SH ARGUMENTS
.IP "id" 12
GPU to switch to
.SH "DESCRIPTION"
Execute the necessary ATPX functions to switch between the discrete GPU and
integrated GPU (all asics).
Returns 0 on success, error on failure.
