.TH "amdgpu_device_suspend" 9 "amdgpu_device_suspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_device_suspend \- initiate device suspend
.SH SYNOPSIS
.B "int" amdgpu_device_suspend
.BI "(struct drm_device *dev "  ","
.BI "bool fbcon "  ");"
.SH ARGUMENTS
.IP "dev" 12
drm dev pointer
.IP "fbcon" 12
notify the fbdev of suspend
.SH "DESCRIPTION"
Puts the hw in the suspend state (all asics).
Returns 0 for success or an error on failure.
Called at driver suspend.
