.TH "amdgpu_bo_init" 9 "amdgpu_bo_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_bo_init \- initialize memory manager
.SH SYNOPSIS
.B "int" amdgpu_bo_init
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu device object
.SH "DESCRIPTION"
Calls \fBamdgpu_ttm_init\fP to initialize amdgpu memory manager.
.SH "RETURN"
0 for success or a negative error code on failure.
