.TH "amdgpu_gtt_mgr_debug" 9 "amdgpu_gtt_mgr_debug" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_gtt_mgr_debug \- dump VRAM table
.SH SYNOPSIS
.B "void" amdgpu_gtt_mgr_debug
.BI "(struct ttm_resource_manager *man "  ","
.BI "struct drm_printer *printer "  ");"
.SH ARGUMENTS
.IP "man" 12
TTM memory type manager
.IP "printer" 12
DRM printer to use
.SH "DESCRIPTION"
Dump the table content using printk.
