.TH "amdgpu_irq_handler" 9 "amdgpu_irq_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_irq_handler \- IRQ handler
.SH SYNOPSIS
.B "irqreturn_t" amdgpu_irq_handler
.BI "(int irq "  ","
.BI "void *arg "  ");"
.SH ARGUMENTS
.IP "irq" 12
IRQ number (unused)
.IP "arg" 12
pointer to DRM device
.SH "DESCRIPTION"
IRQ handler for amdgpu driver (all ASICs).
.SH "RETURN"
result of handling the IRQ, as defined by \fIirqreturn_t\fP
