.TH "amdgpu_bo_create_reserved" 9 "amdgpu_bo_create_reserved" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_bo_create_reserved \- create reserved BO for kernel use
.SH SYNOPSIS
.B "int" amdgpu_bo_create_reserved
.BI "(struct amdgpu_device *adev "  ","
.BI "unsigned long size "  ","
.BI "int align "  ","
.BI "u32 domain "  ","
.BI "struct amdgpu_bo **bo_ptr "  ","
.BI "u64 *gpu_addr "  ","
.BI "void **cpu_addr "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu device object
.IP "size" 12
size for the new BO
.IP "align" 12
alignment for the new BO
.IP "domain" 12
where to place it
.IP "bo_ptr" 12
used to initialize BOs in structures
.IP "gpu_addr" 12
GPU addr of the pinned BO
.IP "cpu_addr" 12
optional CPU address mapping
.SH "DESCRIPTION"
Allocates and pins a BO for kernel internal use, and returns it still
reserved.
.SH "NOTE"
For bo_ptr new BO is only created if bo_ptr points to NULL.
.SH "RETURN"
0 on success, negative error code otherwise.
