.TH "amdgpu_vm_handle_moved" 9 "amdgpu_vm_handle_moved" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vm_handle_moved \- handle moved BOs in the PT
.SH SYNOPSIS
.B "int" amdgpu_vm_handle_moved
.BI "(struct amdgpu_device *adev "  ","
.BI "struct amdgpu_vm *vm "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.IP "vm" 12
requested vm
.SH "DESCRIPTION"
Make sure all BOs which are moved are updated in the PTs.

PTs have to be reserved!
.SH "RETURN"
0 for success.
