.TH "amdgpu_vce_ring_emit_fence" 9 "amdgpu_vce_ring_emit_fence" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vce_ring_emit_fence \- add a fence command to the ring
.SH SYNOPSIS
.B "void" amdgpu_vce_ring_emit_fence
.BI "(struct amdgpu_ring *ring "  ","
.BI "u64 addr "  ","
.BI "u64 seq "  ","
.BI "unsigned flags "  ");"
.SH ARGUMENTS
.IP "ring" 12
engine to use
.IP "addr" 12
address
.IP "seq" 12
sequence number
.IP "flags" 12
fence related flags
