.TH "amdtp_stream_set_parameters" 9 "amdtp_stream_set_parameters" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdtp_stream_set_parameters \- set stream parameters
.SH SYNOPSIS
.B "int" amdtp_stream_set_parameters
.BI "(struct amdtp_stream *s "  ","
.BI "unsigned int rate "  ","
.BI "unsigned int data_block_quadlets "  ");"
.SH ARGUMENTS
.IP "s" 12
the AMDTP stream to configure
.IP "rate" 12
the sample rate
.IP "data_block_quadlets" 12
the size of a data block in quadlet unit
.SH "DESCRIPTION"
The parameters must be set before the stream is started, and must not be
changed while the stream is running.
