.TH "amdtp_am824_set_pcm_position" 9 "amdtp_am824_set_pcm_position" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdtp_am824_set_pcm_position \- set an index of data channel for a channel of PCM frame
.SH SYNOPSIS
.B "void" amdtp_am824_set_pcm_position
.BI "(struct amdtp_stream *s "  ","
.BI "unsigned int index "  ","
.BI "unsigned int position "  ");"
.SH ARGUMENTS
.IP "s" 12
the AMDTP stream
.IP "index" 12
the index of data channel in an data block
.IP "position" 12
the channel of PCM frame
