.TH "ap_sm_setirq_wait" 9 "ap_sm_setirq_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ap_sm_setirq_wait \- Test queue for completion of the irq enablement
.SH SYNOPSIS
.B "enum ap_sm_wait" ap_sm_setirq_wait
.BI "(struct ap_queue *aq "  ");"
.SH ARGUMENTS
.IP "aq" 12
pointer to the AP queue
.SH "DESCRIPTION"
Returns AP_POLL_IMMEDIATELY, AP_POLL_AFTER_TIMEROUT or 0.
