.TH "apm_do_idle" 9 "apm_do_idle" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
apm_do_idle \- perform power saving
.SH SYNOPSIS
.B "int" apm_do_idle
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This function notifies the BIOS that the processor is (in the view
of the OS) idle. It returns -1 in the event that the BIOS refuses
to handle the idle request. On a success the function returns 1
if the BIOS did clock slowing or 0 otherwise.
