.TH "apm_queue_event" 9 "apm_queue_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
apm_queue_event \- queue an APM event for kapmd
.SH SYNOPSIS
.B "void" apm_queue_event
.BI "(apm_event_t event "  ");"
.SH ARGUMENTS
.IP "event" 12
APM event
.SH "DESCRIPTION"
Queue an APM event for kapmd to process and ultimately take the
appropriate action.  Only a subset of events are handled:
APM_LOW_BATTERY
APM_POWER_STATUS_CHANGE
APM_USER_SUSPEND
APM_SYS_SUSPEND
APM_CRITICAL_SUSPEND
