.TH "apm_engage_power_management" 9 "apm_engage_power_management" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
apm_engage_power_management \- enable PM on a device
.SH SYNOPSIS
.B "int" apm_engage_power_management
.BI "(u_short device "  ","
.BI "int enable "  ");"
.SH ARGUMENTS
.IP "device" 12
identity of device
.IP "enable" 12
on/off

Activate or deactivate power management on either a specific device
or the entire system (APM_DEVICE_ALL).
