.TH "arc_emac_set_rx_mode" 9 "arc_emac_set_rx_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
arc_emac_set_rx_mode \- Change the receive filtering mode.
.SH SYNOPSIS
.B "void" arc_emac_set_rx_mode
.BI "(struct net_device *ndev "  ");"
.SH ARGUMENTS
.IP "ndev" 12
Pointer to the network device.
.SH "DESCRIPTION"
This function enables/disables promiscuous or all-multicast mode
and updates the multicast filtering list of the network device.
