.TH "arc_emac_tx" 9 "arc_emac_tx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
arc_emac_tx \- Starts the data transmission.
.SH SYNOPSIS
.B "netdev_tx_t" arc_emac_tx
.BI "(struct sk_buff *skb "  ","
.BI "struct net_device *ndev "  ");"
.SH ARGUMENTS
.IP "skb" 12
sk_buff pointer that contains data to be Transmitted.
.IP "ndev" 12
Pointer to net_device structure.
.SH "RETURN"
NETDEV_TX_OK, on success
NETDEV_TX_BUSY, if any of the descriptors are not free.
.SH "DESCRIPTION"
This function is invoked from upper layers to initiate transmission.
