.TH "arc_emac_set_address" 9 "arc_emac_set_address" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
arc_emac_set_address \- Set the MAC address for this device.
.SH SYNOPSIS
.B "int" arc_emac_set_address
.BI "(struct net_device *ndev "  ","
.BI "void *p "  ");"
.SH ARGUMENTS
.IP "ndev" 12
Pointer to net_device structure.
.IP "p" 12
6 byte Address to be written as MAC address.
.SH "DESCRIPTION"
This function copies the HW address from the sockaddr structure to the
net_device structure and updates the address in HW.
.SH "RETURN"
-EBUSY if the net device is busy or 0 if the address is set
successfully.
