.TH "arch_uprobe_analyze_insn" 9 "arch_uprobe_analyze_insn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
arch_uprobe_analyze_insn \- instruction analysis including validity and fixups.
.SH SYNOPSIS
.B "int" arch_uprobe_analyze_insn
.BI "(struct arch_uprobe *auprobe "  ","
.BI "struct mm_struct *mm "  ","
.BI "unsigned long addr "  ");"
.SH ARGUMENTS
.IP "auprobe" 12
the probepoint information.
.IP "mm" 12
the probed address space.
.IP "addr" 12
virtual address at which to install the probepoint
Return 0 on success or a -ve number on error.
