.TH "arm_coherent_iommu_unmap_page" 9 "arm_coherent_iommu_unmap_page" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
arm_coherent_iommu_unmap_page \- 
.SH SYNOPSIS
.B "void" arm_coherent_iommu_unmap_page
.BI "(struct device *dev "  ","
.BI "dma_addr_t handle "  ","
.BI "size_t size "  ","
.BI "enum dma_data_direction dir "  ","
.BI "unsigned long attrs "  ");"
.SH ARGUMENTS
.IP "dev" 12
valid struct device pointer
.IP "handle" 12
DMA address of buffer
.IP "size" 12
size of buffer (same as passed to dma_map_page)
.IP "dir" 12
DMA transfer direction (same as passed to dma_map_page)
.IP "attrs" 12
-- undescribed --
.SH "DESCRIPTION"
Coherent IOMMU aware version of \fBarm_dma_unmap_page\fP
