.TH "as3645a_set_control" 9 "as3645a_set_control" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
as3645a_set_control \- Set flash control register
.SH SYNOPSIS
.B "int" as3645a_set_control
.BI "(struct as3645a *flash "  ","
.BI "enum as_mode mode "  ","
.BI "bool on "  ");"
.SH ARGUMENTS
.IP "flash" 12
The flash
.IP "mode" 12
Desired output mode
.IP "on" 12
Desired output state
.SH "DESCRIPTION"
Configure the hardware with output mode and state.

Return 0 on success, or a negative error code if an I2C communication error
occurred.
