.TH "asd_verify_flash_seg" 9 "asd_verify_flash_seg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
asd_verify_flash_seg \- verify data with flash memory
.SH SYNOPSIS
.B "int" asd_verify_flash_seg
.BI "(struct asd_ha_struct *asd_ha "  ","
.BI "const void *src "  ","
.BI "u32 dest_offset "  ","
.BI "u32 bytes_to_verify "  ");"
.SH ARGUMENTS
.IP "asd_ha" 12
pointer to the host adapter structure
.IP "src" 12
pointer to the source data to be verified
.IP "dest_offset" 12
offset from flash memory
.IP "bytes_to_verify" 12
total bytes to verify
