.TH "assign_aeb_to_av" 9 "assign_aeb_to_av" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
assign_aeb_to_av \- assigns a SEB to a given ainf_volume and removes it from it's original list.
.SH SYNOPSIS
.B "void" assign_aeb_to_av
.BI "(struct ubi_attach_info *ai "  ","
.BI "struct ubi_ainf_peb *aeb "  ","
.BI "struct ubi_ainf_volume *av "  ");"
.SH ARGUMENTS
.IP "ai" 12
ubi_attach_info object
.IP "aeb" 12
the to be assigned SEB
.IP "av" 12
target scan volume
