.TH "ata_host_register" 9 "ata_host_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_host_register \- register initialized ATA host
.SH SYNOPSIS
.B "int" ata_host_register
.BI "(struct ata_host *host "  ","
.BI "struct scsi_host_template *sht "  ");"
.SH ARGUMENTS
.IP "host" 12
ATA host to register
.IP "sht" 12
template for SCSI host

Register initialized ATA host.  \fIhost\fP is allocated using
\fBata_host_alloc\fP and fully initialized by LLD.  This function
starts ports, registers \fIhost\fP with ATA and SCSI layers and
probe registered devices.

LOCKING:
Inherited from calling layer (may sleep).
.SH "RETURN"
0 on success, -errno otherwise.
