.TH "ata_bmdma_qc_prep" 9 "ata_bmdma_qc_prep" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_bmdma_qc_prep \- Prepare taskfile for submission
.SH SYNOPSIS
.B "enum ata_completion_errors" ata_bmdma_qc_prep
.BI "(struct ata_queued_cmd *qc "  ");"
.SH ARGUMENTS
.IP "qc" 12
Metadata associated with taskfile to be prepared

Prepare ATA taskfile for submission.

LOCKING:
spin_lock_irqsave(host lock)
