.TH "ata_task_ioctl" 9 "ata_task_ioctl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_task_ioctl \- Handler for HDIO_DRIVE_TASK ioctl
.SH SYNOPSIS
.B "int" ata_task_ioctl
.BI "(struct scsi_device *scsidev "  ","
.BI "void __user *arg "  ");"
.SH ARGUMENTS
.IP "scsidev" 12
Device to which we are issuing command
.IP "arg" 12
User provided data for issuing command

LOCKING:
Defined by the SCSI layer.  We don't really care.
.SH "RETURN"
Zero on success, negative errno on error.
