.TH "ata_scsiop_inq_std" 9 "ata_scsiop_inq_std" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_scsiop_inq_std \- Simulate INQUIRY command
.SH SYNOPSIS
.B "unsigned int" ata_scsiop_inq_std
.BI "(struct ata_scsi_args *args "  ","
.BI "u8 *rbuf "  ");"
.SH ARGUMENTS
.IP "args" 12
device IDENTIFY data / SCSI command of interest.
.IP "rbuf" 12
Response buffer, to which simulated SCSI cmd output is sent.

Returns standard device identification data associated
with non-VPD INQUIRY command output.

LOCKING:
spin_lock_irqsave(host lock)
