.TH "ata_sff_dma_pause" 9 "ata_sff_dma_pause" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_sff_dma_pause \- Pause before commencing DMA
.SH SYNOPSIS
.B "void" ata_sff_dma_pause
.BI "(struct ata_port *ap "  ");"
.SH ARGUMENTS
.IP "ap" 12
Port to pause for.

Perform I/O fencing and ensure sufficient cycle delays occur
for the HDMA1:0 transition
