.TH "ata_scsi_report_zones_complete" 9 "ata_scsi_report_zones_complete" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_scsi_report_zones_complete \- convert ATA output
.SH SYNOPSIS
.B "void" ata_scsi_report_zones_complete
.BI "(struct ata_queued_cmd *qc "  ");"
.SH ARGUMENTS
.IP "qc" 12
command structure returning the data

Convert T-13 little-endian field representation into
T-10 big-endian field representation.
What a mess.
