.TH "ata_gen_ata_sense" 9 "ata_gen_ata_sense" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_gen_ata_sense \- generate a SCSI fixed sense block
.SH SYNOPSIS
.B "void" ata_gen_ata_sense
.BI "(struct ata_queued_cmd *qc "  ");"
.SH ARGUMENTS
.IP "qc" 12
Command that we are erroring out

Generate sense block for a failed ATA command \fIqc\fP.  Descriptor
format is used to accommodate LBA48 block address.

LOCKING:
None.
