.TH "ata_scsiop_maint_in" 9 "ata_scsiop_maint_in" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_scsiop_maint_in \- Simulate a subset of MAINTENANCE_IN
.SH SYNOPSIS
.B "unsigned int" ata_scsiop_maint_in
.BI "(struct ata_scsi_args *args "  ","
.BI "u8 *rbuf "  ");"
.SH ARGUMENTS
.IP "args" 12
device MAINTENANCE_IN data / SCSI command of interest.
.IP "rbuf" 12
Response buffer, to which simulated SCSI cmd output is sent.

Yields a subset to satisfy \fBscsi_report_opcode\fP

LOCKING:
spin_lock_irqsave(host lock)
