.TH "ata_acpi_gtm" 9 "ata_acpi_gtm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_acpi_gtm \- execute _GTM
.SH SYNOPSIS
.B "int" ata_acpi_gtm
.BI "(struct ata_port *ap "  ","
.BI "struct ata_acpi_gtm *gtm "  ");"
.SH ARGUMENTS
.IP "ap" 12
target ATA port
.IP "gtm" 12
out parameter for _GTM result
.SH "DESCRIPTION"
Evaluate _GTM and store the result in \fIgtm\fP.

LOCKING:
EH context.
.SH "RETURN"
0 on success, -ENOENT if _GTM doesn't exist, -errno on failure.
