.TH "ata_sff_irq_on" 9 "ata_sff_irq_on" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_sff_irq_on \- Enable interrupts on a port.
.SH SYNOPSIS
.B "void" ata_sff_irq_on
.BI "(struct ata_port *ap "  ");"
.SH ARGUMENTS
.IP "ap" 12
Port on which interrupts are enabled.

Enable interrupts on a legacy IDE device using MMIO or PIO,
wait for idle, clear any pending interrupts.
.SH "NOTE"
may NOT be used as the \fBsff_irq_on\fP entry in
ata_port_operations.

LOCKING:
Inherited from caller.
