.TH "ata_eh_done" 9 "ata_eh_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_eh_done \- EH action complete
.SH SYNOPSIS
.B "void" ata_eh_done
.BI "(struct ata_link *link "  ","
.BI "struct ata_device *dev "  ","
.BI "unsigned int action "  ");"
.SH ARGUMENTS
.IP "link" 12
ATA link for which EH actions are complete
.IP "dev" 12
target ATA dev for per-dev action (can be NULL)
.IP "action" 12
action just completed

Called right after performing EH actions to clear related bits
in \fIlink->eh_context\fP.

LOCKING:
None.
