.TH "ata_scsiop_inq_80" 9 "ata_scsiop_inq_80" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_scsiop_inq_80 \- Simulate INQUIRY VPD page 80, device serial number
.SH SYNOPSIS
.B "unsigned int" ata_scsiop_inq_80
.BI "(struct ata_scsi_args *args "  ","
.BI "u8 *rbuf "  ");"
.SH ARGUMENTS
.IP "args" 12
device IDENTIFY data / SCSI command of interest.
.IP "rbuf" 12
Response buffer, to which simulated SCSI cmd output is sent.

Returns ATA device serial number.

LOCKING:
spin_lock_irqsave(host lock)
