.TH "ata_dev_reread_id" 9 "ata_dev_reread_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_dev_reread_id \- Re-read IDENTIFY data
.SH SYNOPSIS
.B "int" ata_dev_reread_id
.BI "(struct ata_device *dev "  ","
.BI "unsigned int readid_flags "  ");"
.SH ARGUMENTS
.IP "dev" 12
target ATA device
.IP "readid_flags" 12
read ID flags

Re-read IDENTIFY page and make sure \fIdev\fP is still attached to
the port.

LOCKING:
Kernel thread context (may sleep)
.SH "RETURN"
0 on success, negative errno otherwise
