.TH "ata_port_detach" 9 "ata_port_detach" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_port_detach \- Detach ATA port in preparation of device removal
.SH SYNOPSIS
.B "void" ata_port_detach
.BI "(struct ata_port *ap "  ");"
.SH ARGUMENTS
.IP "ap" 12
ATA port to be detached

Detach all ATA devices and the associated SCSI devices of \fIap\fP;
then, remove the associated SCSI host.  \fIap\fP is guaranteed to
be quiescent on return from this function.

LOCKING:
Kernel thread context (may sleep).
