.TH "ata_bmdma_post_internal_cmd" 9 "ata_bmdma_post_internal_cmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_bmdma_post_internal_cmd \- Stock post_internal_cmd for BMDMA
.SH SYNOPSIS
.B "void" ata_bmdma_post_internal_cmd
.BI "(struct ata_queued_cmd *qc "  ");"
.SH ARGUMENTS
.IP "qc" 12
internal command to clean up

LOCKING:
Kernel thread context (may sleep)
