.TH "ata_port_freeze" 9 "ata_port_freeze" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_port_freeze \- abort & freeze port
.SH SYNOPSIS
.B "int" ata_port_freeze
.BI "(struct ata_port *ap "  ");"
.SH ARGUMENTS
.IP "ap" 12
ATA port to freeze

Abort and freeze \fIap\fP.  The freeze operation must be called
first, because some hardware requires special operations
before the taskfile registers are accessible.

LOCKING:
spin_lock_irqsave(host lock)
.SH "RETURN"
Number of aborted commands.
