.TH "ata_eh_autopsy" 9 "ata_eh_autopsy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_eh_autopsy \- analyze error and determine recovery action
.SH SYNOPSIS
.B "void" ata_eh_autopsy
.BI "(struct ata_port *ap "  ");"
.SH ARGUMENTS
.IP "ap" 12
host port to perform autopsy on

Analyze all links of \fIap\fP and determine why they failed and
which recovery actions are needed.

LOCKING:
Kernel thread context (may sleep).
