.TH "ata_dev_same_device" 9 "ata_dev_same_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_dev_same_device \- Determine whether new ID matches configured device
.SH SYNOPSIS
.B "int" ata_dev_same_device
.BI "(struct ata_device *dev "  ","
.BI "unsigned int new_class "  ","
.BI "const u16 *new_id "  ");"
.SH ARGUMENTS
.IP "dev" 12
device to compare against
.IP "new_class" 12
class of the new device
.IP "new_id" 12
IDENTIFY page of the new device

Compare \fInew_class\fP and \fInew_id\fP against \fIdev\fP and determine
whether \fIdev\fP is the device indicated by \fInew_class\fP and
\fInew_id\fP.

LOCKING:
None.
.SH "RETURN"
1 if \fIdev\fP matches \fInew_class\fP and \fInew_id\fP, 0 otherwise.
