.TH "ata_sff_std_ports" 9 "ata_sff_std_ports" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_sff_std_ports \- initialize ioaddr with standard port offsets.
.SH SYNOPSIS
.B "void" ata_sff_std_ports
.BI "(struct ata_ioports *ioaddr "  ");"
.SH ARGUMENTS
.IP "ioaddr" 12
IO address structure to be initialized

Utility function which initializes data_addr, error_addr,
feature_addr, nsect_addr, lbal_addr, lbam_addr, lbah_addr,
device_addr, status_addr, and command_addr to standard offsets
relative to cmd_addr.

Does not set ctl_addr, altstatus_addr, bmdma_addr, or scr_addr.
