.TH "atc_calc_bytes_left" 9 "atc_calc_bytes_left" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
atc_calc_bytes_left \- calculates the number of bytes left according to the value read from CTRLA.
.SH SYNOPSIS
.B "int" atc_calc_bytes_left
.BI "(int current_len "  ","
.BI "u32 ctrla "  ");"
.SH ARGUMENTS
.IP "current_len" 12
the number of bytes left before reading CTRLA
.IP "ctrla" 12
the value of CTRLA
