.TH "ath5k_hw_set_ledstate" 9 "ath5k_hw_set_ledstate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath5k_hw_set_ledstate \- Set led state
.SH SYNOPSIS
.B "void" ath5k_hw_set_ledstate
.BI "(struct ath5k_hw *ah "  ","
.BI "unsigned int state "  ");"
.SH ARGUMENTS
.IP "ah" 12
The \fIstruct ath5k_hw\fP
.IP "state" 12
One of AR5K_LED_*
.SH "DESCRIPTION"
Used to set the LED blinking state. This only
works for the LED connected to the LED_0, LED_1 pins,
not the GPIO based.
