.TH "ath5k_hw_get_default_sifs" 9 "ath5k_hw_get_default_sifs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath5k_hw_get_default_sifs \- Get the default SIFS for current mode
.SH SYNOPSIS
.B "unsigned int" ath5k_hw_get_default_sifs
.BI "(struct ath5k_hw *ah "  ");"
.SH ARGUMENTS
.IP "ah" 12
The \fIstruct ath5k_hw\fP
