.TH "ath5k_hw_wisoc_reset" 9 "ath5k_hw_wisoc_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath5k_hw_wisoc_reset \- Reset AHB chipset
.SH SYNOPSIS
.B "int" ath5k_hw_wisoc_reset
.BI "(struct ath5k_hw *ah "  ","
.BI "u32 flags "  ");"
.SH ARGUMENTS
.IP "ah" 12
The \fIstruct ath5k_hw\fP
.IP "flags" 12
Mask to indicate what units to reset
.SH "DESCRIPTION"
Same as ath5k_hw_nic_reset but for AHB based devices

Returns 0 if we are O.K. or -EAGAIN (from athk5_hw_register_timeout)
