.TH "ath5k_hw_clocktoh" 9 "ath5k_hw_clocktoh" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath5k_hw_clocktoh \- Translate hw clock units to usec
.SH SYNOPSIS
.B "unsigned int" ath5k_hw_clocktoh
.BI "(struct ath5k_hw *ah "  ","
.BI "unsigned int clock "  ");"
.SH ARGUMENTS
.IP "ah" 12
The \fIstruct ath5k_hw\fP
.IP "clock" 12
value in hw clock units
.SH "DESCRIPTION"
Translate hw clock units to usecs based on the current
hw clock rate.

Returns number of usecs
