.TH "ath_dynack_get_sifs" 9 "ath_dynack_get_sifs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath_dynack_get_sifs \- get sifs time based on phy used
.SH SYNOPSIS
.B "u32" ath_dynack_get_sifs
.BI "(struct ath_hw *ah "  ","
.BI "int phy "  ");"
.SH ARGUMENTS
.IP "ah" 12
ath hw
.IP "phy" 12
phy used
