.TH "atime_needs_update" 9 "atime_needs_update" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
atime_needs_update \- update the access time
.SH SYNOPSIS
.B "bool" atime_needs_update
.BI "(const struct path *path "  ","
.BI "struct inode *inode "  ");"
.SH ARGUMENTS
.IP "path" 12
the \fIstruct path\fP to update
.IP "inode" 12
inode to update

Update the accessed time on an inode and mark it for writeback.
This function automatically handles read only file systems and media,
as well as the "noatime" flag and inode specific "noatime" markers.
