.TH "attach_node_and_children" 9 "attach_node_and_children" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
attach_node_and_children \- attaches nodes and its children to live tree. CAUTION: misleading function name - if node @np already exists in the live tree then children of @np are *not* attached to the live tree. This works for the current test devicetree nodes because such nodes do not have child nodes.
.SH SYNOPSIS
.B "void" attach_node_and_children
.BI "(struct device_node *np "  ");"
.SH ARGUMENTS
.IP "np" 12
Node to attach to live tree
