.TH "attach_entity_load_avg" 9 "attach_entity_load_avg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
attach_entity_load_avg \- attach this entity to its cfs_rq load avg
.SH SYNOPSIS
.B "void" attach_entity_load_avg
.BI "(struct cfs_rq *cfs_rq "  ","
.BI "struct sched_entity *se "  ");"
.SH ARGUMENTS
.IP "cfs_rq" 12
cfs_rq to attach to
.IP "se" 12
sched_entity to attach
.SH "DESCRIPTION"
Must call \fBupdate_cfs_rq_load_avg\fP before this, since we rely on
cfs_rq->avg.last_update_time being current.
