.TH "audit_cb" 9 "audit_cb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
audit_cb \- call back for mount specific audit fields
.SH SYNOPSIS
.B "void" audit_cb
.BI "(struct audit_buffer *ab "  ","
.BI "void *va "  ");"
.SH ARGUMENTS
.IP "ab" 12
audit_buffer  (NOT NULL)
.IP "va" 12
audit struct to audit values of  (NOT NULL)
