.TH "audit_compare_dname_path" 9 "audit_compare_dname_path" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
audit_compare_dname_path \- compare given dentry name with last component in given path. Return of 0 indicates a match.
.SH SYNOPSIS
.B "int" audit_compare_dname_path
.BI "(const struct qstr *dname "  ","
.BI "const char *path "  ","
.BI "int parentlen "  ");"
.SH ARGUMENTS
.IP "dname" 12
dentry name that we're comparing
.IP "path" 12
full pathname that we're comparing
.IP "parentlen" 12
length of the parent if known. Passing in AUDIT_NAME_FULL
here indicates that we must compute this value.
