.TH "bam_slave_config" 9 "bam_slave_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bam_slave_config \- set slave configuration for channel
.SH SYNOPSIS
.B "int" bam_slave_config
.BI "(struct dma_chan *chan "  ","
.BI "struct dma_slave_config *cfg "  ");"
.SH ARGUMENTS
.IP "chan" 12
dma channel
.IP "cfg" 12
slave configuration
.SH "DESCRIPTION"
Sets slave configuration for channel
