.TH "bank_is_io" 9 "bank_is_io" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bank_is_io \- test whether bank is used for IO
.SH SYNOPSIS
.B "int" bank_is_io
.BI "(unsigned long bankcon "  ");"
.SH ARGUMENTS
.IP "bankcon" 12
The bank control register.
.SH "DESCRIPTION"
This is a simplistic test to see if any BANKCON[x] is not an IO
bank. It currently does not take into account whether BWSCON has
an illegal width-setting in it, or if the pin connected to nCS[x]
is actually being handled as a chip-select.
