.TH "batadv_v_ogm_queue_on_if" 9 "batadv_v_ogm_queue_on_if" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_v_ogm_queue_on_if \- queue a batman ogm on a given interface
.SH SYNOPSIS
.B "void" batadv_v_ogm_queue_on_if
.BI "(struct sk_buff *skb "  ","
.BI "struct batadv_hard_iface *hard_iface "  ");"
.SH ARGUMENTS
.IP "skb" 12
the OGM to queue
.IP "hard_iface" 12
the interface to queue the OGM on
