.TH "batadv_tt_req_node_release" 9 "batadv_tt_req_node_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_tt_req_node_release \- free tt_req node entry
.SH SYNOPSIS
.B "void" batadv_tt_req_node_release
.BI "(struct kref *ref "  ");"
.SH ARGUMENTS
.IP "ref" 12
kref pointer of the tt req_node entry
