.TH "batadv_v_gw_is_eligible" 9 "batadv_v_gw_is_eligible" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_v_gw_is_eligible \- check if a originator would be selected as GW
.SH SYNOPSIS
.B "bool" batadv_v_gw_is_eligible
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct batadv_orig_node *curr_gw_orig "  ","
.BI "struct batadv_orig_node *orig_node "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "curr_gw_orig" 12
originator representing the currently selected GW
.IP "orig_node" 12
the originator representing the new candidate
.SH "RETURN"
true if orig_node can be selected as current GW, false otherwise
