.TH "batadv_bla_is_backbone_gw_orig" 9 "batadv_bla_is_backbone_gw_orig" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_bla_is_backbone_gw_orig \- Check if the originator is a gateway for the VLAN identified by vid.
.SH SYNOPSIS
.B "bool" batadv_bla_is_backbone_gw_orig
.BI "(struct batadv_priv *bat_priv "  ","
.BI "u8 *orig "  ","
.BI "unsigned short vid "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "orig" 12
originator mac address
.IP "vid" 12
VLAN identifier
.SH "RETURN"
true if orig is a backbone for this vid, false otherwise.
