.TH "batadv_bla_send_claim" 9 "batadv_bla_send_claim" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_bla_send_claim \- sends a claim frame according to the provided info
.SH SYNOPSIS
.B "void" batadv_bla_send_claim
.BI "(struct batadv_priv *bat_priv "  ","
.BI "u8 *mac "  ","
.BI "unsigned short vid "  ","
.BI "int claimtype "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "mac" 12
the mac address to be announced within the claim
.IP "vid" 12
the VLAN ID
.IP "claimtype" 12
the type of the claim (CLAIM, UNCLAIM, ANNOUNCE, ...)
