.TH "batadv_mcast_mla_tt_add" 9 "batadv_mcast_mla_tt_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_mcast_mla_tt_add \- add multicast listener announcements
.SH SYNOPSIS
.B "void" batadv_mcast_mla_tt_add
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct hlist_head *mcast_list "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "mcast_list" 12
a list of addresses which are going to get added
.SH "DESCRIPTION"
Adds multicast listener announcements from the given mcast_list to the
translation table if they have not been added yet.
