.TH "batadv_mcast_forw_tt_node_get" 9 "batadv_mcast_forw_tt_node_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_mcast_forw_tt_node_get \- get a multicast tt node
.SH SYNOPSIS
.B "struct batadv_orig_node *" batadv_mcast_forw_tt_node_get
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct ethhdr *ethhdr "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "ethhdr" 12
the ether header containing the multicast destination
.SH "RETURN"
an orig_node matching the multicast address provided by ethhdr
via a translation table lookup. This increases the returned nodes refcount.
