.TH "batadv_is_orig_node_eligible" 9 "batadv_is_orig_node_eligible" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_is_orig_node_eligible \- check whether a node can be a DHT candidate
.SH SYNOPSIS
.B "bool" batadv_is_orig_node_eligible
.BI "(struct batadv_dat_candidate *res "  ","
.BI "int select "  ","
.BI "batadv_dat_addr_t tmp_max "  ","
.BI "batadv_dat_addr_t max "  ","
.BI "batadv_dat_addr_t last_max "  ","
.BI "struct batadv_orig_node *candidate "  ","
.BI "struct batadv_orig_node *max_orig_node "  ");"
.SH ARGUMENTS
.IP "res" 12
the array with the already selected candidates
.IP "select" 12
number of already selected candidates
.IP "tmp_max" 12
address of the currently evaluated node
.IP "max" 12
current round max address
.IP "last_max" 12
address of the last selected candidate
.IP "candidate" 12
orig_node under evaluation
.IP "max_orig_node" 12
last selected candidate
.SH "RETURN"
true if the node has been elected as next candidate or false
otherwise.
