.TH "batadv_gw_node_put" 9 "batadv_gw_node_put" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_gw_node_put \- decrement the gw_node refcounter and possibly release it
.SH SYNOPSIS
.B "void" batadv_gw_node_put
.BI "(struct batadv_gw_node *gw_node "  ");"
.SH ARGUMENTS
.IP "gw_node" 12
gateway node to free
