.TH "batadv_transtable_best_orig" 9 "batadv_transtable_best_orig" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_transtable_best_orig \- Get best originator list entry from tt entry
.SH SYNOPSIS
.B "struct batadv_tt_orig_list_entry *" batadv_transtable_best_orig
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct batadv_tt_global_entry *tt_global_entry "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "tt_global_entry" 12
global translation table entry to be analyzed
.SH "DESCRIPTION"
This function assumes the caller holds \fBrcu_read_lock\fP.
.SH "RETURN"
best originator list entry or NULL on errors.
