.TH "batadv_tp_sender_shutdown" 9 "batadv_tp_sender_shutdown" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_tp_sender_shutdown \- let sender thread/timer stop gracefully
.SH SYNOPSIS
.B "void" batadv_tp_sender_shutdown
.BI "(struct batadv_tp_vars *tp_vars "  ","
.BI "enum batadv_tp_meter_reason reason "  ");"
.SH ARGUMENTS
.IP "tp_vars" 12
the private data of the current TP meter session
.IP "reason" 12
reason for tp meter session stop
