.TH "batadv_mcast_forw_want_all_ip_count" 9 "batadv_mcast_forw_want_all_ip_count" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_mcast_forw_want_all_ip_count \- count nodes with unspecific mcast interest
.SH SYNOPSIS
.B "int" batadv_mcast_forw_want_all_ip_count
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct ethhdr *ethhdr "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "ethhdr" 12
ethernet header of a packet
.SH "RETURN"
the number of nodes which want all IPv4 multicast traffic if the
given ethhdr is from an IPv4 packet or the number of nodes which want all
IPv6 traffic if it matches an IPv6 packet.
