.TH "batadv_last_bonding_replace" 9 "batadv_last_bonding_replace" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_last_bonding_replace \- Replace last_bonding_candidate of orig_node
.SH SYNOPSIS
.B "void" batadv_last_bonding_replace
.BI "(struct batadv_orig_node *orig_node "  ","
.BI "struct batadv_orig_ifinfo *new_candidate "  ");"
.SH ARGUMENTS
.IP "orig_node" 12
originator node whose bonding candidates should be replaced
.IP "new_candidate" 12
new bonding candidate or NULL
