.TH "batadv_tvlv_ogm_receive" 9 "batadv_tvlv_ogm_receive" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_tvlv_ogm_receive \- process an incoming ogm and call the appropriate handlers
.SH SYNOPSIS
.B "void" batadv_tvlv_ogm_receive
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct batadv_ogm_packet *batadv_ogm_packet "  ","
.BI "struct batadv_orig_node *orig_node "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "batadv_ogm_packet" 12
ogm packet containing the tvlv containers
.IP "orig_node" 12
orig node emitting the ogm packet
