.TH "batadv_mesh_init" 9 "batadv_mesh_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_mesh_init \- Initialize soft interface
.SH SYNOPSIS
.B "int" batadv_mesh_init
.BI "(struct net_device *soft_iface "  ");"
.SH ARGUMENTS
.IP "soft_iface" 12
netdev struct of the soft interface
.SH "RETURN"
0 on success or negative error number in case of failure
