.TH "batadv_gw_election" 9 "batadv_gw_election" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_gw_election \- Elect the best gateway
.SH SYNOPSIS
.B "void" batadv_gw_election
.BI "(struct batadv_priv *bat_priv "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
