.TH "batadv_tvlv_container_remove" 9 "batadv_tvlv_container_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_tvlv_container_remove \- remove tvlv container from the tvlv container list
.SH SYNOPSIS
.B "void" batadv_tvlv_container_remove
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct batadv_tvlv_container *tvlv "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "tvlv" 12
the to be removed tvlv container
.SH "DESCRIPTION"
Has to be called with the appropriate locks being acquired
(tvlv.container_list_lock).
