.TH "bcm63xx_udc_probe" 9 "bcm63xx_udc_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bcm63xx_udc_probe \- Initialize a new instance of the UDC.
.SH SYNOPSIS
.B "int" bcm63xx_udc_probe
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
Platform device struct from the bcm63xx BSP code.
.SH "DESCRIPTION"
Note that platform data is required, because pd.port_no varies from chip
to chip and is used to switch the correct USB port to device mode.
