.TH "bcm63xx_fifo_reset_ep" 9 "bcm63xx_fifo_reset_ep" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bcm63xx_fifo_reset_ep \- Flush a single endpoint's FIFO.
.SH SYNOPSIS
.B "void" bcm63xx_fifo_reset_ep
.BI "(struct bcm63xx_udc *udc "  ","
.BI "int ep_num "  ");"
.SH ARGUMENTS
.IP "udc" 12
Reference to the device controller.
.IP "ep_num" 12
Endpoint number.
