.TH "bcm63xx_udc_cleanup_debugfs" 9 "bcm63xx_udc_cleanup_debugfs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bcm63xx_udc_cleanup_debugfs \- Remove debugfs entries.
.SH SYNOPSIS
.B "void" bcm63xx_udc_cleanup_debugfs
.BI "(struct bcm63xx_udc *udc "  ");"
.SH ARGUMENTS
.IP "udc" 12
Reference to the device controller.
.SH "DESCRIPTION"
\fBdebugfs_remove\fP is safe to call with a NULL argument.
