.TH "be_cmd_set_vlan" 9 "be_cmd_set_vlan" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
be_cmd_set_vlan \- Configure VLAN paramters on the adapter
.SH SYNOPSIS
.B "int" be_cmd_set_vlan
.BI "(struct beiscsi_hba *phba "  ","
.BI "uint16_t vlan_tag "  ");"
.SH ARGUMENTS
.IP "phba" 12
device priv structure instance
.IP "vlan_tag" 12
TAG to be set
.SH "DESCRIPTION"
Set the VLAN_TAG for the adapter or Disable VLAN on adapter

returns
TAG for the MBX Cmd
