.TH "bfq_calc_finish" 9 "bfq_calc_finish" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bfq_calc_finish \- assign the finish time to an entity.
.SH SYNOPSIS
.B "void" bfq_calc_finish
.BI "(struct bfq_entity *entity "  ","
.BI "unsigned long service "  ");"
.SH ARGUMENTS
.IP "entity" 12
the entity to act upon.
.IP "service" 12
the service to be charged to the entity.
