.TH "bfq_put_idle_entity" 9 "bfq_put_idle_entity" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bfq_put_idle_entity \- release the idle tree ref of an entity.
.SH SYNOPSIS
.B "void" bfq_put_idle_entity
.BI "(struct bfq_service_tree *st "  ","
.BI "struct bfq_entity *entity "  ");"
.SH ARGUMENTS
.IP "st" 12
service tree for the entity.
.IP "entity" 12
the entity being released.
