.TH "bh_hbm_work_fn" 9 "bh_hbm_work_fn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bh_hbm_work_fn \- HBM work function
.SH SYNOPSIS
.B "void" bh_hbm_work_fn
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
work struct
.SH "DESCRIPTION"
Bottom half processing work function (instead of thread handler)
for processing hbm messages
