.TH "binder_inner_proc_unlock" 9 "binder_inner_proc_unlock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
binder_inner_proc_unlock \- Release inner lock for given binder_proc
.SH SYNOPSIS
.B "binder_inner_proc_unlock
.BI "(proc "  ");"
.SH ARGUMENTS
.IP "proc" 12
struct binder_proc to acquire
.SH "DESCRIPTION"
Release lock acquired via \fBbinder_inner_proc_lock\fP
