.TH "binder_dequeue_work" 9 "binder_dequeue_work" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
binder_dequeue_work \- Removes an item from the work list
.SH SYNOPSIS
.B "void" binder_dequeue_work
.BI "(struct binder_proc *proc "  ","
.BI "struct binder_work *work "  ");"
.SH ARGUMENTS
.IP "proc" 12
binder_proc associated with list
.IP "work" 12
struct binder_work to remove from list
.SH "DESCRIPTION"
Removes the specified work item from whatever list it is on.
Can safely be called if work is not on any list.
