.TH "bio_copy_data" 9 "bio_copy_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bio_copy_data \- copy contents of data buffers from one bio to another
.SH SYNOPSIS
.B "void" bio_copy_data
.BI "(struct bio *dst "  ","
.BI "struct bio *src "  ");"
.SH ARGUMENTS
.IP "dst" 12
destination bio
.IP "src" 12
source bio
.SH "DESCRIPTION"
Stops when it reaches the end of either \fIsrc\fP or \fIdst\fP - that is, copies
min(src->bi_size, dst->bi_size) bytes (or the equivalent for lists of bios).
