.TH "bio_clone_blkg_association" 9 "bio_clone_blkg_association" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bio_clone_blkg_association \- clone blkg association from src to dst bio
.SH SYNOPSIS
.B "void" bio_clone_blkg_association
.BI "(struct bio *dst "  ","
.BI "struct bio *src "  ");"
.SH ARGUMENTS
.IP "dst" 12
destination bio
.IP "src" 12
source bio
