.TH "bit_map_string_get" 9 "bit_map_string_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bit_map_string_get \- find and set a bit string in bit map.
.SH SYNOPSIS
.B "int" bit_map_string_get
.BI "(struct bit_map *t "  ","
.BI "int len "  ","
.BI "int align "  ");"
.SH ARGUMENTS
.IP "t" 12
the bit map.
.IP "len" 12
requested string length
.IP "align" 12
requested alignment
.SH "DESCRIPTION"
Returns offset in the map or -1 if out of space.

Not safe to call from an interrupt (uses spin_lock).
