.TH "blk_set_queue_depth" 9 "blk_set_queue_depth" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
blk_set_queue_depth \- tell the block layer about the device queue depth
.SH SYNOPSIS
.B "void" blk_set_queue_depth
.BI "(struct request_queue *q "  ","
.BI "unsigned int depth "  ");"
.SH ARGUMENTS
.IP "q" 12
the request queue for the device
.IP "depth" 12
queue depth
