.TH "blk_integrity_compare" 9 "blk_integrity_compare" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
blk_integrity_compare \- Compare integrity profile of two disks
.SH SYNOPSIS
.B "int" blk_integrity_compare
.BI "(struct gendisk *gd1 "  ","
.BI "struct gendisk *gd2 "  ");"
.SH ARGUMENTS
.IP "gd1" 12
Disk to compare
.IP "gd2" 12
Disk to compare
.SH "DESCRIPTION"
Meta-devices like DM and MD need to verify that all
sub-devices use the same integrity format before advertising to
upper layers that they can send/receive integrity metadata.  This
function can be used to check whether two gendisk devices have
compatible integrity formats.
