.TH "blk_rq_set_mixed_merge" 9 "blk_rq_set_mixed_merge" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
blk_rq_set_mixed_merge \- mark a request as mixed merge
.SH SYNOPSIS
.B "void" blk_rq_set_mixed_merge
.BI "(struct request *rq "  ");"
.SH ARGUMENTS
.IP "rq" 12
request to mark as mixed merge
.SH "DESCRIPTION"
\fIrq\fP is about to be mixed merged.  Make sure the attributes
which can be mixed are set in each bio and mark \fIrq\fP as mixed
merged.
