.TH "blk_add_driver_data" 9 "blk_add_driver_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
blk_add_driver_data \- Add binary message with driver-specific data
.SH SYNOPSIS
.B "void" blk_add_driver_data
.BI "(struct request *rq "  ","
.BI "void *data "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "rq" 12
io request
.IP "data" 12
driver-specific data
.IP "len" 12
length of driver-specific data
.SH "DESCRIPTION"
Some drivers might want to write driver-specific data per request.
