.TH "blk_queue_write_cache" 9 "blk_queue_write_cache" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
blk_queue_write_cache \- configure queue's write cache
.SH SYNOPSIS
.B "void" blk_queue_write_cache
.BI "(struct request_queue *q "  ","
.BI "bool wc "  ","
.BI "bool fua "  ");"
.SH ARGUMENTS
.IP "q" 12
the request queue for the device
.IP "wc" 12
write back cache on or off
.IP "fua" 12
device supports FUA writes, if true
.SH "DESCRIPTION"
Tell the block layer about the write cache of \fIq\fP.
