.TH "blocking_notifier_chain_register" 9 "blocking_notifier_chain_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
blocking_notifier_chain_register \- Add notifier to a blocking notifier chain
.SH SYNOPSIS
.B "int" blocking_notifier_chain_register
.BI "(struct blocking_notifier_head *nh "  ","
.BI "struct notifier_block *n "  ");"
.SH ARGUMENTS
.IP "nh" 12
Pointer to head of the blocking notifier chain
.IP "n" 12
New entry in notifier chain

Adds a notifier to a blocking notifier chain.
Must be called in process context.

Currently always returns zero.
