.TH "bnx2x_set_pbd_gso" 9 "bnx2x_set_pbd_gso" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2x_set_pbd_gso \- update PBD in GSO case.
.SH SYNOPSIS
.B "void" bnx2x_set_pbd_gso
.BI "(struct sk_buff *skb "  ","
.BI "struct eth_tx_parse_bd_e1x *pbd "  ","
.BI "u32 xmit_type "  ");"
.SH ARGUMENTS
.IP "skb" 12
packet skb
.IP "pbd" 12
parse BD
.IP "xmit_type" 12
xmit flags
