.TH "bnx2i_cpy_scsi_cdb" 9 "bnx2i_cpy_scsi_cdb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2i_cpy_scsi_cdb \- copies LUN & CDB fields in required format to sq wqe
.SH SYNOPSIS
.B "void" bnx2i_cpy_scsi_cdb
.BI "(struct scsi_cmnd *sc "  ","
.BI "struct bnx2i_cmd *cmd "  ");"
.SH ARGUMENTS
.IP "sc" 12
SCSI-ML command pointer
.IP "cmd" 12
iscsi cmd pointer
