.TH "bnx2i_iscsi_prep_generic_pdu_bd" 9 "bnx2i_iscsi_prep_generic_pdu_bd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2i_iscsi_prep_generic_pdu_bd \- prepares BD table.
.SH SYNOPSIS
.B "void" bnx2i_iscsi_prep_generic_pdu_bd
.BI "(struct bnx2i_conn *bnx2i_conn "  ");"
.SH ARGUMENTS
.IP "bnx2i_conn" 12
iscsi connection pointer
.SH "DESCRIPTION"
Allocates buffers and BD tables before shipping requests to cnic
for PDUs prepared by 'iscsid' daemon
