.TH "bnx2i_iscsi_send_generic_request" 9 "bnx2i_iscsi_send_generic_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2i_iscsi_send_generic_request \- called to send mgmt tasks.
.SH SYNOPSIS
.B "int" bnx2i_iscsi_send_generic_request
.BI "(struct iscsi_task *task "  ");"
.SH ARGUMENTS
.IP "task" 12
transport layer task pointer
.SH "DESCRIPTION"
called to transmit PDUs prepared by the 'iscsid' daemon. iSCSI login,
Nop-out and Logout requests flow through this path.
