.TH "bnx2x_mcast_handle_restore_cmd_e2" 9 "bnx2x_mcast_handle_restore_cmd_e2" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2x_mcast_handle_restore_cmd_e2 \- restore configuration from the registry
.SH SYNOPSIS
.B "int" bnx2x_mcast_handle_restore_cmd_e2
.BI "(struct bnx2x *bp "  ","
.BI "struct bnx2x_mcast_obj *o "  ","
.BI "int start_bin "  ","
.BI "int *rdata_idx "  ");"
.SH ARGUMENTS
.IP "bp" 12
device handle
.IP "o" 12
multicast object info
.IP "start_bin" 12
index in the registry to start from (including)
.IP "rdata_idx" 12
index in the ramrod data to start from
.SH "DESCRIPTION"
returns last handled bin index or -1 if all bins have been handled
