.TH "bnx2x_get_common_flags" 9 "bnx2x_get_common_flags" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2x_get_common_flags \- Return common flags
.SH SYNOPSIS
.B "unsigned long" bnx2x_get_common_flags
.BI "(struct bnx2x *bp "  ","
.BI "struct bnx2x_fastpath *fp "  ","
.BI "bool zero_stats "  ");"
.SH ARGUMENTS
.IP "bp" 12
device handle
.IP "fp" 12
queue handle
.IP "zero_stats" 12
TRUE if statistics zeroing is needed
.SH "DESCRIPTION"
Return the flags that are common for the Tx-only and not normal connections.
