.TH "bnx2x_set_pbd_csum_enc" 9 "bnx2x_set_pbd_csum_enc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2x_set_pbd_csum_enc \- update PBD with checksum and return header length
.SH SYNOPSIS
.B "u8" bnx2x_set_pbd_csum_enc
.BI "(struct bnx2x *bp "  ","
.BI "struct sk_buff *skb "  ","
.BI "u32 *parsing_data "  ","
.BI "u32 xmit_type "  ");"
.SH ARGUMENTS
.IP "bp" 12
driver handle
.IP "skb" 12
packet skb
.IP "parsing_data" 12
data to be updated
.IP "xmit_type" 12
xmit flags
.SH "DESCRIPTION"
57712/578xx related, when skb has encapsulation
