.TH "board_replaced" 9 "board_replaced" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
board_replaced \- Called after a board has been replaced in the system.
.SH SYNOPSIS
.B "u32" board_replaced
.BI "(struct pci_func *func "  ","
.BI "struct controller *ctrl "  ");"
.SH ARGUMENTS
.IP "func" 12
PCI device/function information
.IP "ctrl" 12
hotplug controller
.SH "DESCRIPTION"
This is only used if we don't have resources for hot add.
Turns power on for the board.
Checks to see if board is the same.
If board is same, reconfigures it.
If board isn't same, turns it back off.
