.TH "bond_set_dev_addr" 9 "bond_set_dev_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bond_set_dev_addr \- clone slave's address to bond
.SH SYNOPSIS
.B "int" bond_set_dev_addr
.BI "(struct net_device *bond_dev "  ","
.BI "struct net_device *slave_dev "  ");"
.SH ARGUMENTS
.IP "bond_dev" 12
bond net device
.IP "slave_dev" 12
slave net device
.SH "DESCRIPTION"
Should be called with RTNL held.
