.TH "brcmf_fweh_unregister" 9 "brcmf_fweh_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
brcmf_fweh_unregister \- remove handler for given code.
.SH SYNOPSIS
.B "void" brcmf_fweh_unregister
.BI "(struct brcmf_pub *drvr "  ","
.BI "enum brcmf_fweh_event_code code "  ");"
.SH ARGUMENTS
.IP "drvr" 12
driver information object.
.IP "code" 12
event code.
