.TH "brcmf_mon_add_vif" 9 "brcmf_mon_add_vif" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
brcmf_mon_add_vif \- create monitor mode virtual interface
.SH SYNOPSIS
.B "struct wireless_dev *" brcmf_mon_add_vif
.BI "(struct wiphy *wiphy "  ","
.BI "const char *name "  ");"
.SH ARGUMENTS
.IP "wiphy" 12
wiphy device of new interface.
.IP "name" 12
name of the new interface.
