.TH "btrfs_clone" 9 "btrfs_clone" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
btrfs_clone \- clone a range from inode file to another
.SH SYNOPSIS
.B "int" btrfs_clone
.BI "(struct inode *src "  ","
.BI "struct inode *inode "  ","
.BI "const u64 off "  ","
.BI "const u64 olen "  ","
.BI "const u64 olen_aligned "  ","
.BI "const u64 destoff "  ","
.BI "int no_time_update "  ");"
.SH ARGUMENTS
.IP "src" 12
Inode to clone from
.IP "inode" 12
Inode to clone to
.IP "off" 12
Offset within source to start clone from
.IP "olen" 12
Original length, passed by user, of range to clone
.IP "olen_aligned" 12
Block-aligned value of olen
.IP "destoff" 12
Offset within \fIinode\fP to start clone
.IP "no_time_update" 12
Whether to update mtime/ctime on the target inode
