.TH "bytes_str_to_int" 9 "bytes_str_to_int" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bytes_str_to_int \- convert a number of bytes string into an integer.
.SH SYNOPSIS
.B "int" bytes_str_to_int
.BI "(const char *str "  ");"
.SH ARGUMENTS
.IP "str" 12
the string to convert
.SH "DESCRIPTION"
This function returns positive resulting integer in case of success and a
negative error code in case of failure.
