.TH "ca8210_spi_transfer" 9 "ca8210_spi_transfer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ca8210_spi_transfer \- Initiate duplex spi transfer with ca8210
.SH SYNOPSIS
.B "int" ca8210_spi_transfer
.BI "(struct spi_device *spi "  ","
.BI "const u8 *buf "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "spi" 12
Pointer to spi device for transfer
.IP "buf" 12
Octet array to send
.IP "len" 12
length of the buffer being sent
.SH "RETURN"
0 or linux error code
