.TH "cail_mc_write" 9 "cail_mc_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cail_mc_write \- write MC (Memory Controller) register
.SH SYNOPSIS
.B "void" cail_mc_write
.BI "(struct card_info *info "  ","
.BI "uint32_t reg "  ","
.BI "uint32_t val "  ");"
.SH ARGUMENTS
.IP "info" 12
atom card_info pointer
.IP "reg" 12
MC register offset
.IP "val" 12
value to write to the pll register
.SH "DESCRIPTION"
Provides a MC register accessor for the atom interpreter (r4xx+).
