.TH "calculate_imbalance" 9 "calculate_imbalance" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
calculate_imbalance \- Calculate the amount of imbalance present within the groups of a given sched_domain during load balance.
.SH SYNOPSIS
.B "void" calculate_imbalance
.BI "(struct lb_env *env "  ","
.BI "struct sd_lb_stats *sds "  ");"
.SH ARGUMENTS
.IP "env" 12
load balance environment
.IP "sds" 12
statistics of the sched_domain whose imbalance is to be calculated.
