.TH "calipso_doi_remove" 9 "calipso_doi_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
calipso_doi_remove \- Remove an existing DOI from the CALIPSO protocol engine
.SH SYNOPSIS
.B "int" calipso_doi_remove
.BI "(u32 doi "  ","
.BI "struct netlbl_audit *audit_info "  ");"
.SH ARGUMENTS
.IP "doi" 12
the DOI value
.IP "audit_info" 12
NetLabel audit information
.SH "DESCRIPTION"
Removes a DOI definition from the CALIPSO engine.  The NetLabel routines will
be called to release their own LSM domain mappings as well as our own
domain list.  Returns zero on success and negative values on failure.
