.TH "can_proto_register" 9 "can_proto_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
can_proto_register \- register CAN transport protocol
.SH SYNOPSIS
.B "int" can_proto_register
.BI "(const struct can_proto *cp "  ");"
.SH ARGUMENTS
.IP "cp" 12
pointer to CAN protocol structure
.SH "RETURN"
0 on success
-EINVAL invalid (out of range) protocol number
-EBUSY  protocol already in use
-ENOBUF if \fBproto_register\fP fails
