.TH "cap_inode_killpriv" 9 "cap_inode_killpriv" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cap_inode_killpriv \- Erase the security markings on an inode
.SH SYNOPSIS
.B "int" cap_inode_killpriv
.BI "(struct user_namespace *mnt_userns "  ","
.BI "struct dentry *dentry "  ");"
.SH ARGUMENTS
.IP "mnt_userns" 12
user namespace of the mount the inode was found from
.IP "dentry" 12
The inode/dentry to alter
.SH "DESCRIPTION"
Erase the privilege-enhancing security markings on an inode.

If the inode has been found through an idmapped mount the user namespace of
the vfsmount must be passed through \fImnt_userns\fP. This function will then
take care to map the inode according to \fImnt_userns\fP before checking
permissions. On non-idmapped mounts or if permission checking is to be
performed on the raw inode simply passs init_user_ns.

Returns 0 if successful, -ve on error.
