.TH "cayman_dma_vm_copy_pages" 9 "cayman_dma_vm_copy_pages" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cayman_dma_vm_copy_pages \- update PTEs by copying them from the GART
.SH SYNOPSIS
.B "void" cayman_dma_vm_copy_pages
.BI "(struct radeon_device *rdev "  ","
.BI "struct radeon_ib *ib "  ","
.BI "uint64_t pe "  ","
.BI "uint64_t src "  ","
.BI "unsigned count "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ib" 12
indirect buffer to fill with commands
.IP "pe" 12
addr of the page entry
.IP "src" 12
src addr where to copy from
.IP "count" 12
number of page entries to update
.SH "DESCRIPTION"
Update PTEs by copying them from the GART using the DMA (cayman/TN).
