.TH "ccid3_hc_tx_send_packet" 9 "ccid3_hc_tx_send_packet" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ccid3_hc_tx_send_packet \- Delay-based dequeueing of TX packets
.SH SYNOPSIS
.B "int" ccid3_hc_tx_send_packet
.BI "(struct sock *sk "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "sk" 12
socket to send packet from
.IP "skb" 12
next packet candidate to send on \fIsk\fP
.SH "DESCRIPTION"
This function uses the convention of \fBccid_packet_dequeue_eval\fP and
returns a millisecond-delay value between 0 and t_mbi = 64000 msec.
