.TH "cdns3_ep_addr_to_index" 9 "cdns3_ep_addr_to_index" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cdns3_ep_addr_to_index \- Macro converts endpoint address to index of endpoint object in cdns3_device.eps[] container
.SH SYNOPSIS
.B "u8" cdns3_ep_addr_to_index
.BI "(u8 ep_addr "  ");"
.SH ARGUMENTS
.IP "ep_addr" 12
endpoint address for which endpoint object is required
