.TH "cdns3_gadget_giveback" 9 "cdns3_gadget_giveback" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cdns3_gadget_giveback \- call struct usb_request's ->complete callback
.SH SYNOPSIS
.B "void" cdns3_gadget_giveback
.BI "(struct cdns3_endpoint *priv_ep "  ","
.BI "struct cdns3_request *priv_req "  ","
.BI "int status "  ");"
.SH ARGUMENTS
.IP "priv_ep" 12
The endpoint to whom the request belongs to
.IP "priv_req" 12
The request we're giving back
.IP "status" 12
completion code for the request
.SH "DESCRIPTION"
Must be called with controller's lock held and interrupts disabled. This
function will unmap \fIreq\fP and call its ->\fBcomplete\fP callback to notify upper
layers that it has completed.
