.TH "cdns_uart_console_putchar" 9 "cdns_uart_console_putchar" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cdns_uart_console_putchar \- write the character to the FIFO buffer
.SH SYNOPSIS
.B "void" cdns_uart_console_putchar
.BI "(struct uart_port *port "  ","
.BI "int ch "  ");"
.SH ARGUMENTS
.IP "port" 12
Handle to the uart port structure
.IP "ch" 12
Character to be written
