.TH "cec_add_elem" 9 "cec_add_elem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cec_add_elem \- Add an element to the CEC array.
.SH SYNOPSIS
.B "int" cec_add_elem
.BI "(u64 pfn "  ");"
.SH ARGUMENTS
.IP "pfn" 12
page frame number to insert
.SH "DESCRIPTION"
Return values:
- <0:        on error
-  0:        on success
- >0:        when the inserted pfn was offlined
