.TH "cik_ib_test" 9 "cik_ib_test" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cik_ib_test \- basic gfx ring IB test
.SH SYNOPSIS
.B "int" cik_ib_test
.BI "(struct radeon_device *rdev "  ","
.BI "struct radeon_ring *ring "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ring" 12
radeon_ring structure holding ring information
.SH "DESCRIPTION"
Allocate an IB and execute it on the gfx ring (CIK).
Provides a basic gfx ring test to verify that IBs are working.
Returns 0 on success, error on failure.
