.TH "cik_cp_gfx_start" 9 "cik_cp_gfx_start" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cik_cp_gfx_start \- start the gfx ring
.SH SYNOPSIS
.B "int" cik_cp_gfx_start
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Enables the ring and loads the clear state context and other
packets required to init the ring.
Returns 0 for success, error for failure.
