.TH "cik_sdma_get_wptr" 9 "cik_sdma_get_wptr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cik_sdma_get_wptr \- get the current write pointer
.SH SYNOPSIS
.B "uint32_t" cik_sdma_get_wptr
.BI "(struct radeon_device *rdev "  ","
.BI "struct radeon_ring *ring "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ring" 12
radeon ring pointer
.SH "DESCRIPTION"
Get the current wptr from the hardware (CIK+).
