.TH "cipso_v4_cache_init" 9 "cipso_v4_cache_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cipso_v4_cache_init \- Initialize the CIPSO cache
.SH SYNOPSIS
.B "int" cipso_v4_cache_init
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"
Initializes the CIPSO label mapping cache, this function should be called
before any of the other functions defined in this file.  Returns zero on
success, negative values on error.
