.TH "cipso_v4_doi_remove" 9 "cipso_v4_doi_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cipso_v4_doi_remove \- Remove an existing DOI from the CIPSO protocol engine
.SH SYNOPSIS
.B "int" cipso_v4_doi_remove
.BI "(u32 doi "  ","
.BI "struct netlbl_audit *audit_info "  ");"
.SH ARGUMENTS
.IP "doi" 12
the DOI value
.IP "audit_info" 12
NetLabel audit information
.SH "DESCRIPTION"
Removes a DOI definition from the CIPSO engine.  The NetLabel routines will
be called to release their own LSM domain mappings as well as our own
domain list.  Returns zero on success and negative values on failure.
