.TH "class_compat_remove_link" 9 "class_compat_remove_link" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
class_compat_remove_link \- remove a compatibility class device link to a bus device
.SH SYNOPSIS
.B "void" class_compat_remove_link
.BI "(struct class_compat *cls "  ","
.BI "struct device *dev "  ","
.BI "struct device *device_link "  ");"
.SH ARGUMENTS
.IP "cls" 12
the compatibility class
.IP "dev" 12
the target bus device
.IP "device_link" 12
an optional device to which a "device" link was previously
created
