.TH "clear_update_marker" 9 "clear_update_marker" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
clear_update_marker \- clear update marker.
.SH SYNOPSIS
.B "int" clear_update_marker
.BI "(struct ubi_device *ubi "  ","
.BI "struct ubi_volume *vol "  ","
.BI "long long bytes "  ");"
.SH ARGUMENTS
.IP "ubi" 12
UBI device description object
.IP "vol" 12
volume description object
.IP "bytes" 12
new data size in bytes
.SH "DESCRIPTION"
This function clears the update marker for volume \fIvol\fP, sets new volume
data size and clears the "corrupted" flag (static volumes only). Returns
zero in case of success and a negative error code in case of failure.
