.TH "clkdm_get_pwrdm" 9 "clkdm_get_pwrdm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
clkdm_get_pwrdm \- return a ptr to the pwrdm that this clkdm resides in
.SH SYNOPSIS
.B "struct powerdomain *" clkdm_get_pwrdm
.BI "(struct clockdomain *clkdm "  ");"
.SH ARGUMENTS
.IP "clkdm" 12
struct clockdomain *
.SH "DESCRIPTION"
Return a pointer to the struct powerdomain that the specified clockdomain
\fIclkdm\fP exists in, or returns NULL if \fIclkdm\fP is NULL.
