.TH "comedi_pcmcia_driver_unregister" 9 "comedi_pcmcia_driver_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
comedi_pcmcia_driver_unregister \- Unregister a PCMCIA COMEDI driver
.SH SYNOPSIS
.B "void" comedi_pcmcia_driver_unregister
.BI "(struct comedi_driver *comedi_driver "  ","
.BI "struct pcmcia_driver *pcmcia_driver "  ");"
.SH ARGUMENTS
.IP "comedi_driver" 12
COMEDI driver to be registered.
.IP "pcmcia_driver" 12
PCMCIA driver to be registered.
.SH "DESCRIPTION"
This function is called from the \fBmodule_exit\fP of PCMCIA COMEDI driver
modules to unregister the PCMCIA driver and the COMEDI driver.  Do not call
it directly, use the \fBmodule_comedi_pcmcia_driver\fP helper macro instead.
