.TH "comedi_isadma_disable" 9 "comedi_isadma_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
comedi_isadma_disable \- disable the ISA DMA channel
.SH SYNOPSIS
.B "unsigned int" comedi_isadma_disable
.BI "(unsigned int dma_chan "  ");"
.SH ARGUMENTS
.IP "dma_chan" 12
the DMA channel to disable
.SH "DESCRIPTION"
Returns the residue (remaining bytes) left in the DMA transfer.
