.TH "comedi_isadma_poll" 9 "comedi_isadma_poll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
comedi_isadma_poll \- poll the current DMA transfer
.SH SYNOPSIS
.B "unsigned int" comedi_isadma_poll
.BI "(struct comedi_isadma *dma "  ");"
.SH ARGUMENTS
.IP "dma" 12
the ISA DMA to poll
.SH "DESCRIPTION"
Returns the position (in bytes) of the current DMA transfer.
