.TH "comedi_is_subdevice_running" 9 "comedi_is_subdevice_running" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
comedi_is_subdevice_running \- Check if async command running on subdevice
.SH SYNOPSIS
.B "bool" comedi_is_subdevice_running
.BI "(struct comedi_subdevice *s "  ");"
.SH ARGUMENTS
.IP "s" 12
COMEDI subdevice.
.SH "RETURN"
true if an asynchronous COMEDI command is active on the
subdevice, else false.
