.TH "console_conditional_schedule" 9 "console_conditional_schedule" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
console_conditional_schedule \- yield the CPU if required
.SH SYNOPSIS
.B "void" console_conditional_schedule
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

If the console code is currently allowed to sleep, and
if this CPU should yield the CPU to another task, do
so here.

Must be called within \fBconsole_lock\fP;.
