.TH "console_flush_on_panic" 9 "console_flush_on_panic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
console_flush_on_panic \- flush console content on panic
.SH SYNOPSIS
.B "void" console_flush_on_panic
.BI "(enum con_flush_mode mode "  ");"
.SH ARGUMENTS
.IP "mode" 12
flush all messages in buffer or just the pending ones
.SH "DESCRIPTION"
Immediately output all pending messages no matter what.
