.TH "copy_dynamic_supervisor_to_kernel" 9 "copy_dynamic_supervisor_to_kernel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
copy_dynamic_supervisor_to_kernel \- Save dynamic supervisor states to an xsave area
.SH SYNOPSIS
.B "void" copy_dynamic_supervisor_to_kernel
.BI "(struct xregs_state *xstate "  ","
.BI "u64 mask "  ");"
.SH ARGUMENTS
.IP "xstate" 12
A pointer to an xsave area
.IP "mask" 12
Represent the dynamic supervisor features saved into the xsave area
.SH "DESCRIPTION"
Only the dynamic supervisor states sets in the mask are saved into the xsave
area (See the comment in XFEATURE_MASK_DYNAMIC for the details of dynamic
supervisor feature). Besides the dynamic supervisor states, the legacy
region and XSAVE header are also saved into the xsave area. The supervisor
features in the XFEATURE_MASK_SUPERVISOR_SUPPORTED and
XFEATURE_MASK_SUPERVISOR_UNSUPPORTED are not saved.

The xsave area must be 64-bytes aligned.
