.TH "count_pages_for_highmem" 9 "count_pages_for_highmem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
count_pages_for_highmem \- Count non-highmem pages needed for copying highmem.
.SH SYNOPSIS
.B "unsigned int" count_pages_for_highmem
.BI "(unsigned int nr_highmem "  ");"
.SH ARGUMENTS
.IP "nr_highmem" 12
-- undescribed --
.SH "DESCRIPTION"

Compute the number of non-highmem pages that will be necessary for creating
copies of highmem pages.
