.TH "cppc_get_desired_perf" 9 "cppc_get_desired_perf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cppc_get_desired_perf \- Get the value of desired performance register.
.SH SYNOPSIS
.B "int" cppc_get_desired_perf
.BI "(int cpunum "  ","
.BI "u64 *desired_perf "  ");"
.SH ARGUMENTS
.IP "cpunum" 12
CPU from which to get desired performance.
.IP "desired_perf" 12
address of a variable to store the returned desired performance
.SH "RETURN"
0 for success, -EIO otherwise.
