.TH "cpu_pm_exit" 9 "cpu_pm_exit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpu_pm_exit \- CPU low power exit notifier
.SH SYNOPSIS
.B "int" cpu_pm_exit
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Notifies listeners that a single CPU is exiting a low power state that may
have caused some blocks in the same power domain as the cpu to reset.

Notified drivers can include VFP co-processor, interrupt controller
and its PM extensions, local CPU timers context save/restore which
shouldn't be interrupted. Hence it must be called with interrupts disabled.

Return conditions are same as __raw_notifier_call_chain.
