.TH "cpu_pm_register_notifier" 9 "cpu_pm_register_notifier" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpu_pm_register_notifier \- register a driver with cpu_pm
.SH SYNOPSIS
.B "int" cpu_pm_register_notifier
.BI "(struct notifier_block *nb "  ");"
.SH ARGUMENTS
.IP "nb" 12
notifier block to register
.SH "DESCRIPTION"
Add a driver to a list of drivers that are notified about
CPU and CPU cluster low power entry and exit.

This function may sleep, and has the same return conditions as
raw_notifier_chain_register.
