.TH "cpufreq_driver_resolve_freq" 9 "cpufreq_driver_resolve_freq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpufreq_driver_resolve_freq \- Map a target frequency to a driver-supported one.
.SH SYNOPSIS
.B "unsigned int" cpufreq_driver_resolve_freq
.BI "(struct cpufreq_policy *policy "  ","
.BI "unsigned int target_freq "  ");"
.SH ARGUMENTS
.IP "policy" 12
associated policy to interrogate
.IP "target_freq" 12
target frequency to resolve.
.SH "DESCRIPTION"
The target to driver frequency mapping is cached in the policy.
.SH "RETURN"
Lowest driver-supported frequency greater than or equal to the
given target_freq, subject to policy (min/max) and driver limitations.
