.TH "cpufreq_register_driver" 9 "cpufreq_register_driver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpufreq_register_driver \- register a CPU Frequency driver
.SH SYNOPSIS
.B "int" cpufreq_register_driver
.BI "(struct cpufreq_driver *driver_data "  ");"
.SH ARGUMENTS
.IP "driver_data" 12
A struct cpufreq_driver containing the values#
submitted by the CPU Frequency driver.
.SH "DESCRIPTION"
Registers a CPU Frequency driver to this core code. This code
returns zero on success, -EEXIST when another driver got here first
(and isn't unregistered in the meantime).
