.TH "cpufreq_driver_test_flags" 9 "cpufreq_driver_test_flags" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpufreq_driver_test_flags \- Test cpufreq driver's flags against given ones.
.SH SYNOPSIS
.B "bool" cpufreq_driver_test_flags
.BI "(u16 flags "  ");"
.SH ARGUMENTS
.IP "flags" 12
Flags to test against the current cpufreq driver's flags.
.SH "DESCRIPTION"
Assumes that the driver is there, so callers must ensure that this is the
case.
