.TH "cpufreq_get_driver_data" 9 "cpufreq_get_driver_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpufreq_get_driver_data \- Return current driver data.
.SH SYNOPSIS
.B "void *" cpufreq_get_driver_data
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Return the private data of the currently registered cpufreq driver, or NULL
if no cpufreq driver has been registered.
