.TH "cpuidle_disable_device" 9 "cpuidle_disable_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpuidle_disable_device \- disables idle PM for a CPU
.SH SYNOPSIS
.B "void" cpuidle_disable_device
.BI "(struct cpuidle_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the CPU
.SH "DESCRIPTION"
This function must be called between cpuidle_pause_and_lock and
cpuidle_resume_and_unlock when used externally.
