.TH "cpuidle_enter_state" 9 "cpuidle_enter_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpuidle_enter_state \- enter the state and update stats
.SH SYNOPSIS
.B "int" cpuidle_enter_state
.BI "(struct cpuidle_device *dev "  ","
.BI "struct cpuidle_driver *drv "  ","
.BI "int index "  ");"
.SH ARGUMENTS
.IP "dev" 12
cpuidle device for this cpu
.IP "drv" 12
cpuidle driver for this cpu
.IP "index" 12
index into the states table in \fIdrv\fP of the state to enter
