.TH "cpuidle_remove_sysfs" 9 "cpuidle_remove_sysfs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpuidle_remove_sysfs \- deletes a sysfs instance on the target device
.SH SYNOPSIS
.B "void" cpuidle_remove_sysfs
.BI "(struct cpuidle_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the target device
