.TH "cpuidle_remove_driver_sysfs" 9 "cpuidle_remove_driver_sysfs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpuidle_remove_driver_sysfs \- removes the driver name sysfs attribute
.SH SYNOPSIS
.B "void" cpuidle_remove_driver_sysfs
.BI "(struct cpuidle_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the target device
