.TH "cpumask_next_and" 9 "cpumask_next_and" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpumask_next_and \- get the next cpu in *src1p & *src2p
.SH SYNOPSIS
.B "int" cpumask_next_and
.BI "(int n "  ","
.BI "const struct cpumask *src1p "  ","
.BI "const struct cpumask *src2p "  ");"
.SH ARGUMENTS
.IP "n" 12
the cpu prior to the place to search (ie. return will be > \fIn\fP)
.IP "src1p" 12
the first cpumask pointer
.IP "src2p" 12
the second cpumask pointer
.SH "DESCRIPTION"
Returns >= nr_cpu_ids if no further cpus set in both.
