.TH "cpuset_cpus_allowed" 9 "cpuset_cpus_allowed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpuset_cpus_allowed \- return cpus_allowed mask from a tasks cpuset.
.SH SYNOPSIS
.B "void" cpuset_cpus_allowed
.BI "(struct task_struct *tsk "  ","
.BI "struct cpumask *pmask "  ");"
.SH ARGUMENTS
.IP "tsk" 12
pointer to task_struct from which to obtain cpuset->cpus_allowed.
.IP "pmask" 12
pointer to struct cpumask variable to receive cpus_allowed set.
.SH "DESCRIPTION"
Returns the cpumask_var_t cpus_allowed of the cpuset
attached to the specified \fItsk\fP.  Guaranteed to return some non-empty
subset of cpu_online_mask, even if this means going outside the
tasks cpuset.
