.TH "crc32_be_generic" 9 "crc32_be_generic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
crc32_be_generic \- Calculate bitwise big-endian Ethernet AUTODIN II CRC32
.SH SYNOPSIS
.B "u32 __pure" crc32_be_generic
.BI "(u32 crc "  ","
.BI "unsigned char const *p "  ","
.BI "size_t len "  ","
.BI "const u32 (*tab)[256] "  ","
.BI "u32 polynomial "  ");"
.SH ARGUMENTS
.IP "crc" 12
seed value for computation.  ~0 for Ethernet, sometimes 0 for
other uses, or the previous crc32 value if computing incrementally.
.IP "p" 12
pointer to buffer over which CRC32 is run
.IP "len" 12
length of buffer \fIp\fP
.IP "tab" 12
big-endian Ethernet table
.IP "polynomial" 12
CRC32 BE polynomial
