.TH "crc_ccitt" 9 "crc_ccitt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
crc_ccitt \- recompute the CRC (CRC-CCITT variant) for the data buffer
.SH SYNOPSIS
.B "u16" crc_ccitt
.BI "(u16 crc "  ","
.BI "u8 const *buffer "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "crc" 12
previous CRC value
.IP "buffer" 12
data pointer
.IP "len" 12
number of bytes in the buffer
