.TH "create_zone_bm_rtree" 9 "create_zone_bm_rtree" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
create_zone_bm_rtree \- Create a radix tree for one zone.
.SH SYNOPSIS
.B "struct mem_zone_bm_rtree *" create_zone_bm_rtree
.BI "(gfp_t gfp_mask "  ","
.BI "int safe_needed "  ","
.BI "struct chain_allocator *ca "  ","
.BI "unsigned long start "  ","
.BI "unsigned long end "  ");"
.SH ARGUMENTS
.IP "gfp_mask" 12
-- undescribed --
.IP "safe_needed" 12
-- undescribed --
.IP "ca" 12
-- undescribed --
.IP "start" 12
-- undescribed --
.IP "end" 12
-- undescribed --
.SH "DESCRIPTION"

Allocated the mem_zone_bm_rtree structure and initializes it.
This function also allocated and builds the radix tree for the
zone.
