.TH "create_hdr_descs" 9 "create_hdr_descs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
create_hdr_descs \- create header and header extension descriptors
.SH SYNOPSIS
.B "int" create_hdr_descs
.BI "(u8 hdr_field "  ","
.BI "u8 *hdr_data "  ","
.BI "int len "  ","
.BI "int *hdr_len "  ","
.BI "union sub_crq *scrq_arr "  ");"
.SH ARGUMENTS
.IP "hdr_field" 12
bitfield determining needed headers
.IP "hdr_data" 12
buffer containing header data
.IP "len" 12
length of data buffer
.IP "hdr_len" 12
array of individual header lengths
.IP "scrq_arr" 12
descriptor array
.SH "DESCRIPTION"
Creates header and, if needed, header extension descriptors and
places them in a descriptor array, scrq_arr
