.TH "cros_ec_pd_command" 9 "cros_ec_pd_command" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cros_ec_pd_command \- Send a command to the EC.
.SH SYNOPSIS
.B "int" cros_ec_pd_command
.BI "(struct cros_ec_device *ec_dev "  ","
.BI "int command "  ","
.BI "uint8_t *outdata "  ","
.BI "int outsize "  ","
.BI "uint8_t *indata "  ","
.BI "int insize "  ");"
.SH ARGUMENTS
.IP "ec_dev" 12
EC device
.IP "command" 12
EC command
.IP "outdata" 12
EC command output data
.IP "outsize" 12
Size of outdata
.IP "indata" 12
EC command input data
.IP "insize" 12
Size of indata
.SH "RETURN"
>= 0 on success, negative error number on failure.
