.TH "cros_ec_spi_receive_packet" 9 "cros_ec_spi_receive_packet" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cros_ec_spi_receive_packet \- Receive a packet from the EC.
.SH SYNOPSIS
.B "int" cros_ec_spi_receive_packet
.BI "(struct cros_ec_device *ec_dev "  ","
.BI "int need_len "  ");"
.SH ARGUMENTS
.IP "ec_dev" 12
ChromeOS EC device
.IP "need_len" 12
Number of message bytes we need to read
.SH "DESCRIPTION"

This function has two phases: reading the preamble bytes (since if we read
data from the EC before it is ready to send, we just get preamble) and
reading the actual message.

The received data is placed into ec_dev->din.
