.TH "cros_ec_keyb_query_switches" 9 "cros_ec_keyb_query_switches" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cros_ec_keyb_query_switches \- Query the state of switches and report
.SH SYNOPSIS
.B "int" cros_ec_keyb_query_switches
.BI "(struct cros_ec_keyb *ckdev "  ");"
.SH ARGUMENTS
.IP "ckdev" 12
The keyboard device
.SH "DESCRIPTION"

This will ask the EC about the current state of switches and report to the
kernel.  Note that we don't query for buttons because they are more
transitory and we'll get an update on the next release / press.

Returns 0 if no error or -error upon error.
