.TH "crypto_engine_start" 9 "crypto_engine_start" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
crypto_engine_start \- start the hardware engine
.SH SYNOPSIS
.B "int" crypto_engine_start
.BI "(struct crypto_engine *engine "  ");"
.SH ARGUMENTS
.IP "engine" 12
the hardware engine need to be started
.SH "DESCRIPTION"
Return 0 on success, else on fail.
