.TH "cryp_configure_key_values" 9 "cryp_configure_key_values" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cryp_configure_key_values \- configures the key values for CRYP operations
.SH SYNOPSIS
.B "int" cryp_configure_key_values
.BI "(struct cryp_device_data *device_data "  ","
.BI "enum cryp_key_reg_index key_reg_index "  ","
.BI "struct cryp_key_value key_value "  ");"
.SH ARGUMENTS
.IP "device_data" 12
Pointer to the device data struct for base address.
.IP "key_reg_index" 12
Key value index register
.IP "key_value" 12
The key value struct
