.TH "cs5520_pci_device_suspend" 9 "cs5520_pci_device_suspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cs5520_pci_device_suspend \- device suspend
.SH SYNOPSIS
.B "int" cs5520_pci_device_suspend
.BI "(struct pci_dev *pdev "  ","
.BI "pm_message_t mesg "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device

We have to cut and waste bits from the standard method because
the 5520 is a bit odd and not just a pure ATA device. As a result
we must not disable it. The needed code is short and this avoids
chip specific mess in the core code.
.IP "mesg" 12
-- undescribed --
