.TH "cs5530_set_pio_mode" 9 "cs5530_set_pio_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cs5530_set_pio_mode \- set host controller for PIO mode
.SH SYNOPSIS
.B "void" cs5530_set_pio_mode
.BI "(ide_hwif_t *hwif "  ","
.BI "ide_drive_t *drive "  ");"
.SH ARGUMENTS
.IP "hwif" 12
port
.IP "drive" 12
drive

Handles setting of PIO mode for the chipset.

The \fBinit_hwif_cs5530\fP routine guarantees that all drives
will have valid default PIO timings set up before we get here.
