.TH "ctx_event_pending" 9 "ctx_event_pending" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ctx_event_pending \- check for any event pending on the context
.SH SYNOPSIS
.B "bool" ctx_event_pending
.BI "(struct ocxlflash_context *ctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
Context to be checked.
.SH "RETURN"
true if there is an event pending, false if none pending
