.TH "cuse_channel_release" 9 "cuse_channel_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cuse_channel_release \- release method for /dev/cuse
.SH SYNOPSIS
.B "int" cuse_channel_release
.BI "(struct inode *inode "  ","
.BI "struct file *file "  ");"
.SH ARGUMENTS
.IP "inode" 12
inode for /dev/cuse
.IP "file" 12
file struct being closed
.SH "DESCRIPTION"
Disconnect the channel, deregister CUSE device and initiate
destruction by putting the default reference.
.SH "RETURN"
0 on success, -errno on failure.
