.TH "cvm_oct_xmit" 9 "cvm_oct_xmit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cvm_oct_xmit \- transmit a packet
.SH SYNOPSIS
.B "int" cvm_oct_xmit
.BI "(struct sk_buff *skb "  ","
.BI "struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "skb" 12
Packet to send
.IP "dev" 12
Device info structure
.SH "DESCRIPTION"
Returns Always returns NETDEV_TX_OK
