.TH "cxgb4_ptp_enable" 9 "cxgb4_ptp_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cxgb4_ptp_enable \- enable or disable an ancillary feature
.SH SYNOPSIS
.B "int" cxgb4_ptp_enable
.BI "(struct ptp_clock_info __always_unused *ptp "  ","
.BI "struct ptp_clock_request __always_unused *request "  ","
.BI "int __always_unused on "  ");"
.SH ARGUMENTS
.IP "ptp" 12
ptp clock structure
.IP "request" 12
Desired resource to enable or disable
.IP "on" 12
Caller passes one to enable or zero to disable
.SH "DESCRIPTION"
Enable (or disable) ancillary features of the PHC subsystem.
Currently, no ancillary features are supported.
