.TH "cxlflash_disk_direct_open" 9 "cxlflash_disk_direct_open" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cxlflash_disk_direct_open \- opens a direct (physical) disk
.SH SYNOPSIS
.B "int" cxlflash_disk_direct_open
.BI "(struct scsi_device *sdev "  ","
.BI "void *arg "  ");"
.SH ARGUMENTS
.IP "sdev" 12
SCSI device associated with LUN.
.IP "arg" 12
UDirect ioctl data structure.
.SH "DESCRIPTION"
On successful return, the user is informed of the resource handle
to be used to identify the direct lun and the size (in blocks) of
the direct lun in last LBA format.
.SH "RETURN"
0 on success, -errno on failure
