.TH "cxlflash_term_local_luns" 9 "cxlflash_term_local_luns" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cxlflash_term_local_luns \- Delete all entries from local LUN list, free.
.SH SYNOPSIS
.B "void" cxlflash_term_local_luns
.BI "(struct cxlflash_cfg *cfg "  ");"
.SH ARGUMENTS
.IP "cfg" 12
Internal structure associated with the host.
