.TH "db8500_prcmu_get_arm_opp" 9 "db8500_prcmu_get_arm_opp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
db8500_prcmu_get_arm_opp \- get the current ARM OPP
.SH SYNOPSIS
.B "int" db8500_prcmu_get_arm_opp
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
the current ARM OPP
