.TH "db8500_prcmu_request_clock" 9 "db8500_prcmu_request_clock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
db8500_prcmu_request_clock \- Request for a clock to be enabled or disabled.
.SH SYNOPSIS
.B "int" db8500_prcmu_request_clock
.BI "(u8 clock "  ","
.BI "bool enable "  ");"
.SH ARGUMENTS
.IP "clock" 12
The clock for which the request is made.
.IP "enable" 12
Whether the clock should be enabled (true) or disabled (false).
.SH "DESCRIPTION"
This function should only be used by the clock implementation.
Do not use it from any other place!
