.TH "dccp_ackvec_add_new" 9 "dccp_ackvec_add_new" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dccp_ackvec_add_new \- Record one or more new entries in Ack Vector buffer
.SH SYNOPSIS
.B "void" dccp_ackvec_add_new
.BI "(struct dccp_ackvec *av "  ","
.BI "u32 num_packets "  ","
.BI "u64 seqno "  ","
.BI "enum dccp_ackvec_states state "  ");"
.SH ARGUMENTS
.IP "av" 12
container of buffer to update (can be empty or non-empty)
.IP "num_packets" 12
number of packets to register (must be >= 1)
.IP "seqno" 12
sequence number of the first packet in \fInum_packets\fP
.IP "state" 12
state in which packet carrying \fIseqno\fP was received
