.TH "dccp_insert_option_mandatory" 9 "dccp_insert_option_mandatory" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dccp_insert_option_mandatory \- Mandatory option (5.8.2)
.SH SYNOPSIS
.B "int" dccp_insert_option_mandatory
.BI "(struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "skb" 12
frame into which to insert option
.SH "DESCRIPTION"
Note that since we are using skb_push, this function needs to be called
_after_ inserting the option it is supposed to influence (stack order).
