.TH "dccp_feat_prefer" 9 "dccp_feat_prefer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dccp_feat_prefer \- Move preferred entry to the start of array
.SH SYNOPSIS
.B "u8" dccp_feat_prefer
.BI "(u8 preferred_value "  ","
.BI "u8 *array "  ","
.BI "u8 array_len "  ");"
.SH ARGUMENTS
.IP "preferred_value" 12
entry to move to start of array
.IP "array" 12
array of preferred entries
.IP "array_len" 12
size of the array
.SH "DESCRIPTION"
Reorder the \fIarray_len\fP elements in \fIarray\fP so that \fIpreferred_value\fP comes
first. Returns >0 to indicate that \fIpreferred_value\fP does occur in \fIarray\fP.
