.TH "dccp_feat_push_confirm" 9 "dccp_feat_push_confirm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dccp_feat_push_confirm \- Add a Confirm entry to the FN list
.SH SYNOPSIS
.B "int" dccp_feat_push_confirm
.BI "(struct list_head *fn_list "  ","
.BI "u8 feat "  ","
.BI "u8 local "  ","
.BI "dccp_feat_val *fval "  ");"
.SH ARGUMENTS
.IP "fn_list" 12
feature-negotiation list to add to
.IP "feat" 12
one of dccp_feature_numbers
.IP "local" 12
whether local (1) or remote (0) \fIfeat_num\fP is being confirmed
.IP "fval" 12
pointer to NN/SP value to be inserted or NULL
.SH "DESCRIPTION"
Returns 0 on success, a Reset code for further processing otherwise.
