.TH "dcdbas_host_control" 9 "dcdbas_host_control" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dcdbas_host_control \- initiate host control
.SH SYNOPSIS
.B "void" dcdbas_host_control
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This function is called by the driver after the system has
finished shutting down if the user application specified a
host control action to perform on shutdown.  It is safe to
use smi_data_buf at this point because the system has finished
shutting down and no userspace apps are running.
