.TH "dcdbas_smi_request" 9 "dcdbas_smi_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dcdbas_smi_request \- generate SMI request
.SH SYNOPSIS
.B "int" dcdbas_smi_request
.BI "(struct smi_cmd *smi_cmd "  ");"
.SH ARGUMENTS
.IP "smi_cmd" 12
-- undescribed --
.SH "DESCRIPTION"

Called with smi_data_lock.
