.TH "debug_set_level" 9 "debug_set_level" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
debug_set_level \- Sets new actual debug level if new_level is valid.
.SH SYNOPSIS
.B "void" debug_set_level
.BI "(debug_info_t *id "  ","
.BI "int new_level "  ");"
.SH ARGUMENTS
.IP "id" 12
handle for debug log
.IP "new_level" 12
new debug level
.SH "RETURN"
none
