.TH "dev_pm_enable_wake_irq" 9 "dev_pm_enable_wake_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_pm_enable_wake_irq \- Enable device wake-up interrupt
.SH SYNOPSIS
.B "void" dev_pm_enable_wake_irq
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device
.SH "DESCRIPTION"
Optionally called from the bus code or the device driver for
\fBruntime_resume\fP to override the PM runtime core managed wake-up
interrupt handling to enable the wake-up interrupt.

Note that for \fBruntime_suspend\fP) the wake-up interrupts
should be unconditionally enabled unlike for \fBsuspend\fP
that is conditional.
