.TH "dev_pm_qos_remove_notifier" 9 "dev_pm_qos_remove_notifier" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_pm_qos_remove_notifier \- deletes notification for changes to target value of per-device PM QoS constraints
.SH SYNOPSIS
.B "int" dev_pm_qos_remove_notifier
.BI "(struct device *dev "  ","
.BI "struct notifier_block *notifier "  ","
.BI "enum dev_pm_qos_req_type type "  ");"
.SH ARGUMENTS
.IP "dev" 12
target device for the constraint
.IP "notifier" 12
notifier block to be removed.
.IP "type" 12
request type.
.SH "DESCRIPTION"
Will remove the notifier from the notification chain that gets called
upon changes to the target value.
