.TH "dev_get_phys_port_id" 9 "dev_get_phys_port_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_get_phys_port_id \- Get device physical port ID
.SH SYNOPSIS
.B "int" dev_get_phys_port_id
.BI "(struct net_device *dev "  ","
.BI "struct netdev_phys_item_id *ppid "  ");"
.SH ARGUMENTS
.IP "dev" 12
device
.IP "ppid" 12
port ID

Get device physical port ID
