.TH "dev_pm_opp_detach_genpd" 9 "dev_pm_opp_detach_genpd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_pm_opp_detach_genpd \- Detach genpd(s) from the device.
.SH SYNOPSIS
.B "void" dev_pm_opp_detach_genpd
.BI "(struct opp_table *opp_table "  ");"
.SH ARGUMENTS
.IP "opp_table" 12
OPP table returned by \fBdev_pm_opp_attach_genpd\fP.
.SH "DESCRIPTION"
This detaches the genpd(s), resets the virtual device pointers, and puts the
OPP table.
