.TH "dev_pm_arm_wake_irq" 9 "dev_pm_arm_wake_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_pm_arm_wake_irq \- Arm device wake-up
.SH SYNOPSIS
.B "void" dev_pm_arm_wake_irq
.BI "(struct wake_irq *wirq "  ");"
.SH ARGUMENTS
.IP "wirq" 12
Device wake-up interrupt
.SH "DESCRIPTION"
Sets up the wake-up event conditionally based on the
\fBdevice_may_wake\fP.
