.TH "dev_get_iflink" 9 "dev_get_iflink" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_get_iflink \- get 'iflink' value of a interface
.SH SYNOPSIS
.B "int" dev_get_iflink
.BI "(const struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
targeted interface

Indicates the ifindex the interface is linked to.
Physical interfaces have the same 'ifindex' and 'iflink' values.
