.TH "dev_pm_opp_get_opp_count" 9 "dev_pm_opp_get_opp_count" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_pm_opp_get_opp_count \- Get number of opps available in the opp table
.SH SYNOPSIS
.B "int" dev_pm_opp_get_opp_count
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device for which we do this operation
.SH "RETURN"
This function returns the number of available opps if there are any,
else returns 0 if none or the corresponding error value.
