.TH "dev_pm_opp_cpumask_remove_table" 9 "dev_pm_opp_cpumask_remove_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_pm_opp_cpumask_remove_table \- Removes OPP table for @cpumask
.SH SYNOPSIS
.B "void" dev_pm_opp_cpumask_remove_table
.BI "(const struct cpumask *cpumask "  ");"
.SH ARGUMENTS
.IP "cpumask" 12
cpumask for which OPP table needs to be removed
.SH "DESCRIPTION"
This removes the OPP tables for CPUs present in the \fIcpumask\fP.
This should be used to remove all the OPPs entries associated with
the cpus in \fIcpumask\fP.
