.TH "dev_mmio" 9 "dev_mmio" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_mmio \- Get the MMIO address of PDC2027x extended registers
.SH SYNOPSIS
.B "void __iomem *" dev_mmio
.BI "(struct ata_port *ap "  ","
.BI "struct ata_device *adev "  ","
.BI "unsigned int offset "  ");"
.SH ARGUMENTS
.IP "ap" 12
Port
.IP "adev" 12
device
.IP "offset" 12
offset from mmio base
