.TH "dev_addr_del" 9 "dev_addr_del" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_addr_del \- Release a device address.
.SH SYNOPSIS
.B "int" dev_addr_del
.BI "(struct net_device *dev "  ","
.BI "const unsigned char *addr "  ","
.BI "unsigned char addr_type "  ");"
.SH ARGUMENTS
.IP "dev" 12
device
.IP "addr" 12
address to delete
.IP "addr_type" 12
address type

Release reference to a device address and remove it from the device
if the reference count drops to zero.

The caller must hold the rtnl_mutex.
