.TH "dev_pm_opp_get_freq" 9 "dev_pm_opp_get_freq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_pm_opp_get_freq \- Gets the frequency corresponding to an available opp
.SH SYNOPSIS
.B "unsigned long" dev_pm_opp_get_freq
.BI "(struct dev_pm_opp *opp "  ");"
.SH ARGUMENTS
.IP "opp" 12
opp for which frequency has to be returned for
.SH "RETURN"
frequency in hertz corresponding to the opp, else
return 0
