.TH "device_reprobe" 9 "device_reprobe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
device_reprobe \- remove driver for a device and probe for a new driver
.SH SYNOPSIS
.B "int" device_reprobe
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device to reprobe
.SH "DESCRIPTION"
This function detaches the attached driver (if any) for the given
device and restarts the driver probing process.  It is intended
to use if probing criteria changed during a devices lifetime and
driver attachment should change accordingly.
