.TH "device_destroy" 9 "device_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
device_destroy \- removes a device that was created with device_create()
.SH SYNOPSIS
.B "void" device_destroy
.BI "(struct class *class "  ","
.BI "dev_t devt "  ");"
.SH ARGUMENTS
.IP "class" 12
pointer to the struct class that this device was registered with
.IP "devt" 12
the dev_t of the device that was previously registered
.SH "DESCRIPTION"
This call unregisters and cleans up a device that was created with a
call to \fBdevice_create\fP.
