.TH "device_property_present" 9 "device_property_present" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
device_property_present \- check if a property of a device is present
.SH SYNOPSIS
.B "bool" device_property_present
.BI "(struct device *dev "  ","
.BI "const char *propname "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device whose property is being checked
.IP "propname" 12
Name of the property
.SH "DESCRIPTION"
Check if property \fIpropname\fP is present in the device firmware description.
