.TH "device_remove_bin_file" 9 "device_remove_bin_file" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
device_remove_bin_file \- remove sysfs binary attribute file
.SH SYNOPSIS
.B "void" device_remove_bin_file
.BI "(struct device *dev "  ","
.BI "const struct bin_attribute *attr "  ");"
.SH ARGUMENTS
.IP "dev" 12
device.
.IP "attr" 12
device binary attribute descriptor.
