.TH "devlink_resources_unregister" 9 "devlink_resources_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devlink_resources_unregister \- free all resources
.SH SYNOPSIS
.B "void" devlink_resources_unregister
.BI "(struct devlink *devlink "  ","
.BI "struct devlink_resource *resource "  ");"
.SH ARGUMENTS
.IP "devlink" 12
devlink
.IP "resource" 12
resource
