.TH "devlink_param_value_changed" 9 "devlink_param_value_changed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devlink_param_value_changed \- notify devlink on a parameter's value change. Should be called by the driver right after the change.
.SH SYNOPSIS
.B "void" devlink_param_value_changed
.BI "(struct devlink *devlink "  ","
.BI "u32 param_id "  ");"
.SH ARGUMENTS
.IP "devlink" 12
devlink
.IP "param_id" 12
parameter ID

This function should be used by the driver to notify devlink on value
change, excluding driverinit configuration mode.
For driverinit configuration mode driver should use the function
