.TH "devm_ti_sci_get_resource_sets" 9 "devm_ti_sci_get_resource_sets" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_ti_sci_get_resource_sets \- Get a TISCI resources assigned to a device
.SH SYNOPSIS
.B "struct ti_sci_resource *" devm_ti_sci_get_resource_sets
.BI "(const struct ti_sci_handle *handle "  ","
.BI "struct device *dev "  ","
.BI "u32 dev_id "  ","
.BI "u32 *sub_types "  ","
.BI "u32 sets "  ");"
.SH ARGUMENTS
.IP "handle" 12
TISCI handle
.IP "dev" 12
Device pointer to which the resource is assigned
.IP "dev_id" 12
TISCI device id to which the resource is assigned
.IP "sub_types" 12
Array of sub_types assigned corresponding to device
.IP "sets" 12
Number of sub_types
.SH "RETURN"
Pointer to ti_sci_resource if all went well else appropriate
error pointer.
