.TH "devm_regulator_get" 9 "devm_regulator_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_regulator_get \- Resource managed regulator_get()
.SH SYNOPSIS
.B "struct regulator *" devm_regulator_get
.BI "(struct device *dev "  ","
.BI "const char *id "  ");"
.SH ARGUMENTS
.IP "dev" 12
device to supply
.IP "id" 12
supply name or regulator ID.
.SH "DESCRIPTION"
Managed \fBregulator_get\fP. Regulators returned from this function are
automatically \fBregulator_put\fP on driver detach. See \fBregulator_get\fP for more
information.
