.TH "devm_regmap_del_irq_chip" 9 "devm_regmap_del_irq_chip" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_regmap_del_irq_chip \- Resource managed regmap_del_irq_chip()
.SH SYNOPSIS
.B "void" devm_regmap_del_irq_chip
.BI "(struct device *dev "  ","
.BI "int irq "  ","
.BI "struct regmap_irq_chip_data *data "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device for which which resource was allocated.
.IP "irq" 12
Primary IRQ for the device.
.IP "data" 12
\fIregmap_irq_chip_data\fP allocated by \fBregmap_add_irq_chip\fP.
.SH "DESCRIPTION"
A resource managed version of \fBregmap_del_irq_chip\fP.
