.TH "devm_nvmem_cell_get" 9 "devm_nvmem_cell_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_nvmem_cell_get \- Get nvmem cell of device form a given id
.SH SYNOPSIS
.B "struct nvmem_cell *" devm_nvmem_cell_get
.BI "(struct device *dev "  ","
.BI "const char *id "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device that requests the nvmem cell.
.IP "id" 12
nvmem cell name id to get.
.SH "RETURN"
Will be an \fBERR_PTR\fP on error or a valid pointer
to a struct nvmem_cell.  The nvmem_cell will be freed by the
automatically once the device is freed.
