.TH "devm_ioport_unmap" 9 "devm_ioport_unmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_ioport_unmap \- Managed ioport_unmap()
.SH SYNOPSIS
.B "void" devm_ioport_unmap
.BI "(struct device *dev "  ","
.BI "void __iomem *addr "  ");"
.SH ARGUMENTS
.IP "dev" 12
Generic device to unmap for
.IP "addr" 12
Address to unmap
.SH "DESCRIPTION"
Managed \fBioport_unmap\fP.  \fIaddr\fP must have been mapped using
\fBdevm_ioport_map\fP.
