.TH "devm_devfreq_unregister_opp_notifier" 9 "devm_devfreq_unregister_opp_notifier" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_devfreq_unregister_opp_notifier \- Resource-managed devfreq_unregister_opp_notifier()
.SH SYNOPSIS
.B "void" devm_devfreq_unregister_opp_notifier
.BI "(struct device *dev "  ","
.BI "struct devfreq *devfreq "  ");"
.SH ARGUMENTS
.IP "dev" 12
The devfreq user device. (parent of devfreq)
.IP "devfreq" 12
The devfreq object.
