.TH "devm_gpiod_get_array_optional" 9 "devm_gpiod_get_array_optional" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_gpiod_get_array_optional \- Resource-managed gpiod_get_array_optional()
.SH SYNOPSIS
.B "struct gpio_descs *" devm_gpiod_get_array_optional
.BI "(struct device *dev "  ","
.BI "const char *con_id "  ","
.BI "enum gpiod_flags flags "  ");"
.SH ARGUMENTS
.IP "dev" 12
GPIO consumer
.IP "con_id" 12
function within the GPIO consumer
.IP "flags" 12
optional GPIO initialization flags
.SH "DESCRIPTION"
Managed \fBgpiod_get_array_optional\fP. GPIO descriptors returned from this
function are automatically disposed on driver detach.
See \fBgpiod_get_array_optional\fP for detailed information about behavior and
return values.
