.TH "devres_for_each_res" 9 "devres_for_each_res" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devres_for_each_res \- Resource iterator
.SH SYNOPSIS
.B "void" devres_for_each_res
.BI "(struct device *dev "  ","
.BI "dr_release_t release "  ","
.BI "dr_match_t match "  ","
.BI "void *match_data "  ","
.BI "void (*fn)(struct device *, void *, void *) "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to iterate resource from
.IP "release" 12
Look for resources associated with this release function
.IP "match" 12
Match function (optional)
.IP "match_data" 12
Data for the match function
.IP "fn" 12
Function to be called for each matched resource.
.IP "data" 12
Data for \fIfn\fP, the 3rd parameter of \fIfn\fP
.SH "DESCRIPTION"
Call \fIfn\fP for each devres of \fIdev\fP which is associated with \fIrelease\fP
and for which \fImatch\fP returns 1.
.SH "RETURN"
void
