.TH "dfl_fpga_check_port_id" 9 "dfl_fpga_check_port_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dfl_fpga_check_port_id \- check the port id
.SH SYNOPSIS
.B "int" dfl_fpga_check_port_id
.BI "(struct platform_device *pdev "  ","
.BI "void *pport_id "  ");"
.SH ARGUMENTS
.IP "pdev" 12
port platform device.
.IP "pport_id" 12
port id to compare.
.SH "RETURN"
1 if port device matches with given port id, otherwise 0.
