.TH "dfll_init_out_if" 9 "dfll_init_out_if" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dfll_init_out_if \- prepare DFLL-to-PMIC interface
.SH SYNOPSIS
.B "void" dfll_init_out_if
.BI "(struct tegra_dfll *td "  ");"
.SH ARGUMENTS
.IP "td" 12
DFLL instance
.SH "DESCRIPTION"
During DFLL driver initialization or resume from context loss,
disable the I2C command output to the PMIC, set safe voltage and
output limits, and disable and clear limit interrupts.
