.TH "dfll_disable" 9 "dfll_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dfll_disable \- switch from open-loop mode to disabled mode
.SH SYNOPSIS
.B "int" dfll_disable
.BI "(struct tegra_dfll *td "  ");"
.SH ARGUMENTS
.IP "td" 12
DFLL instance
.SH "DESCRIPTION"
Switch from OPEN_LOOP state to DISABLED state. Returns 0 upon success
or -EPERM if the DFLL is not currently in open-loop mode.
