.TH "die_get_varname" 9 "die_get_varname" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
die_get_varname \- Get the name and type of given variable DIE
.SH SYNOPSIS
.B "int" die_get_varname
.BI "(Dwarf_Die *vr_die "  ","
.BI "struct strbuf *buf "  ");"
.SH ARGUMENTS
.IP "vr_die" 12
a variable DIE
.IP "buf" 12
a strbuf for type and variable name
.SH "DESCRIPTION"
Get the name and type of \fIvr_die\fP and stores it in \fIbuf\fP as "type\tname".
