.TH "die_is_func_instance" 9 "die_is_func_instance" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
die_is_func_instance \- Ensure that this DIE is an instance of a subprogram
.SH SYNOPSIS
.B "bool" die_is_func_instance
.BI "(Dwarf_Die *dw_die "  ");"
.SH ARGUMENTS
.IP "dw_die" 12
a DIE
.SH "DESCRIPTION"
Ensure that this DIE is an instance (which has an entry address).
This returns true if \fIdw_die\fP is a function instance. If not, the \fIdw_die\fP
must be a prototype. You can use \fBdie_walk_instances\fP to find actual
instances.
