.TH "dir_double_exhash" 9 "dir_double_exhash" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dir_double_exhash \- Double size of ExHash table
.SH SYNOPSIS
.B "int" dir_double_exhash
.BI "(struct gfs2_inode *dip "  ");"
.SH ARGUMENTS
.IP "dip" 12
The GFS2 dinode
.SH "RETURN"
0 on success, error code on failure
