.TH "dirent_next" 9 "dirent_next" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dirent_next \- Next dirent
.SH SYNOPSIS
.B "int" dirent_next
.BI "(struct gfs2_inode *dip "  ","
.BI "struct buffer_head *bh "  ","
.BI "struct gfs2_dirent **dent "  ");"
.SH ARGUMENTS
.IP "dip" 12
the directory
.IP "bh" 12
The buffer
.IP "dent" 12
Pointer to list of dirents
.SH "RETURN"
0 on success, error code otherwise
