.TH "dm_copy_name_and_uuid" 9 "dm_copy_name_and_uuid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dm_copy_name_and_uuid \- Copy mapped device name & uuid into supplied buffers
.SH SYNOPSIS
.B "int" dm_copy_name_and_uuid
.BI "(struct mapped_device *md "  ","
.BI "char *name "  ","
.BI "char *uuid "  ");"
.SH ARGUMENTS
.IP "md" 12
Pointer to mapped_device
.IP "name" 12
Buffer (size DM_NAME_LEN) for name
.IP "uuid" 12
Buffer (size DM_UUID_LEN) for uuid or empty string if uuid not defined
