.TH "dm_path_uevent" 9 "dm_path_uevent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dm_path_uevent \- called to create a new path event and queue it
.SH SYNOPSIS
.B "void" dm_path_uevent
.BI "(enum dm_uevent_type event_type "  ","
.BI "struct dm_target *ti "  ","
.BI "const char *path "  ","
.BI "unsigned nr_valid_paths "  ");"
.SH ARGUMENTS
.IP "event_type" 12
path event type enum
.IP "ti" 12
pointer to a dm_target
.IP "path" 12
string containing pathname
.IP "nr_valid_paths" 12
number of valid paths remaining
