.TH "dma_fence_chain_walk" 9 "dma_fence_chain_walk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dma_fence_chain_walk \- chain walking function
.SH SYNOPSIS
.B "struct dma_fence *" dma_fence_chain_walk
.BI "(struct dma_fence *fence "  ");"
.SH ARGUMENTS
.IP "fence" 12
current chain node
.SH "DESCRIPTION"
Walk the chain to the next node. Returns the next fence or NULL if we are at
the end of the chain. Garbage collects chain nodes which are already
signaled.
