.TH "dma_chan_is_local" 9 "dma_chan_is_local" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dma_chan_is_local \- checks if the channel is in the same NUMA-node as the CPU
.SH SYNOPSIS
.B "bool" dma_chan_is_local
.BI "(struct dma_chan *chan "  ","
.BI "int cpu "  ");"
.SH ARGUMENTS
.IP "chan" 12
DMA channel to test
.IP "cpu" 12
CPU index which the channel should be close to
.SH "DESCRIPTION"
Returns true if the channel is in the same NUMA-node as the CPU.
