.TH "dma_port_flash_read" 9 "dma_port_flash_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dma_port_flash_read \- Read from active flash region
.SH SYNOPSIS
.B "int" dma_port_flash_read
.BI "(struct tb_dma_port *dma "  ","
.BI "unsigned int address "  ","
.BI "void *buf "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "dma" 12
DMA control port
.IP "address" 12
Address relative to the start of active region
.IP "buf" 12
Buffer where the data is read
.IP "size" 12
Size of the buffer
