.TH "dma_async_device_register" 9 "dma_async_device_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dma_async_device_register \- registers DMA devices found
.SH SYNOPSIS
.B "int" dma_async_device_register
.BI "(struct dma_device *device "  ");"
.SH ARGUMENTS
.IP "device" 12
pointer to \fIstruct dma_device\fP
.SH "DESCRIPTION"
After calling this routine the structure should not be freed except in the
\fBdevice_release\fP callback which will be called after
\fBdma_async_device_unregister\fP is called and no further references are taken.
