.TH "dma_can_mmap" 9 "dma_can_mmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dma_can_mmap \- check if a given device supports dma_mmap_*
.SH SYNOPSIS
.B "bool" dma_can_mmap
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device to check
.SH "DESCRIPTION"
Returns true if \fIdev\fP supports \fBdma_mmap_coherent\fP and \fBdma_mmap_attrs\fP to
map DMA allocations to userspace.
