.TH "dmi_is_end_of_table" 9 "dmi_is_end_of_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dmi_is_end_of_table \- check for end-of-table marker
.SH SYNOPSIS
.B "bool" dmi_is_end_of_table
.BI "(const struct dmi_system_id *dmi "  ");"
.SH ARGUMENTS
.IP "dmi" 12
pointer to the dmi_system_id structure to check
