.TH "dn_route_rx_packet" 9 "dn_route_rx_packet" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dn_route_rx_packet \- Try and find a route for an incoming packet
.SH SYNOPSIS
.B "int" dn_route_rx_packet
.BI "(struct net *net "  ","
.BI "struct sock *sk "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "net" 12
The applicable net namespace
.IP "sk" 12
Socket packet transmitted on
.IP "skb" 12
The packet to find a route for
.SH "RETURN"
result of input function if route is found, error code otherwise
