.TH "do_error" 9 "do_error" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
do_error \- Something unexpected has happened during a lock request
.SH SYNOPSIS
.B "void" do_error
.BI "(struct gfs2_glock *gl "  ","
.BI "const int ret "  ");"
.SH ARGUMENTS
.IP "gl" 12
-- undescribed --
.IP "ret" 12
-- undescribed --
