.TH "do_kernel_restart" 9 "do_kernel_restart" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
do_kernel_restart \- Execute kernel restart handler call chain
.SH SYNOPSIS
.B "void" do_kernel_restart
.BI "(char *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
-- undescribed --
.SH "DESCRIPTION"

Calls functions registered with register_restart_handler.

Expected to be called from machine_restart as last step of the restart
sequence.

Restarts the system immediately if a restart handler function has been
registered. Otherwise does nothing.
