.TH "do_s2io_chk_alarm_bit" 9 "do_s2io_chk_alarm_bit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
do_s2io_chk_alarm_bit \- Check for alarm and incrment the counter
.SH SYNOPSIS
.B "int" do_s2io_chk_alarm_bit
.BI "(u64 value "  ","
.BI "void __iomem *addr "  ","
.BI "unsigned long long *cnt "  ");"
.SH ARGUMENTS
.IP "value" 12
alarm bits
.IP "addr" 12
address value
.IP "cnt" 12
counter variable
.SH "DESCRIPTION"
Check for alarm and increment the counter
Return Value:
1 - if alarm bit set
0 - if alarm bit is not set
