.TH "doc_read_oob" 9 "doc_read_oob" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
doc_read_oob \- Read out of band bytes from flash
.SH SYNOPSIS
.B "int" doc_read_oob
.BI "(struct mtd_info *mtd "  ","
.BI "loff_t from "  ","
.BI "struct mtd_oob_ops *ops "  ");"
.SH ARGUMENTS
.IP "mtd" 12
the device
.IP "from" 12
the offset from first block and first page, in bytes, aligned on page
size
.IP "ops" 12
the mtd oob structure
.SH "DESCRIPTION"
Reads flash memory OOB area of pages.

Returns 0 if read successful, of -EIO, -EINVAL if an error occurred
