.TH "doc_set_asic_mode" 9 "doc_set_asic_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
doc_set_asic_mode \- Set the ASIC mode
.SH SYNOPSIS
.B "void" doc_set_asic_mode
.BI "(struct docg3 *docg3 "  ","
.BI "u8 mode "  ");"
.SH ARGUMENTS
.IP "docg3" 12
the device
.IP "mode" 12
the mode
.SH "DESCRIPTION"
The ASIC can work in 3 modes :
- RESET: all registers are zeroed
- NORMAL: receives and handles commands
- POWERDOWN: minimal poweruse, flash parts shut off
