.TH "dpaa2_io_query_bp_count" 9 "dpaa2_io_query_bp_count" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dpaa2_io_query_bp_count \- Query the number of buffers currently in a buffer pool.
.SH SYNOPSIS
.B "int" dpaa2_io_query_bp_count
.BI "(struct dpaa2_io *d "  ","
.BI "u16 bpid "  ","
.BI "u32 *num "  ");"
.SH ARGUMENTS
.IP "d" 12
the given DPIO object.
.IP "bpid" 12
the index of buffer pool to be queried.
.IP "num" 12
the queried number of buffers in the buffer pool.
.SH "DESCRIPTION"
Return 0 for a successful query, and negative error code if query fails.
