.TH "dprc_cleanup" 9 "dprc_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dprc_cleanup \- function that cleanups a DPRC
.SH SYNOPSIS
.B "int" dprc_cleanup
.BI "(struct fsl_mc_device *mc_dev "  ");"
.SH ARGUMENTS
.IP "mc_dev" 12
Pointer to fsl-mc device representing the DPRC
.SH "DESCRIPTION"
It closes the DPRC device in the MC.
It destroys the interrupt pool associated with this MC bus.
