.TH "dpsw_fdb_add_unicast" 9 "dpsw_fdb_add_unicast" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dpsw_fdb_add_unicast \- Function adds an unicast entry into MAC lookup table
.SH SYNOPSIS
.B "int" dpsw_fdb_add_unicast
.BI "(struct fsl_mc_io *mc_io "  ","
.BI "u32 cmd_flags "  ","
.BI "u16 token "  ","
.BI "u16 fdb_id "  ","
.BI "const struct dpsw_fdb_unicast_cfg *cfg "  ");"
.SH ARGUMENTS
.IP "mc_io" 12
Pointer to MC portal's I/O object
.IP "cmd_flags" 12
Command flags; one or more of 'MC_CMD_FLAG_'
.IP "token" 12
Token of DPSW object
.IP "fdb_id" 12
Forwarding Database Identifier
.IP "cfg" 12
Unicast entry configuration
.SH "RETURN"
Completion status. '0' on Success; Error code otherwise.
