.TH "drbd_resume_next" 9 "drbd_resume_next" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drbd_resume_next \- Resume resync on all devices that may resync now
.SH SYNOPSIS
.B "bool" drbd_resume_next
.BI "(struct drbd_device *device "  ");"
.SH ARGUMENTS
.IP "device" 12
DRBD device.
.SH "DESCRIPTION"
Called from process context only (admin command and worker).
