.TH "driver_probe_done" 9 "driver_probe_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
driver_probe_done \- 
.SH SYNOPSIS
.B "int" driver_probe_done
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"
Determine if the probe sequence is finished or not.

Should somehow figure out how to use a semaphore, not an atomic variable...
