.TH "drm_fb_cma_get_gem_addr" 9 "drm_fb_cma_get_gem_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_fb_cma_get_gem_addr \- Get physical address for framebuffer, for pixel formats where values are grouped in blocks this will get you the beginning of the block
.SH SYNOPSIS
.B "dma_addr_t" drm_fb_cma_get_gem_addr
.BI "(struct drm_framebuffer *fb "  ","
.BI "struct drm_plane_state *state "  ","
.BI "unsigned int plane "  ");"
.SH ARGUMENTS
.IP "fb" 12
The framebuffer
.IP "state" 12
Which state of drm plane
.IP "plane" 12
Which plane
Return the CMA GEM address for given framebuffer.
.SH "DESCRIPTION"
This function will usually be called from the PLANE callback functions.
