.TH "drm_dp_downstream_debug" 9 "drm_dp_downstream_debug" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_dp_downstream_debug \- debug DP branch devices
.SH SYNOPSIS
.B "void" drm_dp_downstream_debug
.BI "(struct seq_file *m "  ","
.BI "const u8 dpcd[DP_RECEIVER_CAP_SIZE] "  ","
.BI "const u8 port_cap[4] "  ","
.BI "const struct edid *edid "  ","
.BI "struct drm_dp_aux *aux "  ");"
.SH ARGUMENTS
.IP "m" 12
pointer for debugfs file
.IP "dpcd" 12
DisplayPort configuration data
.IP "port_cap" 12
port capabilities
.IP "edid" 12
EDID
.IP "aux" 12
DisplayPort AUX channel
