.TH "drm_flip_work_cleanup" 9 "drm_flip_work_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_flip_work_cleanup \- cleans up flip-work
.SH SYNOPSIS
.B "void" drm_flip_work_cleanup
.BI "(struct drm_flip_work *work "  ");"
.SH ARGUMENTS
.IP "work" 12
the flip-work to cleanup
.SH "DESCRIPTION"
Destroy resources allocated for the flip-work
