.TH "drm_dp_mst_put_port_malloc" 9 "drm_dp_mst_put_port_malloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_dp_mst_put_port_malloc \- Decrement the malloc refcount of an MST port
.SH SYNOPSIS
.B "void" drm_dp_mst_put_port_malloc
.BI "(struct drm_dp_mst_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
The \fIstruct drm_dp_mst_port\fP to decrement the malloc refcount of
.SH "DESCRIPTION"
Decrements \fIdrm_dp_mst_port.malloc_kref\fP. When \fIdrm_dp_mst_port.malloc_kref\fP
reaches 0, the memory allocation for \fIport\fP will be released and \fIport\fP may
no longer be used.

See also: \fBdrm_dp_mst_get_port_malloc\fP
