.TH "drm_sched_entity_pop_job" 9 "drm_sched_entity_pop_job" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_sched_entity_pop_job \- get a ready to be scheduled job from the entity
.SH SYNOPSIS
.B "struct drm_sched_job *" drm_sched_entity_pop_job
.BI "(struct drm_sched_entity *entity "  ");"
.SH ARGUMENTS
.IP "entity" 12
entity to get the job from
.SH "DESCRIPTION"
Process all dependencies and try to get one job from the entities queue.
