.TH "drm_dp_send_real_edid_checksum" 9 "drm_dp_send_real_edid_checksum" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_dp_send_real_edid_checksum \- send back real edid checksum value
.SH SYNOPSIS
.B "bool" drm_dp_send_real_edid_checksum
.BI "(struct drm_dp_aux *aux "  ","
.BI "u8 real_edid_checksum "  ");"
.SH ARGUMENTS
.IP "aux" 12
DisplayPort AUX channel
.IP "real_edid_checksum" 12
real edid checksum for the last block
.SH "RETURN"
True on success
