.TH "drm_crtc_vblank_off" 9 "drm_crtc_vblank_off" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_crtc_vblank_off \- disable vblank events on a CRTC
.SH SYNOPSIS
.B "void" drm_crtc_vblank_off
.BI "(struct drm_crtc *crtc "  ");"
.SH ARGUMENTS
.IP "crtc" 12
CRTC in question
.SH "DESCRIPTION"
Drivers can use this function to shut down the vblank interrupt handling when
disabling a crtc. This function ensures that the latest vblank frame count is
stored so that drm_vblank_on can restore it again.

Drivers must use this function when the hardware vblank counter can get
reset, e.g. when suspending or disabling the \fIcrtc\fP in general.
