.TH "drm_client_framebuffer_create" 9 "drm_client_framebuffer_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_client_framebuffer_create \- Create a client framebuffer
.SH SYNOPSIS
.B "struct drm_client_buffer *" drm_client_framebuffer_create
.BI "(struct drm_client_dev *client "  ","
.BI "u32 width "  ","
.BI "u32 height "  ","
.BI "u32 format "  ");"
.SH ARGUMENTS
.IP "client" 12
DRM client
.IP "width" 12
Framebuffer width
.IP "height" 12
Framebuffer height
.IP "format" 12
Buffer format
.SH "DESCRIPTION"
This function creates a \fIdrm_client_buffer\fP which consists of a
\fIdrm_framebuffer\fP backed by a dumb buffer.
Call \fBdrm_client_framebuffer_delete\fP to free the buffer.
.SH "RETURN"
Pointer to a client buffer or an error pointer on failure.
