.TH "drm_atomic_helper_plane_duplicate_state" 9 "drm_atomic_helper_plane_duplicate_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_atomic_helper_plane_duplicate_state \- default state duplicate hook
.SH SYNOPSIS
.B "struct drm_plane_state *" drm_atomic_helper_plane_duplicate_state
.BI "(struct drm_plane *plane "  ");"
.SH ARGUMENTS
.IP "plane" 12
drm plane
.SH "DESCRIPTION"
Default plane state duplicate hook for drivers which don't have their own
subclassed plane state structure.
