.TH "drm_gem_shmem_print_info" 9 "drm_gem_shmem_print_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_gem_shmem_print_info \- Print &drm_gem_shmem_object info for debugfs
.SH SYNOPSIS
.B "void" drm_gem_shmem_print_info
.BI "(struct drm_printer *p "  ","
.BI "unsigned int indent "  ","
.BI "const struct drm_gem_object *obj "  ");"
.SH ARGUMENTS
.IP "p" 12
DRM printer
.IP "indent" 12
Tab indentation level
.IP "obj" 12
GEM object
.SH "DESCRIPTION"
This implements the \fIdrm_gem_object_funcs.info\fP callback.
