.TH "drm_atomic_plane_check" 9 "drm_atomic_plane_check" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_atomic_plane_check \- check plane state
.SH SYNOPSIS
.B "int" drm_atomic_plane_check
.BI "(const struct drm_plane_state *old_plane_state "  ","
.BI "const struct drm_plane_state *new_plane_state "  ");"
.SH ARGUMENTS
.IP "old_plane_state" 12
old plane state to check
.IP "new_plane_state" 12
new plane state to check
.SH "DESCRIPTION"
Provides core sanity checks for plane state.
.SH "RETURN"
Zero on success, error code on failure
