.TH "drm_simple_display_pipe_attach_bridge" 9 "drm_simple_display_pipe_attach_bridge" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_simple_display_pipe_attach_bridge \- Attach a bridge to the display pipe
.SH SYNOPSIS
.B "int" drm_simple_display_pipe_attach_bridge
.BI "(struct drm_simple_display_pipe *pipe "  ","
.BI "struct drm_bridge *bridge "  ");"
.SH ARGUMENTS
.IP "pipe" 12
simple display pipe object
.IP "bridge" 12
bridge to attach
.SH "DESCRIPTION"
Makes it possible to still use the drm_simple_display_pipe helpers when
a DRM bridge has to be used.

Note that you probably want to initialize the pipe by passing a NULL
connector to \fBdrm_simple_display_pipe_init\fP.
.SH "RETURN"
Zero on success, negative error code on failure.
