.TH "drm_property_replace_blob" 9 "drm_property_replace_blob" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_property_replace_blob \- replace a blob property
.SH SYNOPSIS
.B "bool" drm_property_replace_blob
.BI "(struct drm_property_blob **blob "  ","
.BI "struct drm_property_blob *new_blob "  ");"
.SH ARGUMENTS
.IP "blob" 12
a pointer to the member blob to be replaced
.IP "new_blob" 12
the new blob to replace with
.SH "RETURN"
true if the blob was in fact replaced.
