.TH "drm_dp_mst_connector_late_register" 9 "drm_dp_mst_connector_late_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_dp_mst_connector_late_register \- Late MST connector registration
.SH SYNOPSIS
.B "int" drm_dp_mst_connector_late_register
.BI "(struct drm_connector *connector "  ","
.BI "struct drm_dp_mst_port *port "  ");"
.SH ARGUMENTS
.IP "connector" 12
The MST connector
.IP "port" 12
The MST port for this connector
.SH "DESCRIPTION"
Helper to register the remote aux device for this MST port. Drivers should
call this from their mst connector's late_register hook to enable MST aux
devices.
.SH "RETURN"
0 on success, negative error code on failure.
