.TH "drm_dp_pcon_frl_configure_1" 9 "drm_dp_pcon_frl_configure_1" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_dp_pcon_frl_configure_1 \- Set HDMI LINK Configuration-Step1
.SH SYNOPSIS
.B "int" drm_dp_pcon_frl_configure_1
.BI "(struct drm_dp_aux *aux "  ","
.BI "int max_frl_gbps "  ","
.BI "bool concurrent_mode "  ");"
.SH ARGUMENTS
.IP "aux" 12
DisplayPort AUX channel
.IP "max_frl_gbps" 12
maximum frl bw to be configured between PCON and HDMI sink
.IP "concurrent_mode" 12
true if concurrent mode or operation is required,
false otherwise.
.SH "DESCRIPTION"
Returns 0 if success, else returns negative error code.
