.TH "drm_helper_mode_fill_fb_struct" 9 "drm_helper_mode_fill_fb_struct" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_helper_mode_fill_fb_struct \- fill out framebuffer metadata
.SH SYNOPSIS
.B "void" drm_helper_mode_fill_fb_struct
.BI "(struct drm_device *dev "  ","
.BI "struct drm_framebuffer *fb "  ","
.BI "const struct drm_mode_fb_cmd2 *mode_cmd "  ");"
.SH ARGUMENTS
.IP "dev" 12
DRM device
.IP "fb" 12
drm_framebuffer object to fill out
.IP "mode_cmd" 12
metadata from the userspace fb creation request
.SH "DESCRIPTION"
This helper can be used in a drivers fb_create callback to pre-fill the fb's
metadata fields.
