.TH "drm_mode_detailed" 9 "drm_mode_detailed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_mode_detailed \- create a new mode from an EDID detailed timing section
.SH SYNOPSIS
.B "struct drm_display_mode *" drm_mode_detailed
.BI "(struct drm_device *dev "  ","
.BI "struct edid *edid "  ","
.BI "struct detailed_timing *timing "  ","
.BI "u32 quirks "  ");"
.SH ARGUMENTS
.IP "dev" 12
DRM device (needed to create new mode)
.IP "edid" 12
EDID block
.IP "timing" 12
EDID detailed timing info
.IP "quirks" 12
quirks to apply
.SH "DESCRIPTION"
An EDID detailed timing block contains enough info for us to create and
return a new struct drm_display_mode.
