.TH "drm_sched_job_done" 9 "drm_sched_job_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_sched_job_done \- complete a job
.SH SYNOPSIS
.B "void" drm_sched_job_done
.BI "(struct drm_sched_job *s_job "  ");"
.SH ARGUMENTS
.IP "s_job" 12
pointer to the job which is done
.SH "DESCRIPTION"
Finish the job's fence and wake up the worker thread.
