.TH "drm_rect_clip_scaled" 9 "drm_rect_clip_scaled" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_rect_clip_scaled \- perform a scaled clip operation
.SH SYNOPSIS
.B "bool" drm_rect_clip_scaled
.BI "(struct drm_rect *src "  ","
.BI "struct drm_rect *dst "  ","
.BI "const struct drm_rect *clip "  ");"
.SH ARGUMENTS
.IP "src" 12
source window rectangle
.IP "dst" 12
destination window rectangle
.IP "clip" 12
clip rectangle
.SH "DESCRIPTION"
Clip rectangle \fIdst\fP by rectangle \fIclip\fP. Clip rectangle \fIsrc\fP by the
the corresponding amounts, retaining the vertical and horizontal scaling
factors from \fIsrc\fP to \fIdst\fP.

true if rectangle \fIdst\fP is still visible after being clipped,
false otherwise.
.SH "RETURN"
