.TH "drm_mm_init" 9 "drm_mm_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_mm_init \- initialize a drm-mm allocator
.SH SYNOPSIS
.B "void" drm_mm_init
.BI "(struct drm_mm *mm "  ","
.BI "u64 start "  ","
.BI "u64 size "  ");"
.SH ARGUMENTS
.IP "mm" 12
the drm_mm structure to initialize
.IP "start" 12
start of the range managed by \fImm\fP
.IP "size" 12
end of the range managed by \fImm\fP
.SH "DESCRIPTION"
Note that \fImm\fP must be cleared to 0 before calling this function.
