.TH "drm_atomic_helper_damage_merged" 9 "drm_atomic_helper_damage_merged" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_atomic_helper_damage_merged \- Merged plane damage
.SH SYNOPSIS
.B "bool" drm_atomic_helper_damage_merged
.BI "(const struct drm_plane_state *old_state "  ","
.BI "struct drm_plane_state *state "  ","
.BI "struct drm_rect *rect "  ");"
.SH ARGUMENTS
.IP "old_state" 12
Old plane state for validation.
.IP "state" 12
Plane state from which to iterate the damage clips.
.IP "rect" 12
Returns the merged damage rectangle
.SH "DESCRIPTION"
This function merges any valid plane damage clips into one rectangle and
returns it in \fIrect\fP.

For details see: \fBdrm_atomic_helper_damage_iter_init\fP and
\fBdrm_atomic_helper_damage_iter_next\fP.
.SH "RETURN"
True if there is valid plane damage otherwise false.
