.TH "drm_syncobj_open" 9 "drm_syncobj_open" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_syncobj_open \- initalizes syncobj file-private structures at devnode open time
.SH SYNOPSIS
.B "void" drm_syncobj_open
.BI "(struct drm_file *file_private "  ");"
.SH ARGUMENTS
.IP "file_private" 12
drm file-private structure to set up
.SH "DESCRIPTION"
Called at device open time, sets up the structure for handling refcounting
of sync objects.
