.TH "drm_lease_filter_crtcs" 9 "drm_lease_filter_crtcs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_lease_filter_crtcs \- restricted crtc set to leased values (idr_mutex not held)
.SH SYNOPSIS
.B "uint32_t" drm_lease_filter_crtcs
.BI "(struct drm_file *file_priv "  ","
.BI "uint32_t crtcs_in "  ");"
.SH ARGUMENTS
.IP "file_priv" 12
requestor file
.IP "crtcs_in" 12
bitmask of crtcs to check
.SH "DESCRIPTION"
Reconstructs a crtc mask based on the crtcs which are visible
through the specified file.
