.TH "drm_bridge_chain_enable" 9 "drm_bridge_chain_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_bridge_chain_enable \- enables all bridges in the encoder chain
.SH SYNOPSIS
.B "void" drm_bridge_chain_enable
.BI "(struct drm_bridge *bridge "  ");"
.SH ARGUMENTS
.IP "bridge" 12
bridge control structure
.SH "DESCRIPTION"
Calls \fIdrm_bridge_funcs.enable\fP op for all the bridges in the encoder
chain, starting from the first bridge to the last. These are called
after completing the encoder's commit op.

Note that the bridge passed should be the one closest to the encoder
