.TH "dump_holder" 9 "dump_holder" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dump_holder \- print information about a glock holder
.SH SYNOPSIS
.B "void" dump_holder
.BI "(struct seq_file *seq "  ","
.BI "const struct gfs2_holder *gh "  ","
.BI "const char *fs_id_buf "  ");"
.SH ARGUMENTS
.IP "seq" 12
the seq_file struct
.IP "gh" 12
the glock holder
.IP "fs_id_buf" 12
pointer to file system id (if requested)
