.TH "dvb_ca_en50221_parse_attributes" 9 "dvb_ca_en50221_parse_attributes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dvb_ca_en50221_parse_attributes \- Parse attribute memory of a CAM module, extracting Config register, and checking it is a DVB CAM module.
.SH SYNOPSIS
.B "int" dvb_ca_en50221_parse_attributes
.BI "(struct dvb_ca_private *ca "  ","
.BI "int slot "  ");"
.SH ARGUMENTS
.IP "ca" 12
CA instance.
.IP "slot" 12
Slot id.
.SH "RETURN"
0 on success, <0 on failure.
