.TH "dw_mci_exynos_suspend_noirq" 9 "dw_mci_exynos_suspend_noirq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dw_mci_exynos_suspend_noirq \- Exynos-specific suspend code
.SH SYNOPSIS
.B "int" dw_mci_exynos_suspend_noirq
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to suspend (this device)
.SH "DESCRIPTION"
This ensures that device will be in runtime active state in
dw_mci_exynos_resume_noirq after calling \fBpm_runtime_force_resume\fP
