.TH "dwarf_read_encoded_value" 9 "dwarf_read_encoded_value" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwarf_read_encoded_value \- return the decoded value at @addr
.SH SYNOPSIS
.B "int" dwarf_read_encoded_value
.BI "(char *addr "  ","
.BI "unsigned long *val "  ","
.BI "char encoding "  ");"
.SH ARGUMENTS
.IP "addr" 12
the address of the encoded value
.IP "val" 12
where to write the decoded value
.IP "encoding" 12
the encoding with which we can decode \fIaddr\fP

GCC emits encoded address in the .eh_frame FDE entries. Decode
the value at \fIaddr\fP using \fIencoding\fP. The decoded value is written
to \fIval\fP and the number of bytes read is returned.
