.TH "dwc2_uframe_unschedule" 9 "dwc2_uframe_unschedule" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc2_uframe_unschedule \- Undoes dwc2_uframe_schedule().
.SH SYNOPSIS
.B "void" dwc2_uframe_unschedule
.BI "(struct dwc2_hsotg *hsotg "  ","
.BI "struct dwc2_qh *qh "  ");"
.SH ARGUMENTS
.IP "hsotg" 12
The HCD state structure for the DWC OTG controller.
.IP "qh" 12
QH for the periodic transfer.
