.TH "dwc2_hsotg_epint" 9 "dwc2_hsotg_epint" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc2_hsotg_epint \- handle an in/out endpoint interrupt
.SH SYNOPSIS
.B "void" dwc2_hsotg_epint
.BI "(struct dwc2_hsotg *hsotg "  ","
.BI "unsigned int idx "  ","
.BI "int dir_in "  ");"
.SH ARGUMENTS
.IP "hsotg" 12
The driver state
.IP "idx" 12
The index for the endpoint (0..15)
.IP "dir_in" 12
Set if this is an IN endpoint
.SH "DESCRIPTION"
Process and clear any interrupt pending for an individual endpoint
