.TH "dwc2_hsotg_irq_fifoempty" 9 "dwc2_hsotg_irq_fifoempty" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc2_hsotg_irq_fifoempty \- TX FIFO empty interrupt handler
.SH SYNOPSIS
.B "void" dwc2_hsotg_irq_fifoempty
.BI "(struct dwc2_hsotg *hsotg "  ","
.BI "bool periodic "  ");"
.SH ARGUMENTS
.IP "hsotg" 12
The device state:
.IP "periodic" 12
True if this is a periodic FIFO interrupt
