.TH "dwc2_wait_for_mode" 9 "dwc2_wait_for_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc2_wait_for_mode \- Waits for the controller mode.
.SH SYNOPSIS
.B "void" dwc2_wait_for_mode
.BI "(struct dwc2_hsotg *hsotg "  ","
.BI "bool host_mode "  ");"
.SH ARGUMENTS
.IP "hsotg" 12
Programming view of the DWC_otg controller.
.IP "host_mode" 12
If true, waits for host mode, otherwise device mode.
