.TH "dwc2_qh_init" 9 "dwc2_qh_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc2_qh_init \- Initializes a QH structure
.SH SYNOPSIS
.B "void" dwc2_qh_init
.BI "(struct dwc2_hsotg *hsotg "  ","
.BI "struct dwc2_qh *qh "  ","
.BI "struct dwc2_hcd_urb *urb "  ","
.BI "gfp_t mem_flags "  ");"
.SH ARGUMENTS
.IP "hsotg" 12
The HCD state structure for the DWC OTG controller
.IP "qh" 12
The QH to init
.IP "urb" 12
Holds the information about the device/endpoint needed to initialize
the QH
.IP "mem_flags" 12
Flags for allocating memory.
