.TH "e1000_rar_set_pch2lan" 9 "e1000_rar_set_pch2lan" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
e1000_rar_set_pch2lan \- Set receive address register
.SH SYNOPSIS
.B "int" e1000_rar_set_pch2lan
.BI "(struct e1000_hw *hw "  ","
.BI "u8 *addr "  ","
.BI "u32 index "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "addr" 12
pointer to the receive address
.IP "index" 12
receive address array register

Sets the receive address array register at index to the address passed
in by addr.  For 82579, RAR[0] is the base address register that is to
contain the MAC address but RAR[1-6] are reserved for manageability (ME).
Use SHRA[0-3] in place of those reserved for ME.
