.TH "e1000_get_link_up_info_vf" 9 "e1000_get_link_up_info_vf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
e1000_get_link_up_info_vf \- Gets link info.
.SH SYNOPSIS
.B "s32" e1000_get_link_up_info_vf
.BI "(struct e1000_hw *hw "  ","
.BI "u16 *speed "  ","
.BI "u16 *duplex "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "speed" 12
pointer to 16 bit value to store link speed.
.IP "duplex" 12
pointer to 16 bit value to store duplex.

Since we cannot read the PHY and get accurate link info, we must rely upon
the status register's data which is often stale and inaccurate.
