.TH "e1000_obtain_mbx_lock_vf" 9 "e1000_obtain_mbx_lock_vf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
e1000_obtain_mbx_lock_vf \- obtain mailbox lock
.SH SYNOPSIS
.B "s32" e1000_obtain_mbx_lock_vf
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure

return SUCCESS if we obtained the mailbox lock
