.TH "e1000_get_auto_rd_done" 9 "e1000_get_auto_rd_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
e1000_get_auto_rd_done \- 
.SH SYNOPSIS
.B "s32" e1000_get_auto_rd_done
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
Struct containing variables accessed by shared code
.SH "DESCRIPTION"
Check for EEPROM Auto Read bit done.
.SH "RETURN"
- E1000_ERR_RESET if fail to reset MAC
E1000_SUCCESS at any other case.
