.TH "ecryptfs_write_packet_length" 9 "ecryptfs_write_packet_length" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ecryptfs_write_packet_length \- 
.SH SYNOPSIS
.B "int" ecryptfs_write_packet_length
.BI "(char *dest "  ","
.BI "size_t size "  ","
.BI "size_t *packet_size_length "  ");"
.SH ARGUMENTS
.IP "dest" 12
The byte array target into which to write the length. Must
have at least ECRYPTFS_MAX_PKT_LEN_SIZE bytes allocated.
.IP "size" 12
The length to write.
.IP "packet_size_length" 12
The number of bytes used to encode the packet
length is written to this address.
.SH "DESCRIPTION"
Returns zero on success; non-zero on error.
