.TH "ecryptfs_process_flags" 9 "ecryptfs_process_flags" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ecryptfs_process_flags \- 
.SH SYNOPSIS
.B "void" ecryptfs_process_flags
.BI "(struct ecryptfs_crypt_stat *crypt_stat "  ","
.BI "char *page_virt "  ","
.BI "int *bytes_read "  ");"
.SH ARGUMENTS
.IP "crypt_stat" 12
The cryptographic context
.IP "page_virt" 12
Source data to be parsed
.IP "bytes_read" 12
Updated with the number of bytes read
