.TH "ecryptfs_truncate" 9 "ecryptfs_truncate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ecryptfs_truncate \- 
.SH SYNOPSIS
.B "int" ecryptfs_truncate
.BI "(struct dentry *dentry "  ","
.BI "loff_t new_length "  ");"
.SH ARGUMENTS
.IP "dentry" 12
The ecryptfs layer dentry
.IP "new_length" 12
The length to expand the file to
.SH "DESCRIPTION"
Simple function that handles the truncation of an eCryptfs inode and
its corresponding lower inode.

Returns zero on success; non-zero otherwise
