.TH "ecryptfs_init_kmem_caches" 9 "ecryptfs_init_kmem_caches" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ecryptfs_init_kmem_caches \- 
.SH SYNOPSIS
.B "int" ecryptfs_init_kmem_caches
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Returns zero on success; non-zero otherwise
