.TH "ecryptfs_privileged_open" 9 "ecryptfs_privileged_open" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ecryptfs_privileged_open \- 
.SH SYNOPSIS
.B "int" ecryptfs_privileged_open
.BI "(struct file **lower_file "  ","
.BI "struct dentry *lower_dentry "  ","
.BI "struct vfsmount *lower_mnt "  ","
.BI "const struct cred *cred "  ");"
.SH ARGUMENTS
.IP "lower_file" 12
Result of dentry_open by root on lower dentry
.IP "lower_dentry" 12
Lower dentry for file to open
.IP "lower_mnt" 12
Lower vfsmount for file to open
.IP "cred" 12
-- undescribed --
.SH "DESCRIPTION"
This function gets a r/w file opened against the lower dentry.

Returns zero on success; non-zero otherwise
