.TH "eeh_pe_update_time_stamp" 9 "eeh_pe_update_time_stamp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeh_pe_update_time_stamp \- Update PE's frozen time stamp
.SH SYNOPSIS
.B "void" eeh_pe_update_time_stamp
.BI "(struct eeh_pe *pe "  ");"
.SH ARGUMENTS
.IP "pe" 12
EEH PE
.SH "DESCRIPTION"
We have time stamp for each PE to trace its time of getting
frozen in last hour. The function should be called to update
the time stamp on first error of the specific PE. On the other
handle, we needn't account for errors happened in last hour.
