.TH "eeh_handle_special_event" 9 "eeh_handle_special_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeh_handle_special_event \- Handle EEH events without a specific failing PE
.SH SYNOPSIS
.B "void" eeh_handle_special_event
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Called when an EEH event is detected but can't be narrowed down to a
specific PE.  Iterates through possible failures and handles them as
necessary.
