.TH "eeh_pe_get" 9 "eeh_pe_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeh_pe_get \- Search PE based on the given address
.SH SYNOPSIS
.B "struct eeh_pe *" eeh_pe_get
.BI "(struct pci_controller *phb "  ","
.BI "int pe_no "  ");"
.SH ARGUMENTS
.IP "phb" 12
PCI controller
.IP "pe_no" 12
PE number
.SH "DESCRIPTION"
Search the corresponding PE based on the specified address which
is included in the eeh device. The function is used to check if
the associated PE has been created against the PE address. It's
notable that the PE address has 2 format: traditional PE address
which is composed of PCI bus/device/function number, or unified
PE address.
