.TH "eeprom_93cx6_wren" 9 "eeprom_93cx6_wren" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeprom_93cx6_wren \- set the write enable state
.SH SYNOPSIS
.B "void" eeprom_93cx6_wren
.BI "(struct eeprom_93cx6 *eeprom "  ","
.BI "bool enable "  ");"
.SH ARGUMENTS
.IP "eeprom" 12
Pointer to eeprom structure
.IP "enable" 12
true to enable writes, otherwise disable writes
.SH "DESCRIPTION"
Set the EEPROM write enable state to either allow or deny
writes depending on the \fIenable\fP value.
