.TH "efa_com_admin_destroy" 9 "efa_com_admin_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
efa_com_admin_destroy \- Destroy the admin and the async events queues.
.SH SYNOPSIS
.B "void" efa_com_admin_destroy
.BI "(struct efa_com_dev *edev "  ");"
.SH ARGUMENTS
.IP "edev" 12
EFA communication layer struct
