.TH "efi_random_get_seed" 9 "efi_random_get_seed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
efi_random_get_seed \- provide random seed as configuration table
.SH SYNOPSIS
.B "efi_status_t" efi_random_get_seed
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

The EFI_RNG_PROTOCOL is used to read random bytes. These random bytes are
saved as a configuration table which can be used as entropy by the kernel
for the initialization of its pseudo random number generator.

If the EFI_RNG_PROTOCOL is not available or there are not enough random bytes
available, the configuration table will not be installed and an error code
will be returned.
.SH "RETURN"
status code
