.TH "efi_printk" 9 "efi_printk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
efi_printk \- Print a kernel message
.SH SYNOPSIS
.B "int" efi_printk
.BI "(const char *fmt "  ","
.BI "... "  ");"
.SH ARGUMENTS
.IP "fmt" 12
format string
.IP "..." 12
variable arguments
.SH "DESCRIPTION"
The first letter of the format string is used to determine the logging level
of the message. If the level is less then the current EFI logging level, the
message is suppressed. The message will be truncated to 255 bytes.
.SH "RETURN"
number of printed characters
