.TH "ei_receive" 9 "ei_receive" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ei_receive \- receive some packets
.SH SYNOPSIS
.B "void" ei_receive
.BI "(struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
network device with which receive will be run
.SH "DESCRIPTION"
We have a good packet(s), get it/them out of the buffers.
Called with lock held.
