.TH "elf_read_phdrs" 9 "elf_read_phdrs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
elf_read_phdrs \- read the program headers from the buffer
.SH SYNOPSIS
.B "int" elf_read_phdrs
.BI "(const char *buf "  ","
.BI "size_t len "  ","
.BI "struct kexec_elf_info *elf_info "  ");"
.SH ARGUMENTS
.IP "buf" 12
-- undescribed --
.IP "len" 12
-- undescribed --
.IP "elf_info" 12
-- undescribed --
.SH "DESCRIPTION"

This function assumes that the program header table was checked for sanity.
Use \fBelf_is_ehdr_sane\fP if it wasn't.
