.TH "emac_setmac" 9 "emac_setmac" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
emac_setmac \- Set mac address in the adapter (internal function)
.SH SYNOPSIS
.B "void" emac_setmac
.BI "(struct emac_priv *priv "  ","
.BI "u32 ch "  ","
.BI "char *mac_addr "  ");"
.SH ARGUMENTS
.IP "priv" 12
The DaVinci EMAC private adapter structure
.IP "ch" 12
RX channel number
.IP "mac_addr" 12
MAC address to set in device
.SH "DESCRIPTION"
Called internally to set the mac address of the adapter (Device)

Returns success (0) or appropriate error code (none as of now)
