.TH "ep93xx_dma_synchronize" 9 "ep93xx_dma_synchronize" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ep93xx_dma_synchronize \- Synchronizes the termination of transfers to the current context.
.SH SYNOPSIS
.B "void" ep93xx_dma_synchronize
.BI "(struct dma_chan *chan "  ");"
.SH ARGUMENTS
.IP "chan" 12
channel
.SH "DESCRIPTION"
Synchronizes the DMA channel termination to the current context. When this
function returns it is guaranteed that all transfers for previously issued
descriptors have stopped and and it is safe to free the memory associated
with them. Furthermore it is guaranteed that all complete callback functions
for a previously submitted descriptor have finished running and it is safe to
free resources accessed from within the complete callbacks.
