.TH "ep_end_in_req" 9 "ep_end_in_req" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ep_end_in_req \- Ends endpoint IN request
.SH SYNOPSIS
.B "void" ep_end_in_req
.BI "(struct pxa_ep *ep "  ","
.BI "struct pxa27x_request *req "  ","
.BI "unsigned long *pflags "  ");"
.SH ARGUMENTS
.IP "ep" 12
physical endpoint
.IP "req" 12
pxa request
.IP "pflags" 12
flags of previous \fBspinlock_irq_save\fP or NULL if no lock held
.SH "CONTEXT"
ep->lock held or released (see \fBreq_done\fP)
.SH "DESCRIPTION"
Ends endpoint IN request (completes usb request).
