.TH "epf_ntb_epc_create" 9 "epf_ntb_epc_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
epf_ntb_epc_create \- Create and initialize NTB EPC interface
.SH SYNOPSIS
.B "int" epf_ntb_epc_create
.BI "(struct epf_ntb *ntb "  ");"
.SH ARGUMENTS
.IP "ntb" 12
NTB device that facilitates communication between HOST1 and HOST2
.SH "DESCRIPTION"
Get a reference to EPC device and bind NTB function device to that EPC
for each of the interface. It is also a wrapper to
\fBepf_ntb_epc_create_interface\fP to allocate memory for NTB EPC interface
and initialize it
