.TH "evm_write_key" 9 "evm_write_key" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
evm_write_key \- write() for <securityfs>/evm
.SH SYNOPSIS
.B "ssize_t" evm_write_key
.BI "(struct file *file "  ","
.BI "const char __user *buf "  ","
.BI "size_t count "  ","
.BI "loff_t *ppos "  ");"
.SH ARGUMENTS
.IP "file" 12
file pointer, not actually used
.IP "buf" 12
where to get the data from
.IP "count" 12
bytes sent
.IP "ppos" 12
where to start
.SH "DESCRIPTION"
Used to signal that key is on the kernel key ring.
- get the integrity hmac key from the kernel key ring
- create list of hmac protected extended attributes
Returns number of bytes written or error code, as appropriate
