.TH "ext4_inode_to_goal_block" 9 "ext4_inode_to_goal_block" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ext4_inode_to_goal_block \- return a hint for block allocation
.SH SYNOPSIS
.B "ext4_fsblk_t" ext4_inode_to_goal_block
.BI "(struct inode *inode "  ");"
.SH ARGUMENTS
.IP "inode" 12
inode for block allocation

Return the ideal location to start allocating blocks for a
newly created inode.
