.TH "exynos4_read_count_64" 9 "exynos4_read_count_64" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
exynos4_read_count_64 \- Read all 64-bits of the global counter
.SH SYNOPSIS
.B "u64" exynos4_read_count_64
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This will read all 64-bits of the global counter taking care to make sure
that the upper and lower half match.  Note that reading the MCT can be quite
slow (hundreds of nanoseconds) so you should use the 32-bit (lower half
only) version when possible.

Returns the number of cycles in the global counter.
