.TH "exynos5_dmc_switch_to_bypass_configuration" 9 "exynos5_dmc_switch_to_bypass_configuration" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
exynos5_dmc_switch_to_bypass_configuration \- Switching to temporary clock
.SH SYNOPSIS
.B "int" exynos5_dmc_switch_to_bypass_configuration
.BI "(struct exynos5_dmc *dmc "  ","
.BI "unsigned long target_rate "  ","
.BI "unsigned long target_volt "  ");"
.SH ARGUMENTS
.IP "dmc" 12
DMC device for which the switching is going to happen
.IP "target_rate" 12
new frequency which is going to be set as a final
.IP "target_volt" 12
new voltage which is going to be set as a final
.SH "DESCRIPTION"
Function configures DMC and clocks for operating in temporary 'bypass' mode.
This mode is used only temporary but if required, changes voltage and timings
for DRAM chips. It switches the main clock to stable clock source for the
period of the main PLL reconfiguration.
