.TH "exynos5_dmc_set_pause_on_switching" 9 "exynos5_dmc_set_pause_on_switching" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
exynos5_dmc_set_pause_on_switching \- Controls a pause feature in DMC
.SH SYNOPSIS
.B "int" exynos5_dmc_set_pause_on_switching
.BI "(struct exynos5_dmc *dmc "  ");"
.SH ARGUMENTS
.IP "dmc" 12
device which is used for changing this feature
.SH "DESCRIPTION"
There is a need of pausing DREX DMC when divider or MUX in clock tree
changes its configuration. In such situation access to the memory is blocked
in DMC automatically. This feature is used when clock frequency change
request appears and touches clock tree.
