.TH "fas216_eh_device_reset" 9 "fas216_eh_device_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fas216_eh_device_reset \- Reset the device associated with this command
.SH SYNOPSIS
.B "int" fas216_eh_device_reset
.BI "(struct scsi_cmnd *SCpnt "  ");"
.SH ARGUMENTS
.IP "SCpnt" 12
command specifing device to reset
.SH "DESCRIPTION"
Reset the device associated with this command.
.SH "RETURN"
FAILED if unable to reset.
.SH "NOTES"
We won't be re-entered, so we'll only have one device
reset on the go at one time.
