.TH "fas216_send_messageout" 9 "fas216_send_messageout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fas216_send_messageout \- handle bus service to send a message
.SH SYNOPSIS
.B "void" fas216_send_messageout
.BI "(FAS216_Info *info "  ","
.BI "int start "  ");"
.SH ARGUMENTS
.IP "info" 12
interface which caused bus service
.IP "start" 12
-- undescribed --
.SH "DESCRIPTION"
Handle bus service to send a message.
.SH "NOTE"
We do not allow the device to change the data direction!
