.TH "fas216_init" 9 "fas216_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fas216_init \- initialise FAS/NCR/AMD SCSI structures.
.SH SYNOPSIS
.B "int" fas216_init
.BI "(struct Scsi_Host *host "  ");"
.SH ARGUMENTS
.IP "host" 12
a driver-specific filled-out structure
.SH "DESCRIPTION"
Initialise FAS/NCR/AMD SCSI structures.
.SH "RETURN"
0 on success
