.TH "fb_copy_cmap" 9 "fb_copy_cmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fb_copy_cmap \- copy a colormap
.SH SYNOPSIS
.B "int" fb_copy_cmap
.BI "(const struct fb_cmap *from "  ","
.BI "struct fb_cmap *to "  ");"
.SH ARGUMENTS
.IP "from" 12
frame buffer colormap structure
.IP "to" 12
frame buffer colormap structure

Copy contents of colormap from \fIfrom\fP to \fIto\fP.
