.TH "fb_var_to_videomode" 9 "fb_var_to_videomode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fb_var_to_videomode \- convert fb_var_screeninfo to fb_videomode
.SH SYNOPSIS
.B "void" fb_var_to_videomode
.BI "(struct fb_videomode *mode "  ","
.BI "const struct fb_var_screeninfo *var "  ");"
.SH ARGUMENTS
.IP "mode" 12
pointer to struct fb_videomode
.IP "var" 12
pointer to struct fb_var_screeninfo
