.TH "fc_exch_mgr_del" 9 "fc_exch_mgr_del" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_exch_mgr_del \- Delete an EM from a local port's list
.SH SYNOPSIS
.B "void" fc_exch_mgr_del
.BI "(struct fc_exch_mgr_anchor *ema "  ");"
.SH ARGUMENTS
.IP "ema" 12
The exchange manager anchor identifying the EM to be deleted
