.TH "fc_exch_done" 9 "fc_exch_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_exch_done \- Indicate that an exchange/sequence tuple is complete and the memory allocated for the related objects may be freed.
.SH SYNOPSIS
.B "void" fc_exch_done
.BI "(struct fc_seq *sp "  ");"
.SH ARGUMENTS
.IP "sp" 12
The sequence that has completed
.SH "NOTE"
May sleep if invoked from outside a response handler.
