.TH "fc_eh_abort" 9 "fc_eh_abort" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_eh_abort \- Abort a command
.SH SYNOPSIS
.B "int" fc_eh_abort
.BI "(struct scsi_cmnd *sc_cmd "  ");"
.SH ARGUMENTS
.IP "sc_cmd" 12
The SCSI command to abort
.SH "DESCRIPTION"
From SCSI host template.
Send an ABTS to the target device and wait for the response.
