.TH "fc_fcp_can_queue_ramp_down" 9 "fc_fcp_can_queue_ramp_down" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_fcp_can_queue_ramp_down \- reduces can_queue
.SH SYNOPSIS
.B "bool" fc_fcp_can_queue_ramp_down
.BI "(struct fc_lport *lport "  ");"
.SH ARGUMENTS
.IP "lport" 12
lport to reduce can_queue
.SH "DESCRIPTION"
If we are getting memory allocation failures, then we may
be trying to execute too many commands. We let the running
commands complete or timeout, then try again with a reduced
can_queue. Eventually we will hit the point where we run
on all reserved structs.
