.TH "fc_lport_reset" 9 "fc_lport_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_lport_reset \- Reset a local port
.SH SYNOPSIS
.B "int" fc_lport_reset
.BI "(struct fc_lport *lport "  ");"
.SH ARGUMENTS
.IP "lport" 12
The local port which should be reset
.SH "DESCRIPTION"
Locking Note: This functions should not be called with the
lport lock held.
