.TH "fc_rport_recv_prlo_req" 9 "fc_rport_recv_prlo_req" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_rport_recv_prlo_req \- Handler for process logout (PRLO) requests
.SH SYNOPSIS
.B "void" fc_rport_recv_prlo_req
.BI "(struct fc_rport_priv *rdata "  ","
.BI "struct fc_frame *rx_fp "  ");"
.SH ARGUMENTS
.IP "rdata" 12
The remote port that sent the PRLO request
.IP "rx_fp" 12
The PRLO request frame
