.TH "fc_rport_recv_logo_req" 9 "fc_rport_recv_logo_req" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_rport_recv_logo_req \- Handler for logout (LOGO) requests
.SH SYNOPSIS
.B "void" fc_rport_recv_logo_req
.BI "(struct fc_lport *lport "  ","
.BI "struct fc_frame *fp "  ");"
.SH ARGUMENTS
.IP "lport" 12
The local port that received the LOGO request
.IP "fp" 12
The LOGO request frame
.SH "DESCRIPTION"
Reference counting: drops kref on return
