.TH "fc_starget_delete" 9 "fc_starget_delete" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_starget_delete \- called to delete the scsi descendants of an rport
.SH SYNOPSIS
.B "void" fc_starget_delete
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
remote port to be operated on.
.SH "DESCRIPTION"
Deletes target and all sdevs.
