.TH "fcntl_setlease" 9 "fcntl_setlease" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcntl_setlease \- sets a lease on an open file
.SH SYNOPSIS
.B "int" fcntl_setlease
.BI "(unsigned int fd "  ","
.BI "struct file *filp "  ","
.BI "long arg "  ");"
.SH ARGUMENTS
.IP "fd" 12
open file descriptor
.IP "filp" 12
file pointer
.IP "arg" 12
type of lease to obtain

Call this fcntl to establish a lease on the file.
Note that you also need to call F_SETSIG to
receive a signal when the lease is broken.
