.TH "fcoe_interface_cleanup" 9 "fcoe_interface_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_interface_cleanup \- Clean up a FCoE interface
.SH SYNOPSIS
.B "void" fcoe_interface_cleanup
.BI "(struct fcoe_interface *fcoe "  ");"
.SH ARGUMENTS
.IP "fcoe" 12
The FCoE interface to be cleaned up
