.TH "fcoe_transport_attach" 9 "fcoe_transport_attach" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_transport_attach \- Attaches an FCoE transport
.SH SYNOPSIS
.B "int" fcoe_transport_attach
.BI "(struct fcoe_transport *ft "  ");"
.SH ARGUMENTS
.IP "ft" 12
The fcoe transport to be attached
.SH "RETURN"
0 for success
