.TH "fcoe_libfc_config" 9 "fcoe_libfc_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_libfc_config \- Sets up libfc related properties for local port
.SH SYNOPSIS
.B "int" fcoe_libfc_config
.BI "(struct fc_lport *lport "  ","
.BI "struct fcoe_ctlr *fip "  ","
.BI "const struct libfc_function_template *tt "  ","
.BI "int init_fcp "  ");"
.SH ARGUMENTS
.IP "lport" 12
The local port to configure libfc for
.IP "fip" 12
The FCoE controller in use by the local port
.IP "tt" 12
The libfc function template
.IP "init_fcp" 12
If non-zero, the FCP portion of libfc should be initialized
.SH "RETURN"
0 for success
