.TH "fcoe_ctlr_recv_handler" 9 "fcoe_ctlr_recv_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_ctlr_recv_handler \- Receive a FIP frame
.SH SYNOPSIS
.B "int" fcoe_ctlr_recv_handler
.BI "(struct fcoe_ctlr *fip "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "fip" 12
The FCoE controller that received the frame
.IP "skb" 12
The received FIP frame
.SH "DESCRIPTION"
Returns non-zero if the frame is dropped.
