.TH "fcoe_ctlr_timer_work" 9 "fcoe_ctlr_timer_work" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_ctlr_timer_work \- Worker thread function for timer work
.SH SYNOPSIS
.B "void" fcoe_ctlr_timer_work
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
Handle to a FCoE controller
.SH "DESCRIPTION"
Ages FCFs.  Triggers FCF selection if possible.
Sends keep-alives and resets.
