.TH "fcoe_ddp_done" 9 "fcoe_ddp_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_ddp_done \- Call a LLD's ddp_done through the net device
.SH SYNOPSIS
.B "int" fcoe_ddp_done
.BI "(struct fc_lport *lport "  ","
.BI "u16 xid "  ");"
.SH ARGUMENTS
.IP "lport" 12
The local port to complete DDP on
.IP "xid" 12
The exchange ID for this DDP transfer
.SH "RETURN"
the length of data that have been completed by DDP
