.TH "fcoe_hostlist_lookup_port" 9 "fcoe_hostlist_lookup_port" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_hostlist_lookup_port \- Find the FCoE interface associated with a net device
.SH SYNOPSIS
.B "struct fcoe_interface *" fcoe_hostlist_lookup_port
.BI "(const struct net_device *netdev "  ");"
.SH ARGUMENTS
.IP "netdev" 12
The net device used as a key
.SH "DESCRIPTION"
Locking: Must be called with the RNL mutex held.
.SH "RETURN"
NULL or the FCoE interface
