.TH "fec_ptp_init" 9 "fec_ptp_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fec_ptp_init \- 
.SH SYNOPSIS
.B "void" fec_ptp_init
.BI "(struct platform_device *pdev "  ","
.BI "int irq_idx "  ");"
.SH ARGUMENTS
.IP "pdev" 12
The FEC network adapter
.IP "irq_idx" 12
the interrupt index
.SH "DESCRIPTION"
This function performs the required steps for enabling ptp
support. If ptp support has already been loaded it simply calls the
cyclecounter init routine and exits.
