.TH "fec_ptp_adjfreq" 9 "fec_ptp_adjfreq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fec_ptp_adjfreq \- adjust ptp cycle frequency
.SH SYNOPSIS
.B "int" fec_ptp_adjfreq
.BI "(struct ptp_clock_info *ptp "  ","
.BI "s32 ppb "  ");"
.SH ARGUMENTS
.IP "ptp" 12
the ptp clock structure
.IP "ppb" 12
parts per billion adjustment from base
.SH "DESCRIPTION"
Adjust the frequency of the ptp cycle counter by the
indicated ppb from the base frequency.

Because ENET hardware frequency adjust is complex,
using software method to do that.
