.TH "fm10k_setup_rx_resources" 9 "fm10k_setup_rx_resources" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_setup_rx_resources \- allocate Rx resources (Descriptors)
.SH SYNOPSIS
.B "int" fm10k_setup_rx_resources
.BI "(struct fm10k_ring *rx_ring "  ");"
.SH ARGUMENTS
.IP "rx_ring" 12
rx descriptor ring (for a specific queue) to setup
.SH "DESCRIPTION"
Returns 0 on success, negative on failure
