.TH "fm10k_update_int_moderator_vf" 9 "fm10k_update_int_moderator_vf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_update_int_moderator_vf \- Request update of interrupt moderator list
.SH SYNOPSIS
.B "void" fm10k_update_int_moderator_vf
.BI "(struct fm10k_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure

This function will issue a request to the PF to rescan our MSI-X table
and to update the interrupt moderator linked list.
