.TH "fm10k_reset_num_queues" 9 "fm10k_reset_num_queues" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_reset_num_queues \- Reset the number of queues to zero
.SH SYNOPSIS
.B "void" fm10k_reset_num_queues
.BI "(struct fm10k_intfc *interface "  ");"
.SH ARGUMENTS
.IP "interface" 12
board private structure
.SH "DESCRIPTION"
This function should be called whenever we need to reset the number of
queues after an error condition.
