.TH "fm10k_tlv_attr_put_null_string" 9 "fm10k_tlv_attr_put_null_string" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_tlv_attr_put_null_string \- Place null terminated string on message
.SH SYNOPSIS
.B "s32" fm10k_tlv_attr_put_null_string
.BI "(u32 *msg "  ","
.BI "u16 attr_id "  ","
.BI "const unsigned char *string "  ");"
.SH ARGUMENTS
.IP "msg" 12
Pointer to message block
.IP "attr_id" 12
Attribute ID
.IP "string" 12
Pointer to string to be stored in attribute

This function will reorder a string to be CPU endian and store it in
the attribute buffer.  It will return success if provided with a valid
pointers.
