.TH "fm10k_update_rx_drop_en" 9 "fm10k_update_rx_drop_en" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_update_rx_drop_en \- Configures the drop enable bits for Rx rings
.SH SYNOPSIS
.B "void" fm10k_update_rx_drop_en
.BI "(struct fm10k_intfc *interface "  ");"
.SH ARGUMENTS
.IP "interface" 12
board private structure
.SH "DESCRIPTION"
Configure the drop enable bits for the Rx rings.
