.TH "fm10k_update_hw_stats_tx_q" 9 "fm10k_update_hw_stats_tx_q" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_update_hw_stats_tx_q \- Updates TX queue statistics counters
.SH SYNOPSIS
.B "void" fm10k_update_hw_stats_tx_q
.BI "(struct fm10k_hw *hw "  ","
.BI "struct fm10k_hw_stats_q *q "  ","
.BI "u32 idx "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.IP "q" 12
pointer to the ring of hardware statistics queue
.IP "idx" 12
index pointing to the start of the ring iteration

Function updates the TX queue statistics counters that are related to the
hardware.
