.TH "fm10k_dbg_intfc_exit" 9 "fm10k_dbg_intfc_exit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_dbg_intfc_exit \- clean out the interface's debugfs entries
.SH SYNOPSIS
.B "void" fm10k_dbg_intfc_exit
.BI "(struct fm10k_intfc *interface "  ");"
.SH ARGUMENTS
.IP "interface" 12
the interface that is stopping
