.TH "fm10k_iov_set_lport_pf" 9 "fm10k_iov_set_lport_pf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_iov_set_lport_pf \- Assign and enable a logical port for a given VF
.SH SYNOPSIS
.B "s32" fm10k_iov_set_lport_pf
.BI "(struct fm10k_hw *hw "  ","
.BI "struct fm10k_vf_info *vf_info "  ","
.BI "u16 lport_idx "  ","
.BI "u8 flags "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
.IP "vf_info" 12
pointer to VF information structure
.IP "lport_idx" 12
Logical port offset from the hardware glort
.IP "flags" 12
Set of capability flags to extend port beyond basic functionality

This function allows enabling a VF port by assigning it a GLORT and
setting the flags so that it can enable an Rx mode.
