.TH "fm10k_alloc_rx_buffers" 9 "fm10k_alloc_rx_buffers" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_alloc_rx_buffers \- Replace used receive buffers
.SH SYNOPSIS
.B "void" fm10k_alloc_rx_buffers
.BI "(struct fm10k_ring *rx_ring "  ","
.BI "u16 cleaned_count "  ");"
.SH ARGUMENTS
.IP "rx_ring" 12
ring to place buffers on
.IP "cleaned_count" 12
number of buffers to replace
