.TH "fm10k_check_hang_subtask" 9 "fm10k_check_hang_subtask" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_check_hang_subtask \- check for hung queues and dropped interrupts
.SH SYNOPSIS
.B "void" fm10k_check_hang_subtask
.BI "(struct fm10k_intfc *interface "  ");"
.SH ARGUMENTS
.IP "interface" 12
pointer to the device interface structure
.SH "DESCRIPTION"
This function serves two purposes.  First it strobes the interrupt lines
in order to make certain interrupts are occurring.  Secondly it sets the
bits needed to check for TX hangs.  As a result we should immediately
determine if a hang has occurred.
