.TH "fman_register_intr" 9 "fman_register_intr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fman_register_intr \- 
.SH SYNOPSIS
.B "void" fman_register_intr
.BI "(struct fman *fman "  ","
.BI "enum fman_event_modules module "  ","
.BI "u8 mod_id "  ","
.BI "enum fman_intr_type intr_type "  ","
.BI "void (*isr_cb)(void *src_arg) "  ","
.BI "void *src_arg "  ");"
.SH ARGUMENTS
.IP "fman" 12
A Pointer to FMan device
.IP "module" 12
Calling module
.IP "mod_id" 12
Module id (if more than 1 exists, '0' if not)
.IP "intr_type" 12
Interrupt type (error/normal) selection.
.IP "isr_cb" 12
The interrupt service routine.
.IP "src_arg" 12
Argument to be passed to isr_cb.
.SH "DESCRIPTION"
Used to register an event handler to be processed by FMan
.SH "RETURN"
0 on success; Error code otherwise.
