.TH "free_device_data" 9 "free_device_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
free_device_data \- Callback to free the event_device_data structure.
.SH SYNOPSIS
.B "void" free_device_data
.BI "(struct device *d "  ");"
.SH ARGUMENTS
.IP "d" 12
The device embedded in our device data, which we have been ref counting.
.SH "DESCRIPTION"
This is called only after \fBevent_device_remove\fP has been called and all
userspace programs have called \fBevent_release\fP on all the open file
descriptors.
