.TH "freezer_css_offline" 9 "freezer_css_offline" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
freezer_css_offline \- initiate destruction of a freezer css
.SH SYNOPSIS
.B "void" freezer_css_offline
.BI "(struct cgroup_subsys_state *css "  ");"
.SH ARGUMENTS
.IP "css" 12
css being destroyed
.SH "DESCRIPTION"
\fIcss\fP is going away.  Mark it dead and decrement system_freezing_count if
it was holding one.
