.TH "freq_qos_remove_request" 9 "freq_qos_remove_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
freq_qos_remove_request \- Remove frequency QoS request from its list.
.SH SYNOPSIS
.B "int" freq_qos_remove_request
.BI "(struct freq_qos_request *req "  ");"
.SH ARGUMENTS
.IP "req" 12
Request to remove.
.SH "DESCRIPTION"
Remove the given frequency QoS request from the list of constraints it
belongs to and recompute the effective constraint value for that list.

Return 1 if the effective constraint value has changed, 0 if the effective
constraint value has not changed, or a negative error code on failures.
