.TH "from_kgid_munged" 9 "from_kgid_munged" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
from_kgid_munged \- Create a gid from a kgid user-namespace pair.
.SH SYNOPSIS
.B "gid_t" from_kgid_munged
.BI "(struct user_namespace *targ "  ","
.BI "kgid_t kgid "  ");"
.SH ARGUMENTS
.IP "targ" 12
The user namespace we want a gid in.
.IP "kgid" 12
The kernel internal gid to start with.

Map \fIkgid\fP into the user-namespace specified by \fItarg\fP and
return the resulting gid.

There is always a mapping into the initial user_namespace.

Unlike from_kgid from_kgid_munged never fails and always
returns a valid gid.  This makes from_kgid_munged appropriate
for use in syscalls like stat and getgid where failing the
system call and failing to provide a valid gid are not options.

If \fIkgid\fP has no mapping in \fItarg\fP overflowgid is returned.
