.TH "fs_validate_description" 9 "fs_validate_description" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fs_validate_description \- Validate a parameter description
.SH SYNOPSIS
.B "bool" fs_validate_description
.BI "(const char *name "  ","
.BI "const struct fs_parameter_spec *desc "  ");"
.SH ARGUMENTS
.IP "name" 12
-- undescribed --
.IP "desc" 12
The parameter description to validate.
