.TH "fscrypt_show_test_dummy_encryption" 9 "fscrypt_show_test_dummy_encryption" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fscrypt_show_test_dummy_encryption \- show '-o test_dummy_encryption'
.SH SYNOPSIS
.B "void" fscrypt_show_test_dummy_encryption
.BI "(struct seq_file *seq "  ","
.BI "char sep "  ","
.BI "struct super_block *sb "  ");"
.SH ARGUMENTS
.IP "seq" 12
the seq_file to print the option to
.IP "sep" 12
the separator character to use
.IP "sb" 12
the filesystem whose options are being shown
.SH "DESCRIPTION"
Show the test_dummy_encryption mount option, if it was specified.
This is mainly used for /proc/mounts.
