.TH "fscrypt_mergeable_bio_bh" 9 "fscrypt_mergeable_bio_bh" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fscrypt_mergeable_bio_bh \- test whether data can be added to a bio
.SH SYNOPSIS
.B "bool" fscrypt_mergeable_bio_bh
.BI "(struct bio *bio "  ","
.BI "const struct buffer_head *next_bh "  ");"
.SH ARGUMENTS
.IP "bio" 12
the bio being built up
.IP "next_bh" 12
the next buffer_head for which I/O will be submitted
.SH "DESCRIPTION"
Same as \fBfscrypt_mergeable_bio\fP, except this takes a buffer_head instead of
an inode and block number directly.
.SH "RETURN"
true iff the I/O is mergeable
