.TH "fsl_mc_driver_unregister" 9 "fsl_mc_driver_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fsl_mc_driver_unregister \- unregisters a device driver from the MC bus
.SH SYNOPSIS
.B "void" fsl_mc_driver_unregister
.BI "(struct fsl_mc_driver *mc_driver "  ");"
.SH ARGUMENTS
.IP "mc_driver" 12
-- undescribed --
