.TH "fsl_tx_status" 9 "fsl_tx_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fsl_tx_status \- Determine the DMA status
.SH SYNOPSIS
.B "enum dma_status" fsl_tx_status
.BI "(struct dma_chan *dchan "  ","
.BI "dma_cookie_t cookie "  ","
.BI "struct dma_tx_state *txstate "  ");"
.SH ARGUMENTS
.IP "dchan" 12
-- undescribed --
.IP "cookie" 12
-- undescribed --
.IP "txstate" 12
-- undescribed --
