.TH "fsl_mc_get_version" 9 "fsl_mc_get_version" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fsl_mc_get_version \- function to retrieve the MC f/w version information
.SH SYNOPSIS
.B "struct fsl_mc_version *" fsl_mc_get_version
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
mc version when called after fsl-mc-bus probe; NULL otherwise.
