.TH "fsl_open_outb_mbox" 9 "fsl_open_outb_mbox" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fsl_open_outb_mbox \- Initialize MPC85xx outbound mailbox
.SH SYNOPSIS
.B "int" fsl_open_outb_mbox
.BI "(struct rio_mport *mport "  ","
.BI "void *dev_id "  ","
.BI "int mbox "  ","
.BI "int entries "  ");"
.SH ARGUMENTS
.IP "mport" 12
Master port implementing the outbound message unit
.IP "dev_id" 12
Device specific pointer to pass on event
.IP "mbox" 12
Mailbox to open
.IP "entries" 12
Number of entries in the outbound mailbox ring
.SH "DESCRIPTION"
Initializes buffer ring, request the outbound message interrupt,
and enables the outbound message unit. Returns 0 on success and
-EINVAL or -ENOMEM on failure.
