.TH "fsverity_free_hash_request" 9 "fsverity_free_hash_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fsverity_free_hash_request \- free a hash request object
.SH SYNOPSIS
.B "void" fsverity_free_hash_request
.BI "(struct fsverity_hash_alg *alg "  ","
.BI "struct ahash_request *req "  ");"
.SH ARGUMENTS
.IP "alg" 12
the hash algorithm
.IP "req" 12
the hash request object to free
