.TH "ftrace_kill" 9 "ftrace_kill" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ftrace_kill \- kill ftrace
.SH SYNOPSIS
.B "void" ftrace_kill
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This function should be used by panic code. It stops ftrace
but in a not so nice way. If you need to simply kill ftrace
from a non-atomic section, use ftrace_kill.
