.TH "ftrace_ops_set_global_filter" 9 "ftrace_ops_set_global_filter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ftrace_ops_set_global_filter \- setup ops to use global filters @ops - the ops which will use the global filters
.SH SYNOPSIS
.B "void" ftrace_ops_set_global_filter
.BI "(struct ftrace_ops *ops "  ");"
.SH ARGUMENTS
.IP "ops" 12
-- undescribed --
.SH "DESCRIPTION"

ftrace users who need global function trace filtering should call this.
It can set the global filter only if ops were not initialized before.
