.TH "fwcap_to_fwspeed" 9 "fwcap_to_fwspeed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fwcap_to_fwspeed \- return highest speed in Port Capabilities
.SH SYNOPSIS
.B "fw_port_cap32_t" fwcap_to_fwspeed
.BI "(fw_port_cap32_t acaps "  ");"
.SH ARGUMENTS
.IP "acaps" 12
advertised Port Capabilities
.SH "DESCRIPTION"
Get the highest speed for the port from the advertised Port
Capabilities.
