.TH "fwnode_count_parents" 9 "fwnode_count_parents" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fwnode_count_parents \- Return the number of parents a node has
.SH SYNOPSIS
.B "unsigned int" fwnode_count_parents
.BI "(const struct fwnode_handle *fwnode "  ");"
.SH ARGUMENTS
.IP "fwnode" 12
The node the parents of which are to be counted
.SH "DESCRIPTION"
Returns the number of parents a node has.
