.TH "fwnode_get_next_parent_dev" 9 "fwnode_get_next_parent_dev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fwnode_get_next_parent_dev \- Find device of closest ancestor fwnode
.SH SYNOPSIS
.B "struct device *" fwnode_get_next_parent_dev
.BI "(struct fwnode_handle *fwnode "  ");"
.SH ARGUMENTS
.IP "fwnode" 12
firmware node
.SH "DESCRIPTION"
Given a firmware node (\fIfwnode\fP), this function finds its closest ancestor
firmware node that has a corresponding struct device and returns that struct
device.

The caller of this function is expected to call \fBput_device\fP on the returned
device when they are done.
