.TH "generic_set_mtrr" 9 "generic_set_mtrr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
generic_set_mtrr \- set variable MTRR register on the local CPU.
.SH SYNOPSIS
.B "void" generic_set_mtrr
.BI "(unsigned int reg "  ","
.BI "unsigned long base "  ","
.BI "unsigned long size "  ","
.BI "mtrr_type type "  ");"
.SH ARGUMENTS
.IP "reg" 12
The register to set.
.IP "base" 12
The base address of the region.
.IP "size" 12
The size of the region. If this is 0 the region is disabled.
.IP "type" 12
The type of the region.
.SH "DESCRIPTION"
Returns nothing.
