.TH "generic_parse_monolithic" 9 "generic_parse_monolithic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
generic_parse_monolithic \- Parse key[=val][,key[=val]]* mount data
.SH SYNOPSIS
.B "int" generic_parse_monolithic
.BI "(struct fs_context *fc "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "fc" 12
-- undescribed --
.IP "data" 12
The data to parse
.SH "DESCRIPTION"
Parse a blob of data that's in key[=val][,key[=val]]* form.  This can be
called from the ->\fBmonolithic_mount_data\fP fs_context operation.

Returns 0 on success or the error returned by the ->\fBparse_option\fP fs_context
operation on failure.
