.TH "genpd_finish_suspend" 9 "genpd_finish_suspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genpd_finish_suspend \- Completion of suspend or hibernation of device in an I/O pm domain.
.SH SYNOPSIS
.B "int" genpd_finish_suspend
.BI "(struct device *dev "  ","
.BI "bool poweroff "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to suspend.
.IP "poweroff" 12
Specifies if this is a poweroff_noirq or suspend_noirq callback.
.SH "DESCRIPTION"
Stop the device and remove power from the domain if all devices in it have
been stopped.
