.TH "genpd_freeze_noirq" 9 "genpd_freeze_noirq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genpd_freeze_noirq \- Completion of freezing a device in an I/O PM domain.
.SH SYNOPSIS
.B "int" genpd_freeze_noirq
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to freeze.
.SH "DESCRIPTION"
Carry out a late freeze of a device under the assumption that its
pm_domain field points to the domain member of an object of type
struct generic_pm_domain representing a power domain consisting of I/O
devices.
