.TH "genpd_poweroff_noirq" 9 "genpd_poweroff_noirq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genpd_poweroff_noirq \- Completion of hibernation of device in an I/O PM domain.
.SH SYNOPSIS
.B "int" genpd_poweroff_noirq
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to poweroff.
.SH "DESCRIPTION"
Stop the device and remove power from the domain if all devices in it have
been stopped.
