.TH "genwqe_ffdc_buff_size" 9 "genwqe_ffdc_buff_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genwqe_ffdc_buff_size \- Calculates the number of dump registers
.SH SYNOPSIS
.B "int" genwqe_ffdc_buff_size
.BI "(struct genwqe_dev *cd "  ","
.BI "int uid "  ");"
.SH ARGUMENTS
.IP "cd" 12
genwqe device descriptor
.IP "uid" 12
unit ID
