.TH "genwqe_base_clock_frequency" 9 "genwqe_base_clock_frequency" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genwqe_base_clock_frequency \- Deteremine base clock frequency of the card
.SH SYNOPSIS
.B "int" genwqe_base_clock_frequency
.BI "(struct genwqe_dev *cd "  ");"
.SH ARGUMENTS
.IP "cd" 12
genwqe device descriptor
.SH "NOTE"
From a design perspective it turned out to be a bad idea to
use codes here to specifiy the frequency/speed values. An old
driver cannot understand new codes and is therefore always a
problem. Better is to measure out the value or put the
speed/frequency directly into a register which is always a valid
value for old as well as for new software.
.SH "RETURN"
Card clock in MHz
