.TH "genwqe_ddcbs_in_flight" 9 "genwqe_ddcbs_in_flight" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genwqe_ddcbs_in_flight \- Check how many DDCBs are in flight
.SH SYNOPSIS
.B "int" genwqe_ddcbs_in_flight
.BI "(struct genwqe_dev *cd "  ");"
.SH ARGUMENTS
.IP "cd" 12
pointer to genwqe device descriptor
.SH "DESCRIPTION"
Keep track on the number of DDCBs which ware currently in the
queue. This is needed for statistics as well as conditon if we want
to wait or better do polling in case of no interrupts available.
