.TH "get_lvl2_pble" 9 "get_lvl2_pble" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_lvl2_pble \- get level 2 pble resource
.SH SYNOPSIS
.B "enum i40iw_status_code" get_lvl2_pble
.BI "(struct i40iw_hmc_pble_rsrc *pble_rsrc "  ","
.BI "struct i40iw_pble_alloc *palloc "  ","
.BI "struct gen_pool *pool "  ");"
.SH ARGUMENTS
.IP "pble_rsrc" 12
pble resource management
.IP "palloc" 12
level 2 pble allocation
.IP "pool" 12
pool pointer
