.TH "get_sd_pd_idx" 9 "get_sd_pd_idx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_sd_pd_idx \- Returns sd index, pd index and rel_pd_idx from fpm address
.SH SYNOPSIS
.B "void" get_sd_pd_idx
.BI "(struct i40iw_hmc_pble_rsrc *pble_rsrc "  ","
.BI "struct sd_pd_idx *idx "  ");"
.SH ARGUMENTS
.IP "pble_rsrc" 12
structure containing fpm address
.IP "idx" 12
where to return indexes
