.TH "get_ext_path" 9 "get_ext_path" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_ext_path \- Find an extent path for designated logical block number.
.SH SYNOPSIS
.B "int" get_ext_path
.BI "(struct inode *inode "  ","
.BI "ext4_lblk_t lblock "  ","
.BI "struct ext4_ext_path **ppath "  ");"
.SH ARGUMENTS
.IP "inode" 12
inode to be searched
.IP "lblock" 12
logical block number to find an extent path
.IP "ppath" 12
pointer to an extent path pointer (for output)
.SH "DESCRIPTION"
ext4_find_extent wrapper. Return 0 on success, or a negative error value
on failure.
