.TH "get_max_nr_ranges" 9 "get_max_nr_ranges" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_max_nr_ranges \- Get the max no. of ranges crash_mem structure could hold, given the size allocated for it.
.SH SYNOPSIS
.B "unsigned int" get_max_nr_ranges
.BI "(size_t size "  ");"
.SH ARGUMENTS
.IP "size" 12
Allocation size of crash_mem structure.
.SH "DESCRIPTION"
Returns the maximum no. of ranges.
