.TH "get_pci_mode" 9 "get_pci_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_pci_mode \- determine a card's PCI mode
.SH SYNOPSIS
.B "void" get_pci_mode
.BI "(struct adapter *adapter "  ","
.BI "struct pci_params *p "  ");"
.SH ARGUMENTS
.IP "adapter" 12
the adapter
.IP "p" 12
where to store the PCI settings

Determines a card's PCI mode and associated parameters, such as speed
and width.
