.TH "get_super" 9 "get_super" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_super \- get the superblock of a device
.SH SYNOPSIS
.B "struct super_block *" get_super
.BI "(struct block_device *bdev "  ");"
.SH ARGUMENTS
.IP "bdev" 12
device to get the superblock for
.SH "DESCRIPTION"
Scans the superblock list and finds the superblock of the file system
mounted on the device given. NULL is returned if no match is found.
