.TH "get_mtd_device_nm" 9 "get_mtd_device_nm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_mtd_device_nm \- obtain a validated handle for an MTD device by device name
.SH SYNOPSIS
.B "struct mtd_info *" get_mtd_device_nm
.BI "(const char *name "  ");"
.SH ARGUMENTS
.IP "name" 12
MTD device name to open

This function returns MTD device description structure in case of
success and an error code in case of failure.
