.TH "get_cnodes_to_commit" 9 "get_cnodes_to_commit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_cnodes_to_commit \- create list of dirty cnodes to commit.
.SH SYNOPSIS
.B "int" get_cnodes_to_commit
.BI "(struct ubifs_info *c "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.SH "DESCRIPTION"
This function returns the number of cnodes to commit.
