.TH "get_wmiobj_pointer" 9 "get_wmiobj_pointer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_wmiobj_pointer \- Get Content of WMI block for particular instance
.SH SYNOPSIS
.B "union acpi_object *" get_wmiobj_pointer
.BI "(int instance_id "  ","
.BI "const char *guid_string "  ");"
.SH ARGUMENTS
.IP "instance_id" 12
WMI instance ID
.IP "guid_string" 12
WMI GUID (in str form)
.SH "DESCRIPTION"
Fetches the content for WMI block (instance_id) under GUID (guid_string)
Caller must kfree the return
