.TH "geth_cleanup_freeq" 9 "geth_cleanup_freeq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
geth_cleanup_freeq \- cleanup the DMA mappings and free the queue
.SH SYNOPSIS
.B "void" geth_cleanup_freeq
.BI "(struct gemini_ethernet *geth "  ");"
.SH ARGUMENTS
.IP "geth" 12
the Gemini global ethernet state
