.TH "gfs2_read_sb" 9 "gfs2_read_sb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_read_sb \- Read super block
.SH SYNOPSIS
.B "int" gfs2_read_sb
.BI "(struct gfs2_sbd *sdp "  ","
.BI "int silent "  ");"
.SH ARGUMENTS
.IP "sdp" 12
The GFS2 superblock
.IP "silent" 12
Don't print message if mount fails
