.TH "gfs2_exchange" 9 "gfs2_exchange" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_exchange \- exchange two files
.SH SYNOPSIS
.B "int" gfs2_exchange
.BI "(struct inode *odir "  ","
.BI "struct dentry *odentry "  ","
.BI "struct inode *ndir "  ","
.BI "struct dentry *ndentry "  ","
.BI "unsigned int flags "  ");"
.SH ARGUMENTS
.IP "odir" 12
Parent directory of old file name
.IP "odentry" 12
The old dentry of the file
.IP "ndir" 12
Parent directory of new file name
.IP "ndentry" 12
The new dentry of the file
.IP "flags" 12
The rename flags
.SH "RETURN"
errno
