.TH "gfs2_assert_withdraw_i" 9 "gfs2_assert_withdraw_i" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_assert_withdraw_i \- Cause the machine to withdraw if @assertion is false
.SH SYNOPSIS
.B "void" gfs2_assert_withdraw_i
.BI "(struct gfs2_sbd *sdp "  ","
.BI "char *assertion "  ","
.BI "const char *function "  ","
.BI "char *file "  ","
.BI "unsigned int line "  ","
.BI "bool delayed "  ");"
.SH ARGUMENTS
.IP "sdp" 12
-- undescribed --
.IP "assertion" 12
-- undescribed --
.IP "function" 12
-- undescribed --
.IP "file" 12
-- undescribed --
.IP "line" 12
-- undescribed --
.IP "delayed" 12
-- undescribed --
