.TH "gfs2_meta_wait" 9 "gfs2_meta_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_meta_wait \- Reread a block from disk
.SH SYNOPSIS
.B "int" gfs2_meta_wait
.BI "(struct gfs2_sbd *sdp "  ","
.BI "struct buffer_head *bh "  ");"
.SH ARGUMENTS
.IP "sdp" 12
the filesystem
.IP "bh" 12
The block to wait for
.SH "RETURN"
errno
