.TH "gfs2_ail_empty_tr" 9 "gfs2_ail_empty_tr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_ail_empty_tr \- empty one of the ail lists of a transaction
.SH SYNOPSIS
.B "void" gfs2_ail_empty_tr
.BI "(struct gfs2_sbd *sdp "  ","
.BI "struct gfs2_trans *tr "  ","
.BI "struct list_head *head "  ");"
.SH ARGUMENTS
.IP "sdp" 12
-- undescribed --
.IP "tr" 12
-- undescribed --
.IP "head" 12
-- undescribed --
