.TH "gfs2_meta_ra" 9 "gfs2_meta_ra" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_meta_ra \- start readahead on an extent of a file
.SH SYNOPSIS
.B "struct buffer_head *" gfs2_meta_ra
.BI "(struct gfs2_glock *gl "  ","
.BI "u64 dblock "  ","
.BI "u32 extlen "  ");"
.SH ARGUMENTS
.IP "gl" 12
the glock the blocks belong to
.IP "dblock" 12
the starting disk block
.IP "extlen" 12
the number of blocks in the extent
.SH "RETURN"
the first buffer in the extent
