.TH "gfs2_readpage" 9 "gfs2_readpage" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_readpage \- read a page of a file
.SH SYNOPSIS
.B "int" gfs2_readpage
.BI "(struct file *file "  ","
.BI "struct page *page "  ");"
.SH ARGUMENTS
.IP "file" 12
The file to read
.IP "page" 12
The page of the file
