.TH "gfs2_log_submit_bio" 9 "gfs2_log_submit_bio" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_log_submit_bio \- Submit any pending log bio
.SH SYNOPSIS
.B "void" gfs2_log_submit_bio
.BI "(struct bio **biop "  ","
.BI "int opf "  ");"
.SH ARGUMENTS
.IP "biop" 12
Address of the bio pointer
.IP "opf" 12
REQ_OP | op_flags
.SH "DESCRIPTION"
Submit any pending part-built or full bio to the block device. If
there is no pending bio, then this is a no-op.
