.TH "gfx_v7_0_constants_init" 9 "gfx_v7_0_constants_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfx_v7_0_constants_init \- setup the 3D engine
.SH SYNOPSIS
.B "void" gfx_v7_0_constants_init
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
init the gfx constants such as the 3D engine, tiling configuration
registers, maximum number of quad pipes, render backends...
