.TH "gluebi_resized" 9 "gluebi_resized" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gluebi_resized \- UBI volume was re-sized notifier.
.SH SYNOPSIS
.B "int" gluebi_resized
.BI "(struct ubi_volume_info *vi "  ");"
.SH ARGUMENTS
.IP "vi" 12
volume info structure
.SH "DESCRIPTION"
This function is called every time an UBI volume is re-size. It changes the
corresponding fake MTD device size. This function returns zero in case of
success and a negative error code in case of error.
