.TH "gnttab_alloc_pages" 9 "gnttab_alloc_pages" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gnttab_alloc_pages \- alloc pages suitable for grant mapping into
.SH SYNOPSIS
.B "int" gnttab_alloc_pages
.BI "(int nr_pages "  ","
.BI "struct page **pages "  ");"
.SH ARGUMENTS
.IP "nr_pages" 12
number of pages to alloc
.IP "pages" 12
returns the pages
