.TH "gpiod_get_optional" 9 "gpiod_get_optional" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gpiod_get_optional \- obtain an optional GPIO for a given GPIO function
.SH SYNOPSIS
.B "struct gpio_desc *" gpiod_get_optional
.BI "(struct device *dev "  ","
.BI "const char *con_id "  ","
.BI "enum gpiod_flags flags "  ");"
.SH ARGUMENTS
.IP "dev" 12
GPIO consumer, can be NULL for system-global GPIOs
.IP "con_id" 12
function within the GPIO consumer
.IP "flags" 12
optional GPIO initialization flags
.SH "DESCRIPTION"
This is equivalent to \fBgpiod_get\fP, except that when no GPIO was assigned to
the requested function it will return NULL. This is convenient for drivers
that need to handle optional GPIOs.
