.TH "gpio_chrdev_release" 9 "gpio_chrdev_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gpio_chrdev_release \- close chardev after ioctl operations
.SH SYNOPSIS
.B "int" gpio_chrdev_release
.BI "(struct inode *inode "  ","
.BI "struct file *file "  ");"
.SH ARGUMENTS
.IP "inode" 12
inode for this chardev
.IP "file" 12
file struct for storing private data
Returns 0 on success
