.TH "gss_update_rslack" 9 "gss_update_rslack" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gss_update_rslack \- Possibly update RPC receive buffer size estimates
.SH SYNOPSIS
.B "void" gss_update_rslack
.BI "(struct rpc_task *task "  ","
.BI "struct rpc_cred *cred "  ","
.BI "unsigned int before "  ","
.BI "unsigned int after "  ");"
.SH ARGUMENTS
.IP "task" 12
rpc_task for incoming RPC Reply being unwrapped
.IP "cred" 12
controlling rpc_cred for \fItask\fP
.IP "before" 12
XDR words needed before each RPC Reply message
.IP "after" 12
XDR words needed following each RPC Reply message
