.TH "gx_set_cpuspeed" 9 "gx_set_cpuspeed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gx_set_cpuspeed \-  set cpu speed in khz.
.SH SYNOPSIS
.B "void" gx_set_cpuspeed
.BI "(struct cpufreq_policy *policy "  ","
.BI "unsigned int khz "  ");"
.SH ARGUMENTS
.IP "policy" 12
-- undescribed --
.IP "khz" 12
-- undescribed --
