.TH "h_request_vmc" 9 "h_request_vmc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
h_request_vmc \- - request a hypervisor virtual management channel device
.SH SYNOPSIS
.B "long" h_request_vmc
.BI "(u32 *vmc_index "  ");"
.SH ARGUMENTS
.IP "vmc_index" 12
drc index of the vmc device created
.SH "DESCRIPTION"
Requests the hypervisor create a new virtual management channel device,
allowing this partition to send hypervisor virtualization control
commands.
.SH "RETURN"
0 - Success
Non-zero - Failure
