.TH "handle_bounds_compressed_page" 9 "handle_bounds_compressed_page" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
handle_bounds_compressed_page \- test for&handle out of bounds compressed page
.SH SYNOPSIS
.B "void" handle_bounds_compressed_page
.BI "(struct page *page "  ","
.BI "const loff_t i_size "  ","
.BI "const s64 initialized_size "  ");"
.SH ARGUMENTS
.IP "page" 12
-- undescribed --
.IP "i_size" 12
-- undescribed --
.IP "initialized_size" 12
-- undescribed --
