.TH "hbm_ver_drv_show" 9 "hbm_ver_drv_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hbm_ver_drv_show \- display HBM protocol version advertised by driver
.SH SYNOPSIS
.B "ssize_t" hbm_ver_drv_show
.BI "(struct device *device "  ","
.BI "struct device_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "device" 12
device pointer
.IP "attr" 12
attribute pointer
.IP "buf" 12
char out buffer
.SH "RETURN"
number of the bytes printed into buf or error
