.TH "hfi1_netdev_remove_data" 9 "hfi1_netdev_remove_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hfi1_netdev_remove_data \- Removes data with previously given id. Returns the reference to removed entry.
.SH SYNOPSIS
.B "void *" hfi1_netdev_remove_data
.BI "(struct hfi1_devdata *dd "  ","
.BI "int id "  ");"
.SH ARGUMENTS
.IP "dd" 12
hfi1 dev data
.IP "id" 12
requested integer id up to INT_MAX
