.TH "hfi1_netdev_enable_queues" 9 "hfi1_netdev_enable_queues" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hfi1_netdev_enable_queues \- This is napi enable function. It enables napi objects associated with queues. When at least one device has called it it increments atomic counter. Disable function decrements counter and when it is 0, calls napi_disable for every queue.
.SH SYNOPSIS
.B "void" hfi1_netdev_enable_queues
.BI "(struct hfi1_devdata *dd "  ");"
.SH ARGUMENTS
.IP "dd" 12
hfi1 dev data
