.TH "hid_open_report" 9 "hid_open_report" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hid_open_report \- open a driver-specific device report
.SH SYNOPSIS
.B "int" hid_open_report
.BI "(struct hid_device *device "  ");"
.SH ARGUMENTS
.IP "device" 12
hid device
.SH "DESCRIPTION"
Parse a report description into a hid_device structure. Reports are
enumerated, fields are attached to these reports.
0 returned on success, otherwise nonzero error value.

This function (or the equivalent \fBhid_parse\fP macro) should only be
called from \fBprobe\fP in drivers, before starting the device.
