.TH "hid_validate_values" 9 "hid_validate_values" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hid_validate_values \- validate existing device report's value indexes
.SH SYNOPSIS
.B "struct hid_report *" hid_validate_values
.BI "(struct hid_device *hid "  ","
.BI "unsigned int type "  ","
.BI "unsigned int id "  ","
.BI "unsigned int field_index "  ","
.BI "unsigned int report_counts "  ");"
.SH ARGUMENTS
.IP "hid" 12
hid device
.IP "type" 12
which report type to examine
.IP "id" 12
which report ID to examine (0 for first)
.IP "field_index" 12
which report field to examine
.IP "report_counts" 12
expected number of values
.SH "DESCRIPTION"
Validate the number of values in a given field of a given report, after
parsing.
