.TH "hid_compare_device_paths" 9 "hid_compare_device_paths" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hid_compare_device_paths \- check if both devices share the same path
.SH SYNOPSIS
.B "bool" hid_compare_device_paths
.BI "(struct hid_device *hdev_a "  ","
.BI "struct hid_device *hdev_b "  ","
.BI "char separator "  ");"
.SH ARGUMENTS
.IP "hdev_a" 12
hid device
.IP "hdev_b" 12
hid device
.IP "separator" 12
char to use as separator
.SH "DESCRIPTION"
Check if two devices share the same path up to the last occurrence of
the separator char. Both paths must exist (i.e., zero-length paths
don't match).
