.TH "hinic_port_set_func_state" 9 "hinic_port_set_func_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_port_set_func_state \- set func device state
.SH SYNOPSIS
.B "int" hinic_port_set_func_state
.BI "(struct hinic_dev *nic_dev "  ","
.BI "enum hinic_func_port_state state "  ");"
.SH ARGUMENTS
.IP "nic_dev" 12
nic device
.IP "state" 12
the state to set
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
