.TH "hinic_rq_get_sge" 9 "hinic_rq_get_sge" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_rq_get_sge \- get sge from the wqe
.SH SYNOPSIS
.B "void" hinic_rq_get_sge
.BI "(struct hinic_rq *rq "  ","
.BI "struct hinic_rq_wqe *rq_wqe "  ","
.BI "u16 cons_idx "  ","
.BI "struct hinic_sge *sge "  ");"
.SH ARGUMENTS
.IP "rq" 12
recv queue
.IP "rq_wqe" 12
wqe to get the sge from its buf address
.IP "cons_idx" 12
consumer index
.IP "sge" 12
returned sge
