.TH "hinic_sq_put_wqe" 9 "hinic_sq_put_wqe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_sq_put_wqe \- release the ci for new wqes
.SH SYNOPSIS
.B "void" hinic_sq_put_wqe
.BI "(struct hinic_sq *sq "  ","
.BI "unsigned int wqe_size "  ");"
.SH ARGUMENTS
.IP "sq" 12
send queue
.IP "wqe_size" 12
the size of the wqe
