.TH "hinic_msix_attr_cnt_clear" 9 "hinic_msix_attr_cnt_clear" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_msix_attr_cnt_clear \- clear message attribute counters for msix entry
.SH SYNOPSIS
.B "int" hinic_msix_attr_cnt_clear
.BI "(struct hinic_hwif *hwif "  ","
.BI "u16 msix_index "  ");"
.SH ARGUMENTS
.IP "hwif" 12
the HW interface of a pci function device
.IP "msix_index" 12
msix_index
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
