.TH "hinic_msix_attr_get" 9 "hinic_msix_attr_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_msix_attr_get \- get message attribute of msix entry
.SH SYNOPSIS
.B "int" hinic_msix_attr_get
.BI "(struct hinic_hwif *hwif "  ","
.BI "u16 msix_index "  ","
.BI "u8 *pending_limit "  ","
.BI "u8 *coalesc_timer "  ","
.BI "u8 *lli_timer "  ","
.BI "u8 *lli_credit_limit "  ","
.BI "u8 *resend_timer "  ");"
.SH ARGUMENTS
.IP "hwif" 12
the HW interface of a pci function device
.IP "msix_index" 12
msix_index
.IP "pending_limit" 12
the maximum pending interrupt events (unit 8)
.IP "coalesc_timer" 12
coalesc period for interrupt (unit 8 us)
.IP "lli_timer" 12
replenishing period for low latency credit (unit 8 us)
.IP "lli_credit_limit" 12
maximum credits for low latency msix messages (unit 8)
.IP "resend_timer" 12
maximum wait for resending msix (unit coalesc period)
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
