.TH "hinic_hwdev_msix_cnt_set" 9 "hinic_hwdev_msix_cnt_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_hwdev_msix_cnt_set \- clear message attribute counters for msix entry
.SH SYNOPSIS
.B "int" hinic_hwdev_msix_cnt_set
.BI "(struct hinic_hwdev *hwdev "  ","
.BI "u16 msix_index "  ");"
.SH ARGUMENTS
.IP "hwdev" 12
the NIC HW device
.IP "msix_index" 12
msix_index
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
