.TH "hinic_sge_to_dma" 9 "hinic_sge_to_dma" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_sge_to_dma \- get dma address from scatter gather entry
.SH SYNOPSIS
.B "dma_addr_t" hinic_sge_to_dma
.BI "(struct hinic_sge *sge "  ");"
.SH ARGUMENTS
.IP "sge" 12
scatter gather entry
.SH "DESCRIPTION"
Return dma address of sg entry
