.TH "hinic_aeq_register_hw_cb" 9 "hinic_aeq_register_hw_cb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_aeq_register_hw_cb \- register AEQ callback for specific event
.SH SYNOPSIS
.B "void" hinic_aeq_register_hw_cb
.BI "(struct hinic_aeqs *aeqs "  ","
.BI "enum hinic_aeq_type event "  ","
.BI "void *handle "  ","
.BI "void (*hwe_handler)(void *handle, void *data, u8 size) "  ");"
.SH ARGUMENTS
.IP "aeqs" 12
pointer to Async eqs of the chip
.IP "event" 12
aeq event to register callback for it
.IP "handle" 12
private data will be used by the callback
.IP "hwe_handler" 12
callback function
