.TH "hisi_qm_dev_slot_reset" 9 "hisi_qm_dev_slot_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hisi_qm_dev_slot_reset \- slot reset
.SH SYNOPSIS
.B "pci_ers_result_t" hisi_qm_dev_slot_reset
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
the PCIe device
.SH "DESCRIPTION"
This function offers QM relate PCIe device reset interface. Drivers which
use QM can use this function as slot_reset in its struct pci_error_handlers.
