.TH "hl_cq_init" 9 "hl_cq_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hl_cq_init \- main initialization function for an cq object
.SH SYNOPSIS
.B "int" hl_cq_init
.BI "(struct hl_device *hdev "  ","
.BI "struct hl_cq *q "  ","
.BI "u32 hw_queue_id "  ");"
.SH ARGUMENTS
.IP "hdev" 12
pointer to device structure
.IP "q" 12
pointer to cq structure
.IP "hw_queue_id" 12
The H/W queue ID this completion queue belongs to
.SH "DESCRIPTION"
Allocate dma-able memory for the completion queue and initialize fields
Returns 0 on success
