.TH "hl_userptr_is_pinned" 9 "hl_userptr_is_pinned" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hl_userptr_is_pinned \- returns whether the given userptr is pinned.
.SH SYNOPSIS
.B "bool" hl_userptr_is_pinned
.BI "(struct hl_device *hdev "  ","
.BI "u64 addr "  ","
.BI "u32 size "  ","
.BI "struct list_head *userptr_list "  ","
.BI "struct hl_userptr **userptr "  ");"
.SH ARGUMENTS
.IP "hdev" 12
pointer to the habanalabs device structure.
.IP "addr" 12
-- undescribed --
.IP "size" 12
-- undescribed --
.IP "userptr_list" 12
pointer to the list to clear.
.IP "userptr" 12
pointer to userptr to check.
.SH "DESCRIPTION"
This function does the following:
- Iterates over the list and checks if the given userptr is in it, means is
pinned. If so, returns true, otherwise returns false.
