.TH "hns_rcb_ring_enable_hw" 9 "hns_rcb_ring_enable_hw" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hns_rcb_ring_enable_hw \- enable ring
.SH SYNOPSIS
.B "void" hns_rcb_ring_enable_hw
.BI "(struct hnae_queue *q "  ","
.BI "u32 val "  ");"
.SH ARGUMENTS
.IP "q" 12
rcb ring
.IP "val" 12
value to write
