.TH "hns_dsaf_tbl_tcam_ucast_cfg" 9 "hns_dsaf_tbl_tcam_ucast_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hns_dsaf_tbl_tcam_ucast_cfg \- tbl
.SH SYNOPSIS
.B "void" hns_dsaf_tbl_tcam_ucast_cfg
.BI "(struct dsaf_device *dsaf_dev "  ","
.BI "struct dsaf_tbl_tcam_ucast_cfg *tbl_tcam_ucast "  ");"
.SH ARGUMENTS
.IP "dsaf_dev" 12
dsa fabric id
.IP "tbl_tcam_ucast" 12
addr
