.TH "hns_dsaf_sbm_link_sram_init_en" 9 "hns_dsaf_sbm_link_sram_init_en" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hns_dsaf_sbm_link_sram_init_en \- config dsaf_sbm_init_en
.SH SYNOPSIS
.B "void" hns_dsaf_sbm_link_sram_init_en
.BI "(struct dsaf_device *dsaf_dev "  ");"
.SH ARGUMENTS
.IP "dsaf_dev" 12
dsa fabric id
