.TH "hpt37x_clock_slot" 9 "hpt37x_clock_slot" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hpt37x_clock_slot \- Turn timing to PC clock entry
.SH SYNOPSIS
.B "int" hpt37x_clock_slot
.BI "(unsigned int freq "  ","
.BI "unsigned int base "  ");"
.SH ARGUMENTS
.IP "freq" 12
Reported frequency timing
.IP "base" 12
Base timing

Turn the timing data intoa clock slot (0 for 33, 1 for 40, 2 for 50
and 3 for 66Mhz)
