.TH "hv_pci_free_bridge_windows" 9 "hv_pci_free_bridge_windows" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hv_pci_free_bridge_windows \- Release memory regions for the bus
.SH SYNOPSIS
.B "void" hv_pci_free_bridge_windows
.BI "(struct hv_pcibus_device *hbus "  ");"
.SH ARGUMENTS
.IP "hbus" 12
Root PCI bus, as understood by this driver
