.TH "hvc_iucv_pm_freeze" 9 "hvc_iucv_pm_freeze" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hvc_iucv_pm_freeze \- Freeze PM callback
.SH SYNOPSIS
.B "int" hvc_iucv_pm_freeze
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
IUVC HVC terminal device
.SH "DESCRIPTION"
Sever an established IUCV communication path and
trigger a hang-up of the underlying HVC terminal.
