.TH "hw_alloc_pkt" 9 "hw_alloc_pkt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hw_alloc_pkt \- allocate enough descriptors for transmission
.SH SYNOPSIS
.B "int" hw_alloc_pkt
.BI "(struct ksz_hw *hw "  ","
.BI "int length "  ","
.BI "int physical "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware instance.
.IP "length" 12
The length of the packet.
.IP "physical" 12
Number of descriptors required.
.SH "DESCRIPTION"
This function allocates descriptors for transmission.

Return 0 if not successful; 1 for buffer copy; or number of descriptors.
