.TH "hw_clr_multicast" 9 "hw_clr_multicast" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hw_clr_multicast \- clear multicast addresses
.SH SYNOPSIS
.B "void" hw_clr_multicast
.BI "(struct ksz_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware instance.
.SH "DESCRIPTION"
This routine removes all multicast addresses set in the hardware.
