.TH "hw_ep_disable" 9 "hw_ep_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hw_ep_disable \- disables endpoint (execute without interruption)
.SH SYNOPSIS
.B "int" hw_ep_disable
.BI "(struct ci_hdrc *ci "  ","
.BI "int num "  ","
.BI "int dir "  ");"
.SH ARGUMENTS
.IP "ci" 12
the controller
.IP "num" 12
endpoint number
.IP "dir" 12
endpoint direction
.SH "DESCRIPTION"
This function returns an error code
