.TH "hw_port_test_set" 9 "hw_port_test_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hw_port_test_set \- writes port test mode (execute without interruption)
.SH SYNOPSIS
.B "int" hw_port_test_set
.BI "(struct ci_hdrc *ci "  ","
.BI "u8 mode "  ");"
.SH ARGUMENTS
.IP "ci" 12
the controller
.IP "mode" 12
new value
.SH "DESCRIPTION"
This function returns an error code
