.TH "hw_read_addr" 9 "hw_read_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hw_read_addr \- read MAC address
.SH SYNOPSIS
.B "void" hw_read_addr
.BI "(struct ksz_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware instance.
.SH "DESCRIPTION"
This routine retrieves the MAC address of the hardware.
