.TH "hw_set_promiscuous" 9 "hw_set_promiscuous" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hw_set_promiscuous \- enable or disable promiscuous receiving
.SH SYNOPSIS
.B "void" hw_set_promiscuous
.BI "(struct ksz_hw *hw "  ","
.BI "u8 prom "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware instance.
.IP "prom" 12
To turn on or off the promiscuous feature.
.SH "DESCRIPTION"
This routine enables/disables the hardware to accept all packets.
