.TH "i2c_handle_smbus_host_notify" 9 "i2c_handle_smbus_host_notify" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i2c_handle_smbus_host_notify \- Forward a Host Notify event to the correct I2C client.
.SH SYNOPSIS
.B "int" i2c_handle_smbus_host_notify
.BI "(struct i2c_adapter *adap "  ","
.BI "unsigned short addr "  ");"
.SH ARGUMENTS
.IP "adap" 12
the adapter
.IP "addr" 12
the I2C address of the notifying device
.SH "CONTEXT"
can't sleep
.SH "DESCRIPTION"
Helper function to be called from an I2C bus driver's interrupt
handler. It will schedule the Host Notify IRQ.
