.TH "i2c_unregister_device" 9 "i2c_unregister_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i2c_unregister_device \- reverse effect of i2c_new_*_device()
.SH SYNOPSIS
.B "void" i2c_unregister_device
.BI "(struct i2c_client *client "  ");"
.SH ARGUMENTS
.IP "client" 12
value returned from i2c_new_*\fB_device\fP
.SH "CONTEXT"
can sleep
