.TH "i2c_irq_handler" 9 "i2c_irq_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i2c_irq_handler \- interrupt routine
.SH SYNOPSIS
.B "irqreturn_t" i2c_irq_handler
.BI "(int irq "  ","
.BI "void *arg "  ");"
.SH ARGUMENTS
.IP "irq" 12
interrupt number
.IP "arg" 12
data passed to the handler
.SH "DESCRIPTION"
This is the interrupt handler for the i2c driver. Currently
it handles the major interrupts like Rx & Tx FIFO management
interrupts, master transaction interrupts, arbitration and
bus error interrupts. The rest of the interrupts are treated as
unhandled.
