.TH "i2c_put_dma_safe_msg_buf" 9 "i2c_put_dma_safe_msg_buf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i2c_put_dma_safe_msg_buf \- release DMA safe buffer and sync with i2c_msg
.SH SYNOPSIS
.B "void" i2c_put_dma_safe_msg_buf
.BI "(u8 *buf "  ","
.BI "struct i2c_msg *msg "  ","
.BI "bool xferred "  ");"
.SH ARGUMENTS
.IP "buf" 12
the buffer obtained from \fBi2c_get_dma_safe_msg_buf\fP. May be NULL.
.IP "msg" 12
the message which the buffer corresponds to
.IP "xferred" 12
bool saying if the message was transferred
