.TH "i40e_fill_rx_flow_user_data" 9 "i40e_fill_rx_flow_user_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_fill_rx_flow_user_data \- Fill in user-defined data field
.SH SYNOPSIS
.B "void" i40e_fill_rx_flow_user_data
.BI "(struct ethtool_rx_flow_spec *fsp "  ","
.BI "struct i40e_rx_flow_userdef *data "  ");"
.SH ARGUMENTS
.IP "fsp" 12
pointer to rx_flow specification
.IP "data" 12
pointer to return userdef data
.SH "DESCRIPTION"
Reads the userdef data structure and properly fills in the user defined
fields of the rx_flow_spec.
