.TH "i40e_force_link_state" 9 "i40e_force_link_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_force_link_state \- Force the link status
.SH SYNOPSIS
.B "i40e_status" i40e_force_link_state
.BI "(struct i40e_pf *pf "  ","
.BI "bool is_up "  ");"
.SH ARGUMENTS
.IP "pf" 12
board private structure
.IP "is_up" 12
whether the link state should be forced up or down
