.TH "i40e_add_vsi" 9 "i40e_add_vsi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_add_vsi \- Add a VSI to the switch
.SH SYNOPSIS
.B "int" i40e_add_vsi
.BI "(struct i40e_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI being configured
.SH "DESCRIPTION"
This initializes a VSI context depending on the VSI type to be added and
passes it down to the add_vsi aq command.
