.TH "i40e_dcbnl_get_pfc_cfg" 9 "i40e_dcbnl_get_pfc_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_dcbnl_get_pfc_cfg \- Get CEE PFC configuration
.SH SYNOPSIS
.B "void" i40e_dcbnl_get_pfc_cfg
.BI "(struct net_device *netdev "  ","
.BI "int prio "  ","
.BI "u8 *setting "  ");"
.SH ARGUMENTS
.IP "netdev" 12
the corresponding netdev
.IP "prio" 12
the corresponding user priority
.IP "setting" 12
the PFC setting for given priority
.SH "DESCRIPTION"
Get the PFC enabled/disabled setting for given user priority
