.TH "i40e_tx_timeout" 9 "i40e_tx_timeout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_tx_timeout \- Respond to a Tx Hang
.SH SYNOPSIS
.B "void" i40e_tx_timeout
.BI "(struct net_device *netdev "  ","
.BI "unsigned int txqueue "  ");"
.SH ARGUMENTS
.IP "netdev" 12
network interface device structure
.IP "txqueue" 12
queue number timing out
.SH "DESCRIPTION"
If any port has noticed a Tx timeout, it is likely that the whole
device is munged, not just the one netdev port, so go for the full
reset.
