.TH "i40e_set_hmc_context" 9 "i40e_set_hmc_context" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_set_hmc_context \- replace HMC context bits
.SH SYNOPSIS
.B "i40e_status" i40e_set_hmc_context
.BI "(u8 *context_bytes "  ","
.BI "struct i40e_context_ele *ce_info "  ","
.BI "u8 *dest "  ");"
.SH ARGUMENTS
.IP "context_bytes" 12
pointer to the context bit array
.IP "ce_info" 12
a description of the struct to be filled
.IP "dest" 12
the struct to be filled
