.TH "i40e_channel_config_tx_ring" 9 "i40e_channel_config_tx_ring" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_channel_config_tx_ring \- config TX ring associated with new channel
.SH SYNOPSIS
.B "int" i40e_channel_config_tx_ring
.BI "(struct i40e_pf *pf "  ","
.BI "struct i40e_vsi *vsi "  ","
.BI "struct i40e_channel *ch "  ");"
.SH ARGUMENTS
.IP "pf" 12
ptr to PF device
.IP "vsi" 12
the VSI being setup
.IP "ch" 12
ptr to channel structure
.SH "DESCRIPTION"
Configure TX rings associated with channel (VSI) since queues are being
from parent VSI.
