.TH "i40e_aq_config_vsi_tc_bw" 9 "i40e_aq_config_vsi_tc_bw" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_aq_config_vsi_tc_bw \- Config VSI BW Allocation per TC
.SH SYNOPSIS
.B "i40e_status" i40e_aq_config_vsi_tc_bw
.BI "(struct i40e_hw *hw "  ","
.BI "u16 seid "  ","
.BI "struct i40e_aqc_configure_vsi_tc_bw_data *bw_data "  ","
.BI "struct i40e_asq_cmd_details *cmd_details "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hw struct
.IP "seid" 12
VSI seid
.IP "bw_data" 12
Buffer holding enabled TCs, relative TC BW limit/credits
.IP "cmd_details" 12
pointer to command details structure or NULL
