.TH "i40e_aq_config_switch_comp_ets" 9 "i40e_aq_config_switch_comp_ets" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_aq_config_switch_comp_ets \- Enable/Disable/Modify ETS on the port
.SH SYNOPSIS
.B "i40e_status" i40e_aq_config_switch_comp_ets
.BI "(struct i40e_hw *hw "  ","
.BI "u16 seid "  ","
.BI "struct i40e_aqc_configure_switching_comp_ets_data *ets_data "  ","
.BI "enum i40e_admin_queue_opc opcode "  ","
.BI "struct i40e_asq_cmd_details *cmd_details "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hw struct
.IP "seid" 12
seid of the switching component connected to Physical Port
.IP "ets_data" 12
Buffer holding ETS parameters
.IP "opcode" 12
Tx scheduler AQ command opcode
.IP "cmd_details" 12
pointer to command details structure or NULL
