.TH "i40e_clear_lan_rx_queue_context" 9 "i40e_clear_lan_rx_queue_context" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_clear_lan_rx_queue_context \- clear the HMC context for the queue
.SH SYNOPSIS
.B "i40e_status" i40e_clear_lan_rx_queue_context
.BI "(struct i40e_hw *hw "  ","
.BI "u16 queue "  ");"
.SH ARGUMENTS
.IP "hw" 12
the hardware struct
.IP "queue" 12
the queue we care about
