.TH "i40e_set_promiscuous" 9 "i40e_set_promiscuous" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_set_promiscuous \- set promiscuous mode
.SH SYNOPSIS
.B "int" i40e_set_promiscuous
.BI "(struct i40e_pf *pf "  ","
.BI "bool promisc "  ");"
.SH ARGUMENTS
.IP "pf" 12
board private structure
.IP "promisc" 12
promisc on or off
.SH "DESCRIPTION"
There are different ways of setting promiscuous mode on a PF depending on
what state/environment we're in.  This identifies and sets it appropriately.
Returns 0 on success.
