.TH "i40e_set_mac_type" 9 "i40e_set_mac_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_set_mac_type \- Sets MAC type
.SH SYNOPSIS
.B "i40e_status" i40e_set_mac_type
.BI "(struct i40e_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.SH "DESCRIPTION"
This function sets the mac type of the adapter based on the
vendor ID and device ID stored in the hw structure.
