.TH "i40e_setup_pf_switch_element" 9 "i40e_setup_pf_switch_element" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_setup_pf_switch_element \- set PF vars based on switch type
.SH SYNOPSIS
.B "void" i40e_setup_pf_switch_element
.BI "(struct i40e_pf *pf "  ","
.BI "struct i40e_aqc_switch_config_element_resp *ele "  ","
.BI "u16 num_reported "  ","
.BI "bool printconfig "  ");"
.SH ARGUMENTS
.IP "pf" 12
board private structure
.IP "ele" 12
element we are building info from
.IP "num_reported" 12
total number of elements
.IP "printconfig" 12
should we print the contents
.SH "DESCRIPTION"
helper function to assist in extracting a few useful SEID values.
