.TH "i40e_dbg_find_veb" 9 "i40e_dbg_find_veb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_dbg_find_veb \- searches for the veb with the given seid
.SH SYNOPSIS
.B "struct i40e_veb *" i40e_dbg_find_veb
.BI "(struct i40e_pf *pf "  ","
.BI "int seid "  ");"
.SH ARGUMENTS
.IP "pf" 12
the PF structure to search for the veb
.IP "seid" 12
seid of the veb it is searching for
