.TH "i40e_align_l2obj_base" 9 "i40e_align_l2obj_base" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_align_l2obj_base \- aligns base object pointer to 512 bytes
.SH SYNOPSIS
.B "u64" i40e_align_l2obj_base
.BI "(u64 offset "  ");"
.SH ARGUMENTS
.IP "offset" 12
base address offset needing alignment
.SH "DESCRIPTION"
Aligns the layer 2 function private memory so it's 512-byte aligned.
