.TH "i40e_intr" 9 "i40e_intr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_intr \- MSI/Legacy and non-queue interrupt handler
.SH SYNOPSIS
.B "irqreturn_t" i40e_intr
.BI "(int irq "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "irq" 12
interrupt number
.IP "data" 12
pointer to a q_vector
.SH "DESCRIPTION"
This is the handler used for all MSI/Legacy interrupts, and deals
with both queue and non-queue interrupts.  This is also used in
MSIX mode to handle the non-queue interrupts.
