.TH "i40e_parse_org_tlv" 9 "i40e_parse_org_tlv" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_parse_org_tlv \- 
.SH SYNOPSIS
.B "void" i40e_parse_org_tlv
.BI "(struct i40e_lldp_org_tlv *tlv "  ","
.BI "struct i40e_dcbx_config *dcbcfg "  ");"
.SH ARGUMENTS
.IP "tlv" 12
Organization specific TLV
.IP "dcbcfg" 12
Local store to update ETS REC data
.SH "DESCRIPTION"
Currently only IEEE 802.1Qaz TLV is supported, all others
will be returned
