.TH "i40e_print_link_message" 9 "i40e_print_link_message" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_print_link_message \- print link up or down
.SH SYNOPSIS
.B "void" i40e_print_link_message
.BI "(struct i40e_vsi *vsi "  ","
.BI "bool isup "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI for which link needs a message
.IP "isup" 12
true of link is up, false otherwise
