.TH "i40e_led_set" 9 "i40e_led_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_led_set \- set new on/off mode
.SH SYNOPSIS
.B "void" i40e_led_set
.BI "(struct i40e_hw *hw "  ","
.BI "u32 mode "  ","
.BI "bool blink "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hw struct
.IP "mode" 12
0=off, 0xf=on (else see manual for mode details)
.IP "blink" 12
true if the LED should blink when on, false if steady
.SH "DESCRIPTION"
if this function is used to turn on the blink it should
be used to disable the blink when restoring the original state.
