.TH "i40e_aqc_broadcast_filter" 9 "i40e_aqc_broadcast_filter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_aqc_broadcast_filter \- Set promiscuous broadcast flags
.SH SYNOPSIS
.B "i40e_status" i40e_aqc_broadcast_filter
.BI "(struct i40e_vsi *vsi "  ","
.BI "const char *vsi_name "  ","
.BI "struct i40e_mac_filter *f "  ");"
.SH ARGUMENTS
.IP "vsi" 12
pointer to the VSI
.IP "vsi_name" 12
the VSI name
.IP "f" 12
filter data
.SH "DESCRIPTION"
This function sets or clears the promiscuous broadcast flags for VLAN
filters in order to properly receive broadcast frames. Assumes that only
broadcast filters are passed.

Returns status indicating success or failure;
