.TH "i40e_reprogram_flex_pit" 9 "i40e_reprogram_flex_pit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_reprogram_flex_pit \- Reprogram all FLX_PIT tables after input set change
.SH SYNOPSIS
.B "void" i40e_reprogram_flex_pit
.BI "(struct i40e_pf *pf "  ");"
.SH ARGUMENTS
.IP "pf" 12
pointer to the PF structure
.SH "DESCRIPTION"
This function reprograms both the L3 and L4 FLX_PIT tables. See the
internal helper function for implementation details.
