.TH "i40e_switch_branch_release" 9 "i40e_switch_branch_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_switch_branch_release \- Delete a branch of the switch tree
.SH SYNOPSIS
.B "void" i40e_switch_branch_release
.BI "(struct i40e_veb *branch "  ");"
.SH ARGUMENTS
.IP "branch" 12
where to start deleting
.SH "DESCRIPTION"
This uses recursion to find the tips of the branch to be
removed, deleting until we get back to and can delete this VEB.
