.TH "i40e_dcbnl_vsi_del_app" 9 "i40e_dcbnl_vsi_del_app" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_dcbnl_vsi_del_app \- Delete APP for given VSI
.SH SYNOPSIS
.B "int" i40e_dcbnl_vsi_del_app
.BI "(struct i40e_vsi *vsi "  ","
.BI "struct i40e_dcb_app_priority_table *app "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the corresponding vsi
.IP "app" 12
APP to delete
.SH "DESCRIPTION"
Delete given APP from the DCBNL APP table for given
VSI
