.TH "i40e_aq_get_switch_config" 9 "i40e_aq_get_switch_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_aq_get_switch_config \- 
.SH SYNOPSIS
.B "i40e_status" i40e_aq_get_switch_config
.BI "(struct i40e_hw *hw "  ","
.BI "struct i40e_aqc_get_switch_config_resp *buf "  ","
.BI "u16 buf_size "  ","
.BI "u16 *start_seid "  ","
.BI "struct i40e_asq_cmd_details *cmd_details "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.IP "buf" 12
pointer to the result buffer
.IP "buf_size" 12
length of input buffer
.IP "start_seid" 12
seid to start for the report, 0 == beginning
.IP "cmd_details" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Fill the buf with switch configuration returned from AdminQ command
