.TH "i40e_client_virtchnl_send" 9 "i40e_client_virtchnl_send" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_client_virtchnl_send \- TBD
.SH SYNOPSIS
.B "int" i40e_client_virtchnl_send
.BI "(struct i40e_info *ldev "  ","
.BI "struct i40e_client *client "  ","
.BI "u32 vf_id "  ","
.BI "u8 *msg "  ","
.BI "u16 len "  ");"
.SH ARGUMENTS
.IP "ldev" 12
pointer to L2 context
.IP "client" 12
Client pointer
.IP "vf_id" 12
absolute VF identifier
.IP "msg" 12
message buffer
.IP "len" 12
length of message buffer
.SH "DESCRIPTION"
Return 0 on success or < 0 on error
