.TH "i40e_validate_nvm_checksum" 9 "i40e_validate_nvm_checksum" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_validate_nvm_checksum \- Validate EEPROM checksum
.SH SYNOPSIS
.B "i40e_status" i40e_validate_nvm_checksum
.BI "(struct i40e_hw *hw "  ","
.BI "u16 *checksum "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
.IP "checksum" 12
calculated checksum
.SH "DESCRIPTION"
Performs checksum calculation and validates the NVM SW checksum. If the
caller does not need checksum, the value can be NULL.
