.TH "i40e_aq_start_lldp" 9 "i40e_aq_start_lldp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_aq_start_lldp \- 
.SH SYNOPSIS
.B "i40e_status" i40e_aq_start_lldp
.BI "(struct i40e_hw *hw "  ","
.BI "bool persist "  ","
.BI "struct i40e_asq_cmd_details *cmd_details "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hw struct
.IP "persist" 12
True if start of LLDP should be persistent across power cycles
.IP "cmd_details" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Start the embedded LLDP Agent on all ports.
