.TH "i40e_set_fc" 9 "i40e_set_fc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_set_fc \- 
.SH SYNOPSIS
.B "enum i40e_status_code" i40e_set_fc
.BI "(struct i40e_hw *hw "  ","
.BI "u8 *aq_failures "  ","
.BI "bool atomic_restart "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hw struct
.IP "aq_failures" 12
buffer to return AdminQ failure information
.IP "atomic_restart" 12
whether to enable atomic link restart
.SH "DESCRIPTION"
Set the requested flow control mode using set_phy_config.
