.TH "i40e_notify_client_of_l2_param_changes" 9 "i40e_notify_client_of_l2_param_changes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_notify_client_of_l2_param_changes \- call the client notify callback
.SH SYNOPSIS
.B "void" i40e_notify_client_of_l2_param_changes
.BI "(struct i40e_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI with l2 param changes
.SH "DESCRIPTION"
If there is a client to this VSI, call the client
