.TH "i40e_dbg_dump_vf" 9 "i40e_dbg_dump_vf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_dbg_dump_vf \- dump VF info
.SH SYNOPSIS
.B "void" i40e_dbg_dump_vf
.BI "(struct i40e_pf *pf "  ","
.BI "int vf_id "  ");"
.SH ARGUMENTS
.IP "pf" 12
the i40e_pf created in command write
.IP "vf_id" 12
the vf_id from the user
