.TH "i40iw_alloc_query_fpm_buf" 9 "i40iw_alloc_query_fpm_buf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_alloc_query_fpm_buf \- allocate buffer for fpm
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_alloc_query_fpm_buf
.BI "(struct i40iw_sc_dev *dev "  ","
.BI "struct i40iw_dma_mem *mem "  ");"
.SH ARGUMENTS
.IP "dev" 12
hardware control device structure
.IP "mem" 12
buffer ptr for fpm to be allocated
.SH "RETURN"
memory allocation status
