.TH "i40iw_alloc_pd" 9 "i40iw_alloc_pd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_alloc_pd \- allocate protection domain
.SH SYNOPSIS
.B "int" i40iw_alloc_pd
.BI "(struct ib_pd *pd "  ","
.BI "struct ib_udata *udata "  ");"
.SH ARGUMENTS
.IP "pd" 12
PD pointer
.IP "udata" 12
user data
