.TH "i40iw_create_ceq" 9 "i40iw_create_ceq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_create_ceq \- create completion event queue
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_create_ceq
.BI "(struct i40iw_device *iwdev "  ","
.BI "struct i40iw_ceq *iwceq "  ","
.BI "u32 ceq_id "  ");"
.SH ARGUMENTS
.IP "iwdev" 12
iwarp device
.IP "iwceq" 12
pointer to the ceq resources to be created
.IP "ceq_id" 12
the id number of the iwceq
.SH "DESCRIPTION"
Return 0, if the ceq and the resources associated with it
are successfully created, otherwise return error
