.TH "i40iw_create_hmc_objs" 9 "i40iw_create_hmc_objs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_create_hmc_objs \- create all hmc objects for the device
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_create_hmc_objs
.BI "(struct i40iw_device *iwdev "  ","
.BI "bool is_pf "  ");"
.SH ARGUMENTS
.IP "iwdev" 12
iwarp device
.IP "is_pf" 12
true if the function is PF otherwise false
.SH "DESCRIPTION"
Create the device hmc objects and allocate hmc pages
Return 0 if successful, otherwise clean up and return error
