.TH "i40iw_setup_termhdr" 9 "i40iw_setup_termhdr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_setup_termhdr \- termhdr for terminate pkt
.SH SYNOPSIS
.B "void" i40iw_setup_termhdr
.BI "(struct i40iw_sc_qp *qp "  ","
.BI "struct i40iw_terminate_hdr *hdr "  ","
.BI "enum i40iw_flush_opcode opcode "  ","
.BI "u8 layer_etype "  ","
.BI "u8 err "  ");"
.SH ARGUMENTS
.IP "qp" 12
sc qp ptr for pkt
.IP "hdr" 12
term hdr
.IP "opcode" 12
flush opcode for termhdr
.IP "layer_etype" 12
error layer + error type
.IP "err" 12
error cod ein the header
