.TH "i40iw_puda_get_bufpool" 9 "i40iw_puda_get_bufpool" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_puda_get_bufpool \- return buffer from resource
.SH SYNOPSIS
.B "struct i40iw_puda_buf *" i40iw_puda_get_bufpool
.BI "(struct i40iw_puda_rsrc *rsrc "  ");"
.SH ARGUMENTS
.IP "rsrc" 12
resource to use for buffer
