.TH "i40iw_ieq_receive" 9 "i40iw_ieq_receive" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_ieq_receive \- received exception buffer
.SH SYNOPSIS
.B "void" i40iw_ieq_receive
.BI "(struct i40iw_sc_vsi *vsi "  ","
.BI "struct i40iw_puda_buf *buf "  ");"
.SH ARGUMENTS
.IP "vsi" 12
pointer to vsi structure
.IP "buf" 12
exception buffer received
