.TH "i40iw_hwreg_mr" 9 "i40iw_hwreg_mr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_hwreg_mr \- send cqp command for memory registration
.SH SYNOPSIS
.B "int" i40iw_hwreg_mr
.BI "(struct i40iw_device *iwdev "  ","
.BI "struct i40iw_mr *iwmr "  ","
.BI "u16 access "  ");"
.SH ARGUMENTS
.IP "iwdev" 12
iwarp device
.IP "iwmr" 12
iwarp mr pointer
.IP "access" 12
access for MR
