.TH "i40iw_vchnl_vf_get_hmc_fcn" 9 "i40iw_vchnl_vf_get_hmc_fcn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_vchnl_vf_get_hmc_fcn \- Request HMC Function
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_vchnl_vf_get_hmc_fcn
.BI "(struct i40iw_sc_dev *dev "  ","
.BI "u16 *hmc_fcn "  ");"
.SH ARGUMENTS
.IP "dev" 12
IWARP device pointer
.IP "hmc_fcn" 12
HMC function index pointer
