.TH "i40iw_next_pbl_addr" 9 "i40iw_next_pbl_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_next_pbl_addr \- Get next pbl address
.SH SYNOPSIS
.B "u64 *" i40iw_next_pbl_addr
.BI "(u64 *pbl "  ","
.BI "struct i40iw_pble_info **pinfo "  ","
.BI "u32 *idx "  ");"
.SH ARGUMENTS
.IP "pbl" 12
pointer to a pble
.IP "pinfo" 12
info pointer
.IP "idx" 12
index
