.TH "i40iw_get_rdma_features" 9 "i40iw_get_rdma_features" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_get_rdma_features \- get RDMA features
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_get_rdma_features
.BI "(struct i40iw_sc_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
sc device struct
