.TH "i40iw_change_l2params" 9 "i40iw_change_l2params" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_change_l2params \- given the new l2 parameters, change all qp
.SH SYNOPSIS
.B "void" i40iw_change_l2params
.BI "(struct i40iw_sc_vsi *vsi "  ","
.BI "struct i40iw_l2params *l2params "  ");"
.SH ARGUMENTS
.IP "vsi" 12
pointer to the vsi structure
.IP "l2params" 12
New paramaters from l2
