.TH "i40iw_destroy_cqp" 9 "i40iw_destroy_cqp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_destroy_cqp \- destroy control qp
.SH SYNOPSIS
.B "void" i40iw_destroy_cqp
.BI "(struct i40iw_device *iwdev "  ","
.BI "bool free_hwcqp "  ");"
.SH ARGUMENTS
.IP "iwdev" 12
iwarp device
.IP "free_hwcqp" 12
1 if CQP should be destroyed
.SH "DESCRIPTION"
Issue destroy cqp request and
free the resources associated with the cqp
