.TH "i40iw_insert_wqe_hdr" 9 "i40iw_insert_wqe_hdr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_insert_wqe_hdr \- write wqe header
.SH SYNOPSIS
.B "void" i40iw_insert_wqe_hdr
.BI "(u64 *wqe "  ","
.BI "u64 header "  ");"
.SH ARGUMENTS
.IP "wqe" 12
cqp wqe for header
.IP "header" 12
header for the cqp wqe
