.TH "i40iw_add_mqh_4" 9 "i40iw_add_mqh_4" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_add_mqh_4 \- Adds multiple qhashes for IPv4
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_add_mqh_4
.BI "(struct i40iw_device *iwdev "  ","
.BI "struct i40iw_cm_info *cm_info "  ","
.BI "struct i40iw_cm_listener *cm_parent_listen_node "  ");"
.SH ARGUMENTS
.IP "iwdev" 12
iWarp device
.IP "cm_info" 12
CM info for parent listen node
.IP "cm_parent_listen_node" 12
The parent listen node
.SH "DESCRIPTION"
Adds a qhash and a child listen node for every IPv4 address
on the adapter and adds the associated qhash filter
