.TH "i40iw_vf_hmcinfo_from_fpm" 9 "i40iw_vf_hmcinfo_from_fpm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_vf_hmcinfo_from_fpm \- get ptr to hmc for func_id
.SH SYNOPSIS
.B "struct i40iw_hmc_info *" i40iw_vf_hmcinfo_from_fpm
.BI "(struct i40iw_sc_dev *dev "  ","
.BI "u8 hmc_fn_id "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to the device structure
.IP "hmc_fn_id" 12
hmc's function id
