.TH "i40iw_hmc_finish_add_sd_reg" 9 "i40iw_hmc_finish_add_sd_reg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_hmc_finish_add_sd_reg \- program sd entries for objects
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_hmc_finish_add_sd_reg
.BI "(struct i40iw_sc_dev *dev "  ","
.BI "struct i40iw_hmc_create_obj_info *info "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to the device structure
.IP "info" 12
create obj info
