.TH "i40iw_cleanup_pending_cqp_op" 9 "i40iw_cleanup_pending_cqp_op" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_cleanup_pending_cqp_op \- clean-up cqp with no completions
.SH SYNOPSIS
.B "void" i40iw_cleanup_pending_cqp_op
.BI "(struct i40iw_device *iwdev "  ");"
.SH ARGUMENTS
.IP "iwdev" 12
iwarp device
