.TH "i40iw_term_modify_qp" 9 "i40iw_term_modify_qp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_term_modify_qp \- modify qp for term message
.SH SYNOPSIS
.B "void" i40iw_term_modify_qp
.BI "(struct i40iw_sc_qp *qp "  ","
.BI "u8 next_state "  ","
.BI "u8 term "  ","
.BI "u8 term_len "  ");"
.SH ARGUMENTS
.IP "qp" 12
hardware control qp
.IP "next_state" 12
qp's next state
.IP "term" 12
terminate code
.IP "term_len" 12
length
