.TH "i40iw_puda_send" 9 "i40iw_puda_send" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_puda_send \- complete send wqe for transmit
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_puda_send
.BI "(struct i40iw_sc_qp *qp "  ","
.BI "struct i40iw_puda_send_info *info "  ");"
.SH ARGUMENTS
.IP "qp" 12
puda qp for send
.IP "info" 12
buffer information for transmit
