.TH "i40iw_handle_tcp_options" 9 "i40iw_handle_tcp_options" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_handle_tcp_options \- 
.SH SYNOPSIS
.B "int" i40iw_handle_tcp_options
.BI "(struct i40iw_cm_node *cm_node "  ","
.BI "struct tcphdr *tcph "  ","
.BI "int optionsize "  ","
.BI "int passive "  ");"
.SH ARGUMENTS
.IP "cm_node" 12
connection's node
.IP "tcph" 12
pointer tcp header
.IP "optionsize" 12
size of options rcvd
.IP "passive" 12
active or passive flag
