.TH "i40iw_create_event" 9 "i40iw_create_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_create_event \- create cm event
.SH SYNOPSIS
.B "struct i40iw_cm_event *" i40iw_create_event
.BI "(struct i40iw_cm_node *cm_node "  ","
.BI "enum i40iw_cm_event_type type "  ");"
.SH ARGUMENTS
.IP "cm_node" 12
connection's node
.IP "type" 12
Event type to generate
