.TH "i40iw_l2param_change" 9 "i40iw_l2param_change" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_l2param_change \- handle qs handles for qos and mss change
.SH SYNOPSIS
.B "void" i40iw_l2param_change
.BI "(struct i40e_info *ldev "  ","
.BI "struct i40e_client *client "  ","
.BI "struct i40e_params *params "  ");"
.SH ARGUMENTS
.IP "ldev" 12
lan device information
.IP "client" 12
client for paramater change
.IP "params" 12
new parameters from L2
