.TH "i40iw_fill_sockaddr4" 9 "i40iw_fill_sockaddr4" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_fill_sockaddr4 \- get addr info for passive connection
.SH SYNOPSIS
.B "void" i40iw_fill_sockaddr4
.BI "(struct i40iw_cm_node *cm_node "  ","
.BI "struct iw_cm_event *event "  ");"
.SH ARGUMENTS
.IP "cm_node" 12
connection's node
.IP "event" 12
upper layer's cm event
