.TH "i810_load_pll" 9 "i810_load_pll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i810_load_pll \- loads values for the hardware PLL clock
.SH SYNOPSIS
.B "void" i810_load_pll
.BI "(struct i810fb_par *par "  ");"
.SH ARGUMENTS
.IP "par" 12
pointer to i810fb_par structure
.SH "DESCRIPTION"
Loads the P, M, and N registers.  
