.TH "i810_get_watermark" 9 "i810_get_watermark" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i810_get_watermark \- gets watermark
.SH SYNOPSIS
.B "u32" i810_get_watermark
.BI "(const struct fb_var_screeninfo *var "  ","
.BI "struct i810fb_par *par "  ");"
.SH ARGUMENTS
.IP "var" 12
pointer to fb_var_screeninfo
.IP "par" 12
pointer to i810fb_par structure
.SH "DESCRIPTION"
Gets the required watermark based on 
pixelclock and RAMBUS frequency.
.SH "RETURN"
watermark
