.TH "i810_init_defaults" 9 "i810_init_defaults" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i810_init_defaults \- initializes default values to use
.SH SYNOPSIS
.B "void" i810_init_defaults
.BI "(struct i810fb_par *par "  ","
.BI "struct fb_info *info "  ");"
.SH ARGUMENTS
.IP "par" 12
pointer to i810fb_par structure
.IP "info" 12
pointer to current fb_info structure
