.TH "i915_gem_object_create_internal" 9 "i915_gem_object_create_internal" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i915_gem_object_create_internal \- create an object with volatile pages
.SH SYNOPSIS
.B "struct drm_i915_gem_object *" i915_gem_object_create_internal
.BI "(struct drm_i915_private *i915 "  ","
.BI "phys_addr_t size "  ");"
.SH ARGUMENTS
.IP "i915" 12
the i915 device
.IP "size" 12
the size in bytes of backing storage to allocate for the object
.SH "DESCRIPTION"
Creates a new object that wraps some internal memory for private use.
This object is not backed by swappable storage, and as such its contents
are volatile and only valid whilst pinned. If the object is reaped by the
shrinker, its pages and data will be discarded. Equally, it is not a full
GEM object and so not valid for access from userspace. This makes it useful
for hardware interfaces like ringbuffers (which are pinned from the time
the request is written to the time the hardware stops accessing it), but
not for contexts (which need to be preserved when not active for later
reuse). Note that it is not cleared upon allocation.
