.TH "i91u_unmap_scb" 9 "i91u_unmap_scb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i91u_unmap_scb \- Unmap a command
.SH SYNOPSIS
.B "void" i91u_unmap_scb
.BI "(struct pci_dev *pci_dev "  ","
.BI "struct scsi_cmnd *cmnd "  ");"
.SH ARGUMENTS
.IP "pci_dev" 12
PCI device the command is for
.IP "cmnd" 12
The command itself

Unmap any PCI mapping/IOMMU resources allocated when the command
was mapped originally as part of initio_build_scb
