.TH "iavf_init_get_resources" 9 "iavf_init_get_resources" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_init_get_resources \- third step of driver startup
.SH SYNOPSIS
.B "int" iavf_init_get_resources
.BI "(struct iavf_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure
.SH "DESCRIPTION"
Function process __IAVF_INIT_GET_RESOURCES driver state and
finishes driver initialization procedure.
When success the state is changed to __IAVF_DOWN
when fails it returns -EAGAIN
