.TH "iavf_notify_client_message" 9 "iavf_notify_client_message" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_notify_client_message \- call the client message receive callback
.SH SYNOPSIS
.B "void" iavf_notify_client_message
.BI "(struct iavf_vsi *vsi "  ","
.BI "u8 *msg "  ","
.BI "u16 len "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI associated with this client
.IP "msg" 12
message buffer
.IP "len" 12
length of message
.SH "DESCRIPTION"
If there is a client to this VSI, call the client
