.TH "iavf_del_vlan" 9 "iavf_del_vlan" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_del_vlan \- Remove a vlan filter from the list
.SH SYNOPSIS
.B "void" iavf_del_vlan
.BI "(struct iavf_adapter *adapter "  ","
.BI "u16 vlan "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure
.IP "vlan" 12
VLAN tag
