.TH "iavf_reinit_interrupt_scheme" 9 "iavf_reinit_interrupt_scheme" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_reinit_interrupt_scheme \- Reallocate queues and vectors
.SH SYNOPSIS
.B "int" iavf_reinit_interrupt_scheme
.BI "(struct iavf_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure
.SH "DESCRIPTION"
Returns 0 on success, negative on failure
