.TH "iavf_tso" 9 "iavf_tso" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_tso \- set up the tso context descriptor
.SH SYNOPSIS
.B "int" iavf_tso
.BI "(struct iavf_tx_buffer *first "  ","
.BI "u8 *hdr_len "  ","
.BI "u64 *cd_type_cmd_tso_mss "  ");"
.SH ARGUMENTS
.IP "first" 12
pointer to first Tx buffer for xmit
.IP "hdr_len" 12
ptr to the size of the packet header
.IP "cd_type_cmd_tso_mss" 12
Quad Word 1
.SH "DESCRIPTION"
Returns 0 if no TSO can happen, 1 if tso is going, or error
