.TH "iavf_request_misc_irq" 9 "iavf_request_misc_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_request_misc_irq \- Initialize MSI-X interrupts
.SH SYNOPSIS
.B "int" iavf_request_misc_irq
.BI "(struct iavf_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure
.SH "DESCRIPTION"
Allocates MSI-X vector 0 and requests interrupts from the kernel. This
vector is only for the admin queue, and stays active even when the netdev
is closed.
