.TH "ib_find_gid" 9 "ib_find_gid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ib_find_gid \- Returns the port number and GID table index where a specified GID value occurs. Its searches only for IB link layer.
.SH SYNOPSIS
.B "int" ib_find_gid
.BI "(struct ib_device *device "  ","
.BI "union ib_gid *gid "  ","
.BI "u8 *port_num "  ","
.BI "u16 *index "  ");"
.SH ARGUMENTS
.IP "device" 12
The device to query.
.IP "gid" 12
The GID value to search for.
.IP "port_num" 12
The port number of the device where the GID value was found.
.IP "index" 12
The index into the GID table where the GID was found.  This
parameter may be NULL.
