.TH "ib_get_net_dev_by_params" 9 "ib_get_net_dev_by_params" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ib_get_net_dev_by_params \- Return the appropriate net_dev for a received CM request
.SH SYNOPSIS
.B "struct net_device *" ib_get_net_dev_by_params
.BI "(struct ib_device *dev "  ","
.BI "u8 port "  ","
.BI "u16 pkey "  ","
.BI "const union ib_gid *gid "  ","
.BI "const struct sockaddr *addr "  ");"
.SH ARGUMENTS
.IP "dev" 12
An RDMA device on which the request has been received.
.IP "port" 12
Port number on the RDMA device.
.IP "pkey" 12
The Pkey the request came on.
.IP "gid" 12
A GID that the net_dev uses to communicate.
.IP "addr" 12
Contains the IP address that the request specified as its
destination.
