.TH "ib_port_register_module_stat" 9 "ib_port_register_module_stat" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ib_port_register_module_stat \- add module counters under relevant port of IB device.
.SH SYNOPSIS
.B "int" ib_port_register_module_stat
.BI "(struct ib_device *device "  ","
.BI "u8 port_num "  ","
.BI "struct kobject *kobj "  ","
.BI "struct kobj_type *ktype "  ","
.BI "const char *name "  ");"
.SH ARGUMENTS
.IP "device" 12
IB device to add counters
.IP "port_num" 12
valid port number
.IP "kobj" 12
pointer to the kobject to initialize
.IP "ktype" 12
pointer to the ktype for this kobject.
.IP "name" 12
the name of the kobject
