.TH "ib_ud_header_unpack" 9 "ib_ud_header_unpack" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ib_ud_header_unpack \- Unpack UD header struct from wire format
.SH SYNOPSIS
.B "int" ib_ud_header_unpack
.BI "(void *buf "  ","
.BI "struct ib_ud_header *header "  ");"
.SH ARGUMENTS
.IP "buf" 12
Buffer to pack into
.IP "header" 12
UD header struct
.SH "DESCRIPTION"
\fBib_ud_header_pack\fP unpacks the UD header structure \fIheader\fP from wire
format in the buffer \fIbuf\fP.
