.TH "ib_umem_odp_alloc_implicit" 9 "ib_umem_odp_alloc_implicit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ib_umem_odp_alloc_implicit \- Allocate a parent implicit ODP umem
.SH SYNOPSIS
.B "struct ib_umem_odp *" ib_umem_odp_alloc_implicit
.BI "(struct ib_device *device "  ","
.BI "int access "  ");"
.SH ARGUMENTS
.IP "device" 12
IB device to create UMEM
.IP "access" 12
ib_reg_mr access flags
.SH "DESCRIPTION"

Implicit ODP umems do not have a VA range and do not have any page lists.
They exist only to hold the per_mm reference to help the driver create
children umems.
