.TH "ibmvfc_purge_requests" 9 "ibmvfc_purge_requests" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvfc_purge_requests \- Our virtual adapter just shut down. Purge any sent requests
.SH SYNOPSIS
.B "void" ibmvfc_purge_requests
.BI "(struct ibmvfc_host *vhost "  ","
.BI "int error_code "  ");"
.SH ARGUMENTS
.IP "vhost" 12
ibmvfc host struct
.IP "error_code" 12
error code to fail requests with
.SH "DESCRIPTION"
Return value:
none
