.TH "ibmvtpm_crq_send_init" 9 "ibmvtpm_crq_send_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvtpm_crq_send_init \- Send a CRQ initialize message
.SH SYNOPSIS
.B "int" ibmvtpm_crq_send_init
.BI "(struct ibmvtpm_dev *ibmvtpm "  ");"
.SH ARGUMENTS
.IP "ibmvtpm" 12
vtpm device struct
.SH "RETURN"
0 on success.
Non-zero on failure.
