.TH "ibmvfc_match_target" 9 "ibmvfc_match_target" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvfc_match_target \- Match function for specified target
.SH SYNOPSIS
.B "int" ibmvfc_match_target
.BI "(struct ibmvfc_event *evt "  ","
.BI "void *device "  ");"
.SH ARGUMENTS
.IP "evt" 12
ibmvfc event struct
.IP "device" 12
device to match (starget)
.SH "RETURN"
1 if event matches starget / 0 if event does not match starget
