.TH "ibmvmc_get_free_hmc" 9 "ibmvmc_get_free_hmc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvmc_get_free_hmc \- Get Free HMC
.SH SYNOPSIS
.B "struct ibmvmc_hmc *" ibmvmc_get_free_hmc
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
Pointer to an available HMC Connection
Null otherwise
