.TH "ibmvfc_discover_targets_done" 9 "ibmvfc_discover_targets_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvfc_discover_targets_done \- Completion handler for discover targets MAD
.SH SYNOPSIS
.B "void" ibmvfc_discover_targets_done
.BI "(struct ibmvfc_event *evt "  ");"
.SH ARGUMENTS
.IP "evt" 12
ibmvfc event struct
