.TH "ibmvfc_alloc_target" 9 "ibmvfc_alloc_target" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvfc_alloc_target \- Allocate and initialize an ibmvfc target
.SH SYNOPSIS
.B "int" ibmvfc_alloc_target
.BI "(struct ibmvfc_host *vhost "  ","
.BI "struct ibmvfc_discover_targets_entry *target "  ");"
.SH ARGUMENTS
.IP "vhost" 12
ibmvfc host struct
.IP "target" 12
-- undescribed --
.SH "RETURN"
0 on success / other on failure
