.TH "ice_add_rule_internal" 9 "ice_add_rule_internal" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_add_rule_internal \- add rule for a given lookup type
.SH SYNOPSIS
.B "enum ice_status" ice_add_rule_internal
.BI "(struct ice_hw *hw "  ","
.BI "u8 recp_id "  ","
.BI "struct ice_fltr_list_entry *f_entry "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.IP "recp_id" 12
lookup type (recipe ID) for which rule has to be added
.IP "f_entry" 12
structure containing MAC forwarding information
.SH "DESCRIPTION"
Adds or updates the rule lists for a given recipe
