.TH "ice_get_prof" 9 "ice_get_prof" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_get_prof \- get profile
.SH SYNOPSIS
.B "enum ice_status" ice_get_prof
.BI "(struct ice_hw *hw "  ","
.BI "enum ice_block blk "  ","
.BI "u64 hdl "  ","
.BI "struct list_head *chg "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "blk" 12
hardware block
.IP "hdl" 12
profile handle
.IP "chg" 12
change list
