.TH "ice_parse_valid_functions_cap" 9 "ice_parse_valid_functions_cap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_parse_valid_functions_cap \- Parse ICE_AQC_CAPS_VALID_FUNCTIONS caps
.SH SYNOPSIS
.B "void" ice_parse_valid_functions_cap
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_hw_dev_caps *dev_p "  ","
.BI "struct ice_aqc_list_caps_elem *cap "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "dev_p" 12
pointer to device capabilities structure
.IP "cap" 12
capability element to parse
.SH "DESCRIPTION"
Parse ICE_AQC_CAPS_VALID_FUNCTIONS for device capabilities.
