.TH "ice_set_fd_vsi_ctx" 9 "ice_set_fd_vsi_ctx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_set_fd_vsi_ctx \- Set FD VSI context before adding a VSI
.SH SYNOPSIS
.B "void" ice_set_fd_vsi_ctx
.BI "(struct ice_vsi_ctx *ctxt "  ","
.BI "struct ice_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "ctxt" 12
the VSI context being set
.IP "vsi" 12
the VSI being configured
