.TH "ice_xsk_wakeup" 9 "ice_xsk_wakeup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_xsk_wakeup \- Implements ndo_xsk_wakeup
.SH SYNOPSIS
.B "int" ice_xsk_wakeup
.BI "(struct net_device *netdev "  ","
.BI "u32 queue_id "  ","
.BI "u32 __always_unused flags "  ");"
.SH ARGUMENTS
.IP "netdev" 12
net_device
.IP "queue_id" 12
queue to wake up
.IP "flags" 12
ignored in our case, since we have Rx and Tx in the same NAPI
.SH "DESCRIPTION"
Returns negative on error, zero otherwise.
