.TH "ice_fdir_get_prgm_desc" 9 "ice_fdir_get_prgm_desc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_fdir_get_prgm_desc \- set a fdir descriptor from a fdir filter struct
.SH SYNOPSIS
.B "void" ice_fdir_get_prgm_desc
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_fdir_fltr *input "  ","
.BI "struct ice_fltr_desc *fdesc "  ","
.BI "bool add "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.IP "input" 12
filter
.IP "fdesc" 12
filter descriptor
.IP "add" 12
if add is true, this is an add operation, false implies delete
