.TH "ice_vc_get_max_frame_size" 9 "ice_vc_get_max_frame_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_vc_get_max_frame_size \- get max frame size allowed for VF
.SH SYNOPSIS
.B "u16" ice_vc_get_max_frame_size
.BI "(struct ice_vf *vf "  ");"
.SH ARGUMENTS
.IP "vf" 12
VF used to determine max frame size
.SH "DESCRIPTION"
Max frame size is determined based on the current port's max frame size and
whether a port VLAN is configured on this VF. The VF is not aware whether
it's in a port VLAN so the PF needs to account for this in max frame size
checks and sending the max frame size to the VF.
