.TH "ice_xsk_pool_enable" 9 "ice_xsk_pool_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_xsk_pool_enable \- enable a buffer pool region
.SH SYNOPSIS
.B "int" ice_xsk_pool_enable
.BI "(struct ice_vsi *vsi "  ","
.BI "struct xsk_buff_pool *pool "  ","
.BI "u16 qid "  ");"
.SH ARGUMENTS
.IP "vsi" 12
Current VSI
.IP "pool" 12
pointer to a requested buffer pool region
.IP "qid" 12
queue ID
.SH "DESCRIPTION"
Returns 0 on success, negative on failure
