.TH "ice_caps_to_fec_mode" 9 "ice_caps_to_fec_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_caps_to_fec_mode \- 
.SH SYNOPSIS
.B "enum ice_fec_mode" ice_caps_to_fec_mode
.BI "(u8 caps "  ","
.BI "u8 fec_options "  ");"
.SH ARGUMENTS
.IP "caps" 12
PHY capabilities
.IP "fec_options" 12
Link FEC options
.SH "DESCRIPTION"
Convert PHY FEC capabilities to ice FEC mode
