.TH "ice_vsi_open" 9 "ice_vsi_open" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_vsi_open \- Called when a network interface is made active
.SH SYNOPSIS
.B "int" ice_vsi_open
.BI "(struct ice_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI to open
.SH "DESCRIPTION"
Initialization of the VSI

Returns 0 on success, negative value on error
