.TH "ice_init_ctrlq_locks" 9 "ice_init_ctrlq_locks" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_init_ctrlq_locks \- Initialize locks for a control queue
.SH SYNOPSIS
.B "void" ice_init_ctrlq_locks
.BI "(struct ice_ctl_q_info *cq "  ");"
.SH ARGUMENTS
.IP "cq" 12
pointer to the control queue
.SH "DESCRIPTION"
Initializes the send and receive queue locks for a given control queue.
