.TH "ice_get_nvm_ver_info" 9 "ice_get_nvm_ver_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_get_nvm_ver_info \- Read NVM version information
.SH SYNOPSIS
.B "enum ice_status" ice_get_nvm_ver_info
.BI "(struct ice_hw *hw "  ","
.BI "enum ice_bank_select bank "  ","
.BI "struct ice_nvm_info *nvm "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "bank" 12
whether to read from the active or inactive flash bank
.IP "nvm" 12
pointer to NVM info structure
.SH "DESCRIPTION"
Read the NVM EETRACK ID and map version of the main NVM image bank, filling
in the NVM info structure.
