.TH "ice_get_link_speed_based_on_phy_type" 9 "ice_get_link_speed_based_on_phy_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_get_link_speed_based_on_phy_type \- returns link speed
.SH SYNOPSIS
.B "u16" ice_get_link_speed_based_on_phy_type
.BI "(u64 phy_type_low "  ","
.BI "u64 phy_type_high "  ");"
.SH ARGUMENTS
.IP "phy_type_low" 12
lower part of phy_type
.IP "phy_type_high" 12
higher part of phy_type
.SH "DESCRIPTION"
This helper function will convert an entry in PHY type structure
[phy_type_low, phy_type_high] to its corresponding link speed.
.SH "NOTE"
In the structure of [phy_type_low, phy_type_high], there should
be one bit set, as this function will convert one PHY type to its
speed.
If no bit gets set, ICE_LINK_SPEED_UNKNOWN will be returned
If more than one bit gets set, ICE_LINK_SPEED_UNKNOWN will be returned
