.TH "ice_aq_set_lldp_mib" 9 "ice_aq_set_lldp_mib" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_set_lldp_mib \- Set the LLDP MIB
.SH SYNOPSIS
.B "enum ice_status" ice_aq_set_lldp_mib
.BI "(struct ice_hw *hw "  ","
.BI "u8 mib_type "  ","
.BI "void *buf "  ","
.BI "u16 buf_size "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "mib_type" 12
Local, Remote or both Local and Remote MIBs
.IP "buf" 12
pointer to the caller-supplied buffer to store the MIB block
.IP "buf_size" 12
size of the buffer (in bytes)
.IP "cd" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Set the LLDP MIB. (0x0A08)
