.TH "ice_alloc_lan_q_ctx" 9 "ice_alloc_lan_q_ctx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_alloc_lan_q_ctx \- allocate LAN queue contexts for the given VSI and TC
.SH SYNOPSIS
.B "enum ice_status" ice_alloc_lan_q_ctx
.BI "(struct ice_hw *hw "  ","
.BI "u16 vsi_handle "  ","
.BI "u8 tc "  ","
.BI "u16 new_numqs "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "vsi_handle" 12
VSI handle
.IP "tc" 12
TC number
.IP "new_numqs" 12
number of queues
