.TH "ice_init_pkg_info" 9 "ice_init_pkg_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_init_pkg_info \- 
.SH SYNOPSIS
.B "enum ice_status" ice_init_pkg_info
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_pkg_hdr *pkg_hdr "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.IP "pkg_hdr" 12
pointer to the driver's package hdr
.SH "DESCRIPTION"
Saves off the package details into the HW structure.
