.TH "ice_write_es" 9 "ice_write_es" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_write_es \- write an extraction sequence to hardware
.SH SYNOPSIS
.B "void" ice_write_es
.BI "(struct ice_hw *hw "  ","
.BI "enum ice_block blk "  ","
.BI "u8 prof_id "  ","
.BI "struct ice_fv_word *fv "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "blk" 12
the block in which to write the extraction sequence
.IP "prof_id" 12
the profile ID to write
.IP "fv" 12
pointer to the extraction sequence to write - NULL to clear extraction
