.TH "ice_match_prop_lst" 9 "ice_match_prop_lst" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_match_prop_lst \- determine if properties of two lists match
.SH SYNOPSIS
.B "bool" ice_match_prop_lst
.BI "(struct list_head *list1 "  ","
.BI "struct list_head *list2 "  ");"
.SH ARGUMENTS
.IP "list1" 12
first properties list
.IP "list2" 12
second properties list
.SH "DESCRIPTION"
Count, cookies and the order must match in order to be considered equivalent.
