.TH "ice_get_pkg_info" 9 "ice_get_pkg_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_get_pkg_info \- 
.SH SYNOPSIS
.B "enum ice_status" ice_get_pkg_info
.BI "(struct ice_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.SH "DESCRIPTION"
Store details of the package currently loaded in HW into the HW structure.
