.TH "ice_aq_cfg_sched_elems" 9 "ice_aq_cfg_sched_elems" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_cfg_sched_elems \- configures scheduler elements
.SH SYNOPSIS
.B "enum ice_status" ice_aq_cfg_sched_elems
.BI "(struct ice_hw *hw "  ","
.BI "u16 elems_req "  ","
.BI "struct ice_aqc_txsched_elem_data *buf "  ","
.BI "u16 buf_size "  ","
.BI "u16 *elems_cfgd "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "elems_req" 12
number of elements to configure
.IP "buf" 12
pointer to buffer
.IP "buf_size" 12
buffer size in bytes
.IP "elems_cfgd" 12
returns total number of elements configured
.IP "cd" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Configure scheduling elements (0x0403)
