.TH "ice_set_fecparam" 9 "ice_set_fecparam" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_set_fecparam \- Set FEC link options
.SH SYNOPSIS
.B "int" ice_set_fecparam
.BI "(struct net_device *netdev "  ","
.BI "struct ethtool_fecparam *fecparam "  ");"
.SH ARGUMENTS
.IP "netdev" 12
network interface device structure
.IP "fecparam" 12
Ethtool structure to retrieve FEC parameters
