.TH "ice_fill_tx_timer_and_fc_thresh" 9 "ice_fill_tx_timer_and_fc_thresh" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_fill_tx_timer_and_fc_thresh \- 
.SH SYNOPSIS
.B "void" ice_fill_tx_timer_and_fc_thresh
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_aqc_set_mac_cfg *cmd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "cmd" 12
pointer to MAC cfg structure
.SH "DESCRIPTION"
Add Tx timer and FC refresh threshold info to Set MAC Config AQ command
descriptor
