.TH "ice_vf_get_port_info" 9 "ice_vf_get_port_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_vf_get_port_info \- Get the VF's port info structure
.SH SYNOPSIS
.B "struct ice_port_info *" ice_vf_get_port_info
.BI "(struct ice_vf *vf "  ");"
.SH ARGUMENTS
.IP "vf" 12
VF used to get the port info structure for
