.TH "ice_dcb_get_tc" 9 "ice_dcb_get_tc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_dcb_get_tc \- Get the TC associated with the queue
.SH SYNOPSIS
.B "u8" ice_dcb_get_tc
.BI "(struct ice_vsi *vsi "  ","
.BI "int queue_index "  ");"
.SH ARGUMENTS
.IP "vsi" 12
ptr to the VSI
.IP "queue_index" 12
queue number associated with VSI
