.TH "ice_alloc_tcam_ent" 9 "ice_alloc_tcam_ent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_alloc_tcam_ent \- allocate hardware TCAM entry
.SH SYNOPSIS
.B "enum ice_status" ice_alloc_tcam_ent
.BI "(struct ice_hw *hw "  ","
.BI "enum ice_block blk "  ","
.BI "u16 *tcam_idx "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "blk" 12
the block to allocate the TCAM for
.IP "tcam_idx" 12
pointer to variable to receive the TCAM entry
.SH "DESCRIPTION"
This function allocates a new entry in a Profile ID TCAM for a specific
block.
