.TH "ice_fltr_prepare_eth" 9 "ice_fltr_prepare_eth" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_fltr_prepare_eth \- add or remove ethertype filter
.SH SYNOPSIS
.B "enum ice_status" ice_fltr_prepare_eth
.BI "(struct ice_vsi *vsi "  ","
.BI "u16 ethertype "  ","
.BI "u16 flag "  ","
.BI "enum ice_sw_fwd_act_type action "  ","
.BI "enum ice_status (*eth_action)(struct ice_vsi *, struct list_head *) "  ");"
.SH ARGUMENTS
.IP "vsi" 12
pointer to VSI struct
.IP "ethertype" 12
ethertype of packet to be filtered
.IP "flag" 12
direction of packet, Tx or Rx
.IP "action" 12
action to be performed on filter match
.IP "eth_action" 12
pointer to add or remove ethertype function
