.TH "ice_set_vf_state_qs_dis" 9 "ice_set_vf_state_qs_dis" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_set_vf_state_qs_dis \- Set VF queues state to disabled
.SH SYNOPSIS
.B "void" ice_set_vf_state_qs_dis
.BI "(struct ice_vf *vf "  ");"
.SH ARGUMENTS
.IP "vf" 12
pointer to the VF structure
