.TH "ice_copy_phy_caps_to_cfg" 9 "ice_copy_phy_caps_to_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_copy_phy_caps_to_cfg \- Copy PHY ability data to configuration data
.SH SYNOPSIS
.B "void" ice_copy_phy_caps_to_cfg
.BI "(struct ice_port_info *pi "  ","
.BI "struct ice_aqc_get_phy_caps_data *caps "  ","
.BI "struct ice_aqc_set_phy_cfg_data *cfg "  ");"
.SH ARGUMENTS
.IP "pi" 12
port information structure
.IP "caps" 12
PHY ability structure to copy date from
.IP "cfg" 12
PHY configuration structure to copy data to
.SH "DESCRIPTION"
Helper function to copy AQC PHY get ability data to PHY set configuration
data structure
