.TH "ice_get_rss_cfg" 9 "ice_get_rss_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_get_rss_cfg \- returns hashed fields for the given header types
.SH SYNOPSIS
.B "u64" ice_get_rss_cfg
.BI "(struct ice_hw *hw "  ","
.BI "u16 vsi_handle "  ","
.BI "u32 hdrs "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.IP "vsi_handle" 12
software VSI handle
.IP "hdrs" 12
protocol header type
.SH "DESCRIPTION"
This function will return the match fields of the first instance of flow
profile having the given header types and containing input VSI
