.TH "ice_check_for_pending_update" 9 "ice_check_for_pending_update" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_check_for_pending_update \- Check for a pending flash update
.SH SYNOPSIS
.B "int" ice_check_for_pending_update
.BI "(struct ice_pf *pf "  ","
.BI "const char *component "  ","
.BI "struct netlink_ext_ack *extack "  ");"
.SH ARGUMENTS
.IP "pf" 12
the PF driver structure
.IP "component" 12
if not NULL, the name of the component being updated
.IP "extack" 12
Netlink extended ACK structure
.SH "DESCRIPTION"
Check whether the device already has a pending flash update. If such an
update is found, cancel it so that the requested update may proceed.
.SH "RETURN"
zero on success, or a negative error code on failure.
