.TH "ice_get_inactive_netlist_ver" 9 "ice_get_inactive_netlist_ver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_get_inactive_netlist_ver \- 
.SH SYNOPSIS
.B "enum ice_status" ice_get_inactive_netlist_ver
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_netlist_info *netlist "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "netlist" 12
pointer to netlist version info structure
.SH "DESCRIPTION"
Read the netlist version data from the inactive netlist bank. Used to
extract version data of a pending flash update in order to display the
version data.
