.TH "ice_set_mac_type" 9 "ice_set_mac_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_set_mac_type \- Sets MAC type
.SH SYNOPSIS
.B "enum ice_status" ice_set_mac_type
.BI "(struct ice_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.SH "DESCRIPTION"
This function sets the MAC type of the adapter based on the
vendor ID and device ID stored in the HW structure.
