.TH "ice_aq_query_sched_res" 9 "ice_aq_query_sched_res" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_query_sched_res \- query scheduler resource
.SH SYNOPSIS
.B "enum ice_status" ice_aq_query_sched_res
.BI "(struct ice_hw *hw "  ","
.BI "u16 buf_size "  ","
.BI "struct ice_aqc_query_txsched_res_resp *buf "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "buf_size" 12
buffer size in bytes
.IP "buf" 12
pointer to buffer
.IP "cd" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Query scheduler resource allocation (0x0412)
