.TH "ice_sched_is_agg_inuse" 9 "ice_sched_is_agg_inuse" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_sched_is_agg_inuse \- check whether the aggregator is in use or not
.SH SYNOPSIS
.B "bool" ice_sched_is_agg_inuse
.BI "(struct ice_port_info *pi "  ","
.BI "struct ice_sched_node *node "  ");"
.SH ARGUMENTS
.IP "pi" 12
port information structure
.IP "node" 12
node pointer
.SH "DESCRIPTION"
This function checks whether the aggregator is attached with any VSI or not.
