.TH "ice_aq_set_port_id_led" 9 "ice_aq_set_port_id_led" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_set_port_id_led \- 
.SH SYNOPSIS
.B "enum ice_status" ice_aq_set_port_id_led
.BI "(struct ice_port_info *pi "  ","
.BI "bool is_orig_mode "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "pi" 12
pointer to the port information
.IP "is_orig_mode" 12
is this LED set to original mode (by the net-list)
.IP "cd" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Set LED value for the given port (0x06e9)
