.TH "ice_aq_resume_sched_elems" 9 "ice_aq_resume_sched_elems" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_resume_sched_elems \- resume scheduler elements
.SH SYNOPSIS
.B "enum ice_status" ice_aq_resume_sched_elems
.BI "(struct ice_hw *hw "  ","
.BI "u16 elems_req "  ","
.BI "__le32 *buf "  ","
.BI "u16 buf_size "  ","
.BI "u16 *elems_ret "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "elems_req" 12
number of elements to resume
.IP "buf" 12
pointer to buffer
.IP "buf_size" 12
buffer size in bytes
.IP "elems_ret" 12
returns total number of elements resumed
.IP "cd" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
resume scheduling elements (0x040A)
