.TH "ice_dcbnl_find_app" 9 "ice_dcbnl_find_app" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_dcbnl_find_app \- Search for APP in given DCB config
.SH SYNOPSIS
.B "bool" ice_dcbnl_find_app
.BI "(struct ice_dcbx_cfg *cfg "  ","
.BI "struct ice_dcb_app_priority_table *app "  ");"
.SH ARGUMENTS
.IP "cfg" 12
struct to hold DCBX config
.IP "app" 12
struct to hold app data to look for
