.TH "ice_is_mask_valid" 9 "ice_is_mask_valid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_is_mask_valid \- check mask field set
.SH SYNOPSIS
.B "bool" ice_is_mask_valid
.BI "(u64 mask "  ","
.BI "u64 field "  ");"
.SH ARGUMENTS
.IP "mask" 12
full mask to check
.IP "field" 12
field for which mask should be valid
.SH "DESCRIPTION"
If the mask is fully set return true. If it is not valid for field return
false.
