.TH "ice_aq_set_event_mask" 9 "ice_aq_set_event_mask" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_set_event_mask \- 
.SH SYNOPSIS
.B "enum ice_status" ice_aq_set_event_mask
.BI "(struct ice_hw *hw "  ","
.BI "u8 port_num "  ","
.BI "u16 mask "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "port_num" 12
port number of the physical function
.IP "mask" 12
event mask to be set
.IP "cd" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Set event mask (0x0613)
