.TH "ice_aq_send_msg_to_vf" 9 "ice_aq_send_msg_to_vf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_send_msg_to_vf \- 
.SH SYNOPSIS
.B "enum ice_status" ice_aq_send_msg_to_vf
.BI "(struct ice_hw *hw "  ","
.BI "u16 vfid "  ","
.BI "u32 v_opcode "  ","
.BI "u32 v_retval "  ","
.BI "u8 *msg "  ","
.BI "u16 msglen "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.IP "vfid" 12
VF ID to send msg
.IP "v_opcode" 12
opcodes for VF-PF communication
.IP "v_retval" 12
return error code
.IP "msg" 12
pointer to the msg buffer
.IP "msglen" 12
msg length
.IP "cd" 12
pointer to command details
.SH "DESCRIPTION"
Send message to VF driver (0x0802) using mailbox
queue and asynchronously sending message via
\fBice_sq_send_cmd\fP function
