.TH "ice_write_rxq_ctx" 9 "ice_write_rxq_ctx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_write_rxq_ctx \- 
.SH SYNOPSIS
.B "enum ice_status" ice_write_rxq_ctx
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_rlan_ctx *rlan_ctx "  ","
.BI "u32 rxq_index "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.IP "rlan_ctx" 12
pointer to the rxq context
.IP "rxq_index" 12
the index of the Rx queue
.SH "DESCRIPTION"
Converts rxq context from sparse to dense structure and then writes
it to HW register space and enables the hardware to prefetch descriptors
instead of only fetching them on demand
