.TH "ice_get_inactive_orom_ver" 9 "ice_get_inactive_orom_ver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_get_inactive_orom_ver \- Read Option ROM version from the inactive bank
.SH SYNOPSIS
.B "enum ice_status" ice_get_inactive_orom_ver
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_orom_info *orom "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "orom" 12
storage for Option ROM version information
.SH "DESCRIPTION"
Reads the Option ROM version and security revision data for the inactive
section of flash. Used to access version data for a pending update that has
not yet been activated.
