.TH "ice_aq_erase_nvm" 9 "ice_aq_erase_nvm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_erase_nvm \- 
.SH SYNOPSIS
.B "enum ice_status" ice_aq_erase_nvm
.BI "(struct ice_hw *hw "  ","
.BI "u16 module_typeid "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "module_typeid" 12
module pointer location in words from the NVM beginning
.IP "cd" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Erase the NVM sector using the admin queue commands (0x0702)
