.TH "ice_set_vf_spoofchk" 9 "ice_set_vf_spoofchk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_set_vf_spoofchk \- 
.SH SYNOPSIS
.B "int" ice_set_vf_spoofchk
.BI "(struct net_device *netdev "  ","
.BI "int vf_id "  ","
.BI "bool ena "  ");"
.SH ARGUMENTS
.IP "netdev" 12
network interface device structure
.IP "vf_id" 12
VF identifier
.IP "ena" 12
flag to enable or disable feature
.SH "DESCRIPTION"
Enable or disable VF spoof checking
