.TH "ice_dcb_init_cfg" 9 "ice_dcb_init_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_dcb_init_cfg \- set the initial DCB config in SW
.SH SYNOPSIS
.B "int" ice_dcb_init_cfg
.BI "(struct ice_pf *pf "  ","
.BI "bool locked "  ");"
.SH ARGUMENTS
.IP "pf" 12
PF to apply config to
.IP "locked" 12
Is the RTNL held
