.TH "ice_aq_rl_profile" 9 "ice_aq_rl_profile" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_rl_profile \- performs a rate limiting task
.SH SYNOPSIS
.B "enum ice_status" ice_aq_rl_profile
.BI "(struct ice_hw *hw "  ","
.BI "enum ice_adminq_opc opcode "  ","
.BI "u16 num_profiles "  ","
.BI "struct ice_aqc_rl_profile_elem *buf "  ","
.BI "u16 buf_size "  ","
.BI "u16 *num_processed "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "opcode" 12
opcode for add, query, or remove profile(s)
.IP "num_profiles" 12
the number of profiles
.IP "buf" 12
pointer to buffer
.IP "buf_size" 12
buffer size in bytes
.IP "num_processed" 12
number of processed add or remove profile(s) to return
.IP "cd" 12
pointer to command details structure
.SH "DESCRIPTION"
RL profile function to add, query, or remove profile(s)
