.TH "ice_sched_get_free_vsi_parent" 9 "ice_sched_get_free_vsi_parent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_sched_get_free_vsi_parent \- Find a free parent node in aggregator subtree
.SH SYNOPSIS
.B "struct ice_sched_node *" ice_sched_get_free_vsi_parent
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_sched_node *node "  ","
.BI "u16 *num_nodes "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "node" 12
pointer to a child node
.IP "num_nodes" 12
num nodes count array
.SH "DESCRIPTION"
This function walks through the aggregator subtree to find a free parent
node
