.TH "ice_clear_pxe_mode" 9 "ice_clear_pxe_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_clear_pxe_mode \- clear pxe operations mode
.SH SYNOPSIS
.B "void" ice_clear_pxe_mode
.BI "(struct ice_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.SH "DESCRIPTION"
Make sure all PXE mode settings are cleared, including things
like descriptor fetch/write-back mode.
