.TH "ice_vf_init_vlan_stripping" 9 "ice_vf_init_vlan_stripping" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_vf_init_vlan_stripping \- enable/disable VLAN stripping on initialization
.SH SYNOPSIS
.B "int" ice_vf_init_vlan_stripping
.BI "(struct ice_vf *vf "  ");"
.SH ARGUMENTS
.IP "vf" 12
VF to enable/disable VLAN stripping for on initialization
.SH "DESCRIPTION"
If the VIRTCHNL_VF_OFFLOAD_VLAN flag is set enable VLAN stripping, else if
the flag is cleared then we want to disable stripping. For example, the flag
will be cleared when port VLANs are configured by the administrator before
passing the VF to the guest or if the AVF driver doesn't support VLAN
offloads.
