.TH "ide_hwif_setup_dma" 9 "ide_hwif_setup_dma" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ide_hwif_setup_dma \- configure DMA interface
.SH SYNOPSIS
.B "int" ide_hwif_setup_dma
.BI "(ide_hwif_t *hwif "  ","
.BI "const struct ide_port_info *d "  ");"
.SH ARGUMENTS
.IP "hwif" 12
IDE interface
.IP "d" 12
IDE port info

Set up the DMA base for the interface. Enable the master bits as
necessary and attempt to bring the device DMA into a ready to use
state
