.TH "idle_inject_set_latency" 9 "idle_inject_set_latency" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
idle_inject_set_latency \- set the maximum latency allowed
.SH SYNOPSIS
.B "void" idle_inject_set_latency
.BI "(struct idle_inject_device *ii_dev "  ","
.BI "unsigned int latency_us "  ");"
.SH ARGUMENTS
.IP "ii_dev" 12
-- undescribed --
.IP "latency_us" 12
set the latency requirement for the idle state
