.TH "ieee_fpe_handler" 9 "ieee_fpe_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ieee_fpe_handler \- Handle denormalized number exception
.SH SYNOPSIS
.B "int" ieee_fpe_handler
.BI "(struct pt_regs *regs "  ");"
.SH ARGUMENTS
.IP "regs" 12
Pointer to register structure

Returns 1 when it's handled (should not cause exception).
