.TH "igb_init_module" 9 "igb_init_module" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_init_module \- Driver Registration Routine
.SH SYNOPSIS
.B "int" igb_init_module
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

igb_init_module is the first routine called when the driver is
loaded. All it does is register with the PCI subsystem.
