.TH "igb_write_mbx_pf" 9 "igb_write_mbx_pf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_write_mbx_pf \- Places a message in the mailbox
.SH SYNOPSIS
.B "s32" igb_write_mbx_pf
.BI "(struct e1000_hw *hw "  ","
.BI "u32 *msg "  ","
.BI "u16 size "  ","
.BI "u16 vf_number "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "msg" 12
The message buffer
.IP "size" 12
Length of buffer
.IP "vf_number" 12
the VF index

returns SUCCESS if it successfully copied message into the buffer
