.TH "igb_reset_mdicnfg_82580" 9 "igb_reset_mdicnfg_82580" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_reset_mdicnfg_82580 \- Reset MDICNFG destination and com_mdio bits
.SH SYNOPSIS
.B "s32" igb_reset_mdicnfg_82580
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure

This resets the the MDICNFG.Destination and MDICNFG.Com_MDIO bits based on
the values found in the EEPROM.  This addresses an issue in which these
bits are not restored from EEPROM after reset.
