.TH "igb_init_thermal_sensor_thresh_generic" 9 "igb_init_thermal_sensor_thresh_generic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_init_thermal_sensor_thresh_generic \- Sets thermal sensor thresholds
.SH SYNOPSIS
.B "s32" igb_init_thermal_sensor_thresh_generic
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure

Sets the thermal sensor thresholds according to the NVM map
and save off the threshold and location values into mac.thermal_sensor_data
