.TH "igb_config_collision_dist" 9 "igb_config_collision_dist" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_config_collision_dist \- Configure collision distance
.SH SYNOPSIS
.B "void" igb_config_collision_dist
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure

Configures the collision distance to the default value and is used
during link setup. Currently no func pointer exists and all
implementations are handled in the generic version of this function.
