.TH "igb_set_rx_mode" 9 "igb_set_rx_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_set_rx_mode \- Secondary Unicast, Multicast and Promiscuous mode set
.SH SYNOPSIS
.B "void" igb_set_rx_mode
.BI "(struct net_device *netdev "  ");"
.SH ARGUMENTS
.IP "netdev" 12
network interface device structure

The set_rx_mode entry point is called whenever the unicast or multicast
address lists or the network interface flags are updated.  This routine is
responsible for configuring the hardware for proper unicast, multicast,
promiscuous mode, and all-multi behavior.
