.TH "igb_release_nvm_i210" 9 "igb_release_nvm_i210" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_release_nvm_i210 \- Release exclusive access to EEPROM
.SH SYNOPSIS
.B "void" igb_release_nvm_i210
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure

Stop any current commands to the EEPROM and clear the EEPROM request bit,
then release the semaphores acquired.
