.TH "igbvf_configure_msix" 9 "igbvf_configure_msix" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igbvf_configure_msix \- Configure MSI-X hardware
.SH SYNOPSIS
.B "void" igbvf_configure_msix
.BI "(struct igbvf_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure
.SH "DESCRIPTION"
igbvf_configure_msix sets up the hardware to properly
generate MSI-X interrupts.
