.TH "igbvf_clean_tx_irq" 9 "igbvf_clean_tx_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igbvf_clean_tx_irq \- Reclaim resources after transmit completes
.SH SYNOPSIS
.B "bool" igbvf_clean_tx_irq
.BI "(struct igbvf_ring *tx_ring "  ");"
.SH ARGUMENTS
.IP "tx_ring" 12
ring structure to clean descriptors from
.SH "DESCRIPTION"
returns true if ring is completely cleaned
