.TH "igc_init_rx_addrs" 9 "igc_init_rx_addrs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igc_init_rx_addrs \- Initialize receive addresses
.SH SYNOPSIS
.B "void" igc_init_rx_addrs
.BI "(struct igc_hw *hw "  ","
.BI "u16 rar_count "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "rar_count" 12
receive address registers
.SH "DESCRIPTION"
Setup the receive address registers by setting the base receive address
register to the devices MAC address and clearing all the other receive
address registers to 0.
