.TH "igc_clear_hw_cntrs_base" 9 "igc_clear_hw_cntrs_base" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igc_clear_hw_cntrs_base \- Clear base hardware counters
.SH SYNOPSIS
.B "void" igc_clear_hw_cntrs_base
.BI "(struct igc_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.SH "DESCRIPTION"
Clears the base hardware counters by reading the counter registers.
