.TH "iio_dmaengine_buffer_free" 9 "iio_dmaengine_buffer_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iio_dmaengine_buffer_free \- Free dmaengine buffer
.SH SYNOPSIS
.B "void" iio_dmaengine_buffer_free
.BI "(struct iio_buffer *buffer "  ");"
.SH ARGUMENTS
.IP "buffer" 12
Buffer to free
.SH "DESCRIPTION"
Frees a buffer previously allocated with \fBiio_dmaengine_buffer_alloc\fP.
