.TH "iio_device_attach_buffer" 9 "iio_device_attach_buffer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iio_device_attach_buffer \- Attach a buffer to a IIO device
.SH SYNOPSIS
.B "void" iio_device_attach_buffer
.BI "(struct iio_dev *indio_dev "  ","
.BI "struct iio_buffer *buffer "  ");"
.SH ARGUMENTS
.IP "indio_dev" 12
The device the buffer should be attached to
.IP "buffer" 12
The buffer to attach to the device
.SH "DESCRIPTION"
This function attaches a buffer to a IIO device. The buffer stays attached to
the device until the device is freed. The function should only be called at
most once per device.
