.TH "iio_dma_buffer_request_update" 9 "iio_dma_buffer_request_update" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iio_dma_buffer_request_update \- DMA buffer request_update callback
.SH SYNOPSIS
.B "int" iio_dma_buffer_request_update
.BI "(struct iio_buffer *buffer "  ");"
.SH ARGUMENTS
.IP "buffer" 12
The buffer which to request an update
.SH "DESCRIPTION"
Should be used as the \fBiio_dma_buffer_request_update\fP callback for
iio_buffer_access_ops struct for DMA buffers.
