.TH "iio_dummy_init_device" 9 "iio_dummy_init_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iio_dummy_init_device \- device instance specific init
.SH SYNOPSIS
.B "int" iio_dummy_init_device
.BI "(struct iio_dev *indio_dev "  ");"
.SH ARGUMENTS
.IP "indio_dev" 12
the iio device structure
.SH "DESCRIPTION"
Most drivers have one of these to set up default values,
reset the device to known state etc.
