.TH "iio_simple_dummy_events_register" 9 "iio_simple_dummy_events_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iio_simple_dummy_events_register \- setup interrupt handling for events
.SH SYNOPSIS
.B "int" iio_simple_dummy_events_register
.BI "(struct iio_dev *indio_dev "  ");"
.SH ARGUMENTS
.IP "indio_dev" 12
device instance data
.SH "DESCRIPTION"
This function requests the threaded interrupt to handle the events.
Normally the irq is a hardware interrupt and the number comes
from board configuration files.  Here we get it from a companion
module that fakes the interrupt for us. Note that module in
no way forms part of this example. Just assume that events magically
appear via the provided interrupt.
