.TH "iio_event_poll" 9 "iio_event_poll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iio_event_poll \- poll the event queue to find out if it has data
.SH SYNOPSIS
.B "__poll_t" iio_event_poll
.BI "(struct file *filep "  ","
.BI "struct poll_table_struct *wait "  ");"
.SH ARGUMENTS
.IP "filep" 12
File structure pointer to identify the device
.IP "wait" 12
Poll table pointer to add the wait queue on
.SH "RETURN"
(EPOLLIN | EPOLLRDNORM) if data is available for reading
or a negative error code on failure
