.TH "ima_post_key_create_or_update" 9 "ima_post_key_create_or_update" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ima_post_key_create_or_update \- measure asymmetric keys
.SH SYNOPSIS
.B "void" ima_post_key_create_or_update
.BI "(struct key *keyring "  ","
.BI "struct key *key "  ","
.BI "const void *payload "  ","
.BI "size_t payload_len "  ","
.BI "unsigned long flags "  ","
.BI "bool create "  ");"
.SH ARGUMENTS
.IP "keyring" 12
keyring to which the key is linked to
.IP "key" 12
created or updated key
.IP "payload" 12
The data used to instantiate or update the key.
.IP "payload_len" 12
The length of \fIpayload\fP.
.IP "flags" 12
key flags
.IP "create" 12
flag indicating whether the key was created or updated
.SH "DESCRIPTION"
Keys can only be measured, not appraised.
The payload data used to instantiate or update the key is measured.
