.TH "img_ir_write_timings" 9 "img_ir_write_timings" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
img_ir_write_timings \- Write timings to the hardware now
.SH SYNOPSIS
.B "void" img_ir_write_timings
.BI "(struct img_ir_priv *priv "  ","
.BI "struct img_ir_timing_regvals *regs "  ","
.BI "enum rc_filter_type type "  ");"
.SH ARGUMENTS
.IP "priv" 12
IR private data
.IP "regs" 12
Timing register values to write
.IP "type" 12
RC filter type (RC_FILTER_*)
.SH "DESCRIPTION"
Write timing register values \fIregs\fP to the hardware, taking into account the
current filter which may impose restrictions on the length of the expected
data.
