.TH "imgu_mmu_map" 9 "imgu_mmu_map" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
imgu_mmu_map \- map a buffer to a physical address
.SH SYNOPSIS
.B "int" imgu_mmu_map
.BI "(struct imgu_mmu_info *info "  ","
.BI "unsigned long iova "  ","
.BI "phys_addr_t paddr "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "info" 12
MMU mappable range
.IP "iova" 12
the virtual address
.IP "paddr" 12
the physical address
.IP "size" 12
length of the mappable area
.SH "DESCRIPTION"
The function has been adapted from \fBiommu_map\fP in
drivers/iommu/iommu.c .
