.TH "inia100_scb_handler" 9 "inia100_scb_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
inia100_scb_handler \- interrupt callback
.SH SYNOPSIS
.B "void" inia100_scb_handler
.BI "(struct orc_host *host "  ","
.BI "struct orc_scb *scb "  ");"
.SH ARGUMENTS
.IP "host" 12
Host causing the interrupt
.IP "scb" 12
SCB the controller returned as needing processing

Perform completion processing on a control block. Do the conversions
from host to SCSI midlayer error coding, save any sense data and
the complete with the midlayer and recycle the scb.
