.TH "init_context" 9 "init_context" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
init_context \- initializes a previously allocated context
.SH SYNOPSIS
.B "void" init_context
.BI "(struct ctx_info *ctxi "  ","
.BI "struct cxlflash_cfg *cfg "  ","
.BI "void *ctx "  ","
.BI "int ctxid "  ","
.BI "struct file *file "  ","
.BI "u32 perms "  ","
.BI "u64 irqs "  ");"
.SH ARGUMENTS
.IP "ctxi" 12
Previously allocated context
.IP "cfg" 12
Internal structure associated with the host.
.IP "ctx" 12
Previously obtained context cookie.
.IP "ctxid" 12
Previously obtained process element associated with CXL context.
.IP "file" 12
Previously obtained file associated with CXL context.
.IP "perms" 12
User-specified permissions.
.IP "irqs" 12
User-specified number of interrupts.
