.TH "init_link_config" 9 "init_link_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
init_link_config \- initialize a link's SW state
.SH SYNOPSIS
.B "void" init_link_config
.BI "(struct link_config *lc "  ","
.BI "fw_port_cap32_t pcaps "  ","
.BI "fw_port_cap32_t acaps "  ");"
.SH ARGUMENTS
.IP "lc" 12
pointer to structure holding the link state
.IP "pcaps" 12
link Port Capabilities
.IP "acaps" 12
link current Advertised Port Capabilities

Initializes the SW state maintained for each link, including the link's
capabilities and default speed/flow-control/autonegotiation settings.
