.TH "init_display" 9 "init_display" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
init_display \- initialize the display controller
.SH SYNOPSIS
.B "int" init_display
.BI "(struct fbtft_par *par "  ");"
.SH ARGUMENTS
.IP "par" 12
FBTFT parameter object
.SH "DESCRIPTION"
Most of the commands in this init function set their parameters to the
same default values which are already in place after the display has been
powered up. (The main exception to this rule is the pixel format which
would default to 18 instead of 16 bit per pixel.)
Nonetheless, this sequence can be used as a template for concrete
displays which usually need some adjustments.
.SH "RETURN"
0 on success, < 0 if error occurred.
