.TH "input_register_handle" 9 "input_register_handle" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
input_register_handle \- register a new input handle
.SH SYNOPSIS
.B "int" input_register_handle
.BI "(struct input_handle *handle "  ");"
.SH ARGUMENTS
.IP "handle" 12
handle to register
.SH "DESCRIPTION"
This function puts a new input handle onto device's
and handler's lists so that events can flow through
it once it is opened using \fBinput_open_device\fP.

This function is supposed to be called from handler's
\fBconnect\fP method.
