.TH "input_free_device" 9 "input_free_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
input_free_device \- free memory occupied by input_dev structure
.SH SYNOPSIS
.B "void" input_free_device
.BI "(struct input_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
input device to free
.SH "DESCRIPTION"
This function should only be used if \fBinput_register_device\fP
was not called yet or if it failed. Once device was registered
use \fBinput_unregister_device\fP and memory will be freed once last
reference to the device is dropped.

Device should be allocated by \fBinput_allocate_device\fP.
.SH "NOTE"
If there are references to the input device then memory
will not be freed until last reference is dropped.
