.TH "input_release_device" 9 "input_release_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
input_release_device \- release previously grabbed device
.SH SYNOPSIS
.B "void" input_release_device
.BI "(struct input_handle *handle "  ");"
.SH ARGUMENTS
.IP "handle" 12
input handle that owns the device
.SH "DESCRIPTION"
Releases previously grabbed device so that other input handles can
start receiving input events. Upon release all handlers attached
to the device have their \fBstart\fP method called so they have a change
to synchronize device state with the rest of the system.
