.TH "input_mt_sync_frame" 9 "input_mt_sync_frame" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
input_mt_sync_frame \- synchronize mt frame
.SH SYNOPSIS
.B "void" input_mt_sync_frame
.BI "(struct input_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
input device with allocated MT slots
.SH "DESCRIPTION"
Close the frame and prepare the internal state for a new one.
Depending on the flags, marks unused slots as inactive and performs
pointer emulation.
