.TH "input_set_timestamp" 9 "input_set_timestamp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
input_set_timestamp \- set timestamp for input events
.SH SYNOPSIS
.B "void" input_set_timestamp
.BI "(struct input_dev *dev "  ","
.BI "ktime_t timestamp "  ");"
.SH ARGUMENTS
.IP "dev" 12
input device to set timestamp for
.IP "timestamp" 12
the time at which the event has occurred
in CLOCK_MONOTONIC
.SH "DESCRIPTION"
This function is intended to provide to the input system a more
accurate time of when an event actually occurred. The driver should
call this function as soon as a timestamp is acquired ensuring
clock conversions in input_set_timestamp are done correctly.

The system entering suspend state between timestamp acquisition and
calling input_set_timestamp can result in inaccurate conversions.
