.TH "insn_decode" 9 "insn_decode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
insn_decode \- Decode an instruction
.SH SYNOPSIS
.B "bool" insn_decode
.BI "(struct insn *insn "  ","
.BI "struct pt_regs *regs "  ","
.BI "unsigned char buf[MAX_INSN_SIZE] "  ","
.BI "int buf_size "  ");"
.SH ARGUMENTS
.IP "insn" 12
Structure to store decoded instruction
.IP "regs" 12
Structure with register values as seen when entering kernel mode
.IP "buf" 12
Buffer containing the instruction bytes
.IP "buf_size" 12
Number of instruction bytes available in buf
.SH "DESCRIPTION"
Decodes the instruction provided in buf and stores the decoding results in
insn. Also determines the correct address and operand sizes.

True if instruction was decoded, False otherwise.
.SH "RETURN"
