.TH "intel_vgpu_reg_imr_handler" 9 "intel_vgpu_reg_imr_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_vgpu_reg_imr_handler \- Generic IMR register emulation write handler
.SH SYNOPSIS
.B "int" intel_vgpu_reg_imr_handler
.BI "(struct intel_vgpu *vgpu "  ","
.BI "unsigned int reg "  ","
.BI "void *p_data "  ","
.BI "unsigned int bytes "  ");"
.SH ARGUMENTS
.IP "vgpu" 12
a vGPU
.IP "reg" 12
register offset written by guest
.IP "p_data" 12
register data written by guest
.IP "bytes" 12
register data length
.SH "DESCRIPTION"
This function is used to emulate the generic IMR register bit change
behavior.
.SH "RETURN"
Zero on success, negative error code if failed.
