.TH "intel_vgpu_get_ppgtt_mm" 9 "intel_vgpu_get_ppgtt_mm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_vgpu_get_ppgtt_mm \- get or create a PPGTT mm object.
.SH SYNOPSIS
.B "struct intel_vgpu_mm *" intel_vgpu_get_ppgtt_mm
.BI "(struct intel_vgpu *vgpu "  ","
.BI "enum intel_gvt_gtt_type root_entry_type "  ","
.BI "u64 pdps[] "  ");"
.SH ARGUMENTS
.IP "vgpu" 12
a vGPU
.IP "root_entry_type" 12
ppgtt root entry type
.IP "pdps" 12
guest pdps
.SH "DESCRIPTION"
This function is used to find or create a PPGTT mm object from a guest.
.SH "RETURN"
Zero on success, negative error code if failed.
