.TH "intel_plane_destroy" 9 "intel_plane_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_plane_destroy \- destroy a plane
.SH SYNOPSIS
.B "void" intel_plane_destroy
.BI "(struct drm_plane *plane "  ");"
.SH ARGUMENTS
.IP "plane" 12
plane to destroy
.SH "DESCRIPTION"
Common destruction function for all types of planes (primary, cursor,
sprite).
