.TH "intel_device_info_runtime_init" 9 "intel_device_info_runtime_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_device_info_runtime_init \- initialize runtime info
.SH SYNOPSIS
.B "void" intel_device_info_runtime_init
.BI "(struct drm_i915_private *dev_priv "  ");"
.SH ARGUMENTS
.IP "dev_priv" 12
the i915 device
.SH "DESCRIPTION"
Determine various intel_device_info fields at runtime.

Use it when either:
- it's judged too laborious to fill n static structures with the limit
when a simple if statement does the job,
- run-time checks (eg read fuse/strap registers) are needed.

This function needs to be called:
- after the MMIO has been setup as we are reading registers,
- after the PCH has been detected,
- before the first usage of the fields it can tweak.
