.TH "intel_irq_fini" 9 "intel_irq_fini" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_irq_fini \- deinitializes IRQ support
.SH SYNOPSIS
.B "void" intel_irq_fini
.BI "(struct drm_i915_private *i915 "  ");"
.SH ARGUMENTS
.IP "i915" 12
i915 device instance
.SH "DESCRIPTION"
This function deinitializes all the IRQ support.
