.TH "intel_th_gth_enable" 9 "intel_th_gth_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_th_gth_enable \- enable tracing to an output device
.SH SYNOPSIS
.B "void" intel_th_gth_enable
.BI "(struct intel_th_device *thdev "  ","
.BI "struct intel_th_output *output "  ");"
.SH ARGUMENTS
.IP "thdev" 12
GTH device
.IP "output" 12
output device's descriptor
.SH "DESCRIPTION"
This will configure all masters set to output to this device and
enable tracing using force storeEn signal.
