.TH "intel_vgpu_page_track_handler" 9 "intel_vgpu_page_track_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_vgpu_page_track_handler \- called when write to write-protected page
.SH SYNOPSIS
.B "int" intel_vgpu_page_track_handler
.BI "(struct intel_vgpu *vgpu "  ","
.BI "u64 gpa "  ","
.BI "void *data "  ","
.BI "unsigned int bytes "  ");"
.SH ARGUMENTS
.IP "vgpu" 12
a vGPU
.IP "gpa" 12
the gpa of this write
.IP "data" 12
the writed data
.IP "bytes" 12
the length of this write
.SH "RETURN"
zero on success, negative error code if failed.
