.TH "intel_gvt_render_mmio_to_engine" 9 "intel_gvt_render_mmio_to_engine" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_gvt_render_mmio_to_engine \- convert a mmio offset into the engine
.SH SYNOPSIS
.B "const struct intel_engine_cs *" intel_gvt_render_mmio_to_engine
.BI "(struct intel_gvt *gvt "  ","
.BI "unsigned int offset "  ");"
.SH ARGUMENTS
.IP "gvt" 12
a GVT device
.IP "offset" 12
register offset
.SH "RETURN"
The engine containing the offset within its mmio page.
