.TH "intel_vgt_deballoon" 9 "intel_vgt_deballoon" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_vgt_deballoon \- deballoon reserved graphics address trunks
.SH SYNOPSIS
.B "void" intel_vgt_deballoon
.BI "(struct i915_ggtt *ggtt "  ");"
.SH ARGUMENTS
.IP "ggtt" 12
the global GGTT from which we reserved earlier
.SH "DESCRIPTION"
This function is called to deallocate the ballooned-out graphic memory, when
driver is unloaded or when ballooning fails.
