.TH "intel_gpio_to_pin" 9 "intel_gpio_to_pin" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_gpio_to_pin \- Translate from GPIO offset to pin number
.SH SYNOPSIS
.B "int" intel_gpio_to_pin
.BI "(struct intel_pinctrl *pctrl "  ","
.BI "unsigned int offset "  ","
.BI "const struct intel_community **community "  ","
.BI "const struct intel_padgroup **padgrp "  ");"
.SH ARGUMENTS
.IP "pctrl" 12
Pinctrl structure
.IP "offset" 12
GPIO offset from gpiolib
.IP "community" 12
Community is filled here if not NULL
.IP "padgrp" 12
Pad group is filled here if not NULL
.SH "DESCRIPTION"
When coming through gpiolib irqchip, the GPIO offset is not
automatically translated to pinctrl pin number. This function can be
used to find out the corresponding pinctrl pin.
