.TH "intel_crtc_duplicate_state" 9 "intel_crtc_duplicate_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_crtc_duplicate_state \- duplicate crtc state
.SH SYNOPSIS
.B "struct drm_crtc_state *" intel_crtc_duplicate_state
.BI "(struct drm_crtc *crtc "  ");"
.SH ARGUMENTS
.IP "crtc" 12
drm crtc
.SH "DESCRIPTION"
Allocates and returns a copy of the crtc state (both common and
Intel-specific) for the specified crtc.
.SH "RETURN"
The newly allocated crtc state, or NULL on failure.
