.TH "ioat_dma_self_test" 9 "ioat_dma_self_test" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ioat_dma_self_test \- Perform a IOAT transaction to verify the HW works.
.SH SYNOPSIS
.B "int" ioat_dma_self_test
.BI "(struct ioatdma_device *ioat_dma "  ");"
.SH ARGUMENTS
.IP "ioat_dma" 12
dma device to be tested
