.TH "iommu_group_remove_device" 9 "iommu_group_remove_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iommu_group_remove_device \- remove a device from it's current group
.SH SYNOPSIS
.B "void" iommu_group_remove_device
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device to be removed
.SH "DESCRIPTION"
This function is called by an iommu driver to remove the device from
it's current group.  This decrements the iommu group reference count.
