.TH "iop_adma_free_slots" 9 "iop_adma_free_slots" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iop_adma_free_slots \- flags descriptor slots for reuse
.SH SYNOPSIS
.B "void" iop_adma_free_slots
.BI "(struct iop_adma_desc_slot *slot "  ");"
.SH ARGUMENTS
.IP "slot" 12
Slot to free
Caller must hold \fIiop_chan->lock\fP while calling this function
