.TH "iopgtable_lookup_entry" 9 "iopgtable_lookup_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iopgtable_lookup_entry \- Lookup an iommu pte entry
.SH SYNOPSIS
.B "void" iopgtable_lookup_entry
.BI "(struct omap_iommu *obj "  ","
.BI "u32 da "  ","
.BI "u32 **ppgd "  ","
.BI "u32 **ppte "  ");"
.SH ARGUMENTS
.IP "obj" 12
target iommu
.IP "da" 12
iommu device virtual address
.IP "ppgd" 12
iommu pgd entry pointer to be returned
.IP "ppte" 12
iommu pte entry pointer to be returned
