.TH "iort_deregister_domain_token" 9 "iort_deregister_domain_token" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iort_deregister_domain_token \- Deregister domain token based on ITS ID
.SH SYNOPSIS
.B "void" iort_deregister_domain_token
.BI "(int trans_id "  ");"
.SH ARGUMENTS
.IP "trans_id" 12
ITS ID.
.SH "RETURN"
none.
