.TH "ip6_tnl_dev_setup" 9 "ip6_tnl_dev_setup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ip6_tnl_dev_setup \- setup virtual tunnel device
.SH SYNOPSIS
.B "void" ip6_tnl_dev_setup
.BI "(struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
virtual device associated with tunnel
.SH "DESCRIPTION"
Initialize function pointers and device parameters
