.TH "ipc_parse_version" 9 "ipc_parse_version" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipc_parse_version \- ipc call version
.SH SYNOPSIS
.B "int" ipc_parse_version
.BI "(int *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
pointer to command
.SH "DESCRIPTION"
Return IPC_64 for new style IPC and IPC_OLD for old style IPC.
The \fIcmd\fP value is turned from an encoding command and version into
just the command code.
