.TH "ipr_check_term_power" 9 "ipr_check_term_power" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_check_term_power \- Check for term power errors
.SH SYNOPSIS
.B "void" ipr_check_term_power
.BI "(struct ipr_ioa_cfg *ioa_cfg "  ","
.BI "struct ipr_mode_pages *mode_pages "  ");"
.SH ARGUMENTS
.IP "ioa_cfg" 12
ioa config struct
.IP "mode_pages" 12
IOAFP mode pages buffer
.SH "DESCRIPTION"
Check the IOAFP's mode page 28 for term power errors

Return value:
nothing
