.TH "ipr_find_ses_entry" 9 "ipr_find_ses_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_find_ses_entry \- Find matching SES in SES table
.SH SYNOPSIS
.B "const struct ipr_ses_table_entry *" ipr_find_ses_entry
.BI "(struct ipr_resource_entry *res "  ");"
.SH ARGUMENTS
.IP "res" 12
resource entry struct of SES
.SH "DESCRIPTION"
Return value:
pointer to SES table entry / NULL on failure
