.TH "ipr_build_mode_select" 9 "ipr_build_mode_select" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_build_mode_select \- Build a mode select command
.SH SYNOPSIS
.B "void" ipr_build_mode_select
.BI "(struct ipr_cmnd *ipr_cmd "  ","
.BI "__be32 res_handle "  ","
.BI "u8 parm "  ","
.BI "dma_addr_t dma_addr "  ","
.BI "u8 xfer_len "  ");"
.SH ARGUMENTS
.IP "ipr_cmd" 12
ipr command struct
.IP "res_handle" 12
resource handle to send command to
.IP "parm" 12
Byte 2 of Mode Sense command
.IP "dma_addr" 12
DMA buffer address
.IP "xfer_len" 12
data transfer length
.SH "DESCRIPTION"
Return value:
none
