.TH "ipr_probe_ioa_part2" 9 "ipr_probe_ioa_part2" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_probe_ioa_part2 \- Initializes IOAs found in ipr_probe_ioa(..)
.SH SYNOPSIS
.B "int" ipr_probe_ioa_part2
.BI "(struct ipr_ioa_cfg *ioa_cfg "  ");"
.SH ARGUMENTS
.IP "ioa_cfg" 12
ioa cfg struct
.SH "DESCRIPTION"
This is the second phase of adapter initialization
This function takes care of initilizing the adapter to the point
where it can accept new commands.
Return value:
0 on success / -EIO on failure
