.TH "ipr_build_ucode_ioadl" 9 "ipr_build_ucode_ioadl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_build_ucode_ioadl \- Build a microcode download IOADL
.SH SYNOPSIS
.B "void" ipr_build_ucode_ioadl
.BI "(struct ipr_cmnd *ipr_cmd "  ","
.BI "struct ipr_sglist *sglist "  ");"
.SH ARGUMENTS
.IP "ipr_cmd" 12
ipr command struct
.IP "sglist" 12
scatter/gather list
.SH "DESCRIPTION"
Builds a microcode download IOA data list (IOADL).
