.TH "ipr_show_adapter_state" 9 "ipr_show_adapter_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_show_adapter_state \- Show the adapter's state
.SH SYNOPSIS
.B "ssize_t" ipr_show_adapter_state
.BI "(struct device *dev "  ","
.BI "struct device_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "dev" 12
device struct
.IP "attr" 12
device attribute (unused)
.IP "buf" 12
buffer
.SH "DESCRIPTION"
Return value:
number of bytes printed to buffer
