.TH "ipr_ioafp_page3_inquiry" 9 "ipr_ioafp_page3_inquiry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_ioafp_page3_inquiry \- Send a Page 3 Inquiry to the adapter.
.SH SYNOPSIS
.B "int" ipr_ioafp_page3_inquiry
.BI "(struct ipr_cmnd *ipr_cmd "  ");"
.SH ARGUMENTS
.IP "ipr_cmd" 12
ipr command struct
.SH "DESCRIPTION"
This function sends a Page 3 inquiry to the adapter
to retrieve software VPD information.

Return value:
IPR_RC_JOB_CONTINUE / IPR_RC_JOB_RETURN
