.TH "ipr_reset_get_unit_check_job" 9 "ipr_reset_get_unit_check_job" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_reset_get_unit_check_job \- Call to get the unit check buffer.
.SH SYNOPSIS
.B "int" ipr_reset_get_unit_check_job
.BI "(struct ipr_cmnd *ipr_cmd "  ");"
.SH ARGUMENTS
.IP "ipr_cmd" 12
ipr command struct
.SH "DESCRIPTION"
This function will call to get the unit check buffer.

Return value:
IPR_RC_JOB_RETURN
