.TH "ipr_set_sup_dev_dflt" 9 "ipr_set_sup_dev_dflt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_set_sup_dev_dflt \- Initialize a Set Supported Device buffer
.SH SYNOPSIS
.B "void" ipr_set_sup_dev_dflt
.BI "(struct ipr_supported_device *supported_dev "  ","
.BI "struct ipr_std_inq_vpids *vpids "  ");"
.SH ARGUMENTS
.IP "supported_dev" 12
supported device struct
.IP "vpids" 12
vendor product id struct
.SH "DESCRIPTION"
Return value:
none
