.TH "ipr_sdt_copy" 9 "ipr_sdt_copy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_sdt_copy \- Copy Smart Dump Table to kernel buffer
.SH SYNOPSIS
.B "int" ipr_sdt_copy
.BI "(struct ipr_ioa_cfg *ioa_cfg "  ","
.BI "unsigned long pci_address "  ","
.BI "u32 length "  ");"
.SH ARGUMENTS
.IP "ioa_cfg" 12
ioa config struct
.IP "pci_address" 12
adapter address
.IP "length" 12
length of data to copy
.SH "DESCRIPTION"
Copy data from PCI adapter to kernel buffer.
.SH "NOTE"
length MUST be a 4 byte multiple
Return value:
0 on success / other on failure
