.TH "ips_gpu_busy" 9 "ips_gpu_busy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ips_gpu_busy \- is GPU busy?
.SH SYNOPSIS
.B "bool" ips_gpu_busy
.BI "(struct ips_driver *ips "  ");"
.SH ARGUMENTS
.IP "ips" 12
IPS driver struct
.SH "DESCRIPTION"
Check GPU for load to see whether we should increase its thermal budget.
We need to call into the i915 driver in this case.
.SH "RETURN"
True if the GPU could use more power, false otherwise.
