.TH "iptunnel_pmtud_build_icmp" 9 "iptunnel_pmtud_build_icmp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iptunnel_pmtud_build_icmp \- Build ICMP error message for PMTUD
.SH SYNOPSIS
.B "int" iptunnel_pmtud_build_icmp
.BI "(struct sk_buff *skb "  ","
.BI "int mtu "  ");"
.SH ARGUMENTS
.IP "skb" 12
Original packet with L2 header
.IP "mtu" 12
MTU value for ICMP error
.SH "RETURN"
length on success, negative error code if message couldn't be built.
