.TH "iptunnel_pmtud_check_icmpv6" 9 "iptunnel_pmtud_check_icmpv6" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iptunnel_pmtud_check_icmpv6 \- Trigger ICMPv6 reply if needed and allowed
.SH SYNOPSIS
.B "int" iptunnel_pmtud_check_icmpv6
.BI "(struct sk_buff *skb "  ","
.BI "int mtu "  ");"
.SH ARGUMENTS
.IP "skb" 12
Buffer being sent by encapsulation, L2 headers expected
.IP "mtu" 12
Network MTU for path
.SH "RETURN"
0 for no ICMPv6 reply, length if built, negative value on error.
