.TH "ipu_init_channel" 9 "ipu_init_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipu_init_channel \- initialize an IPU channel.
.SH SYNOPSIS
.B "int" ipu_init_channel
.BI "(struct idmac *idmac "  ","
.BI "struct idmac_channel *ichan "  ");"
.SH ARGUMENTS
.IP "idmac" 12
IPU DMAC context.
.IP "ichan" 12
pointer to the channel object.
\fIreturn\fP      0 on success or negative error code on failure.
