.TH "irq_reserve_ipi" 9 "irq_reserve_ipi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
irq_reserve_ipi \- Setup an IPI to destination cpumask
.SH SYNOPSIS
.B "int" irq_reserve_ipi
.BI "(struct irq_domain *domain "  ","
.BI "const struct cpumask *dest "  ");"
.SH ARGUMENTS
.IP "domain" 12
IPI domain
.IP "dest" 12
cpumask of cpus which can receive the IPI
.SH "DESCRIPTION"
Allocate a virq that can be used to send IPI to any CPU in dest mask.

On success it'll return linux irq number and error code on failure
