.TH "irqpoll_weight_store" 9 "irqpoll_weight_store" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
irqpoll_weight_store \- sets the current IRQ poll weight for the host
.SH SYNOPSIS
.B "ssize_t" irqpoll_weight_store
.BI "(struct device *dev "  ","
.BI "struct device_attribute *attr "  ","
.BI "const char *buf "  ","
.BI "size_t count "  ");"
.SH ARGUMENTS
.IP "dev" 12
Generic device associated with the host.
.IP "attr" 12
Device attribute representing the IRQ poll weight.
.IP "buf" 12
Buffer of length PAGE_SIZE containing the desired IRQ poll
weight in ASCII.
.IP "count" 12
Length of data resizing in \fIbuf\fP.
.SH "DESCRIPTION"
An IRQ poll weight of 0 indicates polling is disabled.
.SH "RETURN"
The size of the ASCII string returned in \fIbuf\fP.
