.TH "is_prime_number" 9 "is_prime_number" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
is_prime_number \- test whether the given number is prime
.SH SYNOPSIS
.B "bool" is_prime_number
.BI "(unsigned long x "  ");"
.SH ARGUMENTS
.IP "x" 12
the number to test
.SH "DESCRIPTION"
A prime number is an integer greater than 1 that is only divisible by
itself and 1. Internally a cache of prime numbers is kept (to speed up
searching for sequential primes, see \fBnext_prime_number\fP), but if the number
falls outside of that cache, its primality is tested using trial-divison.
.SH "RETURN"
true if \fIx\fP is prime, false for composite numbers.
