.TH "isapnp_remove_one" 9 "isapnp_remove_one" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
isapnp_remove_one \- unplug an isapnp interface
.SH SYNOPSIS
.B "void" isapnp_remove_one
.BI "(struct pnp_dev *idev "  ");"
.SH ARGUMENTS
.IP "idev" 12
PnP device

Remove a previously configured PnP ATA port. Called only on module
unload events as the core does not currently deal with ISAPnP docking.
