.TH "iscsi_session_event" 9 "iscsi_session_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iscsi_session_event \- send session destr. completion event
.SH SYNOPSIS
.B "int" iscsi_session_event
.BI "(struct iscsi_cls_session *session "  ","
.BI "enum iscsi_uevent_e event "  ");"
.SH ARGUMENTS
.IP "session" 12
iscsi class session
.IP "event" 12
type of event
