.TH "iscsi_prep_scsi_cmd_pdu" 9 "iscsi_prep_scsi_cmd_pdu" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iscsi_prep_scsi_cmd_pdu \- prep iscsi scsi cmd pdu
.SH SYNOPSIS
.B "int" iscsi_prep_scsi_cmd_pdu
.BI "(struct iscsi_task *task "  ");"
.SH ARGUMENTS
.IP "task" 12
iscsi task
.SH "DESCRIPTION"
Prep basic iSCSI PDU fields for a scsi cmd pdu. The LLD should set
fields like dlength or final based on how much data it sends
