.TH "iscsi_tcp_task_xmit" 9 "iscsi_tcp_task_xmit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iscsi_tcp_task_xmit \- xmit normal PDU task
.SH SYNOPSIS
.B "int" iscsi_tcp_task_xmit
.BI "(struct iscsi_task *task "  ");"
.SH ARGUMENTS
.IP "task" 12
iscsi command task
.SH "DESCRIPTION"
We're expected to return 0 when everything was transmitted successfully,
-EAGAIN if there's still data in the queue, or != 0 for any other kind
of error.
