.TH "iscsi_tcp_data_in" 9 "iscsi_tcp_data_in" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iscsi_tcp_data_in \- SCSI Data-In Response processing
.SH SYNOPSIS
.B "int" iscsi_tcp_data_in
.BI "(struct iscsi_conn *conn "  ","
.BI "struct iscsi_task *task "  ");"
.SH ARGUMENTS
.IP "conn" 12
iscsi connection
.IP "task" 12
scsi command task
