.TH "iscsi_destroy_all_flashnode" 9 "iscsi_destroy_all_flashnode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iscsi_destroy_all_flashnode \- destroy all flashnode session entries
.SH SYNOPSIS
.B "void" iscsi_destroy_all_flashnode
.BI "(struct Scsi_Host *shost "  ");"
.SH ARGUMENTS
.IP "shost" 12
pointer to host data
.SH "DESCRIPTION"
Destroys all the flashnode session entries and all corresponding children
flashnode connection entries from sysfs
