.TH "iscsi_unblock_session" 9 "iscsi_unblock_session" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iscsi_unblock_session \- set a session as logged in and start IO.
.SH SYNOPSIS
.B "void" iscsi_unblock_session
.BI "(struct iscsi_cls_session *session "  ");"
.SH ARGUMENTS
.IP "session" 12
iscsi session
.SH "DESCRIPTION"
Mark a session as ready to accept IO.
