.TH "iser_alloc_fastreg_pool" 9 "iser_alloc_fastreg_pool" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iser_alloc_fastreg_pool \- Creates pool of fast_reg descriptors for fast registration work requests.
.SH SYNOPSIS
.B "int" iser_alloc_fastreg_pool
.BI "(struct ib_conn *ib_conn "  ","
.BI "unsigned cmds_max "  ","
.BI "unsigned int size "  ");"
.SH ARGUMENTS
.IP "ib_conn" 12
connection RDMA resources
.IP "cmds_max" 12
max number of SCSI commands for this connection
.IP "size" 12
max number of pages per map request
.SH "RETURN"
0 on success, or errno code on failure
