.TH "iser_conn_terminate" 9 "iser_conn_terminate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iser_conn_terminate \- triggers start of the disconnect procedures and waits for them to be done
.SH SYNOPSIS
.B "int" iser_conn_terminate
.BI "(struct iser_conn *iser_conn "  ");"
.SH ARGUMENTS
.IP "iser_conn" 12
iSER connection context
.SH "DESCRIPTION"
Called with state mutex held
