.TH "ish_resume_handler" 9 "ish_resume_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ish_resume_handler \- Work function to complete resume
.SH SYNOPSIS
.B "void __maybe_unused" ish_resume_handler
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
work struct
.SH "DESCRIPTION"
The resume work function to complete resume function asynchronously.
There are two resume paths, one where ISH is not powered off,
in that case a simple resume message is enough, others we need
a reset sequence.
