.TH "ish_remove" 9 "ish_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ish_remove \- PCI driver remove callback
.SH SYNOPSIS
.B "void" ish_remove
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
pci device
.SH "DESCRIPTION"
This function does cleanup of ISH on pci remove callback
