.TH "ishtp_cl_init" 9 "ishtp_cl_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_cl_init \- Initialize all fields of a client device
.SH SYNOPSIS
.B "void" ishtp_cl_init
.BI "(struct ishtp_cl *cl "  ","
.BI "struct ishtp_device *dev "  ");"
.SH ARGUMENTS
.IP "cl" 12
ishtp client instance
.IP "dev" 12
ishtp device
.SH "DESCRIPTION"
Initializes a client device fields: Init spinlocks, init queues etc.
This function is called during new client creation
