.TH "ishtp_io_rb_free" 9 "ishtp_io_rb_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_io_rb_free \- Free IO request block
.SH SYNOPSIS
.B "void" ishtp_io_rb_free
.BI "(struct ishtp_cl_rb *rb "  ");"
.SH ARGUMENTS
.IP "rb" 12
IO request block
.SH "DESCRIPTION"
Free io request block memory
