.TH "ishtp_hid_probe" 9 "ishtp_hid_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_hid_probe \- hid register ll driver
.SH SYNOPSIS
.B "int" ishtp_hid_probe
.BI "(unsigned int cur_hid_dev "  ","
.BI "struct ishtp_cl_data *client_data "  ");"
.SH ARGUMENTS
.IP "cur_hid_dev" 12
Index of hid device calling to register
.IP "client_data" 12
Client data pointer
.SH "DESCRIPTION"
This function is used to allocate and add HID device.
.SH "RETURN"
0 on success, non zero on error
