.TH "ishtp_trace_callback" 9 "ishtp_trace_callback" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_trace_callback \- Return trace callback
.SH SYNOPSIS
.B "void *" ishtp_trace_callback
.BI "(struct ishtp_cl_device *cl_device "  ");"
.SH ARGUMENTS
.IP "cl_device" 12
-- undescribed --
.SH "DESCRIPTION"

This interface is used to return trace callback function pointer.
.SH "RETURN"
void *.
