.TH "isr_tr_complete_handler" 9 "isr_tr_complete_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
isr_tr_complete_handler \- transaction complete interrupt handler
.SH SYNOPSIS
.B "void" isr_tr_complete_handler
.BI "(struct ci_hdrc *ci "  ");"
.SH ARGUMENTS
.IP "ci" 12
UDC descriptor
.SH "DESCRIPTION"
This function handles traffic events
