.TH "isst_resume_common" 9 "isst_resume_common" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
isst_resume_common \- Process Resume request
.SH SYNOPSIS
.B "void" isst_resume_common
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

On resume replay all mailbox commands and MSRs.
.SH "RETURN"
None.
