.TH "iw_valid_channel" 9 "iw_valid_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iw_valid_channel \- validate channel in regulatory domain
.SH SYNOPSIS
.B "int" iw_valid_channel
.BI "(int reg_domain "  ","
.BI "int channel "  ");"
.SH ARGUMENTS
.IP "reg_domain" 12
regulatory domain
.IP "channel" 12
channel to validate
.SH "DESCRIPTION"
Returns 0 if invalid in the specified regulatory domain, non-zero if valid.
