.TH "iwpm_remote_info_cb" 9 "iwpm_remote_info_cb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iwpm_remote_info_cb \- Process remote connecting peer address info, which the port mapper has received from the connecting peer
.SH SYNOPSIS
.B "int" iwpm_remote_info_cb
.BI "(struct sk_buff *skb "  ","
.BI "struct netlink_callback *cb "  ");"
.SH ARGUMENTS
.IP "skb" 12
The socket buffer
.IP "cb" 12
Contains the received message (payload and netlink header)
.SH "DESCRIPTION"
Stores the IPv4/IPv6 address info in a hash table
