.TH "ixgbe_set_rar_generic" 9 "ixgbe_set_rar_generic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_set_rar_generic \- Set Rx address register
.SH SYNOPSIS
.B "s32" ixgbe_set_rar_generic
.BI "(struct ixgbe_hw *hw "  ","
.BI "u32 index "  ","
.BI "u8 *addr "  ","
.BI "u32 vmdq "  ","
.BI "u32 enable_addr "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
.IP "index" 12
Receive address register to write
.IP "addr" 12
Address to put into receive address register
.IP "vmdq" 12
VMDq "set" or "pool" index
.IP "enable_addr" 12
set flag that address is active

Puts an ethernet address into a receive address register.
