.TH "ixgbe_ptp_create_clock" 9 "ixgbe_ptp_create_clock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_ptp_create_clock \- 
.SH SYNOPSIS
.B "long" ixgbe_ptp_create_clock
.BI "(struct ixgbe_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
the ixgbe private adapter structure
.SH "DESCRIPTION"
This function performs setup of the user entry point function table and
initializes the PTP clock device, which is used to access the clock-like
features of the PTP core. It will be called by ixgbe_ptp_init, and may
reuse a previously initialized clock (such as during a suspend/resume
cycle).
