.TH "ixgbe_reset_hw_82598" 9 "ixgbe_reset_hw_82598" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_reset_hw_82598 \- Performs hardware reset
.SH SYNOPSIS
.B "s32" ixgbe_reset_hw_82598
.BI "(struct ixgbe_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure

Resets the hardware by resetting the transmit and receive units, masks and
clears all interrupts, performing a PHY reset, and performing a link (MAC)
reset.
