.TH "ixgbe_write_cs4227" 9 "ixgbe_write_cs4227" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_write_cs4227 \- Write CS4227 register
.SH SYNOPSIS
.B "s32" ixgbe_write_cs4227
.BI "(struct ixgbe_hw *hw "  ","
.BI "u16 reg "  ","
.BI "u16 value "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
.IP "reg" 12
register number to write
.IP "value" 12
value to write to register
.SH "DESCRIPTION"
Returns status code
