.TH "ixgbe_lpbthresh" 9 "ixgbe_lpbthresh" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_lpbthresh \- calculate low water mark for for flow control
.SH SYNOPSIS
.B "int" ixgbe_lpbthresh
.BI "(struct ixgbe_adapter *adapter "  ","
.BI "int pb "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure to calculate for
.IP "pb" 12
packet buffer to calculate
