.TH "ixgbevf_set_ivar" 9 "ixgbevf_set_ivar" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbevf_set_ivar \- set IVAR registers - maps interrupt causes to vectors
.SH SYNOPSIS
.B "void" ixgbevf_set_ivar
.BI "(struct ixgbevf_adapter *adapter "  ","
.BI "s8 direction "  ","
.BI "u8 queue "  ","
.BI "u8 msix_vector "  ");"
.SH ARGUMENTS
.IP "adapter" 12
pointer to adapter struct
.IP "direction" 12
0 for Rx, 1 for Tx, -1 for other causes
.IP "queue" 12
queue to map the corresponding interrupt to
.IP "msix_vector" 12
the vector to map to the corresponding queue
