.TH "ixgbe_ipsec_offload_ok" 9 "ixgbe_ipsec_offload_ok" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_ipsec_offload_ok \- can this packet use the xfrm hw offload
.SH SYNOPSIS
.B "bool" ixgbe_ipsec_offload_ok
.BI "(struct sk_buff *skb "  ","
.BI "struct xfrm_state *xs "  ");"
.SH ARGUMENTS
.IP "skb" 12
current data packet
.IP "xs" 12
pointer to transformer state struct
