.TH "ixgbe_fc_enable_generic" 9 "ixgbe_fc_enable_generic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_fc_enable_generic \- Enable flow control
.SH SYNOPSIS
.B "s32" ixgbe_fc_enable_generic
.BI "(struct ixgbe_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure

Enable flow control according to the current settings.
