.TH "jbd2_journal_clear_err" 9 "jbd2_journal_clear_err" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
jbd2_journal_clear_err \- clears the journal's error state
.SH SYNOPSIS
.B "int" jbd2_journal_clear_err
.BI "(journal_t *journal "  ");"
.SH ARGUMENTS
.IP "journal" 12
journal to act on.
.SH "DESCRIPTION"
An error must be cleared or acked to take a FS out of readonly
mode.
