.TH "jbd2_journal_load" 9 "jbd2_journal_load" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
jbd2_journal_load \- Read journal from disk.
.SH SYNOPSIS
.B "int" jbd2_journal_load
.BI "(journal_t *journal "  ");"
.SH ARGUMENTS
.IP "journal" 12
Journal to act on.
.SH "DESCRIPTION"
Given a journal_t structure which tells us which disk blocks contain
a journal, read the journal from disk to initialise the in-memory
structures.
