.TH "kbuffer_subbuffer_size" 9 "kbuffer_subbuffer_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kbuffer_subbuffer_size \- the size of the loaded subbuffer
.SH SYNOPSIS
.B "int" kbuffer_subbuffer_size
.BI "(struct kbuffer *kbuf "  ");"
.SH ARGUMENTS
.IP "kbuf" 12
The kbuffer to read from
.SH "DESCRIPTION"
Returns the size of the subbuffer. Note, this size is
where the last event resides. The stored subbuffer may actually be
bigger due to padding and such.
