.TH "kernfs_node_from_dentry" 9 "kernfs_node_from_dentry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kernfs_node_from_dentry \- determine kernfs_node associated with a dentry
.SH SYNOPSIS
.B "struct kernfs_node *" kernfs_node_from_dentry
.BI "(struct dentry *dentry "  ");"
.SH ARGUMENTS
.IP "dentry" 12
the dentry in question
.SH "DESCRIPTION"
Return the kernfs_node associated with \fIdentry\fP.  If \fIdentry\fP is not a
kernfs one, NULL is returned.

While the returned kernfs_node will stay accessible as long as \fIdentry\fP
is accessible, the returned node can be in any state and the caller is
fully responsible for determining what's accessible.
