.TH "kernel_bind" 9 "kernel_bind" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kernel_bind \- bind an address to a socket (kernel space)
.SH SYNOPSIS
.B "int" kernel_bind
.BI "(struct socket *sock "  ","
.BI "struct sockaddr *addr "  ","
.BI "int addrlen "  ");"
.SH ARGUMENTS
.IP "sock" 12
socket
.IP "addr" 12
address
.IP "addrlen" 12
length of address

Returns 0 or an error.
