.TH "kgdb_register_io_module" 9 "kgdb_register_io_module" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kgdb_register_io_module \- register KGDB IO module
.SH SYNOPSIS
.B "int" kgdb_register_io_module
.BI "(struct kgdb_io *new_dbg_io_ops "  ");"
.SH ARGUMENTS
.IP "new_dbg_io_ops" 12
the io ops vector

Register it with the KGDB core.
