.TH "kmem_cache_alloc" 9 "kmem_cache_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kmem_cache_alloc \- Allocate an object
.SH SYNOPSIS
.B "void *" kmem_cache_alloc
.BI "(struct kmem_cache *cachep "  ","
.BI "gfp_t flags "  ");"
.SH ARGUMENTS
.IP "cachep" 12
The cache to allocate from.
.IP "flags" 12
See \fBkmalloc\fP.
.SH "DESCRIPTION"
Allocate an object from this cache.  The flags are only relevant
if the cache has no available objects.
.SH "RETURN"
pointer to the new object or NULL in case of error
