.TH "knav_queue_push" 9 "knav_queue_push" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
knav_queue_push \- push data (or descriptor) to the tail of a queue
.SH SYNOPSIS
.B "int" knav_queue_push
.BI "(void *qhandle "  ","
.BI "dma_addr_t dma "  ","
.BI "unsigned size "  ","
.BI "unsigned flags "  ");"
.SH ARGUMENTS
.IP "qhandle" 12
- hardware queue handle
.IP "dma" 12
- DMA data to push
.IP "size" 12
- size of data to push
.IP "flags" 12
- can be used to pass additional information
.SH "DESCRIPTION"
Returns 0 on success, errno otherwise.
