.TH "ks_pcie_v3_65_add_bus" 9 "ks_pcie_v3_65_add_bus" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ks_pcie_v3_65_add_bus \- keystone add_bus post initialization
.SH SYNOPSIS
.B "int" ks_pcie_v3_65_add_bus
.BI "(struct pci_bus *bus "  ");"
.SH ARGUMENTS
.IP "bus" 12
-- undescribed --
.SH "DESCRIPTION"

This sets BAR0 to enable inbound access for MSI_IRQ register
