.TH "ksz_alloc_soft_desc" 9 "ksz_alloc_soft_desc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ksz_alloc_soft_desc \- allocate software descriptors
.SH SYNOPSIS
.B "int" ksz_alloc_soft_desc
.BI "(struct ksz_desc_info *desc_info "  ","
.BI "int transmit "  ");"
.SH ARGUMENTS
.IP "desc_info" 12
Descriptor information structure.
.IP "transmit" 12
Indication that descriptors are for transmit.
.SH "DESCRIPTION"
This local function allocates software descriptors for manipulation in
memory.

Return 0 if successful.
