.TH "ktime_get_raw_fast_ns" 9 "ktime_get_raw_fast_ns" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ktime_get_raw_fast_ns \- Fast NMI safe access to clock monotonic raw
.SH SYNOPSIS
.B "u64" ktime_get_raw_fast_ns
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Contrary to \fBktime_get_mono_fast_ns\fP this is always correct because the
conversion factor is not affected by NTP/PTP correction.
