.TH "ktime_mono_to_any" 9 "ktime_mono_to_any" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ktime_mono_to_any \- convert mononotic time to any other time
.SH SYNOPSIS
.B "ktime_t" ktime_mono_to_any
.BI "(ktime_t tmono "  ","
.BI "enum tk_offsets offs "  ");"
.SH ARGUMENTS
.IP "tmono" 12
time to convert.
.IP "offs" 12
which offset to use
