.TH "kvm_pmu_idx_is_high_counter" 9 "kvm_pmu_idx_is_high_counter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kvm_pmu_idx_is_high_counter \- determine if select_idx is a high/low counter
.SH SYNOPSIS
.B "bool" kvm_pmu_idx_is_high_counter
.BI "(u64 select_idx "  ");"
.SH ARGUMENTS
.IP "select_idx" 12
The counter index
