.TH "kvm_pmu_sync_hwstate" 9 "kvm_pmu_sync_hwstate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kvm_pmu_sync_hwstate \- sync pmu state from cpu
.SH SYNOPSIS
.B "void" kvm_pmu_sync_hwstate
.BI "(struct kvm_vcpu *vcpu "  ");"
.SH ARGUMENTS
.IP "vcpu" 12
The vcpu pointer
.SH "DESCRIPTION"
Check if the PMU has overflowed while we were running in the guest, and
inject an interrupt if that was the case.
