.TH "lbs_get_firmware_async" 9 "lbs_get_firmware_async" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lbs_get_firmware_async \- Retrieves firmware asynchronously. Can load either a helper firmware and a main firmware (2-stage), or just the helper.
.SH SYNOPSIS
.B "int" lbs_get_firmware_async
.BI "(struct lbs_private *priv "  ","
.BI "struct device *device "  ","
.BI "u32 card_model "  ","
.BI "const struct lbs_fw_table *fw_table "  ","
.BI "lbs_fw_cb callback "  ");"
.SH ARGUMENTS
.IP "priv" 12
Pointer to lbs_private instance
.IP "device" 12
A pointer to \fIdevice\fP structure
.IP "card_model" 12
Bus-specific card model ID used to filter firmware table
elements
.IP "fw_table" 12
Table of firmware file names and device model numbers
terminated by an entry with a NULL helper name
.IP "callback" 12
User callback to invoke when firmware load succeeds or fails.
