.TH "lbs_get_free_cmd_node" 9 "lbs_get_free_cmd_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lbs_get_free_cmd_node \- gets a free command node if available in command free queue
.SH SYNOPSIS
.B "struct cmd_ctrl_node *" lbs_get_free_cmd_node
.BI "(struct lbs_private *priv "  ");"
.SH ARGUMENTS
.IP "priv" 12
A pointer to \fIstruct lbs_private\fP structure
.SH "RETURN"
A pointer to \fIcmd_ctrl_node\fP structure on success
or NULL on error
