.TH "link_schedule_user" 9 "link_schedule_user" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
link_schedule_user \- schedule a message sender for wakeup after congestion
.SH SYNOPSIS
.B "int" link_schedule_user
.BI "(struct tipc_link *l "  ","
.BI "struct tipc_msg *hdr "  ");"
.SH ARGUMENTS
.IP "l" 12
congested link
.IP "hdr" 12
header of message that is being sent
Create pseudo msg to send back to user when congestion abates
