.TH "link_to_linux_err" 9 "link_to_linux_err" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
link_to_linux_err \- Translates an 802.15.4 return code into the closest linux error
.SH SYNOPSIS
.B "int" link_to_linux_err
.BI "(int link_status "  ");"
.SH ARGUMENTS
.IP "link_status" 12
802.15.4 status code
.SH "RETURN"
0 or Linux error code
