.TH "liquidio_napi_poll" 9 "liquidio_napi_poll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
liquidio_napi_poll \- Entry point for NAPI polling
.SH SYNOPSIS
.B "int" liquidio_napi_poll
.BI "(struct napi_struct *napi "  ","
.BI "int budget "  ");"
.SH ARGUMENTS
.IP "napi" 12
NAPI structure
.IP "budget" 12
maximum number of items to process
