.TH "lis3lv02d_acpi_init" 9 "lis3lv02d_acpi_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lis3lv02d_acpi_init \- ACPI _INI method: initialize the device.
.SH SYNOPSIS
.B "int" lis3lv02d_acpi_init
.BI "(struct lis3lv02d *lis3 "  ");"
.SH ARGUMENTS
.IP "lis3" 12
pointer to the device struct
.SH "DESCRIPTION"
Returns 0 on success.
