.TH "lis3lv02d_acpi_read" 9 "lis3lv02d_acpi_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lis3lv02d_acpi_read \- ACPI ALRD method: read a register
.SH SYNOPSIS
.B "int" lis3lv02d_acpi_read
.BI "(struct lis3lv02d *lis3 "  ","
.BI "int reg "  ","
.BI "u8 *ret "  ");"
.SH ARGUMENTS
.IP "lis3" 12
pointer to the device struct
.IP "reg" 12
the register to read
.IP "ret" 12
result of the operation
.SH "DESCRIPTION"
Returns 0 on success.
