.TH "llc_conn_ac_adjust_npta_by_rr" 9 "llc_conn_ac_adjust_npta_by_rr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
llc_conn_ac_adjust_npta_by_rr \- decreases "npta" by one
.SH SYNOPSIS
.B "int" llc_conn_ac_adjust_npta_by_rr
.BI "(struct sock *sk "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "sk" 12
current connection structure.
.IP "skb" 12
current event.

After receiving "dec_cntr" times RR command, this action decreases
"npta" by one. Returns 0 for success, 1 otherwise.
