.TH "llc_ui_header_len" 9 "llc_ui_header_len" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
llc_ui_header_len \- return length of llc header based on operation
.SH SYNOPSIS
.B "u8" llc_ui_header_len
.BI "(struct sock *sk "  ","
.BI "struct sockaddr_llc *addr "  ");"
.SH ARGUMENTS
.IP "sk" 12
Socket which contains a valid llc socket type.
.IP "addr" 12
Complete sockaddr_llc structure received from the user.

Provide the length of the llc header depending on what kind of
operation the user would like to perform and the type of socket.
Returns the correct llc header length.
