.TH "llc_conn_ac_inc_npta_value" 9 "llc_conn_ac_inc_npta_value" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
llc_conn_ac_inc_npta_value \- tries to make value of npta greater
.SH SYNOPSIS
.B "int" llc_conn_ac_inc_npta_value
.BI "(struct sock *sk "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "sk" 12
current connection structure.
.IP "skb" 12
current event.

After "inc_cntr" times calling of this action, "npta" increase by one.
this action tries to make vale of "npta" greater as possible; number of
acknowledgements decreases by increasing of "npta". Returns 0 for
success, 1 otherwise.
