.TH "llc_conn_rcv" 9 "llc_conn_rcv" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
llc_conn_rcv \- sends received pdus to the connection state machine
.SH SYNOPSIS
.B "int" llc_conn_rcv
.BI "(struct sock *sk "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "sk" 12
current connection structure.
.IP "skb" 12
received frame.

Sends received pdus to the connection state machine.
