.TH "llc_sap_remove_socket" 9 "llc_sap_remove_socket" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
llc_sap_remove_socket \- removes a socket from SAP
.SH SYNOPSIS
.B "void" llc_sap_remove_socket
.BI "(struct llc_sap *sap "  ","
.BI "struct sock *sk "  ");"
.SH ARGUMENTS
.IP "sap" 12
SAP
.IP "sk" 12
socket

This function removes a connection from the hash tables of a SAP if
the connection was in this list.
