.TH "lmm_to_fw_caps" 9 "lmm_to_fw_caps" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lmm_to_fw_caps \- translate ethtool Link Mode Mask to Firmware capabilities
.SH SYNOPSIS
.B "unsigned int" lmm_to_fw_caps
.BI "(const unsigned long *link_mode_mask "  ");"
.SH ARGUMENTS
.IP "link_mode_mask" 12
ethtool Link Mode Mask

Translate ethtool Link Mode Mask into a Firmware Port capabilities
value.
