.TH "locks_mandatory_locked" 9 "locks_mandatory_locked" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
locks_mandatory_locked \- Check for an active lock
.SH SYNOPSIS
.B "int" locks_mandatory_locked
.BI "(struct file *file "  ");"
.SH ARGUMENTS
.IP "file" 12
the file to check
.SH "DESCRIPTION"
Searches the inode's list of locks to find any POSIX locks which conflict.
This function is called from \fBlocks_verify_locked\fP only.
