.TH "longrun_get_policy" 9 "longrun_get_policy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
longrun_get_policy \- get the current LongRun policy
.SH SYNOPSIS
.B "void" longrun_get_policy
.BI "(struct cpufreq_policy *policy "  ");"
.SH ARGUMENTS
.IP "policy" 12
struct cpufreq_policy where current policy is written into
.SH "DESCRIPTION"
Reads the current LongRun policy by access to MSR_TMTA_LONGRUN_FLAGS
and MSR_TMTA_LONGRUN_CTRL
