.TH "lpfc_sli_iocb_cmd_type" 9 "lpfc_sli_iocb_cmd_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli_iocb_cmd_type \- Get the iocb type
.SH SYNOPSIS
.B "lpfc_iocb_type" lpfc_sli_iocb_cmd_type
.BI "(uint8_t iocb_cmnd "  ");"
.SH ARGUMENTS
.IP "iocb_cmnd" 12
iocb command code.
.SH "DESCRIPTION"
This function is called by ring event handler function to get the iocb type.
This function translates the iocb command to an iocb command type used to
decide the final disposition of each completed IOCB.
The function returns
LPFC_UNKNOWN_IOCB if it is an unsupported iocb
LPFC_SOL_IOCB     if it is a solicited iocb completion
LPFC_ABORT_IOCB   if it is an abort iocb
LPFC_UNSOL_IOCB   if it is an unsolicited iocb

The caller is not required to hold any lock.
