.TH "lpfc_sli_hbqbuf_fill_hbqs" 9 "lpfc_sli_hbqbuf_fill_hbqs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli_hbqbuf_fill_hbqs \- Post more hbq buffers to HBQ
.SH SYNOPSIS
.B "int" lpfc_sli_hbqbuf_fill_hbqs
.BI "(struct lpfc_hba *phba "  ","
.BI "uint32_t hbqno "  ","
.BI "uint32_t count "  ");"
.SH ARGUMENTS
.IP "phba" 12
Pointer to HBA context object.
.IP "hbqno" 12
HBQ number.
.IP "count" 12
Number of HBQ buffers to be posted.
.SH "DESCRIPTION"
This function is called with no lock held to post more hbq buffers to the
given HBQ. The function returns the number of HBQ buffers successfully
posted.
