.TH "lpfc_wwn_set" 9 "lpfc_wwn_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_wwn_set \- Convert string to the 8 byte WWN value.
.SH SYNOPSIS
.B "size_t" lpfc_wwn_set
.BI "(const char *buf "  ","
.BI "size_t cnt "  ","
.BI "char wwn[] "  ");"
.SH ARGUMENTS
.IP "buf" 12
WWN string.
.IP "cnt" 12
Length of string.
.IP "wwn" 12
Array to receive converted wwn value.
.SH "RETURN"
-EINVAL if the buffer does not contain a valid wwn
0 success
