.TH "lpfc_bsg_handle_sli_cfg_ebuf" 9 "lpfc_bsg_handle_sli_cfg_ebuf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_bsg_handle_sli_cfg_ebuf \- handle ext buffer with sli-cfg mailbox cmd
.SH SYNOPSIS
.B "int" lpfc_bsg_handle_sli_cfg_ebuf
.BI "(struct lpfc_hba *phba "  ","
.BI "struct bsg_job *job "  ","
.BI "struct lpfc_dmabuf *dmabuf "  ");"
.SH ARGUMENTS
.IP "phba" 12
Pointer to HBA context object.
.IP "job" 12
Pointer to the job object.
.IP "dmabuf" 12
Pointer to a DMA buffer descriptor.
.SH "DESCRIPTION"
This routine handles the external buffer with SLI_CONFIG (0x9B) mailbox
command with multiple non-embedded external buffers.
