.TH "lpfc_bsg_event_free" 9 "lpfc_bsg_event_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_bsg_event_free \- frees an allocated event structure
.SH SYNOPSIS
.B "void" lpfc_bsg_event_free
.BI "(struct kref *kref "  ");"
.SH ARGUMENTS
.IP "kref" 12
Pointer to a kref.
.SH "DESCRIPTION"
Called from kref_put. Back cast the kref into an event structure address.
Free any events to get, delete associated nodes, free any events to see,
free any data then free the event itself.
