.TH "lpfc_config_port_post" 9 "lpfc_config_port_post" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_config_port_post \- Perform lpfc initialization after config port
.SH SYNOPSIS
.B "int" lpfc_config_port_post
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine will do LPFC initialization after the CONFIG_PORT mailbox
command call. It performs all internal resource and state setups on the
port: post IOCB buffers, enable appropriate host interrupt attentions,
ELS ring timers, etc.

Return codes
0 - success.
Any other value - error.
