.TH "lpfc_debugfs_terminate" 9 "lpfc_debugfs_terminate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_debugfs_terminate \- Tear down debugfs infrastructure for this vport
.SH SYNOPSIS
.B "void" lpfc_debugfs_terminate
.BI "(struct lpfc_vport *vport "  ");"
.SH ARGUMENTS
.IP "vport" 12
The vport pointer to remove from debugfs.
.SH "DESCRIPTION"
When Debugfs is configured this routine removes debugfs file system elements
that are specific to this vport. It also checks to see if there are any
users left for the debugfs directories associated with the HBA and driver. If
this is the last user of the HBA directory or driver directory then it will
remove those from the debugfs infrastructure as well.
