.TH "lpfc_ignore_els_cmpl" 9 "lpfc_ignore_els_cmpl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_ignore_els_cmpl \- Completion handler for aborted ELS command
.SH SYNOPSIS
.B "void" lpfc_ignore_els_cmpl
.BI "(struct lpfc_hba *phba "  ","
.BI "struct lpfc_iocbq *cmdiocb "  ","
.BI "struct lpfc_iocbq *rspiocb "  ");"
.SH ARGUMENTS
.IP "phba" 12
Pointer to HBA context object.
.IP "cmdiocb" 12
Pointer to driver command iocb object.
.IP "rspiocb" 12
Pointer to driver response iocb object.
.SH "DESCRIPTION"
The function is called from SLI ring event handler with no
lock held. This function is the completion handler for ELS commands
which are aborted. The function frees memory resources used for
the aborted ELS commands.
