.TH "lpfc_issue_lip" 9 "lpfc_issue_lip" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_issue_lip \- Misnomer, name carried over from long ago
.SH SYNOPSIS
.B "int" lpfc_issue_lip
.BI "(struct Scsi_Host *shost "  ");"
.SH ARGUMENTS
.IP "shost" 12
Scsi_Host pointer.
.SH "DESCRIPTION"
Bring the link down gracefully then re-init the link. The firmware will
re-init the fiber channel interface as required. Does not issue a LIP.
.SH "RETURN"
-EPERM port offline or management commands are being blocked
-ENOMEM cannot allocate memory for the mailbox command
-EIO error sending the mailbox command
zero for success
