.TH "lpfc_io_free" 9 "lpfc_io_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_io_free \- Free all the IO buffers and IOCBs from driver lists
.SH SYNOPSIS
.B "void" lpfc_io_free
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine is to free all the IO buffers and IOCBs from the driver
list back to kernel. It is called from lpfc_pci_remove_one to free
the internal resources before the device is removed from the system.
