.TH "lpfc_hba_down_post" 9 "lpfc_hba_down_post" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_hba_down_post \- Wrapper func for hba down post routine
.SH SYNOPSIS
.B "int" lpfc_hba_down_post
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc HBA data structure.
.SH "DESCRIPTION"
This routine wraps the actual SLI3 or SLI4 routine for performing
uninitialization after the HBA is reset when bring down the SLI Layer.

Return codes
0 - success.
Any other value - error.
