.TH "lpfc_sli4_bar2_register_memmap" 9 "lpfc_sli4_bar2_register_memmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_bar2_register_memmap \- Set up SLI4 BAR2 register memory map.
.SH SYNOPSIS
.B "int" lpfc_sli4_bar2_register_memmap
.BI "(struct lpfc_hba *phba "  ","
.BI "uint32_t vf "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.IP "vf" 12
virtual function number
.SH "DESCRIPTION"
This routine is invoked to set up SLI4 BAR2 doorbell register memory map
based on the given viftual function number, \fIvf\fP.

Return 0 if successful, otherwise -ENODEV.
