.TH "lpfc_io_resume" 9 "lpfc_io_resume" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_io_resume \- lpfc method for resuming PCI I/O operation
.SH SYNOPSIS
.B "void" lpfc_io_resume
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
pointer to PCI device
.SH "DESCRIPTION"
This routine is registered to the PCI subsystem for error handling. It
is called when kernel error recovery tells the lpfc driver that it is
OK to resume normal PCI operation after PCI bus error recovery. When
this routine is invoked, it dispatches the action to the proper SLI-3
or SLI-4 device io_resume routine, which will resume the device operation.
