.TH "lpfc_destroy_shost" 9 "lpfc_destroy_shost" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_destroy_shost \- Destroy hba physical port with associated scsi host.
.SH SYNOPSIS
.B "void" lpfc_destroy_shost
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine is invoked to destroy HBA physical port and the associated
SCSI host.
