.TH "lpfc_reg_vpi" 9 "lpfc_reg_vpi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_reg_vpi \- Prepare a mailbox command for registering vport identifier
.SH SYNOPSIS
.B "void" lpfc_reg_vpi
.BI "(struct lpfc_vport *vport "  ","
.BI "LPFC_MBOXQ_t *pmb "  ");"
.SH ARGUMENTS
.IP "vport" 12
pointer to a vport object.
.IP "pmb" 12
pointer to the driver internal queue element for mailbox command.
.SH "DESCRIPTION"
The registration vport identifier mailbox command is used to activate a
virtual N_Port after it has acquired an N_Port_ID. The HBA validates the
N_Port_ID against the information in the selected virtual N_Port context
block and marks it active to allow normal processing of IOCB commands and
received unsolicited exchanges.

This routine prepares the mailbox command for registering a virtual N_Port.
