.TH "lpfc_sli4_parse_latt_type" 9 "lpfc_sli4_parse_latt_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_parse_latt_type \- Parse sli4 link attention type
.SH SYNOPSIS
.B "uint8_t" lpfc_sli4_parse_latt_type
.BI "(struct lpfc_hba *phba "  ","
.BI "struct lpfc_acqe_link *acqe_link "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.IP "acqe_link" 12
pointer to the async link completion queue entry.
.SH "DESCRIPTION"
This routine is to parse the SLI4 link attention type and translate it
into the base driver's link attention type coding.
.SH "RETURN"
Link attention type in terms of base driver's coding.
