.TH "lpfc_create_shost" 9 "lpfc_create_shost" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_create_shost \- Create hba physical port with associated scsi host.
.SH SYNOPSIS
.B "int" lpfc_create_shost
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine is invoked to create HBA physical port and associate a SCSI
host with it.

Return codes
0 - successful
other values - error
