.TH "lpfc_sli4_if6_eq_clr_intr" 9 "lpfc_sli4_if6_eq_clr_intr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_if6_eq_clr_intr \- Turn off interrupts from this EQ
.SH SYNOPSIS
.B "void" lpfc_sli4_if6_eq_clr_intr
.BI "(struct lpfc_queue *q "  ");"
.SH ARGUMENTS
.IP "q" 12
The Event Queue to disable interrupts
