.TH "lpfc_build_hbq_profile3" 9 "lpfc_build_hbq_profile3" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_build_hbq_profile3 \- Set up the HBQ Selection Profile 3
.SH SYNOPSIS
.B "void" lpfc_build_hbq_profile3
.BI "(struct config_hbq_var *hbqmb "  ","
.BI "struct lpfc_hbq_init *hbq_desc "  ");"
.SH ARGUMENTS
.IP "hbqmb" 12
pointer to the HBQ configuration data structure in mailbox command.
.IP "hbq_desc" 12
pointer to the HBQ selection profile descriptor.
.SH "DESCRIPTION"
The Host Buffer Queue (HBQ) Selection Profile 3 specifies that the HBA
tests the incoming frame's R_CTL/TYPE fields with words 10:15 and performs
the Sequence Length Test and Byte Field Test using the fields in the
Selection Profile 3 extension in words 20:31.
