.TH "lpfc_sli4_queue_alloc" 9 "lpfc_sli4_queue_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_queue_alloc \- Allocate and initialize a queue structure
.SH SYNOPSIS
.B "struct lpfc_queue *" lpfc_sli4_queue_alloc
.BI "(struct lpfc_hba *phba "  ","
.BI "uint32_t page_size "  ","
.BI "uint32_t entry_size "  ","
.BI "uint32_t entry_count "  ","
.BI "int cpu "  ");"
.SH ARGUMENTS
.IP "phba" 12
The HBA that this queue is being created on.
.IP "page_size" 12
The size of a queue page
.IP "entry_size" 12
The size of each queue entry for this queue.
.IP "entry_count" 12
The number of entries that this queue will handle.
.IP "cpu" 12
The cpu that will primarily utilize this queue.
.SH "DESCRIPTION"
This function allocates a queue structure and the DMAable memory used for
the host resident queue. This function must be called before creating the
queue on the HBA.
