.TH "lpfc_hba_clean_txcmplq" 9 "lpfc_hba_clean_txcmplq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_hba_clean_txcmplq \- Perform lpfc uninitialization after HBA reset
.SH SYNOPSIS
.B "void" lpfc_hba_clean_txcmplq
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc HBA data structure.
.SH "DESCRIPTION"
This routine will cleanup the txcmplq after the HBA is reset when bringing
down the SLI Layer.

Return codes
void
