.TH "lpfc_hba_down_post_s3" 9 "lpfc_hba_down_post_s3" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_hba_down_post_s3 \- Perform lpfc uninitialization after HBA reset
.SH SYNOPSIS
.B "int" lpfc_hba_down_post_s3
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc HBA data structure.
.SH "DESCRIPTION"
This routine will do uninitialization after the HBA is reset when bring
down the SLI Layer.

Return codes
0 - success.
Any other value - error.
