.TH "lpfc_sli4_next_xritag" 9 "lpfc_sli4_next_xritag" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_next_xritag \- Get an xritag for the io
.SH SYNOPSIS
.B "uint16_t" lpfc_sli4_next_xritag
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
Pointer to HBA context object.
.SH "DESCRIPTION"
This function gets an xritag for the iocb. If there is no unused xritag
it will return 0xffff.
The function returns the allocated xritag if successful, else returns zero.
Zero is not a valid xritag.
The caller is not required to hold any lock.
