.TH "lsm_file_alloc" 9 "lsm_file_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lsm_file_alloc \- allocate a composite file blob
.SH SYNOPSIS
.B "int" lsm_file_alloc
.BI "(struct file *file "  ");"
.SH ARGUMENTS
.IP "file" 12
the file that needs a blob
.SH "DESCRIPTION"
Allocate the file blob for all the modules

Returns 0, or -ENOMEM if memory can't be allocated.
