.TH "mac_set_cam" 9 "mac_set_cam" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mac_set_cam \- set CAM data
.SH SYNOPSIS
.B "void" mac_set_cam
.BI "(struct mac_regs __iomem *regs "  ","
.BI "int idx "  ","
.BI "const u8 *addr "  ");"
.SH ARGUMENTS
.IP "regs" 12
register block of this velocity
.IP "idx" 12
Cam index
.IP "addr" 12
2 or 6 bytes of CAM data

Load an address or vlan tag into a CAM
