.TH "macb_set_tx_clk" 9 "macb_set_tx_clk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
macb_set_tx_clk \- Set a clock to a new frequency
.SH SYNOPSIS
.B "void" macb_set_tx_clk
.BI "(struct macb *bp "  ","
.BI "int speed "  ");"
.SH ARGUMENTS
.IP "bp" 12
pointer to struct macb
.IP "speed" 12
New frequency in Hz
