.TH "marvell_pata_active" 9 "marvell_pata_active" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
marvell_pata_active \- check if PATA is active
.SH SYNOPSIS
.B "int" marvell_pata_active
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device

Returns 1 if the PATA port may be active. We know how to check this
for the 6145 but not the other devices
