.TH "max9611_read_csa_voltage" 9 "max9611_read_csa_voltage" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
max9611_read_csa_voltage \- read current sense amplifier output voltage
.SH SYNOPSIS
.B "int" max9611_read_csa_voltage
.BI "(struct max9611_dev *max9611 "  ","
.BI "u16 *adc_raw "  ","
.BI "enum max9611_csa_gain *csa_gain "  ");"
.SH ARGUMENTS
.IP "max9611" 12
max9611 device
.IP "adc_raw" 12
raw value read from ADC output
.IP "csa_gain" 12
gain configuration option selector
.SH "DESCRIPTION"

Current sense amplifier output voltage is read through a configurable
1x, 4x or 8x gain.
Start with plain 1x gain, and adjust gain control properly until a
meaningful value is read from ADC output.
