.TH "mdev_register_driver" 9 "mdev_register_driver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mdev_register_driver \- register a new MDEV driver
.SH SYNOPSIS
.B "int" mdev_register_driver
.BI "(struct mdev_driver *drv "  ","
.BI "struct module *owner "  ");"
.SH ARGUMENTS
.IP "drv" 12
the driver to register
.IP "owner" 12
module owner of driver to be registered
.SH "DESCRIPTION"
Returns a negative value on error, otherwise 0.
