.TH "mdiobus_setup_mdiodev_from_board_info" 9 "mdiobus_setup_mdiodev_from_board_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mdiobus_setup_mdiodev_from_board_info \- create and setup MDIO devices from pre-collected board specific MDIO information
.SH SYNOPSIS
.B "void" mdiobus_setup_mdiodev_from_board_info
.BI "(struct mii_bus *bus "  ","
.BI "int (*cb) (struct mii_bus *bus, struct mdio_board_info *bi) "  ");"
.SH ARGUMENTS
.IP "bus" 12
Bus the board_info belongs to
.IP "cb" 12
Callback to create device on bus
.SH "CONTEXT"
can sleep
