.TH "media_graph_walk_init" 9 "media_graph_walk_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
media_graph_walk_init \- Allocate resources for graph walk
.SH SYNOPSIS
.B "int" media_graph_walk_init
.BI "(struct media_graph *graph "  ","
.BI "struct media_device *mdev "  ");"
.SH ARGUMENTS
.IP "graph" 12
Media graph structure that will be used to walk the graph
.IP "mdev" 12
Media device
.SH "DESCRIPTION"
Reserve resources for graph walk in media device's current
state. The memory must be released using
\fBmedia_graph_walk_free\fP.

Returns error on failure, zero on success.
