.TH "megaraid_isr_iomapped" 9 "megaraid_isr_iomapped" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_isr_iomapped \- 
.SH SYNOPSIS
.B "irqreturn_t" megaraid_isr_iomapped
.BI "(int irq "  ","
.BI "void *devp "  ");"
.SH ARGUMENTS
.IP "irq" 12
irq
.IP "devp" 12
pointer to our soft state
.SH "DESCRIPTION"
Interrupt service routine for io-mapped controllers.
Find out if our device is interrupting. If yes, acknowledge the interrupt
and service the completed commands.
