.TH "megasas_init_adapter_fusion" 9 "megasas_init_adapter_fusion" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megasas_init_adapter_fusion \- Initializes the FW
.SH SYNOPSIS
.B "u32" megasas_init_adapter_fusion
.BI "(struct megasas_instance *instance "  ");"
.SH ARGUMENTS
.IP "instance" 12
Adapter soft state
.SH "DESCRIPTION"
This is the main function for initializing firmware.
