.TH "megaraid_sysfs_free_resources" 9 "megaraid_sysfs_free_resources" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_sysfs_free_resources \- free sysfs related resources
.SH SYNOPSIS
.B "void" megaraid_sysfs_free_resources
.BI "(adapter_t *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
controller's soft state
.SH "DESCRIPTION"
Free packets allocated for sysfs FW commands
