.TH "megaraid_alloc_scb" 9 "megaraid_alloc_scb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_alloc_scb \- detach and return a scb from the free list
.SH SYNOPSIS
.B "scb_t *" megaraid_alloc_scb
.BI "(adapter_t *adapter "  ","
.BI "struct scsi_cmnd *scp "  ");"
.SH ARGUMENTS
.IP "adapter" 12
controller's soft state
.IP "scp" 12
pointer to the scsi command to be executed
.SH "DESCRIPTION"
Return the scb from the head of the free list. NULL if there are none
available.
