.TH "megaraid_mbox_shutdown" 9 "megaraid_mbox_shutdown" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_mbox_shutdown \- PCI shutdown for megaraid HBA
.SH SYNOPSIS
.B "void" megaraid_mbox_shutdown
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
generic driver model device
.SH "DESCRIPTION"
Shutdown notification, perform flush cache.
