.TH "megaraid_mbox_mm_done" 9 "megaraid_mbox_mm_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_mbox_mm_done \- callback for CMM commands
.SH SYNOPSIS
.B "void" megaraid_mbox_mm_done
.BI "(adapter_t *adapter "  ","
.BI "scb_t *scb "  ");"
.SH ARGUMENTS
.IP "adapter" 12
HBA soft state
.IP "scb" 12
completed command
.SH "DESCRIPTION"
Callback routine for internal commands originated from the management
module.
