.TH "megasas_start_timer" 9 "megasas_start_timer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megasas_start_timer \- Initializes sriov heartbeat timer object
.SH SYNOPSIS
.B "void" megasas_start_timer
.BI "(struct megasas_instance *instance "  ");"
.SH ARGUMENTS
.IP "instance" 12
Adapter soft state
