.TH "megaraid_mbox_setup_device_map" 9 "megaraid_mbox_setup_device_map" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_mbox_setup_device_map \- manage device ids
.SH SYNOPSIS
.B "void" megaraid_mbox_setup_device_map
.BI "(adapter_t *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
Driver's soft state
.SH "DESCRIPTION"
Manage the device ids to have an appropriate mapping between the kernel
scsi addresses and megaraid scsi and logical drive addresses. We export
scsi devices on their actual addresses, whereas the logical drives are
exported on a virtual scsi channel.
