.TH "megasas_return_cmd_fusion" 9 "megasas_return_cmd_fusion" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megasas_return_cmd_fusion \- Return a cmd to free command pool
.SH SYNOPSIS
.B "void" megasas_return_cmd_fusion
.BI "(struct megasas_instance *instance "  ","
.BI "struct megasas_cmd_fusion *cmd "  ");"
.SH ARGUMENTS
.IP "instance" 12
Adapter soft state
.IP "cmd" 12
Command packet to be returned to free command pool
