.TH "megasas_reset_bus_host" 9 "megasas_reset_bus_host" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megasas_reset_bus_host \- Bus & host reset handler entry point
.SH SYNOPSIS
.B "int" megasas_reset_bus_host
.BI "(struct scsi_cmnd *scmd "  ");"
.SH ARGUMENTS
.IP "scmd" 12
Mid-layer SCSI command
