.TH "megasas_cmd_type" 9 "megasas_cmd_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megasas_cmd_type \- Checks if the cmd is for logical drive/sysPD and whether it's RW or non RW
.SH SYNOPSIS
.B "int" megasas_cmd_type
.BI "(struct scsi_cmnd *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
SCSI command
