.TH "megasas_create_sg_sense_fusion" 9 "megasas_create_sg_sense_fusion" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megasas_create_sg_sense_fusion \- Creates DMA pool for cmd frames
.SH SYNOPSIS
.B "int" megasas_create_sg_sense_fusion
.BI "(struct megasas_instance *instance "  ");"
.SH ARGUMENTS
.IP "instance" 12
Adapter soft state
