.TH "megaraid_mbox_extended_cdb" 9 "megaraid_mbox_extended_cdb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_mbox_extended_cdb \- check for support for extended CDBs
.SH SYNOPSIS
.B "int" megaraid_mbox_extended_cdb
.BI "(adapter_t *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
soft state for the controller
.SH "DESCRIPTION"
This routine check whether the controller in question supports extended
( > 10 bytes ) CDBs.
