.TH "mei_txe_hw_config" 9 "mei_txe_hw_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_txe_hw_config \- configure hardware at the start of the devices
.SH SYNOPSIS
.B "int" mei_txe_hw_config
.BI "(struct mei_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device structure
.SH "DESCRIPTION"
Configure hardware at the start of the device should be done only
once at the device probe time
.SH "RETURN"
always 0
