.TH "mei_hbm_fw_disconnect_req" 9 "mei_hbm_fw_disconnect_req" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_hbm_fw_disconnect_req \- disconnect request initiated by ME firmware host sends disconnect response
.SH SYNOPSIS
.B "int" mei_hbm_fw_disconnect_req
.BI "(struct mei_device *dev "  ","
.BI "struct hbm_client_connect_request *disconnect_req "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device structure.
.IP "disconnect_req" 12
disconnect request bus message from the me
.SH "RETURN"
-ENOMEM on allocation failure
