.TH "mei_cldev_uuid" 9 "mei_cldev_uuid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_cldev_uuid \- return uuid of the underlying me client
.SH SYNOPSIS
.B "const uuid_le *" mei_cldev_uuid
.BI "(const struct mei_cl_device *cldev "  ");"
.SH ARGUMENTS
.IP "cldev" 12
mei client device
.SH "RETURN"
me client uuid
