.TH "mei_hbm_start_wait" 9 "mei_hbm_start_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_hbm_start_wait \- wait for start response message.
.SH SYNOPSIS
.B "int" mei_hbm_start_wait
.BI "(struct mei_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device structure
.SH "RETURN"
0 on success and < 0 on failure
