.TH "mei_cl_bus_vtag_alloc" 9 "mei_cl_bus_vtag_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_cl_bus_vtag_alloc \- add bus client entry to vtag map
.SH SYNOPSIS
.B "int" mei_cl_bus_vtag_alloc
.BI "(struct mei_cl_device *cldev "  ");"
.SH ARGUMENTS
.IP "cldev" 12
me client device
.SH "RETURN"
* 0 on success
* -ENOMEM if memory allocation failed
