.TH "mei_dma_ring_empty_slots" 9 "mei_dma_ring_empty_slots" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_dma_ring_empty_slots \- calaculate number of empty slots in dma ring
.SH SYNOPSIS
.B "u32" mei_dma_ring_empty_slots
.BI "(struct mei_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
mei_device
.SH "RETURN"
number of empty slots
