.TH "mei_cl_bus_rx_event" 9 "mei_cl_bus_rx_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_cl_bus_rx_event \- schedule rx event
.SH SYNOPSIS
.B "bool" mei_cl_bus_rx_event
.BI "(struct mei_cl *cl "  ");"
.SH ARGUMENTS
.IP "cl" 12
host client
.SH "RETURN"
true if event was scheduled
false if the client is not waiting for event
