.TH "mem_cgroup_uncharge_skmem" 9 "mem_cgroup_uncharge_skmem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mem_cgroup_uncharge_skmem \- uncharge socket memory
.SH SYNOPSIS
.B "void" mem_cgroup_uncharge_skmem
.BI "(struct mem_cgroup *memcg "  ","
.BI "unsigned int nr_pages "  ");"
.SH ARGUMENTS
.IP "memcg" 12
memcg to uncharge
.IP "nr_pages" 12
number of pages to uncharge
