.TH "mem_cgroup_charge_skmem" 9 "mem_cgroup_charge_skmem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mem_cgroup_charge_skmem \- charge socket memory
.SH SYNOPSIS
.B "bool" mem_cgroup_charge_skmem
.BI "(struct mem_cgroup *memcg "  ","
.BI "unsigned int nr_pages "  ");"
.SH ARGUMENTS
.IP "memcg" 12
memcg to charge
.IP "nr_pages" 12
number of pages to charge
.SH "DESCRIPTION"
Charges \fInr_pages\fP to \fImemcg\fP. Returns true if the charge fit within
\fImemcg\fP's configured limit, false if the charge had to be forced.
