.TH "memblock_setclr_flag" 9 "memblock_setclr_flag" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
memblock_setclr_flag \- set or clear flag for a memory region
.SH SYNOPSIS
.B "int __init_memblock" memblock_setclr_flag
.BI "(phys_addr_t base "  ","
.BI "phys_addr_t size "  ","
.BI "int set "  ","
.BI "int flag "  ");"
.SH ARGUMENTS
.IP "base" 12
base address of the region
.IP "size" 12
size of the region
.IP "set" 12
set or clear the flag
.IP "flag" 12
the flag to update
.SH "DESCRIPTION"
This function isolates region [\fIbase\fP, \fIbase\fP + \fIsize\fP), and sets/clears flag
.SH "RETURN"
0 on success, -errno on failure.
