.TH "mempool_destroy" 9 "mempool_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mempool_destroy \- deallocate a memory pool
.SH SYNOPSIS
.B "void" mempool_destroy
.BI "(mempool_t *pool "  ");"
.SH ARGUMENTS
.IP "pool" 12
pointer to the memory pool which was allocated via
\fBmempool_create\fP.
.SH "DESCRIPTION"
Free all reserved elements in \fIpool\fP and \fIpool\fP itself.  This function
only sleeps if the \fBfree_fn\fP function sleeps.
