.TH "mempool_free" 9 "mempool_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mempool_free \- return an element to the pool.
.SH SYNOPSIS
.B "void" mempool_free
.BI "(void *element "  ","
.BI "mempool_t *pool "  ");"
.SH ARGUMENTS
.IP "element" 12
pool element pointer.
.IP "pool" 12
pointer to the memory pool which was allocated via
\fBmempool_create\fP.
.SH "DESCRIPTION"
this function only sleeps if the \fBfree_fn\fP function sleeps.
