.TH "men_z135_probe" 9 "men_z135_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
men_z135_probe \- Probe a z135 instance
.SH SYNOPSIS
.B "int" men_z135_probe
.BI "(struct mcb_device *mdev "  ","
.BI "const struct mcb_device_id *id "  ");"
.SH ARGUMENTS
.IP "mdev" 12
The MCB device
.IP "id" 12
The MCB device ID
.SH "DESCRIPTION"
men_z135_probe does the basic setup of hardware resources and registers the
new uart port to the tty layer.
