.TH "mesh_path_tx_pending" 9 "mesh_path_tx_pending" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mesh_path_tx_pending \- sends pending frames in a mesh path queue
.SH SYNOPSIS
.B "void" mesh_path_tx_pending
.BI "(struct mesh_path *mpath "  ");"
.SH ARGUMENTS
.IP "mpath" 12
mesh path to activate
.SH "DESCRIPTION"
Locking: the state_lock of the mpath structure must NOT be held when calling
this function.
