.TH "mext_page_double_lock" 9 "mext_page_double_lock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mext_page_double_lock \- Grab and lock pages on both @inode1 and @inode2
.SH SYNOPSIS
.B "int" mext_page_double_lock
.BI "(struct inode *inode1 "  ","
.BI "struct inode *inode2 "  ","
.BI "pgoff_t index1 "  ","
.BI "pgoff_t index2 "  ","
.BI "struct page *page[2] "  ");"
.SH ARGUMENTS
.IP "inode1" 12
the inode structure
.IP "inode2" 12
the inode structure
.IP "index1" 12
page index
.IP "index2" 12
page index
.IP "page" 12
result page vector
.SH "DESCRIPTION"
Grab two locked pages for inode's by inode order
