.TH "mfsdram" 9 "mfsdram" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mfsdram \- read and return controller register data
.SH SYNOPSIS
.B "u32" mfsdram
.BI "(const dcr_host_t *dcr_host "  ","
.BI "unsigned int idcr_n "  ");"
.SH ARGUMENTS
.IP "dcr_host" 12
A pointer to the DCR mapping.
.IP "idcr_n" 12
The indirect DCR register to read.
.SH "DESCRIPTION"
This routine reads and returns the data associated with the
controller's specified indirect DCR register.

Returns the read data.
