.TH "mipi_dsi_driver_unregister" 9 "mipi_dsi_driver_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mipi_dsi_driver_unregister \- unregister a driver for DSI devices
.SH SYNOPSIS
.B "void" mipi_dsi_driver_unregister
.BI "(struct mipi_dsi_driver *drv "  ");"
.SH ARGUMENTS
.IP "drv" 12
DSI driver structure
.SH "RETURN"
0 on success or a negative error code on failure.
