.TH "mipi_dsi_dcs_write_buffer" 9 "mipi_dsi_dcs_write_buffer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mipi_dsi_dcs_write_buffer \- transmit a DCS command with payload
.SH SYNOPSIS
.B "ssize_t" mipi_dsi_dcs_write_buffer
.BI "(struct mipi_dsi_device *dsi "  ","
.BI "const void *data "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "dsi" 12
DSI peripheral device
.IP "data" 12
buffer containing data to be transmitted
.IP "len" 12
size of transmission buffer
.SH "DESCRIPTION"
This function will automatically choose the right data type depending on
the command payload length.
.SH "RETURN"
The number of bytes successfully transmitted or a negative error
code on failure.
