.TH "mls_export_netlbl_cat" 9 "mls_export_netlbl_cat" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mls_export_netlbl_cat \- Export the MLS categories to NetLabel
.SH SYNOPSIS
.B "int" mls_export_netlbl_cat
.BI "(struct policydb *p "  ","
.BI "struct context *context "  ","
.BI "struct netlbl_lsm_secattr *secattr "  ");"
.SH ARGUMENTS
.IP "p" 12
-- undescribed --
.IP "context" 12
the security context
.IP "secattr" 12
the NetLabel security attributes
.SH "DESCRIPTION"
Given the security context copy the low MLS categories into the NetLabel
MLS category field.  Returns zero on success, negative values on failure.
