.TH "mmc_erase" 9 "mmc_erase" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mmc_erase \- erase sectors.
.SH SYNOPSIS
.B "int" mmc_erase
.BI "(struct mmc_card *card "  ","
.BI "unsigned int from "  ","
.BI "unsigned int nr "  ","
.BI "unsigned int arg "  ");"
.SH ARGUMENTS
.IP "card" 12
card to erase
.IP "from" 12
first sector to erase
.IP "nr" 12
number of sectors to erase
.IP "arg" 12
erase command argument
.SH "DESCRIPTION"
Caller must claim host before calling this function.
