.TH "mnt_drop_write" 9 "mnt_drop_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mnt_drop_write \- give up write access to a mount
.SH SYNOPSIS
.B "void" mnt_drop_write
.BI "(struct vfsmount *mnt "  ");"
.SH ARGUMENTS
.IP "mnt" 12
the mount on which to give up write access
.SH "DESCRIPTION"
Tells the low-level filesystem that we are done performing writes to it and
also allows filesystem to be frozen again.  Must be matched with
\fBmnt_want_write\fP call above.
