.TH "mpc8610_hpcd_machine_probe" 9 "mpc8610_hpcd_machine_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpc8610_hpcd_machine_probe \- initialize the board
.SH SYNOPSIS
.B "int" mpc8610_hpcd_machine_probe
.BI "(struct snd_soc_card *card "  ");"
.SH ARGUMENTS
.IP "card" 12
-- undescribed --
.SH "DESCRIPTION"

This function is used to initialize the board-specific hardware.

Here we program the DMACR and PMUXCR registers.
