.TH "mpc8610_hpcd_machine_remove" 9 "mpc8610_hpcd_machine_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpc8610_hpcd_machine_remove \- Remove the sound device
.SH SYNOPSIS
.B "int" mpc8610_hpcd_machine_remove
.BI "(struct snd_soc_card *card "  ");"
.SH ARGUMENTS
.IP "card" 12
-- undescribed --
.SH "DESCRIPTION"

This function is called to remove the sound device for one SSI.  We
de-program the DMACR and PMUXCR register.
