.TH "mpi_hw_event" 9 "mpi_hw_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpi_hw_event \- The hw event has come.
.SH SYNOPSIS
.B "int" mpi_hw_event
.BI "(struct pm8001_hba_info *pm8001_ha "  ","
.BI "void *piomb "  ");"
.SH ARGUMENTS
.IP "pm8001_ha" 12
our hba card information
.IP "piomb" 12
IO message buffer
