.TH "mpt3sas_get_num_volumes" 9 "mpt3sas_get_num_volumes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt3sas_get_num_volumes \- Get number of volumes in the ioc
.SH SYNOPSIS
.B "u8" mpt3sas_get_num_volumes
.BI "(struct MPT3SAS_ADAPTER *ioc "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
