.TH "mpt3sas_transport_port_remove" 9 "mpt3sas_transport_port_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt3sas_transport_port_remove \- remove port from the list
.SH SYNOPSIS
.B "void" mpt3sas_transport_port_remove
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "u64 sas_address "  ","
.BI "u64 sas_address_parent "  ","
.BI "struct hba_port *port "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "sas_address" 12
sas address of attached device
.IP "sas_address_parent" 12
sas address of parent expander or sas host
.IP "port" 12
hba port entry
.SH "CONTEXT"
This function will acquire ioc->sas_node_lock.
.SH "DESCRIPTION"
Removing object and freeing associated memory from the
ioc->sas_port_list.
