.TH "mpt3sas_config_update_driver_trigger_pg4" 9 "mpt3sas_config_update_driver_trigger_pg4" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt3sas_config_update_driver_trigger_pg4 \- update driver trigger page 4
.SH SYNOPSIS
.B "int" mpt3sas_config_update_driver_trigger_pg4
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "struct SL_WH_MPI_TRIGGERS_T *mpi_tg "  ","
.BI "bool set "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "mpi_tg" 12
mpi trigger list
.IP "set" 12
set ot clear trigger values
.SH "CONTEXT"
sleep.
.SH "DESCRIPTION"
Returns 0 for success, non-zero for failure.
