.TH "mpt3sas_trigger_mpi" 9 "mpt3sas_trigger_mpi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt3sas_trigger_mpi \- MPI trigger handler
.SH SYNOPSIS
.B "void" mpt3sas_trigger_mpi
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "u16 ioc_status "  ","
.BI "u32 loginfo "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "ioc_status" 12
?
.IP "loginfo" 12
?
