.TH "mpt3sas_config_get_raid_volume_pg1" 9 "mpt3sas_config_get_raid_volume_pg1" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt3sas_config_get_raid_volume_pg1 \- obtain raid volume page 1
.SH SYNOPSIS
.B "int" mpt3sas_config_get_raid_volume_pg1
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "Mpi2ConfigReply_t *mpi_reply "  ","
.BI "Mpi2RaidVolPage1_t *config_page "  ","
.BI "u32 form "  ","
.BI "u32 handle "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "mpi_reply" 12
reply mf payload returned from firmware
.IP "config_page" 12
contents of the config page
.IP "form" 12
GET_NEXT_HANDLE or HANDLE
.IP "handle" 12
volume handle
.SH "CONTEXT"
sleep.
.SH "RETURN"
0 for success, non-zero for failure.
