.TH "mpt3sas_base_update_missing_delay" 9 "mpt3sas_base_update_missing_delay" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt3sas_base_update_missing_delay \- change the missing delay timers
.SH SYNOPSIS
.B "void" mpt3sas_base_update_missing_delay
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "u16 device_missing_delay "  ","
.BI "u8 io_missing_delay "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "device_missing_delay" 12
amount of time till device is reported missing
.IP "io_missing_delay" 12
interval IO is returned when there is a missing device
.SH "DESCRIPTION"
Passed on the command line, this function will modify the device missing
delay, as well as the io missing delay. This should be called at driver
load time.
