.TH "mpt_iocstatus_info" 9 "mpt_iocstatus_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt_iocstatus_info \- IOCSTATUS information returned from IOC.
.SH SYNOPSIS
.B "void" mpt_iocstatus_info
.BI "(MPT_ADAPTER *ioc "  ","
.BI "u32 ioc_status "  ","
.BI "MPT_FRAME_HDR *mf "  ");"
.SH ARGUMENTS
.IP "ioc" 12
Pointer to MPT_ADAPTER structure
.IP "ioc_status" 12
U32 IOCStatus word from IOC
.IP "mf" 12
Pointer to MPT request frame

Refer to lsi/mpi.h.
