.TH "mptsas_issue_tm" 9 "mptsas_issue_tm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mptsas_issue_tm \- send mptsas internal tm request
.SH SYNOPSIS
.B "int" mptsas_issue_tm
.BI "(MPT_ADAPTER *ioc "  ","
.BI "u8 type "  ","
.BI "u8 channel "  ","
.BI "u8 id "  ","
.BI "u64 lun "  ","
.BI "int task_context "  ","
.BI "ulong timeout "  ","
.BI "u8 *issue_reset "  ");"
.SH ARGUMENTS
.IP "ioc" 12
Pointer to MPT_ADAPTER structure
.IP "type" 12
Task Management type
.IP "channel" 12
channel number for task management
.IP "id" 12
Logical Target ID for reset (if appropriate)
.IP "lun" 12
Logical unit for reset (if appropriate)
.IP "task_context" 12
Context for the task to be aborted
.IP "timeout" 12
timeout for task management control

return 0 on success and -1 on failure:
.IP "issue_reset" 12
-- undescribed --
