.TH "mptsas_exp_repmanufacture_info" 9 "mptsas_exp_repmanufacture_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mptsas_exp_repmanufacture_info \- 
.SH SYNOPSIS
.B "int" mptsas_exp_repmanufacture_info
.BI "(MPT_ADAPTER *ioc "  ","
.BI "u64 sas_address "  ","
.BI "struct sas_expander_device *edev "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "sas_address" 12
expander sas address
.IP "edev" 12
the sas_expander_device object
.SH "DESCRIPTION"
Fills in the sas_expander_device object when SMP port is created.

Returns 0 for success, non-zero for failure.
