.TH "mptsas_broadcast_primitive_work" 9 "mptsas_broadcast_primitive_work" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mptsas_broadcast_primitive_work \- Handle broadcast primitives
.SH SYNOPSIS
.B "void" mptsas_broadcast_primitive_work
.BI "(struct fw_event_work *fw_event "  ");"
.SH ARGUMENTS
.IP "fw_event" 12
-- undescribed --
