.TH "mptsas_firmware_event_work" 9 "mptsas_firmware_event_work" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mptsas_firmware_event_work \- work thread for processing fw events
.SH SYNOPSIS
.B "void" mptsas_firmware_event_work
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
work queue payload containing info describing the event
.SH "CONTEXT"
user
