.TH "mpu3050_drdy_trigger_set_state" 9 "mpu3050_drdy_trigger_set_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpu3050_drdy_trigger_set_state \- set data ready interrupt state
.SH SYNOPSIS
.B "int" mpu3050_drdy_trigger_set_state
.BI "(struct iio_trigger *trig "  ","
.BI "bool enable "  ");"
.SH ARGUMENTS
.IP "trig" 12
trigger instance
.IP "enable" 12
true if trigger should be enabled, false to disable
