.TH "mraid_mm_register_adp" 9 "mraid_mm_register_adp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mraid_mm_register_adp \- Registration routine for low level drivers
.SH SYNOPSIS
.B "int" mraid_mm_register_adp
.BI "(mraid_mmadp_t *lld_adp "  ");"
.SH ARGUMENTS
.IP "lld_adp" 12
Adapter object
