.TH "msc_oldest_window" 9 "msc_oldest_window" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
msc_oldest_window \- locate the window with oldest data
.SH SYNOPSIS
.B "struct msc_window *" msc_oldest_window
.BI "(struct msc *msc "  ");"
.SH ARGUMENTS
.IP "msc" 12
MSC device
.SH "DESCRIPTION"
This should only be used in multiblock mode. Caller should hold the
msc::user_count reference.
.SH "RETURN"
the oldest window with valid data
