.TH "msgdma_start_transfer" 9 "msgdma_start_transfer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
msgdma_start_transfer \- Initiate the new transfer
.SH SYNOPSIS
.B "void" msgdma_start_transfer
.BI "(struct msgdma_device *mdev "  ");"
.SH ARGUMENTS
.IP "mdev" 12
Pointer to the Altera mSGDMA device structure
