.TH "msix_capability_init" 9 "msix_capability_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
msix_capability_init \- configure device's MSI-X capability
.SH SYNOPSIS
.B "int" msix_capability_init
.BI "(struct pci_dev *dev "  ","
.BI "struct msix_entry *entries "  ","
.BI "int nvec "  ","
.BI "struct irq_affinity *affd "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to the pci_dev data structure of MSI-X device function
.IP "entries" 12
pointer to an array of struct msix_entry entries
.IP "nvec" 12
number of \fIentries\fP
.IP "affd" 12
Optional pointer to enable automatic affinity assignment
.SH "DESCRIPTION"
Setup the MSI-X capability structure of device function with a
single MSI-X IRQ. A return of zero indicates the successful setup of
requested MSI-X entries with allocated IRQs or non-zero for otherwise.
