.TH "mt2063_lockStatus" 9 "mt2063_lockStatus" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mt2063_lockStatus \- Checks to see if LO1 and LO2 are locked
.SH SYNOPSIS
.B "int" mt2063_lockStatus
.BI "(struct mt2063_state *state "  ");"
.SH ARGUMENTS
.IP "state" 12
struct mt2063_state pointer
.SH "DESCRIPTION"
This function returns 0, if no lock, 1 if locked and a value < 1 if error
