.TH "mux_type" 9 "mux_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mux_type \- Describe the port.
.SH SYNOPSIS
.B "const char *" mux_type
.BI "(struct uart_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
Ptr to the uart_port.
.SH "DESCRIPTION"
Return a pointer to a string constant describing the
specified port.
