.TH "mux_chip_unregister" 9 "mux_chip_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mux_chip_unregister \- Take the mux-chip off-line.
.SH SYNOPSIS
.B "void" mux_chip_unregister
.BI "(struct mux_chip *mux_chip "  ");"
.SH ARGUMENTS
.IP "mux_chip" 12
The mux-chip to unregister.
.SH "DESCRIPTION"
\fBmux_chip_unregister\fP reverses the effects of \fBmux_chip_register\fP.
But not completely, you should not try to call \fBmux_chip_register\fP
on a mux-chip that has been registered before.
