.TH "mux_start_tx" 9 "mux_start_tx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mux_start_tx \- Start transmitting characters.
.SH SYNOPSIS
.B "void" mux_start_tx
.BI "(struct uart_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
Ptr to the uart_port.
.SH "DESCRIPTION"
The Serial Mux does not support this function.
