.TH "mv6_reset_hc" 9 "mv6_reset_hc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mv6_reset_hc \- Perform the 6xxx global soft reset
.SH SYNOPSIS
.B "int" mv6_reset_hc
.BI "(struct mv_host_priv *hpriv "  ","
.BI "void __iomem *mmio "  ","
.BI "unsigned int n_hc "  ");"
.SH ARGUMENTS
.IP "hpriv" 12
-- undescribed --
.IP "mmio" 12
base address of the HBA

This routine only applies to 6xxx parts.

LOCKING:
Inherited from caller.
.IP "n_hc" 12
-- undescribed --
