.TH "mv_write_cached_reg" 9 "mv_write_cached_reg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mv_write_cached_reg \- write to a cached port register
.SH SYNOPSIS
.B "void" mv_write_cached_reg
.BI "(void __iomem *addr "  ","
.BI "u32 *old "  ","
.BI "u32 new "  ");"
.SH ARGUMENTS
.IP "addr" 12
hardware address of the register
.IP "old" 12
pointer to cached value of the register
.IP "new" 12
new value for the register

Write a new value to a cached register,
but only if the value is different from before.
