.TH "mx3fb_blank" 9 "mx3fb_blank" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mx3fb_blank \- blank the display.
.SH SYNOPSIS
.B "int" mx3fb_blank
.BI "(int blank "  ","
.BI "struct fb_info *fbi "  ");"
.SH ARGUMENTS
.IP "blank" 12
blank value for the panel
.IP "fbi" 12
framebuffer information pointer
