.TH "myrb_exec_cmd" 9 "myrb_exec_cmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
myrb_exec_cmd \- executes command block and waits for completion.
.SH SYNOPSIS
.B "unsigned short" myrb_exec_cmd
.BI "(struct myrb_hba *cb "  ","
.BI "struct myrb_cmdblk *cmd_blk "  ");"
.SH ARGUMENTS
.IP "cb" 12
-- undescribed --
.IP "cmd_blk" 12
-- undescribed --
.SH "RETURN"
command status
