.TH "myrb_exec_type3" 9 "myrb_exec_type3" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
myrb_exec_type3 \- executes a type 3 command and waits for completion.
.SH SYNOPSIS
.B "unsigned short" myrb_exec_type3
.BI "(struct myrb_hba *cb "  ","
.BI "enum myrb_cmd_opcode op "  ","
.BI "dma_addr_t addr "  ");"
.SH ARGUMENTS
.IP "cb" 12
-- undescribed --
.IP "op" 12
-- undescribed --
.IP "addr" 12
-- undescribed --
.SH "RETURN"
command status
