.TH "nand_maximize_ecc" 9 "nand_maximize_ecc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_maximize_ecc \- choose the max ECC strength available
.SH SYNOPSIS
.B "int" nand_maximize_ecc
.BI "(struct nand_chip *chip "  ","
.BI "const struct nand_ecc_caps *caps "  ","
.BI "int oobavail "  ");"
.SH ARGUMENTS
.IP "chip" 12
nand chip info structure
.IP "caps" 12
ECC engine caps info structure
.IP "oobavail" 12
OOB size that the ECC engine can use
.SH "DESCRIPTION"
Choose the max ECC strength that is supported on the controller, and can fit
within the chip's OOB.  On success, the chosen ECC settings are set.
