.TH "nand_block_checkbad" 9 "nand_block_checkbad" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_block_checkbad \- [GENERIC] Check if a block is marked bad
.SH SYNOPSIS
.B "int" nand_block_checkbad
.BI "(struct nand_chip *chip "  ","
.BI "loff_t ofs "  ","
.BI "int allowbbt "  ");"
.SH ARGUMENTS
.IP "chip" 12
NAND chip object
.IP "ofs" 12
offset from device start
.IP "allowbbt" 12
1, if its allowed to access the bbt area
.SH "DESCRIPTION"
Check, if the block is bad. Either by reading the bad block table or
calling of the scan function.
