.TH "nand_check_wp" 9 "nand_check_wp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_check_wp \- [GENERIC] check if the chip is write protected
.SH SYNOPSIS
.B "int" nand_check_wp
.BI "(struct nand_chip *chip "  ");"
.SH ARGUMENTS
.IP "chip" 12
NAND chip object
.SH "DESCRIPTION"
Check, if the device is write protected. The function expects, that the
device is already selected.
