.TH "nand_block_isreserved" 9 "nand_block_isreserved" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_block_isreserved \- [GENERIC] Check if a block is marked reserved.
.SH SYNOPSIS
.B "int" nand_block_isreserved
.BI "(struct mtd_info *mtd "  ","
.BI "loff_t ofs "  ");"
.SH ARGUMENTS
.IP "mtd" 12
MTD device structure
.IP "ofs" 12
offset from device start
.SH "DESCRIPTION"
Check if the block is marked as reserved.
