.TH "nand_ecc_init_ctx" 9 "nand_ecc_init_ctx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_ecc_init_ctx \- Init the ECC engine context
.SH SYNOPSIS
.B "int" nand_ecc_init_ctx
.BI "(struct nand_device *nand "  ");"
.SH ARGUMENTS
.IP "nand" 12
the NAND device
.SH "DESCRIPTION"
On success, the caller is responsible of calling \fI\fP\fBnand_ecc_cleanup_ctx\fP.
