.TH "nand_do_write_ops" 9 "nand_do_write_ops" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_do_write_ops \- [INTERN] NAND write with ECC
.SH SYNOPSIS
.B "int" nand_do_write_ops
.BI "(struct nand_chip *chip "  ","
.BI "loff_t to "  ","
.BI "struct mtd_oob_ops *ops "  ");"
.SH ARGUMENTS
.IP "chip" 12
NAND chip object
.IP "to" 12
offset to write to
.IP "ops" 12
oob operations description structure
.SH "DESCRIPTION"
NAND write with ECC.
