.TH "nand_choose_best_sdr_timings" 9 "nand_choose_best_sdr_timings" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_choose_best_sdr_timings \- Pick up the best SDR timings that both the NAND controller and the NAND chip support
.SH SYNOPSIS
.B "int" nand_choose_best_sdr_timings
.BI "(struct nand_chip *chip "  ","
.BI "struct nand_interface_config *iface "  ","
.BI "struct nand_sdr_timings *spec_timings "  ");"
.SH ARGUMENTS
.IP "chip" 12
the NAND chip
.IP "iface" 12
the interface configuration (can eventually be updated)
.IP "spec_timings" 12
specific timings, when not fitting the ONFI specification
.SH "DESCRIPTION"
If specific timings are provided, use them. Otherwise, retrieve supported
timing modes from ONFI information.
