.TH "nand_setup_interface" 9 "nand_setup_interface" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_setup_interface \- Setup the best data interface and timings
.SH SYNOPSIS
.B "int" nand_setup_interface
.BI "(struct nand_chip *chip "  ","
.BI "int chipnr "  ");"
.SH ARGUMENTS
.IP "chip" 12
The NAND chip
.IP "chipnr" 12
Internal die id
.SH "DESCRIPTION"
Configure what has been reported to be the best data interface and NAND
timings supported by the chip and the driver.

Returns 0 for success or negative error code otherwise.
