.TH "nand_read_byte16" 9 "nand_read_byte16" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_read_byte16 \- [DEFAULT] read one byte endianness aware from the chip
.SH SYNOPSIS
.B "uint8_t" nand_read_byte16
.BI "(struct nand_chip *chip "  ");"
.SH ARGUMENTS
.IP "chip" 12
NAND chip object
.SH "DESCRIPTION"
Default read function for 16bit buswidth with endianness conversion.
