.TH "nci_spi_read" 9 "nci_spi_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nci_spi_read \- read frame from NCI SPI drivers
.SH SYNOPSIS
.B "struct sk_buff *" nci_spi_read
.BI "(struct nci_spi *nspi "  ");"
.SH ARGUMENTS
.IP "nspi" 12
The nci spi
.SH "CONTEXT"
can sleep
.SH "DESCRIPTION"
This call may only be used from a context that may sleep.  The sleep
is non-interruptible, and has no timeout.

It returns an allocated skb containing the frame on success, or NULL.
