.TH "NCR5380_info" 9 "NCR5380_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
NCR5380_info \- report driver and host information
.SH SYNOPSIS
.B "const char *" NCR5380_info
.BI "(struct Scsi_Host *instance "  ");"
.SH ARGUMENTS
.IP "instance" 12
relevant scsi host instance
.SH "DESCRIPTION"
For use as the host template \fBinfo\fP handler.
