.TH "net_failover_destroy" 9 "net_failover_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
net_failover_destroy \- Destroy a failover instance
.SH SYNOPSIS
.B "void" net_failover_destroy
.BI "(struct failover *failover "  ");"
.SH ARGUMENTS
.IP "failover" 12
pointer to failover instance
.SH "DESCRIPTION"
Unregisters any slave netdevs associated with the failover instance by
calling \fBfailover_slave_unregister\fP.
unregisters the failover instance itself and finally frees the failover
netdev. Used by paravirtual drivers that use 3-netdev model.
