.TH "netdev_set_wol" 9 "netdev_set_wol" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
netdev_set_wol \- set Wake-on-LAN support
.SH SYNOPSIS
.B "int" netdev_set_wol
.BI "(struct net_device *dev "  ","
.BI "struct ethtool_wolinfo *wol "  ");"
.SH ARGUMENTS
.IP "dev" 12
Network device.
.IP "wol" 12
Ethtool Wake-on-LAN data structure.
.SH "DESCRIPTION"
This function sets Wake-on-LAN support.

Return 0 if successful; otherwise an error code.
