.TH "netiucv_unpack_skb" 9 "netiucv_unpack_skb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
netiucv_unpack_skb \- 
.SH SYNOPSIS
.B "void" netiucv_unpack_skb
.BI "(struct iucv_connection *conn "  ","
.BI "struct sk_buff *pskb "  ");"
.SH ARGUMENTS
.IP "conn" 12
The connection where this skb has been received.
.IP "pskb" 12
The received skb.
.SH "DESCRIPTION"
Unpack a just received skb and hand it over to upper layers.
Helper function for conn_action_rx.
