.TH "netif_device_attach" 9 "netif_device_attach" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
netif_device_attach \- mark device as attached
.SH SYNOPSIS
.B "void" netif_device_attach
.BI "(struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
network device
.SH "DESCRIPTION"
Mark device as attached from system and restart if needed.
