.TH "nfp_net_rx_ring_free" 9 "nfp_net_rx_ring_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_net_rx_ring_free \- Free resources allocated to a RX ring
.SH SYNOPSIS
.B "void" nfp_net_rx_ring_free
.BI "(struct nfp_net_rx_ring *rx_ring "  ");"
.SH ARGUMENTS
.IP "rx_ring" 12
RX ring to free
