.TH "nfp_mip_open" 9 "nfp_mip_open" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_mip_open \- Get device MIP structure
.SH SYNOPSIS
.B "const struct nfp_mip *" nfp_mip_open
.BI "(struct nfp_cpp *cpp "  ");"
.SH ARGUMENTS
.IP "cpp" 12
NFP CPP Handle
.SH "DESCRIPTION"
Copy MIP structure from NFP device and return it.  The returned
structure is handled internally by the library and should be
freed by calling \fBnfp_mip_close\fP.
.SH "RETURN"
pointer to mip, NULL on failure.
