.TH "nfp_cpp_serial" 9 "nfp_cpp_serial" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_cpp_serial \- Retrieve the Serial ID of the NFP
.SH SYNOPSIS
.B "int" nfp_cpp_serial
.BI "(struct nfp_cpp *cpp "  ","
.BI "const u8 **serial "  ");"
.SH ARGUMENTS
.IP "cpp" 12
NFP CPP handle
.IP "serial" 12
Pointer to NFP serial number
.SH "RETURN"
Length of NFP serial number
