.TH "nfp_cpp_explicit_set_posted" 9 "nfp_cpp_explicit_set_posted" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_cpp_explicit_set_posted \- Set completion fields for explicit
.SH SYNOPSIS
.B "int" nfp_cpp_explicit_set_posted
.BI "(struct nfp_cpp_explicit *expl "  ","
.BI "int posted "  ","
.BI "u8 siga "  ","
.BI "enum nfp_cpp_explicit_signal_mode siga_mode "  ","
.BI "u8 sigb "  ","
.BI "enum nfp_cpp_explicit_signal_mode sigb_mode "  ");"
.SH ARGUMENTS
.IP "expl" 12
Explicit handle
.IP "posted" 12
True for signaled completion, false otherwise
.IP "siga" 12
CPP Signal A field
.IP "siga_mode" 12
CPP Signal A Mode field
.IP "sigb" 12
CPP Signal B field
.IP "sigb_mode" 12
CPP Signal B Mode field
.SH "RETURN"
0, or -ERRNO
