.TH "nfp_rtsym_read_le" 9 "nfp_rtsym_read_le" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_rtsym_read_le \- Read a simple unsigned scalar value from symbol
.SH SYNOPSIS
.B "u64" nfp_rtsym_read_le
.BI "(struct nfp_rtsym_table *rtbl "  ","
.BI "const char *name "  ","
.BI "int *error "  ");"
.SH ARGUMENTS
.IP "rtbl" 12
NFP RTsym table
.IP "name" 12
Symbol name
.IP "error" 12
Poniter to error code (optional)
.SH "DESCRIPTION"
Lookup a symbol, map, read it and return it's value. Value of the symbol
will be interpreted as a simple little-endian unsigned value. Symbol can
be 4 or 8 bytes in size.
.SH "RETURN"
value read, on error sets the error and returns ~0ULL.
