.TH "nfs4_proc_setclientid_confirm" 9 "nfs4_proc_setclientid_confirm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfs4_proc_setclientid_confirm \- Confirm client ID
.SH SYNOPSIS
.B "int" nfs4_proc_setclientid_confirm
.BI "(struct nfs_client *clp "  ","
.BI "struct nfs4_setclientid_res *arg "  ","
.BI "const struct cred *cred "  ");"
.SH ARGUMENTS
.IP "clp" 12
state data structure
.IP "arg" 12
result of a previous SETCLIENTID
.IP "cred" 12
credential to use for this call
.SH "DESCRIPTION"
Returns zero, a negative errno, or a negative NFS4ERR status code.
