.TH "nfs41_free_stateid" 9 "nfs41_free_stateid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfs41_free_stateid \- perform a FREE_STATEID operation
.SH SYNOPSIS
.B "int" nfs41_free_stateid
.BI "(struct nfs_server *server "  ","
.BI "const nfs4_stateid *stateid "  ","
.BI "const struct cred *cred "  ","
.BI "bool privileged "  ");"
.SH ARGUMENTS
.IP "server" 12
server / transport on which to perform the operation
.IP "stateid" 12
state ID to release
.IP "cred" 12
credential
.IP "privileged" 12
set to true if this call needs to be privileged
.SH "NOTE"
this function is always asynchronous.
