.TH "nfs_close_context" 9 "nfs_close_context" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfs_close_context \- Common close_context() routine NFSv2/v3
.SH SYNOPSIS
.B "void" nfs_close_context
.BI "(struct nfs_open_context *ctx "  ","
.BI "int is_sync "  ");"
.SH ARGUMENTS
.IP "ctx" 12
pointer to context
.IP "is_sync" 12
is this a synchronous close
.SH "DESCRIPTION"
Ensure that the attributes are up to date if we're mounted
with close-to-open semantics and we have cached data that will
need to be revalidated on open.
