.TH "nfs_async_unlink_done" 9 "nfs_async_unlink_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfs_async_unlink_done \- Sillydelete post-processing
.SH SYNOPSIS
.B "void" nfs_async_unlink_done
.BI "(struct rpc_task *task "  ","
.BI "void *calldata "  ");"
.SH ARGUMENTS
.IP "task" 12
rpc_task of the sillydelete
.IP "calldata" 12
pointer to nfs_unlinkdata
.SH "DESCRIPTION"
Do the directory attribute update.
