.TH "nfs_end_io_direct" 9 "nfs_end_io_direct" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfs_end_io_direct \- declare that the direct i/o operation is done
.SH SYNOPSIS
.B "void" nfs_end_io_direct
.BI "(struct inode *inode "  ");"
.SH ARGUMENTS
.IP "inode" 12
file inode
.SH "DESCRIPTION"
Declare that a direct I/O operation is done, and release the shared
lock on inode->i_rwsem.
