.TH "nfs_fattr_init_names" 9 "nfs_fattr_init_names" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfs_fattr_init_names \- initialise the nfs_fattr owner_name/group_name fields
.SH SYNOPSIS
.B "void" nfs_fattr_init_names
.BI "(struct nfs_fattr *fattr "  ","
.BI "struct nfs4_string *owner_name "  ","
.BI "struct nfs4_string *group_name "  ");"
.SH ARGUMENTS
.IP "fattr" 12
fully initialised struct nfs_fattr
.IP "owner_name" 12
owner name string cache
.IP "group_name" 12
group name string cache
