.TH "nfs_follow_referral" 9 "nfs_follow_referral" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfs_follow_referral \- set up mountpoint when hitting a referral on moved error
.SH SYNOPSIS
.B "int" nfs_follow_referral
.BI "(struct fs_context *fc "  ","
.BI "const struct nfs4_fs_locations *locations "  ");"
.SH ARGUMENTS
.IP "fc" 12
pointer to struct nfs_fs_context
.IP "locations" 12
array of NFSv4 server location information
