.TH "nft_pipapo_insert" 9 "nft_pipapo_insert" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nft_pipapo_insert \- Validate and insert ranged elements
.SH SYNOPSIS
.B "int" nft_pipapo_insert
.BI "(const struct net *net "  ","
.BI "const struct nft_set *set "  ","
.BI "const struct nft_set_elem *elem "  ","
.BI "struct nft_set_ext **ext2 "  ");"
.SH ARGUMENTS
.IP "net" 12
Network namespace
.IP "set" 12
nftables API set representation
.IP "elem" 12
nftables API element representation containing key data
.IP "ext2" 12
Filled with pointer to \fIstruct nft_set_ext\fP in inserted element
.SH "RETURN"
0 on success, error pointer on failure.
