.TH "ni_tio_set_bits" 9 "ni_tio_set_bits" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ni_tio_set_bits \- Safely write a counter register.
.SH SYNOPSIS
.B "void" ni_tio_set_bits
.BI "(struct ni_gpct *counter "  ","
.BI "enum ni_gpct_register reg "  ","
.BI "unsigned int mask "  ","
.BI "unsigned int value "  ");"
.SH ARGUMENTS
.IP "counter" 12
struct ni_gpct counter.
.IP "reg" 12
the register to write.
.IP "mask" 12
the bits to change.
.IP "value" 12
the new bits value.
.SH "DESCRIPTION"
Used to write to, and update the software copy, a register whose bits may
be twiddled in interrupt context, or whose software copy may be read in
interrupt context.
