.TH "nilfs_palloc_abort_free_entry" 9 "nilfs_palloc_abort_free_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nilfs_palloc_abort_free_entry \- cancel deallocating a persistent object
.SH SYNOPSIS
.B "void" nilfs_palloc_abort_free_entry
.BI "(struct inode *inode "  ","
.BI "struct nilfs_palloc_req *req "  ");"
.SH ARGUMENTS
.IP "inode" 12
inode of metadata file using this allocator
.IP "req" 12
nilfs_palloc_req structure exchanged for the removal
