.TH "nilfs_ifile_delete_inode" 9 "nilfs_ifile_delete_inode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nilfs_ifile_delete_inode \- delete a disk inode
.SH SYNOPSIS
.B "int" nilfs_ifile_delete_inode
.BI "(struct inode *ifile "  ","
.BI "ino_t ino "  ");"
.SH ARGUMENTS
.IP "ifile" 12
ifile inode
.IP "ino" 12
inode number
.SH "DESCRIPTION"
Return Value: On success, 0 is returned. On error, one of the following
negative error codes is returned.

-EIO - I/O error.

-ENOMEM - Insufficient amount of memory available.

-ENOENT - The inode number \fIino\fP have not been allocated.
