.TH "nilfs_dat_translate" 9 "nilfs_dat_translate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nilfs_dat_translate \- translate a virtual block number to a block number
.SH SYNOPSIS
.B "int" nilfs_dat_translate
.BI "(struct inode *dat "  ","
.BI "__u64 vblocknr "  ","
.BI "sector_t *blocknrp "  ");"
.SH ARGUMENTS
.IP "dat" 12
DAT file inode
.IP "vblocknr" 12
virtual block number
.IP "blocknrp" 12
pointer to a block number
.SH "DESCRIPTION"
\fBnilfs_dat_translate\fP maps the virtual block number \fIvblocknr\fP
to the corresponding block number.

Return Value: On success, 0 is returned and the block number associated
with \fIvblocknr\fP is stored in the place pointed by \fIblocknrp\fP. On error, one
of the following negative error codes is returned.

-EIO - I/O error.

-ENOMEM - Insufficient amount of memory available.

-ENOENT - A block number associated with \fIvblocknr\fP does not exist.
