.TH "nitrox_probe" 9 "nitrox_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nitrox_probe \- NITROX Initialization function.
.SH SYNOPSIS
.B "int" nitrox_probe
.BI "(struct pci_dev *pdev "  ","
.BI "const struct pci_device_id *id "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device information struct
.IP "id" 12
entry in nitrox_pci_tbl
.SH "RETURN"
0, if the driver is bound to the device, or
a negative error if there is failure.
