.TH "nlm_host_rebooted" 9 "nlm_host_rebooted" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nlm_host_rebooted \- Release all resources held by rebooted host
.SH SYNOPSIS
.B "void" nlm_host_rebooted
.BI "(const struct net *net "  ","
.BI "const struct nlm_reboot *info "  ");"
.SH ARGUMENTS
.IP "net" 12
network namespace
.IP "info" 12
pointer to decoded results of NLM_SM_NOTIFY call
.SH "DESCRIPTION"
We were notified that the specified host has rebooted.  Release
all resources held by that peer.
