.TH "nlmsvc_invalidate_all" 9 "nlmsvc_invalidate_all" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nlmsvc_invalidate_all \- remove all locks held for clients
.SH SYNOPSIS
.B "void" nlmsvc_invalidate_all
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Release all locks held by NFS clients.
