.TH "nps_enet_set_rx_mode" 9 "nps_enet_set_rx_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nps_enet_set_rx_mode \- Change the receive filtering mode.
.SH SYNOPSIS
.B "void" nps_enet_set_rx_mode
.BI "(struct net_device *ndev "  ");"
.SH ARGUMENTS
.IP "ndev" 12
Pointer to the network device.
.SH "DESCRIPTION"
This function enables/disables promiscuous mode
