.TH "ns_match" 9 "ns_match" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ns_match \- Returns true if current namespace matches dev/ino provided.
.SH SYNOPSIS
.B "bool" ns_match
.BI "(const struct ns_common *ns "  ","
.BI "dev_t dev "  ","
.BI "ino_t ino "  ");"
.SH ARGUMENTS
.IP "ns" 12
-- undescribed --
.IP "dev" 12
dev_t from nsfs that will be matched against current nsfs
.IP "ino" 12
ino_t from nsfs that will be matched against current nsfs
.SH "RETURN"
true if dev and ino matches the current nsfs.
