.TH "nsecs_to_jiffies" 9 "nsecs_to_jiffies" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nsecs_to_jiffies \- Convert nsecs in u64 to jiffies
.SH SYNOPSIS
.B "unsigned long" nsecs_to_jiffies
.BI "(u64 n "  ");"
.SH ARGUMENTS
.IP "n" 12
nsecs in u64
.SH "DESCRIPTION"
Unlike {m,u}secs_to_jiffies, type of input is not unsigned int but u64.
And this doesn't return MAX_JIFFY_OFFSET since this function is designed
for scheduler, not for use in device drivers to calculate timeout value.
.SH "NOTE"
NSEC_PER_SEC = 10^9 = (5^9 * 2^9) = (1953125 * 512)
ULLONG_MAX ns = 18446744073.709551615 secs = about 584 years
