.TH "ntb_msi_init" 9 "ntb_msi_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ntb_msi_init \- Initialize the MSI context
.SH SYNOPSIS
.B "int" ntb_msi_init
.BI "(struct ntb_dev *ntb "  ","
.BI "void (*desc_changed)(void *ctx) "  ");"
.SH ARGUMENTS
.IP "ntb" 12
NTB device context
.IP "desc_changed" 12
-- undescribed --
.SH "DESCRIPTION"
This function must be called before any other ntb_msi function.
It initializes the context for MSI operations and maps
the peer memory windows.

This function reserves the last N outbound memory windows (where N
is the number of peers).
.SH "RETURN"
Zero on success, otherwise a negative error number.
