.TH "ntfs_rl_mc" 9 "ntfs_rl_mc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ntfs_rl_mc \- runlist memory copy
.SH SYNOPSIS
.B "void" ntfs_rl_mc
.BI "(runlist_element *dstbase "  ","
.BI "int dst "  ","
.BI "runlist_element *srcbase "  ","
.BI "int src "  ","
.BI "int size "  ");"
.SH ARGUMENTS
.IP "dstbase" 12
-- undescribed --
.IP "dst" 12
-- undescribed --
.IP "srcbase" 12
-- undescribed --
.IP "src" 12
-- undescribed --
.IP "size" 12
-- undescribed --
.SH "DESCRIPTION"

It is up to the caller to serialize access to the runlists \fIdstbase\fP and
\fIsrcbase\fP.
