.TH "nvec_tx_set" 9 "nvec_tx_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nvec_tx_set \- Set the message to transfer (nvec->tx)
.SH SYNOPSIS
.B "void" nvec_tx_set
.BI "(struct nvec_chip *nvec "  ");"
.SH ARGUMENTS
.IP "nvec" 12
A \fIstruct nvec_chip\fP
.SH "DESCRIPTION"
Gets the first entry from the tx_data list of \fInvec\fP and sets the
tx member to it. If the tx_data list is empty, this uses the
tx_scratch message to send a no operation message.
