.TH "nvec_write_async" 9 "nvec_write_async" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nvec_write_async \- Asynchronously write a message to NVEC
.SH SYNOPSIS
.B "int" nvec_write_async
.BI "(struct nvec_chip *nvec "  ","
.BI "const unsigned char *data "  ","
.BI "short size "  ");"
.SH ARGUMENTS
.IP "nvec" 12
An nvec_chip instance
.IP "data" 12
The message data, starting with the request type
.IP "size" 12
The size of \fIdata\fP
.SH "DESCRIPTION"
Queue a single message to be transferred to the embedded controller
and return immediately.
.SH "RETURN"
0 on success, a negative error code on failure. If a failure
occurred, the nvec driver may print an error.
