.TH "nvec_register_notifier" 9 "nvec_register_notifier" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nvec_register_notifier \- Register a notifier with nvec
.SH SYNOPSIS
.B "int" nvec_register_notifier
.BI "(struct nvec_chip *nvec "  ","
.BI "struct notifier_block *nb "  ","
.BI "unsigned int events "  ");"
.SH ARGUMENTS
.IP "nvec" 12
A \fIstruct nvec_chip\fP
.IP "nb" 12
The notifier block to register
.IP "events" 12
-- undescribed --
.SH "DESCRIPTION"
Registers a notifier with \fInvec\fP. The notifier will be added to an atomic
notifier chain that is called for all received messages except those that
correspond to a request initiated by \fBnvec_write_sync\fP.
