.TH "nvmem_register" 9 "nvmem_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nvmem_register \- Register a nvmem device for given nvmem_config. Also creates a binary entry in /sys/bus/nvmem/devices/dev-name/nvmem
.SH SYNOPSIS
.B "struct nvmem_device *" nvmem_register
.BI "(const struct nvmem_config *config "  ");"
.SH ARGUMENTS
.IP "config" 12
nvmem device configuration with which nvmem device is created.
.SH "RETURN"
Will be an \fBERR_PTR\fP on error or a valid pointer to nvmem_device
on success.
