.TH "oaktrail_lvds_init" 9 "oaktrail_lvds_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
oaktrail_lvds_init \- setup LVDS connectors on this device
.SH SYNOPSIS
.B "void" oaktrail_lvds_init
.BI "(struct drm_device *dev "  ","
.BI "struct psb_intel_mode_device *mode_dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
drm device
.IP "mode_dev" 12
PSB mode device
.SH "DESCRIPTION"
Create the connector, register the LVDS DDC bus, and try to figure out what
modes we can display on the LVDS panel (if present).
