.TH "octeon_mbox_write" 9 "octeon_mbox_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
octeon_mbox_write \- 
.SH SYNOPSIS
.B "int" octeon_mbox_write
.BI "(struct octeon_device *oct "  ","
.BI "struct octeon_mbox_cmd *mbox_cmd "  ");"
.SH ARGUMENTS
.IP "oct" 12
Pointer Octeon Device
.IP "mbox_cmd" 12
Cmd to send to mailbox.
.SH "DESCRIPTION"
Populates the queue specific mbox structure
with cmd information.
Write the cmd to mbox register
