.TH "ocxlflash_allocate_afu_irqs" 9 "ocxlflash_allocate_afu_irqs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ocxlflash_allocate_afu_irqs \- allocates the requested number of interrupts
.SH SYNOPSIS
.B "int" ocxlflash_allocate_afu_irqs
.BI "(void *ctx_cookie "  ","
.BI "int num "  ");"
.SH ARGUMENTS
.IP "ctx_cookie" 12
Context associated with the request.
.IP "num" 12
Number of interrupts requested.
.SH "RETURN"
0 on success, -errno on failure
