.TH "of_alias_get_id" 9 "of_alias_get_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_alias_get_id \- Get alias id for the given device_node
.SH SYNOPSIS
.B "int" of_alias_get_id
.BI "(struct device_node *np "  ","
.BI "const char *stem "  ");"
.SH ARGUMENTS
.IP "np" 12
Pointer to the given device_node
.IP "stem" 12
Alias stem of the given device_node
.SH "DESCRIPTION"
The function travels the lookup table to get the alias id for the given
device_node and alias stem.  It returns the alias id if found.
