.TH "of_create_pci_dev" 9 "of_create_pci_dev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_create_pci_dev \- Given a device tree node on a pci bus, create a pci_dev
.SH SYNOPSIS
.B "struct pci_dev *" of_create_pci_dev
.BI "(struct device_node *node "  ","
.BI "struct pci_bus *bus "  ","
.BI "int devfn "  ");"
.SH ARGUMENTS
.IP "node" 12
device tree node pointer
.IP "bus" 12
bus the device is sitting on
.IP "devfn" 12
PCI function number, extracted from device tree by caller.
