.TH "of_clk_add_hw_provider" 9 "of_clk_add_hw_provider" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_clk_add_hw_provider \- Register a clock provider for a node
.SH SYNOPSIS
.B "int" of_clk_add_hw_provider
.BI "(struct device_node *np "  ","
.BI "struct clk_hw *(*get)(struct of_phandle_args *clkspec, void *data) "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "np" 12
Device node pointer associated with clock provider
.IP "get" 12
callback for decoding clk_hw
.IP "data" 12
context pointer for \fIget\fP callback.
