.TH "of_changeset_destroy" 9 "of_changeset_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_changeset_destroy \- Destroy a changeset
.SH SYNOPSIS
.B "void" of_changeset_destroy
.BI "(struct of_changeset *ocs "  ");"
.SH ARGUMENTS
.IP "ocs" 12
changeset pointer
.SH "DESCRIPTION"
Destroys a changeset. Note that if a changeset is applied,
its changes to the tree cannot be reverted.
