.TH "of_devfreq_cooling_register" 9 "of_devfreq_cooling_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_devfreq_cooling_register \- Register devfreq cooling device, with OF information.
.SH SYNOPSIS
.B "struct thermal_cooling_device *" of_devfreq_cooling_register
.BI "(struct device_node *np "  ","
.BI "struct devfreq *df "  ");"
.SH ARGUMENTS
.IP "np" 12
Pointer to OF device_node.
.IP "df" 12
Pointer to devfreq device.
