.TH "of_dma_request_slave_channel" 9 "of_dma_request_slave_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_dma_request_slave_channel \- Get the DMA slave channel
.SH SYNOPSIS
.B "struct dma_chan *" of_dma_request_slave_channel
.BI "(struct device_node *np "  ","
.BI "const char *name "  ");"
.SH ARGUMENTS
.IP "np" 12
device node to get DMA request from
.IP "name" 12
name of desired channel
.SH "DESCRIPTION"
Returns pointer to appropriate DMA channel on success or an error pointer.
