.TH "of_find_mipi_dsi_device_by_node" 9 "of_find_mipi_dsi_device_by_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_find_mipi_dsi_device_by_node \- find the MIPI DSI device matching a device tree node
.SH SYNOPSIS
.B "struct mipi_dsi_device *" of_find_mipi_dsi_device_by_node
.BI "(struct device_node *np "  ");"
.SH ARGUMENTS
.IP "np" 12
device tree node
.SH "RETURN"
A pointer to the MIPI DSI device corresponding to \fInp\fP or NULL if no
such device exists (or has not been registered yet).
