.TH "of_fpga_region_notify" 9 "of_fpga_region_notify" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_fpga_region_notify \- reconfig notifier for dynamic DT changes
.SH SYNOPSIS
.B "int" of_fpga_region_notify
.BI "(struct notifier_block *nb "  ","
.BI "unsigned long action "  ","
.BI "void *arg "  ");"
.SH ARGUMENTS
.IP "nb" 12
notifier block
.IP "action" 12
notifier action
.IP "arg" 12
reconfig data
.SH "DESCRIPTION"
This notifier handles programming a FPGA when a "firmware-name" property is
added to a fpga-region.

Returns NOTIFY_OK or error if FPGA programming fails.
