.TH "of_get_dram_timings" 9 "of_get_dram_timings" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_get_dram_timings \- helper function for parsing DT settings for DRAM
.SH SYNOPSIS
.B "int" of_get_dram_timings
.BI "(struct exynos5_dmc *dmc "  ");"
.SH ARGUMENTS
.IP "dmc" 12
device for which the frequency is going to be set
.SH "DESCRIPTION"
The function parses DT entries with DRAM information.
