.TH "of_genpd_del_provider" 9 "of_genpd_del_provider" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_genpd_del_provider \- Remove a previously registered PM domain provider
.SH SYNOPSIS
.B "void" of_genpd_del_provider
.BI "(struct device_node *np "  ");"
.SH ARGUMENTS
.IP "np" 12
Device node pointer associated with the PM domain provider
