.TH "of_get_parent" 9 "of_get_parent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_get_parent \- Get a node's parent if any
.SH SYNOPSIS
.B "struct device_node *" of_get_parent
.BI "(const struct device_node *node "  ");"
.SH ARGUMENTS
.IP "node" 12
Node to get parent

Returns a node pointer with refcount incremented, use
\fBof_node_put\fP on it when done.
