.TH "of_genpd_add_subdomain" 9 "of_genpd_add_subdomain" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_genpd_add_subdomain \- Add a subdomain to an I/O PM domain.
.SH SYNOPSIS
.B "int" of_genpd_add_subdomain
.BI "(struct of_phandle_args *parent_spec "  ","
.BI "struct of_phandle_args *subdomain_spec "  ");"
.SH ARGUMENTS
.IP "parent_spec" 12
OF phandle args to use for parent PM domain look-up
.IP "subdomain_spec" 12
OF phandle args to use for subdomain look-up
.SH "DESCRIPTION"
Looks-up a parent PM domain and subdomain based upon phandle args
provided and adds the subdomain to the parent PM domain. Returns a
negative error code on failure.
