.TH "of_genpd_remove_last" 9 "of_genpd_remove_last" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_genpd_remove_last \- Remove the last PM domain registered for a provider
.SH SYNOPSIS
.B "struct generic_pm_domain *" of_genpd_remove_last
.BI "(struct device_node *np "  ");"
.SH ARGUMENTS
.IP "np" 12
-- undescribed --
.SH "DESCRIPTION"
Find the last PM domain that was added by a particular provider and
remove this PM domain from the list of PM domains. The provider is
identified by the 'provider' device structure that is passed. The PM
domain will only be removed, if the provider associated with domain
has been removed.

Returns a valid pointer to struct generic_pm_domain on success or
\fBERR_PTR\fP on failure.
