.TH "of_parse_phandle_with_fixed_args" 9 "of_parse_phandle_with_fixed_args" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_parse_phandle_with_fixed_args \- Find a node pointed by phandle in a list
.SH SYNOPSIS
.B "int" of_parse_phandle_with_fixed_args
.BI "(const struct device_node *np "  ","
.BI "const char *list_name "  ","
.BI "int cell_count "  ","
.BI "int index "  ","
.BI "struct of_phandle_args *out_args "  ");"
.SH ARGUMENTS
.IP "np" 12
pointer to a device tree node containing a list
.IP "list_name" 12
property name that contains a list
.IP "cell_count" 12
number of argument cells following the phandle
.IP "index" 12
index of a phandle to parse out
.IP "out_args" 12
optional pointer to output arguments structure (will be filled)
.SH "DESCRIPTION"
This function is useful to parse lists of phandles and their arguments.
Returns 0 on success and fills out_args, on error returns appropriate
errno value.

Caller is responsible to call \fBof_node_put\fP on the returned out_args->np
pointer.

phandle1: node1 {
}

phandle2: node2 {
}

node3 {
list = <\fIphandle1\fP 0 2 \fIphandle2\fP 2 3>;
}

To get a device_node of the `node2' node you may call this:
of_parse_phandle_with_fixed_args(node3, "list", 2, 1, \fIargs\fP);
.SH "EXAMPLE"
