.TH "of_scan_flat_dt_subnodes" 9 "of_scan_flat_dt_subnodes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_scan_flat_dt_subnodes \- scan sub-nodes of a node call callback on each.
.SH SYNOPSIS
.B "int" of_scan_flat_dt_subnodes
.BI "(unsigned long parent "  ","
.BI "int (*it)(unsigned long node, const char *uname, void *data) "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "parent" 12
-- undescribed --
.IP "it" 12
callback function
.IP "data" 12
context data pointer
.SH "DESCRIPTION"
This function is used to scan sub-nodes of a node.
