.TH "omac1_aes_128" 9 "omac1_aes_128" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omac1_aes_128 \- One-Key CBC MAC (OMAC1) hash with AES-128 (aka AES-CMAC)
.SH SYNOPSIS
.B "int" omac1_aes_128
.BI "(u8 *key "  ","
.BI "u8 *data "  ","
.BI "size_t data_len "  ","
.BI "u8 *mac "  ");"
.SH ARGUMENTS
.IP "key" 12
128-bit key for the hash operation
.IP "data" 12
Data buffer for which a MAC is determined
.IP "data_len" 12
Length of data buffer in bytes
.IP "mac" 12
Buffer for MAC (128 bits, i.e., 16 bytes)
.SH "RETURN"
0 on success, -1 on failure
.SH "DESCRIPTION"
This is a mode for using block cipher (AES in this case) for authentication.
OMAC1 was standardized with the name CMAC by NIST in a Special Publication
(SP) 800-38B.
