.TH "omap_iommu_domain_deactivate" 9 "omap_iommu_domain_deactivate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_iommu_domain_deactivate \- deactivate attached iommu devices
.SH SYNOPSIS
.B "int" omap_iommu_domain_deactivate
.BI "(struct iommu_domain *domain "  ");"
.SH ARGUMENTS
.IP "domain" 12
iommu domain attached to the target iommu device
.SH "DESCRIPTION"
This API allows the client devices of IOMMU devices to suspend
the IOMMUs they control at runtime, after they are idled and
suspended all activity. System Suspend will leverage the PM
driver late callbacks.
