.TH "omap2_clk_deny_idle" 9 "omap2_clk_deny_idle" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap2_clk_deny_idle \- disable autoidle on an OMAP clock
.SH SYNOPSIS
.B "int" omap2_clk_deny_idle
.BI "(struct clk *clk "  ");"
.SH ARGUMENTS
.IP "clk" 12
struct clk * to disable autoidle for
.SH "DESCRIPTION"
Disable autoidle on an OMAP clock.
