.TH "omap_register_i2c_bus" 9 "omap_register_i2c_bus" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_register_i2c_bus \- register I2C bus with device descriptors
.SH SYNOPSIS
.B "int" omap_register_i2c_bus
.BI "(int bus_id "  ","
.BI "u32 clkrate "  ","
.BI "struct i2c_board_info const *info "  ","
.BI "unsigned len "  ");"
.SH ARGUMENTS
.IP "bus_id" 12
bus id counting from number 1
.IP "clkrate" 12
clock rate of the bus in kHz
.IP "info" 12
pointer into I2C device descriptor table or NULL
.IP "len" 12
number of descriptors in the table
.SH "DESCRIPTION"
Returns 0 on success or an error code.
