.TH "omap_device_idle" 9 "omap_device_idle" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_device_idle \- idle an omap_device
.SH SYNOPSIS
.B "int" omap_device_idle
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
The platform_device (omap_device) to idle
.SH "DESCRIPTION"
Idle omap_device \fIod\fP.  Device drivers call this function indirectly
via pm_runtime_put*().  Returns -EINVAL if the omap_device is not
currently enabled, or passes along the return value of
\fB_omap_device_idle_hwmods\fP.
