.TH "omap2_prm_is_hardreset_asserted" 9 "omap2_prm_is_hardreset_asserted" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap2_prm_is_hardreset_asserted \- read the HW reset line state of submodules contained in the hwmod module
.SH SYNOPSIS
.B "int" omap2_prm_is_hardreset_asserted
.BI "(u8 shift "  ","
.BI "u8 part "  ","
.BI "s16 prm_mod "  ","
.BI "u16 offset "  ");"
.SH ARGUMENTS
.IP "shift" 12
register bit shift corresponding to the reset line to check
.IP "part" 12
PRM partition, ignored for OMAP2
.IP "prm_mod" 12
PRM submodule base (e.g. CORE_MOD)
.IP "offset" 12
register offset, ignored for OMAP2
.SH "DESCRIPTION"
Returns 1 if the (sub)module hardreset line is currently asserted,
0 if the (sub)module hardreset line is not currently asserted, or
-EINVAL if called while running on a non-OMAP2/3 chip.
