.TH "omap2_dflt_clk_disable" 9 "omap2_dflt_clk_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap2_dflt_clk_disable \- disable a clock in the hardware
.SH SYNOPSIS
.B "void" omap2_dflt_clk_disable
.BI "(struct clk_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
struct clk_hw * of the clock to disable
.SH "DESCRIPTION"
Disable the clock \fIhw\fP in the hardware, and call into the OMAP
clockdomain code to "disable" the corresponding clockdomain if all
clocks/hwmods in that clockdomain are now disabled.  No return
value.
