.TH "omap_enable_hwecc" 9 "omap_enable_hwecc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_enable_hwecc \- This function enables the hardware ecc functionality
.SH SYNOPSIS
.B "void" omap_enable_hwecc
.BI "(struct nand_chip *chip "  ","
.BI "int mode "  ");"
.SH ARGUMENTS
.IP "chip" 12
NAND chip object
.IP "mode" 12
Read/Write mode
