.TH "omap2_sdrc_init" 9 "omap2_sdrc_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap2_sdrc_init \- initialize SMS, SDRC devices on boot @sdrc_cs[01]: pointers to a null-terminated list of struct omap_sdrc_params Support for 2 chip selects timings
.SH SYNOPSIS
.B "void" omap2_sdrc_init
.BI "(struct omap_sdrc_params *sdrc_cs0 "  ","
.BI "struct omap_sdrc_params *sdrc_cs1 "  ");"
.SH ARGUMENTS
.IP "sdrc_cs0" 12
-- undescribed --
.IP "sdrc_cs1" 12
-- undescribed --
.SH "DESCRIPTION"

Turn on smart idle modes for SDRAM scheduler and controller.
Program a known-good configuration for the SDRC to deal with buggy
bootloaders.
