.TH "omap_wait" 9 "omap_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_wait \- wait until the command is done
.SH SYNOPSIS
.B "int" omap_wait
.BI "(struct nand_chip *this "  ");"
.SH ARGUMENTS
.IP "this" 12
NAND Chip structure
.SH "DESCRIPTION"
Wait function is called during Program and erase operations and
the way it is called from MTD layer, we should wait till the NAND
chip is ready after the programming/erase operation has completed.

Erase can take up to 400ms and program up to 20ms according to
general NAND and SmartMedia specs
