.TH "omap_vc_i2c_init" 9 "omap_vc_i2c_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_vc_i2c_init \- initialize I2C interface to PMIC
.SH SYNOPSIS
.B "void" omap_vc_i2c_init
.BI "(struct voltagedomain *voltdm "  ");"
.SH ARGUMENTS
.IP "voltdm" 12
voltage domain containing VC data
.SH "DESCRIPTION"
Use PMIC supplied settings for I2C high-speed mode and
master code (if set) and program the VC I2C configuration
register.

The VC I2C configuration is common to all VC channels,
so this function only configures I2C for the first VC
channel registers.  All other VC channels will use the
same configuration.
