.TH "omap3_dpll4_set_rate_and_parent" 9 "omap3_dpll4_set_rate_and_parent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap3_dpll4_set_rate_and_parent \- set rate and parent for omap3 per-dpll
.SH SYNOPSIS
.B "int" omap3_dpll4_set_rate_and_parent
.BI "(struct clk_hw *hw "  ","
.BI "unsigned long rate "  ","
.BI "unsigned long parent_rate "  ","
.BI "u8 index "  ");"
.SH ARGUMENTS
.IP "hw" 12
clock to change
.IP "rate" 12
target rate for clock
.IP "parent_rate" 12
rate of the parent clock
.IP "index" 12
parent index, 0 - reference clock, 1 - bypass clock
.SH "DESCRIPTION"
Check if the current SoC support the per-dpll reprogram operation
or not, and then do the rate + parent change if supported. Returns
-EINVAL if not supported, 0 for success, and potential error codes
from the clock rate change.
