.TH "omap_hwmod_lookup" 9 "omap_hwmod_lookup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_hwmod_lookup \- look up a registered omap_hwmod by name
.SH SYNOPSIS
.B "struct omap_hwmod *" omap_hwmod_lookup
.BI "(const char *name "  ");"
.SH ARGUMENTS
.IP "name" 12
name of the omap_hwmod to look up
.SH "DESCRIPTION"
Given a \fIname\fP of an omap_hwmod, return a pointer to the registered
struct omap_hwmod *, or NULL upon error.
