.TH "omap_prefetch_enable" 9 "omap_prefetch_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_prefetch_enable \- configures and starts prefetch transfer
.SH SYNOPSIS
.B "int" omap_prefetch_enable
.BI "(int cs "  ","
.BI "int fifo_th "  ","
.BI "int dma_mode "  ","
.BI "unsigned int u32_count "  ","
.BI "int is_write "  ","
.BI "struct omap_nand_info *info "  ");"
.SH ARGUMENTS
.IP "cs" 12
cs (chip select) number
.IP "fifo_th" 12
fifo threshold to be used for read/ write
.IP "dma_mode" 12
dma mode enable (1) or disable (0)
.IP "u32_count" 12
number of bytes to be transferred
.IP "is_write" 12
prefetch read(0) or write post(1) mode
.IP "info" 12
NAND device structure containing platform data
