.TH "omap_rproc_get_timer_irq" 9 "omap_rproc_get_timer_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_rproc_get_timer_irq \- get the irq for a timer
.SH SYNOPSIS
.B "int" omap_rproc_get_timer_irq
.BI "(struct omap_rproc_timer *timer "  ");"
.SH ARGUMENTS
.IP "timer" 12
handle to a OMAP rproc timer
.SH "DESCRIPTION"
This function is used to get the irq associated with a watchdog timer. The
function is called by the OMAP remoteproc driver to register a interrupt
handler to handle watchdog events on the remote processor.
.SH "RETURN"
irq id on success, otherwise a failure as returned by DMTimer ops
