.TH "omap4_pm_init_early" 9 "omap4_pm_init_early" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap4_pm_init_early \- Does early initialization necessary for OMAP4+ devices
.SH SYNOPSIS
.B "int" omap4_pm_init_early
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Initializes basic stuff for power management functionality.
