.TH "omap2xxx_prm_clear_mod_irqs" 9 "omap2xxx_prm_clear_mod_irqs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap2xxx_prm_clear_mod_irqs \- clear wakeup status bits for a module
.SH SYNOPSIS
.B "int" omap2xxx_prm_clear_mod_irqs
.BI "(s16 module "  ","
.BI "u8 regs "  ","
.BI "u32 wkst_mask "  ");"
.SH ARGUMENTS
.IP "module" 12
PRM module to clear wakeups from
.IP "regs" 12
register offset to clear
.IP "wkst_mask" 12
wakeup status mask to clear
.SH "DESCRIPTION"
Clears wakeup status bits for a given module, so that the device can
re-enter idle.
