.TH "omap_vc_calc_vsel" 9 "omap_vc_calc_vsel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_vc_calc_vsel \- calculate vsel value for a channel
.SH SYNOPSIS
.B "u8" omap_vc_calc_vsel
.BI "(struct voltagedomain *voltdm "  ","
.BI "u32 uvolt "  ");"
.SH ARGUMENTS
.IP "voltdm" 12
channel to calculate value for
.IP "uvolt" 12
microvolt value to convert to vsel
.SH "DESCRIPTION"
Converts a microvolt value to vsel value for the used PMIC.
This checks whether the microvolt value is out of bounds, and
adjusts the value accordingly. If unsupported value detected,
warning is thrown.
