.TH "omap_pm_setup_sr_i2c_pcb_length" 9 "omap_pm_setup_sr_i2c_pcb_length" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_pm_setup_sr_i2c_pcb_length \- set length of SR I2C traces on PCB
.SH SYNOPSIS
.B "void" omap_pm_setup_sr_i2c_pcb_length
.BI "(u32 mm "  ");"
.SH ARGUMENTS
.IP "mm" 12
length of the PCB trace in millimetres
.SH "DESCRIPTION"
Sets the PCB trace length for the I2C channel. By default uses 63mm.
This is needed for properly calculating the capacitance value for
the PCB trace, and for setting the SR I2C channel timing parameters.
