.TH "omap4_prminst_assert_hardreset" 9 "omap4_prminst_assert_hardreset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap4_prminst_assert_hardreset \- assert the HW reset line of a submodule
.SH SYNOPSIS
.B "int" omap4_prminst_assert_hardreset
.BI "(u8 shift "  ","
.BI "u8 part "  ","
.BI "s16 inst "  ","
.BI "u16 rstctrl_offs "  ");"
.SH ARGUMENTS
.IP "shift" 12
register bit shift corresponding to the reset line to assert
.IP "part" 12
-- undescribed --
.IP "inst" 12
-- undescribed --
.IP "rstctrl_offs" 12
-- undescribed --
.SH "DESCRIPTION"
Some IPs like dsp, ipu or iva contain processors that require an HW
reset line to be asserted / deasserted in order to fully enable the
IP.  These modules may have multiple hard-reset lines that reset
different 'submodules' inside the IP block.  This function will
place the submodule into reset.  Returns 0 upon success or -EINVAL
upon an argument error.
