.TH "onebit_depop_mute_stage" 9 "onebit_depop_mute_stage" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
onebit_depop_mute_stage \- auto depop in mute stage.
.SH SYNOPSIS
.B "void" onebit_depop_mute_stage
.BI "(struct snd_soc_component *component "  ","
.BI "int enable "  ");"
.SH ARGUMENTS
.IP "component" 12
ASoC component
.IP "enable" 12
mute/unmute
.SH "DESCRIPTION"
When mute/unmute headphone, the depop sequence is done by hardware.
