.TH "onenand_update_bufferram" 9 "onenand_update_bufferram" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
onenand_update_bufferram \- [GENERIC] Update BufferRAM information
.SH SYNOPSIS
.B "void" onenand_update_bufferram
.BI "(struct mtd_info *mtd "  ","
.BI "loff_t addr "  ","
.BI "int valid "  ");"
.SH ARGUMENTS
.IP "mtd" 12
MTD data structure
.IP "addr" 12
address to update
.IP "valid" 12
valid flag
.SH "DESCRIPTION"
Update BufferRAM information
