.TH "onenand_memory_bbt" 9 "onenand_memory_bbt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
onenand_memory_bbt \- [GENERIC] create a memory based bad block table
.SH SYNOPSIS
.B "int" onenand_memory_bbt
.BI "(struct mtd_info *mtd "  ","
.BI "struct nand_bbt_descr *bd "  ");"
.SH ARGUMENTS
.IP "mtd" 12
MTD device structure
.IP "bd" 12
descriptor for the good/bad block search pattern
.SH "DESCRIPTION"
The function creates a memory based bbt by scanning the device
for manufacturer / software marked good / bad blocks
