.TH "onenand_unlock" 9 "onenand_unlock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
onenand_unlock \- [MTD Interface] Unlock block(s)
.SH SYNOPSIS
.B "int" onenand_unlock
.BI "(struct mtd_info *mtd "  ","
.BI "loff_t ofs "  ","
.BI "uint64_t len "  ");"
.SH ARGUMENTS
.IP "mtd" 12
MTD device structure
.IP "ofs" 12
offset relative to mtd start
.IP "len" 12
number of bytes to unlock
.SH "DESCRIPTION"
Unlock one or more blocks
