.TH "optee_from_msg_param" 9 "optee_from_msg_param" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
optee_from_msg_param \- convert from OPTEE_MSG parameters to struct tee_param
.SH SYNOPSIS
.B "int" optee_from_msg_param
.BI "(struct tee_param *params "  ","
.BI "size_t num_params "  ","
.BI "const struct optee_msg_param *msg_params "  ");"
.SH ARGUMENTS
.IP "params" 12
subsystem internal parameter representation
.IP "num_params" 12
number of elements in the parameter arrays
.IP "msg_params" 12
OPTEE_MSG parameters
Returns 0 on success or <0 on failure
