.TH "optidma_unlock" 9 "optidma_unlock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
optidma_unlock \- unlock control registers
.SH SYNOPSIS
.B "void" optidma_unlock
.BI "(struct ata_port *ap "  ");"
.SH ARGUMENTS
.IP "ap" 12
ATA port

Unlock the control register block for this adapter. Registers must not
be unlocked in a situation where libata might look at them.
