.TH "overlay_merge" 9 "overlay_merge" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
overlay_merge \- Merge an overlay into its base device tree
.SH SYNOPSIS
.B "int" overlay_merge
.BI "(void *fdt "  ","
.BI "void *fdto "  ");"
.SH ARGUMENTS
.IP "fdt" 12
Base Device Tree blob
.IP "fdto" 12
Device tree overlay blob
.SH "DESCRIPTION"
\fBoverlay_merge\fP merges an overlay into its base device tree.

This is the next to last step in the device tree overlay application
process, when all the phandles have been adjusted and resolved and
you just have to merge overlay into the base device tree.
.SH "RETURN"
0 on success
Negative error code on failure
