.TH "p1022ds_set_pixel_clock" 9 "p1022ds_set_pixel_clock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
p1022ds_set_pixel_clock \- program the DIU's clock
.SH SYNOPSIS
.B "void" p1022ds_set_pixel_clock
.BI "(unsigned int pixclock "  ");"
.SH ARGUMENTS
.IP "pixclock" 12
the wavelength, in picoseconds, of the clock
