.TH "p1022_rdk_exit" 9 "p1022_rdk_exit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
p1022_rdk_exit \- machine driver exit
.SH SYNOPSIS
.B "void __exit" p1022_rdk_exit
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This function is called when this driver is unloaded.
