.TH "p9_virtio_probe" 9 "p9_virtio_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
p9_virtio_probe \- probe for existence of 9P virtio channels
.SH SYNOPSIS
.B "int" p9_virtio_probe
.BI "(struct virtio_device *vdev "  ");"
.SH ARGUMENTS
.IP "vdev" 12
virtio device to probe
.SH "DESCRIPTION"
This probes for existing virtio channels.
