.TH "pack_inode" 9 "pack_inode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pack_inode \- pack an inode node.
.SH SYNOPSIS
.B "void" pack_inode
.BI "(struct ubifs_info *c "  ","
.BI "struct ubifs_ino_node *ino "  ","
.BI "const struct inode *inode "  ","
.BI "int last "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "ino" 12
buffer in which to pack inode node
.IP "inode" 12
inode to pack
.IP "last" 12
indicates the last node of the group
