.TH "padata_set_cpumask" 9 "padata_set_cpumask" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
padata_set_cpumask \- Sets specified by @cpumask_type cpumask to the value equivalent to @cpumask.
.SH SYNOPSIS
.B "int" padata_set_cpumask
.BI "(struct padata_instance *pinst "  ","
.BI "int cpumask_type "  ","
.BI "cpumask_var_t cpumask "  ");"
.SH ARGUMENTS
.IP "pinst" 12
padata instance
.IP "cpumask_type" 12
PADATA_CPU_SERIAL or PADATA_CPU_PARALLEL corresponding
to parallel and serial cpumasks respectively.
.IP "cpumask" 12
the cpumask to use
.SH "RETURN"
0 on success or negative error code
