.TH "parman_prio_fini" 9 "parman_prio_fini" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parman_prio_fini \- finalizes use of parman priority chunk
.SH SYNOPSIS
.B "void" parman_prio_fini
.BI "(struct parman_prio *prio "  ");"
.SH ARGUMENTS
.IP "prio" 12
parman prio structure
.SH "NOTE"
all locking must be provided by the caller.
