.TH "parport_ip32_fifo_write_block_dma" 9 "parport_ip32_fifo_write_block_dma" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parport_ip32_fifo_write_block_dma \- write a block of data (DMA mode)
.SH SYNOPSIS
.B "size_t" parport_ip32_fifo_write_block_dma
.BI "(struct parport *p "  ","
.BI "const void *buf "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "p" 12
pointer to \fIstruct parport\fP
.IP "buf" 12
buffer of data to write
.IP "len" 12
length of buffer \fIbuf\fP
.SH "DESCRIPTION"
Uses DMA to write the contents of the buffer \fIbuf\fP into the parallel port
FIFO.  Returns the number of bytes that were actually written.  The
parallel port must be correctly initialized before calling
\fBparport_ip32_fifo_write_block_dma\fP.
