.TH "parport_ip32_dma_register" 9 "parport_ip32_dma_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parport_ip32_dma_register \- initialize DMA engine
.SH SYNOPSIS
.B "int" parport_ip32_dma_register
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Returns zero for success.
