.TH "parport_find_base" 9 "parport_find_base" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parport_find_base \- find a parallel port by base address
.SH SYNOPSIS
.B "struct parport *" parport_find_base
.BI "(unsigned long base "  ");"
.SH ARGUMENTS
.IP "base" 12
base I/O address

This returns the parallel port with the specified base
address, or NULL if there is none.

There is an implicit \fBparport_get_port\fP done already; to throw
away the reference to the port that \fBparport_find_base\fP
gives you, use \fBparport_put_port\fP.
