.TH "parport_ip32_data_reverse" 9 "parport_ip32_data_reverse" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parport_ip32_data_reverse \- enable peripheral-to-host communications
.SH SYNOPSIS
.B "void" parport_ip32_data_reverse
.BI "(struct parport *p "  ");"
.SH ARGUMENTS
.IP "p" 12
pointer to \fIstruct parport\fP
.SH "DESCRIPTION"
Place the data bus in a high impedance state, if \fIp->modes\fP has the
PARPORT_MODE_TRISTATE bit set.
