.TH "parport_ip32_fifo_write_block" 9 "parport_ip32_fifo_write_block" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parport_ip32_fifo_write_block \- write a block of data
.SH SYNOPSIS
.B "size_t" parport_ip32_fifo_write_block
.BI "(struct parport *p "  ","
.BI "const void *buf "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "p" 12
pointer to \fIstruct parport\fP
.IP "buf" 12
buffer of data to write
.IP "len" 12
length of buffer \fIbuf\fP
.SH "DESCRIPTION"
Uses PIO or DMA to write the contents of the buffer \fIbuf\fP into the parallel
p FIFO.  Returns the number of bytes that were actually written.
