.TH "parse_feature" 9 "parse_feature" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parse_feature \- parse a feature on given device feature list
.SH SYNOPSIS
.B "int" parse_feature
.BI "(struct build_feature_devs_info *binfo "  ","
.BI "resource_size_t ofst "  ");"
.SH ARGUMENTS
.IP "binfo" 12
build feature devices information.
.IP "ofst" 12
offset to current FIU header
