.TH "path_get" 9 "path_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
path_get \- get a reference to a path
.SH SYNOPSIS
.B "void" path_get
.BI "(const struct path *path "  ");"
.SH ARGUMENTS
.IP "path" 12
path to get the reference to
.SH "DESCRIPTION"
Given a path increment the reference count to the dentry and the vfsmount.
