.TH "pch_udc_pcd_queue" 9 "pch_udc_pcd_queue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_udc_pcd_queue \- This function queues a request packet. It is called by gadget driver
.SH SYNOPSIS
.B "int" pch_udc_pcd_queue
.BI "(struct usb_ep *usbep "  ","
.BI "struct usb_request *usbreq "  ","
.BI "gfp_t gfp "  ");"
.SH ARGUMENTS
.IP "usbep" 12
Reference to the USB endpoint structure
.IP "usbreq" 12
Reference to the USB request
.IP "gfp" 12
Flag to be used while mapping the data buffer
.SH "DESCRIPTION"
Return codes:
0:                      Success
linux error number:     Failure
