.TH "pch_udc_pcd_init" 9 "pch_udc_pcd_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_udc_pcd_init \- This API initializes the driver structure
.SH SYNOPSIS
.B "int" pch_udc_pcd_init
.BI "(struct pch_udc_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Reference to the driver structure
.SH "DESCRIPTION"
Return codes:
0:              Success
-ERRNO:        All kind of errors when retrieving VBUS GPIO
