.TH "pch_gbe_reset_task" 9 "pch_gbe_reset_task" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_gbe_reset_task \- Reset processing at the time of transmission timeout
.SH SYNOPSIS
.B "void" pch_gbe_reset_task
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
Pointer of board private structure
