.TH "pch_gbe_mac_mar_set" 9 "pch_gbe_mac_mar_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_gbe_mac_mar_set \- Set MAC address register
.SH SYNOPSIS
.B "void" pch_gbe_mac_mar_set
.BI "(struct pch_gbe_hw *hw "  ","
.BI "u8 * addr "  ","
.BI "u32 index "  ");"
.SH ARGUMENTS
.IP "hw" 12
Pointer to the HW structure
.IP "addr" 12
Pointer to the MAC address
.IP "index" 12
MAC address array register
