.TH "pch_gbe_clean_tx_ring" 9 "pch_gbe_clean_tx_ring" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_gbe_clean_tx_ring \- Free Tx Buffers
.SH SYNOPSIS
.B "void" pch_gbe_clean_tx_ring
.BI "(struct pch_gbe_adapter *adapter "  ","
.BI "struct pch_gbe_tx_ring *tx_ring "  ");"
.SH ARGUMENTS
.IP "adapter" 12
Board private structure
.IP "tx_ring" 12
Ring to be cleaned
