.TH "pch_spi_clear_fifo" 9 "pch_spi_clear_fifo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_spi_clear_fifo \- Clears the Transmit and Receive FIFOs
.SH SYNOPSIS
.B "void" pch_spi_clear_fifo
.BI "(struct spi_master *master "  ");"
.SH ARGUMENTS
.IP "master" 12
Pointer to struct spi_master.
