.TH "pch_udc_ep_clear_stall" 9 "pch_udc_ep_clear_stall" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_udc_ep_clear_stall \- Clear the stall of endpoint
.SH SYNOPSIS
.B "void" pch_udc_ep_clear_stall
.BI "(struct pch_udc_ep *ep "  ");"
.SH ARGUMENTS
.IP "ep" 12
Reference to structure of type pch_udc_ep_regs
