.TH "pci_real_dma_dev" 9 "pci_real_dma_dev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_real_dma_dev \- Get PCI DMA device for PCI device
.SH SYNOPSIS
.B "struct pci_dev *" pci_real_dma_dev
.BI "(struct pci_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the PCI device that may have a PCI DMA alias
.SH "DESCRIPTION"
Permits the platform to provide architecture-specific functionality to
devices needing to alias DMA to another PCI device on another PCI bus. If
the PCI device is on the same bus, it is recommended to use
\fBpci_add_dma_alias\fP. This is the default implementation. Architecture
implementations can override this.
