.TH "pci_bus_set_current_state" 9 "pci_bus_set_current_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_bus_set_current_state \- Walk given bus and set current state of devices
.SH SYNOPSIS
.B "void" pci_bus_set_current_state
.BI "(struct pci_bus *bus "  ","
.BI "pci_power_t state "  ");"
.SH ARGUMENTS
.IP "bus" 12
Top bus of the subtree to walk.
.IP "state" 12
state to be set
