.TH "pci_free_p2pmem" 9 "pci_free_p2pmem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_free_p2pmem \- free peer-to-peer DMA memory
.SH SYNOPSIS
.B "void" pci_free_p2pmem
.BI "(struct pci_dev *pdev "  ","
.BI "void *addr "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "pdev" 12
the device the memory was allocated from
.IP "addr" 12
address of the memory that was allocated
.IP "size" 12
number of bytes that were allocated
