.TH "pci_pme_capable" 9 "pci_pme_capable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_pme_capable \- check the capability of PCI device to generate PME#
.SH SYNOPSIS
.B "bool" pci_pme_capable
.BI "(struct pci_dev *dev "  ","
.BI "pci_power_t state "  ");"
.SH ARGUMENTS
.IP "dev" 12
PCI device to handle.
.IP "state" 12
PCI state from which device will issue PME#.
