.TH "pci_get_rom_size" 9 "pci_get_rom_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_get_rom_size \- obtain the actual size of the ROM image
.SH SYNOPSIS
.B "size_t" pci_get_rom_size
.BI "(struct pci_dev *pdev "  ","
.BI "void __iomem *rom "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "pdev" 12
target PCI device
.IP "rom" 12
kernel virtual pointer to image of ROM
.IP "size" 12
size of PCI window
.SH "RETURN"
size of actual ROM image
.SH "DESCRIPTION"
Determine the actual length of the ROM image.
The PCI window size could be much larger than the
actual image size.
