.TH "pci_bus_error_reset" 9 "pci_bus_error_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_bus_error_reset \- reset the bridge's subordinate bus
.SH SYNOPSIS
.B "int" pci_bus_error_reset
.BI "(struct pci_dev *bridge "  ");"
.SH ARGUMENTS
.IP "bridge" 12
The parent device that connects to the bus to reset
.SH "DESCRIPTION"
This function will first try to reset the slots on this bus if the method is
available. If slot reset fails or is not available, this will fall back to a
secondary bus reset.
