.TH "pci_vpd_size" 9 "pci_vpd_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_vpd_size \- determine actual size of Vital Product Data
.SH SYNOPSIS
.B "size_t" pci_vpd_size
.BI "(struct pci_dev *dev "  ","
.BI "size_t old_size "  ");"
.SH ARGUMENTS
.IP "dev" 12
pci device struct
.IP "old_size" 12
current assumed size, also maximum allowed size
