.TH "pci_cfg_access_trylock" 9 "pci_cfg_access_trylock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_cfg_access_trylock \- try to lock PCI config reads/writes
.SH SYNOPSIS
.B "bool" pci_cfg_access_trylock
.BI "(struct pci_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
pci device struct
.SH "DESCRIPTION"
Same as pci_cfg_access_lock, but will return 0 if access is
already locked, 1 otherwise. This function can be used from
atomic contexts.
