.TH "pci_restore_vc_state" 9 "pci_restore_vc_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_restore_vc_state \- Restore VC state from save buffer
.SH SYNOPSIS
.B "void" pci_restore_vc_state
.BI "(struct pci_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device
.SH "DESCRIPTION"
For each type of VC capability, VC/VC9/MFVC, find the capability and
restore it from the previously saved buffer.
