.TH "pci_find_ext_capability" 9 "pci_find_ext_capability" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_find_ext_capability \- Find an extended capability
.SH SYNOPSIS
.B "u16" pci_find_ext_capability
.BI "(struct pci_dev *dev "  ","
.BI "int cap "  ");"
.SH ARGUMENTS
.IP "dev" 12
PCI device to query
.IP "cap" 12
capability code
.SH "DESCRIPTION"
Returns the address of the requested extended capability structure
within the device's PCI configuration space or 0 if the device does
not support it.  Possible values for \fIcap\fP include:

PCI_EXT_CAP_ID_ERR         Advanced Error Reporting
PCI_EXT_CAP_ID_VC          Virtual Channel
PCI_EXT_CAP_ID_DSN         Device Serial Number
PCI_EXT_CAP_ID_PWR         Power Budgeting
