.TH "pci_clear_mwi" 9 "pci_clear_mwi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_clear_mwi \- disables Memory-Write-Invalidate for device dev
.SH SYNOPSIS
.B "void" pci_clear_mwi
.BI "(struct pci_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the PCI device to disable
.SH "DESCRIPTION"
Disables PCI Memory-Write-Invalidate transaction on the device
