.TH "pci_pasid_features" 9 "pci_pasid_features" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_pasid_features \- Check which PASID features are supported
.SH SYNOPSIS
.B "int" pci_pasid_features
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device structure
.SH "DESCRIPTION"
Returns a negative value when no PASI capability is present.
Otherwise is returns a bitmask with supported features. Current
features reported are:
PCI_PASID_CAP_EXEC - Execute permission supported
PCI_PASID_CAP_PRIV - Privileged mode supported
