.TH "pci_enable_wake" 9 "pci_enable_wake" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_enable_wake \- change wakeup settings for a PCI device
.SH SYNOPSIS
.B "int" pci_enable_wake
.BI "(struct pci_dev *pci_dev "  ","
.BI "pci_power_t state "  ","
.BI "bool enable "  ");"
.SH ARGUMENTS
.IP "pci_dev" 12
Target device
.IP "state" 12
PCI state from which device will issue wakeup events
.IP "enable" 12
Whether or not to enable event generation
.SH "DESCRIPTION"
If \fIenable\fP is set, check \fBdevice_may_wakeup\fP for the device before calling
\fB__pci_enable_wake\fP for it.
