.TH "pci_acpi_add_bus_pm_notifier" 9 "pci_acpi_add_bus_pm_notifier" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_acpi_add_bus_pm_notifier \- Register PM notifier for root PCI bus.
.SH SYNOPSIS
.B "acpi_status" pci_acpi_add_bus_pm_notifier
.BI "(struct acpi_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
PCI root bridge ACPI device.
