.TH "pci_unmap_iospace" 9 "pci_unmap_iospace" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_unmap_iospace \- Unmap the memory mapped I/O space
.SH SYNOPSIS
.B "void" pci_unmap_iospace
.BI "(struct resource *res "  ");"
.SH ARGUMENTS
.IP "res" 12
resource to be unmapped
.SH "DESCRIPTION"
Unmap the CPU virtual address \fIres\fP from virtual address space.  Only
architectures that have memory mapped IO functions defined (and the
PCI_IOBASE value defined) should call this function.
