.TH "pcibios_disable_device" 9 "pcibios_disable_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcibios_disable_device \- disable arch specific PCI resources for device dev
.SH SYNOPSIS
.B "void" pcibios_disable_device
.BI "(struct pci_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the PCI device to disable
.SH "DESCRIPTION"
Disables architecture specific PCI resources for the device. This
is the default implementation. Architecture implementations can
override this.
