.TH "pcibios_penalize_isa_irq" 9 "pcibios_penalize_isa_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcibios_penalize_isa_irq \- penalize an ISA IRQ
.SH SYNOPSIS
.B "void" pcibios_penalize_isa_irq
.BI "(int irq "  ","
.BI "int active "  ");"
.SH ARGUMENTS
.IP "irq" 12
ISA IRQ to penalize
.IP "active" 12
IRQ active or not
.SH "DESCRIPTION"
Permits the platform to provide architecture-specific functionality when
penalizing ISA IRQs. This is the default implementation. Architecture
implementations can override this.
