.TH "pcie_relaxed_ordering_enabled" 9 "pcie_relaxed_ordering_enabled" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcie_relaxed_ordering_enabled \- Probe for PCIe relaxed ordering enable
.SH SYNOPSIS
.B "bool" pcie_relaxed_ordering_enabled
.BI "(struct pci_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
PCI device to query
.SH "DESCRIPTION"
Returns true if the device has enabled relaxed ordering attribute.
