.TH "pcim_iounmap" 9 "pcim_iounmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcim_iounmap \- Managed pci_iounmap()
.SH SYNOPSIS
.B "void" pcim_iounmap
.BI "(struct pci_dev *pdev "  ","
.BI "void __iomem *addr "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device to iounmap for
.IP "addr" 12
Address to unmap
.SH "DESCRIPTION"
Managed \fBpci_iounmap\fP.  \fIaddr\fP must have been mapped using \fBpcim_iomap\fP.
