.TH "pcm_new_ver" 9 "pcm_new_ver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcm_new_ver \- Create the new version of PCM from the old version.
.SH SYNOPSIS
.B "int" pcm_new_ver
.BI "(struct soc_tplg *tplg "  ","
.BI "struct snd_soc_tplg_pcm *src "  ","
.BI "struct snd_soc_tplg_pcm **pcm "  ");"
.SH ARGUMENTS
.IP "tplg" 12
topology context
.IP "src" 12
older version of pcm as a source
.IP "pcm" 12
latest version of pcm created from the source
.SH "DESCRIPTION"
Support from vesion 4. User should free the returned pcm manually.
