.TH "pcmcia_request_io" 9 "pcmcia_request_io" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcmcia_request_io \- attempt to reserve port ranges for PCMCIA devices
.SH SYNOPSIS
.B "int" pcmcia_request_io
.BI "(struct pcmcia_device *p_dev "  ");"
.SH ARGUMENTS
.IP "p_dev" 12
the associated PCMCIA device
.SH "DESCRIPTION"
\fBpcmcia_request_io\fP attempts to reserve the IO port ranges specified in
\fIstruct pcmcia_device\fP \fIp_dev->resource\fP[0] and \fIp_dev->resource\fP[1]. The
"start" value is the requested start of the IO port resource; "end"
reflects the number of ports requested. The number of IO lines requested
is specified in \fIstruct pcmcia_device\fP \fIp_dev->io_lines\fP.
