.TH "pcpu_need_numa" 9 "pcpu_need_numa" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcpu_need_numa \- determine percpu allocation needs to consider NUMA
.SH SYNOPSIS
.B "bool" pcpu_need_numa
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

If NUMA is not configured or there is only one NUMA node available,
there is no reason to consider NUMA.  This function determines
whether percpu allocation should consider NUMA or not.
.SH "RETURN"
true if NUMA should be considered; otherwise, false.
