.TH "pcpu_alloc_bootmem" 9 "pcpu_alloc_bootmem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcpu_alloc_bootmem \- NUMA friendly alloc_bootmem wrapper for percpu
.SH SYNOPSIS
.B "void *" pcpu_alloc_bootmem
.BI "(unsigned int cpu "  ","
.BI "size_t size "  ","
.BI "size_t align "  ");"
.SH ARGUMENTS
.IP "cpu" 12
cpu to allocate for
.IP "size" 12
size allocation in bytes
.IP "align" 12
alignment
.SH "DESCRIPTION"
Allocate \fIsize\fP bytes aligned at \fIalign\fP for cpu \fIcpu\fP.  This wrapper
does the right thing for NUMA regardless of the current
configuration.
.SH "RETURN"
Pointer to the allocated area on success, NULL on failure.
