.TH "pdc_model_cpuid" 9 "pdc_model_cpuid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_model_cpuid \- Returns the CPU_ID.
.SH SYNOPSIS
.B "int" pdc_model_cpuid
.BI "(unsigned long *cpu_id "  ");"
.SH ARGUMENTS
.IP "cpu_id" 12
The return buffer.
.SH "DESCRIPTION"
Returns the CPU_ID value which uniquely identifies the cpu portion of
the processor module.
