.TH "pdc_pci_config_write" 9 "pdc_pci_config_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_pci_config_write \- read PCI config space. @hpa token from PDC to indicate which PCI device @pci_addr configuration space address to write @val value we want in the 32-bit register
.SH SYNOPSIS
.B "void" pdc_pci_config_write
.BI "(void *hpa "  ","
.BI "unsigned long cfg_addr "  ","
.BI "unsigned int val "  ");"
.SH ARGUMENTS
.IP "hpa" 12
-- undescribed --
.IP "cfg_addr" 12
-- undescribed --
.IP "val" 12
-- undescribed --
.SH "DESCRIPTION"

Write PCI Configuration space *before* linux PCI subsystem is running.
