.TH "pdc_stable_write" 9 "pdc_stable_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_stable_write \- Write data to Stable Storage.
.SH SYNOPSIS
.B "int" pdc_stable_write
.BI "(unsigned long staddr "  ","
.BI "void *memaddr "  ","
.BI "unsigned long count "  ");"
.SH ARGUMENTS
.IP "staddr" 12
Stable Storage address to access.
.IP "memaddr" 12
The memory address where Stable Storage data shall be read from.
.IP "count" 12
number of bytes to transfer. count is multiple of 4.
.SH "DESCRIPTION"
This PDC call reads count bytes from the supplied memaddr address,
and copies count bytes to the Stable Storage address staddr.
The call will fail if staddr+count > PDC_STABLE size.
