.TH "pdc_receive_one" 9 "pdc_receive_one" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_receive_one \- Receive a response message from a given SPU.
.SH SYNOPSIS
.B "int" pdc_receive_one
.BI "(struct pdc_state *pdcs "  ");"
.SH ARGUMENTS
.IP "pdcs" 12
PDC state for the SPU to receive from
.SH "DESCRIPTION"
When the return code indicates success, the response message is available in
the receive buffers provided prior to submission of the request.
.SH "RETURN"
PDC_SUCCESS if one or more receive descriptors was processed
-EAGAIN indicates that no response message is available
-EIO an error occurred
