.TH "pdc_iodc_getc" 9 "pdc_iodc_getc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_iodc_getc \- Read a character (non-blocking) from the PDC console.
.SH SYNOPSIS
.B "int" pdc_iodc_getc
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Read a character (non-blocking) from the PDC console, returns -1 if
key is not present.
