.TH "pdc_add_valid" 9 "pdc_add_valid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_add_valid \- Verify address can be accessed without causing a HPMC.
.SH SYNOPSIS
.B "int" pdc_add_valid
.BI "(unsigned long address "  ");"
.SH ARGUMENTS
.IP "address" 12
Address to be verified.
.SH "DESCRIPTION"
This PDC call attempts to read from the specified address and verifies
if the address is valid.

The return value is PDC_OK (0) in case accessing this address is valid.
