.TH "pdc_model_info" 9 "pdc_model_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_model_info \- Return model information about the processor.
.SH SYNOPSIS
.B "int" pdc_model_info
.BI "(struct pdc_model *model "  ");"
.SH ARGUMENTS
.IP "model" 12
The return buffer.
.SH "DESCRIPTION"
Returns the version numbers, identifiers, and capabilities from the processor module.
