.TH "pdr_add_lookup" 9 "pdr_add_lookup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdr_add_lookup \- register a tracking request for a PD
.SH SYNOPSIS
.B "struct pdr_service *" pdr_add_lookup
.BI "(struct pdr_handle *pdr "  ","
.BI "const char *service_name "  ","
.BI "const char *service_path "  ");"
.SH ARGUMENTS
.IP "pdr" 12
PDR client handle
.IP "service_name" 12
service name of the tracking request
.IP "service_path" 12
service path of the tracking request
.SH "DESCRIPTION"
Registering a pdr lookup allows for tracking the life cycle of the PD.
.SH "RETURN"
pdr_service object on success, ERR_PTR on failure. -EALREADY is
returned if a lookup is already in progress for the given service path.
