.TH "phy_read_mmd" 9 "phy_read_mmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_read_mmd \- Convenience function for reading a register from an MMD on a given PHY.
.SH SYNOPSIS
.B "int" phy_read_mmd
.BI "(struct phy_device *phydev "  ","
.BI "int devad "  ","
.BI "u32 regnum "  ");"
.SH ARGUMENTS
.IP "phydev" 12
The phy_device struct
.IP "devad" 12
The MMD to read from
.IP "regnum" 12
The register on the MMD to read
.SH "DESCRIPTION"
Same rules as for \fBphy_read\fP;
