.TH "phy_check_valid" 9 "phy_check_valid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_check_valid \- check if there is a valid PHY setting which matches speed, duplex, and feature mask
.SH SYNOPSIS
.B "bool" phy_check_valid
.BI "(int speed "  ","
.BI "int duplex "  ","
.BI "unsigned long *features "  ");"
.SH ARGUMENTS
.IP "speed" 12
speed to match
.IP "duplex" 12
duplex to match
.IP "features" 12
A mask of the valid settings
.SH "DESCRIPTION"
Returns true if there is a valid setting, false otherwise.
