.TH "phylink_mii_c22_pcs_an_restart" 9 "phylink_mii_c22_pcs_an_restart" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phylink_mii_c22_pcs_an_restart \- restart 802.3z autonegotiation
.SH SYNOPSIS
.B "void" phylink_mii_c22_pcs_an_restart
.BI "(struct mdio_device *pcs "  ");"
.SH ARGUMENTS
.IP "pcs" 12
a pointer to a \fIstruct mdio_device\fP.
.SH "DESCRIPTION"
Helper for MAC PCS supporting the 802.3 clause 22 register set for
clause 37 negotiation.

Restart the clause 37 negotiation with the link partner. This is
suitable to be directly plugged into the \fBmac_pcs_get_state\fP member
of the struct phylink_mac_ops structure.
