.TH "pinctrl_lookup_state" 9 "pinctrl_lookup_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pinctrl_lookup_state \- retrieves a state handle from a pinctrl handle
.SH SYNOPSIS
.B "struct pinctrl_state *" pinctrl_lookup_state
.BI "(struct pinctrl *p "  ","
.BI "const char *name "  ");"
.SH ARGUMENTS
.IP "p" 12
the pinctrl handle to retrieve the state from
.IP "name" 12
the state name to retrieve
