.TH "pinctrl_parse_index_with_args" 9 "pinctrl_parse_index_with_args" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pinctrl_parse_index_with_args \- Find a node pointed by index in a list
.SH SYNOPSIS
.B "int" pinctrl_parse_index_with_args
.BI "(const struct device_node *np "  ","
.BI "const char *list_name "  ","
.BI "int index "  ","
.BI "struct of_phandle_args *out_args "  ");"
.SH ARGUMENTS
.IP "np" 12
pointer to device node with the property
.IP "list_name" 12
property that contains the list
.IP "index" 12
index within the list
.IP "out_args" 12
entries in the list pointed by index
.SH "DESCRIPTION"
Finds the selected element in a pinctrl array consisting of an index
within the controller and a number of u32 entries specified for each
entry. Note that device_node is always for the parent pin controller device.
