.TH "pipapo_clone" 9 "pipapo_clone" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pipapo_clone \- Clone matching data to create new working copy
.SH SYNOPSIS
.B "struct nft_pipapo_match *" pipapo_clone
.BI "(struct nft_pipapo_match *old "  ");"
.SH ARGUMENTS
.IP "old" 12
Existing matching data
.SH "RETURN"
copy of matching data passed as 'old', error pointer on failure
