.TH "pipapo_step_diff" 9 "pipapo_step_diff" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pipapo_step_diff \- Check if setting @step bit in netmask would change it
.SH SYNOPSIS
.B "bool" pipapo_step_diff
.BI "(u8 *base "  ","
.BI "int step "  ","
.BI "int len "  ");"
.SH ARGUMENTS
.IP "base" 12
Mask we are expanding
.IP "step" 12
Step bit for given expansion step
.IP "len" 12
Total length of mask space (set and unset bits), bytes
.SH "DESCRIPTION"
Convenience function for mask expansion.
.SH "RETURN"
true if step bit changes mask (i.e. isn't set), false otherwise.
