.TH "platform_device_unregister" 9 "platform_device_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
platform_device_unregister \- unregister a platform-level device
.SH SYNOPSIS
.B "void" platform_device_unregister
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
platform device we're unregistering
.SH "DESCRIPTION"
Unregistration is done in 2 steps. First we release all resources
and remove it from the subsystem, then we drop reference count by
calling \fBplatform_device_put\fP.
