.TH "pldm_parse_desc_tlvs" 9 "pldm_parse_desc_tlvs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pldm_parse_desc_tlvs \- Check and skip past a number of TLVs
.SH SYNOPSIS
.B "int" pldm_parse_desc_tlvs
.BI "(struct pldmfw_priv *data "  ","
.BI "struct pldmfw_record *record "  ","
.BI "u8 desc_count "  ");"
.SH ARGUMENTS
.IP "data" 12
pointer to private data
.IP "record" 12
pointer to the record this TLV belongs too
.IP "desc_count" 12
descriptor count
.SH "DESCRIPTION"
From the current offset, read and extract the descriptor TLVs, updating the
current offset each time.
.SH "RETURN"
zero on success, or a negative error code on failure.
