.TH "pm_generic_restore_early" 9 "pm_generic_restore_early" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pm_generic_restore_early \- Generic restore_early callback for subsystems.
.SH SYNOPSIS
.B "int" pm_generic_restore_early
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to resume.
