.TH "pm_qos_flags_remove_req" 9 "pm_qos_flags_remove_req" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pm_qos_flags_remove_req \- Remove device PM QoS flags request.
.SH SYNOPSIS
.B "void" pm_qos_flags_remove_req
.BI "(struct pm_qos_flags *pqf "  ","
.BI "struct pm_qos_flags_request *req "  ");"
.SH ARGUMENTS
.IP "pqf" 12
Device PM QoS flags set to remove the request from.
.IP "req" 12
Request to remove from the set.
