.TH "pm_runtime_no_callbacks" 9 "pm_runtime_no_callbacks" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pm_runtime_no_callbacks \- Ignore runtime PM callbacks for a device.
.SH SYNOPSIS
.B "void" pm_runtime_no_callbacks
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to handle.
.SH "DESCRIPTION"
Set the power.no_callbacks flag, which tells the PM core that this
device is power-managed through its parent and has no runtime PM
callbacks of its own.  The runtime sysfs attributes will be removed.
