.TH "pmcraid_prepare_cancel_cmd" 9 "pmcraid_prepare_cancel_cmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_prepare_cancel_cmd \- prepares a command block to abort another
.SH SYNOPSIS
.B "void" pmcraid_prepare_cancel_cmd
.BI "(struct pmcraid_cmd *cmd "  ","
.BI "struct pmcraid_cmd *cmd_to_cancel "  ");"
.SH ARGUMENTS
.IP "cmd" 12
pointer to cmd that is used as cancelling command
.IP "cmd_to_cancel" 12
pointer to the command that needs to be cancelled
