.TH "pmcraid_frame_auto_sense" 9 "pmcraid_frame_auto_sense" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_frame_auto_sense \- frame fixed format sense information
.SH SYNOPSIS
.B "void" pmcraid_frame_auto_sense
.BI "(struct pmcraid_cmd *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
pointer to failing command block
.SH "DESCRIPTION"
Return value
none
