.TH "pmcraid_send_cmd" 9 "pmcraid_send_cmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_send_cmd \- fires a command to IOA
.SH SYNOPSIS
.B "void" pmcraid_send_cmd
.BI "(struct pmcraid_cmd *cmd "  ","
.BI "void (*cmd_done) (struct pmcraid_cmd *) "  ","
.BI "unsigned long timeout "  ","
.BI "void (*timeout_func) (struct timer_list *) "  ");"
.SH ARGUMENTS
.IP "cmd" 12
pointer to the command block to be fired to IOA
.IP "cmd_done" 12
command completion function, called once IOA responds
.IP "timeout" 12
timeout to wait for this command completion
.IP "timeout_func" 12
timeout handler
.SH "DESCRIPTION"

This function also sets up timeout function, and command completion
function

Return value
none
