.TH "pmcraid_reset_device" 9 "pmcraid_reset_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_reset_device \- device reset handler functions
.SH SYNOPSIS
.B "int" pmcraid_reset_device
.BI "(struct scsi_cmnd *scsi_cmd "  ","
.BI "unsigned long timeout "  ","
.BI "u8 modifier "  ");"
.SH ARGUMENTS
.IP "scsi_cmd" 12
scsi command struct
.IP "timeout" 12
-- undescribed --
.IP "modifier" 12
reset modifier indicating the reset sequence to be performed
.SH "DESCRIPTION"
This function issues a device reset to the affected device.
A LUN reset will be sent to the device first. If that does
not work, a target reset will be sent.

Return value:
SUCCESS / FAILED
