.TH "pmcraid_notify_aen" 9 "pmcraid_notify_aen" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_notify_aen \- sends event msg to user space application
.SH SYNOPSIS
.B "int" pmcraid_notify_aen
.BI "(struct pmcraid_instance *pinstance "  ","
.BI "struct pmcraid_aen_msg *aen_msg "  ","
.BI "u32 data_size "  ");"
.SH ARGUMENTS
.IP "pinstance" 12
pointer to adapter instance structure
.IP "aen_msg" 12
-- undescribed --
.IP "data_size" 12
-- undescribed --
.SH "DESCRIPTION"
Return value:
0 if success, error value in case of any failure.
