.TH "pmcraid_resume" 9 "pmcraid_resume" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_resume \- driver resume entry point PCI power management
.SH SYNOPSIS
.B "int __maybe_unused" pmcraid_resume
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device structure
.SH "DESCRIPTION"
Return Value - 0 in case of success. Error code in case of any failure
