.TH "pmcraid_timeout_handler" 9 "pmcraid_timeout_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_timeout_handler \- Timeout handler for internally generated ops
.SH SYNOPSIS
.B "void" pmcraid_timeout_handler
.BI "(struct timer_list *t "  ");"
.SH ARGUMENTS
.IP "t" 12
-- undescribed --
.SH "DESCRIPTION"
This function blocks host requests and initiates an adapter reset.

Return value:
None
