.TH "populate_enum_data" 9 "populate_enum_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
populate_enum_data \- Populate all properties of an instance under enumeration attribute
.SH SYNOPSIS
.B "int" populate_enum_data
.BI "(union acpi_object *enumeration_obj "  ","
.BI "int instance_id "  ","
.BI "struct kobject *attr_name_kobj "  ");"
.SH ARGUMENTS
.IP "enumeration_obj" 12
ACPI object with enumeration data
.IP "instance_id" 12
The instance to enumerate
.IP "attr_name_kobj" 12
The parent kernel object
