.TH "port_mmio" 9 "port_mmio" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
port_mmio \- Get the MMIO address of PDC2027x extended registers
.SH SYNOPSIS
.B "void __iomem *" port_mmio
.BI "(struct ata_port *ap "  ","
.BI "unsigned int offset "  ");"
.SH ARGUMENTS
.IP "ap" 12
Port
.IP "offset" 12
offset from mmio base
