.TH "ppc440spe_desc_init_dma01pq" 9 "ppc440spe_desc_init_dma01pq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ppc440spe_desc_init_dma01pq \- initialize the descriptors for PQ operation with DMA0/1
.SH SYNOPSIS
.B "void" ppc440spe_desc_init_dma01pq
.BI "(struct ppc440spe_adma_desc_slot *desc "  ","
.BI "int dst_cnt "  ","
.BI "int src_cnt "  ","
.BI "unsigned long flags "  ","
.BI "unsigned long op "  ");"
.SH ARGUMENTS
.IP "desc" 12
-- undescribed --
.IP "dst_cnt" 12
-- undescribed --
.IP "src_cnt" 12
-- undescribed --
.IP "flags" 12
-- undescribed --
.IP "op" 12
-- undescribed --
