.TH "ppc440spe_desc_is_aligned" 9 "ppc440spe_desc_is_aligned" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ppc440spe_desc_is_aligned \- check alignment
.SH SYNOPSIS
.B "int" ppc440spe_desc_is_aligned
.BI "(struct ppc440spe_adma_desc_slot *desc "  ","
.BI "int num_slots "  ");"
.SH ARGUMENTS
.IP "desc" 12
-- undescribed --
.IP "num_slots" 12
-- undescribed --
