.TH "ppc4xx_edac_opstate_init" 9 "ppc4xx_edac_opstate_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ppc4xx_edac_opstate_init \- initialize EDAC reporting method
.SH SYNOPSIS
.B "void" ppc4xx_edac_opstate_init
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This routine ensures that the EDAC memory controller reporting
method is mapped to a sane value as the EDAC core defines the value
to EDAC_OPSTATE_INVAL by default. We don't call the global
opstate_init as that defaults to polling and we want interrupt as
the default.
