.TH "ppc440spe_adma_issue_pending" 9 "ppc440spe_adma_issue_pending" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ppc440spe_adma_issue_pending \- flush all pending descriptors to h/w
.SH SYNOPSIS
.B "void" ppc440spe_adma_issue_pending
.BI "(struct dma_chan *chan "  ");"
.SH ARGUMENTS
.IP "chan" 12
-- undescribed --
