.TH "ppc440spe_chan_get_current_descriptor" 9 "ppc440spe_chan_get_current_descriptor" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ppc440spe_chan_get_current_descriptor \- get the currently executed descriptor
.SH SYNOPSIS
.B "u32" ppc440spe_chan_get_current_descriptor
.BI "(struct ppc440spe_adma_chan *chan "  ");"
.SH ARGUMENTS
.IP "chan" 12
-- undescribed --
