.TH "prcmu_configure_auto_pm" 9 "prcmu_configure_auto_pm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
prcmu_configure_auto_pm \- Configure autonomous power management.
.SH SYNOPSIS
.B "void" prcmu_configure_auto_pm
.BI "(struct prcmu_auto_pm_config *sleep "  ","
.BI "struct prcmu_auto_pm_config *idle "  ");"
.SH ARGUMENTS
.IP "sleep" 12
Configuration for ApSleep.
.IP "idle" 12
Configuration for ApIdle.
