.TH "prcmu_abb_write" 9 "prcmu_abb_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
prcmu_abb_write \- Write register value(s) to the ABB.
.SH SYNOPSIS
.B "int" prcmu_abb_write
.BI "(u8 slave "  ","
.BI "u8 reg "  ","
.BI "u8 *value "  ","
.BI "u8 size "  ");"
.SH ARGUMENTS
.IP "slave" 12
The I2C slave address.
.IP "reg" 12
The (start) register address.
.IP "value" 12
The value(s) to write.
.IP "size" 12
The number of registers to write.
.SH "DESCRIPTION"
Writes register value(s) to the ABB.
\fIsize\fP has to be 1 for the current firmware version.
