.TH "preempt_notifier_register" 9 "preempt_notifier_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
preempt_notifier_register \- tell me when current is being preempted & rescheduled
.SH SYNOPSIS
.B "void" preempt_notifier_register
.BI "(struct preempt_notifier *notifier "  ");"
.SH ARGUMENTS
.IP "notifier" 12
notifier struct to register
