.TH "print_eeprom_settings" 9 "print_eeprom_settings" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
print_eeprom_settings \- output the eeprom settings to the kernel log so people can see what they were.
.SH SYNOPSIS
.B "void" print_eeprom_settings
.BI "(struct NvRamType *eeprom "  ");"
.SH ARGUMENTS
.IP "eeprom" 12
The eeprom data strucutre to show details for.
