.TH "process_scan" 9 "process_scan" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
process_scan \- print out the values in SI units
.SH SYNOPSIS
.B "void" process_scan
.BI "(char *data "  ","
.BI "struct iio_channel_info *channels "  ","
.BI "int num_channels "  ");"
.SH ARGUMENTS
.IP "data" 12
pointer to the start of the scan
.IP "channels" 12
information about the channels.
.IP "num_channels" 12
number of channels
.SH "NOTE"
size_from_channelarray must have been called first
to fill the location offsets.
