.TH "property_entries_dup" 9 "property_entries_dup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
property_entries_dup \- duplicate array of properties
.SH SYNOPSIS
.B "struct property_entry *" property_entries_dup
.BI "(const struct property_entry *properties "  ");"
.SH ARGUMENTS
.IP "properties" 12
array of properties to copy
.SH "DESCRIPTION"
This function creates a deep copy of the given NULL-terminated array
of property entries.
