.TH "ps3_vuart_queue_rx_bytes" 9 "ps3_vuart_queue_rx_bytes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ps3_vuart_queue_rx_bytes \- Queue waiting bytes into the buffer list.
.SH SYNOPSIS
.B "int" ps3_vuart_queue_rx_bytes
.BI "(struct ps3_system_bus_device *dev "  ","
.BI "u64 *bytes_queued "  ");"
.SH ARGUMENTS
.IP "dev" 12
The struct ps3_system_bus_device instance.
.IP "bytes_queued" 12
Number of bytes queued to the buffer list.
.SH "DESCRIPTION"
Must be called with priv->rx_list.lock held.
