.TH "ps3_repository_read_boot_dat_info" 9 "ps3_repository_read_boot_dat_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ps3_repository_read_boot_dat_info \- Get address and size of cell_ext_os_area. address: lpar address of cell_ext_os_area
.SH SYNOPSIS
.B "int" ps3_repository_read_boot_dat_info
.BI "(u64 *lpar_addr "  ","
.BI "unsigned int *size "  ");"
.SH ARGUMENTS
.IP "lpar_addr" 12
-- undescribed --
.IP "size" 12
size of cell_ext_os_area
