.TH "ps3stor_teardown" 9 "ps3stor_teardown" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ps3stor_teardown \- Tear down a storage device after use
.SH SYNOPSIS
.B "void" ps3stor_teardown
.BI "(struct ps3_storage_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Pointer to a struct ps3_storage_device
