.TH "pseries_suspend_begin" 9 "pseries_suspend_begin" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pseries_suspend_begin \- First phase of hibernation
.SH SYNOPSIS
.B "int" pseries_suspend_begin
.BI "(u64 stream_id "  ");"
.SH ARGUMENTS
.IP "stream_id" 12
-- undescribed --
.SH "DESCRIPTION"

Check to ensure we are in a valid state to hibernate

Return value:
0 on success / other on failure
