.TH "pvrdma_alloc_pd" 9 "pvrdma_alloc_pd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pvrdma_alloc_pd \- allocate protection domain
.SH SYNOPSIS
.B "int" pvrdma_alloc_pd
.BI "(struct ib_pd *ibpd "  ","
.BI "struct ib_udata *udata "  ");"
.SH ARGUMENTS
.IP "ibpd" 12
PD pointer
.IP "udata" 12
user data
.SH "RETURN"
the ib_pd protection domain pointer on success, otherwise errno.
