.TH "pwrdm_get_mem_bank_count" 9 "pwrdm_get_mem_bank_count" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pwrdm_get_mem_bank_count \- get number of memory banks in this powerdomain
.SH SYNOPSIS
.B "int" pwrdm_get_mem_bank_count
.BI "(struct powerdomain *pwrdm "  ");"
.SH ARGUMENTS
.IP "pwrdm" 12
struct powerdomain *
.SH "DESCRIPTION"
Return the number of controllable memory banks in powerdomain \fIpwrdm\fP,
starting with 1.  Returns -EINVAL if the powerdomain pointer is null.
