.TH "pxa_ep_enable" 9 "pxa_ep_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pxa_ep_enable \- Enables usb endpoint
.SH SYNOPSIS
.B "int" pxa_ep_enable
.BI "(struct usb_ep *_ep "  ","
.BI "const struct usb_endpoint_descriptor *desc "  ");"
.SH ARGUMENTS
.IP "_ep" 12
usb endpoint
.IP "desc" 12
usb endpoint descriptor
.SH "DESCRIPTION"
Nothing much to do here, as ep configuration is done once and for all
before udc is enabled. After udc enable, no physical endpoint configuration
can be changed.
Function makes sanity checks and flushes the endpoint.
