.TH "q6asm_read" 9 "q6asm_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
q6asm_read \- read data of period size from audio client
.SH SYNOPSIS
.B "int" q6asm_read
.BI "(struct audio_client *ac "  ","
.BI "uint32_t stream_id "  ");"
.SH ARGUMENTS
.IP "ac" 12
audio client pointer
.IP "stream_id" 12
stream id
.SH "RETURN"
Will be an negative value on error or zero on success
