.TH "qcom_smem_virt_to_phys" 9 "qcom_smem_virt_to_phys" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qcom_smem_virt_to_phys \- return the physical address associated with an smem item pointer (previously returned by qcom_smem_get()
.SH SYNOPSIS
.B "phys_addr_t" qcom_smem_virt_to_phys
.BI "(void *p "  ");"
.SH ARGUMENTS
.IP "p" 12
the virtual address to convert
.SH "DESCRIPTION"
Returns 0 if the pointer provided is not within any smem region.
