.TH "qcom_pdc_gic_set_type" 9 "qcom_pdc_gic_set_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qcom_pdc_gic_set_type \- Configure PDC for the interrupt
.SH SYNOPSIS
.B "int" qcom_pdc_gic_set_type
.BI "(struct irq_data *d "  ","
.BI "unsigned int type "  ");"
.SH ARGUMENTS
.IP "d" 12
the interrupt data
.IP "type" 12
the interrupt type
.SH "DESCRIPTION"
If \fItype\fP is edge triggered, forward that as Rising edge as PDC
takes care of converting falling edge to rising edge signal
If \fItype\fP is level, then forward that as level high as PDC
takes care of converting falling edge to rising edge signal
