.TH "qcom_scm_ice_available" 9 "qcom_scm_ice_available" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qcom_scm_ice_available \- Is the ICE key programming interface available?
.SH SYNOPSIS
.B "bool" qcom_scm_ice_available
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
true iff the SCM calls wrapped by \fBqcom_scm_ice_invalidate_key\fP and
\fBqcom_scm_ice_set_key\fP are available.
