.TH "qcom_icc_set" 9 "qcom_icc_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qcom_icc_set \- set the constraints based on path
.SH SYNOPSIS
.B "int" qcom_icc_set
.BI "(struct icc_node *src "  ","
.BI "struct icc_node *dst "  ");"
.SH ARGUMENTS
.IP "src" 12
source node for the path to set constraints on
.IP "dst" 12
destination node for the path to set constraints on
.SH "RETURN"
0 on success, or an error code otherwise
