.TH "qcom_wcnss_open_channel" 9 "qcom_wcnss_open_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qcom_wcnss_open_channel \- open additional SMD channel to WCNSS
.SH SYNOPSIS
.B "struct rpmsg_endpoint *" qcom_wcnss_open_channel
.BI "(void *wcnss "  ","
.BI "const char *name "  ","
.BI "rpmsg_rx_cb_t cb "  ","
.BI "void *priv "  ");"
.SH ARGUMENTS
.IP "wcnss" 12
wcnss handle, retrieved from drvdata
.IP "name" 12
SMD channel name
.IP "cb" 12
callback to handle incoming data on the channel
.IP "priv" 12
private data for use in the call-back
