.TH "qed_iov_config_perm_table" 9 "qed_iov_config_perm_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qed_iov_config_perm_table \- Configure the permission zone table.
.SH SYNOPSIS
.B "void" qed_iov_config_perm_table
.BI "(struct qed_hwfn *p_hwfn "  ","
.BI "struct qed_ptt *p_ptt "  ","
.BI "struct qed_vf_info *vf "  ","
.BI "u8 enable "  ");"
.SH ARGUMENTS
.IP "p_hwfn" 12
HW device data.
.IP "p_ptt" 12
PTT window for writing the registers.
.IP "vf" 12
VF info data.
.IP "enable" 12
The actual permision for this VF.
.SH "DESCRIPTION"
In E4, queue zone permission table size is 320x9. There
are 320 VF queues for single engine device (256 for dual
engine device), and each entry has the following format:
{Valid, VF[7:0]}
