.TH "qeth_bridgeport_an_set" 9 "qeth_bridgeport_an_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qeth_bridgeport_an_set \- Enable or disable bridgeport address notification
.SH SYNOPSIS
.B "int" qeth_bridgeport_an_set
.BI "(struct qeth_card *card "  ","
.BI "int enable "  ");"
.SH ARGUMENTS
.IP "card" 12
qeth_card structure pointer.
.IP "enable" 12
0 - disable, non-zero - enable notifications
.SH "DESCRIPTION"
Returns negative errno-compatible error indication or 0 on success.

On enable, emits a series of address notifications udev events for all
currently registered hosts.
