.TH "qeth_send_ipa_cmd" 9 "qeth_send_ipa_cmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qeth_send_ipa_cmd \- send an IPA command
.SH SYNOPSIS
.B "int" qeth_send_ipa_cmd
.BI "(struct qeth_card *card "  ","
.BI "struct qeth_cmd_buffer *iob "  ","
.BI "int (*reply_cb)(struct qeth_card *, struct qeth_reply*, unsigned long) "  ","
.BI "void *reply_param "  ");"
.SH ARGUMENTS
.IP "card" 12
-- undescribed --
.IP "iob" 12
-- undescribed --
.IP "reply_cb" 12
-- undescribed --
.IP "reply_param" 12
-- undescribed --
.SH "DESCRIPTION"

See \fBqeth_send_control_data\fP for explanation of the arguments.
