.TH "qeth_bridgeport_query_support" 9 "qeth_bridgeport_query_support" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qeth_bridgeport_query_support \- store bitmask of supported subfunctions.
.SH SYNOPSIS
.B "void" qeth_bridgeport_query_support
.BI "(struct qeth_card *card "  ");"
.SH ARGUMENTS
.IP "card" 12
qeth_card structure pointer.
.SH "DESCRIPTION"
Sets bitmask of supported setbridgeport subfunctions in the qeth_card
strucutre: card->options.sbp.supported_funcs.
