.TH "qib_fill_device_attr" 9 "qib_fill_device_attr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qib_fill_device_attr \- Fill in rvt dev info device attributes.
.SH SYNOPSIS
.B "void" qib_fill_device_attr
.BI "(struct qib_devdata *dd "  ");"
.SH ARGUMENTS
.IP "dd" 12
the device data structure
