.TH "qib_6120_setup_cleanup" 9 "qib_6120_setup_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qib_6120_setup_cleanup \- clean up any per-chip chip-specific stuff
.SH SYNOPSIS
.B "void" qib_6120_setup_cleanup
.BI "(struct qib_devdata *dd "  ");"
.SH ARGUMENTS
.IP "dd" 12
the qlogic_ib device
.SH "DESCRIPTION"
This is called during driver unload.
