.TH "qla2x00_process_completed_request" 9 "qla2x00_process_completed_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla2x00_process_completed_request \- Process a Fast Post response.
.SH SYNOPSIS
.B "void" qla2x00_process_completed_request
.BI "(struct scsi_qla_host *vha "  ","
.BI "struct req_que *req "  ","
.BI "uint32_t index "  ");"
.SH ARGUMENTS
.IP "vha" 12
SCSI driver HA context
.IP "req" 12
request queue
.IP "index" 12
SRB index
