.TH "qla2x00_update_fw_options" 9 "qla2x00_update_fw_options" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla2x00_update_fw_options \- Read and process firmware options.
.SH SYNOPSIS
.B "void" qla2x00_update_fw_options
.BI "(scsi_qla_host_t *vha "  ");"
.SH ARGUMENTS
.IP "vha" 12
HA context
.SH "DESCRIPTION"
Returns 0 on success.
