.TH "qla2x00_init_rings" 9 "qla2x00_init_rings" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla2x00_init_rings \- Initializes firmware.
.SH SYNOPSIS
.B "int" qla2x00_init_rings
.BI "(scsi_qla_host_t *vha "  ");"
.SH ARGUMENTS
.IP "vha" 12
HA context
.SH "DESCRIPTION"
Beginning of request ring has initialization control block already built
by nvram config routine.

Returns 0 on success.
