.TH "qla2x00_start_scsi" 9 "qla2x00_start_scsi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla2x00_start_scsi \- Send a SCSI command to the ISP
.SH SYNOPSIS
.B "int" qla2x00_start_scsi
.BI "(srb_t *sp "  ");"
.SH ARGUMENTS
.IP "sp" 12
command to send to the ISP
.SH "DESCRIPTION"
Returns non-zero if a failure occurred, else zero.
