.TH "qla24xx_reset_risc" 9 "qla24xx_reset_risc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla24xx_reset_risc \- Perform full reset of ISP24xx RISC.
.SH SYNOPSIS
.B "int" qla24xx_reset_risc
.BI "(scsi_qla_host_t *vha "  ");"
.SH ARGUMENTS
.IP "vha" 12
HA context
.SH "DESCRIPTION"
Returns 0 on success.
