.TH "qla2x00_rft_id" 9 "qla2x00_rft_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla2x00_rft_id \- SNS Register FC-4 TYPEs (RFT_ID) supported by the HBA.
.SH SYNOPSIS
.B "int" qla2x00_rft_id
.BI "(scsi_qla_host_t *vha "  ");"
.SH ARGUMENTS
.IP "vha" 12
HA context
.SH "DESCRIPTION"
Returns 0 on success.
