.TH "qla2x00_async_event" 9 "qla2x00_async_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla2x00_async_event \- Process aynchronous events.
.SH SYNOPSIS
.B "void" qla2x00_async_event
.BI "(scsi_qla_host_t *vha "  ","
.BI "struct rsp_que *rsp "  ","
.BI "uint16_t *mb "  ");"
.SH ARGUMENTS
.IP "vha" 12
SCSI driver HA context
.IP "rsp" 12
response queue
.IP "mb" 12
Mailbox registers (0 - 3)
