.TH "qla2x00_gid_pt" 9 "qla2x00_gid_pt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla2x00_gid_pt \- SNS scan for fabric devices via GID_PT command.
.SH SYNOPSIS
.B "int" qla2x00_gid_pt
.BI "(scsi_qla_host_t *vha "  ","
.BI "sw_info_t *list "  ");"
.SH ARGUMENTS
.IP "vha" 12
HA context
.IP "list" 12
switch info entries to populate
.SH "NOTE"
Non-Nx_Ports are not requested.
.SH "DESCRIPTION"
Returns 0 on success.
