.TH "qla2x00_nv_write" 9 "qla2x00_nv_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla2x00_nv_write \- Prepare for NVRAM read/write operation.
.SH SYNOPSIS
.B "void" qla2x00_nv_write
.BI "(struct qla_hw_data *ha "  ","
.BI "uint16_t data "  ");"
.SH ARGUMENTS
.IP "ha" 12
HA context
.IP "data" 12
Serial interface selector
