.TH "qla4xxx_sysfs_ddb_is_non_persistent" 9 "qla4xxx_sysfs_ddb_is_non_persistent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla4xxx_sysfs_ddb_is_non_persistent \- check for non-persistence of ddb entry
.SH SYNOPSIS
.B "int" qla4xxx_sysfs_ddb_is_non_persistent
.BI "(struct device *dev "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "dev" 12
dev associated with the sysfs entry
.IP "data" 12
pointer to flashnode session object
.SH "RETURN"
1: if flashnode entry is non-persistent
0: if flashnode entry is persistent
