.TH "qla4_82xx_spurious_interrupt" 9 "qla4_82xx_spurious_interrupt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla4_82xx_spurious_interrupt \- processes spurious interrupt
.SH SYNOPSIS
.B "void" qla4_82xx_spurious_interrupt
.BI "(struct scsi_qla_host *ha "  ","
.BI "uint8_t reqs_count "  ");"
.SH ARGUMENTS
.IP "ha" 12
pointer to host adapter structure.
.IP "reqs_count" 12
\&.
