.TH "qla4xxx_interrupt_service_routine" 9 "qla4xxx_interrupt_service_routine" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla4xxx_interrupt_service_routine \- isr
.SH SYNOPSIS
.B "void" qla4xxx_interrupt_service_routine
.BI "(struct scsi_qla_host * ha "  ","
.BI "uint32_t intr_status "  ");"
.SH ARGUMENTS
.IP "ha" 12
pointer to host adapter structure.
.IP "intr_status" 12
Local interrupt status/type.
.SH "DESCRIPTION"
This is the main interrupt service routine.
hardware_lock locked upon entry. runs in interrupt context.
