.TH "qla4xxx_copy_sense" 9 "qla4xxx_copy_sense" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla4xxx_copy_sense \- copy sense data into cmd sense buffer
.SH SYNOPSIS
.B "void" qla4xxx_copy_sense
.BI "(struct scsi_qla_host *ha "  ","
.BI "struct status_entry *sts_entry "  ","
.BI "struct srb *srb "  ");"
.SH ARGUMENTS
.IP "ha" 12
Pointer to host adapter structure.
.IP "sts_entry" 12
Pointer to status entry structure.
.IP "srb" 12
Pointer to srb structure.
