.TH "qla4xxx_build_ddb_list" 9 "qla4xxx_build_ddb_list" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla4xxx_build_ddb_list \- Build ddb list and setup sessions
.SH SYNOPSIS
.B "void" qla4xxx_build_ddb_list
.BI "(struct scsi_qla_host *ha "  ","
.BI "int is_reset "  ");"
.SH ARGUMENTS
.IP "ha" 12
pointer to adapter structure
.IP "is_reset" 12
Is this init path or reset path
.SH "DESCRIPTION"
Create a list of sendtargets (st) from firmware DDBs, issue send targets
using connection open, then create the list of normal targets (nt)
from firmware DDBs. Based on the list of nt setup session and connection
objects.
