.TH "qla4xxx_sysfs_ddb_set_param" 9 "qla4xxx_sysfs_ddb_set_param" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla4xxx_sysfs_ddb_set_param \- Set parameter for firmware DDB entry
.SH SYNOPSIS
.B "int" qla4xxx_sysfs_ddb_set_param
.BI "(struct iscsi_bus_flash_session *fnode_sess "  ","
.BI "struct iscsi_bus_flash_conn *fnode_conn "  ","
.BI "void *data "  ","
.BI "int len "  ");"
.SH ARGUMENTS
.IP "fnode_sess" 12
pointer to session attrs of flash ddb entry
.IP "fnode_conn" 12
pointer to connection attrs of flash ddb entry
.IP "data" 12
Parameters and their values to update
.IP "len" 12
len of data
.SH "DESCRIPTION"
This sets the parameter of flash ddb entry and writes them to flash
