.TH "queue_set" 9 "queue_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
queue_set \- return the queue set a packet should use
.SH SYNOPSIS
.B "int" queue_set
.BI "(const struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "skb" 12
the packet

Maps a packet to the SGE queue set it should use.  The desired queue
set is carried in bits 1-3 in the packet's priority.
