.TH "queued_read_lock_slowpath" 9 "queued_read_lock_slowpath" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
queued_read_lock_slowpath \- acquire read lock of a queue rwlock
.SH SYNOPSIS
.B "void" queued_read_lock_slowpath
.BI "(struct qrwlock *lock "  ");"
.SH ARGUMENTS
.IP "lock" 12
Pointer to queue rwlock structure
