.TH "radeon_irq_kms_init" 9 "radeon_irq_kms_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_irq_kms_init \- init driver interrupt info
.SH SYNOPSIS
.B "int" radeon_irq_kms_init
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon device pointer
.SH "DESCRIPTION"
Sets up the work irq handlers, vblank init, MSIs, etc. (all asics).
Returns 0 for success, error for failure.
