.TH "radeon_fence_activity" 9 "radeon_fence_activity" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_fence_activity \- check for fence activity
.SH SYNOPSIS
.B "bool" radeon_fence_activity
.BI "(struct radeon_device *rdev "  ","
.BI "int ring "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ring" 12
ring index the fence is associated with
.SH "DESCRIPTION"
Checks the current fence value and calculates the last
signalled fence value. Returns true if activity occured
on the ring, and the fence_queue should be waken up.
