.TH "radeon_vce_semaphore_emit" 9 "radeon_vce_semaphore_emit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_vce_semaphore_emit \- emit a semaphore command
.SH SYNOPSIS
.B "bool" radeon_vce_semaphore_emit
.BI "(struct radeon_device *rdev "  ","
.BI "struct radeon_ring *ring "  ","
.BI "struct radeon_semaphore *semaphore "  ","
.BI "bool emit_wait "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ring" 12
engine to use
.IP "semaphore" 12
address of semaphore
.IP "emit_wait" 12
true=emit wait, false=emit signal
