.TH "radeon_vm_directory_size" 9 "radeon_vm_directory_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_vm_directory_size \- returns the size of the page directory in bytes
.SH SYNOPSIS
.B "unsigned" radeon_vm_directory_size
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Calculate the size of the page directory in bytes (cayman+).
