.TH "radeon_fence_write" 9 "radeon_fence_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_fence_write \- write a fence value
.SH SYNOPSIS
.B "void" radeon_fence_write
.BI "(struct radeon_device *rdev "  ","
.BI "u32 seq "  ","
.BI "int ring "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "seq" 12
sequence number to write
.IP "ring" 12
ring index the fence is associated with
.SH "DESCRIPTION"
Writes a fence value to memory or a scratch register (all asics).
