.TH "radeon_update_bandwidth_info" 9 "radeon_update_bandwidth_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_update_bandwidth_info \- update display bandwidth params
.SH SYNOPSIS
.B "void" radeon_update_bandwidth_info
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Used when sclk/mclk are switched or display modes are set.
params are used to calculate display watermarks (all asics)
