.TH "radeon_vga_set_decode" 9 "radeon_vga_set_decode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_vga_set_decode \- enable/disable vga decode
.SH SYNOPSIS
.B "unsigned int" radeon_vga_set_decode
.BI "(void *cookie "  ","
.BI "bool state "  ");"
.SH ARGUMENTS
.IP "cookie" 12
radeon_device pointer
.IP "state" 12
enable/disable vga decode
.SH "DESCRIPTION"
Enable/disable vga decode (all asics).
Returns VGA resource flags.
