.TH "radeon_gart_table_ram_free" 9 "radeon_gart_table_ram_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_gart_table_ram_free \- free system ram for gart page table
.SH SYNOPSIS
.B "void" radeon_gart_table_ram_free
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Free system memory for GART page table
(r1xx-r3xx, non-pcie r4xx, rs400).  These asics require the
gart table to be in system memory.
