.TH "radeon_atif_get_sbios_requests" 9 "radeon_atif_get_sbios_requests" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_atif_get_sbios_requests \- get requested sbios event
.SH SYNOPSIS
.B "int" radeon_atif_get_sbios_requests
.BI "(acpi_handle handle "  ","
.BI "struct atif_sbios_requests *req "  ");"
.SH ARGUMENTS
.IP "handle" 12
acpi handle
.IP "req" 12
atif sbios request struct
.SH "DESCRIPTION"
Execute the ATIF_FUNCTION_GET_SYSTEM_BIOS_REQUESTS ATIF function
to determine what requests the sbios is making to the driver
(all asics).
Returns 0 on success, error on failure.
