.TH "radeon_atpx_call" 9 "radeon_atpx_call" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_atpx_call \- call an ATPX method
.SH SYNOPSIS
.B "union acpi_object *" radeon_atpx_call
.BI "(acpi_handle handle "  ","
.BI "int function "  ","
.BI "struct acpi_buffer *params "  ");"
.SH ARGUMENTS
.IP "handle" 12
acpi handle
.IP "function" 12
the ATPX function to execute
.IP "params" 12
ATPX function params
.SH "DESCRIPTION"
Executes the requested ATPX function (all asics).
Returns a pointer to the acpi output buffer.
