.TH "radeon_cursor_reset" 9 "radeon_cursor_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_cursor_reset \- Re-set the current cursor, if any.
.SH SYNOPSIS
.B "void" radeon_cursor_reset
.BI "(struct drm_crtc *crtc "  ");"
.SH ARGUMENTS
.IP "crtc" 12
drm crtc
.SH "DESCRIPTION"
If the CRTC passed in currently has a cursor assigned, this function
makes sure it's visible.
