.TH "radeon_flip_work_func" 9 "radeon_flip_work_func" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_flip_work_func \- page flip framebuffer
.SH SYNOPSIS
.B "void" radeon_flip_work_func
.BI "(struct work_struct *__work "  ");"
.SH ARGUMENTS
.IP "__work" 12
kernel work item
.SH "DESCRIPTION"
Wait for the buffer object to become idle and do the actual page flip
