.TH "radeon_fence_driver_force_completion" 9 "radeon_fence_driver_force_completion" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_fence_driver_force_completion \- force all fence waiter to complete
.SH SYNOPSIS
.B "void" radeon_fence_driver_force_completion
.BI "(struct radeon_device *rdev "  ","
.BI "int ring "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon device pointer
.IP "ring" 12
the ring to complete
.SH "DESCRIPTION"
In case of GPU reset failure make sure no process keep waiting on fence
that will never complete.
