.TH "radeon_fence_driver_fini" 9 "radeon_fence_driver_fini" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_fence_driver_fini \- tear down the fence driver for all possible rings.
.SH SYNOPSIS
.B "void" radeon_fence_driver_fini
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon device pointer
.SH "DESCRIPTION"
Tear down the fence driver for all possible rings (all asics).
