.TH "radeon_acpi_is_pcie_performance_request_supported" 9 "radeon_acpi_is_pcie_performance_request_supported" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_acpi_is_pcie_performance_request_supported \- 
.SH SYNOPSIS
.B "bool" radeon_acpi_is_pcie_performance_request_supported
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Check if the ATCS pcie_perf_req and pcie_dev_rdy methods
are supported (all asics).
returns true if supported, false if not.
