.TH "radeon_vce_ib_execute" 9 "radeon_vce_ib_execute" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_vce_ib_execute \- execute indirect buffer
.SH SYNOPSIS
.B "void" radeon_vce_ib_execute
.BI "(struct radeon_device *rdev "  ","
.BI "struct radeon_ib *ib "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ib" 12
the IB to execute
