.TH "radisys_set_piomode" 9 "radisys_set_piomode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radisys_set_piomode \- Initialize host controller PATA PIO timings
.SH SYNOPSIS
.B "void" radisys_set_piomode
.BI "(struct ata_port *ap "  ","
.BI "struct ata_device *adev "  ");"
.SH ARGUMENTS
.IP "ap" 12
ATA port
.IP "adev" 12
Device whose timings we are configuring

Set PIO mode for device, in host controller PCI config space.

LOCKING:
None (inherited from caller).
