.TH "radix_tree_delete_item" 9 "radix_tree_delete_item" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radix_tree_delete_item \- delete an item from a radix tree
.SH SYNOPSIS
.B "void *" radix_tree_delete_item
.BI "(struct radix_tree_root *root "  ","
.BI "unsigned long index "  ","
.BI "void *item "  ");"
.SH ARGUMENTS
.IP "root" 12
radix tree root
.IP "index" 12
index key
.IP "item" 12
expected item
.SH "DESCRIPTION"
Remove \fIitem\fP at \fIindex\fP from the radix tree rooted at \fIroot\fP.
.SH "RETURN"
the deleted entry, or NULL if it was not present
or the entry at the given \fIindex\fP was not \fIitem\fP.
