.TH "raw_notifier_chain_register" 9 "raw_notifier_chain_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
raw_notifier_chain_register \- Add notifier to a raw notifier chain
.SH SYNOPSIS
.B "int" raw_notifier_chain_register
.BI "(struct raw_notifier_head *nh "  ","
.BI "struct notifier_block *n "  ");"
.SH ARGUMENTS
.IP "nh" 12
Pointer to head of the raw notifier chain
.IP "n" 12
New entry in notifier chain

Adds a notifier to a raw notifier chain.
All locking must be provided by the caller.

Currently always returns zero.
