.TH "rdma_connect_ece" 9 "rdma_connect_ece" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rdma_connect_ece \- Initiate an active connection request with ECE data.
.SH SYNOPSIS
.B "int" rdma_connect_ece
.BI "(struct rdma_cm_id *id "  ","
.BI "struct rdma_conn_param *conn_param "  ","
.BI "struct rdma_ucm_ece *ece "  ");"
.SH ARGUMENTS
.IP "id" 12
Connection identifier to connect.
.IP "conn_param" 12
Connection information used for connected QPs.
.IP "ece" 12
ECE parameters
.SH "DESCRIPTION"
See \fBrdma_connect\fP explanation.
