.TH "rdt_bit_usage_show" 9 "rdt_bit_usage_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rdt_bit_usage_show \- Display current usage of resources
.SH SYNOPSIS
.B "int" rdt_bit_usage_show
.BI "(struct kernfs_open_file *of "  ","
.BI "struct seq_file *seq "  ","
.BI "void *v "  ");"
.SH ARGUMENTS
.IP "of" 12
-- undescribed --
.IP "seq" 12
-- undescribed --
.IP "v" 12
-- undescribed --
.SH "DESCRIPTION"

A domain is a shared resource that can now be allocated differently. Here
we display the current regions of the domain as an annotated bitmask.
For each domain of this resource its allocation bitmask
is annotated as below to indicate the current usage of the corresponding bit:
0 - currently unused
X - currently available for sharing and used by software and hardware
H - currently used by hardware only but available for software use
S - currently used and shareable by software only
E - currently used exclusively by one resource group
P - currently pseudo-locked by one resource group
