.TH "rdtgroup_mode_by_closid" 9 "rdtgroup_mode_by_closid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rdtgroup_mode_by_closid \- Return mode of resource group with closid
.SH SYNOPSIS
.B "enum rdtgrp_mode" rdtgroup_mode_by_closid
.BI "(int closid "  ");"
.SH ARGUMENTS
.IP "closid" 12
closid if the resource group
.SH "DESCRIPTION"
Each resource group is associated with a \fIclosid\fP. Here the mode
of a resource group can be queried by searching for it using its closid.
.SH "RETURN"
mode as \fIenum rdtgrp_mode\fP of resource group with closid \fIclosid\fP
