.TH "read_powermode" 9 "read_powermode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
read_powermode \- Query the power mode of the slave
.SH SYNOPSIS
.B "int" read_powermode
.BI "(struct w1_slave *sl "  ");"
.SH ARGUMENTS
.IP "sl" 12
slave to retrieve the power mode
.SH "DESCRIPTION"
Ask the device to get its power mode (external or parasite)
and store the power status in the \fIstruct w1_therm_family_data\fP.
.SH "RETURN"
* 0 parasite powered device
* 1 externally powered device
* <0 kernel error code
