.TH "read_download_mem" 9 "read_download_mem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
read_download_mem \- Read edgeport memory from TI chip
.SH SYNOPSIS
.B "int" read_download_mem
.BI "(struct usb_device *dev "  ","
.BI "int start_address "  ","
.BI "int length "  ","
.BI "__u8 address_type "  ","
.BI "__u8 *buffer "  ");"
.SH ARGUMENTS
.IP "dev" 12
usb device pointer
.IP "start_address" 12
Device CPU address at which to read
.IP "length" 12
Length of above data
.IP "address_type" 12
Can read both XDATA and I2C
.IP "buffer" 12
pointer to input data buffer
