.TH "register_netdevice" 9 "register_netdevice" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
register_netdevice \- register a network device
.SH SYNOPSIS
.B "int" register_netdevice
.BI "(struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device to register

Take a completed network device structure and add it to the kernel
interfaces. A NETDEV_REGISTER message is sent to the netdev notifier
chain. 0 is returned on success. A negative errno code is returned
on a failure to set up the device, or if the name is a duplicate.

Callers must hold the rtnl semaphore. You may want
\fBregister_netdev\fP instead of this.

BUGS:
The locking appears insufficient to guarantee two parallel registers
will not get the same name.
