.TH "regmap_sccb_write" 9 "regmap_sccb_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regmap_sccb_write \- Write data to SCCB slave device
.SH SYNOPSIS
.B "int" regmap_sccb_write
.BI "(void *context "  ","
.BI "unsigned int reg "  ","
.BI "unsigned int val "  ");"
.SH ARGUMENTS
.IP "context" 12
Device that will be interacted with
.IP "reg" 12
Register to write to
.IP "val" 12
Value to be written
.SH "DESCRIPTION"
This executes the SCCB 3-phase write transmission cycle, returning negative
errno else zero on success.
