.TH "regulator_set_voltage" 9 "regulator_set_voltage" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regulator_set_voltage \- set regulator output voltage
.SH SYNOPSIS
.B "int" regulator_set_voltage
.BI "(struct regulator *regulator "  ","
.BI "int min_uV "  ","
.BI "int max_uV "  ");"
.SH ARGUMENTS
.IP "regulator" 12
regulator source
.IP "min_uV" 12
Minimum required voltage in uV
.IP "max_uV" 12
Maximum acceptable voltage in uV
.SH "DESCRIPTION"
Sets a voltage regulator to the desired output voltage. This can be set
during any regulator state. IOW, regulator can be disabled or enabled.

If the regulator is enabled then the voltage will change to the new value
immediately otherwise if the regulator is disabled the regulator will
output at the new voltage when enabled.
.SH "NOTE"
If the regulator is shared between several devices then the lowest
request voltage that meets the system constraints will be used.
Regulator system constraints must be set for this regulator before
calling this function otherwise this call will fail.
