.TH "regulator_get_voltage" 9 "regulator_get_voltage" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regulator_get_voltage \- get regulator output voltage
.SH SYNOPSIS
.B "int" regulator_get_voltage
.BI "(struct regulator *regulator "  ");"
.SH ARGUMENTS
.IP "regulator" 12
regulator source
.SH "DESCRIPTION"
This returns the current regulator voltage in uV.
.SH "NOTE"
If the regulator is disabled it will return the voltage value. This
function should not be used to determine regulator state.
