.TH "regulator_suspend" 9 "regulator_suspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regulator_suspend \- prepare regulators for system wide suspend
.SH SYNOPSIS
.B "int" regulator_suspend
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
``\fIstruct device\fP`` pointer that is passed to \fB_regulator_suspend\fP
.SH "DESCRIPTION"
Configure each regulator with it's suspend operating parameters for state.
