.TH "relay_destroy_channel" 9 "relay_destroy_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
relay_destroy_channel \- free the channel struct
.SH SYNOPSIS
.B "void" relay_destroy_channel
.BI "(struct kref *kref "  ");"
.SH ARGUMENTS
.IP "kref" 12
target kernel reference that contains the relay channel

Should only be called from \fBkref_put\fP.
