.TH "release_new_page_budget" 9 "release_new_page_budget" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
release_new_page_budget \- release budget of a new page.
.SH SYNOPSIS
.B "void" release_new_page_budget
.BI "(struct ubifs_info *c "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.SH "DESCRIPTION"
This is a helper function which releases budget corresponding to the budget
of one new page of data.
