.TH "remap_io_sg" 9 "remap_io_sg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
remap_io_sg \- remap an IO mapping to userspace
.SH SYNOPSIS
.B "int" remap_io_sg
.BI "(struct vm_area_struct *vma "  ","
.BI "unsigned long addr "  ","
.BI "unsigned long size "  ","
.BI "struct scatterlist *sgl "  ","
.BI "resource_size_t iobase "  ");"
.SH ARGUMENTS
.IP "vma" 12
user vma to map to
.IP "addr" 12
target user address to start at
.IP "size" 12
size of map area
.IP "sgl" 12
Start sg entry
.IP "iobase" 12
Use stored dma address offset by this address or pfn if -1
.SH "NOTE"
this is only safe if the mm semaphore is held when called.
