.TH "remap_vmalloc_range" 9 "remap_vmalloc_range" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
remap_vmalloc_range \- map vmalloc pages to userspace
.SH SYNOPSIS
.B "int" remap_vmalloc_range
.BI "(struct vm_area_struct *vma "  ","
.BI "void *addr "  ","
.BI "unsigned long pgoff "  ");"
.SH ARGUMENTS
.IP "vma" 12
vma to cover (map full range of vma)
.IP "addr" 12
vmalloc memory
.IP "pgoff" 12
number of pages into addr before first page to map
.SH "RETURN"
0 for success, -Exxx on failure
.SH "DESCRIPTION"
This function checks that addr is a valid vmalloc'ed area, and
that it is big enough to cover the vma. Will return failure if
that criteria isn't met.

Similar to \fBremap_pfn_range\fP (see mm/memory.c)
