.TH "remove_id_store" 9 "remove_id_store" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
remove_id_store \- remove a PCI device ID from this driver
.SH SYNOPSIS
.B "ssize_t" remove_id_store
.BI "(struct device_driver *driver "  ","
.BI "const char *buf "  ","
.BI "size_t count "  ");"
.SH ARGUMENTS
.IP "driver" 12
target device driver
.IP "buf" 12
buffer for scanning device ID data
.IP "count" 12
input size
.SH "DESCRIPTION"
Removes a dynamic pci device ID to this driver.
