.TH "remove_watch_from_object" 9 "remove_watch_from_object" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
remove_watch_from_object \- Remove a watch or all watches from an object.
.SH SYNOPSIS
.B "int" remove_watch_from_object
.BI "(struct watch_list *wlist "  ","
.BI "struct watch_queue *wq "  ","
.BI "u64 id "  ","
.BI "bool all "  ");"
.SH ARGUMENTS
.IP "wlist" 12
The watch list to remove from
.IP "wq" 12
The watch queue of interest (ignored if \fIall\fP is true)
.IP "id" 12
The ID of the watch to remove (ignored if \fIall\fP is true)
.IP "all" 12
True to remove all objects
.SH "DESCRIPTION"
Remove a specific watch or all watches from an object.  A notification is
sent to the watcher to tell them that this happened.
