.TH "reserve_memory" 9 "reserve_memory" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
reserve_memory \- setup reserved memory areas
.SH SYNOPSIS
.B "void" reserve_memory
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Setup the reserved memory areas set aside for the boot parameters,
initrd, etc.  There are currently IA64_MAX_RSVD_REGIONS defined,
see arch/ia64/include/asm/meminit.h if you need to define more.
