.TH "rfkill_get_global_sw_state" 9 "rfkill_get_global_sw_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rfkill_get_global_sw_state \- returns global state for a type
.SH SYNOPSIS
.B "bool" rfkill_get_global_sw_state
.BI "(const enum rfkill_type type "  ");"
.SH ARGUMENTS
.IP "type" 12
the type to get the global state of
.SH "DESCRIPTION"
Returns the current global state for a given wireless
device type.
