.TH "rhine_init_cam_filter" 9 "rhine_init_cam_filter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rhine_init_cam_filter \- initialize CAM filters
.SH SYNOPSIS
.B "void" rhine_init_cam_filter
.BI "(struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
network device
.SH "DESCRIPTION"
Initialize (disable) hardware VLAN and multicast support on this
Rhine.
