.TH "rhine_set_cam" 9 "rhine_set_cam" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rhine_set_cam \- set CAM multicast filters
.SH SYNOPSIS
.B "void" rhine_set_cam
.BI "(void __iomem *ioaddr "  ","
.BI "int idx "  ","
.BI "u8 *addr "  ");"
.SH ARGUMENTS
.IP "ioaddr" 12
register block of this Rhine
.IP "idx" 12
multicast CAM index [0..MCAM_SIZE-1]
.IP "addr" 12
multicast address (6 bytes)
.SH "DESCRIPTION"
Load addresses into multicast filters.
