.TH "rio_chk_dev_route" 9 "rio_chk_dev_route" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rio_chk_dev_route \- Validate route to the specified device.
.SH SYNOPSIS
.B "int" rio_chk_dev_route
.BI "(struct rio_dev *rdev "  ","
.BI "struct rio_dev **nrdev "  ","
.BI "int *npnum "  ");"
.SH ARGUMENTS
.IP "rdev" 12
RIO device failed to respond
.IP "nrdev" 12
Last active device on the route to rdev
.IP "npnum" 12
nrdev's port number on the route to rdev
.SH "DESCRIPTION"
Follows a route to the specified RIO device to determine the last available
device (and corresponding RIO port) on the route.
