.TH "rio_build_route_tables" 9 "rio_build_route_tables" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rio_build_route_tables \- Generate route tables from switch route entries
.SH SYNOPSIS
.B "void" rio_build_route_tables
.BI "(struct rio_net *net "  ");"
.SH ARGUMENTS
.IP "net" 12
RIO network to run route tables scan on
.SH "DESCRIPTION"
For each switch device, generate a route table by copying existing
route entries from the switch.
