.TH "rio_set_device_id" 9 "rio_set_device_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rio_set_device_id \- Set the base/extended device id for a device
.SH SYNOPSIS
.B "void" rio_set_device_id
.BI "(struct rio_mport *port "  ","
.BI "u16 destid "  ","
.BI "u8 hopcount "  ","
.BI "u16 did "  ");"
.SH ARGUMENTS
.IP "port" 12
RIO master port
.IP "destid" 12
Destination ID of device
.IP "hopcount" 12
Hopcount to device
.IP "did" 12
Device ID value to be written
.SH "DESCRIPTION"
Writes the base/extended device id from a device.
