.TH "riva_load_state" 9 "riva_load_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
riva_load_state \- loads current chip state
.SH SYNOPSIS
.B "void" riva_load_state
.BI "(struct riva_par *par "  ","
.BI "struct riva_regs *regs "  ");"
.SH ARGUMENTS
.IP "par" 12
pointer to riva_par object containing info for current riva board
.IP "regs" 12
pointer to riva_regs object
.SH "DESCRIPTION"
Loads chip state from \fIregs\fP.

CALLED FROM:
\fBriva_load_video_mode\fP
\fBrivafb_probe\fP
\fBrivafb_remove\fP
