.TH "rivafb_copyarea" 9 "rivafb_copyarea" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rivafb_copyarea \- hardware accelerated blit function
.SH SYNOPSIS
.B "void" rivafb_copyarea
.BI "(struct fb_info *info "  ","
.BI "const struct fb_copyarea *region "  ");"
.SH ARGUMENTS
.IP "info" 12
pointer to fb_info structure
.IP "region" 12
pointer to fb_copyarea structure
.SH "DESCRIPTION"
This copies an area of pixels from one location to another

CALLED FROM:
framebuffer hook
