.TH "riva_get_cmap_len" 9 "riva_get_cmap_len" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
riva_get_cmap_len \- query current color map length
.SH SYNOPSIS
.B "int" riva_get_cmap_len
.BI "(const struct fb_var_screeninfo *var "  ");"
.SH ARGUMENTS
.IP "var" 12
standard kernel fb changeable data
.SH "DESCRIPTION"
Get current color map length.

CALLED FROM:
\fBrivafb_setcolreg\fP
.SH "RETURN"
Length of color map
