.TH "rpc_clone_client" 9 "rpc_clone_client" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpc_clone_client \- Clone an RPC client structure
.SH SYNOPSIS
.B "struct rpc_clnt *" rpc_clone_client
.BI "(struct rpc_clnt *clnt "  ");"
.SH ARGUMENTS
.IP "clnt" 12
RPC client whose parameters are copied
.SH "DESCRIPTION"
Returns a fresh RPC client or an ERR_PTR.
