.TH "rpcauth_get_gssinfo" 9 "rpcauth_get_gssinfo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpcauth_get_gssinfo \- find GSS tuple matching a GSS pseudoflavor
.SH SYNOPSIS
.B "int" rpcauth_get_gssinfo
.BI "(rpc_authflavor_t pseudoflavor "  ","
.BI "struct rpcsec_gss_info *info "  ");"
.SH ARGUMENTS
.IP "pseudoflavor" 12
GSS pseudoflavor to match
.IP "info" 12
rpcsec_gss_info structure to fill in
.SH "DESCRIPTION"
Returns zero and fills in "info" if pseudoflavor matches a
supported mechanism.
