.TH "rpcrdma_sendctx_put_locked" 9 "rpcrdma_sendctx_put_locked" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpcrdma_sendctx_put_locked \- Release a send context
.SH SYNOPSIS
.B "void" rpcrdma_sendctx_put_locked
.BI "(struct rpcrdma_xprt *r_xprt "  ","
.BI "struct rpcrdma_sendctx *sc "  ");"
.SH ARGUMENTS
.IP "r_xprt" 12
controlling transport instance
.IP "sc" 12
send context to release
.SH "DESCRIPTION"
Usage: Called from Send completion to return a sendctxt
to the queue.

The caller serializes calls to this function (per transport).
