.TH "rpmh_rsc_invalidate" 9 "rpmh_rsc_invalidate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpmh_rsc_invalidate \- Invalidate sleep and wake TCSes.
.SH SYNOPSIS
.B "void" rpmh_rsc_invalidate
.BI "(struct rsc_drv *drv "  ");"
.SH ARGUMENTS
.IP "drv" 12
The RSC controller.
.SH "DESCRIPTION"
The caller must ensure that no other RPMH actions are happening when this
function is called, since otherwise the device may immediately become
used again even before this function exits.
