.TH "rpmsg_destroy_ept" 9 "rpmsg_destroy_ept" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpmsg_destroy_ept \- destroy an existing rpmsg endpoint
.SH SYNOPSIS
.B "void" rpmsg_destroy_ept
.BI "(struct rpmsg_endpoint *ept "  ");"
.SH ARGUMENTS
.IP "ept" 12
endpoing to destroy
.SH "DESCRIPTION"
Should be used by drivers to destroy an rpmsg endpoint previously
created with \fBrpmsg_create_ept\fP. As with other types of "free" NULL
is a valid parameter.
