.TH "rproc_elf_sanity_check" 9 "rproc_elf_sanity_check" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rproc_elf_sanity_check \- Sanity Check for ELF32/ELF64 firmware image
.SH SYNOPSIS
.B "int" rproc_elf_sanity_check
.BI "(struct rproc *rproc "  ","
.BI "const struct firmware *fw "  ");"
.SH ARGUMENTS
.IP "rproc" 12
the remote processor handle
.IP "fw" 12
the ELF firmware image
.SH "DESCRIPTION"
Make sure this fw image is sane (ie a correct ELF32/ELF64 file).
