.TH "rproc_check_carveout_da" 9 "rproc_check_carveout_da" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rproc_check_carveout_da \- Check specified carveout da configuration
.SH SYNOPSIS
.B "int" rproc_check_carveout_da
.BI "(struct rproc *rproc "  ","
.BI "struct rproc_mem_entry *mem "  ","
.BI "u32 da "  ","
.BI "u32 len "  ");"
.SH ARGUMENTS
.IP "rproc" 12
handle of a remote processor
.IP "mem" 12
pointer on carveout to check
.IP "da" 12
area device address
.IP "len" 12
associated area size
.SH "DESCRIPTION"
This function is a helper function to verify requested device area (couple
da, len) is part of specified carveout.
If da is not set (defined as FW_RSC_ADDR_ANY), only requested length is
checked.
.SH "RETURN"
0 if carveout matches request else error
