.TH "rproc_of_resm_mem_entry_init" 9 "rproc_of_resm_mem_entry_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rproc_of_resm_mem_entry_init \- allocate and initialize rproc_mem_entry struct from a reserved memory phandle
.SH SYNOPSIS
.B "struct rproc_mem_entry *" rproc_of_resm_mem_entry_init
.BI "(struct device *dev "  ","
.BI "u32 of_resm_idx "  ","
.BI "size_t len "  ","
.BI "u32 da "  ","
.BI "const char *name "  ","
.BI "... "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer on device struct
.IP "of_resm_idx" 12
reserved memory phandle index in "memory-region"
.IP "len" 12
memory carveout length
.IP "da" 12
device address
.IP "name" 12
carveout name
.IP "..." 12
variable arguments
.SH "DESCRIPTION"
This function allocates a rproc_mem_entry struct and fill it with parameters
provided by client.
