.TH "rsi_map_rates" 9 "rsi_map_rates" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_map_rates \- This function is used to map selected rates to hw rates.
.SH SYNOPSIS
.B "bool" rsi_map_rates
.BI "(u16 rate "  ","
.BI "int *offset "  ");"
.SH ARGUMENTS
.IP "rate" 12
The standard rate to be mapped.
.IP "offset" 12
Offset that will be returned.
.SH "RETURN"
0 if it is a mcs rate, else 1
