.TH "rsi_core_queue_pkt" 9 "rsi_core_queue_pkt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_core_queue_pkt \- This functions enqueues the packet to the queue specified by the queue number.
.SH SYNOPSIS
.B "void" rsi_core_queue_pkt
.BI "(struct rsi_common *common "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "common" 12
Pointer to the driver private structure.
.IP "skb" 12
Pointer to the socket buffer structure.
.SH "RETURN"
None.
