.TH "rsi_sdio_read_register" 9 "rsi_sdio_read_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_sdio_read_register \- This function reads one byte of information from a register.
.SH SYNOPSIS
.B "int" rsi_sdio_read_register
.BI "(struct rsi_hw *adapter "  ","
.BI "u32 addr "  ","
.BI "u8 *data "  ");"
.SH ARGUMENTS
.IP "adapter" 12
Pointer to the adapter structure.
.IP "addr" 12
Address of the register.
.IP "data" 12
Pointer to the data that stores the data read.
.SH "RETURN"
0 on success, -1 on failure.
