.TH "rsi_stats_open" 9 "rsi_stats_open" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_stats_open \- This function calls single open function of seq_file to open file and read contents from it.
.SH SYNOPSIS
.B "int" rsi_stats_open
.BI "(struct inode *inode "  ","
.BI "struct file *file "  ");"
.SH ARGUMENTS
.IP "inode" 12
Pointer to the inode structure.
.IP "file" 12
Pointer to the file structure.
.SH "RETURN"
Pointer to the opened file status: 0 on success, ENOMEM on failure.
