.TH "rsi_program_bb_rf" 9 "rsi_program_bb_rf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_program_bb_rf \- This function starts base band and RF programming. This is called after initial configurations are done.
.SH SYNOPSIS
.B "int" rsi_program_bb_rf
.BI "(struct rsi_common *common "  ");"
.SH ARGUMENTS
.IP "common" 12
Pointer to the driver private structure.
.SH "RETURN"
0 on success, corresponding negative error code on failure.
