.TH "rtl88eu_mon_xmit_hook" 9 "rtl88eu_mon_xmit_hook" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rtl88eu_mon_xmit_hook \- forward trasmitted frame to the monitor interface
.SH SYNOPSIS
.B "void" rtl88eu_mon_xmit_hook
.BI "(struct net_device *dev "  ","
.BI "struct xmit_frame *frame "  ","
.BI "uint frag_len "  ");"
.SH ARGUMENTS
.IP "dev" 12
-- undescribed --
.IP "frame" 12
-- undescribed --
.IP "frag_len" 12
-- undescribed --
.SH "DESCRIPTION"

Assumes that:
- frame header contains an IV and frame->attrib.iv_len is set accordingly,
- data is not encrypted and ICV/MIC has not been appended yet.
