.TH "rtnl_af_register" 9 "rtnl_af_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rtnl_af_register \- Register rtnl_af_ops with rtnetlink.
.SH SYNOPSIS
.B "void" rtnl_af_register
.BI "(struct rtnl_af_ops *ops "  ");"
.SH ARGUMENTS
.IP "ops" 12
struct rtnl_af_ops * to register
.SH "DESCRIPTION"
Returns 0 on success or a negative error code.
