.TH "run_gc" 9 "run_gc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
run_gc \- run garbage collector.
.SH SYNOPSIS
.B "int" run_gc
.BI "(struct ubifs_info *c "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.SH "DESCRIPTION"
This function runs garbage collector to make some more free space. Returns
zero if a free LEB has been produced, -EAGAIN if commit is required, and a
negative error code in case of failure.
