.TH "rvt_free_qp_cb" 9 "rvt_free_qp_cb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rvt_free_qp_cb \- callback function to reset a qp
.SH SYNOPSIS
.B "void" rvt_free_qp_cb
.BI "(struct rvt_qp *qp "  ","
.BI "u64 v "  ");"
.SH ARGUMENTS
.IP "qp" 12
the qp to reset
.IP "v" 12
a 64-bit value
.SH "DESCRIPTION"
This function resets the qp and removes it from the
qp hash table.
