.TH "rvt_add_rnr_timer" 9 "rvt_add_rnr_timer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rvt_add_rnr_timer \- add/start an rnr timer on the QP
.SH SYNOPSIS
.B "void" rvt_add_rnr_timer
.BI "(struct rvt_qp *qp "  ","
.BI "u32 aeth "  ");"
.SH ARGUMENTS
.IP "qp" 12
the QP
.IP "aeth" 12
aeth of RNR timeout, simulated aeth for loopback
