.TH "rvt_query_ah" 9 "rvt_query_ah" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rvt_query_ah \- return attrs for ah
.SH SYNOPSIS
.B "int" rvt_query_ah
.BI "(struct ib_ah *ibah "  ","
.BI "struct rdma_ah_attr *ah_attr "  ");"
.SH ARGUMENTS
.IP "ibah" 12
address handle to query
.IP "ah_attr" 12
return info in this
.SH "RETURN"
always 0
