.TH "rvt_alloc_ucontext" 9 "rvt_alloc_ucontext" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rvt_alloc_ucontext \- Allocate a user context
.SH SYNOPSIS
.B "int" rvt_alloc_ucontext
.BI "(struct ib_ucontext *uctx "  ","
.BI "struct ib_udata *udata "  ");"
.SH ARGUMENTS
.IP "uctx" 12
Verbs context
.IP "udata" 12
User data allocated
