.TH "rx6110_data_to_rtc_tm" 9 "rx6110_data_to_rtc_tm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rx6110_data_to_rtc_tm \- convert native time encoding to rtc_time
.SH SYNOPSIS
.B "int" rx6110_data_to_rtc_tm
.BI "(u8 *data "  ","
.BI "struct rtc_time *tm "  ");"
.SH ARGUMENTS
.IP "data" 12
holds the encoding in rx6110 native form
.IP "tm" 12
holds date and time
