.TH "rz1000_set_mode" 9 "rz1000_set_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rz1000_set_mode \- mode setting function
.SH SYNOPSIS
.B "int" rz1000_set_mode
.BI "(struct ata_link *link "  ","
.BI "struct ata_device **unused "  ");"
.SH ARGUMENTS
.IP "link" 12
ATA link
.IP "unused" 12
returned device on set_mode failure

Use a non standard set_mode function. We don't want to be tuned. We
would prefer to be BIOS generic but for the fact our hardware is
whacked out.
