.TH "rza1_gpio_register" 9 "rza1_gpio_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rza1_gpio_register \- parse DT to collect gpio-chips and gpio-ranges
.SH SYNOPSIS
.B "int" rza1_gpio_register
.BI "(struct rza1_pinctrl *rza1_pctl "  ");"
.SH ARGUMENTS
.IP "rza1_pctl" 12
RZ/A1 pin controller device
