.TH "s1d13xxxfb_setcolreg" 9 "s1d13xxxfb_setcolreg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s1d13xxxfb_setcolreg \- sets a color register.
.SH SYNOPSIS
.B "int" s1d13xxxfb_setcolreg
.BI "(u_int regno "  ","
.BI "u_int red "  ","
.BI "u_int green "  ","
.BI "u_int blue "  ","
.BI "u_int transp "  ","
.BI "struct fb_info *info "  ");"
.SH ARGUMENTS
.IP "regno" 12
Which register in the CLUT we are programming
.IP "red" 12
The red value which can be up to 16 bits wide
.IP "green" 12
The green value which can be up to 16 bits wide
.IP "blue" 12
The blue value which can be up to 16 bits wide.
.IP "transp" 12
If supported the alpha value which can be up to 16 bits wide.
.IP "info" 12
frame buffer info structure

Returns negative errno on error, or zero on success.
