.TH "s2io_register_test" 9 "s2io_register_test" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s2io_register_test \- reads and writes into all clock domains.
.SH SYNOPSIS
.B "int" s2io_register_test
.BI "(struct s2io_nic *sp "  ","
.BI "uint64_t *data "  ");"
.SH ARGUMENTS
.IP "sp" 12
private member of the device structure, which is a pointer to the
s2io_nic structure.
.IP "data" 12
variable that returns the result of each of the test conducted b
by the driver.
.SH "DESCRIPTION"
Read and write into all clock domains. The NIC has 3 clock domains,
see that registers in all the three regions are accessible.
Return value:
0 on success.
