.TH "s2io_ioctl" 9 "s2io_ioctl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s2io_ioctl \- Entry point for the Ioctl
.SH SYNOPSIS
.B "int" s2io_ioctl
.BI "(struct net_device *dev "  ","
.BI "struct ifreq *rq "  ","
.BI "int cmd "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device pointer.
.IP "rq" 12
An IOCTL specefic structure, that can contain a pointer to
a proprietary structure used to pass information to the driver.
.IP "cmd" 12
This is used to distinguish between the different commands that
can be passed to the IOCTL functions.
.SH "DESCRIPTION"
Currently there are no special functionality supported in IOCTL, hence
function always return EOPNOTSUPPORTED
