.TH "s3c2440_cpufreq_calcdivs" 9 "s3c2440_cpufreq_calcdivs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c2440_cpufreq_calcdivs \- calculate divider settings
.SH SYNOPSIS
.B "int" s3c2440_cpufreq_calcdivs
.BI "(struct s3c_cpufreq_config *cfg "  ");"
.SH ARGUMENTS
.IP "cfg" 12
The cpu frequency settings.
.SH "DESCRIPTION"
Calcualte the divider values for the given frequency settings
specified in \fIcfg\fP. The values are stored in \fIcfg\fP for later use
by the relevant set routine if the request settings can be reached.
