.TH "s3c_hsudc_alloc_request" 9 "s3c_hsudc_alloc_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c_hsudc_alloc_request \- Allocate a new request.
.SH SYNOPSIS
.B "struct usb_request *" s3c_hsudc_alloc_request
.BI "(struct usb_ep *_ep "  ","
.BI "gfp_t gfp_flags "  ");"
.SH ARGUMENTS
.IP "_ep" 12
Endpoint for which request is allocated (not used).
.IP "gfp_flags" 12
Flags used for the allocation.
.SH "DESCRIPTION"
Allocates a single transfer request structure when called from gadget driver.
