.TH "s3c_fb_probe_win" 9 "s3c_fb_probe_win" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c_fb_probe_win \- register an hardware window
.SH SYNOPSIS
.B "int" s3c_fb_probe_win
.BI "(struct s3c_fb *sfb "  ","
.BI "unsigned int win_no "  ","
.BI "struct s3c_fb_win_variant *variant "  ","
.BI "struct s3c_fb_win **res "  ");"
.SH ARGUMENTS
.IP "sfb" 12
The base resources for the hardware
.IP "win_no" 12
The window number
.IP "variant" 12
The variant information for this window.
.IP "res" 12
Pointer to where to place the resultant window.
.SH "DESCRIPTION"
Allocate and do the basic initialisation for one of the hardware's graphics
windows.
