.TH "s3c_hsudc_read_fifo" 9 "s3c_hsudc_read_fifo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c_hsudc_read_fifo \- Read the next chunk of data from EP fifo.
.SH SYNOPSIS
.B "int" s3c_hsudc_read_fifo
.BI "(struct s3c_hsudc_ep *hsep "  ","
.BI "struct s3c_hsudc_req *hsreq "  ");"
.SH ARGUMENTS
.IP "hsep" 12
Endpoint from which the data is to be read.
.IP "hsreq" 12
Transfer request to which the next chunk of data read is written.
.SH "DESCRIPTION"
Read the next chunk of data from the endpoint FIFO and a write it to the
transfer request buffer. If the transfer request completes, 1 is returned,
otherwise 0 is returned.
