.TH "s3c_hwmon_read_ch" 9 "s3c_hwmon_read_ch" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c_hwmon_read_ch \- read a value from a given adc channel.
.SH SYNOPSIS
.B "int" s3c_hwmon_read_ch
.BI "(struct device *dev "  ","
.BI "struct s3c_hwmon *hwmon "  ","
.BI "int channel "  ");"
.SH ARGUMENTS
.IP "dev" 12
The device.
.IP "hwmon" 12
Our state.
.IP "channel" 12
The channel we're reading from.
.SH "DESCRIPTION"
Read a value from the \fIchannel\fP with the proper locking and sleep until
either the read completes or we timeout awaiting the ADC core to get
back to us.
