.TH "s3c_hsudc_nuke_ep" 9 "s3c_hsudc_nuke_ep" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c_hsudc_nuke_ep \- Terminate all requests queued for a endpoint.
.SH SYNOPSIS
.B "void" s3c_hsudc_nuke_ep
.BI "(struct s3c_hsudc_ep *hsep "  ","
.BI "int status "  ");"
.SH ARGUMENTS
.IP "hsep" 12
Endpoint for which queued requests have to be terminated.
.IP "status" 12
Transfer completion status for the transfer request.
