.TH "s5p_hash_update_dma_stop" 9 "s5p_hash_update_dma_stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s5p_hash_update_dma_stop \- unmap DMA
.SH SYNOPSIS
.B "void" s5p_hash_update_dma_stop
.BI "(struct s5p_aes_dev *dd "  ");"
.SH ARGUMENTS
.IP "dd" 12
secss device
.SH "DESCRIPTION"
Unmap scatterlist ctx->sg.
