.TH "sa1111_select_audio_mode" 9 "sa1111_select_audio_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sa1111_select_audio_mode \- select I2S or AC link mode
.SH SYNOPSIS
.B "void" sa1111_select_audio_mode
.BI "(struct sa1111_dev *sadev "  ","
.BI "int mode "  ");"
.SH ARGUMENTS
.IP "sadev" 12
SA1111 function block
.IP "mode" 12
One of SA1111_AUDIO_ACLINK or SA1111_AUDIO_I2S

Frob the SKCR to select AC Link mode or I2S mode for
the audio block.
