.TH "san_dgpu_notifier_unregister" 9 "san_dgpu_notifier_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
san_dgpu_notifier_unregister \- Unregister a SAN dGPU notifier.
.SH SYNOPSIS
.B "int" san_dgpu_notifier_unregister
.BI "(struct notifier_block *nb "  ");"
.SH ARGUMENTS
.IP "nb" 12
The notifier-block to unregister.
