.TH "sas_rphy_add" 9 "sas_rphy_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sas_rphy_add \- add a SAS remote PHY to the device hierarchy
.SH SYNOPSIS
.B "int" sas_rphy_add
.BI "(struct sas_rphy *rphy "  ");"
.SH ARGUMENTS
.IP "rphy" 12
The remote PHY to be added
.SH "DESCRIPTION"
Publishes a SAS remote PHY to the rest of the system.
