.TH "sas_discover_sata" 9 "sas_discover_sata" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sas_discover_sata \- discover an STP/SATA domain device
.SH SYNOPSIS
.B "int" sas_discover_sata
.BI "(struct domain_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to struct domain_device of interest
.SH "DESCRIPTION"
Devices directly attached to a HA port, have no parents.  All other
devices do, and should have their "parent" pointer set appropriately
before calling this function.
