.TH "sbi_remote_sfence_vma" 9 "sbi_remote_sfence_vma" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sbi_remote_sfence_vma \- Execute SFENCE.VMA instructions on given remote harts for the specified virtual address range.
.SH SYNOPSIS
.B "int" sbi_remote_sfence_vma
.BI "(const unsigned long *hart_mask "  ","
.BI "unsigned long start "  ","
.BI "unsigned long size "  ");"
.SH ARGUMENTS
.IP "hart_mask" 12
A cpu mask containing all the target harts.
.IP "start" 12
Start of the virtual address
.IP "size" 12
Total size of the virtual address range.
.SH "RETURN"
0 on success, appropriate linux error code otherwise.
