.TH "sca3000_ring_int_process" 9 "sca3000_ring_int_process" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sca3000_ring_int_process \- ring specific interrupt handling.
.SH SYNOPSIS
.B "void" sca3000_ring_int_process
.BI "(u8 val "  ","
.BI "struct iio_dev *indio_dev "  ");"
.SH ARGUMENTS
.IP "val" 12
Value of the interrupt status register.
.IP "indio_dev" 12
Device instance specific IIO device structure.
