.TH "sci_clk_prepare" 9 "sci_clk_prepare" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sci_clk_prepare \- Prepare (enable) a TI SCI clock
.SH SYNOPSIS
.B "int" sci_clk_prepare
.BI "(struct clk_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
clock to prepare
.SH "DESCRIPTION"
Prepares a clock to be actively used. Returns the SCI protocol status.
