.TH "sci_clk_is_prepared" 9 "sci_clk_is_prepared" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sci_clk_is_prepared \- Check if a TI SCI clock is prepared or not
.SH SYNOPSIS
.B "int" sci_clk_is_prepared
.BI "(struct clk_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
clock to check status for
.SH "DESCRIPTION"
Checks if a clock is prepared (enabled) in hardware. Returns non-zero
value if clock is enabled, zero otherwise.
