.TH "sclp_chp_deconfigure" 9 "sclp_chp_deconfigure" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sclp_chp_deconfigure \- perform deconfigure channel-path sclp command
.SH SYNOPSIS
.B "int" sclp_chp_deconfigure
.BI "(struct chp_id chpid "  ");"
.SH ARGUMENTS
.IP "chpid" 12
channel-path ID
.SH "DESCRIPTION"
Perform deconfigure channel-path command sclp command for specified chpid
and wait for completion. On success return 0. Return non-zero otherwise.
