.TH "scmi_xfer_get_init" 9 "scmi_xfer_get_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scmi_xfer_get_init \- Allocate and initialise one message for transmit
.SH SYNOPSIS
.B "int" scmi_xfer_get_init
.BI "(const struct scmi_handle *handle "  ","
.BI "u8 msg_id "  ","
.BI "u8 prot_id "  ","
.BI "size_t tx_size "  ","
.BI "size_t rx_size "  ","
.BI "struct scmi_xfer **p "  ");"
.SH ARGUMENTS
.IP "handle" 12
Pointer to SCMI entity handle
.IP "msg_id" 12
Message identifier
.IP "prot_id" 12
Protocol identifier for the message
.IP "tx_size" 12
transmit message size
.IP "rx_size" 12
receive message size
.IP "p" 12
pointer to the allocated and initialised message
.SH "DESCRIPTION"
This function allocates the message using \fIscmi_xfer_get\fP and
initialise the header.
.SH "RETURN"
0 if all went fine with \fIp\fP pointing to message, else
corresponding error.
