.TH "scp_get_venc_hw_capa" 9 "scp_get_venc_hw_capa" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scp_get_venc_hw_capa \- get video encoder hardware capability
.SH SYNOPSIS
.B "unsigned int" scp_get_venc_hw_capa
.BI "(struct mtk_scp *scp "  ");"
.SH ARGUMENTS
.IP "scp" 12
mtk_scp structure
.SH "RETURN"
video encoder hardware capability
