.TH "scsi_init_devinfo" 9 "scsi_init_devinfo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_init_devinfo \- set up the dynamic device list.
.SH SYNOPSIS
.B "int" scsi_init_devinfo
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"
Add command line entries from scsi_dev_flags, then add
scsi_static_device_list entries to the scsi device info list.
