.TH "scsih_suspend" 9 "scsih_suspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsih_suspend \- power management suspend main entry point
.SH SYNOPSIS
.B "int __maybe_unused" scsih_suspend
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device struct
.SH "RETURN"
0 success, anything else error.
