.TH "scsi_kmap_atomic_sg" 9 "scsi_kmap_atomic_sg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_kmap_atomic_sg \- find and atomically map an sg-elemnt
.SH SYNOPSIS
.B "void *" scsi_kmap_atomic_sg
.BI "(struct scatterlist *sgl "  ","
.BI "int sg_count "  ","
.BI "size_t *offset "  ","
.BI "size_t *len "  ");"
.SH ARGUMENTS
.IP "sgl" 12
scatter-gather list
.IP "sg_count" 12
number of segments in sg
.IP "offset" 12
offset in bytes into sg, on return offset into the mapped area
.IP "len" 12
bytes to map, on return number of bytes mapped
.SH "DESCRIPTION"
Returns virtual address of the start of the mapped page
