.TH "scsi_dev_info_remove_list" 9 "scsi_dev_info_remove_list" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_dev_info_remove_list \- destroy an added devinfo list
.SH SYNOPSIS
.B "int" scsi_dev_info_remove_list
.BI "(enum scsi_devinfo_key key "  ");"
.SH ARGUMENTS
.IP "key" 12
key of the list to destroy
.SH "DESCRIPTION"
Iterates over the entire list first, freeing all the values, then
frees the list itself.  Returns 0 on success or -EINVAL if the key
can't be found.
