.TH "scsi_kunmap_atomic_sg" 9 "scsi_kunmap_atomic_sg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_kunmap_atomic_sg \- atomically unmap a virtual address, previously mapped with scsi_kmap_atomic_sg
.SH SYNOPSIS
.B "void" scsi_kunmap_atomic_sg
.BI "(void *virt "  ");"
.SH ARGUMENTS
.IP "virt" 12
virtual address to be unmapped
