.TH "scsi_evt_emit" 9 "scsi_evt_emit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_evt_emit \- emit a single SCSI device uevent
.SH SYNOPSIS
.B "void" scsi_evt_emit
.BI "(struct scsi_device *sdev "  ","
.BI "struct scsi_event *evt "  ");"
.SH ARGUMENTS
.IP "sdev" 12
associated SCSI device
.IP "evt" 12
event to emit

Send a single uevent (scsi_event) to the associated scsi_device.
