.TH "scsi_ioctl" 9 "scsi_ioctl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_ioctl \- Dispatch ioctl to scsi device
.SH SYNOPSIS
.B "int" scsi_ioctl
.BI "(struct scsi_device *sdev "  ","
.BI "int cmd "  ","
.BI "void __user *arg "  ");"
.SH ARGUMENTS
.IP "sdev" 12
scsi device receiving ioctl
.IP "cmd" 12
which ioctl is it
.IP "arg" 12
data associated with ioctl
.SH "DESCRIPTION"
The \fBscsi_ioctl\fP function differs from most ioctls in that it
does not take a major/minor number as the dev field.  Rather, it takes
a pointer to a \fIstruct scsi_device\fP.
