.TH "scsi_evt_thread" 9 "scsi_evt_thread" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_evt_thread \- send a uevent for each scsi event
.SH SYNOPSIS
.B "void" scsi_evt_thread
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
work struct for scsi_device

Dispatch queued events to their associated scsi_device kobjects
as uevents.
