.TH "scsi_free_host_dev" 9 "scsi_free_host_dev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_free_host_dev \- Free a scsi_device that points to the host adapter itself
.SH SYNOPSIS
.B "void" scsi_free_host_dev
.BI "(struct scsi_device *sdev "  ");"
.SH ARGUMENTS
.IP "sdev" 12
Host device to be freed
.SH "DESCRIPTION"
Lock status: None assumed.
.SH "RETURN"
Nothing
