.TH "sd_read_block_provisioning" 9 "sd_read_block_provisioning" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sd_read_block_provisioning \- Query provisioning VPD page
.SH SYNOPSIS
.B "void" sd_read_block_provisioning
.BI "(struct scsi_disk *sdkp "  ");"
.SH ARGUMENTS
.IP "sdkp" 12
disk to query
