.TH "sd_revalidate_disk" 9 "sd_revalidate_disk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sd_revalidate_disk \- called the first time a new disk is seen, performs disk spin up, read_capacity, etc.
.SH SYNOPSIS
.B "int" sd_revalidate_disk
.BI "(struct gendisk *disk "  ");"
.SH ARGUMENTS
.IP "disk" 12
struct gendisk we care about
