.TH "sdc_init_panel" 9 "sdc_init_panel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sdc_init_panel \- initialize a synchronous LCD panel.
.SH SYNOPSIS
.B "int" sdc_init_panel
.BI "(struct mx3fb_data *mx3fb "  ","
.BI "enum ipu_panel panel "  ","
.BI "uint32_t pixel_clk "  ","
.BI "uint16_t width "  ","
.BI "uint16_t height "  ","
.BI "uint16_t h_start_width "  ","
.BI "uint16_t h_sync_width "  ","
.BI "uint16_t h_end_width "  ","
.BI "uint16_t v_start_width "  ","
.BI "uint16_t v_sync_width "  ","
.BI "uint16_t v_end_width "  ","
.BI "const struct ipu_di_signal_cfg *sig "  ");"
.SH ARGUMENTS
.IP "mx3fb" 12
mx3fb context.
.IP "panel" 12
panel type.
.IP "pixel_clk" 12
desired pixel clock frequency in Hz.
.IP "width" 12
width of panel in pixels.
.IP "height" 12
height of panel in pixels.
.IP "h_start_width" 12
number of pixel clocks between the HSYNC signal pulse
and the start of valid data.
.IP "h_sync_width" 12
width of the HSYNC signal in units of pixel clocks.
.IP "h_end_width" 12
number of pixel clocks between the end of valid data
and the HSYNC signal for next line.
.IP "v_start_width" 12
number of lines between the VSYNC signal pulse and the
start of valid data.
.IP "v_sync_width" 12
width of the VSYNC signal in units of lines
.IP "v_end_width" 12
number of lines between the end of valid data and the
VSYNC signal for next frame.
.IP "sig" 12
bitfield of signal polarities for LCD interface.
.SH "RETURN"
0 on success or negative error code on failure.
