.TH "sdhci_arasan_register_sampleclk" 9 "sdhci_arasan_register_sampleclk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sdhci_arasan_register_sampleclk \- Register the sampleclk for a PHY to use
.SH SYNOPSIS
.B "int" sdhci_arasan_register_sampleclk
.BI "(struct sdhci_arasan_data *sdhci_arasan "  ","
.BI "struct clk *clk_xin "  ","
.BI "struct device *dev "  ");"
.SH ARGUMENTS
.IP "sdhci_arasan" 12
Our private data structure.
.IP "clk_xin" 12
Pointer to the functional clock
.IP "dev" 12
Pointer to our struct device.
.SH "DESCRIPTION"
Some PHY devices need to know what the actual card clock is.  In order for
them to find out, we'll provide a clock through the common clock framework
for them to query.
.SH "RETURN"
0 on success and error value on error
