.TH "sdma_seqfile_dump_sde" 9 "sdma_seqfile_dump_sde" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sdma_seqfile_dump_sde \- debugfs dump of sde
.SH SYNOPSIS
.B "void" sdma_seqfile_dump_sde
.BI "(struct seq_file *s "  ","
.BI "struct sdma_engine *sde "  ");"
.SH ARGUMENTS
.IP "s" 12
seq file
.IP "sde" 12
send dma engine to dump
.SH "DESCRIPTION"
This routine dumps the sde to the indicated seq file.
