.TH "sel_netnode_hashfn_ipv4" 9 "sel_netnode_hashfn_ipv4" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sel_netnode_hashfn_ipv4 \- IPv4 hashing function for the node table
.SH SYNOPSIS
.B "unsigned int" sel_netnode_hashfn_ipv4
.BI "(__be32 addr "  ");"
.SH ARGUMENTS
.IP "addr" 12
IPv4 address
.SH "DESCRIPTION"
This is the IPv4 hashing function for the node interface table, it returns
the bucket number for the given IP address.
