.TH "selinux_netlbl_skbuff_getsid" 9 "selinux_netlbl_skbuff_getsid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
selinux_netlbl_skbuff_getsid \- Get the sid of a packet using NetLabel
.SH SYNOPSIS
.B "int" selinux_netlbl_skbuff_getsid
.BI "(struct sk_buff *skb "  ","
.BI "u16 family "  ","
.BI "u32 *type "  ","
.BI "u32 *sid "  ");"
.SH ARGUMENTS
.IP "skb" 12
the packet
.IP "family" 12
protocol family
.IP "type" 12
NetLabel labeling protocol type
.IP "sid" 12
the SID
.SH "DESCRIPTION"
Call the NetLabel mechanism to get the security attributes of the given
packet and use those attributes to determine the correct context/SID to
assign to the packet.  Returns zero on success, negative values on failure.
