.TH "selinux_netlbl_sk_security_free" 9 "selinux_netlbl_sk_security_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
selinux_netlbl_sk_security_free \- Free the NetLabel fields
.SH SYNOPSIS
.B "void" selinux_netlbl_sk_security_free
.BI "(struct sk_security_struct *sksec "  ");"
.SH ARGUMENTS
.IP "sksec" 12
the sk_security_struct
.SH "DESCRIPTION"
Free all of the memory in the NetLabel fields of a sk_security_struct.
