.TH "selinux_secmark_enabled" 9 "selinux_secmark_enabled" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
selinux_secmark_enabled \- Check to see if SECMARK is currently enabled
.SH SYNOPSIS
.B "int" selinux_secmark_enabled
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"
This function checks the SECMARK reference counter to see if any SECMARK
targets are currently configured, if the reference counter is greater than
zero SECMARK is considered to be enabled.  Returns true (1) if SECMARK is
enabled, false (0) if SECMARK is disabled.  If the always_check_network
policy capability is enabled, SECMARK is always considered enabled.
