.TH "seq_pad" 9 "seq_pad" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
seq_pad \- write padding spaces to buffer
.SH SYNOPSIS
.B "void" seq_pad
.BI "(struct seq_file *m "  ","
.BI "char c "  ");"
.SH ARGUMENTS
.IP "m" 12
seq_file identifying the buffer to which data should be written
.IP "c" 12
the byte to append after padding if non-zero
