.TH "serial8250_register_8250_port" 9 "serial8250_register_8250_port" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
serial8250_register_8250_port \- register a serial port
.SH SYNOPSIS
.B "int" serial8250_register_8250_port
.BI "(struct uart_8250_port *up "  ");"
.SH ARGUMENTS
.IP "up" 12
serial port template

Configure the serial port specified by the request. If the
port exists and is in use, it is hung up and unregistered
first.

The port is then probed and if necessary the IRQ is autodetected
If this fails an error is returned.

On success the port is ready to use and the line number is returned.
