.TH "serial_port_shutdown" 9 "serial_port_shutdown" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
serial_port_shutdown \- shut down hardware
.SH SYNOPSIS
.B "void" serial_port_shutdown
.BI "(struct tty_port *tport "  ");"
.SH ARGUMENTS
.IP "tport" 12
tty port to shut down
.SH "DESCRIPTION"
Shut down a USB serial port. Serialized against activate by the
tport mutex and kept to matching open/close pairs
of calls by the initialized flag.

Not called if tty is console.
