.TH "set_rx_mode" 9 "set_rx_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
set_rx_mode \- Set SiS900 receive mode
.SH SYNOPSIS
.B "void" set_rx_mode
.BI "(struct net_device *net_dev "  ");"
.SH ARGUMENTS
.IP "net_dev" 12
the net device to be set

Set SiS900 receive mode for promiscuous, multicast, or broadcast mode.
And set the appropriate multicast filter.
Multicast hash table changes from 128 to 256 bits for 635M/B & 900B0.
