.TH "set_current_blocked" 9 "set_current_blocked" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
set_current_blocked \- change current->blocked mask
.SH SYNOPSIS
.B "void" set_current_blocked
.BI "(sigset_t *newset "  ");"
.SH ARGUMENTS
.IP "newset" 12
new mask
.SH "DESCRIPTION"
It is wrong to change ->blocked directly, this helper should be used
to ensure the process can't miss a shared signal we are going to block.
