.TH "set_hw_cap" 9 "set_hw_cap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
set_hw_cap \- Private Function used during initialization.
.SH SYNOPSIS
.B "void" set_hw_cap
.BI "(struct pp_hwmgr *hwmgr "  ","
.BI "bool setIt "  ","
.BI "enum phm_platform_caps cap "  ");"
.SH ARGUMENTS
.IP "hwmgr" 12
Pointer to the hardware manager.
.IP "setIt" 12
A flag indication if the capability should be set (TRUE) or reset (FALSE).
.IP "cap" 12
Which capability to set/reset.
