.TH "set_groups" 9 "set_groups" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
set_groups \- Change a group subscription in a set of credentials
.SH SYNOPSIS
.B "void" set_groups
.BI "(struct cred *new "  ","
.BI "struct group_info *group_info "  ");"
.SH ARGUMENTS
.IP "new" 12
The newly prepared set of credentials to alter
.IP "group_info" 12
The group list to install
