.TH "set_page_address" 9 "set_page_address" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
set_page_address \- set a page's virtual address
.SH SYNOPSIS
.B "void" set_page_address
.BI "(struct page *page "  ","
.BI "void *virtual "  ");"
.SH ARGUMENTS
.IP "page" 12
\fIstruct page\fP to set
.IP "virtual" 12
virtual address to use
