.TH "setup_link_status_change_wq" 9 "setup_link_status_change_wq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
setup_link_status_change_wq \- Sets up the mtu status change work
.SH SYNOPSIS
.B "int" setup_link_status_change_wq
.BI "(struct net_device *netdev "  ");"
.SH ARGUMENTS
.IP "netdev" 12
network device
