.TH "sh_early_platform_add_devices" 9 "sh_early_platform_add_devices" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sh_early_platform_add_devices \- adds a number of early platform devices
.SH SYNOPSIS
.B "void" sh_early_platform_add_devices
.BI "(struct platform_device **devs "  ","
.BI "int num "  ");"
.SH ARGUMENTS
.IP "devs" 12
array of early platform devices to add
.IP "num" 12
number of early platform devices in array
.SH "DESCRIPTION"
Used by early architecture code to register early platform devices and
their platform data.
