.TH "sifive_prci_hfpclkpllsel_use_hfpclkpll" 9 "sifive_prci_hfpclkpllsel_use_hfpclkpll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sifive_prci_hfpclkpllsel_use_hfpclkpll \- switch the HFPCLKPLL mux to output HFPCLKPLL
.SH SYNOPSIS
.B "void" sifive_prci_hfpclkpllsel_use_hfpclkpll
.BI "(struct __prci_data *pd "  ");"
.SH ARGUMENTS
.IP "pd" 12
struct __prci_data * for the PRCI containing the HFPCLKPLL mux reg
.SH "DESCRIPTION"
Switch the HFPCLKPLL mux to the HFPCLKPLL output clock; return once complete.
.SH "CONTEXT"
Any context.  Caller must prevent concurrent changes to the
PRCI_HFPCLKPLLSEL_OFFSET register.
