.TH "sigmadsp_restrict_params" 9 "sigmadsp_restrict_params" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sigmadsp_restrict_params \- Applies DSP firmware specific constraints
.SH SYNOPSIS
.B "int" sigmadsp_restrict_params
.BI "(struct sigmadsp *sigmadsp "  ","
.BI "struct snd_pcm_substream *substream "  ");"
.SH ARGUMENTS
.IP "sigmadsp" 12
The sigmadsp instance
.IP "substream" 12
The substream to restrict
.SH "DESCRIPTION"
Applies samplerate constraints that may be required by the firmware Should
typically be called from the CODEC/component drivers startup callback.

Returns 0 on success, a negative error code otherwise.
