.TH "siimage_selreg" 9 "siimage_selreg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
siimage_selreg \- return register base
.SH SYNOPSIS
.B "unsigned long" siimage_selreg
.BI "(ide_hwif_t *hwif "  ","
.BI "int r "  ");"
.SH ARGUMENTS
.IP "hwif" 12
interface
.IP "r" 12
config offset

Turn a config register offset into the right address in either
PCI space or MMIO space to access the control register in question
Thankfully this is a configuration operation, so isn't performance
critical.
