.TH "sil680_selreg" 9 "sil680_selreg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sil680_selreg \- return register base
.SH SYNOPSIS
.B "unsigned long" sil680_selreg
.BI "(struct ata_port *ap "  ","
.BI "int r "  ");"
.SH ARGUMENTS
.IP "ap" 12
ATA interface
.IP "r" 12
config offset

Turn a config register offset into the right address in PCI space
to access the control register in question.

Thankfully this is a configuration operation so isn't performance
criticial.
