.TH "simple_nosetlease" 9 "simple_nosetlease" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
simple_nosetlease \- generic helper for prohibiting leases
.SH SYNOPSIS
.B "int" simple_nosetlease
.BI "(struct file *filp "  ","
.BI "long arg "  ","
.BI "struct file_lock **flp "  ","
.BI "void **priv "  ");"
.SH ARGUMENTS
.IP "filp" 12
file pointer
.IP "arg" 12
type of lease to obtain
.IP "flp" 12
new lease supplied for insertion
.IP "priv" 12
private data for lm_setup operation
.SH "DESCRIPTION"
Generic helper for filesystems that do not wish to allow leases to be set.
All arguments are ignored and it just returns -EINVAL.
