.TH "sis900_finish_xmit" 9 "sis900_finish_xmit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sis900_finish_xmit \- finish up transmission of packets
.SH SYNOPSIS
.B "void" sis900_finish_xmit
.BI "(struct net_device *net_dev "  ");"
.SH ARGUMENTS
.IP "net_dev" 12
the net device to be transmitted on

Check for error condition and free socket buffer etc
schedule for more transmission as needed
.SH "NOTE"
This function is called by interrupt handler,
don't do "too much" work here
