.TH "sis900_reset" 9 "sis900_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sis900_reset \- Reset sis900 MAC
.SH SYNOPSIS
.B "void" sis900_reset
.BI "(struct net_device *net_dev "  ");"
.SH ARGUMENTS
.IP "net_dev" 12
the net device to reset

reset sis900 MAC and wait until finished
reset through command register
change backoff algorithm for 900B0 & 635 M/B
