.TH "skb_gso_validate_mac_len" 9 "skb_gso_validate_mac_len" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
skb_gso_validate_mac_len \- Will a split GSO skb fit in a given length?
.SH SYNOPSIS
.B "bool" skb_gso_validate_mac_len
.BI "(const struct sk_buff *skb "  ","
.BI "unsigned int len "  ");"
.SH ARGUMENTS
.IP "skb" 12
GSO skb
.IP "len" 12
length to validate against
.SH "DESCRIPTION"
skb_gso_validate_mac_len validates if a given skb will fit a wanted
length once split, including L2, L3 and L4 headers and the payload.
