.TH "skb_queue_tail" 9 "skb_queue_tail" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
skb_queue_tail \- queue a buffer at the list tail
.SH SYNOPSIS
.B "void" skb_queue_tail
.BI "(struct sk_buff_head *list "  ","
.BI "struct sk_buff *newsk "  ");"
.SH ARGUMENTS
.IP "list" 12
list to use
.IP "newsk" 12
buffer to queue

Queue a buffer at the tail of the list. This function takes the
list lock and can be used safely with other locking \fIsk_buff\fP functions
safely.

A buffer cannot be placed on two lists at the same time.
