.TH "skb_dequeue_tail" 9 "skb_dequeue_tail" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
skb_dequeue_tail \- remove from the tail of the queue
.SH SYNOPSIS
.B "struct sk_buff *" skb_dequeue_tail
.BI "(struct sk_buff_head *list "  ");"
.SH ARGUMENTS
.IP "list" 12
list to dequeue from

Remove the tail of the list. The list lock is taken so the function
may be used safely with other locking list functions. The tail item is
returned or NULL if the list is empty.
