.TH "skb_copy_and_csum_datagram" 9 "skb_copy_and_csum_datagram" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
skb_copy_and_csum_datagram \- Copy datagram to an iovec iterator and update a checksum.
.SH SYNOPSIS
.B "int" skb_copy_and_csum_datagram
.BI "(const struct sk_buff *skb "  ","
.BI "int offset "  ","
.BI "struct iov_iter *to "  ","
.BI "int len "  ","
.BI "__wsum *csump "  ");"
.SH ARGUMENTS
.IP "skb" 12
buffer to copy
.IP "offset" 12
offset in the buffer to start copying from
.IP "to" 12
iovec iterator to copy to
.IP "len" 12
amount of data to copy from buffer to iovec
.IP "csump" 12
checksum pointer
