.TH "sl82c105_reset_engine" 9 "sl82c105_reset_engine" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sl82c105_reset_engine \- Reset the DMA engine
.SH SYNOPSIS
.B "void" sl82c105_reset_engine
.BI "(struct ata_port *ap "  ");"
.SH ARGUMENTS
.IP "ap" 12
ATA interface

The sl82c105 has some serious problems with the DMA engine
when transfers don't run as expected or ATAPI is used. The
recommended fix is to reset the engine each use using a chip
test register.
