.TH "slim_get_logical_addr" 9 "slim_get_logical_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
slim_get_logical_addr \- get/allocate logical address of a SLIMbus device.
.SH SYNOPSIS
.B "int" slim_get_logical_addr
.BI "(struct slim_device *sbdev "  ");"
.SH ARGUMENTS
.IP "sbdev" 12
client handle requesting the address.
.SH "RETURN"
zero if a logical address is valid or a new logical address
has been assigned. error code in case of error.
