.TH "slim_do_transfer" 9 "slim_do_transfer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
slim_do_transfer \- Process a SLIMbus-messaging transaction
.SH SYNOPSIS
.B "int" slim_do_transfer
.BI "(struct slim_controller *ctrl "  ","
.BI "struct slim_msg_txn *txn "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
Controller handle
.IP "txn" 12
Transaction to be sent over SLIMbus
.SH "DESCRIPTION"
Called by controller to transmit messaging transactions not dealing with
Interface/Value elements. (e.g. transmittting a message to assign logical
address to a slave device
.SH "RETURN"
-ETIMEDOUT: If transmission of this message timed out
(e.g. due to bus lines not being clocked or driven by controller)
