.TH "smack_socket_getpeersec_stream" 9 "smack_socket_getpeersec_stream" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smack_socket_getpeersec_stream \- pull in packet label
.SH SYNOPSIS
.B "int" smack_socket_getpeersec_stream
.BI "(struct socket *sock "  ","
.BI "char __user *optval "  ","
.BI "int __user *optlen "  ","
.BI "unsigned len "  ");"
.SH ARGUMENTS
.IP "sock" 12
the socket
.IP "optval" 12
user's destination
.IP "optlen" 12
size thereof
.IP "len" 12
max thereof
.SH "DESCRIPTION"
returns zero on success, an error code otherwise
