.TH "smack_inode_permission" 9 "smack_inode_permission" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smack_inode_permission \- Smack version of permission()
.SH SYNOPSIS
.B "int" smack_inode_permission
.BI "(struct inode *inode "  ","
.BI "int mask "  ");"
.SH ARGUMENTS
.IP "inode" 12
the inode in question
.IP "mask" 12
the access requested
.SH "DESCRIPTION"
This is the important Smack hook.

Returns 0 if access is permitted, an error code otherwise
