.TH "smack_flags_to_may" 9 "smack_flags_to_may" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smack_flags_to_may \- convert S_ to MAY_ values
.SH SYNOPSIS
.B "int" smack_flags_to_may
.BI "(int flags "  ");"
.SH ARGUMENTS
.IP "flags" 12
the S_ value
.SH "DESCRIPTION"
Returns the equivalent MAY_ value
