.TH "smb311_update_preauth_hash" 9 "smb311_update_preauth_hash" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smb311_update_preauth_hash \- update @ses hash with the packet data in @iov
.SH SYNOPSIS
.B "int" smb311_update_preauth_hash
.BI "(struct cifs_ses *ses "  ","
.BI "struct kvec *iov "  ","
.BI "int nvec "  ");"
.SH ARGUMENTS
.IP "ses" 12
server session structure
.IP "iov" 12
array containing the SMB request we will send to the server
.IP "nvec" 12
number of array entries for the iov
.SH "DESCRIPTION"

Assumes \fIiov\fP does not contain the rfc1002 length and iov[0] has the
SMB2 header.
