.TH "smb347_charging_status" 9 "smb347_charging_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smb347_charging_status \- returns status of charging
.SH SYNOPSIS
.B "int" smb347_charging_status
.BI "(struct smb347_charger *smb "  ");"
.SH ARGUMENTS
.IP "smb" 12
pointer to smb347 charger instance
.SH "DESCRIPTION"
Function returns charging status. 0 means no charging is in progress,
1 means pre-charging, 2 fast-charging and 3 taper-charging.
