.TH "smk_perm_from_str" 9 "smk_perm_from_str" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smk_perm_from_str \- parse smack accesses from a text string
.SH SYNOPSIS
.B "int" smk_perm_from_str
.BI "(const char *string "  ");"
.SH ARGUMENTS
.IP "string" 12
a text string that contains a Smack accesses code
.SH "DESCRIPTION"
Returns an integer with respective bits set for specified accesses.
