.TH "smpboot_register_percpu_thread" 9 "smpboot_register_percpu_thread" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smpboot_register_percpu_thread \- Register a per_cpu thread related to hotplug
.SH SYNOPSIS
.B "int" smpboot_register_percpu_thread
.BI "(struct smp_hotplug_thread *plug_thread "  ");"
.SH ARGUMENTS
.IP "plug_thread" 12
Hotplug thread descriptor
.SH "DESCRIPTION"
Creates and starts the threads on all online cpus.
