.TH "smu7_thermal_stop_thermal_controller" 9 "smu7_thermal_stop_thermal_controller" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smu7_thermal_stop_thermal_controller \- Uninitialize the thermal controller. Currently just disables alerts.
.SH SYNOPSIS
.B "int" smu7_thermal_stop_thermal_controller
.BI "(struct pp_hwmgr *hwmgr "  ");"
.SH ARGUMENTS
.IP "hwmgr" 12
The address of the hardware manager.
