.TH "snd_pcm_format_physical_width" 9 "snd_pcm_format_physical_width" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_pcm_format_physical_width \- return the physical bit-width of the format
.SH SYNOPSIS
.B "int" snd_pcm_format_physical_width
.BI "(snd_pcm_format_t format "  ");"
.SH ARGUMENTS
.IP "format" 12
the format to check
.SH "RETURN"
The physical bit-width of the format, or a negative error code
if unknown format.
