.TH "snd_vx_create" 9 "snd_vx_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_vx_create \- constructor for struct vx_core
.SH SYNOPSIS
.B "struct vx_core *" snd_vx_create
.BI "(struct snd_card *card "  ","
.BI "const struct snd_vx_hardware *hw "  ","
.BI "const struct snd_vx_ops *ops "  ","
.BI "int extra_size "  ");"
.SH ARGUMENTS
.IP "card" 12
card instance
.IP "hw" 12
hardware specific record
.IP "ops" 12
VX ops pointer
.IP "extra_size" 12
extra byte size to allocate appending to chip
.SH "DESCRIPTION"
this function allocates the instance and prepare for the hardware
initialization.

return the instance pointer if successful, NULL in error.
