.TH "snd_soc_dapm_get_volsw" 9 "snd_soc_dapm_get_volsw" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_soc_dapm_get_volsw \- dapm mixer get callback
.SH SYNOPSIS
.B "int" snd_soc_dapm_get_volsw
.BI "(struct snd_kcontrol *kcontrol "  ","
.BI "struct snd_ctl_elem_value *ucontrol "  ");"
.SH ARGUMENTS
.IP "kcontrol" 12
mixer control
.IP "ucontrol" 12
control element information
.SH "DESCRIPTION"
Callback to get the value of a dapm mixer control.

Returns 0 for success.
