.TH "snd_soc_find_dai_link" 9 "snd_soc_find_dai_link" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_soc_find_dai_link \- Find a DAI link
.SH SYNOPSIS
.B "struct snd_soc_dai_link *" snd_soc_find_dai_link
.BI "(struct snd_soc_card *card "  ","
.BI "int id "  ","
.BI "const char *name "  ","
.BI "const char *stream_name "  ");"
.SH ARGUMENTS
.IP "card" 12
soc card
.IP "id" 12
DAI link ID to match
.IP "name" 12
DAI link name to match, optional
.IP "stream_name" 12
DAI link stream name to match, optional
.SH "DESCRIPTION"
This function will search all existing DAI links of the soc card to
find the link of the same ID. Since DAI links may not have their
unique ID, so name and stream name should also match if being
specified.
.SH "RETURN"
pointer of DAI link, or NULL if not found.
