.TH "snd_ctl_new1" 9 "snd_ctl_new1" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_ctl_new1 \- create a control instance from the template
.SH SYNOPSIS
.B "struct snd_kcontrol *" snd_ctl_new1
.BI "(const struct snd_kcontrol_new *ncontrol "  ","
.BI "void *private_data "  ");"
.SH ARGUMENTS
.IP "ncontrol" 12
the initialization record
.IP "private_data" 12
the private data to set
.SH "DESCRIPTION"
Allocates a new struct snd_kcontrol instance and initialize from the given
template.  When the access field of ncontrol is 0, it's assumed as
READWRITE access. When the count field is 0, it's assumes as one.
.SH "RETURN"
The pointer of the newly generated instance, or NULL on failure.
