.TH "snd_free_dev_iram" 9 "snd_free_dev_iram" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_free_dev_iram \- free allocated specific memory from on-chip internal ram
.SH SYNOPSIS
.B "void" snd_free_dev_iram
.BI "(struct snd_dma_buffer *dmab "  ");"
.SH ARGUMENTS
.IP "dmab" 12
buffer allocation record to store the allocated data
