.TH "snd_interval_mulkdiv" 9 "snd_interval_mulkdiv" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_interval_mulkdiv \- refine the interval value
.SH SYNOPSIS
.B "void" snd_interval_mulkdiv
.BI "(const struct snd_interval *a "  ","
.BI "unsigned int k "  ","
.BI "const struct snd_interval *b "  ","
.BI "struct snd_interval *c "  ");"
.SH ARGUMENTS
.IP "a" 12
dividend 1
.IP "k" 12
dividend 2 (as integer)
.IP "b" 12
divisor
.IP "c" 12
result
.SH "DESCRIPTION"
c = a * k / b

Returns non-zero if the value is changed, zero if not changed.
