.TH "snd_hdac_make_cmd" 9 "snd_hdac_make_cmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hdac_make_cmd \- compose a 32bit command word to be sent to the HD-audio controller
.SH SYNOPSIS
.B "unsigned int" snd_hdac_make_cmd
.BI "(struct hdac_device *codec "  ","
.BI "hda_nid_t nid "  ","
.BI "unsigned int verb "  ","
.BI "unsigned int parm "  ");"
.SH ARGUMENTS
.IP "codec" 12
the codec object
.IP "nid" 12
NID to encode
.IP "verb" 12
verb to encode
.IP "parm" 12
parameter to encode
.SH "DESCRIPTION"
Return an encoded command verb or -1 for error.
