.TH "snd_hda_get_hint" 9 "snd_hda_get_hint" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hda_get_hint \- Look for hint string
.SH SYNOPSIS
.B "const char *" snd_hda_get_hint
.BI "(struct hda_codec *codec "  ","
.BI "const char *key "  ");"
.SH ARGUMENTS
.IP "codec" 12
the HDA codec
.IP "key" 12
the hint key string
.SH "DESCRIPTION"
Look for a hint key/value pair matching with the given key string
and returns the value string.  If nothing found, returns NULL.
