.TH "snd_vx_dsp_boot" 9 "snd_vx_dsp_boot" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_vx_dsp_boot \- load the DSP boot
.SH SYNOPSIS
.B "int" snd_vx_dsp_boot
.BI "(struct vx_core *chip "  ","
.BI "const struct firmware *boot "  ");"
.SH ARGUMENTS
.IP "chip" 12
VX core instance
.IP "boot" 12
firmware data
