.TH "snd_soc_dapm_new_widgets" 9 "snd_soc_dapm_new_widgets" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_soc_dapm_new_widgets \- add new dapm widgets
.SH SYNOPSIS
.B "int" snd_soc_dapm_new_widgets
.BI "(struct snd_soc_card *card "  ");"
.SH ARGUMENTS
.IP "card" 12
card to be checked for new dapm widgets
.SH "DESCRIPTION"
Checks the codec for any new dapm widgets and creates them if found.

Returns 0 for success.
