.TH "snd_pcm_format_name" 9 "snd_pcm_format_name" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_pcm_format_name \- Return a name string for the given PCM format
.SH SYNOPSIS
.B "const char *" snd_pcm_format_name
.BI "(snd_pcm_format_t format "  ");"
.SH ARGUMENTS
.IP "format" 12
PCM format
