.TH "snd_hdac_is_supported_format" 9 "snd_hdac_is_supported_format" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hdac_is_supported_format \- Check the validity of the format
.SH SYNOPSIS
.B "bool" snd_hdac_is_supported_format
.BI "(struct hdac_device *codec "  ","
.BI "hda_nid_t nid "  ","
.BI "unsigned int format "  ");"
.SH ARGUMENTS
.IP "codec" 12
the codec object
.IP "nid" 12
NID to check
.IP "format" 12
the HD-audio format value to check
.SH "DESCRIPTION"
Check whether the given node supports the format value.

Returns true if supported, false if not.
