.TH "snd_soc_dapm_stream_event" 9 "snd_soc_dapm_stream_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_soc_dapm_stream_event \- send a stream event to the dapm core
.SH SYNOPSIS
.B "void" snd_soc_dapm_stream_event
.BI "(struct snd_soc_pcm_runtime *rtd "  ","
.BI "int stream "  ","
.BI "int event "  ");"
.SH ARGUMENTS
.IP "rtd" 12
PCM runtime data
.IP "stream" 12
stream name
.IP "event" 12
stream event
.SH "DESCRIPTION"
Sends a stream event to the dapm core. The core then makes any
necessary widget power changes.

Returns 0 for success else error.
