.TH "snd_rawmidi_receive" 9 "snd_rawmidi_receive" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_rawmidi_receive \- receive the input data from the device
.SH SYNOPSIS
.B "int" snd_rawmidi_receive
.BI "(struct snd_rawmidi_substream *substream "  ","
.BI "const unsigned char *buffer "  ","
.BI "int count "  ");"
.SH ARGUMENTS
.IP "substream" 12
the rawmidi substream
.IP "buffer" 12
the buffer pointer
.IP "count" 12
the data size to read
.SH "DESCRIPTION"
Reads the data from the internal buffer.
.SH "RETURN"
The size of read data, or a negative error code on failure.
