.TH "snd_hda_jack_poll_all" 9 "snd_hda_jack_poll_all" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hda_jack_poll_all \- Poll all jacks
.SH SYNOPSIS
.B "void" snd_hda_jack_poll_all
.BI "(struct hda_codec *codec "  ");"
.SH ARGUMENTS
.IP "codec" 12
the HDA codec
.SH "DESCRIPTION"
Poll all detectable jacks with dirty flag, update the status, call
callbacks and call \fBsnd_hda_jack_report_sync\fP if any changes are found.
