.TH "snd_ctl_register_ioctl_compat" 9 "snd_ctl_register_ioctl_compat" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_ctl_register_ioctl_compat \- register the device-specific 32bit compat control-ioctls
.SH SYNOPSIS
.B "int" snd_ctl_register_ioctl_compat
.BI "(snd_kctl_ioctl_func_t fcn "  ");"
.SH ARGUMENTS
.IP "fcn" 12
ioctl callback function
