.TH "snd_soc_add_card_controls" 9 "snd_soc_add_card_controls" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_soc_add_card_controls \- add an array of controls to a SoC card. Convenience function to add a list of controls.
.SH SYNOPSIS
.B "int" snd_soc_add_card_controls
.BI "(struct snd_soc_card *soc_card "  ","
.BI "const struct snd_kcontrol_new *controls "  ","
.BI "int num_controls "  ");"
.SH ARGUMENTS
.IP "soc_card" 12
SoC card to add controls to
.IP "controls" 12
array of controls to add
.IP "num_controls" 12
number of elements in the array
.SH "DESCRIPTION"
Return 0 for success, else error.
