.TH "sock_register" 9 "sock_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sock_register \- add a socket protocol handler
.SH SYNOPSIS
.B "int" sock_register
.BI "(const struct net_proto_family *ops "  ");"
.SH ARGUMENTS
.IP "ops" 12
description of protocol

This function is called by a protocol handler that wants to
advertise its address family, and have it linked into the
socket interface. The value ops->family corresponds to the
socket system call protocol family.
