.TH "soctherm_init_hw_throt_cdev" 9 "soctherm_init_hw_throt_cdev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
soctherm_init_hw_throt_cdev \- Parse the HW throttle configurations and register them as cooling devices.
.SH SYNOPSIS
.B "void" soctherm_init_hw_throt_cdev
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
Pointer to platform_device struct
