.TH "soctherm_oc_irq_enable" 9 "soctherm_oc_irq_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
soctherm_oc_irq_enable \- Enables the SOC_THERM over-current interrupt queue
.SH SYNOPSIS
.B "void" soctherm_oc_irq_enable
.BI "(struct irq_data *data "  ");"
.SH ARGUMENTS
.IP "data" 12
irq_data structure of the chip
.SH "DESCRIPTION"
Sets the irq_enable bit of SOC_THERM allowing SOC_THERM
to respond to over-current interrupts.
