.TH "soctherm_oc_irq_lock" 9 "soctherm_oc_irq_lock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
soctherm_oc_irq_lock \- locks the over-current interrupt request
.SH SYNOPSIS
.B "void" soctherm_oc_irq_lock
.BI "(struct irq_data *data "  ");"
.SH ARGUMENTS
.IP "data" 12
Interrupt request data
.SH "DESCRIPTION"
Looks up the chip data from \fIdata\fP and locks the mutex associated with
a particular over-current interrupt request.
