.TH "spear_smi_remove" 9 "spear_smi_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spear_smi_remove \- Exit routine
.SH SYNOPSIS
.B "int" spear_smi_remove
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
platform device structure
.SH "DESCRIPTION"
free all allocations and delete the partitions.
