.TH "speedstep_set_state" 9 "speedstep_set_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
speedstep_set_state \- set the SpeedStep state
.SH SYNOPSIS
.B "void" speedstep_set_state
.BI "(unsigned int state "  ");"
.SH ARGUMENTS
.IP "state" 12
new processor frequency state (SPEEDSTEP_LOW or SPEEDSTEP_HIGH)

Tries to change the SpeedStep state.  Can be called from
smp_call_function_single.
