.TH "spi_nor_write_data" 9 "spi_nor_write_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_nor_write_data \- write data to flash memory
.SH SYNOPSIS
.B "ssize_t" spi_nor_write_data
.BI "(struct spi_nor *nor "  ","
.BI "loff_t to "  ","
.BI "size_t len "  ","
.BI "const u8 *buf "  ");"
.SH ARGUMENTS
.IP "nor" 12
pointer to 'struct spi_nor'
.IP "to" 12
offset to write to
.IP "len" 12
number of bytes to write
.IP "buf" 12
pointer to src buffer
.SH "RETURN"
number of bytes written successfully, -errno otherwise
