.TH "spi_set_cs_timing" 9 "spi_set_cs_timing" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_set_cs_timing \- configure CS setup, hold, and inactive delays
.SH SYNOPSIS
.B "int" spi_set_cs_timing
.BI "(struct spi_device *spi "  ","
.BI "struct spi_delay *setup "  ","
.BI "struct spi_delay *hold "  ","
.BI "struct spi_delay *inactive "  ");"
.SH ARGUMENTS
.IP "spi" 12
the device that requires specific CS timing configuration
.IP "setup" 12
CS setup time specified via \fIspi_delay\fP
.IP "hold" 12
CS hold time specified via \fIspi_delay\fP
.IP "inactive" 12
CS inactive delay between transfers specified via \fIspi_delay\fP
.SH "RETURN"
zero on success, else a negative error code.
