.TH "spi_nor_write_sr" 9 "spi_nor_write_sr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_nor_write_sr \- Write the Status Register.
.SH SYNOPSIS
.B "int" spi_nor_write_sr
.BI "(struct spi_nor *nor "  ","
.BI "const u8 *sr "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "nor" 12
pointer to 'struct spi_nor'.
.IP "sr" 12
pointer to DMA-able buffer to write to the Status Register.
.IP "len" 12
number of bytes to write to the Status Register.
.SH "RETURN"
0 on success, -errno otherwise.
