.TH "spi_test_execute_msg" 9 "spi_test_execute_msg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_test_execute_msg \- default implementation to run a test
.SH SYNOPSIS
.B "int" spi_test_execute_msg
.BI "(struct spi_device *spi "  ","
.BI "struct spi_test *test "  ","
.BI "void *tx "  ","
.BI "void *rx "  ");"
.SH ARGUMENTS
.IP "spi" 12
\fIspi_device\fP on which to run the \fIspi_message\fP
.IP "test" 12
the test to execute, which already contains \fImsg\fP
.IP "tx" 12
the tx buffer allocated for the test sequence
.IP "rx" 12
the rx buffer allocated for the test sequence
.SH "RETURN"
error code of spi_sync as well as basic error checking
