.TH "spi_nor_wait_till_ready_with_timeout" 9 "spi_nor_wait_till_ready_with_timeout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_nor_wait_till_ready_with_timeout \- Service routine to read the Status Register until ready, or timeout occurs.
.SH SYNOPSIS
.B "int" spi_nor_wait_till_ready_with_timeout
.BI "(struct spi_nor *nor "  ","
.BI "unsigned long timeout_jiffies "  ");"
.SH ARGUMENTS
.IP "nor" 12
pointer to "struct spi_nor".
.IP "timeout_jiffies" 12
jiffies to wait until timeout.
.SH "RETURN"
0 on success, -errno otherwise.
