.TH "spi_nor_late_init_params" 9 "spi_nor_late_init_params" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_nor_late_init_params \- Late initialization of default flash parameters.
.SH SYNOPSIS
.B "void" spi_nor_late_init_params
.BI "(struct spi_nor *nor "  ");"
.SH ARGUMENTS
.IP "nor" 12
pointer to a 'struct spi_nor'
.SH "DESCRIPTION"
Used to set default flash parameters and settings when the ->\fBdefault_init\fP
hook or the SFDP parser let voids.
