.TH "spider_net_pass_skb_up" 9 "spider_net_pass_skb_up" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spider_net_pass_skb_up \- takes an skb from a descriptor and passes it on
.SH SYNOPSIS
.B "void" spider_net_pass_skb_up
.BI "(struct spider_net_descr *descr "  ","
.BI "struct spider_net_card *card "  ");"
.SH ARGUMENTS
.IP "descr" 12
descriptor to process
.IP "card" 12
card structure
.SH "DESCRIPTION"
Fills out skb structure and passes the data to the stack.
The descriptor state is not changed.
