.TH "spider_net_setup_pci_dev" 9 "spider_net_setup_pci_dev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spider_net_setup_pci_dev \- sets up the device in terms of PCI operations
.SH SYNOPSIS
.B "struct spider_net_card *" spider_net_setup_pci_dev
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device
.SH "DESCRIPTION"
Returns the card structure or NULL if any errors occur

spider_net_setup_pci_dev initializes pdev and together with the
functions called in spider_net_open configures the device so that
data can be transferred over it
The net_device structure is attached to the card structure, if the
function returns without error.
