.TH "spider_net_set_multi" 9 "spider_net_set_multi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spider_net_set_multi \- sets multicast addresses and promisc flags
.SH SYNOPSIS
.B "void" spider_net_set_multi
.BI "(struct net_device *netdev "  ");"
.SH ARGUMENTS
.IP "netdev" 12
interface device structure
.SH "DESCRIPTION"
spider_net_set_multi configures multicast addresses as needed for the
netdev interface. It also sets up multicast, allmulti and promisc
flags appropriately
