.TH "spider_net_set_mac" 9 "spider_net_set_mac" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spider_net_set_mac \- sets the MAC of an interface
.SH SYNOPSIS
.B "int" spider_net_set_mac
.BI "(struct net_device *netdev "  ","
.BI "void *p "  ");"
.SH ARGUMENTS
.IP "netdev" 12
interface device structure
.IP "p" 12
pointer to new MAC address
.SH "DESCRIPTION"
Returns 0 on success, <0 on failure. Currently, we don't support this
and will always return EOPNOTSUPP.
