.TH "spu_mb_init" 9 "spu_mb_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spu_mb_init \- Initialize mailbox client. Request ownership of a mailbox channel for the SPU being probed.
.SH SYNOPSIS
.B "int" spu_mb_init
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
SPU driver device structure
.SH "RETURN"
0 if successful
< 0 otherwise
