.TH "spu_save" 9 "spu_save" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spu_save \- SPU context save, with locking.
.SH SYNOPSIS
.B "int" spu_save
.BI "(struct spu_state *prev "  ","
.BI "struct spu *spu "  ");"
.SH ARGUMENTS
.IP "prev" 12
pointer to SPU context save area, to be saved.
.IP "spu" 12
pointer to SPU iomem structure.
.SH "DESCRIPTION"
Acquire locks, perform the save operation then return.
