.TH "spu_deactivate" 9 "spu_deactivate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spu_deactivate \- unbind a context from it's physical spu
.SH SYNOPSIS
.B "void" spu_deactivate
.BI "(struct spu_context *ctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
spu context to unbind
.SH "DESCRIPTION"
Unbind \fIctx\fP from the physical spu it is running on and schedule
the highest priority context to run on the freed physical spu.
