.TH "sq_remap" 9 "sq_remap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sq_remap \- Map a physical address through the Store Queues
.SH SYNOPSIS
.B "unsigned long" sq_remap
.BI "(unsigned long phys "  ","
.BI "unsigned int size "  ","
.BI "const char *name "  ","
.BI "pgprot_t prot "  ");"
.SH ARGUMENTS
.IP "phys" 12
Physical address of mapping.
.IP "size" 12
Length of mapping.
.IP "name" 12
User invoking mapping.
.IP "prot" 12
Protection bits.
.SH "DESCRIPTION"
Remaps the physical address \fIphys\fP through the next available store queue
address of \fIsize\fP length. \fIname\fP is logged at boot time as well as through
the sysfs interface.
