.TH "sr_register_class" 9 "sr_register_class" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sr_register_class \- API to register a smartreflex class parameters.
.SH SYNOPSIS
.B "int" sr_register_class
.BI "(struct omap_sr_class_data *class_data "  ");"
.SH ARGUMENTS
.IP "class_data" 12
The structure containing various sr class specific data.
.SH "DESCRIPTION"
This API is to be called by the smartreflex class driver to register itself
with the smartreflex driver during init. Returns 0 on success else the
error value.
