.TH "srp_reconnect_work" 9 "srp_reconnect_work" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
srp_reconnect_work \- reconnect and schedule a new attempt if necessary
.SH SYNOPSIS
.B "void" srp_reconnect_work
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
Work structure used for scheduling this operation.
