.TH "srp_rport_del" 9 "srp_rport_del" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
srp_rport_del \- remove a SRP remote port
.SH SYNOPSIS
.B "void" srp_rport_del
.BI "(struct srp_rport *rport "  ");"
.SH ARGUMENTS
.IP "rport" 12
SRP remote port to remove
.SH "DESCRIPTION"
Removes the specified SRP remote port.
