.TH "srp_start_tl_fail_timers" 9 "srp_start_tl_fail_timers" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
srp_start_tl_fail_timers \- start the transport layer failure timers
.SH SYNOPSIS
.B "void" srp_start_tl_fail_timers
.BI "(struct srp_rport *rport "  ");"
.SH ARGUMENTS
.IP "rport" 12
SRP target port.
.SH "DESCRIPTION"
Start the transport layer fast I/O failure and device loss timers. Do not
modify a timer that was already started.
