.TH "srpt_get_ioc" 9 "srpt_get_ioc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
srpt_get_ioc \- write IOControllerprofile to a management datagram
.SH SYNOPSIS
.B "void" srpt_get_ioc
.BI "(struct srpt_port *sport "  ","
.BI "u32 slot "  ","
.BI "struct ib_dm_mad *mad "  ");"
.SH ARGUMENTS
.IP "sport" 12
HCA port through which the MAD has been received.
.IP "slot" 12
Slot number specified in DM_ATTR_IOC_PROFILE query.
.IP "mad" 12
Datagram that will be sent as response to DM_ATTR_IOC_PROFILE.
.SH "DESCRIPTION"
See also section 16.3.3.4 IOControllerProfile in the InfiniBand
Architecture Specification. See also section B.7, table B.7 in the SRP
r16a document.
