.TH "ssam_cplt_destroy" 9 "ssam_cplt_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssam_cplt_destroy \- Deinitialize the completion system.
.SH SYNOPSIS
.B "void" ssam_cplt_destroy
.BI "(struct ssam_cplt *cplt "  ");"
.SH ARGUMENTS
.IP "cplt" 12
The completion system to deinitialize.
.SH "DESCRIPTION"
Deinitialize the given completion system and ensure that all pending, i.e.
yet-to-be-completed, event items and requests have been handled.
