.TH "ssam_controller_destroy" 9 "ssam_controller_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssam_controller_destroy \- Destroy the controller and free its resources.
.SH SYNOPSIS
.B "void" ssam_controller_destroy
.BI "(struct ssam_controller *ctrl "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
The controller.
.SH "DESCRIPTION"
Ensures that all resources associated with the controller get freed. This
function should only be called after the controller has been stopped via
\fBssam_controller_shutdown\fP. In general, this function should not be called
directly. The only valid place to call this function directly is during
initialization, before the controller has been fully initialized and passed
to other processes. This function is called automatically when the
reference count of the controller reaches zero.

This function must be called with the main controller lock held (i.e. by
calling \fBssam_controller_lock\fP).
