.TH "ssh_ptl_should_drop_dsq_packet" 9 "ssh_ptl_should_drop_dsq_packet" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssh_ptl_should_drop_dsq_packet \- Error injection hook to drop sequenced data packet.
.SH SYNOPSIS
.B "bool" ssh_ptl_should_drop_dsq_packet
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Useful to test re-transmit timeout of the driver. If the data packet has not
been ACKed after a certain time, the driver should re-transmit the packet up
to limited number of times defined in SSH_PTL_MAX_PACKET_TRIES.
