.TH "ssh_rtl_start" 9 "ssh_rtl_start" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssh_rtl_start \- Start request transmitter and receiver.
.SH SYNOPSIS
.B "int" ssh_rtl_start
.BI "(struct ssh_rtl *rtl "  ");"
.SH ARGUMENTS
.IP "rtl" 12
The request transport layer.
.SH "RETURN"
Returns zero on success, a negative error code on failure.
