.TH "ssp_common_process_data" 9 "ssp_common_process_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssp_common_process_data \- Common process data callback for ssp sensors
.SH SYNOPSIS
.B "int" ssp_common_process_data
.BI "(struct iio_dev *indio_dev "  ","
.BI "void *buf "  ","
.BI "unsigned int len "  ","
.BI "int64_t timestamp "  ");"
.SH ARGUMENTS
.IP "indio_dev" 12
iio device
.IP "buf" 12
source buffer
.IP "len" 12
sensor data length
.IP "timestamp" 12
system timestamp
.SH "DESCRIPTION"
Returns 0 or negative value in case of error
