.TH "ssp_flush" 9 "ssp_flush" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssp_flush \- flush the transmit and receive FIFOs
.SH SYNOPSIS
.B "int" ssp_flush
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Wait for the SSP to idle, and ensure that the receive FIFO
is empty.

The caller is expected to perform the necessary locking.
.SH "RETURN"
-ETIMEDOUT        timeout occurred
0                  success
