.TH "ssp_common_buffer_postdisable" 9 "ssp_common_buffer_postdisable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssp_common_buffer_postdisable \- generic postdisable callback for ssp buffer
.SH SYNOPSIS
.B "int" ssp_common_buffer_postdisable
.BI "(struct iio_dev *indio_dev "  ");"
.SH ARGUMENTS
.IP "indio_dev" 12
iio device
.SH "DESCRIPTION"
Returns 0 or negative value in case of error
