.TH "sst_resume_stream" 9 "sst_resume_stream" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sst_resume_stream \- Send msg for resuming stream
.SH SYNOPSIS
.B "int" sst_resume_stream
.BI "(struct intel_sst_drv *sst_drv_ctx "  ","
.BI "int str_id "  ");"
.SH ARGUMENTS
.IP "sst_drv_ctx" 12
intel_sst_drv context pointer
.IP "str_id" 12
stream ID
.SH "DESCRIPTION"
This function is called by any function which wants to resume
an already paused stream.
