.TH "st_dwc3_drd_init" 9 "st_dwc3_drd_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
st_dwc3_drd_init \- program the port
.SH SYNOPSIS
.B "int" st_dwc3_drd_init
.BI "(struct st_dwc3 *dwc3_data "  ");"
.SH ARGUMENTS
.IP "dwc3_data" 12
driver private structure
.SH "DESCRIPTION"
this function is to program the port as either host or device
according to the static configuration passed from devicetree.
OTG and dual role are not yet supported!
