.TH "st_sensors_new_samples_available" 9 "st_sensors_new_samples_available" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
st_sensors_new_samples_available \- check if more samples came in
.SH SYNOPSIS
.B "bool" st_sensors_new_samples_available
.BI "(struct iio_dev *indio_dev "  ","
.BI "struct st_sensor_data *sdata "  ");"
.SH ARGUMENTS
.IP "indio_dev" 12
IIO device reference.
.IP "sdata" 12
Sensor data.
.SH "RETURN"
false - no new samples available or read error
true - new samples available
