.TH "sta2x11_vip_remove_one" 9 "sta2x11_vip_remove_one" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sta2x11_vip_remove_one \- release device
.SH SYNOPSIS
.B "void" sta2x11_vip_remove_one
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device
.SH "DESCRIPTION"
Undo everything done in .._init_one

unregister video device
free interrupt
unmap ioadresses
free memory
free GPIO pins
