.TH "stm32_adc_set_trig" 9 "stm32_adc_set_trig" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stm32_adc_set_trig \- Set a regular trigger
.SH SYNOPSIS
.B "int" stm32_adc_set_trig
.BI "(struct iio_dev *indio_dev "  ","
.BI "struct iio_trigger *trig "  ");"
.SH ARGUMENTS
.IP "indio_dev" 12
IIO device
.IP "trig" 12
IIO trigger
.SH "DESCRIPTION"
Set trigger source/polarity (e.g. SW, or HW with polarity) :
- if HW trigger disabled (e.g. trig == NULL, conversion launched by sw)
- if HW trigger enabled, set source & polarity
