.TH "stm32_spi_dma_config" 9 "stm32_spi_dma_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stm32_spi_dma_config \- configure dma slave channel depending on current transfer bits_per_word.
.SH SYNOPSIS
.B "void" stm32_spi_dma_config
.BI "(struct stm32_spi *spi "  ","
.BI "struct dma_slave_config *dma_conf "  ","
.BI "enum dma_transfer_direction dir "  ");"
.SH ARGUMENTS
.IP "spi" 12
pointer to the spi controller data structure
.IP "dma_conf" 12
pointer to the dma_slave_config structure
.IP "dir" 12
direction of the dma transfer
