.TH "stmmac_set_time" 9 "stmmac_set_time" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stmmac_set_time \- 
.SH SYNOPSIS
.B "int" stmmac_set_time
.BI "(struct ptp_clock_info *ptp "  ","
.BI "const struct timespec64 *ts "  ");"
.SH ARGUMENTS
.IP "ptp" 12
pointer to ptp_clock_info structure
.IP "ts" 12
time value to set
.SH "DESCRIPTION"
this function will set the current time on the
hardware clock.
