.TH "stmmac_mac_config_rx_queues_routing" 9 "stmmac_mac_config_rx_queues_routing" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stmmac_mac_config_rx_queues_routing \- Configure RX Queue Routing
.SH SYNOPSIS
.B "void" stmmac_mac_config_rx_queues_routing
.BI "(struct stmmac_priv *priv "  ");"
.SH ARGUMENTS
.IP "priv" 12
driver private structure
.SH "DESCRIPTION"
It is used for configuring the RX queue routing
