.TH "stmmac_mdio_read" 9 "stmmac_mdio_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stmmac_mdio_read \- 
.SH SYNOPSIS
.B "int" stmmac_mdio_read
.BI "(struct mii_bus *bus "  ","
.BI "int phyaddr "  ","
.BI "int phyreg "  ");"
.SH ARGUMENTS
.IP "bus" 12
points to the mii_bus structure
.IP "phyaddr" 12
MII addr
.IP "phyreg" 12
MII reg
.SH "DESCRIPTION"
it reads data from the MII register from within the phy device.
For the 7111 GMAC, we must set the bit 0 in the MII address register while
accessing the PHY registers.
Fortunately, it seems this has no drawback for the 7109 MAC.
