.TH "stmmac_mac_flow_ctrl" 9 "stmmac_mac_flow_ctrl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stmmac_mac_flow_ctrl \- Configure flow control in all queues
.SH SYNOPSIS
.B "void" stmmac_mac_flow_ctrl
.BI "(struct stmmac_priv *priv "  ","
.BI "u32 duplex "  ");"
.SH ARGUMENTS
.IP "priv" 12
driver private structure
.IP "duplex" 12
duplex passed to the next function
.SH "DESCRIPTION"
It is used for configuring the flow control in all queues
