.TH "string_get_size" 9 "string_get_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
string_get_size \- get the size in the specified units
.SH SYNOPSIS
.B "void" string_get_size
.BI "(u64 size "  ","
.BI "u64 blk_size "  ","
.BI "const enum string_size_units units "  ","
.BI "char *buf "  ","
.BI "int len "  ");"
.SH ARGUMENTS
.IP "size" 12
The size to be converted in blocks
.IP "blk_size" 12
Size of the block (use 1 for size in bytes)
.IP "units" 12
units to use (powers of 1000 or 1024)
.IP "buf" 12
buffer to format to
.IP "len" 12
length of buffer
.SH "DESCRIPTION"
This function returns a string formatted to 3 significant figures
giving the size in the required units.  \fIbuf\fP should have room for
at least 9 bytes and will always be zero terminated.
