.TH "strim" 9 "strim" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
strim \- Removes leading and trailing whitespace from @s.
.SH SYNOPSIS
.B "char *" strim
.BI "(char *s "  ");"
.SH ARGUMENTS
.IP "s" 12
The string to be stripped.
.SH "DESCRIPTION"
Note that the first trailing whitespace is replaced with a NUL-terminator
in the given string \fIs\fP. Returns a pointer to the first non-whitespace
character in \fIs\fP.
