.TH "strncasecmp" 9 "strncasecmp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
strncasecmp \- Case insensitive, length-limited string comparison
.SH SYNOPSIS
.B "int" strncasecmp
.BI "(const char *s1 "  ","
.BI "const char *s2 "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "s1" 12
One string
.IP "s2" 12
The other string
.IP "len" 12
the maximum number of characters to compare
