.TH "strpbrk" 9 "strpbrk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
strpbrk \- Find the first occurrence of a set of characters
.SH SYNOPSIS
.B "char *" strpbrk
.BI "(const char *cs "  ","
.BI "const char *ct "  ");"
.SH ARGUMENTS
.IP "cs" 12
The string to be searched
.IP "ct" 12
The characters to search for
