.TH "subdev_8255_regbase" 9 "subdev_8255_regbase" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
subdev_8255_regbase \- get offset of 8255 registers or call-back context
.SH SYNOPSIS
.B "unsigned long" subdev_8255_regbase
.BI "(struct comedi_subdevice *s "  ");"
.SH ARGUMENTS
.IP "s" 12
comedi subdevice
.SH "DESCRIPTION"
Returns the 'regbase' parameter that was previously passed to
\fBsubdev_8255_init\fP or \fBsubdev_8255_mm_init\fP to set up the subdevice.
Only valid if the subdevice was set up successfully.
