.TH "superhyway_register_driver" 9 "superhyway_register_driver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
superhyway_register_driver \- Register a new SuperHyway driver
.SH SYNOPSIS
.B "int" superhyway_register_driver
.BI "(struct superhyway_driver *drv "  ");"
.SH ARGUMENTS
.IP "drv" 12
SuperHyway driver to register.
.SH "DESCRIPTION"
This registers the passed in \fIdrv\fP. Any devices matching the id table will
automatically be populated and handed off to the driver's specified probe
routine.
