.TH "surface3_spi_get_gpio_config" 9 "surface3_spi_get_gpio_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
surface3_spi_get_gpio_config \- Get GPIO config from ACPI/DT
.SH SYNOPSIS
.B "int" surface3_spi_get_gpio_config
.BI "(struct surface3_ts_data *data "  ");"
.SH ARGUMENTS
.IP "data" 12
surface3_spi_ts_data pointer
