.TH "swsusp_free" 9 "swsusp_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
swsusp_free \- Free pages allocated for hibernation image.
.SH SYNOPSIS
.B "void" swsusp_free
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Image pages are alocated before snapshot creation, so they need to be
released after resume.
