.TH "sxgbe_check_ether_addr" 9 "sxgbe_check_ether_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sxgbe_check_ether_addr \- check if the MAC addr is valid
.SH SYNOPSIS
.B "void" sxgbe_check_ether_addr
.BI "(struct sxgbe_priv_data *priv "  ");"
.SH ARGUMENTS
.IP "priv" 12
driver private structure
.SH "DESCRIPTION"
it is to verify if the MAC address is valid, in case of failures it
generates a random MAC address
