.TH "sync_pt_create" 9 "sync_pt_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sync_pt_create \- creates a sync pt
.SH SYNOPSIS
.B "struct sync_pt *" sync_pt_create
.BI "(struct sync_timeline *obj "  ","
.BI "unsigned int value "  ");"
.SH ARGUMENTS
.IP "obj" 12
parent sync_timeline
.IP "value" 12
value of the fence
.SH "DESCRIPTION"
Creates a new sync_pt (fence) as a child of \fIparent\fP.  \fIsize\fP bytes will be
allocated allowing for implementation specific data to be kept after
the generic sync_timeline struct. Returns the sync_pt object or
NULL in case of error.
