.TH "synchronize_srcu_expedited" 9 "synchronize_srcu_expedited" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
synchronize_srcu_expedited \- Brute-force SRCU grace period
.SH SYNOPSIS
.B "void" synchronize_srcu_expedited
.BI "(struct srcu_struct *ssp "  ");"
.SH ARGUMENTS
.IP "ssp" 12
srcu_struct with which to synchronize.
.SH "DESCRIPTION"
Wait for an SRCU grace period to elapse, but be more aggressive about
spinning rather than blocking when waiting.

Note that \fBsynchronize_srcu_expedited\fP has the same deadlock and
memory-ordering properties as does \fBsynchronize_srcu\fP.
