.TH "sys_sched_setattr" 9 "sys_sched_setattr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sys_sched_setattr \- same as above, but with extended sched_attr
.SH SYNOPSIS
.B "long" sys_sched_setattr
.BI "(pid_t pid "  ","
.BI "struct sched_attr __user * uattr "  ","
.BI "unsigned int flags "  ");"
.SH ARGUMENTS
.IP "pid" 12
the pid in question.
.IP "uattr" 12
structure containing the extended parameters.
.IP "flags" 12
for future extension.
