.TH "sys_rt_sigtimedwait" 9 "sys_rt_sigtimedwait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sys_rt_sigtimedwait \- synchronously wait for queued signals specified in @uthese
.SH SYNOPSIS
.B "long" sys_rt_sigtimedwait
.BI "(const sigset_t __user * uthese "  ","
.BI "siginfo_t __user * uinfo "  ","
.BI "const struct __kernel_timespec __user * uts "  ","
.BI "size_t sigsetsize "  ");"
.SH ARGUMENTS
.IP "uthese" 12
queued signals to wait for
.IP "uinfo" 12
if non-null, the signal's siginfo is returned here
.IP "uts" 12
upper bound on process time suspension
.IP "sigsetsize" 12
size of sigset_t type
