.TH "sys_capget" 9 "sys_capget" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sys_capget \- get the capabilities of a given process.
.SH SYNOPSIS
.B "long" sys_capget
.BI "(cap_user_header_t header "  ","
.BI "cap_user_data_t dataptr "  ");"
.SH ARGUMENTS
.IP "header" 12
pointer to struct that contains capability version and
target pid data
.IP "dataptr" 12
pointer to struct that contains the effective, permitted,
and inheritable capabilities that are returned
.SH "DESCRIPTION"
Returns 0 on success and < 0 on error.
