.TH "sysfs_remove_file_self" 9 "sysfs_remove_file_self" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sysfs_remove_file_self \- remove an object attribute from its own method
.SH SYNOPSIS
.B "bool" sysfs_remove_file_self
.BI "(struct kobject *kobj "  ","
.BI "const struct attribute *attr "  ");"
.SH ARGUMENTS
.IP "kobj" 12
object we're acting for
.IP "attr" 12
attribute descriptor
.SH "DESCRIPTION"
See \fBkernfs_remove_self\fP for details.
