.TH "sysfs_add_link_to_group" 9 "sysfs_add_link_to_group" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sysfs_add_link_to_group \- add a symlink to an attribute group.
.SH SYNOPSIS
.B "int" sysfs_add_link_to_group
.BI "(struct kobject *kobj "  ","
.BI "const char *group_name "  ","
.BI "struct kobject *target "  ","
.BI "const char *link_name "  ");"
.SH ARGUMENTS
.IP "kobj" 12
The kobject containing the group.
.IP "group_name" 12
The name of the group.
.IP "target" 12
The target kobject of the symlink to create.
.IP "link_name" 12
The name of the symlink to create.
