.TH "sysfs_remove_file_ns" 9 "sysfs_remove_file_ns" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sysfs_remove_file_ns \- remove an object attribute with a custom ns tag
.SH SYNOPSIS
.B "void" sysfs_remove_file_ns
.BI "(struct kobject *kobj "  ","
.BI "const struct attribute *attr "  ","
.BI "const void *ns "  ");"
.SH ARGUMENTS
.IP "kobj" 12
object we're acting for
.IP "attr" 12
attribute descriptor
.IP "ns" 12
namespace tag of the file to remove
.SH "DESCRIPTION"
Hash the attribute name and namespace tag and kill the victim.
