.TH "sysfs_unmerge_group" 9 "sysfs_unmerge_group" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sysfs_unmerge_group \- remove files from a pre-existing attribute group.
.SH SYNOPSIS
.B "void" sysfs_unmerge_group
.BI "(struct kobject *kobj "  ","
.BI "const struct attribute_group *grp "  ");"
.SH ARGUMENTS
.IP "kobj" 12
The kobject containing the group.
.IP "grp" 12
The files to remove and the attribute group they belong to.
