.TH "sysfs_merge_group" 9 "sysfs_merge_group" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sysfs_merge_group \- merge files into a pre-existing attribute group.
.SH SYNOPSIS
.B "int" sysfs_merge_group
.BI "(struct kobject *kobj "  ","
.BI "const struct attribute_group *grp "  ");"
.SH ARGUMENTS
.IP "kobj" 12
The kobject containing the group.
.IP "grp" 12
The files to create and the attribute group they belong to.
.SH "DESCRIPTION"
This function returns an error if the group doesn't exist or any of the
files already exist in that group, in which case none of the new files
are created.
