.TH "t3_reset_qset" 9 "t3_reset_qset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t3_reset_qset \- reset a sge qset
.SH SYNOPSIS
.B "void" t3_reset_qset
.BI "(struct sge_qset *q "  ");"
.SH ARGUMENTS
.IP "q" 12
the queue set

Reset the qset structure.
the NAPI structure is preserved in the event of
the qset's reincarnation, for example during EEH recovery.
