.TH "t3_stop_sge_timers" 9 "t3_stop_sge_timers" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t3_stop_sge_timers \- stop SGE timer call backs
.SH SYNOPSIS
.B "void" t3_stop_sge_timers
.BI "(struct adapter *adap "  ");"
.SH ARGUMENTS
.IP "adap" 12
the adapter

Stops each SGE queue set's timer call back
