.TH "t3_set_phy_speed_duplex" 9 "t3_set_phy_speed_duplex" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t3_set_phy_speed_duplex \- force PHY speed and duplex
.SH SYNOPSIS
.B "int" t3_set_phy_speed_duplex
.BI "(struct cphy *phy "  ","
.BI "int speed "  ","
.BI "int duplex "  ");"
.SH ARGUMENTS
.IP "phy" 12
the PHY to operate on
.IP "speed" 12
requested PHY speed
.IP "duplex" 12
requested PHY duplex

Force a 10/100/1000 PHY's speed and duplex.  This also disables
auto-negotiation except for GigE, where auto-negotiation is mandatory.
