.TH "t3_tp_set_coalescing_size" 9 "t3_tp_set_coalescing_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t3_tp_set_coalescing_size \- set receive coalescing size
.SH SYNOPSIS
.B "int" t3_tp_set_coalescing_size
.BI "(struct adapter *adap "  ","
.BI "unsigned int size "  ","
.BI "int psh "  ");"
.SH ARGUMENTS
.IP "adap" 12
the adapter
.IP "size" 12
the receive coalescing size
.IP "psh" 12
whether a set PSH bit should deliver coalesced data

Set the receive coalescing size and PSH bit handling.
