.TH "t4_memory_update_win" 9 "t4_memory_update_win" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4_memory_update_win \- Move memory window to specified address.
.SH SYNOPSIS
.B "void" t4_memory_update_win
.BI "(struct adapter *adap "  ","
.BI "int win "  ","
.BI "u32 addr "  ");"
.SH ARGUMENTS
.IP "adap" 12
the adapter
.IP "win" 12
PCI-E Memory Window to use
.IP "addr" 12
location to move.
.SH "DESCRIPTION"
Move memory window to specified address.
