.TH "t4_tx_completion_handler" 9 "t4_tx_completion_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4_tx_completion_handler \- handle CPL_SGE_EGR_UPDATE messages
.SH SYNOPSIS
.B "void" t4_tx_completion_handler
.BI "(struct sge_rspq *rspq "  ","
.BI "const __be64 *rsp "  ","
.BI "const struct pkt_gl *gl "  ");"
.SH ARGUMENTS
.IP "rspq" 12
Ethernet RX Response Queue associated with Ethernet TX Queue
.IP "rsp" 12
Response Entry pointer into Response Queue
.IP "gl" 12
Gather List pointer

For adapters which support the SGE Doorbell Queue Timer facility,
we configure the Ethernet TX Queues to send CIDX Updates to the
Associated Ethernet RX Response Queue with CPL_SGE_EGR_UPDATE
messages.  This adds a small load to PCIe Link RX bandwidth and,
potentially, higher CPU Interrupt load, but allows us to respond
much more quickly to the CIDX Updates.  This is important for
Upper Layer Software which isn't willing to have a large amount
of TX Data outstanding before receiving DMA Completions.
