.TH "t4_tp_fw_ldst_rw" 9 "t4_tp_fw_ldst_rw" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4_tp_fw_ldst_rw \- Access TP indirect register through LDST
.SH SYNOPSIS
.B "int" t4_tp_fw_ldst_rw
.BI "(struct adapter *adap "  ","
.BI "int cmd "  ","
.BI "u32 *vals "  ","
.BI "unsigned int nregs "  ","
.BI "unsigned int start_index "  ","
.BI "unsigned int rw "  ","
.BI "bool sleep_ok "  ");"
.SH ARGUMENTS
.IP "adap" 12
the adapter
.IP "cmd" 12
TP fw ldst address space type
.IP "vals" 12
where the indirect register values are stored/written
.IP "nregs" 12
how many indirect registers to read/write
.IP "start_index" 12
index of first indirect register to read/write
.IP "rw" 12
Read (1) or Write (0)
.IP "sleep_ok" 12
if true we may sleep while awaiting command completion
.SH "DESCRIPTION"
Access TP indirect registers through LDST
