.TH "t4vf_iq_free" 9 "t4vf_iq_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4vf_iq_free \- free an ingress queue and its free lists
.SH SYNOPSIS
.B "int" t4vf_iq_free
.BI "(struct adapter *adapter "  ","
.BI "unsigned int iqtype "  ","
.BI "unsigned int iqid "  ","
.BI "unsigned int fl0id "  ","
.BI "unsigned int fl1id "  ");"
.SH ARGUMENTS
.IP "adapter" 12
the adapter
.IP "iqtype" 12
the ingress queue type (FW_IQ_TYPE_FL_INT_CAP, etc.)
.IP "iqid" 12
ingress queue ID
.IP "fl0id" 12
FL0 queue ID or 0xffff if no attached FL0
.IP "fl1id" 12
FL1 queue ID or 0xffff if no attached FL1

Frees an ingress queue and its associated free lists, if any.
