.TH "target_put_sess_cmd" 9 "target_put_sess_cmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
target_put_sess_cmd \- decrease the command reference count
.SH SYNOPSIS
.B "int" target_put_sess_cmd
.BI "(struct se_cmd *se_cmd "  ");"
.SH ARGUMENTS
.IP "se_cmd" 12
command to drop a reference from
.SH "DESCRIPTION"
Returns 1 if and only if this \fBtarget_put_sess_cmd\fP call caused the
refcount to drop to zero. Returns zero otherwise.
