.TH "target_send_busy" 9 "target_send_busy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
target_send_busy \- Send SCSI BUSY status back to the initiator
.SH SYNOPSIS
.B "int" target_send_busy
.BI "(struct se_cmd *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
SCSI command for which to send a BUSY reply.
.SH "NOTE"
Only call this function if target_submit_cmd*() failed.
