.TH "tb_domain_disapprove_switch" 9 "tb_domain_disapprove_switch" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_domain_disapprove_switch \- Disapprove switch
.SH SYNOPSIS
.B "int" tb_domain_disapprove_switch
.BI "(struct tb *tb "  ","
.BI "struct tb_switch *sw "  ");"
.SH ARGUMENTS
.IP "tb" 12
Domain the switch belongs to
.IP "sw" 12
Switch to disapprove
.SH "DESCRIPTION"
This will disconnect PCIe tunnel from parent to this \fIsw\fP.
.SH "RETURN"
0 on success and negative errno in case of failure.
