.TH "tb_nvm_alloc" 9 "tb_nvm_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_nvm_alloc \- Allocate new NVM structure
.SH SYNOPSIS
.B "struct tb_nvm *" tb_nvm_alloc
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device owning the NVM
.SH "DESCRIPTION"
Allocates new NVM structure with unique \fIid\fP and returns it. In case
of error returns \fBERR_PTR\fP.
