.TH "tb_ring_poll" 9 "tb_ring_poll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_ring_poll \- Poll one completed frame from the ring
.SH SYNOPSIS
.B "struct ring_frame *" tb_ring_poll
.BI "(struct tb_ring *ring "  ");"
.SH ARGUMENTS
.IP "ring" 12
Ring to poll
.SH "DESCRIPTION"
This function can be called when \fIstart_poll\fP callback of the \fIring\fP
has been called. It will read one completed frame from the ring and
return it to the caller. Returns NULL if there is no more completed
frames.
