.TH "tb_switch_find_vse_cap" 9 "tb_switch_find_vse_cap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_switch_find_vse_cap \- Find switch vendor specific capability
.SH SYNOPSIS
.B "int" tb_switch_find_vse_cap
.BI "(struct tb_switch *sw "  ","
.BI "enum tb_switch_vse_cap vsec "  ");"
.SH ARGUMENTS
.IP "sw" 12
Switch to find the capability for
.IP "vsec" 12
Vendor specific capability to look
.SH "DESCRIPTION"
Functions enumerates vendor specific capabilities (VSEC) of a switch
and returns offset when capability matching \fIvsec\fP is found. If no
such capability is found returns -ENOENT. In case of error returns
negative errno.
