.TH "tb_service_debugfs_remove" 9 "tb_service_debugfs_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_service_debugfs_remove \- Remove service debugfs directory
.SH SYNOPSIS
.B "void" tb_service_debugfs_remove
.BI "(struct tb_service *svc "  ");"
.SH ARGUMENTS
.IP "svc" 12
Thunderbolt service pointer
.SH "DESCRIPTION"
Removes the previously created debugfs directory for \fIsvc\fP.
