.TH "tb_tunnel_is_invalid" 9 "tb_tunnel_is_invalid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_tunnel_is_invalid \- check whether an activated path is still valid
.SH SYNOPSIS
.B "bool" tb_tunnel_is_invalid
.BI "(struct tb_tunnel *tunnel "  ");"
.SH ARGUMENTS
.IP "tunnel" 12
Tunnel to check
