.TH "tc_bus_match" 9 "tc_bus_match" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tc_bus_match \- Tell if a device structure has a matching TC device ID structure
.SH SYNOPSIS
.B "int" tc_bus_match
.BI "(struct device *dev "  ","
.BI "struct device_driver *drv "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device structure to match against
.IP "drv" 12
the device driver to search for matching TC device ID strings
.SH "DESCRIPTION"
Used by a driver to check whether a TC device present in the
system is in its list of supported devices.  Returns 1 if there
is a match or 0 otherwise.
