.TH "tdme_channelinit" 9 "tdme_channelinit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tdme_channelinit \- TDME Channel Register Default Initialisation Macro (Tx)
.SH SYNOPSIS
.B "u8" tdme_channelinit
.BI "(u8 channel "  ","
.BI "void *device_ref "  ");"
.SH ARGUMENTS
.IP "channel" 12
802.15.4 channel to initialise chip for
.IP "device_ref" 12
Nondescript pointer to target device
.SH "RETURN"
802.15.4 status code of API calls
