.TH "tee_device_register" 9 "tee_device_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tee_device_register \- Registers a TEE device
.SH SYNOPSIS
.B "int" tee_device_register
.BI "(struct tee_device *teedev "  ");"
.SH ARGUMENTS
.IP "teedev" 12
Device to register
.SH "DESCRIPTION"
\fBtee_device_unregister\fP need to be called to remove the \fIteedev\fP if
this function fails.

\fIreturns\fP < 0 on failure
