.TH "telemetry_reset_events" 9 "telemetry_reset_events" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
telemetry_reset_events \- Restore the IOSS & PSS configuration to default
.SH SYNOPSIS
.B "int" telemetry_reset_events
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
0 success, < 0 for failure
