.TH "tep_get_cpus" 9 "tep_get_cpus" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tep_get_cpus \- get the number of CPUs
.SH SYNOPSIS
.B "int" tep_get_cpus
.BI "(struct tep_handle *tep "  ");"
.SH ARGUMENTS
.IP "tep" 12
a handle to the tep_handle
.SH "DESCRIPTION"
This returns the number of CPUs
If \fItep\fP is NULL, 0 is returned.
