.TH "tep_data_pid" 9 "tep_data_pid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tep_data_pid \- parse the PID from record
.SH SYNOPSIS
.B "int" tep_data_pid
.BI "(struct tep_handle *tep "  ","
.BI "struct tep_record *rec "  ");"
.SH ARGUMENTS
.IP "tep" 12
a handle to the trace event parser context
.IP "rec" 12
the record to parse
.SH "DESCRIPTION"
This returns the PID from a record.
