.TH "tep_filter_alloc" 9 "tep_filter_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tep_filter_alloc \- create a new event filter
.SH SYNOPSIS
.B "struct tep_event_filter *" tep_filter_alloc
.BI "(struct tep_handle *tep "  ");"
.SH ARGUMENTS
.IP "tep" 12
The tep that this filter is associated with
