.TH "tep_get_header_timestamp_size" 9 "tep_get_header_timestamp_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tep_get_header_timestamp_size \- get size of the timestamp in the header page
.SH SYNOPSIS
.B "int" tep_get_header_timestamp_size
.BI "(struct tep_handle *tep "  ");"
.SH ARGUMENTS
.IP "tep" 12
a handle to the tep_handle
.SH "DESCRIPTION"
This returns size of the timestamp in the header page
If \fItep\fP is NULL, 0 is returned.
