.TH "tep_get_long_size" 9 "tep_get_long_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tep_get_long_size \- get the size of a long integer on the traced machine
.SH SYNOPSIS
.B "int" tep_get_long_size
.BI "(struct tep_handle *tep "  ");"
.SH ARGUMENTS
.IP "tep" 12
a handle to the tep_handle
.SH "DESCRIPTION"
This returns the size of a long integer on the traced machine
If \fItep\fP is NULL, 0 is returned.
