.TH "tep_add_plugin_path" 9 "tep_add_plugin_path" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tep_add_plugin_path \- Add a new plugin directory.
.SH SYNOPSIS
.B "int" tep_add_plugin_path
.BI "(struct tep_handle *tep "  ","
.BI "char *path "  ","
.BI "enum tep_plugin_load_priority prio "  ");"
.SH ARGUMENTS
.IP "tep" 12
Trace event handler.
.IP "path" 12
Path to a directory. All plugin files in that
directory will be loaded.
.IP "prio" 12
Load priority of the plugins in that directory.
.SH "DESCRIPTION"
Returns -1 in case of an error, 0 otherwise.
