.TH "tep_event_filtered" 9 "tep_event_filtered" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tep_event_filtered \- return true if event has filter
.SH SYNOPSIS
.B "int" tep_event_filtered
.BI "(struct tep_event_filter *filter "  ","
.BI "int event_id "  ");"
.SH ARGUMENTS
.IP "filter" 12
filter struct with filter information
.IP "event_id" 12
event id to test if filter exists
.SH "DESCRIPTION"
Returns 1 if filter found for \fIevent_id\fP
otherwise 0;
