.TH "tep_parse_format" 9 "tep_parse_format" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tep_parse_format \- parse the event format
.SH SYNOPSIS
.B "enum tep_errno" tep_parse_format
.BI "(struct tep_handle *tep "  ","
.BI "struct tep_event **eventp "  ","
.BI "const char *buf "  ","
.BI "unsigned long size "  ","
.BI "const char *sys "  ");"
.SH ARGUMENTS
.IP "tep" 12
a handle to the trace event parser context
.IP "eventp" 12
returned format
.IP "buf" 12
the buffer storing the event format string
.IP "size" 12
the size of \fIbuf\fP
.IP "sys" 12
the system the event belongs to
.SH "DESCRIPTION"
This parses the event format and creates an event structure
to quickly parse raw data for a given event.

These files currently come from:

/sys/kernel/debug/tracing/events/.../.../format
