.TH "tgafb_imageblit" 9 "tgafb_imageblit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tgafb_imageblit \- REQUIRED function. Can use generic routines if non acclerated hardware and packed pixel based. Copies a image from system memory to the screen.
.SH SYNOPSIS
.B "void" tgafb_imageblit
.BI "(struct fb_info *info "  ","
.BI "const struct fb_image *image "  ");"
.SH ARGUMENTS
.IP "info" 12
frame buffer structure that represents a single frame buffer
.IP "image" 12
structure defining the image.
