.TH "ti_msgmgr_queue_is_error" 9 "ti_msgmgr_queue_is_error" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_msgmgr_queue_is_error \- Check to see if there is queue error
.SH SYNOPSIS
.B "bool" ti_msgmgr_queue_is_error
.BI "(const struct ti_msgmgr_desc *d "  ","
.BI "struct ti_queue_inst *qinst "  ");"
.SH ARGUMENTS
.IP "d" 12
Description of message manager
.IP "qinst" 12
Queue instance for which we check the number of pending messages
.SH "RETURN"
true if error, else false
