.TH "ti_sci_inta_set_type" 9 "ti_sci_inta_set_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_sci_inta_set_type \- Update the trigger type of the irq.
.SH SYNOPSIS
.B "int" ti_sci_inta_set_type
.BI "(struct irq_data *data "  ","
.BI "unsigned int type "  ");"
.SH ARGUMENTS
.IP "data" 12
Pointer to corresponding irq_data
.IP "type" 12
Trigger type as specified by user
.SH "NOTE"
This updates the handle_irq callback for level msi.
.SH "DESCRIPTION"
Return 0 if all went well else appropriate error.
