.TH "ti_sci_debug_show" 9 "ti_sci_debug_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_sci_debug_show \- Helper to dump the debug log
.SH SYNOPSIS
.B "int" ti_sci_debug_show
.BI "(struct seq_file *s "  ","
.BI "void *unused "  ");"
.SH ARGUMENTS
.IP "s" 12
sequence file pointer
.IP "unused" 12
unused.
.SH "RETURN"
0
