.TH "ti_sci_set_device_state" 9 "ti_sci_set_device_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_sci_set_device_state \- Set device state helper
.SH SYNOPSIS
.B "int" ti_sci_set_device_state
.BI "(const struct ti_sci_handle *handle "  ","
.BI "u32 id "  ","
.BI "u32 flags "  ","
.BI "u8 state "  ");"
.SH ARGUMENTS
.IP "handle" 12
pointer to TI SCI handle
.IP "id" 12
Device identifier
.IP "flags" 12
flags to setup for the device
.IP "state" 12
State to move the device to
.SH "RETURN"
0 if all went well, else returns appropriate error value.
