.TH "ti_sci_inta_manage_event" 9 "ti_sci_inta_manage_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_sci_inta_manage_event \- Control the event based on the offset
.SH SYNOPSIS
.B "void" ti_sci_inta_manage_event
.BI "(struct irq_data *data "  ","
.BI "u32 offset "  ");"
.SH ARGUMENTS
.IP "data" 12
Pointer to corresponding irq_data
.IP "offset" 12
register offset using which event is controlled.
