.TH "tipc_skb_dump" 9 "tipc_skb_dump" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tipc_skb_dump \- dump TIPC skb data
.SH SYNOPSIS
.B "int" tipc_skb_dump
.BI "(struct sk_buff *skb "  ","
.BI "bool more "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "skb" 12
skb to be dumped
.IP "more" 12
dump more?
- false: dump only tipc msg data
- true: dump kernel-related skb data and tipc cb[] array as well
.IP "buf" 12
returned buffer of dump data in format
