.TH "tipc_aead_key_validate" 9 "tipc_aead_key_validate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tipc_aead_key_validate \- Validate a AEAD user key
.SH SYNOPSIS
.B "int" tipc_aead_key_validate
.BI "(struct tipc_aead_key *ukey "  ","
.BI "struct genl_info *info "  ");"
.SH ARGUMENTS
.IP "ukey" 12
pointer to user key data
.IP "info" 12
netlink info pointer
