.TH "tipc_getsockopt" 9 "tipc_getsockopt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tipc_getsockopt \- get socket option
.SH SYNOPSIS
.B "int" tipc_getsockopt
.BI "(struct socket *sock "  ","
.BI "int lvl "  ","
.BI "int opt "  ","
.BI "char __user *ov "  ","
.BI "int __user *ol "  ");"
.SH ARGUMENTS
.IP "sock" 12
socket structure
.IP "lvl" 12
option level
.IP "opt" 12
option identifier
.IP "ov" 12
receptacle for option value
.IP "ol" 12
receptacle for length of option value
.SH "DESCRIPTION"
For stream sockets only, returns 0 length result for all IPPROTO_TCP options
(to ease compatibility).
.SH "RETURN"
0 on success, errno otherwise
