.TH "tipc_enable_bearer" 9 "tipc_enable_bearer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tipc_enable_bearer \- enable bearer with the given name
.SH SYNOPSIS
.B "int" tipc_enable_bearer
.BI "(struct net *net "  ","
.BI "const char *name "  ","
.BI "u32 disc_domain "  ","
.BI "u32 prio "  ","
.BI "struct nlattr *attr[] "  ");"
.SH ARGUMENTS
.IP "net" 12
the applicable net namespace
.IP "name" 12
bearer name to enable
.IP "disc_domain" 12
bearer domain
.IP "prio" 12
bearer priority
.IP "attr" 12
nlattr array
