.TH "tipc_msg_fragment" 9 "tipc_msg_fragment" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tipc_msg_fragment \- build a fragment skb list for TIPC message
.SH SYNOPSIS
.B "int" tipc_msg_fragment
.BI "(struct sk_buff *skb "  ","
.BI "const struct tipc_msg *hdr "  ","
.BI "int pktmax "  ","
.BI "struct sk_buff_head *frags "  ");"
.SH ARGUMENTS
.IP "skb" 12
TIPC message skb
.IP "hdr" 12
internal msg header to be put on the top of the fragments
.IP "pktmax" 12
max size of a fragment incl. the header
.IP "frags" 12
returned fragment skb list
.SH "RETURN"
0 if the fragmentation is successful, otherwise: -EINVAL
or -ENOMEM
