.TH "tipc_link_set_skb_retransmit_time" 9 "tipc_link_set_skb_retransmit_time" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tipc_link_set_skb_retransmit_time \- set the time at which retransmission of the given skb should be next attempted
.SH SYNOPSIS
.B "void" tipc_link_set_skb_retransmit_time
.BI "(struct sk_buff *skb "  ","
.BI "struct tipc_link *l "  ");"
.SH ARGUMENTS
.IP "skb" 12
skb to set a future retransmission time for
.IP "l" 12
link the skb will be transmitted on
