.TH "tm_cvsx_active" 9 "tm_cvsx_active" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tm_cvsx_active \- get active number of registers in CVSX
.SH SYNOPSIS
.B "int" tm_cvsx_active
.BI "(struct task_struct *target "  ","
.BI "const struct user_regset *regset "  ");"
.SH ARGUMENTS
.IP "target" 12
The target task.
.IP "regset" 12
The user regset structure.
.SH "DESCRIPTION"
This function checks for the active number of available
regisers in transaction checkpointed VSX category.
