.TH "tnc_read_hashed_node" 9 "tnc_read_hashed_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tnc_read_hashed_node \- read a "hashed" leaf node.
.SH SYNOPSIS
.B "int" tnc_read_hashed_node
.BI "(struct ubifs_info *c "  ","
.BI "struct ubifs_zbranch *zbr "  ","
.BI "void *node "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "zbr" 12
key and position of the node
.IP "node" 12
node is returned here
.SH "DESCRIPTION"
This function reads a "hashed" node defined by \fIzbr\fP from the leaf node cache
(in it is there) or from the hash media, in which case the node is also
added to LNC. Returns zero in case of success or a negative error
code in case of failure.
