.TH "tomoyo_print_header" 9 "tomoyo_print_header" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_print_header \- Get header line of audit log.
.SH SYNOPSIS
.B "char *" tomoyo_print_header
.BI "(struct tomoyo_request_info *r "  ");"
.SH ARGUMENTS
.IP "r" 12
Pointer to "struct tomoyo_request_info".
.SH "DESCRIPTION"
Returns string representation.

This function uses \fBkmalloc\fP, so caller must \fBkfree\fP if this function
didn't return NULL.
