.TH "tomoyo_print_entry" 9 "tomoyo_print_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_print_entry \- Print an ACL entry.
.SH SYNOPSIS
.B "bool" tomoyo_print_entry
.BI "(struct tomoyo_io_buffer *head "  ","
.BI "struct tomoyo_acl_info *acl "  ");"
.SH ARGUMENTS
.IP "head" 12
Pointer to "struct tomoyo_io_buffer".
.IP "acl" 12
Pointer to an ACL entry.
.SH "DESCRIPTION"
Returns true on success, false otherwise.
