.TH "tomoyo_sb_mount" 9 "tomoyo_sb_mount" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_sb_mount \- Target for security_sb_mount().
.SH SYNOPSIS
.B "int" tomoyo_sb_mount
.BI "(const char *dev_name "  ","
.BI "const struct path *path "  ","
.BI "const char *type "  ","
.BI "unsigned long flags "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "dev_name" 12
Name of device file. Maybe NULL.
.IP "path" 12
Pointer to "struct path".
.IP "type" 12
Name of filesystem type. Maybe NULL.
.IP "flags" 12
Mount options.
.IP "data" 12
Optional data. Maybe NULL.
.SH "DESCRIPTION"
Returns 0 on success, negative value otherwise.
