.TH "tomoyo_path_unlink" 9 "tomoyo_path_unlink" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_path_unlink \- Target for security_path_unlink().
.SH SYNOPSIS
.B "int" tomoyo_path_unlink
.BI "(const struct path *parent "  ","
.BI "struct dentry *dentry "  ");"
.SH ARGUMENTS
.IP "parent" 12
Pointer to "struct path".
.IP "dentry" 12
Pointer to "struct dentry".
.SH "DESCRIPTION"
Returns 0 on success, negative value otherwise.
