.TH "tomoyo_filetype" 9 "tomoyo_filetype" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_filetype \- Get string representation of file type.
.SH SYNOPSIS
.B "const char *" tomoyo_filetype
.BI "(const umode_t mode "  ");"
.SH ARGUMENTS
.IP "mode" 12
Mode value for \fBstat\fP.
.SH "DESCRIPTION"
Returns file type string.
