.TH "tomoyo_path_truncate" 9 "tomoyo_path_truncate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_path_truncate \- Target for security_path_truncate().
.SH SYNOPSIS
.B "int" tomoyo_path_truncate
.BI "(const struct path *path "  ");"
.SH ARGUMENTS
.IP "path" 12
Pointer to "struct path".
.SH "DESCRIPTION"
Returns 0 on success, negative value otherwise.
