.TH "tomoyo_same_condition" 9 "tomoyo_same_condition" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_same_condition \- Check for duplicated "struct tomoyo_condition" entry.
.SH SYNOPSIS
.B "bool" tomoyo_same_condition
.BI "(const struct tomoyo_condition *a "  ","
.BI "const struct tomoyo_condition *b "  ");"
.SH ARGUMENTS
.IP "a" 12
Pointer to "struct tomoyo_condition".
.IP "b" 12
Pointer to "struct tomoyo_condition".
.SH "DESCRIPTION"
Returns true if \fIa\fP == \fIb\fP, false otherwise.
