.TH "tomoyo_dump_page" 9 "tomoyo_dump_page" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_dump_page \- Dump a page to buffer.
.SH SYNOPSIS
.B "bool" tomoyo_dump_page
.BI "(struct linux_binprm *bprm "  ","
.BI "unsigned long pos "  ","
.BI "struct tomoyo_page_dump *dump "  ");"
.SH ARGUMENTS
.IP "bprm" 12
Pointer to "struct linux_binprm".
.IP "pos" 12
Location to dump.
.IP "dump" 12
Pointer to "struct tomoyo_page_dump".
.SH "DESCRIPTION"
Returns true on success, false otherwise.
