.TH "tomoyo_merge_path_number_acl" 9 "tomoyo_merge_path_number_acl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_merge_path_number_acl \- Merge duplicated "struct tomoyo_path_number_acl" entry.
.SH SYNOPSIS
.B "bool" tomoyo_merge_path_number_acl
.BI "(struct tomoyo_acl_info *a "  ","
.BI "struct tomoyo_acl_info *b "  ","
.BI "const bool is_delete "  ");"
.SH ARGUMENTS
.IP "a" 12
Pointer to "struct tomoyo_acl_info".
.IP "b" 12
Pointer to "struct tomoyo_acl_info".
.IP "is_delete" 12
True for \fIa\fP &= ~\fIb\fP, false for \fIa\fP |= \fIb\fP.
.SH "DESCRIPTION"
Returns true if \fIa\fP is empty, false otherwise.
