.TH "tomoyo_collect_entry" 9 "tomoyo_collect_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_collect_entry \- Try to kfree() deleted elements.
.SH SYNOPSIS
.B "void" tomoyo_collect_entry
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Returns nothing.
