.TH "tomoyo_init_request_info" 9 "tomoyo_init_request_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_init_request_info \- Initialize "struct tomoyo_request_info" members.
.SH SYNOPSIS
.B "int" tomoyo_init_request_info
.BI "(struct tomoyo_request_info *r "  ","
.BI "struct tomoyo_domain_info *domain "  ","
.BI "const u8 index "  ");"
.SH ARGUMENTS
.IP "r" 12
Pointer to "struct tomoyo_request_info" to initialize.
.IP "domain" 12
Pointer to "struct tomoyo_domain_info". NULL for \fBtomoyo_domain\fP.
.IP "index" 12
Index number of functionality.
.SH "DESCRIPTION"
Returns mode.
