.TH "tomoyo_write" 9 "tomoyo_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_write \- write() for /sys/kernel/security/tomoyo/ interface.
.SH SYNOPSIS
.B "ssize_t" tomoyo_write
.BI "(struct file *file "  ","
.BI "const char __user *buf "  ","
.BI "size_t count "  ","
.BI "loff_t *ppos "  ");"
.SH ARGUMENTS
.IP "file" 12
Pointer to "struct file".
.IP "buf" 12
Pointer to buffer.
.IP "count" 12
Size of \fIbuf\fP.
.IP "ppos" 12
Unused.
.SH "DESCRIPTION"
Returns \fIcount\fP on success, negative value otherwise.
