.TH "tpm_cr50_i2c_probe" 9 "tpm_cr50_i2c_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tpm_cr50_i2c_probe \- Driver probe function.
.SH SYNOPSIS
.B "int" tpm_cr50_i2c_probe
.BI "(struct i2c_client *client "  ","
.BI "const struct i2c_device_id *id "  ");"
.SH ARGUMENTS
.IP "client" 12
I2C client information.
.IP "id" 12
I2C device id.
.SH "RETURN"
- 0:         Success.
- -errno:    A POSIX error code.
