.TH "tpm_dev_release" 9 "tpm_dev_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tpm_dev_release \- free chip memory and the device number
.SH SYNOPSIS
.B "void" tpm_dev_release
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the character device for the TPM chip
.SH "DESCRIPTION"
This is used as the release function for the character device.
