.TH "tracing_snapshot_cond_disable" 9 "tracing_snapshot_cond_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tracing_snapshot_cond_disable \- disable conditional snapshot for an instance
.SH SYNOPSIS
.B "int" tracing_snapshot_cond_disable
.BI "(struct trace_array *tr "  ");"
.SH ARGUMENTS
.IP "tr" 12
The tracing instance
.SH "DESCRIPTION"
Check whether the conditional snapshot for the given instance is
enabled; if so, free the cond_snapshot associated with it,
otherwise return -EINVAL.

Returns 0 if successful, error otherwise.
