.TH "tracing_on" 9 "tracing_on" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tracing_on \- enable tracing buffers
.SH SYNOPSIS
.B "void" tracing_on
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This function enables tracing buffers that may have been
disabled with tracing_off.
