.TH "trace_vbprintk" 9 "trace_vbprintk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
trace_vbprintk \- write binary msg to tracing buffer
.SH SYNOPSIS
.B "int" trace_vbprintk
.BI "(unsigned long ip "  ","
.BI "const char *fmt "  ","
.BI "va_list args "  ");"
.SH ARGUMENTS
.IP "ip" 12
The address of the caller
.IP "fmt" 12
The string format to write to the buffer
.IP "args" 12
Arguments for \fIfmt\fP
