.TH "tracefs_remove" 9 "tracefs_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tracefs_remove \- recursively removes a directory
.SH SYNOPSIS
.B "void" tracefs_remove
.BI "(struct dentry *dentry "  ");"
.SH ARGUMENTS
.IP "dentry" 12
a pointer to a the dentry of the directory to be removed.
.SH "DESCRIPTION"
This function recursively removes a directory tree in tracefs that
was previously created with a call to another tracefs function
(like \fBtracefs_create_file\fP or variants thereof.)
