.TH "tracepoint_probe_unregister" 9 "tracepoint_probe_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tracepoint_probe_unregister \- Disconnect a probe from a tracepoint
.SH SYNOPSIS
.B "int" tracepoint_probe_unregister
.BI "(struct tracepoint *tp "  ","
.BI "void *probe "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "tp" 12
tracepoint
.IP "probe" 12
probe function pointer
.IP "data" 12
tracepoint data
.SH "DESCRIPTION"
Returns 0 if ok, error value on error.
