.TH "trms1040_read_all" 9 "trms1040_read_all" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
trms1040_read_all \- read all bytes from the eeprom
.SH SYNOPSIS
.B "void" trms1040_read_all
.BI "(struct NvRamType *eeprom "  ","
.BI "unsigned long io_port "  ");"
.SH ARGUMENTS
.IP "eeprom" 12
where to store the data
.IP "io_port" 12
the base io port
.SH "DESCRIPTION"

Read the 128 bytes from the SEEPROM.
