.TH "try_offline_node" 9 "try_offline_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
try_offline_node \- 
.SH SYNOPSIS
.B "void" try_offline_node
.BI "(int nid "  ");"
.SH ARGUMENTS
.IP "nid" 12
the node ID
.SH "DESCRIPTION"
Offline a node if all memory sections and cpus of the node are removed.
.SH "NOTE"
The caller must call \fBlock_device_hotplug\fP to serialize hotplug
and online/offline operations before this call.
