.TH "tsi721_add_outb_message" 9 "tsi721_add_outb_message" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tsi721_add_outb_message \- Add message to the Tsi721 outbound message queue
.SH SYNOPSIS
.B "int" tsi721_add_outb_message
.BI "(struct rio_mport *mport "  ","
.BI "struct rio_dev *rdev "  ","
.BI "int mbox "  ","
.BI "void *buffer "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "mport" 12
Master port with outbound message queue
.IP "rdev" 12
Target of outbound message
.IP "mbox" 12
Outbound mailbox
.IP "buffer" 12
Message to add to outbound queue
.IP "len" 12
Length of message
