.TH "tsi721_query_mport" 9 "tsi721_query_mport" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tsi721_query_mport \- Fetch inbound message from the Tsi721 MSG Queue
.SH SYNOPSIS
.B "int" tsi721_query_mport
.BI "(struct rio_mport *mport "  ","
.BI "struct rio_mport_attr *attr "  ");"
.SH ARGUMENTS
.IP "mport" 12
Master port implementing the Inbound Messaging Engine
.IP "attr" 12
-- undescribed --
.SH "DESCRIPTION"
Returns pointer to the message on success or NULL on failure.
