.TH "ttm_mem_evict_wait_busy" 9 "ttm_mem_evict_wait_busy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ttm_mem_evict_wait_busy \- wait for a busy BO to become available
.SH SYNOPSIS
.B "int" ttm_mem_evict_wait_busy
.BI "(struct ttm_buffer_object *busy_bo "  ","
.BI "struct ttm_operation_ctx *ctx "  ","
.BI "struct ww_acquire_ctx *ticket "  ");"
.SH ARGUMENTS
.IP "busy_bo" 12
BO which couldn't be locked with trylock
.IP "ctx" 12
operation context
.IP "ticket" 12
acquire ticket
.SH "DESCRIPTION"
Try to lock a busy buffer object to avoid failing eviction.
