.TH "tty_ldisc_get" 9 "tty_ldisc_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tty_ldisc_get \- take a reference to an ldisc
.SH SYNOPSIS
.B "struct tty_ldisc *" tty_ldisc_get
.BI "(struct tty_struct *tty "  ","
.BI "int disc "  ");"
.SH ARGUMENTS
.IP "tty" 12
tty device
.IP "disc" 12
ldisc number

Takes a reference to a line discipline. Deals with refcounts and
module locking counts.
.SH "RETURN"
-EINVAL if the discipline index is not [N_TTY..NR_LDISCS] or
if the discipline is not registered
-EAGAIN if \fBrequest_module\fP failed to load or register the
the discipline
-ENOMEM if allocation failure

Otherwise, returns a pointer to the discipline and bumps the
ref count

Locking:
takes tty_ldiscs_lock to guard against ldisc races
