.TH "tty_port_unregister_device" 9 "tty_port_unregister_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tty_port_unregister_device \- deregister a tty or serdev device
.SH SYNOPSIS
.B "void" tty_port_unregister_device
.BI "(struct tty_port *port "  ","
.BI "struct tty_driver *driver "  ","
.BI "unsigned index "  ");"
.SH ARGUMENTS
.IP "port" 12
tty_port of the device
.IP "driver" 12
tty_driver for this device
.IP "index" 12
index of the tty
.SH "DESCRIPTION"
If a tty or serdev device is registered with a call to
\fBtty_port_register_device_serdev\fP then this function must be called when
the device is gone.
