.TH "tuner_g_frequency" 9 "tuner_g_frequency" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tuner_g_frequency \- Get the tuned frequency for the tuner
.SH SYNOPSIS
.B "int" tuner_g_frequency
.BI "(struct v4l2_subdev *sd "  ","
.BI "struct v4l2_frequency *f "  ");"
.SH ARGUMENTS
.IP "sd" 12
pointer to struct v4l2_subdev
.IP "f" 12
pointer to struct v4l2_frequency
.SH "DESCRIPTION"
At return, the structure f will be filled with tuner frequency
if the tuner matches the f->type.
.SH "NOTE"
f->type should be initialized before calling it.
This is done by either video_ioctl2 or by the bridge driver.
