.TH "typec_cable_is_active" 9 "typec_cable_is_active" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
typec_cable_is_active \- Check is the USB Type-C cable active or passive
.SH SYNOPSIS
.B "int" typec_cable_is_active
.BI "(struct typec_cable *cable "  ");"
.SH ARGUMENTS
.IP "cable" 12
The USB Type-C Cable
.SH "DESCRIPTION"
Return 1 if the cable is active or 0 if it's passive.
