.TH "typec_match_altmode" 9 "typec_match_altmode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
typec_match_altmode \- Match SVID and mode to an array of alternate modes
.SH SYNOPSIS
.B "struct typec_altmode *" typec_match_altmode
.BI "(struct typec_altmode **altmodes "  ","
.BI "size_t n "  ","
.BI "u16 svid "  ","
.BI "u8 mode "  ");"
.SH ARGUMENTS
.IP "altmodes" 12
Array of alternate modes
.IP "n" 12
Number of elements in the array, or -1 for NULL terminated arrays
.IP "svid" 12
Standard or Vendor ID to match with
.IP "mode" 12
Mode to match with
.SH "DESCRIPTION"
Return pointer to an alternate mode with SVID matching \fIsvid\fP, or NULL when no
match is found.
