.TH "typec_altmode_vdm" 9 "typec_altmode_vdm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
typec_altmode_vdm \- Send Vendor Defined Messages (VDM) to the partner
.SH SYNOPSIS
.B "int" typec_altmode_vdm
.BI "(struct typec_altmode *adev "  ","
.BI "const u32 header "  ","
.BI "const u32 *vdo "  ","
.BI "int count "  ");"
.SH ARGUMENTS
.IP "adev" 12
Alternate mode handle
.IP "header" 12
VDM Header
.IP "vdo" 12
Array of Vendor Defined Data Objects
.IP "count" 12
Number of Data Objects
.SH "DESCRIPTION"
The alternate mode drivers use this function for SVID specific communication
with the partner. The port drivers use it to deliver the Structured VDMs
received from the partners to the alternate mode drivers.
