.TH "typec_set_data_role" 9 "typec_set_data_role" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
typec_set_data_role \- Report data role change
.SH SYNOPSIS
.B "void" typec_set_data_role
.BI "(struct typec_port *port "  ","
.BI "enum typec_data_role role "  ");"
.SH ARGUMENTS
.IP "port" 12
The USB Type-C Port where the role was changed
.IP "role" 12
The new data role
.SH "DESCRIPTION"
This routine is used by the port drivers to report data role changes.
