.TH "uart_get_divisor" 9 "uart_get_divisor" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uart_get_divisor \- return uart clock divisor
.SH SYNOPSIS
.B "unsigned int" uart_get_divisor
.BI "(struct uart_port *port "  ","
.BI "unsigned int baud "  ");"
.SH ARGUMENTS
.IP "port" 12
uart_port structure describing the port.
.IP "baud" 12
desired baud rate

Calculate the uart clock divisor for the port.
