.TH "ubi_attach_fastmap" 9 "ubi_attach_fastmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubi_attach_fastmap \- creates ubi_attach_info from a fastmap.
.SH SYNOPSIS
.B "int" ubi_attach_fastmap
.BI "(struct ubi_device *ubi "  ","
.BI "struct ubi_attach_info *ai "  ","
.BI "struct ubi_fastmap_layout *fm "  ");"
.SH ARGUMENTS
.IP "ubi" 12
UBI device object
.IP "ai" 12
UBI attach info object
.IP "fm" 12
the fastmap to be attached
.SH "DESCRIPTION"
Returns 0 on success, UBI_BAD_FASTMAP if the found fastmap was unusable.
< 0 indicates an internal error.
