.TH "ubi_dump_flash" 9 "ubi_dump_flash" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubi_dump_flash \- dump a region of flash.
.SH SYNOPSIS
.B "void" ubi_dump_flash
.BI "(struct ubi_device *ubi "  ","
.BI "int pnum "  ","
.BI "int offset "  ","
.BI "int len "  ");"
.SH ARGUMENTS
.IP "ubi" 12
UBI device description object
.IP "pnum" 12
the physical eraseblock number to dump
.IP "offset" 12
the starting offset within the physical eraseblock to dump
.IP "len" 12
the length of the region to dump
