.TH "ubi_eba_replace_table" 9 "ubi_eba_replace_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubi_eba_replace_table \- assign a new EBA table to a volume
.SH SYNOPSIS
.B "void" ubi_eba_replace_table
.BI "(struct ubi_volume *vol "  ","
.BI "struct ubi_eba_table *tbl "  ");"
.SH ARGUMENTS
.IP "vol" 12
volume containing the EBA table to copy
.IP "tbl" 12
new EBA table
.SH "DESCRIPTION"
Assign a new EBA table to the volume and release the old one.
