.TH "ubi_resize_volume" 9 "ubi_resize_volume" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubi_resize_volume \- re-size volume.
.SH SYNOPSIS
.B "int" ubi_resize_volume
.BI "(struct ubi_volume_desc *desc "  ","
.BI "int reserved_pebs "  ");"
.SH ARGUMENTS
.IP "desc" 12
volume descriptor
.IP "reserved_pebs" 12
new size in physical eraseblocks
.SH "DESCRIPTION"
This function re-sizes the volume and returns zero in case of success, and a
negative error code in case of failure. The caller has to have the
\fIubi->device_mutex\fP locked.
