.TH "ubi_debugfs_init" 9 "ubi_debugfs_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubi_debugfs_init \- create UBI debugfs directory.
.SH SYNOPSIS
.B "int" ubi_debugfs_init
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Create UBI debugfs directory. Returns zero in case of success and a negative
error code in case of failure.
