.TH "ubifs_garbage_collect_leb" 9 "ubifs_garbage_collect_leb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubifs_garbage_collect_leb \- garbage-collect a logical eraseblock.
.SH SYNOPSIS
.B "int" ubifs_garbage_collect_leb
.BI "(struct ubifs_info *c "  ","
.BI "struct ubifs_lprops *lp "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "lp" 12
describes the LEB to garbage collect
.SH "DESCRIPTION"
This function garbage-collects an LEB and returns one of the \fILEB_FREED\fP,
\fILEB_RETAINED\fP, etc positive codes in case of success, -EAGAIN if commit is
required, and other negative error codes in case of failures.
