.TH "ubifs_decompress" 9 "ubifs_decompress" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubifs_decompress \- decompress data.
.SH SYNOPSIS
.B "int" ubifs_decompress
.BI "(const struct ubifs_info *c "  ","
.BI "const void *in_buf "  ","
.BI "int in_len "  ","
.BI "void *out_buf "  ","
.BI "int *out_len "  ","
.BI "int compr_type "  ");"
.SH ARGUMENTS
.IP "c" 12
-- undescribed --
.IP "in_buf" 12
data to decompress
.IP "in_len" 12
length of the data to decompress
.IP "out_buf" 12
output buffer where decompressed data should
.IP "out_len" 12
output length is returned here
.IP "compr_type" 12
type of compression
.SH "DESCRIPTION"
This function decompresses data from buffer \fIin_buf\fP into buffer \fIout_buf\fP.
The length of the uncompressed data is returned in \fIout_len\fP. This functions
returns 0 on success or a negative error code on failure.
