.TH "ubifs_convert_page_budget" 9 "ubifs_convert_page_budget" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubifs_convert_page_budget \- convert budget of a new page.
.SH SYNOPSIS
.B "void" ubifs_convert_page_budget
.BI "(struct ubifs_info *c "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.SH "DESCRIPTION"
This function converts budget which was allocated for a new page of data to
the budget of changing an existing page of data. The latter is smaller than
the former, so this function only does simple re-calculation and does not
involve any write-back.
