.TH "uclogic_params_frame_cleanup" 9 "uclogic_params_frame_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uclogic_params_frame_cleanup \- free resources used by struct uclogic_params_frame (tablet interface's frame controls input parameters). Can be called repeatedly.
.SH SYNOPSIS
.B "void" uclogic_params_frame_cleanup
.BI "(struct uclogic_params_frame *frame "  ");"
.SH ARGUMENTS
.IP "frame" 12
Frame controls input parameters to cleanup. Cannot be NULL.
