.TH "uclogic_inrange_timeout" 9 "uclogic_inrange_timeout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uclogic_inrange_timeout \- handle pen in-range state timeout. Emulate input events normally generated when pen goes out of range for tablets which don't report that.
.SH SYNOPSIS
.B "void" uclogic_inrange_timeout
.BI "(struct timer_list *t "  ");"
.SH ARGUMENTS
.IP "t" 12
The timer the timeout handler is attached to, stored in a struct
uclogic_drvdata.
