.TH "uclogic_params_init_with_pen_unused" 9 "uclogic_params_init_with_pen_unused" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uclogic_params_init_with_pen_unused \- initialize tablet interface parameters preserving original reports and generic HID processing, but disabling pen usage.
.SH SYNOPSIS
.B "void" uclogic_params_init_with_pen_unused
.BI "(struct uclogic_params *params "  ");"
.SH ARGUMENTS
.IP "params" 12
Parameters to initialize (to be cleaned with
\fBuclogic_params_cleanup\fP). Not modified in case of
error. Cannot be NULL.
