.TH "uclogic_params_init_invalid" 9 "uclogic_params_init_invalid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uclogic_params_init_invalid \- initialize tablet interface parameters, specifying the interface is invalid.
.SH SYNOPSIS
.B "void" uclogic_params_init_invalid
.BI "(struct uclogic_params *params "  ");"
.SH ARGUMENTS
.IP "params" 12
Parameters to initialize (to be cleaned with
\fBuclogic_params_cleanup\fP). Cannot be NULL.
