.TH "ucsi_init" 9 "ucsi_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ucsi_init \- Initialize UCSI interface
.SH SYNOPSIS
.B "int" ucsi_init
.BI "(struct ucsi *ucsi "  ");"
.SH ARGUMENTS
.IP "ucsi" 12
UCSI to be initialized
.SH "DESCRIPTION"
Registers all ports \fIucsi\fP has and enables all notification events.
