.TH "ufshcd_prepare_utp_scsi_cmd_upiu" 9 "ufshcd_prepare_utp_scsi_cmd_upiu" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_prepare_utp_scsi_cmd_upiu \- fills the utp_transfer_req_desc, for scsi commands
.SH SYNOPSIS
.B "void" ufshcd_prepare_utp_scsi_cmd_upiu
.BI "(struct ufshcd_lrb *lrbp "  ","
.BI "u8 upiu_flags "  ");"
.SH ARGUMENTS
.IP "lrbp" 12
local reference block pointer
.IP "upiu_flags" 12
flags
