.TH "ufshcd_disable_intr" 9 "ufshcd_disable_intr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_disable_intr \- disable interrupts
.SH SYNOPSIS
.B "void" ufshcd_disable_intr
.BI "(struct ufs_hba *hba "  ","
.BI "u32 intrs "  ");"
.SH ARGUMENTS
.IP "hba" 12
per adapter instance
.IP "intrs" 12
interrupt bits
