.TH "ufshcd_is_devfreq_scaling_required" 9 "ufshcd_is_devfreq_scaling_required" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_is_devfreq_scaling_required \- check if scaling is required or not
.SH SYNOPSIS
.B "bool" ufshcd_is_devfreq_scaling_required
.BI "(struct ufs_hba *hba "  ","
.BI "bool scale_up "  ");"
.SH ARGUMENTS
.IP "hba" 12
per adapter instance
.IP "scale_up" 12
True if scaling up and false if scaling down
.SH "DESCRIPTION"
Returns true if scaling is required, false otherwise.
