.TH "ufshcd_set_dev_pwr_mode" 9 "ufshcd_set_dev_pwr_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_set_dev_pwr_mode \- sends START STOP UNIT command to set device power mode
.SH SYNOPSIS
.B "int" ufshcd_set_dev_pwr_mode
.BI "(struct ufs_hba *hba "  ","
.BI "enum ufs_dev_pwr_mode pwr_mode "  ");"
.SH ARGUMENTS
.IP "hba" 12
per adapter instance
.IP "pwr_mode" 12
device power mode to set
.SH "DESCRIPTION"
Returns 0 if requested power mode is set successfully
Returns non-zero if failed to set the requested power mode
