.TH "ufshcd_utrl_clear" 9 "ufshcd_utrl_clear" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_utrl_clear \- Clear a bit in UTRLCLR register
.SH SYNOPSIS
.B "void" ufshcd_utrl_clear
.BI "(struct ufs_hba *hba "  ","
.BI "u32 pos "  ");"
.SH ARGUMENTS
.IP "hba" 12
per adapter instance
.IP "pos" 12
position of the bit to be cleared
