.TH "ufshcd_pltfrm_suspend" 9 "ufshcd_pltfrm_suspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_pltfrm_suspend \- suspend power management function
.SH SYNOPSIS
.B "int" ufshcd_pltfrm_suspend
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to device handle
.SH "DESCRIPTION"
Returns 0 if successful
Returns non-zero otherwise
