.TH "uif_init" 9 "uif_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uif_init \- initialize user interfaces for an UBI device.
.SH SYNOPSIS
.B "int" uif_init
.BI "(struct ubi_device *ubi "  ");"
.SH ARGUMENTS
.IP "ubi" 12
UBI device description object
.SH "DESCRIPTION"
This function initializes various user interfaces for an UBI device. If the
initialization fails at an early stage, this function frees all the
resources it allocated, returns an error.

This function returns zero in case of success and a negative error code in
case of failure.
