.TH "ulist_free" 9 "ulist_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ulist_free \- free dynamically allocated ulist
.SH SYNOPSIS
.B "void" ulist_free
.BI "(struct ulist *ulist "  ");"
.SH ARGUMENTS
.IP "ulist" 12
ulist to free
.SH "DESCRIPTION"
It is not necessary to call ulist_release before.
