.TH "unpack_table" 9 "unpack_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
unpack_table \- unpack a dfa table (one of accept, default, base, next check)
.SH SYNOPSIS
.B "struct table_header *" unpack_table
.BI "(char *blob "  ","
.BI "size_t bsize "  ");"
.SH ARGUMENTS
.IP "blob" 12
data to unpack (NOT NULL)
.IP "bsize" 12
size of blob
.SH "RETURN"
pointer to table else NULL on failure
.SH "NOTE"
must be freed by kvfree (not kfree)
