.TH "unpin_user_pages" 9 "unpin_user_pages" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
unpin_user_pages \- release an array of gup-pinned pages.
.SH SYNOPSIS
.B "void" unpin_user_pages
.BI "(struct page **pages "  ","
.BI "unsigned long npages "  ");"
.SH ARGUMENTS
.IP "pages" 12
array of pages to be marked dirty and released.
.IP "npages" 12
number of pages in the \fIpages\fP array.
.SH "DESCRIPTION"
For each page in the \fIpages\fP array, release the page using \fBunpin_user_page\fP.

Please see the \fBunpin_user_page\fP documentation for details.
