.TH "unregister_syscore_ops" 9 "unregister_syscore_ops" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
unregister_syscore_ops \- Unregister a set of system core operations.
.SH SYNOPSIS
.B "void" unregister_syscore_ops
.BI "(struct syscore_ops *ops "  ");"
.SH ARGUMENTS
.IP "ops" 12
System core operations to unregister.
