.TH "update_note_header_size_elf64" 9 "update_note_header_size_elf64" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
update_note_header_size_elf64 \- update p_memsz member of each PT_NOTE entry
.SH SYNOPSIS
.B "int" update_note_header_size_elf64
.BI "(const Elf64_Ehdr *ehdr_ptr "  ");"
.SH ARGUMENTS
.IP "ehdr_ptr" 12
ELF header
.SH "DESCRIPTION"
This function updates p_memsz member of each PT_NOTE entry in the
program header table pointed to by \fIehdr_ptr\fP to real size of ELF
note segment.
