.TH "update_max_tr" 9 "update_max_tr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
update_max_tr \- snapshot all trace buffers from global_trace to max_tr
.SH SYNOPSIS
.B "void" update_max_tr
.BI "(struct trace_array *tr "  ","
.BI "struct task_struct *tsk "  ","
.BI "int cpu "  ","
.BI "void *cond_data "  ");"
.SH ARGUMENTS
.IP "tr" 12
tracer
.IP "tsk" 12
the task with the latency
.IP "cpu" 12
The cpu that initiated the trace.
.IP "cond_data" 12
User data associated with a conditional snapshot
.SH "DESCRIPTION"
Flip the buffers between the \fItr\fP and the max_tr and record information
about which task was the cause of this latency.
