.TH "update_node_properties" 9 "update_node_properties" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
update_node_properties \- adds the properties of np into dup node (present in live tree) and updates parent of children of np to dup.
.SH SYNOPSIS
.B "void" update_node_properties
.BI "(struct device_node *np "  ","
.BI "struct device_node *dup "  ");"
.SH ARGUMENTS
.IP "np" 12
node whose properties are being added to the live tree
.IP "dup" 12
node present in live tree to be updated
