.TH "update_devfreq" 9 "update_devfreq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
update_devfreq \- Reevaluate the device and configure frequency.
.SH SYNOPSIS
.B "int" update_devfreq
.BI "(struct devfreq *devfreq "  ");"
.SH ARGUMENTS
.IP "devfreq" 12
the devfreq instance.
.SH "NOTE"
Lock devfreq->lock before calling update_devfreq
This function is exported for governors.
