.TH "update_outbnd_queue_table" 9 "update_outbnd_queue_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
update_outbnd_queue_table \- update the outbound queue table to the HBA.
.SH SYNOPSIS
.B "void" update_outbnd_queue_table
.BI "(struct pm8001_hba_info *pm8001_ha "  ","
.BI "int number "  ");"
.SH ARGUMENTS
.IP "pm8001_ha" 12
our hba card information
.IP "number" 12
entry in the queue
