.TH "usb4_port_retimer_nvm_read" 9 "usb4_port_retimer_nvm_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb4_port_retimer_nvm_read \- Read contents of retimer NVM
.SH SYNOPSIS
.B "int" usb4_port_retimer_nvm_read
.BI "(struct tb_port *port "  ","
.BI "u8 index "  ","
.BI "unsigned int address "  ","
.BI "void *buf "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "port" 12
USB4 port
.IP "index" 12
Retimer index
.IP "address" 12
NVM address (in bytes) to start reading
.IP "buf" 12
Data read from NVM is stored here
.IP "size" 12
Number of bytes to read
.SH "DESCRIPTION"
Reads retimer NVM and copies the contents to \fIbuf\fP. Returns 0 if the
read was successful and negative errno in case of failure.
Specifically returns -ENODEV if there is no retimer at \fIindex\fP.
