.TH "usb4_switch_map_pcie_down" 9 "usb4_switch_map_pcie_down" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb4_switch_map_pcie_down \- Map USB4 port to a PCIe downstream adapter
.SH SYNOPSIS
.B "struct tb_port *" usb4_switch_map_pcie_down
.BI "(struct tb_switch *sw "  ","
.BI "const struct tb_port *port "  ");"
.SH ARGUMENTS
.IP "sw" 12
USB4 router
.IP "port" 12
USB4 port
.SH "DESCRIPTION"
USB4 routers have direct mapping between USB4 ports and PCIe
downstream adapters where the PCIe topology is extended. This
function returns the corresponding downstream PCIe adapter or NULL
if no such mapping was possible.
