.TH "usb_gadget_clear_selfpowered" 9 "usb_gadget_clear_selfpowered" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_gadget_clear_selfpowered \- clear the device selfpowered feature.
.SH SYNOPSIS
.B "int" usb_gadget_clear_selfpowered
.BI "(struct usb_gadget *gadget "  ");"
.SH ARGUMENTS
.IP "gadget" 12
the device being declared as bus-powered
.SH "DESCRIPTION"
this affects the device status reported by the hardware driver.
some hardware may not support bus-powered operation, in which
case this feature's value can never change.

returns zero on success, else negative errno.
