.TH "usb_reset_endpoint" 9 "usb_reset_endpoint" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_reset_endpoint \- Reset an endpoint's state.
.SH SYNOPSIS
.B "void" usb_reset_endpoint
.BI "(struct usb_device *dev "  ","
.BI "unsigned int epaddr "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device whose endpoint is to be reset
.IP "epaddr" 12
the endpoint's address.  Endpoint number for output,
endpoint number + USB_DIR_IN for input
.SH "DESCRIPTION"
Resets any host-side endpoint state such as the toggle bit,
sequence number or current window.
