.TH "usb_acpi_set_power_state" 9 "usb_acpi_set_power_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_acpi_set_power_state \- control usb port's power via acpi power resource
.SH SYNOPSIS
.B "int" usb_acpi_set_power_state
.BI "(struct usb_device *hdev "  ","
.BI "int index "  ","
.BI "bool enable "  ");"
.SH ARGUMENTS
.IP "hdev" 12
USB device belonging to the usb hub
.IP "index" 12
port index based zero
.IP "enable" 12
power state expected to be set
.SH "DESCRIPTION"
Notice to use \fBusb_acpi_power_manageable\fP to check whether the usb port
has acpi power resource before invoking this function.

Returns 0 on success, else negative errno.
