.TH "usb_cdc_wdm_register" 9 "usb_cdc_wdm_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_cdc_wdm_register \- register a WDM subdriver
.SH SYNOPSIS
.B "struct usb_driver *" usb_cdc_wdm_register
.BI "(struct usb_interface *intf "  ","
.BI "struct usb_endpoint_descriptor *ep "  ","
.BI "int bufsize "  ","
.BI "int (*manage_power)(struct usb_interface *, int) "  ");"
.SH ARGUMENTS
.IP "intf" 12
usb interface the subdriver will associate with
.IP "ep" 12
interrupt endpoint to monitor for notifications
.IP "bufsize" 12
maximum message size to support for read/write
.IP "manage_power" 12
call-back invoked during open and release to
manage the device's power
Create WDM usb class character device and associate it with intf
without binding, allowing another driver to manage the interface.
.SH "DESCRIPTION"
The subdriver will manage the given interrupt endpoint exclusively
and will issue control requests referring to the given intf. It
will otherwise avoid interferring, and in particular not do
usb_set_intfdata/usb_get_intfdata on intf.

The return value is a pointer to the subdriver's struct usb_driver.
The registering driver is responsible for calling this subdriver's
disconnect, suspend, resume, pre_reset and post_reset methods from
its own.
