.TH "usb_register_device_driver" 9 "usb_register_device_driver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_register_device_driver \- register a USB device (not interface) driver
.SH SYNOPSIS
.B "int" usb_register_device_driver
.BI "(struct usb_device_driver *new_udriver "  ","
.BI "struct module *owner "  ");"
.SH ARGUMENTS
.IP "new_udriver" 12
USB operations for the device driver
.IP "owner" 12
module owner of this driver.
.SH "DESCRIPTION"
Registers a USB device driver with the USB core.  The list of
unattached devices will be rescanned whenever a new driver is
added, allowing the new driver to attach to any recognized devices.
.SH "RETURN"
A negative error code on failure and 0 on success.
