.TH "userfaultfd_ctx_get" 9 "userfaultfd_ctx_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
userfaultfd_ctx_get \- Acquires a reference to the internal userfaultfd context.
.SH SYNOPSIS
.B "void" userfaultfd_ctx_get
.BI "(struct userfaultfd_ctx *ctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
[in] Pointer to the userfaultfd context.
