.TH "userio_device_write" 9 "userio_device_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
userio_device_write \- Write data from serio to a userio device in userspace
.SH SYNOPSIS
.B "int" userio_device_write
.BI "(struct serio *id "  ","
.BI "unsigned char val "  ");"
.SH ARGUMENTS
.IP "id" 12
The serio port for the userio device
.IP "val" 12
The data to write to the device
