.TH "uvd_v3_1_ring_emit_fence" 9 "uvd_v3_1_ring_emit_fence" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uvd_v3_1_ring_emit_fence \- emit an fence & trap command
.SH SYNOPSIS
.B "void" uvd_v3_1_ring_emit_fence
.BI "(struct amdgpu_ring *ring "  ","
.BI "u64 addr "  ","
.BI "u64 seq "  ","
.BI "unsigned flags "  ");"
.SH ARGUMENTS
.IP "ring" 12
amdgpu_ring pointer
.IP "addr" 12
address
.IP "seq" 12
sequence number
.IP "flags" 12
fence related flags
.SH "DESCRIPTION"
Write a fence and a trap command to the ring.
