.TH "uvd_v3_1_semaphore_emit" 9 "uvd_v3_1_semaphore_emit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uvd_v3_1_semaphore_emit \- emit semaphore command
.SH SYNOPSIS
.B "bool" uvd_v3_1_semaphore_emit
.BI "(struct radeon_device *rdev "  ","
.BI "struct radeon_ring *ring "  ","
.BI "struct radeon_semaphore *semaphore "  ","
.BI "bool emit_wait "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ring" 12
radeon_ring pointer
.IP "semaphore" 12
semaphore to emit commands for
.IP "emit_wait" 12
true if we should emit a wait command
.SH "DESCRIPTION"
Emit a semaphore command (either wait or signal) to the UVD ring.
