.TH "uvd_v4_2_hw_init" 9 "uvd_v4_2_hw_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uvd_v4_2_hw_init \- start and test UVD block
.SH SYNOPSIS
.B "int" uvd_v4_2_hw_init
.BI "(void *handle "  ");"
.SH ARGUMENTS
.IP "handle" 12
handle used to pass amdgpu_device pointer
.SH "DESCRIPTION"
Initialize the hardware, boot up the VCPU and do some testing
