.TH "v3d_submit_tfu_ioctl" 9 "v3d_submit_tfu_ioctl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
v3d_submit_tfu_ioctl \- Submits a TFU (texture formatting) job to the V3D.
.SH SYNOPSIS
.B "int" v3d_submit_tfu_ioctl
.BI "(struct drm_device *dev "  ","
.BI "void *data "  ","
.BI "struct drm_file *file_priv "  ");"
.SH ARGUMENTS
.IP "dev" 12
DRM device
.IP "data" 12
ioctl argument
.IP "file_priv" 12
DRM file for this fd
.SH "DESCRIPTION"
Userspace provides the register setup for the TFU, which we don't
need to validate since the TFU is behind the MMU.
