.TH "v4l2_jpeg_parse_frame_header" 9 "v4l2_jpeg_parse_frame_header" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
v4l2_jpeg_parse_frame_header \- parse frame header
.SH SYNOPSIS
.B "int" v4l2_jpeg_parse_frame_header
.BI "(void *buf "  ","
.BI "size_t len "  ","
.BI "struct v4l2_jpeg_frame_header *frame_header "  ");"
.SH ARGUMENTS
.IP "buf" 12
address of the frame header, after the SOF0 marker
.IP "len" 12
length of the frame header
.IP "frame_header" 12
returns the parsed frame header
.SH "DESCRIPTION"
Returns 0 or negative error if parsing failed.
