.TH "v9fs_session_cancel" 9 "v9fs_session_cancel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
v9fs_session_cancel \- terminate a session
.SH SYNOPSIS
.B "void" v9fs_session_cancel
.BI "(struct v9fs_session_info *v9ses "  ");"
.SH ARGUMENTS
.IP "v9ses" 12
session to terminate
.SH "DESCRIPTION"
mark transport as disconnected and cancel all pending requests.
