.TH "v9fs_release_page" 9 "v9fs_release_page" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
v9fs_release_page \- release the private state associated with a page
.SH SYNOPSIS
.B "int" v9fs_release_page
.BI "(struct page *page "  ","
.BI "gfp_t gfp "  ");"
.SH ARGUMENTS
.IP "page" 12
-- undescribed --
.IP "gfp" 12
-- undescribed --
.SH "DESCRIPTION"

Returns 1 if the page can be released, false otherwise.
