.TH "v9fs_stat2inode_dotl" 9 "v9fs_stat2inode_dotl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
v9fs_stat2inode_dotl \- populate an inode structure with stat info
.SH SYNOPSIS
.B "void" v9fs_stat2inode_dotl
.BI "(struct p9_stat_dotl *stat "  ","
.BI "struct inode *inode "  ","
.BI "unsigned int flags "  ");"
.SH ARGUMENTS
.IP "stat" 12
stat structure
.IP "inode" 12
inode to populate
.IP "flags" 12
ctrl flags (e.g. V9FS_STAT2INODE_KEEP_ISIZE)
