.TH "v9fs_dir_readdir_dotl" 9 "v9fs_dir_readdir_dotl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
v9fs_dir_readdir_dotl \- iterate through a directory
.SH SYNOPSIS
.B "int" v9fs_dir_readdir_dotl
.BI "(struct file *file "  ","
.BI "struct dir_context *ctx "  ");"
.SH ARGUMENTS
.IP "file" 12
opened file structure
.IP "ctx" 12
actor we feed the entries to
