.TH "v9fs_vfs_link_dotl" 9 "v9fs_vfs_link_dotl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
v9fs_vfs_link_dotl \- create a hardlink for dotl
.SH SYNOPSIS
.B "int" v9fs_vfs_link_dotl
.BI "(struct dentry *old_dentry "  ","
.BI "struct inode *dir "  ","
.BI "struct dentry *dentry "  ");"
.SH ARGUMENTS
.IP "old_dentry" 12
dentry for file to link to
.IP "dir" 12
inode destination for new link
.IP "dentry" 12
dentry for link
