.TH "vce_v3_0_start" 9 "vce_v3_0_start" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vce_v3_0_start \- start VCE block
.SH SYNOPSIS
.B "int" vce_v3_0_start
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Setup and start the VCE block
