.TH "vchnl_pf_send_get_pe_stats_resp" 9 "vchnl_pf_send_get_pe_stats_resp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vchnl_pf_send_get_pe_stats_resp \- Send PE Stats to VF
.SH SYNOPSIS
.B "void" vchnl_pf_send_get_pe_stats_resp
.BI "(struct i40iw_sc_dev *dev "  ","
.BI "u32 vf_id "  ","
.BI "struct i40iw_virtchnl_op_buf *vchnl_msg "  ","
.BI "struct i40iw_dev_hw_stats *hw_stats "  ");"
.SH ARGUMENTS
.IP "dev" 12
IWARP device pointer
.IP "vf_id" 12
Virtual function ID associated with the message
.IP "vchnl_msg" 12
Virtual channel message buffer pointer
.IP "hw_stats" 12
HW Stats struct
