.TH "vdpa_unregister_driver" 9 "vdpa_unregister_driver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vdpa_unregister_driver \- unregister a vDPA device driver
.SH SYNOPSIS
.B "void" vdpa_unregister_driver
.BI "(struct vdpa_driver *drv "  ");"
.SH ARGUMENTS
.IP "drv" 12
the vdpa device driver to be unregistered
