.TH "vdpa_unregister_device" 9 "vdpa_unregister_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vdpa_unregister_device \- unregister a vDPA device
.SH SYNOPSIS
.B "void" vdpa_unregister_device
.BI "(struct vdpa_device *vdev "  ");"
.SH ARGUMENTS
.IP "vdev" 12
the vdpa device to be unregisted from vDPA bus
