.TH "ve_spc_set_resume_addr" 9 "ve_spc_set_resume_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ve_spc_set_resume_addr \- set the jump address used for warm boot
.SH SYNOPSIS
.B "void" ve_spc_set_resume_addr
.BI "(u32 cluster "  ","
.BI "u32 cpu "  ","
.BI "u32 addr "  ");"
.SH ARGUMENTS
.IP "cluster" 12
mpidr[15:8] bitfield describing cluster affinity level
.IP "cpu" 12
mpidr[7:0] bitfield describing cpu affinity level
.IP "addr" 12
physical resume address
