.TH "vec_cmp" 9 "vec_cmp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vec_cmp \- label comparison for set ordering
.SH SYNOPSIS
.B "int" vec_cmp
.BI "(struct aa_profile **a "  ","
.BI "int an "  ","
.BI "struct aa_profile **b "  ","
.BI "int bn "  ");"
.SH ARGUMENTS
.IP "a" 12
label to compare (NOT NULL)
.IP "an" 12
-- undescribed --
.IP "b" 12
-- undescribed --
.IP "bn" 12
-- undescribed --
.SH "RETURN"
<0  if a < vec
==0 if a == vec
>0  if a > vec
