.TH "velocity_poll_controller" 9 "velocity_poll_controller" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
velocity_poll_controller \- Velocity Poll controller function
.SH SYNOPSIS
.B "void" velocity_poll_controller
.BI "(struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
network device


Used by NETCONSOLE and other diagnostic tools to allow network I/P
with interrupts disabled.
