.TH "velocity_get_platform_info" 9 "velocity_get_platform_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
velocity_get_platform_info \- retrieve platform info for device
.SH SYNOPSIS
.B "int" velocity_get_platform_info
.BI "(struct velocity_info *vptr "  ");"
.SH ARGUMENTS
.IP "vptr" 12
velocity device

Retrieve the Platform configuration data that interests us
