.TH "velocity_print_link_status" 9 "velocity_print_link_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
velocity_print_link_status \- link status reporting
.SH SYNOPSIS
.B "void" velocity_print_link_status
.BI "(struct velocity_info *vptr "  ");"
.SH ARGUMENTS
.IP "vptr" 12
velocity to report on

Turn the link status of the velocity card into a kernel log
description of the new link state, detailing speed and duplex
status
