.TH "vema_get_port" 9 "vema_get_port" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vema_get_port \- - Gets the opa_vnic_vema_port
.SH SYNOPSIS
.B "struct opa_vnic_vema_port *" vema_get_port
.BI "(struct opa_vnic_ctrl_port *cport "  ","
.BI "u8 port_num "  ");"
.SH ARGUMENTS
.IP "cport" 12
pointer to control dev
.IP "port_num" 12
Port number
.SH "DESCRIPTION"
This function loops through the ports and returns
the opa_vnic_vema port structure that is associated
with the OPA port number
.SH "RETURN"
ptr to requested opa_vnic_vema_port strucure
if success, NULL if not
