.TH "verify_new_ex" 9 "verify_new_ex" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
verify_new_ex \- verifies if a new exception is allowed by parent cgroup's permissions
.SH SYNOPSIS
.B "bool" verify_new_ex
.BI "(struct dev_cgroup *dev_cgroup "  ","
.BI "struct dev_exception_item *refex "  ","
.BI "enum devcg_behavior behavior "  ");"
.SH ARGUMENTS
.IP "dev_cgroup" 12
dev cgroup to be tested against
.IP "refex" 12
new exception
.IP "behavior" 12
behavior of the exception's dev_cgroup
.SH "DESCRIPTION"
This is used to make sure a child cgroup won't have more privileges
than its parent
