.TH "verify_signature" 9 "verify_signature" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
verify_signature \- Initiate the use of an asymmetric key to verify a signature
.SH SYNOPSIS
.B "int" verify_signature
.BI "(const struct key *key "  ","
.BI "const struct public_key_signature *sig "  ");"
.SH ARGUMENTS
.IP "key" 12
The asymmetric key to verify against
.IP "sig" 12
The signature to check
.SH "DESCRIPTION"
Returns 0 if successful or else an error.
