.TH "vgic_its_save_ite" 9 "vgic_its_save_ite" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vgic_its_save_ite \- Save an interrupt translation entry at @gpa
.SH SYNOPSIS
.B "int" vgic_its_save_ite
.BI "(struct vgic_its *its "  ","
.BI "struct its_device *dev "  ","
.BI "struct its_ite *ite "  ","
.BI "gpa_t gpa "  ","
.BI "int ite_esz "  ");"
.SH ARGUMENTS
.IP "its" 12
-- undescribed --
.IP "dev" 12
-- undescribed --
.IP "ite" 12
-- undescribed --
.IP "gpa" 12
-- undescribed --
.IP "ite_esz" 12
-- undescribed --
