.TH "vgic_v3_dispatch_sgi" 9 "vgic_v3_dispatch_sgi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vgic_v3_dispatch_sgi \- handle SGI requests from VCPUs
.SH SYNOPSIS
.B "void" vgic_v3_dispatch_sgi
.BI "(struct kvm_vcpu *vcpu "  ","
.BI "u64 reg "  ","
.BI "bool allow_group1 "  ");"
.SH ARGUMENTS
.IP "vcpu" 12
The VCPU requesting a SGI
.IP "reg" 12
The value written into ICC_{ASGI1,SGI0,SGI1}R by that VCPU
.IP "allow_group1" 12
Does the sysreg access allow generation of G1 SGIs
.SH "DESCRIPTION"
With GICv3 (and ARE=1) CPUs trigger SGIs by writing to a system register.
This will trap in sys_regs.c and call this function.
This ICC_SGI1R_EL1 register contains the upper three affinity levels of the
target processors as well as a bitmask of 16 Aff0 CPUs.
If the interrupt routing mode bit is not set, we iterate over all VCPUs to
check for matching ones. If this bit is set, we signal all, but not the
calling VCPU.
