.TH "vgic_its_restore_itt" 9 "vgic_its_restore_itt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vgic_its_restore_itt \- restore the ITT of a device
.SH SYNOPSIS
.B "int" vgic_its_restore_itt
.BI "(struct vgic_its *its "  ","
.BI "struct its_device *dev "  ");"
.SH ARGUMENTS
.IP "its" 12
its handle
.IP "dev" 12
device handle
.SH "DESCRIPTION"
Return 0 on success, < 0 on error
