.TH "vgic_its_save_device_tables" 9 "vgic_its_save_device_tables" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vgic_its_save_device_tables \- Save the device table and all ITT into guest RAM
.SH SYNOPSIS
.B "int" vgic_its_save_device_tables
.BI "(struct vgic_its *its "  ");"
.SH ARGUMENTS
.IP "its" 12
-- undescribed --
.SH "DESCRIPTION"

L1/L2 handling is hidden by \fBvgic_its_check_id\fP helper which directly
returns the GPA of the device entry
