.TH "via_mode_filter" 9 "via_mode_filter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
via_mode_filter \- filter buggy device/mode pairs
.SH SYNOPSIS
.B "unsigned long" via_mode_filter
.BI "(struct ata_device *dev "  ","
.BI "unsigned long mask "  ");"
.SH ARGUMENTS
.IP "dev" 12
ATA device
.IP "mask" 12
Mode bitmask

We need to apply some minimal filtering for old controllers and at least
one breed of Transcend SSD. Return the updated mask.
