.TH "vic_init2" 9 "vic_init2" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vic_init2 \- common initialisation code
.SH SYNOPSIS
.B "void" vic_init2
.BI "(void __iomem *base "  ");"
.SH ARGUMENTS
.IP "base" 12
Base of the VIC.
.SH "DESCRIPTION"
Common initialisation code for registration
and resume.
