.TH "vidioc_g_fmt_vid_cap" 9 "vidioc_g_fmt_vid_cap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vidioc_g_fmt_vid_cap \- get current video format parameters
.SH SYNOPSIS
.B "int" vidioc_g_fmt_vid_cap
.BI "(struct file *file "  ","
.BI "void *priv "  ","
.BI "struct v4l2_format *f "  ");"
.SH ARGUMENTS
.IP "file" 12
descriptor of device
.IP "priv" 12
unused
.IP "f" 12
contains format information
.SH "DESCRIPTION"
returns current video format parameters

return value: 0, always successful
