.TH "vimc_streamer_pipeline_terminate" 9 "vimc_streamer_pipeline_terminate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vimc_streamer_pipeline_terminate \- Disable stream in all ved in stream
.SH SYNOPSIS
.B "void" vimc_streamer_pipeline_terminate
.BI "(struct vimc_stream *stream "  ");"
.SH ARGUMENTS
.IP "stream" 12
the pointer to the stream structure with the pipeline to be
disabled.
.SH "DESCRIPTION"
Calls s_stream to disable the stream in each entity of the pipeline
