.TH "vio_register_device_node" 9 "vio_register_device_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vio_register_device_node \- - Register a new vio device.
.SH SYNOPSIS
.B "struct vio_dev *" vio_register_device_node
.BI "(struct device_node *of_node "  ");"
.SH ARGUMENTS
.IP "of_node" 12
The OF node for this device.
.SH "DESCRIPTION"
Creates and initializes a vio_dev structure from the data in
of_node and adds it to the list of virtual devices.
Returns a pointer to the created vio_dev or NULL if node has
NULL device_type or compatible fields.
