.TH "virtqueue_poll" 9 "virtqueue_poll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
virtqueue_poll \- query pending used buffers
.SH SYNOPSIS
.B "bool" virtqueue_poll
.BI "(struct virtqueue *_vq "  ","
.BI "unsigned last_used_idx "  ");"
.SH ARGUMENTS
.IP "_vq" 12
the struct virtqueue we're talking about.
.IP "last_used_idx" 12
virtqueue state (from call to virtqueue_enable_cb_prepare).
.SH "DESCRIPTION"
Returns "true" if there are pending used buffers in the queue.

This does not need to be serialized.
