.TH "vmballoon_add_page" 9 "vmballoon_add_page" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmballoon_add_page \- adds a page towards lock/unlock operation.
.SH SYNOPSIS
.B "void" vmballoon_add_page
.BI "(struct vmballoon *b "  ","
.BI "unsigned int idx "  ","
.BI "struct page *p "  ");"
.SH ARGUMENTS
.IP "b" 12
pointer to the balloon.
.IP "idx" 12
index of the page to be ballooned in this batch.
.IP "p" 12
pointer to the page that is about to be ballooned.
.SH "DESCRIPTION"
Adds the page to be ballooned. Must be called while holding \fIcomm_lock\fP.
