.TH "vme_slot_num" 9 "vme_slot_num" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vme_slot_num \- Retrieve slot ID
.SH SYNOPSIS
.B "int" vme_slot_num
.BI "(struct vme_dev *vdev "  ");"
.SH ARGUMENTS
.IP "vdev" 12
Pointer to VME device struct vme_dev assigned to driver instance.
.SH "DESCRIPTION"
Retrieve the slot ID associated with the provided VME device.
.SH "RETURN"
The slot ID on success, -EINVAL if VME bridge cannot be determined
or the function is not supported. Hardware specific errors may also
be returned.
