.TH "vme_get_size" 9 "vme_get_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vme_get_size \- Helper function returning size of a VME window
.SH SYNOPSIS
.B "size_t" vme_get_size
.BI "(struct vme_resource *resource "  ");"
.SH ARGUMENTS
.IP "resource" 12
Pointer to VME slave or master resource.
.SH "DESCRIPTION"
Determine the size of the VME window provided. This is a helper
function, wrappering the call to vme_master_get or vme_slave_get
depending on the type of window resource handed to it.
.SH "RETURN"
Size of the window on success, zero on failure.
