.TH "vmmouse_enable" 9 "vmmouse_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmmouse_enable \- Enable vmmouse and request absolute mode.
.SH SYNOPSIS
.B "int" vmmouse_enable
.BI "(struct psmouse *psmouse "  ");"
.SH ARGUMENTS
.IP "psmouse" 12
Pointer to the psmouse struct
.SH "DESCRIPTION"
Tries to enable vmmouse mode. Performs basic checks and requests
absolute vmmouse mode.
Returns 0 on success, -ENODEV on failure.
