.TH "vmmouse_disconnect" 9 "vmmouse_disconnect" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmmouse_disconnect \- Take down vmmouse driver
.SH SYNOPSIS
.B "void" vmmouse_disconnect
.BI "(struct psmouse *psmouse "  ");"
.SH ARGUMENTS
.IP "psmouse" 12
Pointer to the psmouse struct
.SH "DESCRIPTION"
Takes down vmmouse driver and frees resources set up in \fBvmmouse_init\fP.
