.TH "vmpressure_cleanup" 9 "vmpressure_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmpressure_cleanup \- shuts down vmpressure control structure
.SH SYNOPSIS
.B "void" vmpressure_cleanup
.BI "(struct vmpressure *vmpr "  ");"
.SH ARGUMENTS
.IP "vmpr" 12
Structure to be cleaned up
.SH "DESCRIPTION"
This function should be called before the structure in which it is
embedded is cleaned up.
