.TH "vmw_view_destroy" 9 "vmw_view_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_view_destroy \- Destroy a hardware view.
.SH SYNOPSIS
.B "int" vmw_view_destroy
.BI "(struct vmw_resource *res "  ");"
.SH ARGUMENTS
.IP "res" 12
Pointer to the view resource.
.SH "DESCRIPTION"
Destroy a hardware view. Typically used on unexpected termination of the
owning process or if the surface the view is pointing to is destroyed.
