.TH "vmw_resource_mob_detach" 9 "vmw_resource_mob_detach" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_resource_mob_detach \- Mark a resource as detached from its backing mob
.SH SYNOPSIS
.B "void" vmw_resource_mob_detach
.BI "(struct vmw_resource *res "  ");"
.SH ARGUMENTS
.IP "res" 12
The resource
