.TH "vmw_cmdbuf_header_inline_free" 9 "vmw_cmdbuf_header_inline_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_cmdbuf_header_inline_free \- Free a struct vmw_cmdbuf_header that has been used for the device context with inline command buffers. Need not be called locked.
.SH SYNOPSIS
.B "void" vmw_cmdbuf_header_inline_free
.BI "(struct vmw_cmdbuf_header *header "  ");"
.SH ARGUMENTS
.IP "header" 12
Pointer to the header to free.
