.TH "vmw_validation_add_bo" 9 "vmw_validation_add_bo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_validation_add_bo \- Add a buffer object to the validation context.
.SH SYNOPSIS
.B "int" vmw_validation_add_bo
.BI "(struct vmw_validation_context *ctx "  ","
.BI "struct vmw_buffer_object *vbo "  ","
.BI "bool as_mob "  ","
.BI "bool cpu_blit "  ");"
.SH ARGUMENTS
.IP "ctx" 12
The validation context.
.IP "vbo" 12
The buffer object.
.IP "as_mob" 12
Validate as mob, otherwise suitable for GMR operations.
.IP "cpu_blit" 12
Validate in a page-mappable location.
.SH "RETURN"
Zero on success, negative error code otherwise.
