.TH "vmw_execbuf_unpin_panic" 9 "vmw_execbuf_unpin_panic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_execbuf_unpin_panic \- Idle the fifo and unpin the query buffer.
.SH SYNOPSIS
.B "void" vmw_execbuf_unpin_panic
.BI "(struct vmw_private *dev_priv "  ");"
.SH ARGUMENTS
.IP "dev_priv" 12
The device private structure.
.SH "DESCRIPTION"
This function is called to idle the fifo and unpin the query buffer if the
normal way to do this hits an error, which should typically be extremely
rare.
