.TH "vmw_ldu_crtc_mode_set_nofb" 9 "vmw_ldu_crtc_mode_set_nofb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_ldu_crtc_mode_set_nofb \- Enable svga
.SH SYNOPSIS
.B "void" vmw_ldu_crtc_mode_set_nofb
.BI "(struct drm_crtc *crtc "  ");"
.SH ARGUMENTS
.IP "crtc" 12
CRTC associated with the new screen
.SH "DESCRIPTION"
For LDU, just enable the svga
