.TH "vmw_user_surface_free" 9 "vmw_user_surface_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_user_surface_free \- User visible surface resource destructor
.SH SYNOPSIS
.B "void" vmw_user_surface_free
.BI "(struct vmw_resource *res "  ");"
.SH ARGUMENTS
.IP "res" 12
A struct vmw_resource embedded in a struct vmw_surface.
