.TH "vmw_sou_crtc_helper_prepare" 9 "vmw_sou_crtc_helper_prepare" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_sou_crtc_helper_prepare \- Noop
.SH SYNOPSIS
.B "void" vmw_sou_crtc_helper_prepare
.BI "(struct drm_crtc *crtc "  ");"
.SH ARGUMENTS
.IP "crtc" 12
CRTC associated with the new screen
.SH "DESCRIPTION"
Prepares the CRTC for a mode set, but we don't need to do anything here.
