.TH "vmw_wait_dma_fence" 9 "vmw_wait_dma_fence" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_wait_dma_fence \- Wait for a dma fence
.SH SYNOPSIS
.B "int" vmw_wait_dma_fence
.BI "(struct vmw_fence_manager *fman "  ","
.BI "struct dma_fence *fence "  ");"
.SH ARGUMENTS
.IP "fman" 12
pointer to a fence manager
.IP "fence" 12
DMA fence to wait on
.SH "DESCRIPTION"
This function handles the case when the fence is actually a fence
array.  If that's the case, it'll wait on each of the child fence
