.TH "vmw_validation_mem_init_ttm" 9 "vmw_validation_mem_init_ttm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_validation_mem_init_ttm \- Interface the validation memory tracker to ttm.
.SH SYNOPSIS
.B "void" vmw_validation_mem_init_ttm
.BI "(struct vmw_private *dev_priv "  ","
.BI "size_t gran "  ");"
.SH ARGUMENTS
.IP "dev_priv" 12
Pointer to struct vmw_private. The reason we choose a vmw private
rather than a struct vmw_validation_mem is to make sure assumption in the
callbacks that struct vmw_private derives from struct vmw_validation_mem
holds true.
.IP "gran" 12
The recommended allocation granularity
