.TH "vmw_bo_cpu_blit_line" 9 "vmw_bo_cpu_blit_line" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_bo_cpu_blit_line \- Blit part of a line from one bo to another.
.SH SYNOPSIS
.B "int" vmw_bo_cpu_blit_line
.BI "(struct vmw_bo_blit_line_data *d "  ","
.BI "u32 dst_offset "  ","
.BI "u32 src_offset "  ","
.BI "u32 bytes_to_copy "  ");"
.SH ARGUMENTS
.IP "d" 12
Blit data as described above.
.IP "dst_offset" 12
Destination copy start offset from start of bo.
.IP "src_offset" 12
Source copy start offset from start of bo.
.IP "bytes_to_copy" 12
Number of bytes to copy in this line.
