.TH "vmw_du_connector_destroy_state" 9 "vmw_du_connector_destroy_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_du_connector_destroy_state \- destroy connector state
.SH SYNOPSIS
.B "void" vmw_du_connector_destroy_state
.BI "(struct drm_connector *connector "  ","
.BI "struct drm_connector_state *state "  ");"
.SH ARGUMENTS
.IP "connector" 12
DRM connector
.IP "state" 12
state object to destroy
.SH "DESCRIPTION"
Destroys the connector state (both common and vmw-specific) for the
specified plane.
