.TH "vpbe_deinitialize" 9 "vpbe_deinitialize" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vpbe_deinitialize \- de-initialize the vpbe display controller
.SH SYNOPSIS
.B "void" vpbe_deinitialize
.BI "(struct device *dev "  ","
.BI "struct vpbe_device *vpbe_dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Master and slave device ptr
.IP "vpbe_dev" 12
vpbe device ptr
.SH "DESCRIPTION"
vpbe_master and slave frame buffer devices calls this to de-initialize
the display controller. It is called when master and slave device
driver modules are removed and no longer requires the display controller.
