.TH "vringh_complete_kern" 9 "vringh_complete_kern" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vringh_complete_kern \- we've finished with descriptor, publish it.
.SH SYNOPSIS
.B "int" vringh_complete_kern
.BI "(struct vringh *vrh "  ","
.BI "u16 head "  ","
.BI "u32 len "  ");"
.SH ARGUMENTS
.IP "vrh" 12
the vring.
.IP "head" 12
the head as filled in by vringh_getdesc_kern.
.IP "len" 12
the length of data we have written.
.SH "DESCRIPTION"
You should check \fBvringh_need_notify_kern\fP after one or more calls
to this function.
