.TH "vsp1_dl_body_write" 9 "vsp1_dl_body_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vsp1_dl_body_write \- Write a register to a display list body
.SH SYNOPSIS
.B "void" vsp1_dl_body_write
.BI "(struct vsp1_dl_body *dlb "  ","
.BI "u32 reg "  ","
.BI "u32 data "  ");"
.SH ARGUMENTS
.IP "dlb" 12
The body
.IP "reg" 12
The register address
.IP "data" 12
The register value
.SH "DESCRIPTION"
Write the given register and value to the display list body. The maximum
number of entries that can be written in a body is specified when the body is
allocated by \fBvsp1_dl_body_alloc\fP.
