.TH "vsp1_entity_get_pad_format" 9 "vsp1_entity_get_pad_format" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vsp1_entity_get_pad_format \- Get a pad format from storage for an entity
.SH SYNOPSIS
.B "struct v4l2_mbus_framefmt *" vsp1_entity_get_pad_format
.BI "(struct vsp1_entity *entity "  ","
.BI "struct v4l2_subdev_pad_config *cfg "  ","
.BI "unsigned int pad "  ");"
.SH ARGUMENTS
.IP "entity" 12
the entity
.IP "cfg" 12
the configuration storage
.IP "pad" 12
the pad number
.SH "DESCRIPTION"
Return the format stored in the given configuration for an entity's pad. The
configuration can be an ACTIVE or TRY configuration.
