.TH "vxfs_lookup" 9 "vxfs_lookup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxfs_lookup \- lookup pathname component
.SH SYNOPSIS
.B "struct dentry *" vxfs_lookup
.BI "(struct inode *dip "  ","
.BI "struct dentry *dp "  ","
.BI "unsigned int flags "  ");"
.SH ARGUMENTS
.IP "dip" 12
dir in which we lookup
.IP "dp" 12
dentry we lookup
.IP "flags" 12
lookup flags
.SH "DESCRIPTION"
vxfs_lookup tries to lookup the pathname component described
by \fIdp\fP in \fIdip\fP.
.SH "RETURN"
A NULL-pointer on success, else a negative error code encoded
in the return pointer.
