.TH "vxfs_stiget" 9 "vxfs_stiget" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxfs_stiget \- find inode using the structural inode list
.SH SYNOPSIS
.B "struct inode *" vxfs_stiget
.BI "(struct super_block *sbp "  ","
.BI "ino_t ino "  ");"
.SH ARGUMENTS
.IP "sbp" 12
VFS superblock
.IP "ino" 12
inode #
.SH "DESCRIPTION"
Find inode \fIino\fP in the filesystem described by \fIsbp\fP using
the structural inode list.
Returns the matching inode on success, else a NULL pointer.
