.TH "vxge_probe" 9 "vxge_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxge_probe \- 
.SH SYNOPSIS
.B "int" vxge_probe
.BI "(struct pci_dev *pdev "  ","
.BI "const struct pci_device_id *pre "  ");"
.SH ARGUMENTS
.IP "pdev" 12
structure containing the PCI related information of the device.
.IP "pre" 12
List of PCI devices supported by the driver listed in vxge_id_table.
.SH "DESCRIPTION"
This function is called when a new PCI device gets detected and initializes
it.
Return value:
returns 0 on success and negative on failure.
