.TH "vxge_open" 9 "vxge_open" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxge_open \- 
.SH SYNOPSIS
.B "int" vxge_open
.BI "(struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to the device structure.
.SH "DESCRIPTION"
This function is the open entry point of the driver. It mainly calls a
function to allocate Rx buffers and inserts them into the buffer
descriptors and then enables the Rx part of the NIC.
Return value: '0' on success and an appropriate (-)ve integer as
defined in errno.h file on failure.
