.TH "vxge_ethtool_idnic" 9 "vxge_ethtool_idnic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxge_ethtool_idnic \- To physically identify the nic on the system.
.SH SYNOPSIS
.B "int" vxge_ethtool_idnic
.BI "(struct net_device *dev "  ","
.BI "enum ethtool_phys_id_state state "  ");"
.SH ARGUMENTS
.IP "dev" 12
device pointer.
.IP "state" 12
requested LED state
.SH "DESCRIPTION"
Used to physically identify the NIC on the system.
0 on success
