.TH "vxge_hw_channel_msix_mask" 9 "vxge_hw_channel_msix_mask" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxge_hw_channel_msix_mask \- Mask MSIX Vector.
.SH SYNOPSIS
.B "void" vxge_hw_channel_msix_mask
.BI "(struct __vxge_hw_channel *channel "  ","
.BI "int msix_id "  ");"
.SH ARGUMENTS
.IP "channel" 12
Channel for rx or tx handle
.IP "msix_id" 12
MSIX ID
.SH "DESCRIPTION"
The function masks the msix interrupt for the given msix_id
.SH "RETURN"
0
