.TH "vxge_hw_vpath_mac_addr_add" 9 "vxge_hw_vpath_mac_addr_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxge_hw_vpath_mac_addr_add \- Add the mac address entry for this vpath to MAC address table.
.SH SYNOPSIS
.B "enum vxge_hw_status" vxge_hw_vpath_mac_addr_add
.BI "(struct __vxge_hw_vpath_handle *vp "  ","
.BI "u8 *macaddr "  ","
.BI "u8 *macaddr_mask "  ","
.BI "enum vxge_hw_vpath_mac_addr_add_mode duplicate_mode "  ");"
.SH ARGUMENTS
.IP "vp" 12
Vpath handle.
.IP "macaddr" 12
MAC address to be added for this vpath into the list
.IP "macaddr_mask" 12
MAC address mask for macaddr
.IP "duplicate_mode" 12
Duplicate MAC address add mode. Please see
enum vxge_hw_vpath_mac_addr_add_mode{}
.SH "DESCRIPTION"
Adds the given mac address and mac address mask into the list for this
vpath.
see also: vxge_hw_vpath_mac_addr_delete, vxge_hw_vpath_mac_addr_get and
vxge_hw_vpath_mac_addr_get_next
