.TH "vxge_hw_channel_msix_clear" 9 "vxge_hw_channel_msix_clear" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxge_hw_channel_msix_clear \- Unmask the MSIX Vector.
.SH SYNOPSIS
.B "void" vxge_hw_channel_msix_clear
.BI "(struct __vxge_hw_channel *channel "  ","
.BI "int msix_id "  ");"
.SH ARGUMENTS
.IP "channel" 12
Channel for rx or tx handle
.IP "msix_id" 12
MSI ID
.SH "DESCRIPTION"
The function unmasks the msix interrupt for the given msix_id
if configured in MSIX oneshot mode
.SH "RETURN"
0
