.TH "vxge_hw_vpath_promisc_enable" 9 "vxge_hw_vpath_promisc_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxge_hw_vpath_promisc_enable \- Enable promiscuous mode.
.SH SYNOPSIS
.B "enum vxge_hw_status" vxge_hw_vpath_promisc_enable
.BI "(struct __vxge_hw_vpath_handle *vp "  ");"
.SH ARGUMENTS
.IP "vp" 12
Vpath handle.
.SH "DESCRIPTION"
Enable promiscuous mode of Titan-e operation.

See also: \fBvxge_hw_vpath_promisc_disable\fP.
