.TH "wait_for_completion_io" 9 "wait_for_completion_io" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wait_for_completion_io \- - waits for completion of a task
.SH SYNOPSIS
.B "void" wait_for_completion_io
.BI "(struct completion *x "  ");"
.SH ARGUMENTS
.IP "x" 12
holds the state of this particular completion
.SH "DESCRIPTION"
This waits to be signaled for completion of a specific task. It is NOT
interruptible and there is no timeout. The caller is accounted as waiting
for IO (which traditionally means blkio only).
