.TH "wait_for_completion_interruptible" 9 "wait_for_completion_interruptible" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wait_for_completion_interruptible \- - waits for completion of a task (w/intr)
.SH SYNOPSIS
.B "int" wait_for_completion_interruptible
.BI "(struct completion *x "  ");"
.SH ARGUMENTS
.IP "x" 12
holds the state of this particular completion
.SH "DESCRIPTION"
This waits for completion of a specific task to be signaled. It is
interruptible.
.SH "RETURN"
-ERESTARTSYS if interrupted, 0 if completed.
