.TH "wb_over_bg_thresh" 9 "wb_over_bg_thresh" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wb_over_bg_thresh \- does @wb need to be written back?
.SH SYNOPSIS
.B "bool" wb_over_bg_thresh
.BI "(struct bdi_writeback *wb "  ");"
.SH ARGUMENTS
.IP "wb" 12
bdi_writeback of interest
.SH "DESCRIPTION"
Determines whether background writeback should keep writing \fIwb\fP or it's
clean enough.
.SH "RETURN"
true if writeback should continue.
