.TH "wkup_m3_set_resume_address" 9 "wkup_m3_set_resume_address" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wkup_m3_set_resume_address \- Pass wkup_m3 resume address
.SH SYNOPSIS
.B "void" wkup_m3_set_resume_address
.BI "(struct wkup_m3_ipc *m3_ipc "  ","
.BI "void *addr "  ");"
.SH ARGUMENTS
.IP "m3_ipc" 12
Pointer to wkup_m3_ipc context
.IP "addr" 12
Physical address from which resume code should execute
