.TH "wl1273_fm_set_tx_power" 9 "wl1273_fm_set_tx_power" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wl1273_fm_set_tx_power \- Set the transmission power value.
.SH SYNOPSIS
.B "int" wl1273_fm_set_tx_power
.BI "(struct wl1273_device *radio "  ","
.BI "u16 power "  ");"
.SH ARGUMENTS
.IP "radio" 12
A pointer to the device struct.
.IP "power" 12
The new power value.
