.TH "wq_worker_running" 9 "wq_worker_running" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wq_worker_running \- a worker is running again
.SH SYNOPSIS
.B "void" wq_worker_running
.BI "(struct task_struct *task "  ");"
.SH ARGUMENTS
.IP "task" 12
task waking up
.SH "DESCRIPTION"
This function is called when a worker returns from \fBschedule\fP
