.TH "xa_destroy" 9 "xa_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xa_destroy \- Free all internal data structures.
.SH SYNOPSIS
.B "void" xa_destroy
.BI "(struct xarray *xa "  ");"
.SH ARGUMENTS
.IP "xa" 12
XArray.
.SH "DESCRIPTION"
After calling this function, the XArray is empty and has freed all memory
allocated for its internal data structures.  You are responsible for
freeing the objects referenced by the XArray.
.SH "CONTEXT"
Any context.  Takes and releases the xa_lock, interrupt-safe.
