.TH "xa_find" 9 "xa_find" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xa_find \- Search the XArray for an entry.
.SH SYNOPSIS
.B "void *" xa_find
.BI "(struct xarray *xa "  ","
.BI "unsigned long *indexp "  ","
.BI "unsigned long max "  ","
.BI "xa_mark_t filter "  ");"
.SH ARGUMENTS
.IP "xa" 12
XArray.
.IP "indexp" 12
Pointer to an index.
.IP "max" 12
Maximum index to search to.
.IP "filter" 12
Selection criterion.
.SH "DESCRIPTION"
Finds the entry in \fIxa\fP which matches the \fIfilter\fP, and has the lowest
index that is at least \fIindexp\fP and no more than \fImax\fP.
If an entry is found, \fIindexp\fP is updated to be the index of the entry.
This function is protected by the RCU read lock, so it may not find
entries which are being simultaneously added.  It will not return an
XA_RETRY_ENTRY; if you need to see retry entries, use \fBxas_find\fP.
.SH "CONTEXT"
Any context.  Takes and releases the RCU lock.
.SH "RETURN"
The entry, if found, otherwise NULL.
