.TH "xcsi2rxss_log_status" 9 "xcsi2rxss_log_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xcsi2rxss_log_status \- Logs the status of the CSI-2 Receiver
.SH SYNOPSIS
.B "int" xcsi2rxss_log_status
.BI "(struct v4l2_subdev *sd "  ");"
.SH ARGUMENTS
.IP "sd" 12
Pointer to V4L2 subdevice structure
.SH "DESCRIPTION"
This function prints the current status of Xilinx MIPI CSI-2
.SH "RETURN"
0 on success
