.TH "xdr_shrink_pagelen" 9 "xdr_shrink_pagelen" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xdr_shrink_pagelen \- shrinks buf->pages to @len bytes
.SH SYNOPSIS
.B "unsigned int" xdr_shrink_pagelen
.BI "(struct xdr_buf *buf "  ","
.BI "unsigned int len "  ");"
.SH ARGUMENTS
.IP "buf" 12
xdr_buf
.IP "len" 12
new page buffer length
.SH "DESCRIPTION"
The extra data is not lost, but is instead moved into buf->tail.
Returns the actual number of bytes moved.
