.TH "xenbus_read_driver_state" 9 "xenbus_read_driver_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xenbus_read_driver_state \- 
.SH SYNOPSIS
.B "enum xenbus_state" xenbus_read_driver_state
.BI "(const char *path "  ");"
.SH ARGUMENTS
.IP "path" 12
path for driver
.SH "DESCRIPTION"
Return the state of the driver rooted at the given store path, or
XenbusStateUnknown if no state can be read.
