.TH "xgene_chan_xfer_ld_pending" 9 "xgene_chan_xfer_ld_pending" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xgene_chan_xfer_ld_pending \- push any pending transactions to hw
.SH SYNOPSIS
.B "void" xgene_chan_xfer_ld_pending
.BI "(struct xgene_dma_chan *chan "  ");"
.SH ARGUMENTS
.IP "chan" 12
X-Gene DMA channel
.SH "DESCRIPTION"
LOCKING: must hold chan->lock
