.TH "xgene_dma_cleanup_descriptors" 9 "xgene_dma_cleanup_descriptors" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xgene_dma_cleanup_descriptors \- cleanup link descriptors which are completed and move them to ld_completed to free until flag 'ack' is set
.SH SYNOPSIS
.B "void" xgene_dma_cleanup_descriptors
.BI "(struct xgene_dma_chan *chan "  ");"
.SH ARGUMENTS
.IP "chan" 12
X-Gene DMA channel
.SH "DESCRIPTION"
This function is used on descriptors which have been executed by the DMA
controller. It will run any callbacks, submit any dependencies, then
free these descriptors if flag 'ack' is set.
