.TH "xgmac_change_mtu" 9 "xgmac_change_mtu" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xgmac_change_mtu \- entry point to change MTU size for the device.
.SH SYNOPSIS
.B "int" xgmac_change_mtu
.BI "(struct net_device *dev "  ","
.BI "int new_mtu "  ");"
.SH ARGUMENTS
.IP "dev" 12
device pointer.
.IP "new_mtu" 12
the new MTU size for the device.
.SH "DESCRIPTION"
the Maximum Transfer Unit (MTU) is used by the network layer
to drive packet transmission. Ethernet has an MTU of 1500 octets
(ETH_DATA_LEN). This value can be changed with ifconfig.
Return value:
0 on success and an appropriate (-)ve integer as defined in errno.h
file on failure.
