.TH "xgmac_tx_timeout" 9 "xgmac_tx_timeout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xgmac_tx_timeout \- 
.SH SYNOPSIS
.B "void" xgmac_tx_timeout
.BI "(struct net_device *dev "  ","
.BI "unsigned int txqueue "  ");"
.SH ARGUMENTS
.IP "dev" 12
Pointer to net device structure
.IP "txqueue" 12
index of the hung transmit queue
.SH "DESCRIPTION"
this function is called when a packet transmission fails to
complete within a reasonable tmrate. The driver will mark the error in the
netdev structure and arrange for the device to be reset to a sane state
in order to transmit a new packet.
