.TH "xgpio_set_multiple" 9 "xgpio_set_multiple" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xgpio_set_multiple \- Write the specified signals of the GPIO device.
.SH SYNOPSIS
.B "void" xgpio_set_multiple
.BI "(struct gpio_chip *gc "  ","
.BI "unsigned long *mask "  ","
.BI "unsigned long *bits "  ");"
.SH ARGUMENTS
.IP "gc" 12
Pointer to gpio_chip device structure.
.IP "mask" 12
Mask of the GPIOS to modify.
.IP "bits" 12
Value to be wrote on each GPIO
.SH "DESCRIPTION"
This function writes the specified values into the specified signals of the
GPIO devices.
