.TH "xilinx_dpdma_chan_pause" 9 "xilinx_dpdma_chan_pause" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xilinx_dpdma_chan_pause \- Pause the channel
.SH SYNOPSIS
.B "void" xilinx_dpdma_chan_pause
.BI "(struct xilinx_dpdma_chan *chan "  ");"
.SH ARGUMENTS
.IP "chan" 12
DPDMA channel
.SH "DESCRIPTION"
Pause the channel.
