.TH "xilinx_dma_chan_remove" 9 "xilinx_dma_chan_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xilinx_dma_chan_remove \- Per Channel remove function
.SH SYNOPSIS
.B "void" xilinx_dma_chan_remove
.BI "(struct xilinx_dma_chan *chan "  ");"
.SH ARGUMENTS
.IP "chan" 12
Driver specific DMA channel
