.TH "xilinx_dpdma_chan_err" 9 "xilinx_dpdma_chan_err" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xilinx_dpdma_chan_err \- Detect any channel error
.SH SYNOPSIS
.B "bool" xilinx_dpdma_chan_err
.BI "(struct xilinx_dpdma_chan *chan "  ","
.BI "u32 isr "  ","
.BI "u32 eisr "  ");"
.SH ARGUMENTS
.IP "chan" 12
DPDMA channel
.IP "isr" 12
masked Interrupt Status Register
.IP "eisr" 12
Error Interrupt Status Register
.SH "RETURN"
true if any channel error occurs, or false otherwise.
