.TH "xilinx_dma_remove" 9 "xilinx_dma_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xilinx_dma_remove \- Driver remove function
.SH SYNOPSIS
.B "int" xilinx_dma_remove
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
Pointer to the platform_device structure
.SH "RETURN"
Always '0'
