.TH "xprt_lookup_rqst" 9 "xprt_lookup_rqst" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_lookup_rqst \- find an RPC request corresponding to an XID
.SH SYNOPSIS
.B "struct rpc_rqst *" xprt_lookup_rqst
.BI "(struct rpc_xprt *xprt "  ","
.BI "__be32 xid "  ");"
.SH ARGUMENTS
.IP "xprt" 12
transport on which the original request was transmitted
.IP "xid" 12
RPC XID of incoming reply
.SH "DESCRIPTION"
Caller holds xprt->queue_lock.
