.TH "xprt_prepare_transmit" 9 "xprt_prepare_transmit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_prepare_transmit \- reserve the transport before sending a request
.SH SYNOPSIS
.B "bool" xprt_prepare_transmit
.BI "(struct rpc_task *task "  ");"
.SH ARGUMENTS
.IP "task" 12
RPC task about to send a request
