.TH "xprt_rdma_connect" 9 "xprt_rdma_connect" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_rdma_connect \- schedule an attempt to reconnect
.SH SYNOPSIS
.B "void" xprt_rdma_connect
.BI "(struct rpc_xprt *xprt "  ","
.BI "struct rpc_task *task "  ");"
.SH ARGUMENTS
.IP "xprt" 12
transport state
.IP "task" 12
RPC scheduler context (unused)
