.TH "xprt_rdma_set_connect_timeout" 9 "xprt_rdma_set_connect_timeout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_rdma_set_connect_timeout \- set timeouts for establishing a connection
.SH SYNOPSIS
.B "void" xprt_rdma_set_connect_timeout
.BI "(struct rpc_xprt *xprt "  ","
.BI "unsigned long connect_timeout "  ","
.BI "unsigned long reconnect_timeout "  ");"
.SH ARGUMENTS
.IP "xprt" 12
controlling transport instance
.IP "connect_timeout" 12
reconnect timeout after client disconnects
.IP "reconnect_timeout" 12
reconnect timeout after server disconnects
