.TH "xprt_rdma_free_slot" 9 "xprt_rdma_free_slot" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_rdma_free_slot \- release an rpc_rqst
.SH SYNOPSIS
.B "void" xprt_rdma_free_slot
.BI "(struct rpc_xprt *xprt "  ","
.BI "struct rpc_rqst *rqst "  ");"
.SH ARGUMENTS
.IP "xprt" 12
controlling RPC transport
.IP "rqst" 12
rpc_rqst to release
