.TH "xprt_switch_put" 9 "xprt_switch_put" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_switch_put \- Release a reference to a rpc_xprt_switch
.SH SYNOPSIS
.B "void" xprt_switch_put
.BI "(struct rpc_xprt_switch *xps "  ");"
.SH ARGUMENTS
.IP "xps" 12
pointer to struct rpc_xprt_switch
.SH "DESCRIPTION"
Release the reference to xps, and free it once the refcount is zero.
