.TH "xudc_free_request" 9 "xudc_free_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xudc_free_request \- Releases the request from queue.
.SH SYNOPSIS
.B "void" xudc_free_request
.BI "(struct usb_ep *_ep "  ","
.BI "struct usb_request *_req "  ");"
.SH ARGUMENTS
.IP "_ep" 12
pointer to the usb device endpoint structure.
.IP "_req" 12
pointer to the usb request structure.
