.TH "xvcu_remove" 9 "xvcu_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xvcu_remove \- Insert gasket isolation and disable the clock
.SH SYNOPSIS
.B "int" xvcu_remove
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
Pointer to the platform_device structure
.SH "RETURN"
Returns 0 on success
Negative error code otherwise
