.TH "yama_task_prctl" 9 "yama_task_prctl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
yama_task_prctl \- check for Yama-specific prctl operations
.SH SYNOPSIS
.B "int" yama_task_prctl
.BI "(int option "  ","
.BI "unsigned long arg2 "  ","
.BI "unsigned long arg3 "  ","
.BI "unsigned long arg4 "  ","
.BI "unsigned long arg5 "  ");"
.SH ARGUMENTS
.IP "option" 12
operation
.IP "arg2" 12
argument
.IP "arg3" 12
argument
.IP "arg4" 12
argument
.IP "arg5" 12
argument
.SH "DESCRIPTION"
Return 0 on success, -ve on error.  -ENOSYS is returned when Yama
does not handle the given option.
