.TH "z8530_sync_dma_close" 9 "z8530_sync_dma_close" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
z8530_sync_dma_close \- Close down DMA I/O
.SH SYNOPSIS
.B "int" z8530_sync_dma_close
.BI "(struct net_device *dev "  ","
.BI "struct z8530_channel *c "  ");"
.SH ARGUMENTS
.IP "dev" 12
Network device to detach
.IP "c" 12
Z8530 channel to move into discard mode

Shut down a DMA mode synchronous interface. Halt the DMA, and
free the buffers.
