.TH "z8530_tx" 9 "z8530_tx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
z8530_tx \- Handle a PIO transmit event
.SH SYNOPSIS
.B "void" z8530_tx
.BI "(struct z8530_channel *c "  ");"
.SH ARGUMENTS
.IP "c" 12
Z8530 channel to process

Z8530 transmit interrupt handler for the PIO mode. The basic
idea is to attempt to keep the FIFO fed. We fill as many bytes
in as possible, its quite possible that we won't keep up with the
data rate otherwise.
