.TH "z_comp_stats" 9 "z_comp_stats" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
z_comp_stats \- return compression statistics for a compressor or decompressor.
.SH SYNOPSIS
.B "void" z_comp_stats
.BI "(void *arg "  ","
.BI "struct compstat *stats "  ");"
.SH ARGUMENTS
.IP "arg" 12
pointer to private space for the (de)compressor
.IP "stats" 12
pointer to a struct compstat to receive the result.
