.TH "z_incomp" 9 "z_incomp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
z_incomp \- add incompressible input data to the history.
.SH SYNOPSIS
.B "void" z_incomp
.BI "(void *arg "  ","
.BI "unsigned char *ibuf "  ","
.BI "int icnt "  ");"
.SH ARGUMENTS
.IP "arg" 12
pointer to private state for the decompressor
.IP "ibuf" 12
pointer to input packet data
.IP "icnt" 12
length of input data.
