.TH "zbud_create_pool" 9 "zbud_create_pool" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zbud_create_pool \- create a new zbud pool
.SH SYNOPSIS
.B "struct zbud_pool *" zbud_create_pool
.BI "(gfp_t gfp "  ","
.BI "const struct zbud_ops *ops "  ");"
.SH ARGUMENTS
.IP "gfp" 12
gfp flags when allocating the zbud pool structure
.IP "ops" 12
user-defined operations for the zbud pool
.SH "RETURN"
pointer to the new zbud pool or NULL if the metadata allocation
failed.
