.TH "zcrypt_queue_register" 9 "zcrypt_queue_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zcrypt_queue_register \- Register a crypto queue device.
.SH SYNOPSIS
.B "int" zcrypt_queue_register
.BI "(struct zcrypt_queue *zq "  ");"
.SH ARGUMENTS
.IP "zq" 12
Pointer to a crypto queue device
.SH "DESCRIPTION"
Register a crypto queue device. Returns 0 if successful.
