.TH "zfcp_erp_set_adapter_status" 9 "zfcp_erp_set_adapter_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_erp_set_adapter_status \- set adapter status bits
.SH SYNOPSIS
.B "void" zfcp_erp_set_adapter_status
.BI "(struct zfcp_adapter *adapter "  ","
.BI "u32 mask "  ");"
.SH ARGUMENTS
.IP "adapter" 12
adapter to change the status
.IP "mask" 12
status bits to change
.SH "DESCRIPTION"
Changes in common status bits are propagated to attached ports and LUNs.
