.TH "zfcp_fc_post_event" 9 "zfcp_fc_post_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_fc_post_event \- post event to userspace via fc_transport
.SH SYNOPSIS
.B "void" zfcp_fc_post_event
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
work struct with enqueued events
