.TH "zfcp_erp_lun_reopen" 9 "zfcp_erp_lun_reopen" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_erp_lun_reopen \- initiate reopen of a LUN
.SH SYNOPSIS
.B "void" zfcp_erp_lun_reopen
.BI "(struct scsi_device *sdev "  ","
.BI "int clear "  ","
.BI "char *dbftag "  ");"
.SH ARGUMENTS
.IP "sdev" 12
SCSI device / LUN to be reopened
.IP "clear" 12
specifies flags in LUN status to be cleared
.IP "dbftag" 12
Tag for debug trace event.
.SH "RETURN"
0 on success, < 0 on error
