.TH "zfcp_dbf_rec_run_lvl" 9 "zfcp_dbf_rec_run_lvl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_dbf_rec_run_lvl \- trace event related to running recovery
.SH SYNOPSIS
.B "void" zfcp_dbf_rec_run_lvl
.BI "(int level "  ","
.BI "char *tag "  ","
.BI "struct zfcp_erp_action *erp "  ");"
.SH ARGUMENTS
.IP "level" 12
trace level to be used for event
.IP "tag" 12
identifier for event
.IP "erp" 12
erp_action running
