.TH "zpool_get_type" 9 "zpool_get_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zpool_get_type \- Get the type of the zpool
.SH SYNOPSIS
.B "const char *" zpool_get_type
.BI "(struct zpool *zpool "  ");"
.SH ARGUMENTS
.IP "zpool" 12
The zpool to check
.SH "DESCRIPTION"
This returns the type of the pool.

Implementations must guarantee this to be thread-safe.
.SH "RETURN"
The type of zpool.
