.TH "zynqmp_disp_get_crtc_mask" 9 "zynqmp_disp_get_crtc_mask" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_disp_get_crtc_mask \- Return the CRTC bit mask
.SH SYNOPSIS
.B "uint32_t" zynqmp_disp_get_crtc_mask
.BI "(struct zynqmp_disp *disp "  ");"
.SH ARGUMENTS
.IP "disp" 12
Display controller
.SH "RETURN"
the crtc mask of the zyqnmp_disp CRTC.
