.TH "zynqmp_get_clock_type" 9 "zynqmp_get_clock_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_get_clock_type \- Get type of clock
.SH SYNOPSIS
.B "int" zynqmp_get_clock_type
.BI "(u32 clk_id "  ","
.BI "u32 *type "  ");"
.SH ARGUMENTS
.IP "clk_id" 12
Clock index
.IP "type" 12
Clock type: CLK_TYPE_OUTPUT or CLK_TYPE_EXTERNAL
.SH "RETURN"
0 on success else error code
