.TH "zynqmp_pm_release_node" 9 "zynqmp_pm_release_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_pm_release_node \- Release a node
.SH SYNOPSIS
.B "int" zynqmp_pm_release_node
.BI "(const u32 node "  ");"
.SH ARGUMENTS
.IP "node" 12
Node ID of the slave
.SH "DESCRIPTION"
This function is used by master to inform firmware that master
has released node. Once released, master must not use that node
without re-request.
.SH "RETURN"
Returns status, either success or error+reason
