.TH "zynqmp_disp_blend_set_bg_color" 9 "zynqmp_disp_blend_set_bg_color" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_disp_blend_set_bg_color \- Set the background color
.SH SYNOPSIS
.B "void" zynqmp_disp_blend_set_bg_color
.BI "(struct zynqmp_disp_blend *blend "  ","
.BI "u32 rcr "  ","
.BI "u32 gy "  ","
.BI "u32 bcb "  ");"
.SH ARGUMENTS
.IP "blend" 12
Blender object
.IP "rcr" 12
Red/Cr color component
.IP "gy" 12
Green/Y color component
.IP "bcb" 12
Blue/Cb color component
.SH "DESCRIPTION"
Set the background color to (\fIrcr\fP, \fIgy\fP, \fIbcb\fP), corresponding to the R, G and
B or Cr, Y and Cb components respectively depending on the selected output
format.
