.TH "zynqmp_dma_issue_pending" 9 "zynqmp_dma_issue_pending" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_dma_issue_pending \- Issue pending transactions
.SH SYNOPSIS
.B "void" zynqmp_dma_issue_pending
.BI "(struct dma_chan *dchan "  ");"
.SH ARGUMENTS
.IP "dchan" 12
DMA channel pointer
