.TH "zynqmp_qspi_copy_read_data" 9 "zynqmp_qspi_copy_read_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_qspi_copy_read_data \- Copy data to RX buffer
.SH SYNOPSIS
.B "void" zynqmp_qspi_copy_read_data
.BI "(struct zynqmp_qspi *xqspi "  ","
.BI "ulong data "  ","
.BI "u8 size "  ");"
.SH ARGUMENTS
.IP "xqspi" 12
Pointer to the zynqmp_qspi structure
.IP "data" 12
The variable where data is stored
.IP "size" 12
Number of bytes to be copied from data to RX buffer
