.TH "zynqmp_pm_set_pll_frac_data" 9 "zynqmp_pm_set_pll_frac_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_pm_set_pll_frac_data \- PM API for setting pll fraction data
.SH SYNOPSIS
.B "int" zynqmp_pm_set_pll_frac_data
.BI "(u32 clk_id "  ","
.BI "u32 data "  ");"
.SH ARGUMENTS
.IP "clk_id" 12
PLL clock ID
.IP "data" 12
fraction data
.SH "DESCRIPTION"
This function sets fraction data.
It is valid for fraction mode only.
.SH "RETURN"
Returns status, either success or error+reason
