.TH "zynqmp_disp_avbuf_disable_video" 9 "zynqmp_disp_avbuf_disable_video" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_disp_avbuf_disable_video \- Disable a video layer
.SH SYNOPSIS
.B "void" zynqmp_disp_avbuf_disable_video
.BI "(struct zynqmp_disp_avbuf *avbuf "  ","
.BI "enum zynqmp_disp_layer_id layer "  ");"
.SH ARGUMENTS
.IP "avbuf" 12
Audio/video buffer manager
.IP "layer" 12
The layer ID
.SH "DESCRIPTION"
Disable the video/graphics buffer for \fIlayer\fP.
