.TH "zynqmp_dma_free_descriptors" 9 "zynqmp_dma_free_descriptors" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_dma_free_descriptors \- Free channel descriptors
.SH SYNOPSIS
.B "void" zynqmp_dma_free_descriptors
.BI "(struct zynqmp_dma_chan *chan "  ");"
.SH ARGUMENTS
.IP "chan" 12
ZynqMP DMA channel pointer
