.TH "zynqmp_disp_layer_request_dma" 9 "zynqmp_disp_layer_request_dma" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_disp_layer_request_dma \- Request DMA channels for a layer
.SH SYNOPSIS
.B "int" zynqmp_disp_layer_request_dma
.BI "(struct zynqmp_disp *disp "  ","
.BI "struct zynqmp_disp_layer *layer "  ");"
.SH ARGUMENTS
.IP "disp" 12
Display controller
.IP "layer" 12
The layer
.SH "DESCRIPTION"
Request all DMA engine channels needed by \fIlayer\fP.
.SH "RETURN"
0 on success, or the DMA channel request error otherwise
