.TH "zynqmp_dma_free_descriptor" 9 "zynqmp_dma_free_descriptor" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_dma_free_descriptor \- Issue pending transactions
.SH SYNOPSIS
.B "void" zynqmp_dma_free_descriptor
.BI "(struct zynqmp_dma_chan *chan "  ","
.BI "struct zynqmp_dma_desc_sw *sdesc "  ");"
.SH ARGUMENTS
.IP "chan" 12
ZynqMP DMA channel pointer
.IP "sdesc" 12
Transaction descriptor pointer
