.TH "__adis_reset" 9 "__adis_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__adis_reset \- Reset the device (unlocked version)
.SH SYNOPSIS
.B "int" __adis_reset
.BI "(struct adis *adis "  ");"
.SH ARGUMENTS
.IP "adis" 12
The adis device
.SH "DESCRIPTION"
Returns 0 on success, a negative error code otherwise
