.TH "__adis_update_bits_base" 9 "__adis_update_bits_base" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__adis_update_bits_base \- ADIS Update bits function - Unlocked version
.SH SYNOPSIS
.B "int" __adis_update_bits_base
.BI "(struct adis *adis "  ","
.BI "unsigned int reg "  ","
.BI "const u32 mask "  ","
.BI "const u32 val "  ","
.BI "u8 size "  ");"
.SH ARGUMENTS
.IP "adis" 12
The adis device
.IP "reg" 12
The address of the lower of the two registers
.IP "mask" 12
Bitmask to change
.IP "val" 12
Value to be written
.IP "size" 12
Size of the register to update
.SH "DESCRIPTION"
Updates the desired bits of \fIreg\fP in accordance with \fImask\fP and \fIval\fP.
