.TH "__alloc_reserved_percpu" 9 "__alloc_reserved_percpu" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__alloc_reserved_percpu \- allocate reserved percpu area
.SH SYNOPSIS
.B "void __percpu *" __alloc_reserved_percpu
.BI "(size_t size "  ","
.BI "size_t align "  ");"
.SH ARGUMENTS
.IP "size" 12
size of area to allocate in bytes
.IP "align" 12
alignment of area (max PAGE_SIZE)
.SH "DESCRIPTION"
Allocate zero-filled percpu area of \fIsize\fP bytes aligned at \fIalign\fP
from reserved percpu area if arch has set it up; otherwise,
allocation is served from the same dynamic area.  Might sleep.
Might trigger writeouts.
.SH "CONTEXT"
Does GFP_KERNEL allocation.
.SH "RETURN"
Percpu pointer to the allocated area on success, NULL on failure.
