.TH "__async_tx_find_channel" 9 "__async_tx_find_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__async_tx_find_channel \- find a channel to carry out the operation or let the transaction execute synchronously
.SH SYNOPSIS
.B "struct dma_chan *" __async_tx_find_channel
.BI "(struct async_submit_ctl *submit "  ","
.BI "enum dma_transaction_type tx_type "  ");"
.SH ARGUMENTS
.IP "submit" 12
transaction dependency and submission modifiers
.IP "tx_type" 12
transaction type
