.TH "__atapi_pio_bytes" 9 "__atapi_pio_bytes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__atapi_pio_bytes \- Transfer data from/to the ATAPI device.
.SH SYNOPSIS
.B "int" __atapi_pio_bytes
.BI "(struct ata_queued_cmd *qc "  ","
.BI "unsigned int bytes "  ");"
.SH ARGUMENTS
.IP "qc" 12
Command on going
.IP "bytes" 12
number of bytes

Transfer Transfer data from/to the ATAPI device.

LOCKING:
Inherited from caller.
