.TH "__audit_mq_notify" 9 "__audit_mq_notify" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__audit_mq_notify \- record audit data for a POSIX MQ notify
.SH SYNOPSIS
.B "void" __audit_mq_notify
.BI "(mqd_t mqdes "  ","
.BI "const struct sigevent *notification "  ");"
.SH ARGUMENTS
.IP "mqdes" 12
MQ descriptor
.IP "notification" 12
Notification event
