.TH "__audit_mq_getsetattr" 9 "__audit_mq_getsetattr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__audit_mq_getsetattr \- record audit data for a POSIX MQ get/set attribute
.SH SYNOPSIS
.B "void" __audit_mq_getsetattr
.BI "(mqd_t mqdes "  ","
.BI "struct mq_attr *mqstat "  ");"
.SH ARGUMENTS
.IP "mqdes" 12
MQ descriptor
.IP "mqstat" 12
MQ flags
