.TH "__bdev_dax_supported" 9 "__bdev_dax_supported" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__bdev_dax_supported \- Check if the device supports dax for filesystem
.SH SYNOPSIS
.B "bool" __bdev_dax_supported
.BI "(struct block_device *bdev "  ","
.BI "int blocksize "  ");"
.SH ARGUMENTS
.IP "bdev" 12
block device to check
.IP "blocksize" 12
The block size of the device
.SH "DESCRIPTION"
This is a library function for filesystems to check if the block device
can be mounted with dax option.
.SH "RETURN"
true if supported, false if unsupported
