.TH "__bio_integrity_endio" 9 "__bio_integrity_endio" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__bio_integrity_endio \- Integrity I/O completion function
.SH SYNOPSIS
.B "bool" __bio_integrity_endio
.BI "(struct bio *bio "  ");"
.SH ARGUMENTS
.IP "bio" 12
Protected bio
.SH "DESCRIPTION"
Completion for integrity I/O

Normally I/O completion is done in interrupt context.  However,
verifying I/O integrity is a time-consuming task which must be run
in process context.  This function postpones completion
accordingly.
