.TH "__blk_mq_run_hw_queue" 9 "__blk_mq_run_hw_queue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__blk_mq_run_hw_queue \- Run a hardware queue.
.SH SYNOPSIS
.B "void" __blk_mq_run_hw_queue
.BI "(struct blk_mq_hw_ctx *hctx "  ");"
.SH ARGUMENTS
.IP "hctx" 12
Pointer to the hardware queue to run.
.SH "DESCRIPTION"
Send pending requests to the hardware.
