.TH "__clk_recalc_accuracies" 9 "__clk_recalc_accuracies" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__clk_recalc_accuracies \- 
.SH SYNOPSIS
.B "void" __clk_recalc_accuracies
.BI "(struct clk_core *core "  ");"
.SH ARGUMENTS
.IP "core" 12
first clk in the subtree
.SH "DESCRIPTION"
Walks the subtree of clks starting with clk and recalculates accuracies as
it goes.  Note that if a clk does not implement the .recalc_accuracy
callback then it is assumed that the clock will take on the accuracy of its
parent.
