.TH "__clear_user" 9 "__clear_user" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__clear_user \- Zero a block of memory in user space, with less checking.
.SH SYNOPSIS
.B "unsigned long" __clear_user
.BI "(void __user *to "  ","
.BI "unsigned long n "  ");"
.SH ARGUMENTS
.IP "to" 12
Destination address, in user space.
.IP "n" 12
Number of bytes to zero.
.SH "DESCRIPTION"
Zero a block of memory in user space.  Caller must check
the specified block with \fBaccess_ok\fP before calling this function.
.SH "RETURN"
number of bytes that could not be cleared.
On success, this will be zero.
