.TH "__get_lock" 9 "__get_lock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__get_lock \- find or create a lock instance
.SH SYNOPSIS
.B "struct lock_lookup *" __get_lock
.BI "(void *lock "  ");"
.SH ARGUMENTS
.IP "lock" 12
pointer to a pthread lock function
.SH "DESCRIPTION"
Try to find an existing lock in the rbtree using the provided pointer. If
one wasn't found - create it.
