.TH "__genpd_runtime_suspend" 9 "__genpd_runtime_suspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__genpd_runtime_suspend \- walk the hierarchy of ->runtime_suspend() callbacks
.SH SYNOPSIS
.B "int" __genpd_runtime_suspend
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to handle.
