.TH "__gfs2_lookup" 9 "__gfs2_lookup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__gfs2_lookup \- Look up a filename in a directory and return its inode
.SH SYNOPSIS
.B "struct dentry *" __gfs2_lookup
.BI "(struct inode *dir "  ","
.BI "struct dentry *dentry "  ","
.BI "struct file *file "  ");"
.SH ARGUMENTS
.IP "dir" 12
The directory inode
.IP "dentry" 12
The dentry of the new inode
.IP "file" 12
File to be opened
.SH "RETURN"
errno
