.TH "__gfs2_xattr_set" 9 "__gfs2_xattr_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__gfs2_xattr_set \- Set (or remove) a GFS2 extended attribute
.SH SYNOPSIS
.B "int" __gfs2_xattr_set
.BI "(struct inode *inode "  ","
.BI "const char *name "  ","
.BI "const void *value "  ","
.BI "size_t size "  ","
.BI "int flags "  ","
.BI "int type "  ");"
.SH ARGUMENTS
.IP "inode" 12
-- undescribed --
.IP "name" 12
The name of the extended attribute
.IP "value" 12
The value of the extended attribute (NULL for remove)
.IP "size" 12
The size of the \fIvalue\fP argument
.IP "flags" 12
Create or Replace
.IP "type" 12
The type of the extended attribute
.SH "DESCRIPTION"
See \fBgfs2_xattr_remove\fP for details of the removal of xattrs.
.SH "RETURN"
0 or errno on failure
