.TH "__ice_vsi_get_qs" 9 "__ice_vsi_get_qs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__ice_vsi_get_qs \- helper function for assigning queues from PF to VSI
.SH SYNOPSIS
.B "int" __ice_vsi_get_qs
.BI "(struct ice_qs_cfg *qs_cfg "  ");"
.SH ARGUMENTS
.IP "qs_cfg" 12
gathered variables needed for pf->vsi queues assignment
.SH "DESCRIPTION"
This function first tries to find contiguous space. If it is not successful,
it tries with the scatter approach.

Return 0 on success and -ENOMEM in case of no left space in PF queue bitmap
