.TH "__kfree_skb" 9 "__kfree_skb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__kfree_skb \- private function
.SH SYNOPSIS
.B "void" __kfree_skb
.BI "(struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "skb" 12
buffer

Free an sk_buff. Release anything attached to the buffer.
Clean the state. This is an internal helper function. Users should
always call kfree_skb
