.TH "__memblock_free_late" 9 "__memblock_free_late" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__memblock_free_late \- free pages directly to buddy allocator
.SH SYNOPSIS
.B "void" __memblock_free_late
.BI "(phys_addr_t base "  ","
.BI "phys_addr_t size "  ");"
.SH ARGUMENTS
.IP "base" 12
phys starting address of the  boot memory block
.IP "size" 12
size of the boot memory block in bytes
.SH "DESCRIPTION"
This is only useful when the memblock allocator has already been torn
down, but we are still initializing the system.  Pages are released directly
to the buddy allocator.
