.TH "__mpt3sas_get_sdev_by_rphy" 9 "__mpt3sas_get_sdev_by_rphy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__mpt3sas_get_sdev_by_rphy \- sas device search
.SH SYNOPSIS
.B "struct _sas_device *" __mpt3sas_get_sdev_by_rphy
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "struct sas_rphy *rphy "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "rphy" 12
sas_rphy pointer
.SH "CONTEXT"
This function will acquire ioc->sas_device_lock and will release
before returning the sas_device object.
.SH "DESCRIPTION"
This searches for sas_device from rphy object
then return sas_device object.
