.TH "__nla_reserve_nohdr" 9 "__nla_reserve_nohdr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__nla_reserve_nohdr \- reserve room for attribute without header
.SH SYNOPSIS
.B "void *" __nla_reserve_nohdr
.BI "(struct sk_buff *skb "  ","
.BI "int attrlen "  ");"
.SH ARGUMENTS
.IP "skb" 12
socket buffer to reserve room on
.IP "attrlen" 12
length of attribute payload
.SH "DESCRIPTION"
Reserves room for attribute payload without a header.

The caller is responsible to ensure that the skb provides enough
tailroom for the payload.
