.TH "__of_prop_dup" 9 "__of_prop_dup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__of_prop_dup \- Copy a property dynamically.
.SH SYNOPSIS
.B "struct property *" __of_prop_dup
.BI "(const struct property *prop "  ","
.BI "gfp_t allocflags "  ");"
.SH ARGUMENTS
.IP "prop" 12
Property to copy
.IP "allocflags" 12
Allocation flags (typically pass GFP_KERNEL)
.SH "DESCRIPTION"
Copy a property by dynamically allocating the memory of both the
property structure and the property name & contents. The property's
flags have the OF_DYNAMIC bit set so that we can differentiate between
dynamically allocated properties and not.
Returns the newly allocated property or NULL on out of memory error.
