.TH "__prci_readl" 9 "__prci_readl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__prci_readl \- read from a PRCI register
.SH SYNOPSIS
.B "u32" __prci_readl
.BI "(struct __prci_data *pd "  ","
.BI "u32 offs "  ");"
.SH ARGUMENTS
.IP "pd" 12
PRCI context
.IP "offs" 12
register offset to read from (in bytes, from PRCI base address)
.SH "DESCRIPTION"
Read the register located at offset \fIoffs\fP from the base virtual
address of the PRCI register target described by \fIpd\fP, and return
the value to the caller.
.SH "CONTEXT"
Any context.
.SH "RETURN"
the contents of the register described by \fIpd\fP and \fIoffs\fP.
