.TH "__release_region" 9 "__release_region" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__release_region \- release a previously reserved resource region
.SH SYNOPSIS
.B "void" __release_region
.BI "(struct resource *parent "  ","
.BI "resource_size_t start "  ","
.BI "resource_size_t n "  ");"
.SH ARGUMENTS
.IP "parent" 12
parent resource descriptor
.IP "start" 12
resource start address
.IP "n" 12
resource region size
.SH "DESCRIPTION"
The described resource region must match a currently busy region.
