.TH "__sdw_register_driver" 9 "__sdw_register_driver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__sdw_register_driver \- register a SoundWire Slave driver
.SH SYNOPSIS
.B "int" __sdw_register_driver
.BI "(struct sdw_driver *drv "  ","
.BI "struct module *owner "  ");"
.SH ARGUMENTS
.IP "drv" 12
driver to register
.IP "owner" 12
owning module/driver
.SH "RETURN"
zero on success, else a negative error code.
