.TH "__ssp_readl" 9 "__ssp_readl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__ssp_readl \- read from a SiFive serial port register
.SH SYNOPSIS
.B "u32" __ssp_readl
.BI "(struct sifive_serial_port *ssp "  ","
.BI "u16 offs "  ");"
.SH ARGUMENTS
.IP "ssp" 12
pointer to a struct sifive_serial_port record
.IP "offs" 12
register address offset from the IP block base address
.SH "DESCRIPTION"
Read the contents of the IP block register located at offset \fIoffs\fP from the
IP block base, given a pointer \fIssp\fP to a struct sifive_serial_port record.
.SH "CONTEXT"
Any context.
.SH "RETURN"
the value of the UART register
