.TH "__tipc_node_link_up" 9 "__tipc_node_link_up" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__tipc_node_link_up \- handle addition of link
.SH SYNOPSIS
.B "void" __tipc_node_link_up
.BI "(struct tipc_node *n "  ","
.BI "int bearer_id "  ","
.BI "struct sk_buff_head *xmitq "  ");"
.SH ARGUMENTS
.IP "n" 12
target tipc_node
.IP "bearer_id" 12
id of the bearer
.IP "xmitq" 12
queue for messages to be xmited on
Node lock must be held by caller
Link becomes active (alone or shared) or standby, depending on its priority.
