.TH "__vfs_removexattr_locked" 9 "__vfs_removexattr_locked" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
__vfs_removexattr_locked \- set an extended attribute while holding the inode lock
.SH SYNOPSIS
.B "int" __vfs_removexattr_locked
.BI "(struct user_namespace *mnt_userns "  ","
.BI "struct dentry *dentry "  ","
.BI "const char *name "  ","
.BI "struct inode **delegated_inode "  ");"
.SH ARGUMENTS
.IP "mnt_userns" 12
-- undescribed --
.IP "dentry" 12
object to perform setxattr on
.IP "name" 12
name of xattr to remove
.IP "delegated_inode" 12
on return, will contain an inode pointer that
a delegation was broken on, NULL if none.
