.TH "_base_assign_reply_queues" 9 "_base_assign_reply_queues" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_base_assign_reply_queues \- assigning msix index for each cpu
.SH SYNOPSIS
.B "void" _base_assign_reply_queues
.BI "(struct MPT3SAS_ADAPTER *ioc "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.SH "DESCRIPTION"
The enduser would need to set the affinity via /proc/irq/#/smp_affinity

It would nice if we could call irq_set_affinity, however it is not
an exported symbol
