.TH "_base_free_irq" 9 "_base_free_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_base_free_irq \- free irq
.SH SYNOPSIS
.B "void" _base_free_irq
.BI "(struct MPT3SAS_ADAPTER *ioc "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.SH "DESCRIPTION"
Freeing respective reply_queue from the list.
