.TH "_base_allocate_memory_pools" 9 "_base_allocate_memory_pools" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_base_allocate_memory_pools \- allocate start of day memory pools
.SH SYNOPSIS
.B "int" _base_allocate_memory_pools
.BI "(struct MPT3SAS_ADAPTER *ioc "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.SH "RETURN"
0 success, anything else error.
