.TH "_base_irqpoll" 9 "_base_irqpoll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_base_irqpoll \- IRQ poll callback handler
.SH SYNOPSIS
.B "int" _base_irqpoll
.BI "(struct irq_poll *irqpoll "  ","
.BI "int budget "  ");"
.SH ARGUMENTS
.IP "irqpoll" 12
irq_poll object
.IP "budget" 12
irq poll weight
.SH "DESCRIPTION"
returns number of reply descriptors processed
