.TH "_base_get_chain_buffer_tracker" 9 "_base_get_chain_buffer_tracker" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_base_get_chain_buffer_tracker \- obtain chain tracker
.SH SYNOPSIS
.B "struct chain_tracker *" _base_get_chain_buffer_tracker
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "struct scsi_cmnd *scmd "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "scmd" 12
SCSI commands of the IO request
.SH "RETURN"
chain tracker from chain_lookup table using key as
smid and smid's chain_offset.
