.TH "_base_diag_reset" 9 "_base_diag_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_base_diag_reset \- the "big hammer" start of day reset
.SH SYNOPSIS
.B "int" _base_diag_reset
.BI "(struct MPT3SAS_ADAPTER *ioc "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.SH "RETURN"
0 for success, non-zero for failure.
