.TH "_ctl_compat_mpt_command" 9 "_ctl_compat_mpt_command" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_ctl_compat_mpt_command \- convert 32bit pointers to 64bit.
.SH SYNOPSIS
.B "long" _ctl_compat_mpt_command
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "unsigned cmd "  ","
.BI "void __user *arg "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "cmd" 12
ioctl opcode
.IP "arg" 12
(struct mpt3_ioctl_command32)
.SH "DESCRIPTION"
MPT3COMMAND32 - Handle 32bit applications running on 64bit os.
