.TH "_dpu_crtc_complete_flip" 9 "_dpu_crtc_complete_flip" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_dpu_crtc_complete_flip \- signal pending page_flip events Any pending vblank events are added to the vblank_event_list so that the next vblank interrupt shall signal them. However PAGE_FLIP events are not handled through the vblank_event_list. This API signals any pending PAGE_FLIP events requested through DRM_IOCTL_MODE_PAGE_FLIP and are cached in the dpu_crtc->event.
.SH SYNOPSIS
.B "void" _dpu_crtc_complete_flip
.BI "(struct drm_crtc *crtc "  ");"
.SH ARGUMENTS
.IP "crtc" 12
Pointer to drm crtc structure
