.TH "_dpu_vbif_get_ot_limit" 9 "_dpu_vbif_get_ot_limit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_dpu_vbif_get_ot_limit \- get OT based on usecase & configuration parameters
.SH SYNOPSIS
.B "u32" _dpu_vbif_get_ot_limit
.BI "(struct dpu_hw_vbif *vbif "  ","
.BI "struct dpu_vbif_set_ot_params *params "  ");"
.SH ARGUMENTS
.IP "vbif" 12
Pointer to hardware vbif driver
.IP "params" 12
Pointer to usecase parameters
.SH "RETURN"
OT limit
