.TH "_hfi1_schedule_send" 9 "_hfi1_schedule_send" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_hfi1_schedule_send \- schedule progress
.SH SYNOPSIS
.B "bool" _hfi1_schedule_send
.BI "(struct rvt_qp *qp "  ");"
.SH ARGUMENTS
.IP "qp" 12
the QP
.SH "DESCRIPTION"
This schedules qp progress w/o regard to the s_flags.

It is only used in the post send, which doesn't hold
the s_lock.
