.TH "_omap4_update_context_lost" 9 "_omap4_update_context_lost" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_omap4_update_context_lost \- increment hwmod context loss counter if hwmod context was lost, and clear hardware context loss reg
.SH SYNOPSIS
.B "void" _omap4_update_context_lost
.BI "(struct omap_hwmod *oh "  ");"
.SH ARGUMENTS
.IP "oh" 12
hwmod to check for context loss
.SH "DESCRIPTION"
If the PRCM indicates that the hwmod \fIoh\fP lost context, increment
our in-memory context loss counter, and clear the RM_*_CONTEXT
bits. No return value.
