.TH "_omap4_disable_direct_prcm" 9 "_omap4_disable_direct_prcm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_omap4_disable_direct_prcm \- disable direct PRCM control for hwmod
.SH SYNOPSIS
.B "int" _omap4_disable_direct_prcm
.BI "(struct omap_hwmod *oh "  ");"
.SH ARGUMENTS
.IP "oh" 12
struct omap_hwmod * to disable control for
.SH "DESCRIPTION"
Disables direct PRCM clkctrl done by hwmod core. Instead, the hwmod
will be using its main_clk to enable/disable the module. Returns
0 if successful.
