.TH "_rvt_reset_qp" 9 "_rvt_reset_qp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_rvt_reset_qp \- initialize the QP state to the reset state
.SH SYNOPSIS
.B "void" _rvt_reset_qp
.BI "(struct rvt_dev_info *rdi "  ","
.BI "struct rvt_qp *qp "  ","
.BI "enum ib_qp_type type "  ");"
.SH ARGUMENTS
.IP "rdi" 12
rvt dev struct
.IP "qp" 12
the QP to reset
.IP "type" 12
the QP type
.SH "DESCRIPTION"
r_lock, s_hlock, and s_lock are required to be held by the caller
