.TH "_scsih_srch_boot_device_name" 9 "_scsih_srch_boot_device_name" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_scsih_srch_boot_device_name \- search based on device name
.SH SYNOPSIS
.B "int" _scsih_srch_boot_device_name
.BI "(u64 device_name "  ","
.BI "Mpi2BootDeviceDeviceName_t *boot_device "  ");"
.SH ARGUMENTS
.IP "device_name" 12
device name specified in INDENTIFY fram
.IP "boot_device" 12
boot device object from bios page 2
.SH "RETURN"
1 when there's a match, 0 means no match.
