.TH "_scsih_set_fwfault_debug" 9 "_scsih_set_fwfault_debug" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_scsih_set_fwfault_debug \- global setting of ioc->fwfault_debug.
.SH SYNOPSIS
.B "int" _scsih_set_fwfault_debug
.BI "(const char *val "  ","
.BI "const struct kernel_param *kp "  ");"
.SH ARGUMENTS
.IP "val" 12
?
.IP "kp" 12
?
.SH "RETURN"
?
