.TH "_scsih_sas_device_init_add" 9 "_scsih_sas_device_init_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_scsih_sas_device_init_add \- insert sas_device to the list.
.SH SYNOPSIS
.B "void" _scsih_sas_device_init_add
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "struct _sas_device *sas_device "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "sas_device" 12
the sas_device object
.SH "CONTEXT"
This function will acquire ioc->sas_device_lock.
.SH "DESCRIPTION"
Adding new object at driver load time to the ioc->sas_device_init_list.
