.TH "_scsih_block_io_to_children_attached_directly" 9 "_scsih_block_io_to_children_attached_directly" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_scsih_block_io_to_children_attached_directly \- 
.SH SYNOPSIS
.B "void" _scsih_block_io_to_children_attached_directly
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "Mpi2EventDataSasTopologyChangeList_t *event_data "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "event_data" 12
topology change event data
.SH "DESCRIPTION"
This routine set sdev state to SDEV_BLOCK for all devices
direct attached during device pull.
