.TH "_transport_get_expander_phy_error_log" 9 "_transport_get_expander_phy_error_log" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
_transport_get_expander_phy_error_log \- return expander counters
.SH SYNOPSIS
.B "int" _transport_get_expander_phy_error_log
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "struct sas_phy *phy "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "phy" 12
The sas phy object
.SH "RETURN"
0 for success, non-zero for failure.
