.TH "aa_audit_msg" 9 "aa_audit_msg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aa_audit_msg \- Log a message to the audit subsystem
.SH SYNOPSIS
.B "void" aa_audit_msg
.BI "(int type "  ","
.BI "struct common_audit_data *sa "  ","
.BI "void (*cb) (struct audit_buffer *, void *) "  ");"
.SH ARGUMENTS
.IP "type" 12
-- undescribed --
.IP "sa" 12
audit event structure (NOT NULL)
.IP "cb" 12
optional callback fn for type specific fields (MAYBE NULL)
