.TH "aa_replace_current_label" 9 "aa_replace_current_label" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aa_replace_current_label \- replace the current tasks label
.SH SYNOPSIS
.B "int" aa_replace_current_label
.BI "(struct aa_label *label "  ");"
.SH ARGUMENTS
.IP "label" 12
new label  (NOT NULL)
.SH "RETURN"
0 or error on failure
