.TH "aa_task_setrlimit" 9 "aa_task_setrlimit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aa_task_setrlimit \- test permission to set an rlimit @label - label confining the task (NOT NULL) @task - task the resource is being set on @resource - the resource being set @new_rlim - the new resource limit (NOT NULL)
.SH SYNOPSIS
.B "int" aa_task_setrlimit
.BI "(struct aa_label *label "  ","
.BI "struct task_struct *task "  ","
.BI "unsigned int resource "  ","
.BI "struct rlimit *new_rlim "  ");"
.SH ARGUMENTS
.IP "label" 12
-- undescribed --
.IP "task" 12
-- undescribed --
.IP "resource" 12
-- undescribed --
.IP "new_rlim" 12
-- undescribed --
.SH "DESCRIPTION"

Control raising the processes hard limit.
.SH "RETURN"
0 or error code if setting resource failed
