.TH "aac_get_driver_ident" 9 "aac_get_driver_ident" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aac_get_driver_ident \- 
.SH SYNOPSIS
.B "struct aac_driver_ident*" aac_get_driver_ident
.BI "(int devtype "  ");"
.SH ARGUMENTS
.IP "devtype" 12
index into lookup table

Returns a pointer to the entry in the driver lookup table.
