.TH "aac_get_containers" 9 "aac_get_containers" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aac_get_containers \- list containers
.SH SYNOPSIS
.B "int" aac_get_containers
.BI "(struct aac_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
aac driver data

Make a list of all containers on this controller
