.TH "ab8500_fg_get" 9 "ab8500_fg_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_fg_get \- returns a reference to the primary AB8500 fuel gauge (i.e. the first fuel gauge in the instance list)
.SH SYNOPSIS
.B "struct ab8500_fg *" ab8500_fg_get
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
