.TH "ab8500_fg_calc_cap_discharge_voltage" 9 "ab8500_fg_calc_cap_discharge_voltage" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_fg_calc_cap_discharge_voltage \- Capacity in discharge with voltage
.SH SYNOPSIS
.B "int" ab8500_fg_calc_cap_discharge_voltage
.BI "(struct ab8500_fg *di "  ","
.BI "bool comp "  ");"
.SH ARGUMENTS
.IP "di" 12
pointer to the ab8500_fg structure
.IP "comp" 12
if voltage should be load compensated before capacity calc
.SH "DESCRIPTION"
Return the capacity in mAh based on the battery voltage. The voltage can
either be load compensated or not. This value is added to the filter and a
new mean value is calculated and returned.
