.TH "ab8500_charger_read_usb_type" 9 "ab8500_charger_read_usb_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_charger_read_usb_type \- read the type of usb connected
.SH SYNOPSIS
.B "int" ab8500_charger_read_usb_type
.BI "(struct ab8500_charger *di "  ");"
.SH ARGUMENTS
.IP "di" 12
pointer to the ab8500_charger structure
.SH "DESCRIPTION"
Detect the type of the plugged USB
Returns error code in case of failure else 0 on success
