.TH "ab8500_gpadc_parse_channels" 9 "ab8500_gpadc_parse_channels" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_gpadc_parse_channels \- Parse the GPADC channels from DT
.SH SYNOPSIS
.B "int" ab8500_gpadc_parse_channels
.BI "(struct ab8500_gpadc *gpadc "  ","
.BI "struct device_node *np "  ","
.BI "struct iio_chan_spec **chans_parsed "  ","
.BI "unsigned int *nchans_parsed "  ");"
.SH ARGUMENTS
.IP "gpadc" 12
the GPADC to configure the channels for
.IP "np" 12
device tree node containing the channel configurations
.IP "chans_parsed" 12
-- undescribed --
.IP "nchans_parsed" 12
-- undescribed --
