.TH "ab8500_fg_convert_permille_to_mah" 9 "ab8500_fg_convert_permille_to_mah" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_fg_convert_permille_to_mah \- Capacity in permille to mAh
.SH SYNOPSIS
.B "int" ab8500_fg_convert_permille_to_mah
.BI "(struct ab8500_fg *di "  ","
.BI "int cap_pm "  ");"
.SH ARGUMENTS
.IP "di" 12
pointer to the ab8500_fg structure
.IP "cap_pm" 12
capacity in permille
.SH "DESCRIPTION"
Converts capacity in permille to capacity in mAh
