.TH "ab8500_charger_set_vbus_in_curr" 9 "ab8500_charger_set_vbus_in_curr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_charger_set_vbus_in_curr \- set VBUS input current limit
.SH SYNOPSIS
.B "int" ab8500_charger_set_vbus_in_curr
.BI "(struct ab8500_charger *di "  ","
.BI "int ich_in "  ");"
.SH ARGUMENTS
.IP "di" 12
pointer to the ab8500_charger structure
.IP "ich_in" 12
charger input current limit
.SH "DESCRIPTION"
Sets the current that can be drawn from the USB host
Returns error code in case of failure else 0(on success)
