.TH "ab8500_charger_usb_en" 9 "ab8500_charger_usb_en" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ab8500_charger_usb_en \- enable usb charging
.SH SYNOPSIS
.B "int" ab8500_charger_usb_en
.BI "(struct ux500_charger *charger "  ","
.BI "int enable "  ","
.BI "int vset "  ","
.BI "int ich_out "  ");"
.SH ARGUMENTS
.IP "charger" 12
-- undescribed --
.IP "enable" 12
enable/disable flag
.IP "vset" 12
charging voltage
.IP "ich_out" 12
charger output current
.SH "DESCRIPTION"
Enable/Disable USB charging and turns on/off the charging led respectively.
Returns error code in case of failure else 0(on success)
