.TH "acct_account_cputime" 9 "acct_account_cputime" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acct_account_cputime \- update mm integral after cputime update
.SH SYNOPSIS
.B "void" acct_account_cputime
.BI "(struct task_struct *tsk "  ");"
.SH ARGUMENTS
.IP "tsk" 12
task_struct for accounting
