.TH "acpi_gpiochip_free_interrupts" 9 "acpi_gpiochip_free_interrupts" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_gpiochip_free_interrupts \- Free GPIO ACPI event interrupts.
.SH SYNOPSIS
.B "void" acpi_gpiochip_free_interrupts
.BI "(struct gpio_chip *chip "  ");"
.SH ARGUMENTS
.IP "chip" 12
GPIO chip
.SH "DESCRIPTION"
Free interrupts associated with GPIO ACPI event method for the given
GPIO chip.
