.TH "acpi_get_wakeup_address" 9 "acpi_get_wakeup_address" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_get_wakeup_address \- provide physical address for S3 wakeup
.SH SYNOPSIS
.B "unsigned long" acpi_get_wakeup_address
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Returns the physical address where the kernel should be resumed after the
system awakes from S3, e.g. for programming into the firmware waking vector.
