.TH "acpi_dev_pm_low_power" 9 "acpi_dev_pm_low_power" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_dev_pm_low_power \- Put ACPI device into a low-power state.
.SH SYNOPSIS
.B "int" acpi_dev_pm_low_power
.BI "(struct device *dev "  ","
.BI "struct acpi_device *adev "  ","
.BI "u32 system_state "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to put into a low-power state.
.IP "adev" 12
ACPI device node corresponding to \fIdev\fP.
.IP "system_state" 12
System state to choose the device state for.
