.TH "acpi_handle_path" 9 "acpi_handle_path" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_handle_path \- Return the object path of handle
.SH SYNOPSIS
.B "char *" acpi_handle_path
.BI "(acpi_handle handle "  ");"
.SH ARGUMENTS
.IP "handle" 12
ACPI device handle
.SH "DESCRIPTION"
Caller must free the returned buffer
