.TH "acpi_evaluate_lck" 9 "acpi_evaluate_lck" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_evaluate_lck \- Evaluate _LCK method to lock/unlock device
.SH SYNOPSIS
.B "acpi_status" acpi_evaluate_lck
.BI "(acpi_handle handle "  ","
.BI "int lock "  ");"
.SH ARGUMENTS
.IP "handle" 12
ACPI device handle
.IP "lock" 12
lock device if non-zero, otherwise unlock device
.SH "DESCRIPTION"
Evaluate device's _LCK method if present to lock/unlock device
