.TH "acpi_subsys_suspend_noirq" 9 "acpi_subsys_suspend_noirq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
acpi_subsys_suspend_noirq \- Run the device driver's "noirq" suspend callback.
.SH SYNOPSIS
.B "int" acpi_subsys_suspend_noirq
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device to suspend.
