.TH "ad_initialize_agg" 9 "ad_initialize_agg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ad_initialize_agg \- initialize a given aggregator's parameters
.SH SYNOPSIS
.B "void" ad_initialize_agg
.BI "(struct aggregator *aggregator "  ");"
.SH ARGUMENTS
.IP "aggregator" 12
the aggregator we're looking at
