.TH "ad_sd_write_reg" 9 "ad_sd_write_reg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ad_sd_write_reg \- Write a register
.SH SYNOPSIS
.B "int" ad_sd_write_reg
.BI "(struct ad_sigma_delta *sigma_delta "  ","
.BI "unsigned int reg "  ","
.BI "unsigned int size "  ","
.BI "unsigned int val "  ");"
.SH ARGUMENTS
.IP "sigma_delta" 12
The sigma delta device
.IP "reg" 12
Address of the register
.IP "size" 12
Size of the register (0-3)
.IP "val" 12
Value to write to the register
.SH "DESCRIPTION"
Returns 0 on success, an error code otherwise.
