.TH "add_to_page_cache_locked" 9 "add_to_page_cache_locked" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
add_to_page_cache_locked \- add a locked page to the pagecache
.SH SYNOPSIS
.B "int" add_to_page_cache_locked
.BI "(struct page *page "  ","
.BI "struct address_space *mapping "  ","
.BI "pgoff_t offset "  ","
.BI "gfp_t gfp_mask "  ");"
.SH ARGUMENTS
.IP "page" 12
page to add
.IP "mapping" 12
the page's address_space
.IP "offset" 12
page index
.IP "gfp_mask" 12
page allocation mode
.SH "DESCRIPTION"
This function is used to add a page to the pagecache. It must be locked.
This function does not add the page to the LRU.  The caller must do that.
.SH "RETURN"
0 on success, negative error code otherwise.
