.TH "add_system_map_addresses" 9 "add_system_map_addresses" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
add_system_map_addresses \- Add additional addresses to the parisc device.
.SH SYNOPSIS
.B "void" add_system_map_addresses
.BI "(struct parisc_device *dev "  ","
.BI "int num_addrs "  ","
.BI "int module_instance "  ");"
.SH ARGUMENTS
.IP "dev" 12
The parisc device.
.IP "num_addrs" 12
Then number of addresses to add;
.IP "module_instance" 12
The system_map module instance.
.SH "DESCRIPTION"
This function adds any additional addresses reported by the system_map
firmware to the parisc device.
