.TH "add_page_wait_queue" 9 "add_page_wait_queue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
add_page_wait_queue \- Add an arbitrary waiter to a page's wait queue
.SH SYNOPSIS
.B "void" add_page_wait_queue
.BI "(struct page *page "  ","
.BI "wait_queue_entry_t *waiter "  ");"
.SH ARGUMENTS
.IP "page" 12
Page defining the wait queue of interest
.IP "waiter" 12
Waiter to add to the queue
.SH "DESCRIPTION"
Add an arbitrary \fIwaiter\fP to the wait queue for the nominated \fIpage\fP.
