.TH "add_idx_dirt" 9 "add_idx_dirt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
add_idx_dirt \- add dirt due to a dirty znode.
.SH SYNOPSIS
.B "int" add_idx_dirt
.BI "(struct ubifs_info *c "  ","
.BI "int lnum "  ","
.BI "int dirt "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "lnum" 12
LEB number of index node
.IP "dirt" 12
size of index node
.SH "DESCRIPTION"
This function updates lprops dirty space and the new size of the index.
