.TH "af_alg_free_resources" 9 "af_alg_free_resources" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
af_alg_free_resources \- release resources required for crypto request
.SH SYNOPSIS
.B "void" af_alg_free_resources
.BI "(struct af_alg_async_req *areq "  ");"
.SH ARGUMENTS
.IP "areq" 12
-- undescribed --
