.TH "afiucv_hs_callback_win" 9 "afiucv_hs_callback_win" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
afiucv_hs_callback_win \- react on received WIN
.SH SYNOPSIS
.B "int" afiucv_hs_callback_win
.BI "(struct sock *sk "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "sk" 12
-- undescribed --
.IP "skb" 12
-- undescribed --
