.TH "afu_release" 9 "afu_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
afu_release \- release and free the context
.SH SYNOPSIS
.B "int" afu_release
.BI "(struct inode *inode "  ","
.BI "struct file *file "  ");"
.SH ARGUMENTS
.IP "inode" 12
File inode pointer.
.IP "file" 12
File associated with the context.
.SH "RETURN"
0 on success, -errno on failure
