.TH "afu_unmap_irq" 9 "afu_unmap_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
afu_unmap_irq \- unmap the interrupt
.SH SYNOPSIS
.B "void" afu_unmap_irq
.BI "(u64 flags "  ","
.BI "struct ocxlflash_context *ctx "  ","
.BI "int num "  ","
.BI "void *cookie "  ");"
.SH ARGUMENTS
.IP "flags" 12
Flags.
.IP "ctx" 12
Adapter context.
.IP "num" 12
Per-context AFU interrupt number.
.IP "cookie" 12
Interrupt handler private data.
