.TH "afu_mmio_region_init" 9 "afu_mmio_region_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
afu_mmio_region_init \- init function for afu mmio region support
.SH SYNOPSIS
.B "void" afu_mmio_region_init
.BI "(struct dfl_feature_platform_data *pdata "  ");"
.SH ARGUMENTS
.IP "pdata" 12
afu platform device's pdata.
