.TH "aica_rtc_gettimeofday" 9 "aica_rtc_gettimeofday" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aica_rtc_gettimeofday \- Get the time from the AICA RTC
.SH SYNOPSIS
.B "int" aica_rtc_gettimeofday
.BI "(struct device *dev "  ","
.BI "struct rtc_time *tm "  ");"
.SH ARGUMENTS
.IP "dev" 12
the RTC device (ignored)
.IP "tm" 12
pointer to resulting RTC time structure
.SH "DESCRIPTION"
Grabs the current RTC seconds counter and adjusts it to the Unix Epoch.
