.TH "aio_chip_set_pll" 9 "aio_chip_set_pll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aio_chip_set_pll \- set frequency to audio PLL
.SH SYNOPSIS
.B "int" aio_chip_set_pll
.BI "(struct uniphier_aio_chip *chip "  ","
.BI "int pll_id "  ","
.BI "unsigned int freq "  ");"
.SH ARGUMENTS
.IP "chip" 12
the AIO chip pointer
.IP "pll_id" 12
PLL
.IP "freq" 12
frequency in Hz, 0 is ignored
.SH "DESCRIPTION"
Sets frequency of audio PLL. This function can be called anytime,
but it takes time till PLL is locked.
.SH "RETURN"
Zero if successful, otherwise a negative value on error.
