.TH "alarm_setitimer" 9 "alarm_setitimer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alarm_setitimer \- set alarm in seconds
.SH SYNOPSIS
.B "unsigned int" alarm_setitimer
.BI "(unsigned int seconds "  ");"
.SH ARGUMENTS
.IP "seconds" 12
number of seconds until alarm
0 disables the alarm
.SH "DESCRIPTION"
Returns the remaining time in seconds of a pending timer or 0 when
the timer is not active.

On 32 bit machines the seconds value is limited to (INT_MAX/2) to avoid
negative timeval settings which would cause immediate expiry.
