.TH "ali_dma_check" 9 "ali_dma_check" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ali_dma_check \- DMA check
.SH SYNOPSIS
.B "int" ali_dma_check
.BI "(ide_drive_t *drive "  ","
.BI "struct ide_cmd *cmd "  ");"
.SH ARGUMENTS
.IP "drive" 12
target device
.IP "cmd" 12
command

Returns 1 if the DMA cannot be performed, zero on success.
