.TH "alloc_swapdev_block" 9 "alloc_swapdev_block" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alloc_swapdev_block \- allocate a swap page and register that it has been allocated, so that it can be freed in case of an error.
.SH SYNOPSIS
.B "sector_t" alloc_swapdev_block
.BI "(int swap "  ");"
.SH ARGUMENTS
.IP "swap" 12
-- undescribed --
