.TH "alloc_xenballooned_pages" 9 "alloc_xenballooned_pages" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
alloc_xenballooned_pages \- get pages that have been ballooned out
.SH SYNOPSIS
.B "int" alloc_xenballooned_pages
.BI "(int nr_pages "  ","
.BI "struct page **pages "  ");"
.SH ARGUMENTS
.IP "nr_pages" 12
Number of pages to get
.IP "pages" 12
pages returned
\fIreturn\fP 0 on success, error otherwise
