.TH "am33xx_cm_clkdm_enable_hwsup" 9 "am33xx_cm_clkdm_enable_hwsup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
am33xx_cm_clkdm_enable_hwsup \- put a clockdomain in hwsup-idle mode
.SH SYNOPSIS
.B "void" am33xx_cm_clkdm_enable_hwsup
.BI "(u16 inst "  ","
.BI "u16 cdoffs "  ");"
.SH ARGUMENTS
.IP "inst" 12
CM instance register offset (*_INST macro)
.IP "cdoffs" 12
Clockdomain register offset (*_CDOFFS macro)
.SH "DESCRIPTION"
Put a clockdomain referred to by (\fIinst\fP, \fIcdoffs\fP) into
hardware-supervised idle mode.  No return value.
