.TH "am43xx_control_save_context" 9 "am43xx_control_save_context" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
am43xx_control_save_context \- Save the wakeup domain registers
.SH SYNOPSIS
.B "void" am43xx_control_save_context
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Save the wkup domain registers
