.TH "amd76x_process_error_info" 9 "amd76x_process_error_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amd76x_process_error_info \- Error check
.SH SYNOPSIS
.B "int" amd76x_process_error_info
.BI "(struct mem_ctl_info *mci "  ","
.BI "struct amd76x_error_info *info "  ","
.BI "int handle_errors "  ");"
.SH ARGUMENTS
.IP "mci" 12
Memory controller
.IP "info" 12
Previously fetched information from chip
.IP "handle_errors" 12
1 if we should do recovery

Process the chip state and decide if an error has occurred.
A return of 1 indicates an error. Also if handle_errors is true
then attempt to handle and clean up after the error
