.TH "amdgpu_bo_kptr" 9 "amdgpu_bo_kptr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_bo_kptr \- returns a kernel virtual address of the buffer object
.SH SYNOPSIS
.B "void *" amdgpu_bo_kptr
.BI "(struct amdgpu_bo *bo "  ");"
.SH ARGUMENTS
.IP "bo" 12
\fIamdgpu_bo\fP buffer object
.SH "DESCRIPTION"
Calls \fBttm_kmap_obj_virtual\fP to get the kernel virtual address
.SH "RETURN"
the virtual address of a buffer object area.
