.TH "amdgpu_irq_handle_ih2" 9 "amdgpu_irq_handle_ih2" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_irq_handle_ih2 \- kick of processing for IH2
.SH SYNOPSIS
.B "void" amdgpu_irq_handle_ih2
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
work structure in struct amdgpu_irq
.SH "DESCRIPTION"
Kick of processing IH ring 2.
