.TH "amdgpu_info_ioctl" 9 "amdgpu_info_ioctl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_info_ioctl \- answer a device specific request.
.SH SYNOPSIS
.B "int" amdgpu_info_ioctl
.BI "(struct drm_device *dev "  ","
.BI "void *data "  ","
.BI "struct drm_file *filp "  ");"
.SH ARGUMENTS
.IP "dev" 12
drm device pointer
.IP "data" 12
request object
.IP "filp" 12
drm filp
.SH "DESCRIPTION"
This function is used to pass device specific parameters to the userspace
drivers.  Examples include: pci device id, pipeline parms, tiling params,
etc. (all asics).
Returns 0 on success, -EINVAL on failure.
