.TH "amdgpu_virt_request_full_gpu" 9 "amdgpu_virt_request_full_gpu" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_virt_request_full_gpu \- request full gpu access
.SH SYNOPSIS
.B "int" amdgpu_virt_request_full_gpu
.BI "(struct amdgpu_device *adev "  ","
.BI "bool init "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu device.
.IP "init" 12
is driver init time.
When start to init/fini driver, first need to request full gpu access.
.SH "RETURN"
Zero if request success, otherwise will return error.
