.TH "amdgpu_vm_prt_cb" 9 "amdgpu_vm_prt_cb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vm_prt_cb \- callback for updating the PRT status
.SH SYNOPSIS
.B "void" amdgpu_vm_prt_cb
.BI "(struct dma_fence *fence "  ","
.BI "struct dma_fence_cb *_cb "  ");"
.SH ARGUMENTS
.IP "fence" 12
fence for the callback
.IP "_cb" 12
the callback function
