.TH "amdgpu_device_doorbell_fini" 9 "amdgpu_device_doorbell_fini" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_device_doorbell_fini \- Tear down doorbell driver information.
.SH SYNOPSIS
.B "void" amdgpu_device_doorbell_fini
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Tear down doorbell driver information (CIK)
