.TH "amdgpu_vm_pt_next_dfs" 9 "amdgpu_vm_pt_next_dfs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vm_pt_next_dfs \- get the next node for a deep first search
.SH SYNOPSIS
.B "void" amdgpu_vm_pt_next_dfs
.BI "(struct amdgpu_device *adev "  ","
.BI "struct amdgpu_vm_pt_cursor *cursor "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device structure
.IP "cursor" 12
current state
.SH "DESCRIPTION"
Move the cursor to the next node in a deep first search.
