.TH "amdgpu_vram_mgr_query_page_status" 9 "amdgpu_vram_mgr_query_page_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vram_mgr_query_page_status \- query the reservation status
.SH SYNOPSIS
.B "int" amdgpu_vram_mgr_query_page_status
.BI "(struct ttm_resource_manager *man "  ","
.BI "uint64_t start "  ");"
.SH ARGUMENTS
.IP "man" 12
TTM memory type manager
.IP "start" 12
start address of a page in VRAM
.SH "RETURN"
-EBUSY: the page is still hold and in pending list
0: the page has been reserved
-ENOENT: the input page is not a reservation
