.TH "amdgpu_vm_bo_moved" 9 "amdgpu_vm_bo_moved" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vm_bo_moved \- vm_bo is moved
.SH SYNOPSIS
.B "void" amdgpu_vm_bo_moved
.BI "(struct amdgpu_vm_bo_base *vm_bo "  ");"
.SH ARGUMENTS
.IP "vm_bo" 12
vm_bo which is moved
.SH "DESCRIPTION"
State for per VM BOs which are moved, but that change is not yet reflected
in the page tables.
