.TH "amdgpu_device_vram_scratch_fini" 9 "amdgpu_device_vram_scratch_fini" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_device_vram_scratch_fini \- Free the VRAM scratch page
.SH SYNOPSIS
.B "void" amdgpu_device_vram_scratch_fini
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Frees the VRAM scratch page.
