.TH "amdgpu_device_pci_reset" 9 "amdgpu_device_pci_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_device_pci_reset \- reset the GPU using generic PCI means
.SH SYNOPSIS
.B "int" amdgpu_device_pci_reset
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Resets the GPU using generic pci reset interfaces (FLR, SBR, etc.).
