.TH "amdgpu_bo_subtract_pin_size" 9 "amdgpu_bo_subtract_pin_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_bo_subtract_pin_size \- Remove BO from pin_size accounting
.SH SYNOPSIS
.B "void" amdgpu_bo_subtract_pin_size
.BI "(struct amdgpu_bo *bo "  ");"
.SH ARGUMENTS
.IP "bo" 12
\fIamdgpu_bo\fP buffer object
.SH "DESCRIPTION"
This function is called when a BO stops being pinned, and updates the
\fIamdgpu_device\fP pin_size values accordingly.
