.TH "amdgpu_vm_update_pde" 9 "amdgpu_vm_update_pde" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vm_update_pde \- update a single level in the hierarchy
.SH SYNOPSIS
.B "int" amdgpu_vm_update_pde
.BI "(struct amdgpu_vm_update_params *params "  ","
.BI "struct amdgpu_vm *vm "  ","
.BI "struct amdgpu_vm_pt *entry "  ");"
.SH ARGUMENTS
.IP "params" 12
parameters for the update
.IP "vm" 12
requested vm
.IP "entry" 12
entry to update
.SH "DESCRIPTION"
Makes sure the requested entry in parent is up to date.
