.TH "amdgpu_gfx_rlc_init_sr" 9 "amdgpu_gfx_rlc_init_sr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_gfx_rlc_init_sr \- Init save restore block
.SH SYNOPSIS
.B "int" amdgpu_gfx_rlc_init_sr
.BI "(struct amdgpu_device *adev "  ","
.BI "u32 dws "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.IP "dws" 12
the size of save restore block
.SH "DESCRIPTION"
Allocate and setup value to save restore block of rlc.
Returns 0 on succeess or negative error code if allocate failed.
