.TH "amdgpu_gfx_parse_disable_cu" 9 "amdgpu_gfx_parse_disable_cu" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_gfx_parse_disable_cu \- Parse the disable_cu module parameter
.SH SYNOPSIS
.B "void" amdgpu_gfx_parse_disable_cu
.BI "(unsigned *mask "  ","
.BI "unsigned max_se "  ","
.BI "unsigned max_sh "  ");"
.SH ARGUMENTS
.IP "mask" 12
array in which the per-shader array disable masks will be stored
.IP "max_se" 12
number of SEs
.IP "max_sh" 12
number of SHs
.SH "DESCRIPTION"
The bitmask of CUs to be disabled in the shader array determined by se and
sh is stored in mask[se * max_sh + sh].
