.TH "amdgpu_bo_get_preferred_pin_domain" 9 "amdgpu_bo_get_preferred_pin_domain" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_bo_get_preferred_pin_domain \- get preferred domain for scanout
.SH SYNOPSIS
.B "uint32_t" amdgpu_bo_get_preferred_pin_domain
.BI "(struct amdgpu_device *adev "  ","
.BI "uint32_t domain "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu device object
.IP "domain" 12
allowed :ref:`memory domains <amdgpu_memory_domains>`
.SH "RETURN"
Which of the allowed domains is preferred for pinning the BO for scanout.
