.TH "amdgpu_device_gpu_recover" 9 "amdgpu_device_gpu_recover" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_device_gpu_recover \- reset the asic and recover scheduler
.SH SYNOPSIS
.B "int" amdgpu_device_gpu_recover
.BI "(struct amdgpu_device *adev "  ","
.BI "struct amdgpu_job *job "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.IP "job" 12
which job trigger hang
.SH "DESCRIPTION"
Attempt to reset the GPU if it has hung (all asics).
Attempt to do soft-reset or full-reset and reinitialize Asic
Returns 0 for success or an error on failure.
