.TH "amdgpu_device_need_post" 9 "amdgpu_device_need_post" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_device_need_post \- check if the hw need post or not
.SH SYNOPSIS
.B "bool" amdgpu_device_need_post
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Check if the asic has been initialized (all asics) at driver startup
or post is needed if  hw reset is performed.
Returns true if need or false if not.
