.TH "amdgpu_vm_bo_invalidated" 9 "amdgpu_vm_bo_invalidated" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vm_bo_invalidated \- vm_bo is invalidated
.SH SYNOPSIS
.B "void" amdgpu_vm_bo_invalidated
.BI "(struct amdgpu_vm_bo_base *vm_bo "  ");"
.SH ARGUMENTS
.IP "vm_bo" 12
vm_bo which is now invalidated
.SH "DESCRIPTION"
State for normal BOs which are invalidated and that change not yet reflected
in the PTs.
