.TH "amdgpu_device_parse_gpu_info_fw" 9 "amdgpu_device_parse_gpu_info_fw" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_device_parse_gpu_info_fw \- parse gpu info firmware
.SH SYNOPSIS
.B "int" amdgpu_device_parse_gpu_info_fw
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Parses the asic configuration parameters specified in the gpu info
firmware and makes them availale to the driver for use in configuring
the asic.
Returns 0 on success, -EINVAL on failure.
