.TH "amdgpu_vm_pt_parent" 9 "amdgpu_vm_pt_parent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vm_pt_parent \- get the parent page directory
.SH SYNOPSIS
.B "struct amdgpu_vm_pt *" amdgpu_vm_pt_parent
.BI "(struct amdgpu_vm_pt *pt "  ");"
.SH ARGUMENTS
.IP "pt" 12
child page table
.SH "DESCRIPTION"
Helper to get the parent entry for the child page table. NULL if we are at
the root page directory.
