.TH "amdgpu_bo_free_kernel" 9 "amdgpu_bo_free_kernel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_bo_free_kernel \- free BO for kernel use
.SH SYNOPSIS
.B "void" amdgpu_bo_free_kernel
.BI "(struct amdgpu_bo **bo "  ","
.BI "u64 *gpu_addr "  ","
.BI "void **cpu_addr "  ");"
.SH ARGUMENTS
.IP "bo" 12
amdgpu BO to free
.IP "gpu_addr" 12
pointer to where the BO's GPU memory space address was stored
.IP "cpu_addr" 12
pointer to where the BO's CPU memory space address was stored
.SH "DESCRIPTION"
unmaps and unpin a BO for kernel internal use.
