.TH "amdgpu_acpi_pcie_notify_device_ready" 9 "amdgpu_acpi_pcie_notify_device_ready" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_acpi_pcie_notify_device_ready \- 
.SH SYNOPSIS
.B "int" amdgpu_acpi_pcie_notify_device_ready
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Executes the PCIE_DEVICE_READY_NOTIFICATION method
(all asics).
returns 0 on success, error on failure.
