.TH "amdgpu_vm_bo_insert_map" 9 "amdgpu_vm_bo_insert_map" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_vm_bo_insert_map \- insert a new mapping
.SH SYNOPSIS
.B "void" amdgpu_vm_bo_insert_map
.BI "(struct amdgpu_device *adev "  ","
.BI "struct amdgpu_bo_va *bo_va "  ","
.BI "struct amdgpu_bo_va_mapping *mapping "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.IP "bo_va" 12
bo_va to store the address
.IP "mapping" 12
the mapping to insert
.SH "DESCRIPTION"
Insert a new mapping into all structures.
