.TH "amdgpu_fence_fallback" 9 "amdgpu_fence_fallback" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_fence_fallback \- fallback for hardware interrupts
.SH SYNOPSIS
.B "void" amdgpu_fence_fallback
.BI "(struct timer_list *t "  ");"
.SH ARGUMENTS
.IP "t" 12
timer context used to obtain the pointer to ring structure
.SH "DESCRIPTION"
Checks for fence activity.
