.TH "amdgpu_sync_vm_fence" 9 "amdgpu_sync_vm_fence" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_sync_vm_fence \- remember to sync to this VM fence
.SH SYNOPSIS
.B "int" amdgpu_sync_vm_fence
.BI "(struct amdgpu_sync *sync "  ","
.BI "struct dma_fence *fence "  ");"
.SH ARGUMENTS
.IP "sync" 12
sync object to add fence to
.IP "fence" 12
the VM fence to add
.SH "DESCRIPTION"
Add the fence to the sync object and remember it as VM update.
