.TH "amdgpu_debugfs_add_files" 9 "amdgpu_debugfs_add_files" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_debugfs_add_files \- Add simple debugfs entries
.SH SYNOPSIS
.B "int" amdgpu_debugfs_add_files
.BI "(struct amdgpu_device *adev "  ","
.BI "const struct drm_info_list *files "  ","
.BI "unsigned nfiles "  ");"
.SH ARGUMENTS
.IP "adev" 12
Device to attach debugfs entries to
.IP "files" 12
Array of function callbacks that respond to reads
.IP "nfiles" 12
Number of callbacks to register
