.TH "amdgpu_dm_crtc_handle_crc_irq" 9 "amdgpu_dm_crtc_handle_crc_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdgpu_dm_crtc_handle_crc_irq \- Report to DRM the CRC on given CRTC.
.SH SYNOPSIS
.B "void" amdgpu_dm_crtc_handle_crc_irq
.BI "(struct drm_crtc *crtc "  ");"
.SH ARGUMENTS
.IP "crtc" 12
DRM CRTC object.
.SH "DESCRIPTION"
This function should be called at the end of a vblank, when the fb has been
fully processed through the pipe.
