.TH "amdtp_stream_pcm_abort" 9 "amdtp_stream_pcm_abort" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
amdtp_stream_pcm_abort \- abort the running PCM device
.SH SYNOPSIS
.B "void" amdtp_stream_pcm_abort
.BI "(struct amdtp_stream *s "  ");"
.SH ARGUMENTS
.IP "s" 12
the AMDTP stream about to be stopped
.SH "DESCRIPTION"
If the isochronous stream needs to be stopped asynchronously, call this
function first to stop the PCM device.
