.TH "ap_poll_timeout" 9 "ap_poll_timeout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ap_poll_timeout \- AP receive polling for finished AP requests.
.SH SYNOPSIS
.B "enum hrtimer_restart" ap_poll_timeout
.BI "(struct hrtimer *unused "  ");"
.SH ARGUMENTS
.IP "unused" 12
Unused pointer.
.SH "DESCRIPTION"
Schedules the AP tasklet using a high resolution timer.
