.TH "ap_tasklet_fn" 9 "ap_tasklet_fn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ap_tasklet_fn \- Tasklet to poll all AP devices.
.SH SYNOPSIS
.B "void" ap_tasklet_fn
.BI "(unsigned long dummy "  ");"
.SH ARGUMENTS
.IP "dummy" 12
Unused variable
.SH "DESCRIPTION"
Poll all AP devices on the bus.
