.TH "api_chain_init" 9 "api_chain_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
api_chain_init \- initialize API CMD specific chain
.SH SYNOPSIS
.B "int" api_chain_init
.BI "(struct hinic_api_cmd_chain *chain "  ","
.BI "struct hinic_api_cmd_chain_attr *attr "  ");"
.SH ARGUMENTS
.IP "chain" 12
the API CMD specific chain to initialize
.IP "attr" 12
attributes to set in the chain
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
