.TH "api_cmd_set_num_cells" 9 "api_cmd_set_num_cells" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
api_cmd_set_num_cells \- set the number cells of a chain in the HW
.SH SYNOPSIS
.B "void" api_cmd_set_num_cells
.BI "(struct hinic_api_cmd_chain *chain "  ");"
.SH ARGUMENTS
.IP "chain" 12
the API CMD specific chain to set in HW the number of cells for
