.TH "apparmor_bprm_committing_creds" 9 "apparmor_bprm_committing_creds" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
apparmor_bprm_committing_creds \- do task cleanup on committing new creds
.SH SYNOPSIS
.B "void" apparmor_bprm_committing_creds
.BI "(struct linux_binprm *bprm "  ");"
.SH ARGUMENTS
.IP "bprm" 12
binprm for the exec  (NOT NULL)
