.TH "arc_mdio_complete_wait" 9 "arc_mdio_complete_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
arc_mdio_complete_wait \- Waits until MDIO transaction is completed.
.SH SYNOPSIS
.B "int" arc_mdio_complete_wait
.BI "(struct arc_emac_priv *priv "  ");"
.SH ARGUMENTS
.IP "priv" 12
Pointer to ARC EMAC private data structure.
.SH "RETURN"
0 on success, -ETIMEDOUT on a timeout.
