.TH "arc_mdio_write" 9 "arc_mdio_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
arc_mdio_write \- MDIO interface write function.
.SH SYNOPSIS
.B "int" arc_mdio_write
.BI "(struct mii_bus *bus "  ","
.BI "int phy_addr "  ","
.BI "int reg_num "  ","
.BI "u16 value "  ");"
.SH ARGUMENTS
.IP "bus" 12
Pointer to MII bus structure.
.IP "phy_addr" 12
Address of the PHY device.
.IP "reg_num" 12
PHY register to write to.
.IP "value" 12
Value to be written into the register.
.SH "RETURN"
0 on success, -ETIMEDOUT on a timeout.
.SH "DESCRIPTION"
Writes the value to the requested register.
