.TH "arch_numa_init" 9 "arch_numa_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
arch_numa_init \- Initialize NUMA
.SH SYNOPSIS
.B "void" arch_numa_init
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Try each configured NUMA initialization method until one succeeds. The
last fallback is dummy single node config encompassing whole memory.
