.TH "artop6210_load_piomode" 9 "artop6210_load_piomode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
artop6210_load_piomode \- Load a set of PATA PIO timings
.SH SYNOPSIS
.B "void" artop6210_load_piomode
.BI "(struct ata_port *ap "  ","
.BI "struct ata_device *adev "  ","
.BI "unsigned int pio "  ");"
.SH ARGUMENTS
.IP "ap" 12
Port whose timings we are configuring
.IP "adev" 12
Device
.IP "pio" 12
PIO mode

Set PIO mode for device, in host controller PCI config space. This
is used both to set PIO timings in PIO mode and also to set the
matching PIO clocking for UDMA, as well as the MWDMA timings.

LOCKING:
None (inherited from caller).
