.TH "as10x_cmd_set_context" 9 "as10x_cmd_set_context" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
as10x_cmd_set_context \- send set context command to AS10x
.SH SYNOPSIS
.B "int" as10x_cmd_set_context
.BI "(struct as10x_bus_adapter_t *adap "  ","
.BI "uint16_t tag "  ","
.BI "uint32_t value "  ");"
.SH ARGUMENTS
.IP "adap" 12
pointer to AS10x bus adapter
.IP "tag" 12
context tag
.IP "value" 12
value to set in context
.SH "DESCRIPTION"
Return 0 on success or negative value in case of error.
