.TH "asd_init_chip" 9 "asd_init_chip" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
asd_init_chip \- - initialize the chip
.SH SYNOPSIS
.B "int" asd_init_chip
.BI "(struct asd_ha_struct *asd_ha "  ");"
.SH ARGUMENTS
.IP "asd_ha" 12
pointer to host adapter structure
.SH "DESCRIPTION"
Hard resets the chip, disables HA interrupts, downloads the sequnecer
microcode and starts the sequencers.  The caller has to explicitly
enable HA interrupts with asd_enable_ints(asd_ha).
