.TH "asd_hst_pcix_isr" 9 "asd_hst_pcix_isr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
asd_hst_pcix_isr \- - process host interface interrupts
.SH SYNOPSIS
.B "void" asd_hst_pcix_isr
.BI "(struct asd_ha_struct *asd_ha "  ");"
.SH ARGUMENTS
.IP "asd_ha" 12
pointer to host adapter structure
.SH "DESCRIPTION"
Asserted on PCIX errors: target abort, etc.
