.TH "asd_seq_start_lseq" 9 "asd_seq_start_lseq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
asd_seq_start_lseq \- - start a link sequencer
.SH SYNOPSIS
.B "int" asd_seq_start_lseq
.BI "(struct asd_ha_struct *asd_ha "  ","
.BI "int lseq "  ");"
.SH ARGUMENTS
.IP "asd_ha" 12
pointer to host adapter structure
.IP "lseq" 12
the link sequencer of interest
