.TH "aspeed_gpio_copro_release_gpio" 9 "aspeed_gpio_copro_release_gpio" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
aspeed_gpio_copro_release_gpio \- Unmark a GPIO used by the coprocessor.
.SH SYNOPSIS
.B "int" aspeed_gpio_copro_release_gpio
.BI "(struct gpio_desc *desc "  ");"
.SH ARGUMENTS
.IP "desc" 12
The GPIO to be marked
