.TH "async_synchronize_cookie" 9 "async_synchronize_cookie" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
async_synchronize_cookie \- synchronize asynchronous function calls with cookie checkpointing
.SH SYNOPSIS
.B "void" async_synchronize_cookie
.BI "(async_cookie_t cookie "  ");"
.SH ARGUMENTS
.IP "cookie" 12
async_cookie_t to use as checkpoint
.SH "DESCRIPTION"
This function waits until all asynchronous function calls prior to \fIcookie\fP
have been done.
