.TH "async_tx_quiesce" 9 "async_tx_quiesce" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
async_tx_quiesce \- ensure tx is complete and freeable upon return @tx - transaction to quiesce
.SH SYNOPSIS
.B "void" async_tx_quiesce
.BI "(struct dma_async_tx_descriptor **tx "  ");"
.SH ARGUMENTS
.IP "tx" 12
-- undescribed --
