.TH "ata_scsi_pass_thru" 9 "ata_scsi_pass_thru" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_scsi_pass_thru \- convert ATA pass-thru CDB to taskfile
.SH SYNOPSIS
.B "unsigned int" ata_scsi_pass_thru
.BI "(struct ata_queued_cmd *qc "  ");"
.SH ARGUMENTS
.IP "qc" 12
command structure to be initialized

Handles either 12, 16, or 32-byte versions of the CDB.
.SH "RETURN"
Zero on success, non-zero on failure.
