.TH "ata_pci_remove_one" 9 "ata_pci_remove_one" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_pci_remove_one \- PCI layer callback for device removal
.SH SYNOPSIS
.B "void" ata_pci_remove_one
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device that was removed

PCI layer indicates to libata via this hook that hot-unplug or
module unload event has occurred.  Detach all ports.  Resource
release is handled via devres.

LOCKING:
Inherited from PCI layer (may sleep).
