.TH "ata_tf_to_fis" 9 "ata_tf_to_fis" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_tf_to_fis \- Convert ATA taskfile to SATA FIS structure
.SH SYNOPSIS
.B "void" ata_tf_to_fis
.BI "(const struct ata_taskfile *tf "  ","
.BI "u8 pmp "  ","
.BI "int is_cmd "  ","
.BI "u8 *fis "  ");"
.SH ARGUMENTS
.IP "tf" 12
Taskfile to convert
.IP "pmp" 12
Port multiplier port
.IP "is_cmd" 12
This FIS is for command
.IP "fis" 12
Buffer into which data will output

Converts a standard ATA taskfile to a Serial ATA
FIS structure (Register - Host to Device).

LOCKING:
Inherited from caller.
