.TH "ata_dump_id" 9 "ata_dump_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_dump_id \- IDENTIFY DEVICE info debugging output
.SH SYNOPSIS
.B "void" ata_dump_id
.BI "(const u16 *id "  ");"
.SH ARGUMENTS
.IP "id" 12
IDENTIFY DEVICE page to dump

Dump selected 16-bit words from the given IDENTIFY DEVICE
page.

LOCKING:
caller.
