.TH "ata_scsi_port_error_handler" 9 "ata_scsi_port_error_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_scsi_port_error_handler \- recover the port after the commands
.SH SYNOPSIS
.B "void" ata_scsi_port_error_handler
.BI "(struct Scsi_Host *host "  ","
.BI "struct ata_port *ap "  ");"
.SH ARGUMENTS
.IP "host" 12
SCSI host containing the port
.IP "ap" 12
the ATA port
.SH "DESCRIPTION"
Handle the recovery of the port \fIap\fP after all the commands
have been recovered.
