.TH "ata_unpack_xfermask" 9 "ata_unpack_xfermask" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_unpack_xfermask \- Unpack xfer_mask into pio, mwdma and udma masks
.SH SYNOPSIS
.B "void" ata_unpack_xfermask
.BI "(unsigned long xfer_mask "  ","
.BI "unsigned long *pio_mask "  ","
.BI "unsigned long *mwdma_mask "  ","
.BI "unsigned long *udma_mask "  ");"
.SH ARGUMENTS
.IP "xfer_mask" 12
xfer_mask to unpack
.IP "pio_mask" 12
resulting pio_mask
.IP "mwdma_mask" 12
resulting mwdma_mask
.IP "udma_mask" 12
resulting udma_mask

Unpack \fIxfer_mask\fP into \fIpio_mask\fP, \fImwdma_mask\fP and \fIudma_mask\fP.
Any NULL destination masks will be ignored.
