.TH "ata_qc_schedule_eh" 9 "ata_qc_schedule_eh" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_qc_schedule_eh \- schedule qc for error handling
.SH SYNOPSIS
.B "void" ata_qc_schedule_eh
.BI "(struct ata_queued_cmd *qc "  ");"
.SH ARGUMENTS
.IP "qc" 12
command to schedule error handling for

Schedule error handling for \fIqc\fP.  EH will kick in as soon as
other commands are drained.

LOCKING:
spin_lock_irqsave(host lock)
