.TH "ata_scsi_flush_xlat" 9 "ata_scsi_flush_xlat" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_scsi_flush_xlat \- Translate SCSI SYNCHRONIZE CACHE command
.SH SYNOPSIS
.B "unsigned int" ata_scsi_flush_xlat
.BI "(struct ata_queued_cmd *qc "  ");"
.SH ARGUMENTS
.IP "qc" 12
Storage for translated ATA taskfile

Sets up an ATA taskfile to issue FLUSH CACHE or
FLUSH CACHE EXT.

LOCKING:
spin_lock_irqsave(host lock)
.SH "RETURN"
Zero on success, non-zero on error.
