.TH "ata_msense_rw_recovery" 9 "ata_msense_rw_recovery" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_msense_rw_recovery \- Simulate MODE SENSE r/w error recovery page
.SH SYNOPSIS
.B "unsigned int" ata_msense_rw_recovery
.BI "(u8 *buf "  ","
.BI "bool changeable "  ");"
.SH ARGUMENTS
.IP "buf" 12
output buffer
.IP "changeable" 12
whether changeable parameters are requested

Generate a generic MODE SENSE r/w error recovery page.

LOCKING:
None.
