.TH "ata_tdev_add" 9 "ata_tdev_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ata_tdev_add \- - initialize a transport ATA device structure.
.SH SYNOPSIS
.B "int" ata_tdev_add
.BI "(struct ata_device *ata_dev "  ");"
.SH ARGUMENTS
.IP "ata_dev" 12
ata_dev structure.
.SH "DESCRIPTION"
Initialize an ATA device structure for sysfs.  It will be added in the
device tree below the ATA LINK device it belongs to.

Returns 0 on success
