.TH "atalk_find_or_insert_socket" 9 "atalk_find_or_insert_socket" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
atalk_find_or_insert_socket \- Try to find a socket matching ADDR
.SH SYNOPSIS
.B "struct sock *" atalk_find_or_insert_socket
.BI "(struct sock *sk "  ","
.BI "struct sockaddr_at *sat "  ");"
.SH ARGUMENTS
.IP "sk" 12
socket to insert in the list if it is not there already
.IP "sat" 12
address to search for
.SH "DESCRIPTION"
Try to find a socket matching ADDR in the socket list, if found then return
it. If not, insert SK into the socket list.

This entire operation must execute atomically.
