.TH "atc_prep_dma_memcpy" 9 "atc_prep_dma_memcpy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
atc_prep_dma_memcpy \- prepare a memcpy operation
.SH SYNOPSIS
.B "struct dma_async_tx_descriptor *" atc_prep_dma_memcpy
.BI "(struct dma_chan *chan "  ","
.BI "dma_addr_t dest "  ","
.BI "dma_addr_t src "  ","
.BI "size_t len "  ","
.BI "unsigned long flags "  ");"
.SH ARGUMENTS
.IP "chan" 12
the channel to prepare operation on
.IP "dest" 12
operation virtual destination address
.IP "src" 12
operation virtual source address
.IP "len" 12
operation length
.IP "flags" 12
tx descriptor status flags
