.TH "ath5k_hw_phy_calibrate" 9 "ath5k_hw_phy_calibrate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath5k_hw_phy_calibrate \- Perform a PHY calibration
.SH SYNOPSIS
.B "int" ath5k_hw_phy_calibrate
.BI "(struct ath5k_hw *ah "  ","
.BI "struct ieee80211_channel *channel "  ");"
.SH ARGUMENTS
.IP "ah" 12
The \fIstruct ath5k_hw\fP
.IP "channel" 12
The \fIstruct ieee80211_channel\fP
.SH "DESCRIPTION"
The main function we call from above to perform
a short or full PHY calibration based on RF chip
and current channel
