.TH "ath5k_hw_num_tx_pending" 9 "ath5k_hw_num_tx_pending" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath5k_hw_num_tx_pending \- Get number of pending frames for a given queue
.SH SYNOPSIS
.B "u32" ath5k_hw_num_tx_pending
.BI "(struct ath5k_hw *ah "  ","
.BI "unsigned int queue "  ");"
.SH ARGUMENTS
.IP "ah" 12
The \fIstruct ath5k_hw\fP
.IP "queue" 12
One of enum ath5k_tx_queue_id
