.TH "ath5k_hw_request_rfgain_probe" 9 "ath5k_hw_request_rfgain_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath5k_hw_request_rfgain_probe \- Request a PAPD probe packet
.SH SYNOPSIS
.B "void" ath5k_hw_request_rfgain_probe
.BI "(struct ath5k_hw *ah "  ");"
.SH ARGUMENTS
.IP "ah" 12
The \fIstruct ath5k_hw\fP
.SH "DESCRIPTION"
Schedules a gain probe check on the next transmitted packet.
That means our next packet is going to be sent with lower
tx power and a Peak to Average Power Detector (PAPD) will try
to measure the gain.

TODO: Force a tx packet (bypassing PCU arbitrator etc)
just after we enable the probe so that we don't mess with
standard traffic.
