.TH "ath5k_hw_write_initvals" 9 "ath5k_hw_write_initvals" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath5k_hw_write_initvals \- Write initial chip-specific register dump
.SH SYNOPSIS
.B "int" ath5k_hw_write_initvals
.BI "(struct ath5k_hw *ah "  ","
.BI "u8 mode "  ","
.BI "bool skip_pcu "  ");"
.SH ARGUMENTS
.IP "ah" 12
The \fIstruct ath5k_hw\fP
.IP "mode" 12
One of enum ath5k_driver_mode
.IP "skip_pcu" 12
Skip PCU registers
.SH "DESCRIPTION"
Write initial chip-specific register dump, to get the chipset on a
clean and ready-to-work state after warm reset.
