.TH "ath5k_hw_write_ofdm_timings" 9 "ath5k_hw_write_ofdm_timings" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath5k_hw_write_ofdm_timings \- set OFDM timings on AR5212
.SH SYNOPSIS
.B "int" ath5k_hw_write_ofdm_timings
.BI "(struct ath5k_hw *ah "  ","
.BI "struct ieee80211_channel *channel "  ");"
.SH ARGUMENTS
.IP "ah" 12
the \fIstruct ath5k_hw\fP
.IP "channel" 12
the currently set channel upon reset
.SH "DESCRIPTION"
Write the delta slope coefficient (used on pilot tracking ?) for OFDM
operation on the AR5212 upon reset. This is a helper for ath5k_hw_phy_init.

Since delta slope is floating point we split it on its exponent and
mantissa and provide these values on hw.

For more infos i think this patent is related
"http://www.freepatentsonline.com/7184495.html"
