.TH "ath_dynack_node_deinit" 9 "ath_dynack_node_deinit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath_dynack_node_deinit \- deinit ath_node related info
.SH SYNOPSIS
.B "void" ath_dynack_node_deinit
.BI "(struct ath_hw *ah "  ","
.BI "struct ath_node *an "  ");"
.SH ARGUMENTS
.IP "ah" 12
ath hw
.IP "an" 12
ath node
