.TH "ath_dynack_sample_tx_ts" 9 "ath_dynack_sample_tx_ts" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ath_dynack_sample_tx_ts \- status timestamp sampling method
.SH SYNOPSIS
.B "void" ath_dynack_sample_tx_ts
.BI "(struct ath_hw *ah "  ","
.BI "struct sk_buff *skb "  ","
.BI "struct ath_tx_status *ts "  ","
.BI "struct ieee80211_sta *sta "  ");"
.SH ARGUMENTS
.IP "ah" 12
ath hw
.IP "skb" 12
socket buffer
.IP "ts" 12
tx status info
.IP "sta" 12
station pointer
