.TH "attribute_container_find_class_device" 9 "attribute_container_find_class_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
attribute_container_find_class_device \- find the corresponding class_device
.SH SYNOPSIS
.B "struct device *" attribute_container_find_class_device
.BI "(struct attribute_container *cont "  ","
.BI "struct device *dev "  ");"
.SH ARGUMENTS
.IP "cont" 12
the container
.IP "dev" 12
the generic device
.SH "DESCRIPTION"
Looks up the device in the container's list of class devices and returns
the corresponding class_device.
