.TH "audit_log_untrustedstring" 9 "audit_log_untrustedstring" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
audit_log_untrustedstring \- log a string that may contain random characters
.SH SYNOPSIS
.B "void" audit_log_untrustedstring
.BI "(struct audit_buffer *ab "  ","
.BI "const char *string "  ");"
.SH ARGUMENTS
.IP "ab" 12
audit_buffer
.IP "string" 12
string to be logged
.SH "DESCRIPTION"
Same as \fBaudit_log_n_untrustedstring\fP, except that strlen is used to
determine string length.
