.TH "autoresize" 9 "autoresize" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
autoresize \- re-size the volume which has the "auto-resize" flag set.
.SH SYNOPSIS
.B "int" autoresize
.BI "(struct ubi_device *ubi "  ","
.BI "int vol_id "  ");"
.SH ARGUMENTS
.IP "ubi" 12
UBI device description object
.IP "vol_id" 12
ID of the volume to re-size
.SH "DESCRIPTION"
This function re-sizes the volume marked by the UBI_VTBL_AUTORESIZE_FLG in
the volume table to the largest possible size. See comments in ubi-header.h
for more description of the flag. Returns zero in case of success and a
negative error code in case of failure.
