.TH "axienet_rx_irq" 9 "axienet_rx_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
axienet_rx_irq \- Rx Isr.
.SH SYNOPSIS
.B "irqreturn_t" axienet_rx_irq
.BI "(int irq "  ","
.BI "void *_ndev "  ");"
.SH ARGUMENTS
.IP "irq" 12
irq number
.IP "_ndev" 12
net_device pointer
.SH "RETURN"
IRQ_HANDLED if device generated a RX interrupt, IRQ_NONE otherwise.
.SH "DESCRIPTION"
This is the Axi DMA Rx Isr. It invokes "axienet_recv" to complete the BD
processing.
