.TH "axienet_ethtools_get_drvinfo" 9 "axienet_ethtools_get_drvinfo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
axienet_ethtools_get_drvinfo \- Get various Axi Ethernet driver information.
.SH SYNOPSIS
.B "void" axienet_ethtools_get_drvinfo
.BI "(struct net_device *ndev "  ","
.BI "struct ethtool_drvinfo *ed "  ");"
.SH ARGUMENTS
.IP "ndev" 12
Pointer to net_device structure
.IP "ed" 12
Pointer to ethtool_drvinfo structure
.SH "DESCRIPTION"
This implements ethtool command for getting the driver information.
Issue "ethtool -i ethX" under linux prompt to execute this function.
