.TH "axxia_divclk_recalc_rate" 9 "axxia_divclk_recalc_rate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
axxia_divclk_recalc_rate \- Calculate clock divider output rage
.SH SYNOPSIS
.B "unsigned long" axxia_divclk_recalc_rate
.BI "(struct clk_hw *hw "  ","
.BI "unsigned long parent_rate "  ");"
.SH ARGUMENTS
.IP "hw" 12
-- undescribed --
.IP "parent_rate" 12
-- undescribed --
