.TH "batadv_bla_purge_claims" 9 "batadv_bla_purge_claims" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_bla_purge_claims \- Remove claims after a timeout or immediately
.SH SYNOPSIS
.B "void" batadv_bla_purge_claims
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct batadv_hard_iface *primary_if "  ","
.BI "int now "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "primary_if" 12
the selected primary interface, may be NULL if now is set
.IP "now" 12
whether the whole hash shall be wiped now
.SH "DESCRIPTION"
Check when we heard last time from our own claims, and remove them in case of
a time out, or clean all claims if now is set
