.TH "batadv_nc_path_search" 9 "batadv_nc_path_search" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_nc_path_search \- Find the coding path matching in_nc_node and out_nc_node to retrieve a buffered packet that can be used for coding.
.SH SYNOPSIS
.B "struct batadv_nc_packet *" batadv_nc_path_search
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct batadv_nc_node *in_nc_node "  ","
.BI "struct batadv_nc_node *out_nc_node "  ","
.BI "struct sk_buff *skb "  ","
.BI "u8 *eth_dst "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "in_nc_node" 12
pointer to skb next hop's neighbor nc node
.IP "out_nc_node" 12
pointer to skb source's neighbor nc node
.IP "skb" 12
data skb to forward
.IP "eth_dst" 12
next hop mac address of skb
.SH "RETURN"
true if coding of a decoded skb is allowed.
