.TH "batadv_nc_purge_orig_nc_nodes" 9 "batadv_nc_purge_orig_nc_nodes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_nc_purge_orig_nc_nodes \- go through list of nc nodes and purge stale entries
.SH SYNOPSIS
.B "void" batadv_nc_purge_orig_nc_nodes
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct list_head *list "  ","
.BI "spinlock_t *lock "  ","
.BI "bool (*to_purge)(struct batadv_priv *, struct batadv_nc_node *) "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "list" 12
list of nc nodes
.IP "lock" 12
nc node list lock
.IP "to_purge" 12
function in charge to decide whether an entry has to be purged or
not. This function takes the nc node as argument and has to return
a boolean value: true if the entry has to be deleted, false
otherwise
