.TH "batadv_nc_send_packet" 9 "batadv_nc_send_packet" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_nc_send_packet \- send non-coded packet and free nc_packet struct
.SH SYNOPSIS
.B "void" batadv_nc_send_packet
.BI "(struct batadv_nc_packet *nc_packet "  ");"
.SH ARGUMENTS
.IP "nc_packet" 12
the nc packet to send
