.TH "batadv_nc_init" 9 "batadv_nc_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_nc_init \- one-time initialization for network coding
.SH SYNOPSIS
.B "int" batadv_nc_init
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
0 on success or negative error number in case of failure
