.TH "batadv_choose_backbone_gw" 9 "batadv_choose_backbone_gw" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_choose_backbone_gw \- choose the right bucket for a backbone gateway.
.SH SYNOPSIS
.B "u32" batadv_choose_backbone_gw
.BI "(const void *data "  ","
.BI "u32 size "  ");"
.SH ARGUMENTS
.IP "data" 12
data to hash
.IP "size" 12
size of the hash table
.SH "RETURN"
the hash index of the backbone gateway
