.TH "batadv_tt_global_client_is_roaming" 9 "batadv_tt_global_client_is_roaming" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_tt_global_client_is_roaming \- check if a client is marked as roaming
.SH SYNOPSIS
.B "bool" batadv_tt_global_client_is_roaming
.BI "(struct batadv_priv *bat_priv "  ","
.BI "u8 *addr "  ","
.BI "unsigned short vid "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "addr" 12
the mac address of the client to check
.IP "vid" 12
VLAN identifier
.SH "RETURN"
true if we know that the client has moved from its old originator
to another one. This entry is still kept for consistency purposes and will be
deleted later by a DEL or because of timeout
