.TH "batadv_hardif_neigh_create" 9 "batadv_hardif_neigh_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_hardif_neigh_create \- create a hardif neighbour node
.SH SYNOPSIS
.B "struct batadv_hardif_neigh_node *" batadv_hardif_neigh_create
.BI "(struct batadv_hard_iface *hard_iface "  ","
.BI "const u8 *neigh_addr "  ","
.BI "struct batadv_orig_node *orig_node "  ");"
.SH ARGUMENTS
.IP "hard_iface" 12
the interface this neighbour is connected to
.IP "neigh_addr" 12
the interface address of the neighbour to retrieve
.IP "orig_node" 12
originator object representing the neighbour
.SH "RETURN"
the hardif neighbour node if found or created or NULL otherwise.
