.TH "batadv_purge_orig_ifinfo" 9 "batadv_purge_orig_ifinfo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_purge_orig_ifinfo \- purge obsolete ifinfo entries from originator
.SH SYNOPSIS
.B "bool" batadv_purge_orig_ifinfo
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct batadv_orig_node *orig_node "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "orig_node" 12
orig node which is to be checked
.SH "RETURN"
true if any ifinfo entry was purged, false otherwise.
