.TH "batadv_tt_local_crc" 9 "batadv_tt_local_crc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_tt_local_crc \- calculates the checksum of the local table
.SH SYNOPSIS
.B "u32" batadv_tt_local_crc
.BI "(struct batadv_priv *bat_priv "  ","
.BI "unsigned short vid "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "vid" 12
VLAN identifier for which the CRC32 has to be computed
.SH "DESCRIPTION"
For details about the computation, please refer to the documentation for
\fBbatadv_tt_global_crc\fP.
.SH "RETURN"
the checksum of the local table
