.TH "batadv_is_wifi_hardif" 9 "batadv_is_wifi_hardif" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_is_wifi_hardif \- check if the given hardif is a wifi interface
.SH SYNOPSIS
.B "bool" batadv_is_wifi_hardif
.BI "(struct batadv_hard_iface *hard_iface "  ");"
.SH ARGUMENTS
.IP "hard_iface" 12
the device to check
.SH "RETURN"
true if the net device is a 802.11 wireless device, false otherwise.
