.TH "batadv_tvlv_container_list_size" 9 "batadv_tvlv_container_list_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_tvlv_container_list_size \- calculate the size of the tvlv container list entries
.SH SYNOPSIS
.B "u16" batadv_tvlv_container_list_size
.BI "(struct batadv_priv *bat_priv "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.SH "DESCRIPTION"
Has to be called with the appropriate locks being acquired
(tvlv.container_list_lock).
.SH "RETURN"
size of all currently registered tvlv containers in bytes.
