.TH "batadv_mcast_forw_mode" 9 "batadv_mcast_forw_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_mcast_forw_mode \- check on how to forward a multicast packet
.SH SYNOPSIS
.B "enum batadv_forw_mode" batadv_mcast_forw_mode
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct sk_buff *skb "  ","
.BI "struct batadv_orig_node **orig "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "skb" 12
The multicast packet to check
.IP "orig" 12
an originator to be set to forward the skb to
.SH "RETURN"
the forwarding mode as enum batadv_forw_mode and in case of
BATADV_FORW_SINGLE set the orig to the single originator the skb
should be forwarded to.
