.TH "batadv_v_neigh_dump" 9 "batadv_v_neigh_dump" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_v_neigh_dump \- Dump the neighbours of a hard interface into a message
.SH SYNOPSIS
.B "void" batadv_v_neigh_dump
.BI "(struct sk_buff *msg "  ","
.BI "struct netlink_callback *cb "  ","
.BI "struct batadv_priv *bat_priv "  ","
.BI "struct batadv_hard_iface *single_hardif "  ");"
.SH ARGUMENTS
.IP "msg" 12
Netlink message to dump into
.IP "cb" 12
Control block containing additional options
.IP "bat_priv" 12
The bat priv with all the soft interface information
.IP "single_hardif" 12
Limit dumping to this hard interface
