.TH "batadv_nc_skb_store_for_decoding" 9 "batadv_nc_skb_store_for_decoding" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_nc_skb_store_for_decoding \- save a clone of the skb which can be used when decoding coded packets
.SH SYNOPSIS
.B "void" batadv_nc_skb_store_for_decoding
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "skb" 12
data skb to store
