.TH "batadv_is_wext_netdev" 9 "batadv_is_wext_netdev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_is_wext_netdev \- check if the given net_device struct is a wext wifi interface
.SH SYNOPSIS
.B "bool" batadv_is_wext_netdev
.BI "(struct net_device *net_device "  ");"
.SH ARGUMENTS
.IP "net_device" 12
the device to check
.SH "RETURN"
true if the net device is a wext wireless device, false
otherwise.
