.TH "batadv_iv_ogm_slide_own_bcast_window" 9 "batadv_iv_ogm_slide_own_bcast_window" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_iv_ogm_slide_own_bcast_window \- bitshift own OGM broadcast windows for the given interface
.SH SYNOPSIS
.B "void" batadv_iv_ogm_slide_own_bcast_window
.BI "(struct batadv_hard_iface *hard_iface "  ");"
.SH ARGUMENTS
.IP "hard_iface" 12
the interface for which the windows have to be shifted
