.TH "batadv_forw_packet_free" 9 "batadv_forw_packet_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_forw_packet_free \- free a forwarding packet
.SH SYNOPSIS
.B "void" batadv_forw_packet_free
.BI "(struct batadv_forw_packet *forw_packet "  ","
.BI "bool dropped "  ");"
.SH ARGUMENTS
.IP "forw_packet" 12
The packet to free
.IP "dropped" 12
whether the packet is freed because is dropped
.SH "DESCRIPTION"
This frees a forwarding packet and releases any resources it might
have claimed.
