.TH "batadv_v_ogm_queue_left" 9 "batadv_v_ogm_queue_left" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_v_ogm_queue_left \- check if given OGM still fits aggregation queue
.SH SYNOPSIS
.B "bool" batadv_v_ogm_queue_left
.BI "(struct sk_buff *skb "  ","
.BI "struct batadv_hard_iface *hard_iface "  ");"
.SH ARGUMENTS
.IP "skb" 12
the OGM to check
.IP "hard_iface" 12
the interface to use to send the OGM
.SH "DESCRIPTION"
Caller needs to hold the hard_iface->bat_v.aggr_list.lock.
.SH "RETURN"
True, if the given OGMv2 packet still fits, false otherwise.
