.TH "batadv_netlink_notify_vlan" 9 "batadv_netlink_notify_vlan" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_netlink_notify_vlan \- send vlan attributes to listener
.SH SYNOPSIS
.B "int" batadv_netlink_notify_vlan
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct batadv_softif_vlan *vlan "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "vlan" 12
vlan which was modified
.SH "RETURN"
0 on success, < 0 on error
