.TH "batadv_nc_random_weight_tq" 9 "batadv_nc_random_weight_tq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_nc_random_weight_tq \- scale the receivers TQ-value to avoid unfair selection of a receiver with slightly lower TQ than the other
.SH SYNOPSIS
.B "u8" batadv_nc_random_weight_tq
.BI "(u8 tq "  ");"
.SH ARGUMENTS
.IP "tq" 12
to be weighted tq value
.SH "RETURN"
scaled tq value
