.TH "batadv_orig_node_vlan_release" 9 "batadv_orig_node_vlan_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_orig_node_vlan_release \- release originator-vlan object from lists and queue for free after rcu grace period
.SH SYNOPSIS
.B "void" batadv_orig_node_vlan_release
.BI "(struct kref *ref "  ");"
.SH ARGUMENTS
.IP "ref" 12
kref pointer of the originator-vlan object
