.TH "batadv_nc_memxor" 9 "batadv_nc_memxor" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_nc_memxor \- XOR destination with source
.SH SYNOPSIS
.B "void" batadv_nc_memxor
.BI "(char *dst "  ","
.BI "const char *src "  ","
.BI "unsigned int len "  ");"
.SH ARGUMENTS
.IP "dst" 12
byte array to XOR into
.IP "src" 12
byte array to XOR from
.IP "len" 12
length of destination array
