.TH "batadv_can_nc_with_orig" 9 "batadv_can_nc_with_orig" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_can_nc_with_orig \- checks whether the given orig node is suitable for coding or not
.SH SYNOPSIS
.B "bool" batadv_can_nc_with_orig
.BI "(struct batadv_priv *bat_priv "  ","
.BI "struct batadv_orig_node *orig_node "  ","
.BI "struct batadv_ogm_packet *ogm_packet "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "orig_node" 12
neighboring orig node which may be used as nc candidate
.IP "ogm_packet" 12
incoming ogm packet also used for the checks
.SH "RETURN"
true if:
1) The OGM must have the most recent sequence number.
2) The TTL must be decremented by one and only one.
3) The OGM must be received from the first hop from orig_node.
4) The TQ value of the OGM must be above bat_priv->nc.min_tq.
