.TH "batadv_tvlv_handler_unregister" 9 "batadv_tvlv_handler_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_tvlv_handler_unregister \- unregister tvlv handler based on the provided type and version (both need to match)
.SH SYNOPSIS
.B "void" batadv_tvlv_handler_unregister
.BI "(struct batadv_priv *bat_priv "  ","
.BI "u8 type "  ","
.BI "u8 version "  ");"
.SH ARGUMENTS
.IP "bat_priv" 12
the bat priv with all the soft interface information
.IP "type" 12
tvlv handler type to be unregistered
.IP "version" 12
tvlv handler version to be unregistered
