.TH "batadv_skb_set_priority" 9 "batadv_skb_set_priority" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
batadv_skb_set_priority \- sets skb priority according to packet content
.SH SYNOPSIS
.B "void" batadv_skb_set_priority
.BI "(struct sk_buff *skb "  ","
.BI "int offset "  ");"
.SH ARGUMENTS
.IP "skb" 12
the packet to be sent
.IP "offset" 12
offset to the packet content
.SH "DESCRIPTION"
This function sets a value between 256 and 263 (802.1d priority), which
can be interpreted by the cfg80211 or other drivers.
