.TH "bcm2835_wait_tx_fifo_empty" 9 "bcm2835_wait_tx_fifo_empty" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bcm2835_wait_tx_fifo_empty \- busy-wait for TX FIFO to empty
.SH SYNOPSIS
.B "void" bcm2835_wait_tx_fifo_empty
.BI "(struct bcm2835_spi *bs "  ");"
.SH ARGUMENTS
.IP "bs" 12
BCM2835 SPI controller
.SH "DESCRIPTION"
The caller must ensure that the RX FIFO can accommodate as many bytes
as have been written to the TX FIFO:  Transmission is halted once the
RX FIFO is full, causing this function to spin forever.
