.TH "bcm63xx_fifo_setup" 9 "bcm63xx_fifo_setup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bcm63xx_fifo_setup \- (Re)initialize FIFO boundaries and settings.
.SH SYNOPSIS
.B "void" bcm63xx_fifo_setup
.BI "(struct bcm63xx_udc *udc "  ");"
.SH ARGUMENTS
.IP "udc" 12
Reference to the device controller.
.SH "DESCRIPTION"
These parameters depend on the USB link speed.  Settings are
per-IUDMA-channel-pair.
