.TH "bdisp_hw_build_all_nodes" 9 "bdisp_hw_build_all_nodes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bdisp_hw_build_all_nodes \- 
.SH SYNOPSIS
.B "int" bdisp_hw_build_all_nodes
.BI "(struct bdisp_ctx *ctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
device context
.SH "DESCRIPTION"
Build all the nodes for the blitter operation
.SH "RETURN"
0 on success
