.TH "bdisp_hw_get_hv_inc" 9 "bdisp_hw_get_hv_inc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bdisp_hw_get_hv_inc \- 
.SH SYNOPSIS
.B "int" bdisp_hw_get_hv_inc
.BI "(struct bdisp_ctx *ctx "  ","
.BI "u16 *h_inc "  ","
.BI "u16 *v_inc "  ");"
.SH ARGUMENTS
.IP "ctx" 12
device context
.IP "h_inc" 12
horizontal increment
.IP "v_inc" 12
vertical increment
.SH "DESCRIPTION"
Computes the horizontal & vertical increments (inverse of scale)
.SH "RETURN"
0 on success
