.TH "be_isr_msix" 9 "be_isr_msix" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
be_isr_msix \- The isr routine of the driver.
.SH SYNOPSIS
.B "irqreturn_t" be_isr_msix
.BI "(int irq "  ","
.BI "void *dev_id "  ");"
.SH ARGUMENTS
.IP "irq" 12
Not used
.IP "dev_id" 12
Pointer to host adapter structure
