.TH "befs_bt_get_key" 9 "befs_bt_get_key" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
befs_bt_get_key \- returns a pointer to the start of a key
.SH SYNOPSIS
.B "char *" befs_bt_get_key
.BI "(struct super_block *sb "  ","
.BI "struct befs_btree_node *node "  ","
.BI "int index "  ","
.BI "u16 * keylen "  ");"
.SH ARGUMENTS
.IP "sb" 12
filesystem superblock
.IP "node" 12
node in which to look for the key
.IP "index" 12
the index of the key to get
.IP "keylen" 12
modified to be the length of the key at \fIindex\fP
.SH "DESCRIPTION"
Returns a valid pointer into \fInode\fP on success.
Returns NULL on failure (bad input) and sets *\fIkeylen\fP = 0
