.TH "befs_leafnode" 9 "befs_leafnode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
befs_leafnode \- Determine if the btree node is a leaf node or an interior node
.SH SYNOPSIS
.B "int" befs_leafnode
.BI "(struct befs_btree_node *node "  ");"
.SH ARGUMENTS
.IP "node" 12
Pointer to node structure to test
.SH "DESCRIPTION"
Return 1 if leaf, 0 if interior
