.TH "beiscsi_boot_get_sinfo" 9 "beiscsi_boot_get_sinfo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
beiscsi_boot_get_sinfo \- Get boot session info
.SH SYNOPSIS
.B "unsigned int" beiscsi_boot_get_sinfo
.BI "(struct beiscsi_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
device priv structure instance
.SH "DESCRIPTION"
Fetches the boot_struct.s_handle info from FW.
return
the TAG used for MBOX Command
