.TH "bfa_nw_ioc_attach" 9 "bfa_nw_ioc_attach" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bfa_nw_ioc_attach \- IOC attach time initialization and setup.
.SH SYNOPSIS
.B "void" bfa_nw_ioc_attach
.BI "(struct bfa_ioc *ioc "  ","
.BI "void *bfa "  ","
.BI "struct bfa_ioc_cbfn *cbfn "  ");"
.SH ARGUMENTS
.IP "ioc" 12
memory for IOC
.IP "bfa" 12
driver instance structure
.IP "cbfn" 12
callback function
