.TH "bfa_nw_flash_update_part" 9 "bfa_nw_flash_update_part" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bfa_nw_flash_update_part \- Update flash partition.
.SH SYNOPSIS
.B "enum bfa_status" bfa_nw_flash_update_part
.BI "(struct bfa_flash *flash "  ","
.BI "u32 type "  ","
.BI "u8 instance "  ","
.BI "void *buf "  ","
.BI "u32 len "  ","
.BI "u32 offset "  ","
.BI "bfa_cb_flash cbfn "  ","
.BI "void *cbarg "  ");"
.SH ARGUMENTS
.IP "flash" 12
flash structure
.IP "type" 12
flash partition type
.IP "instance" 12
flash partition instance
.IP "buf" 12
update data buffer
.IP "len" 12
data buffer length
.IP "offset" 12
offset relative to the partition starting address
.IP "cbfn" 12
callback function
.IP "cbarg" 12
callback argument
.SH "DESCRIPTION"
Return status.
