.TH "bfq_bfqq_served" 9 "bfq_bfqq_served" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bfq_bfqq_served \- update the scheduler status after selection for service.
.SH SYNOPSIS
.B "void" bfq_bfqq_served
.BI "(struct bfq_queue *bfqq "  ","
.BI "int served "  ");"
.SH ARGUMENTS
.IP "bfqq" 12
the queue being served.
.IP "served" 12
bytes to transfer.
.SH "NOTE"
this can be optimized, as the timestamps of upper level entities
are synchronized every time a new bfqq is selected for service.  By now,
we keep it to better check consistency.
