.TH "bfq_flush_idle_tree" 9 "bfq_flush_idle_tree" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bfq_flush_idle_tree \- deactivate any entity on the idle tree of @st.
.SH SYNOPSIS
.B "void" bfq_flush_idle_tree
.BI "(struct bfq_service_tree *st "  ");"
.SH ARGUMENTS
.IP "st" 12
the service tree being flushed.
