.TH "binder_alloc_print_allocated" 9 "binder_alloc_print_allocated" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
binder_alloc_print_allocated \- print buffer info
.SH SYNOPSIS
.B "void" binder_alloc_print_allocated
.BI "(struct seq_file *m "  ","
.BI "struct binder_alloc *alloc "  ");"
.SH ARGUMENTS
.IP "m" 12
seq_file for output via \fBseq_printf\fP
.IP "alloc" 12
binder_alloc for this proc
.SH "DESCRIPTION"
Prints information about every buffer associated with
the binder_alloc state to the given seq_file
