.TH "binder_alloc_init" 9 "binder_alloc_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
binder_alloc_init \- called by binder_open() for per-proc initialization
.SH SYNOPSIS
.B "void" binder_alloc_init
.BI "(struct binder_alloc *alloc "  ");"
.SH ARGUMENTS
.IP "alloc" 12
binder_alloc for this proc
.SH "DESCRIPTION"
Called from \fBbinder_open\fP to initialize binder_alloc fields for
new binder proc
