.TH "blk_queue_max_segment_size" 9 "blk_queue_max_segment_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
blk_queue_max_segment_size \- set max segment size for blk_rq_map_sg
.SH SYNOPSIS
.B "void" blk_queue_max_segment_size
.BI "(struct request_queue *q "  ","
.BI "unsigned int max_size "  ");"
.SH ARGUMENTS
.IP "q" 12
the request queue for the device
.IP "max_size" 12
max size of segment in bytes
.SH "DESCRIPTION"
Enables a low level driver to set an upper limit on the size of a
coalesced segment
