.TH "blk_mq_queue_stopped" 9 "blk_mq_queue_stopped" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
blk_mq_queue_stopped \- check whether one or more hctxs have been stopped
.SH SYNOPSIS
.B "bool" blk_mq_queue_stopped
.BI "(struct request_queue *q "  ");"
.SH ARGUMENTS
.IP "q" 12
request queue.
.SH "DESCRIPTION"
The caller is responsible for serializing this function against
blk_mq_{start,stop}\fB_hw_queue\fP.
