.TH "blk_queue_dma_alignment" 9 "blk_queue_dma_alignment" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
blk_queue_dma_alignment \- set dma length and memory alignment
.SH SYNOPSIS
.B "void" blk_queue_dma_alignment
.BI "(struct request_queue *q "  ","
.BI "int mask "  ");"
.SH ARGUMENTS
.IP "q" 12
the request queue for the device
.IP "mask" 12
alignment mask
.SH "DESCRIPTION"
set required memory and length alignment for direct dma transactions.
this is used when building direct io requests for the queue.
