.TH "blk_queue_max_write_same_sectors" 9 "blk_queue_max_write_same_sectors" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
blk_queue_max_write_same_sectors \- set max sectors for a single write same
.SH SYNOPSIS
.B "void" blk_queue_max_write_same_sectors
.BI "(struct request_queue *q "  ","
.BI "unsigned int max_write_same_sectors "  ");"
.SH ARGUMENTS
.IP "q" 12
the request queue for the device
.IP "max_write_same_sectors" 12
maximum number of sectors to write per command
