.TH "bnx2fc_rcv" 9 "bnx2fc_rcv" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2fc_rcv \- This is bnx2fc's receive function called by NET_RX_SOFTIRQ
.SH SYNOPSIS
.B "int" bnx2fc_rcv
.BI "(struct sk_buff *skb "  ","
.BI "struct net_device *dev "  ","
.BI "struct packet_type *ptype "  ","
.BI "struct net_device *olddev "  ");"
.SH ARGUMENTS
.IP "skb" 12
the receive socket buffer
.IP "dev" 12
associated net device
.IP "ptype" 12
context
.IP "olddev" 12
last device
.SH "DESCRIPTION"
This function receives the packet and builds FC frame and passes it up
