.TH "bnx2i_recovery_que_add_conn" 9 "bnx2i_recovery_que_add_conn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2i_recovery_que_add_conn \- add connection to recovery queue
.SH SYNOPSIS
.B "void" bnx2i_recovery_que_add_conn
.BI "(struct bnx2i_hba *hba "  ","
.BI "struct bnx2i_conn *bnx2i_conn "  ");"
.SH ARGUMENTS
.IP "hba" 12
adapter structure pointer
.IP "bnx2i_conn" 12
iscsi connection
.SH "DESCRIPTION"
Add connection to recovery queue and schedule adapter eh worker
