.TH "bnx2x_init_credit_pool" 9 "bnx2x_init_credit_pool" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2x_init_credit_pool \- initialize credit pool internals.
.SH SYNOPSIS
.B "void" bnx2x_init_credit_pool
.BI "(struct bnx2x_credit_pool_obj *p "  ","
.BI "int base "  ","
.BI "int credit "  ");"
.SH ARGUMENTS
.IP "p" 12
credit pool
.IP "base" 12
Base entry in the CAM to use.
.IP "credit" 12
pool size.
.SH "DESCRIPTION"
If base is negative no CAM entries handling will be performed.
If credit is negative pool operations will always succeed (unlimited pool).
