.TH "bnx2i_indicate_kcqe" 9 "bnx2i_indicate_kcqe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2i_indicate_kcqe \- process iscsi conn update completion KCQE
.SH SYNOPSIS
.B "void" bnx2i_indicate_kcqe
.BI "(void *context "  ","
.BI "struct kcqe *kcqe[] "  ","
.BI "u32 num_cqe "  ");"
.SH ARGUMENTS
.IP "context" 12
adapter structure pointer
.IP "kcqe" 12
kcqe pointer
.IP "num_cqe" 12
number of kcqes to process
.SH "DESCRIPTION"
Generic KCQ event handler/dispatcher
