.TH "bnx2i_iscsi_unmap_sg_list" 9 "bnx2i_iscsi_unmap_sg_list" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2i_iscsi_unmap_sg_list \- unmaps SG list
.SH SYNOPSIS
.B "void" bnx2i_iscsi_unmap_sg_list
.BI "(struct bnx2i_cmd *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
iscsi cmd struct pointer
.SH "DESCRIPTION"
unmap IO buffers and invalidate the BD table
