.TH "bnx2x_exe_queue_step" 9 "bnx2x_exe_queue_step" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2x_exe_queue_step \- execute one execution chunk atomically
.SH SYNOPSIS
.B "int" bnx2x_exe_queue_step
.BI "(struct bnx2x *bp "  ","
.BI "struct bnx2x_exe_queue_obj *o "  ","
.BI "unsigned long *ramrod_flags "  ");"
.SH ARGUMENTS
.IP "bp" 12
driver handle
.IP "o" 12
queue
.IP "ramrod_flags" 12
flags
.SH "DESCRIPTION"
(Should be called while holding the exe_queue->lock).
