.TH "bnx2x_mcast_clear_first_bin" 9 "bnx2x_mcast_clear_first_bin" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2x_mcast_clear_first_bin \- find the first set bin and clear it
.SH SYNOPSIS
.B "int" bnx2x_mcast_clear_first_bin
.BI "(struct bnx2x_mcast_obj *o "  ");"
.SH ARGUMENTS
.IP "o" 12
.SH "DESCRIPTION"
returns the index of the found bin or -1 if none is found
