.TH "bnx2x_send_unload_done" 9 "bnx2x_send_unload_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2x_send_unload_done \- send UNLOAD_DONE command to the MCP.
.SH SYNOPSIS
.B "void" bnx2x_send_unload_done
.BI "(struct bnx2x *bp "  ","
.BI "bool keep_link "  ");"
.SH ARGUMENTS
.IP "bp" 12
driver handle
.IP "keep_link" 12
true iff link should be kept up
