.TH "bnx2i_setup_cmd_pool" 9 "bnx2i_setup_cmd_pool" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2i_setup_cmd_pool \- sets up iscsi command pool for the session
.SH SYNOPSIS
.B "int" bnx2i_setup_cmd_pool
.BI "(struct bnx2i_hba *hba "  ","
.BI "struct iscsi_session *session "  ");"
.SH ARGUMENTS
.IP "hba" 12
adapter instance pointer
.IP "session" 12
iscsi session pointer
