.TH "bnx2i_find_hba_for_cnic" 9 "bnx2i_find_hba_for_cnic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2i_find_hba_for_cnic \- maps cnic device instance to bnx2i adapter instance
.SH SYNOPSIS
.B "struct bnx2i_hba *" bnx2i_find_hba_for_cnic
.BI "(struct cnic_dev *cnic "  ");"
.SH ARGUMENTS
.IP "cnic" 12
pointer to cnic device instance
