.TH "bnx2x_clp_reset_done" 9 "bnx2x_clp_reset_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2x_clp_reset_done \- restore the value of the `magic' bit.
.SH SYNOPSIS
.B "void" bnx2x_clp_reset_done
.BI "(struct bnx2x *bp "  ","
.BI "u32 magic_val "  ");"
.SH ARGUMENTS
.IP "bp" 12
driver handle
.IP "magic_val" 12
old value of the `magic' bit.
