.TH "bnx2x_free_msix_irqs" 9 "bnx2x_free_msix_irqs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2x_free_msix_irqs \- free previously requested MSI-X IRQ vectors
.SH SYNOPSIS
.B "void" bnx2x_free_msix_irqs
.BI "(struct bnx2x *bp "  ","
.BI "int nvecs "  ");"
.SH ARGUMENTS
.IP "bp" 12
driver handle
.IP "nvecs" 12
number of vectors to be released
