.TH "bnx2fc_send_session_enable_req" 9 "bnx2fc_send_session_enable_req" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2fc_send_session_enable_req \- initiates FCoE Session enablement
.SH SYNOPSIS
.B "int" bnx2fc_send_session_enable_req
.BI "(struct fcoe_port *port "  ","
.BI "struct bnx2fc_rport *tgt "  ");"
.SH ARGUMENTS
.IP "port" 12
port structure pointer
.IP "tgt" 12
bnx2fc_rport structure pointer
