.TH "bnx2i_setup_write_cmd_bd_info" 9 "bnx2i_setup_write_cmd_bd_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2i_setup_write_cmd_bd_info \- sets up BD various information
.SH SYNOPSIS
.B "void" bnx2i_setup_write_cmd_bd_info
.BI "(struct iscsi_task *task "  ");"
.SH ARGUMENTS
.IP "task" 12
transport layer's cmd struct pointer
.SH "DESCRIPTION"
identifies & marks various bd info for scsi command's immediate data,
unsolicited data and first solicited data seq which includes BD start
index & BD buf off. his function takes into account iscsi parameter such
as immediate data and unsolicited data is support on this connection.
