.TH "bnx2i_send_iscsi_login" 9 "bnx2i_send_iscsi_login" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bnx2i_send_iscsi_login \- post iSCSI login request MP WQE to hardware
.SH SYNOPSIS
.B "int" bnx2i_send_iscsi_login
.BI "(struct bnx2i_conn *bnx2i_conn "  ","
.BI "struct iscsi_task *task "  ");"
.SH ARGUMENTS
.IP "bnx2i_conn" 12
iscsi connection
.IP "task" 12
transport layer's command structure pointer which is requesting
a WQE to sent to chip for further processing
.SH "DESCRIPTION"
prepare and post an iSCSI Login request WQE to CNIC firmware
