.TH "bond_get_slave_by_id" 9 "bond_get_slave_by_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
bond_get_slave_by_id \- get xmit slave with slave_id
.SH SYNOPSIS
.B "struct slave *" bond_get_slave_by_id
.BI "(struct bonding *bond "  ","
.BI "int slave_id "  ");"
.SH ARGUMENTS
.IP "bond" 12
bonding device that is transmitting
.IP "slave_id" 12
slave id up to slave_cnt-1 through which to transmit
.SH "DESCRIPTION"
This function tries to get slave with slave_id but in case
it fails, it tries to find the first available slave for transmission.
