.TH "brcmf_fweh_event_name" 9 "brcmf_fweh_event_name" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
brcmf_fweh_event_name \- returns name for given event code.
.SH SYNOPSIS
.B "const char *" brcmf_fweh_event_name
.BI "(enum brcmf_fweh_event_code code "  ");"
.SH ARGUMENTS
.IP "code" 12
code to lookup.
