.TH "brcmf_p2p_set_firmware" 9 "brcmf_p2p_set_firmware" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
brcmf_p2p_set_firmware \- prepare firmware for peer-to-peer operation.
.SH SYNOPSIS
.B "int" brcmf_p2p_set_firmware
.BI "(struct brcmf_if *ifp "  ","
.BI "u8 *p2p_mac "  ");"
.SH ARGUMENTS
.IP "ifp" 12
ifp to use for iovars (primary).
.IP "p2p_mac" 12
mac address to configure for p2p_da_override
