.TH "BRM_status_show" 9 "BRM_status_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
BRM_status_show \- Backup Rail Monitor Status
.SH SYNOPSIS
.B "ssize_t" BRM_status_show
.BI "(struct device *cdev "  ","
.BI "struct device_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "cdev" 12
pointer to embedded class device
.IP "attr" 12
?
.IP "buf" 12
the buffer returned
.SH "DESCRIPTION"
This is number of reply queues

A sysfs 'read-only' shost attribute.
