.TH "btrfs_find_allocatable_zones" 9 "btrfs_find_allocatable_zones" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
btrfs_find_allocatable_zones \- find allocatable zones within a given region
.SH SYNOPSIS
.B "u64" btrfs_find_allocatable_zones
.BI "(struct btrfs_device *device "  ","
.BI "u64 hole_start "  ","
.BI "u64 hole_end "  ","
.BI "u64 num_bytes "  ");"
.SH ARGUMENTS
.IP "device" 12
the device to allocate a region on
.IP "hole_start" 12
the position of the hole to allocate the region
.IP "hole_end" 12
the end of the hole
.IP "num_bytes" 12
size of wanted region
.SH "RETURN"
position of allocatable zones
.SH "DESCRIPTION"
Allocatable region should not contain any superblock locations.
