.TH "buffer_icap_set_offset" 9 "buffer_icap_set_offset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
buffer_icap_set_offset \- Set the bram offset register.
.SH SYNOPSIS
.B "void" buffer_icap_set_offset
.BI "(void __iomem *base_address "  ","
.BI "u32 data "  ");"
.SH ARGUMENTS
.IP "base_address" 12
contains the base address of the device.
.IP "data" 12
is the value to be written to the data register.
.SH "DESCRIPTION"
The bram offset register holds the starting bram address to transfer
data from during configuration or write data to during readback.
