.TH "ca8210_remove" 9 "ca8210_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ca8210_remove \- Shut down a ca8210 upon being disconnected
.SH SYNOPSIS
.B "int" ca8210_remove
.BI "(struct spi_device *spi_device "  ");"
.SH ARGUMENTS
.IP "spi_device" 12
Pointer to spi device data structure
.SH "RETURN"
0 or linux error code
