.TH "ca8210_set_csma_params" 9 "ca8210_set_csma_params" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ca8210_set_csma_params \- Sets the CSMA parameters of the ca8210
.SH SYNOPSIS
.B "int" ca8210_set_csma_params
.BI "(struct ieee802154_hw *hw "  ","
.BI "u8 min_be "  ","
.BI "u8 max_be "  ","
.BI "u8 retries "  ");"
.SH ARGUMENTS
.IP "hw" 12
ieee802154_hw of target ca8210
.IP "min_be" 12
Minimum backoff exponent when backing off a transmission
.IP "max_be" 12
Maximum backoff exponent when backing off a transmission
.IP "retries" 12
Number of times to retry after backing off
.SH "RETURN"
0 or linux error code
