.TH "cail_pll_read" 9 "cail_pll_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cail_pll_read \- read PLL register
.SH SYNOPSIS
.B "uint32_t" cail_pll_read
.BI "(struct card_info *info "  ","
.BI "uint32_t reg "  ");"
.SH ARGUMENTS
.IP "info" 12
atom card_info pointer
.IP "reg" 12
PLL register offset
.SH "DESCRIPTION"
Provides a PLL register accessor for the atom interpreter (r4xx+).
Returns the value of the PLL register.
