.TH "calc_0124" 9 "calc_0124" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
calc_0124 \- calculate divisor control for divisors that do /0, /1. /2 and /4
.SH SYNOPSIS
.B "unsigned int" calc_0124
.BI "(unsigned int cyc "  ","
.BI "unsigned long hclk_tns "  ","
.BI "unsigned long *v "  ","
.BI "int shift "  ");"
.SH ARGUMENTS
.IP "cyc" 12
The cycle time, in 10ths of nanoseconds.
.IP "hclk_tns" 12
The cycle time for HCLK, in 10ths of nanoseconds.
.IP "v" 12
Pointer to register to alter.
.IP "shift" 12
The shift to get to the control bits.
.SH "DESCRIPTION"
Calculate the divisor, and turn it into the correct control bits to
set in the result, \fIv\fP.
