.TH "cavium_ptp_settime" 9 "cavium_ptp_settime" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cavium_ptp_settime \- Set hardware clock time. Reset adjustment
.SH SYNOPSIS
.B "int" cavium_ptp_settime
.BI "(struct ptp_clock_info *ptp_info "  ","
.BI "const struct timespec64 *ts "  ");"
.SH ARGUMENTS
.IP "ptp_info" 12
PTP clock info
.IP "ts" 12
timespec
