.TH "cayman_dma_stop" 9 "cayman_dma_stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cayman_dma_stop \- stop the async dma engines
.SH SYNOPSIS
.B "void" cayman_dma_stop
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Stop the async dma engines (cayman-SI).
