.TH "cc_get_sgl_nents" 9 "cc_get_sgl_nents" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cc_get_sgl_nents \- Get scatterlist number of entries.
.SH SYNOPSIS
.B "unsigned int" cc_get_sgl_nents
.BI "(struct device *dev "  ","
.BI "struct scatterlist *sg_list "  ","
.BI "unsigned int nbytes "  ","
.BI "u32 *lbytes "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device object
.IP "sg_list" 12
SG list
.IP "nbytes" 12
[IN] Total SGL data bytes.
.IP "lbytes" 12
[OUT] Returns the amount of bytes at the last entry
.SH "RETURN"
Number of entries in the scatterlist
