.TH "ccid3_update_send_interval" 9 "ccid3_update_send_interval" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ccid3_update_send_interval \- Calculate new t_ipi = s / X_inst
.SH SYNOPSIS
.B "void" ccid3_update_send_interval
.BI "(struct ccid3_hc_tx_sock *hc "  ");"
.SH ARGUMENTS
.IP "hc" 12
socket to have the send interval updated
.SH "DESCRIPTION"
This respects the granularity of X_inst (64 * bytes/second).
