.TH "ccp_del_device" 9 "ccp_del_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ccp_del_device \- remove a CCP device from the list
.SH SYNOPSIS
.B "void" ccp_del_device
.BI "(struct ccp_device *ccp "  ");"
.SH ARGUMENTS
.IP "ccp" 12
ccp_device struct pointer
.SH "DESCRIPTION"
Remove this unit from the list of devices. If the next device
up for use is this one, adjust the pointer. If this is the last
device, NULL the pointer.
