.TH "ccw_device_resume" 9 "ccw_device_resume" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ccw_device_resume \- resume channel program execution
.SH SYNOPSIS
.B "int" ccw_device_resume
.BI "(struct ccw_device *cdev "  ");"
.SH ARGUMENTS
.IP "cdev" 12
target ccw device
.SH "DESCRIPTION"
\fBccw_device_resume\fP calls rsch on \fIcdev\fP's subchannel.
.SH "RETURN"
0 on success,
-ENODEV on device not operational,
-EINVAL on invalid device state,
-EBUSY on device busy or interrupt pending.
.SH "CONTEXT"
Interrupts disabled, ccw device lock held
