.TH "ccw_device_clear_options" 9 "ccw_device_clear_options" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ccw_device_clear_options \- clear some options
.SH SYNOPSIS
.B "void" ccw_device_clear_options
.BI "(struct ccw_device *cdev "  ","
.BI "unsigned long flags "  ");"
.SH ARGUMENTS
.IP "cdev" 12
device for which the options are to be cleared
.IP "flags" 12
options to be cleared
.SH "DESCRIPTION"
All flags specified in \fIflags\fP are cleared, the remainder is left untouched.
