.TH "ccw_purge_blacklisted" 9 "ccw_purge_blacklisted" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ccw_purge_blacklisted \- purge unused, blacklisted devices
.SH SYNOPSIS
.B "int" ccw_purge_blacklisted
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Unregister all ccw devices that are offline and on the blacklist.
