.TH "cdns_uart_type" 9 "cdns_uart_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cdns_uart_type \- Set UART type to cdns_uart port
.SH SYNOPSIS
.B "const char *" cdns_uart_type
.BI "(struct uart_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
Handle to the uart port structure
.SH "RETURN"
string on success, NULL otherwise
