.TH "cdns_uart_console_setup" 9 "cdns_uart_console_setup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cdns_uart_console_setup \- Initialize the uart to default config
.SH SYNOPSIS
.B "int" cdns_uart_console_setup
.BI "(struct console *co "  ","
.BI "char *options "  ");"
.SH ARGUMENTS
.IP "co" 12
Console handle
.IP "options" 12
Initial settings of uart
.SH "RETURN"
0 on success, negative errno otherwise.
