.TH "cdns_i2c_master_isr" 9 "cdns_i2c_master_isr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cdns_i2c_master_isr \- Interrupt handler for the I2C device in master role
.SH SYNOPSIS
.B "irqreturn_t" cdns_i2c_master_isr
.BI "(void *ptr "  ");"
.SH ARGUMENTS
.IP "ptr" 12
Pointer to I2C device private data
.SH "DESCRIPTION"
This function handles the data interrupt, transfer complete interrupt and
the error interrupts of the I2C device in master role.
.SH "RETURN"
IRQ_HANDLED always
