.TH "cdns_find_pdi" 9 "cdns_find_pdi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cdns_find_pdi \- Find a free PDI
.SH SYNOPSIS
.B "struct sdw_cdns_pdi *" cdns_find_pdi
.BI "(struct sdw_cdns *cdns "  ","
.BI "unsigned int offset "  ","
.BI "unsigned int num "  ","
.BI "struct sdw_cdns_pdi *pdi "  ","
.BI "int dai_id "  ");"
.SH ARGUMENTS
.IP "cdns" 12
Cadence instance
.IP "offset" 12
Starting offset
.IP "num" 12
Number of PDIs
.IP "pdi" 12
PDI instances
.IP "dai_id" 12
DAI id
.SH "DESCRIPTION"
Find a PDI for a given PDI array. The PDI num and dai_id are
expected to match, return NULL otherwise.
