.TH "cdv_restore_display_registers" 9 "cdv_restore_display_registers" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cdv_restore_display_registers \- restore lost register state
.SH SYNOPSIS
.B "int" cdv_restore_display_registers
.BI "(struct drm_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
our DRM device

Restore register state that was lost during suspend and resume.

FIXME: review
