.TH "cgroup_add_legacy_cftypes" 9 "cgroup_add_legacy_cftypes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cgroup_add_legacy_cftypes \- add an array of cftypes for legacy hierarchies
.SH SYNOPSIS
.B "int" cgroup_add_legacy_cftypes
.BI "(struct cgroup_subsys *ss "  ","
.BI "struct cftype *cfts "  ");"
.SH ARGUMENTS
.IP "ss" 12
target cgroup subsystem
.IP "cfts" 12
zero-length name terminated array of cftypes
.SH "DESCRIPTION"
Similar to \fBcgroup_add_cftypes\fP but the added files are only used for
the legacy hierarchies.
