.TH "chain_busy" 9 "chain_busy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
chain_busy \- check if the chain is still processing last requests
.SH SYNOPSIS
.B "int" chain_busy
.BI "(struct hinic_api_cmd_chain *chain "  ");"
.SH ARGUMENTS
.IP "chain" 12
chain to check
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
