.TH "change_mac_addr" 9 "change_mac_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
change_mac_addr \- change the main mac address of network device
.SH SYNOPSIS
.B "int" change_mac_addr
.BI "(struct net_device *netdev "  ","
.BI "const u8 *addr "  ");"
.SH ARGUMENTS
.IP "netdev" 12
network device
.IP "addr" 12
mac address to set
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
