.TH "check_signature" 9 "check_signature" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
check_signature \- find BIOS signatures
.SH SYNOPSIS
.B "int" check_signature
.BI "(const volatile void __iomem *io_addr "  ","
.BI "const unsigned char *signature "  ","
.BI "int length "  ");"
.SH ARGUMENTS
.IP "io_addr" 12
mmio address to check
.IP "signature" 12
signature block
.IP "length" 12
length of signature

Perform a signature comparison with the mmio address io_addr. This
address should have been obtained by ioremap.
Returns 1 on a match.
