.TH "check_txq_status" 9 "check_txq_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
check_txq_status \- Check Tx queue status, and take appropriate action
.SH SYNOPSIS
.B "int" check_txq_status
.BI "(struct lio *lio "  ");"
.SH ARGUMENTS
.IP "lio" 12
per-network private data
.SH "RETURN"
0 if full, number of queues woken up otherwise
