.TH "check_acpi_cpu_flag" 9 "check_acpi_cpu_flag" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
check_acpi_cpu_flag \- Determine if CPU node has a flag set
.SH SYNOPSIS
.B "int" check_acpi_cpu_flag
.BI "(unsigned int cpu "  ","
.BI "int rev "  ","
.BI "u32 flag "  ");"
.SH ARGUMENTS
.IP "cpu" 12
Kernel logical CPU number
.IP "rev" 12
The minimum PPTT revision defining the flag
.IP "flag" 12
The flag itself
.SH "DESCRIPTION"
Check the node representing a CPU for a given flag.
.SH "RETURN"
-ENOENT if the PPTT doesn't exist, the CPU cannot be found or
the table revision isn't new enough.
1, any passed flag set
0, flag unset
