.TH "chown_ok" 9 "chown_ok" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
chown_ok \- verify permissions to chown inode
.SH SYNOPSIS
.B "bool" chown_ok
.BI "(struct user_namespace *mnt_userns "  ","
.BI "const struct inode *inode "  ","
.BI "kuid_t uid "  ");"
.SH ARGUMENTS
.IP "mnt_userns" 12
user namespace of the mount \fIinode\fP was found from
.IP "inode" 12
inode to check permissions on
.IP "uid" 12
uid to chown \fIinode\fP to
.SH "DESCRIPTION"
If the inode has been found through an idmapped mount the user namespace of
the vfsmount must be passed through \fImnt_userns\fP. This function will then
take care to map the inode according to \fImnt_userns\fP before checking
permissions. On non-idmapped mounts or if permission checking is to be
performed on the raw inode simply passs init_user_ns.
