.TH "cik_tiling_mode_table_init" 9 "cik_tiling_mode_table_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cik_tiling_mode_table_init \- init the hw tiling table
.SH SYNOPSIS
.B "void" cik_tiling_mode_table_init
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Starting with SI, the tiling setup is done globally in a
set of 32 tiling modes.  Rather than selecting each set of
parameters per surface as on older asics, we just select
which index in the tiling table we want to use, and the
surface uses those parameters (CIK).
