.TH "cik_mm_rdoorbell" 9 "cik_mm_rdoorbell" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cik_mm_rdoorbell \- read a doorbell dword
.SH SYNOPSIS
.B "u32" cik_mm_rdoorbell
.BI "(struct radeon_device *rdev "  ","
.BI "u32 index "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "index" 12
doorbell index
.SH "DESCRIPTION"
Returns the value in the doorbell aperture at the
requested doorbell index (CIK).
