.TH "cik_vm_decode_fault" 9 "cik_vm_decode_fault" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cik_vm_decode_fault \- print human readable fault info
.SH SYNOPSIS
.B "void" cik_vm_decode_fault
.BI "(struct radeon_device *rdev "  ","
.BI "u32 status "  ","
.BI "u32 addr "  ","
.BI "u32 mc_client "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "status" 12
VM_CONTEXT1_PROTECTION_FAULT_STATUS register value
.IP "addr" 12
VM_CONTEXT1_PROTECTION_FAULT_ADDR register value
.IP "mc_client" 12
VM_CONTEXT1_PROTECTION_FAULT_MCCLIENT register value
.SH "DESCRIPTION"
Print human readable fault information (CIK).
