.TH "cik_cp_gfx_load_microcode" 9 "cik_cp_gfx_load_microcode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cik_cp_gfx_load_microcode \- load the gfx CP ME ucode
.SH SYNOPSIS
.B "int" cik_cp_gfx_load_microcode
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Loads the gfx PFP, ME, and CE ucode.
Returns 0 for success, -EINVAL if the ucode is not available.
