.TH "cik_get_xclk" 9 "cik_get_xclk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cik_get_xclk \- get the xclk
.SH SYNOPSIS
.B "u32" cik_get_xclk
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Returns the reference clock used by the gfx engine
(CIK).
