.TH "cik_irq_process" 9 "cik_irq_process" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cik_irq_process \- interrupt handler
.SH SYNOPSIS
.B "int" cik_irq_process
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Interrupt hander (CIK).  Walk the IH ring,
ack interrupts and schedule work to handle
interrupt events.
Returns irq process return code.
