.TH "cik_pcie_gart_enable" 9 "cik_pcie_gart_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cik_pcie_gart_enable \- gart enable
.SH SYNOPSIS
.B "int" cik_pcie_gart_enable
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
This sets up the TLBs, programs the page tables for VMID0,
sets up the hw for VMIDs 1-15 which are allocated on
demand, and sets up the global locations for the LDS, GDS,
and GPUVM for FSA64 clients (CIK).
Returns 0 for success, errors for failure.
