.TH "cio_tm_start_key" 9 "cio_tm_start_key" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cio_tm_start_key \- perform start function
.SH SYNOPSIS
.B "int" cio_tm_start_key
.BI "(struct subchannel *sch "  ","
.BI "struct tcw *tcw "  ","
.BI "u8 lpm "  ","
.BI "u8 key "  ");"
.SH ARGUMENTS
.IP "sch" 12
subchannel on which to perform the start function
.IP "tcw" 12
transport-command word to be started
.IP "lpm" 12
mask of paths to use
.IP "key" 12
storage key to use for storage access
.SH "DESCRIPTION"
Start the tcw on the given subchannel. Return zero on success, non-zero
otherwise.
