.TH "cipso_v4_doi_putdef" 9 "cipso_v4_doi_putdef" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cipso_v4_doi_putdef \- Releases a reference for the given DOI definition
.SH SYNOPSIS
.B "void" cipso_v4_doi_putdef
.BI "(struct cipso_v4_doi *doi_def "  ");"
.SH ARGUMENTS
.IP "doi_def" 12
the DOI definition
.SH "DESCRIPTION"
Releases a DOI definition reference obtained from \fBcipso_v4_doi_getdef\fP.
