.TH "clear_local_APIC" 9 "clear_local_APIC" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
clear_local_APIC \- shutdown the local APIC
.SH SYNOPSIS
.B "void" clear_local_APIC
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This is called, when a CPU is disabled and before rebooting, so the state of
the local APIC has no dangling leftovers. Also used to cleanout any BIOS
leftovers during boot.
