.TH "clk_has_parent" 9 "clk_has_parent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
clk_has_parent \- check if a clock is a possible parent for another
.SH SYNOPSIS
.B "bool" clk_has_parent
.BI "(struct clk *clk "  ","
.BI "struct clk *parent "  ");"
.SH ARGUMENTS
.IP "clk" 12
clock source
.IP "parent" 12
parent clock source
.SH "DESCRIPTION"
This function can be used in drivers that need to check that a clock can be
the parent of another without actually changing the parent.

Returns true if \fIparent\fP is a possible parent for \fIclk\fP, false otherwise.
