.TH "clk_round_rate" 9 "clk_round_rate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
clk_round_rate \- round the given rate for a clk
.SH SYNOPSIS
.B "long" clk_round_rate
.BI "(struct clk *clk "  ","
.BI "unsigned long rate "  ");"
.SH ARGUMENTS
.IP "clk" 12
the clk for which we are rounding a rate
.IP "rate" 12
the rate which is to be rounded
.SH "DESCRIPTION"
Takes in a rate as input and rounds it to a rate that the clk can actually
use which is then returned.  If clk doesn't support round_rate operation
then the parent rate is returned.
