.TH "clocksource_mark_unstable" 9 "clocksource_mark_unstable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
clocksource_mark_unstable \- mark clocksource unstable via watchdog
.SH SYNOPSIS
.B "void" clocksource_mark_unstable
.BI "(struct clocksource *cs "  ");"
.SH ARGUMENTS
.IP "cs" 12
clocksource to be marked unstable
.SH "DESCRIPTION"
This function is called by the x86 TSC code to mark clocksources as unstable;
it defers demotion and re-selection to a kthread.
