.TH "clocksource_touch_watchdog" 9 "clocksource_touch_watchdog" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
clocksource_touch_watchdog \- Update watchdog
.SH SYNOPSIS
.B "void" clocksource_touch_watchdog
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Update the watchdog after exception contexts such as kgdb so as not
to incorrectly trip the watchdog. This might fail when the kernel
was stopped in code which holds watchdog_lock.
