.TH "clockevents_exchange_device" 9 "clockevents_exchange_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
clockevents_exchange_device \- release and request clock devices
.SH SYNOPSIS
.B "void" clockevents_exchange_device
.BI "(struct clock_event_device *old "  ","
.BI "struct clock_event_device *new "  ");"
.SH ARGUMENTS
.IP "old" 12
device to release (can be NULL)
.IP "new" 12
device to request (can be NULL)
.SH "DESCRIPTION"
Called from various tick functions with clockevents_lock held and
interrupts disabled.
