.TH "cma_release" 9 "cma_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cma_release \- release allocated pages
.SH SYNOPSIS
.B "bool" cma_release
.BI "(struct cma *cma "  ","
.BI "const struct page *pages "  ","
.BI "unsigned int count "  ");"
.SH ARGUMENTS
.IP "cma" 12
Contiguous memory region for which the allocation is performed.
.IP "pages" 12
Allocated pages.
.IP "count" 12
Number of allocated pages.
.SH "DESCRIPTION"
This function releases memory allocated by \fBcma_alloc\fP.
It returns false when provided pages do not belong to contiguous area and
true otherwise.
