.TH "cmd640_qc_issue" 9 "cmd640_qc_issue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cmd640_qc_issue \- command preparation hook
.SH SYNOPSIS
.B "unsigned int" cmd640_qc_issue
.BI "(struct ata_queued_cmd *qc "  ");"
.SH ARGUMENTS
.IP "qc" 12
Command to be issued

Channel 1 has shared timings. We must reprogram the
clock each drive 2/3 switch we do.
