.TH "cmm_oom_notify" 9 "cmm_oom_notify" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cmm_oom_notify \- OOM notifier
.SH SYNOPSIS
.B "int" cmm_oom_notify
.BI "(struct notifier_block *self "  ","
.BI "unsigned long dummy "  ","
.BI "void *parm "  ");"
.SH ARGUMENTS
.IP "self" 12
notifier block struct
.IP "dummy" 12
not used
.IP "parm" 12
returned - number of pages freed
.SH "DESCRIPTION"
Return value:
NOTIFY_OK
