.TH "comedi_set_spriv_auto_free" 9 "comedi_set_spriv_auto_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
comedi_set_spriv_auto_free \- Mark subdevice private data as freeable
.SH SYNOPSIS
.B "void" comedi_set_spriv_auto_free
.BI "(struct comedi_subdevice *s "  ");"
.SH ARGUMENTS
.IP "s" 12
COMEDI subdevice.
.SH "DESCRIPTION"
Mark the subdevice as having a pointer to private data that can be
automatically freed when the COMEDI device is detached from the low-level
driver.
