.TH "compare_gpts" 9 "compare_gpts" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
compare_gpts \- Search disk for valid GPT headers and PTEs
.SH SYNOPSIS
.B "void" compare_gpts
.BI "(gpt_header *pgpt "  ","
.BI "gpt_header *agpt "  ","
.BI "u64 lastlba "  ");"
.SH ARGUMENTS
.IP "pgpt" 12
primary GPT header
.IP "agpt" 12
alternate GPT header
.IP "lastlba" 12
last LBA number
.SH "DESCRIPTION"
Returns nothing.  Sanity checks pgpt and agpt fields
and prints warnings on discrepancies.
