.TH "cond_wakeup_cpu0" 9 "cond_wakeup_cpu0" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cond_wakeup_cpu0 \- Wake up CPU0 if needed.
.SH SYNOPSIS
.B "void" cond_wakeup_cpu0
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

If NMI wants to wake up CPU0, start CPU0.
