.TH "congestion_wait" 9 "congestion_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
congestion_wait \- wait for a backing_dev to become uncongested
.SH SYNOPSIS
.B "long" congestion_wait
.BI "(int sync "  ","
.BI "long timeout "  ");"
.SH ARGUMENTS
.IP "sync" 12
SYNC or ASYNC IO
.IP "timeout" 12
timeout in jiffies
.SH "DESCRIPTION"
Waits for up to \fItimeout\fP jiffies for a backing_dev (any backing_dev) to exit
write congestion.  If no backing_devs are congested then just wait for the
next write to be completed.
