.TH "copy_data" 9 "copy_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
copy_data \- implements data copying function
.SH SYNOPSIS
.B "bool" copy_data
.BI "(struct channel *channel "  ","
.BI "struct mbo *mbo "  ");"
.SH ARGUMENTS
.IP "channel" 12
channel
.IP "mbo" 12
MBO from core
.SH "DESCRIPTION"
Copy data from/to ring buffer to/from MBO and update the buffer position
