.TH "copy_last_highmem_page" 9 "copy_last_highmem_page" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
copy_last_highmem_page \- Copy most the most recent highmem image page.
.SH SYNOPSIS
.B "void" copy_last_highmem_page
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Copy the contents of a highmem image from \fIbuffer\fP, where the caller of
\fBsnapshot_write_next\fP has stored them, to the right location represented by
\fIlast_highmem_page\fP .
