.TH "count_immovable_mem_regions" 9 "count_immovable_mem_regions" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
count_immovable_mem_regions \- Parse SRAT and cache the immovable memory regions into the immovable_mem array.
.SH SYNOPSIS
.B "int" count_immovable_mem_regions
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Return the number of immovable memory regions on success, 0 on failure:

- Too many immovable memory regions
- ACPI off or no SRAT found
- No immovable memory region found.
