.TH "cpu_to_chip_id" 9 "cpu_to_chip_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpu_to_chip_id \- Return the cpus chip-id
.SH SYNOPSIS
.B "int" cpu_to_chip_id
.BI "(int cpu "  ");"
.SH ARGUMENTS
.IP "cpu" 12
The logical cpu number.
.SH "DESCRIPTION"
Return the value of the ibm,chip-id property corresponding to the given
logical cpu number. If the chip-id can not be found, returns -1.
