.TH "cpufreq_set" 9 "cpufreq_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpufreq_set \- set the CPU frequency
.SH SYNOPSIS
.B "int" cpufreq_set
.BI "(struct cpufreq_policy *policy "  ","
.BI "unsigned int freq "  ");"
.SH ARGUMENTS
.IP "policy" 12
pointer to policy struct where freq is being set
.IP "freq" 12
target frequency in kHz
.SH "DESCRIPTION"
Sets the CPU frequency to freq.
