.TH "cpufreq_quick_get" 9 "cpufreq_quick_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpufreq_quick_get \- get the CPU frequency (in kHz) from policy->cur
.SH SYNOPSIS
.B "unsigned int" cpufreq_quick_get
.BI "(unsigned int cpu "  ");"
.SH ARGUMENTS
.IP "cpu" 12
CPU number
.SH "DESCRIPTION"
This is the last known freq, without actually getting it from the driver.
Return value will be same as what is shown in scaling_cur_freq in sysfs.
