.TH "cpufreq_cpu_put" 9 "cpufreq_cpu_put" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpufreq_cpu_put \- Decrement kobject usage counter for cpufreq policy.
.SH SYNOPSIS
.B "void" cpufreq_cpu_put
.BI "(struct cpufreq_policy *policy "  ");"
.SH ARGUMENTS
.IP "policy" 12
cpufreq policy returned by \fBcpufreq_cpu_get\fP.
