.TH "cpuidle_unregister" 9 "cpuidle_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpuidle_unregister \- unregister a driver and the devices. This function can be used only if the driver has been previously registered through the cpuidle_register function.
.SH SYNOPSIS
.B "void" cpuidle_unregister
.BI "(struct cpuidle_driver *drv "  ");"
.SH ARGUMENTS
.IP "drv" 12
a valid pointer to a struct cpuidle_driver
