.TH "cpumask_any_but" 9 "cpumask_any_but" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpumask_any_but \- return a "random" in a cpumask, but not this one.
.SH SYNOPSIS
.B "int" cpumask_any_but
.BI "(const struct cpumask *mask "  ","
.BI "unsigned int cpu "  ");"
.SH ARGUMENTS
.IP "mask" 12
the cpumask to search
.IP "cpu" 12
the cpu to ignore.
.SH "DESCRIPTION"
Often used to find any cpu but \fBsmp_processor_id\fP in a mask.
Returns >= nr_cpu_ids if no cpus set.
