.TH "cpuset_print_current_mems_allowed" 9 "cpuset_print_current_mems_allowed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cpuset_print_current_mems_allowed \- prints current's cpuset and mems_allowed
.SH SYNOPSIS
.B "void" cpuset_print_current_mems_allowed
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"
Prints current's name, cpuset name, and cached copy of its
mems_allowed to the kernel log.
