.TH "crc4" 9 "crc4" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
crc4 \- calculate the 4-bit crc of a value.
.SH SYNOPSIS
.B "uint8_t" crc4
.BI "(uint8_t c "  ","
.BI "uint64_t x "  ","
.BI "int bits "  ");"
.SH ARGUMENTS
.IP "c" 12
starting crc4
.IP "x" 12
value to checksum
.IP "bits" 12
number of bits in \fIx\fP to checksum
.SH "DESCRIPTION"
Returns the crc4 value of \fIx\fP, using polynomial 0b10111.

The \fIx\fP value is treated as left-aligned, and bits above \fIbits\fP are ignored
in the crc calculations.
