.TH "crc64_be" 9 "crc64_be" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
crc64_be \- Calculate bitwise big-endian ECMA-182 CRC64
.SH SYNOPSIS
.B "u64 __pure" crc64_be
.BI "(u64 crc "  ","
.BI "const void *p "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "crc" 12
seed value for computation. 0 or (u64)~0 for a new CRC calculation,
.IP "p" 12
pointer to buffer over which CRC64 is run
.IP "len" 12
length of buffer \fIp\fP
