.TH "crc8_populate_msb" 9 "crc8_populate_msb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
crc8_populate_msb \- fill crc table for given polynomial in reverse bit order.
.SH SYNOPSIS
.B "void" crc8_populate_msb
.BI "(u8 table[CRC8_TABLE_SIZE] "  ","
.BI "u8 polynomial "  ");"
.SH ARGUMENTS
.IP "table" 12
table to be filled.
.IP "polynomial" 12
polynomial for which table is to be filled.
