.TH "create_worker" 9 "create_worker" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
create_worker \- create a new workqueue worker
.SH SYNOPSIS
.B "struct worker *" create_worker
.BI "(struct worker_pool *pool "  ");"
.SH ARGUMENTS
.IP "pool" 12
pool the new worker will belong to
.SH "DESCRIPTION"
Create and start a new worker which is attached to \fIpool\fP.
.SH "CONTEXT"
Might sleep.  Does GFP_KERNEL allocations.
.SH "RETURN"
Pointer to the newly created worker.
