.TH "create_txqs" 9 "create_txqs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
create_txqs \- Create the Logical Tx Queues of specific NIC device
.SH SYNOPSIS
.B "int" create_txqs
.BI "(struct hinic_dev *nic_dev "  ");"
.SH ARGUMENTS
.IP "nic_dev" 12
the specific NIC device
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
