.TH "cryp_activity" 9 "cryp_activity" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cryp_activity \- This routine enables/disable the cryptography function.
.SH SYNOPSIS
.B "void" cryp_activity
.BI "(struct cryp_device_data *device_data "  ","
.BI "enum cryp_crypen cryp_crypen "  ");"
.SH ARGUMENTS
.IP "device_data" 12
Pointer to the device data struct for base address.
.IP "cryp_crypen" 12
Enable/Disable functionality
