.TH "cs4270_remove" 9 "cs4270_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cs4270_remove \- ASoC remove function
.SH SYNOPSIS
.B "void" cs4270_remove
.BI "(struct snd_soc_component *component "  ");"
.SH ARGUMENTS
.IP "component" 12
ASoC component
.SH "DESCRIPTION"
This function is the counterpart to \fBcs4270_probe\fP.
