.TH "cs5530_init_one" 9 "cs5530_init_one" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cs5530_init_one \- Initialise a CS5530
.SH SYNOPSIS
.B "int" cs5530_init_one
.BI "(struct pci_dev *pdev "  ","
.BI "const struct pci_device_id *id "  ");"
.SH ARGUMENTS
.IP "pdev" 12
-- undescribed --
.IP "id" 12
Entry in match table

Install a driver for the newly found CS5530 companion chip. Most of
this is just housekeeping. We have to set the chip up correctly and
turn off various bits of emulation magic.
