.TH "csio_rnode_fwevt_handler" 9 "csio_rnode_fwevt_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
csio_rnode_fwevt_handler \- Event handler for firmware rnode events.
.SH SYNOPSIS
.B "void" csio_rnode_fwevt_handler
.BI "(struct csio_rnode *rn "  ","
.BI "uint8_t fwevt "  ");"
.SH ARGUMENTS
.IP "rn" 12
rnode
.IP "fwevt" 12
firmware event to handle
