.TH "css_task_iter_next" 9 "css_task_iter_next" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
css_task_iter_next \- return the next task for the iterator
.SH SYNOPSIS
.B "struct task_struct *" css_task_iter_next
.BI "(struct css_task_iter *it "  ");"
.SH ARGUMENTS
.IP "it" 12
the task iterator being iterated
.SH "DESCRIPTION"
The "next" function for task iteration.  \fIit\fP should have been
initialized via \fBcss_task_iter_start\fP.  Returns NULL when the iteration
reaches the end.
