.TH "css_task_iter_start" 9 "css_task_iter_start" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
css_task_iter_start \- initiate task iteration
.SH SYNOPSIS
.B "void" css_task_iter_start
.BI "(struct cgroup_subsys_state *css "  ","
.BI "unsigned int flags "  ","
.BI "struct css_task_iter *it "  ");"
.SH ARGUMENTS
.IP "css" 12
the css to walk tasks of
.IP "flags" 12
CSS_TASK_ITER_* flags
.IP "it" 12
the task iterator to use
.SH "DESCRIPTION"
Initiate iteration through the tasks of \fIcss\fP.  The caller can call
\fBcss_task_iter_next\fP to walk through the tasks until the function
returns NULL.  On completion of iteration, \fBcss_task_iter_end\fP must be
called.
