.TH "css_driver_unregister" 9 "css_driver_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
css_driver_unregister \- unregister a css driver
.SH SYNOPSIS
.B "void" css_driver_unregister
.BI "(struct css_driver *cdrv "  ");"
.SH ARGUMENTS
.IP "cdrv" 12
css driver to unregister
.SH "DESCRIPTION"
This is a wrapper around driver_unregister.
