.TH "ct_atc_create" 9 "ct_atc_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ct_atc_create \- create and initialize a hardware manager
.SH SYNOPSIS
.B "int" ct_atc_create
.BI "(struct snd_card *card "  ","
.BI "struct pci_dev *pci "  ","
.BI "unsigned int rsr "  ","
.BI "unsigned int msr "  ","
.BI "int chip_type "  ","
.BI "unsigned int ssid "  ","
.BI "struct ct_atc **ratc "  ");"
.SH ARGUMENTS
.IP "card" 12
corresponding alsa card object
.IP "pci" 12
corresponding kernel pci device object
.IP "rsr" 12
reference sampling rate
.IP "msr" 12
master sampling rate
.IP "chip_type" 12
CHIPTYP enum values
.IP "ssid" 12
vendor ID (upper 16 bits) and device ID (lower 16 bits)
.IP "ratc" 12
return created object address in it

Creates and initializes a hardware manager.

Creates kmallocated ct_atc structure. Initializes hardware.
Returns 0 if succeeds, or negative error code if fails.
