.TH "cxgb4_smt_release" 9 "cxgb4_smt_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cxgb4_smt_release \- Release SMT entry
.SH SYNOPSIS
.B "void" cxgb4_smt_release
.BI "(struct smt_entry *e "  ");"
.SH ARGUMENTS
.IP "e" 12
smt entry to release
.SH "DESCRIPTION"
Releases ref count and frees up an smt entry from SMT table
