.TH "cxlflash_disk_verify" 9 "cxlflash_disk_verify" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cxlflash_disk_verify \- verifies a LUN is the same and handle size changes
.SH SYNOPSIS
.B "int" cxlflash_disk_verify
.BI "(struct scsi_device *sdev "  ","
.BI "struct dk_cxlflash_verify *verify "  ");"
.SH ARGUMENTS
.IP "sdev" 12
SCSI device associated with LUN.
.IP "verify" 12
Verify ioctl data structure.
.SH "RETURN"
0 on success, -errno on failure
