.TH "cxlflash_worker_thread" 9 "cxlflash_worker_thread" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cxlflash_worker_thread \- work thread handler for the AFU
.SH SYNOPSIS
.B "void" cxlflash_worker_thread
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
Work structure contained within cxlflash associated with host.
.SH "DESCRIPTION"
Handles the following events:
- Link reset which cannot be performed on interrupt context due to
blocking up to a few seconds
- Rescan the host
