.TH "cxlflash_release_chrdev" 9 "cxlflash_release_chrdev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cxlflash_release_chrdev \- release the character device for the host
.SH SYNOPSIS
.B "void" cxlflash_release_chrdev
.BI "(struct cxlflash_cfg *cfg "  ");"
.SH ARGUMENTS
.IP "cfg" 12
Internal structure associated with the host.
