.TH "cxlflash_cxl_mmap" 9 "cxlflash_cxl_mmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cxlflash_cxl_mmap \- mmap handler for adapter file descriptor
.SH SYNOPSIS
.B "int" cxlflash_cxl_mmap
.BI "(struct file *file "  ","
.BI "struct vm_area_struct *vma "  ");"
.SH ARGUMENTS
.IP "file" 12
File installed with adapter file descriptor.
.IP "vma" 12
VM area associated with mapping.
.SH "DESCRIPTION"
Installs local mmap vmops to 'catch' faults for error notification support.
.SH "RETURN"
0 on success, -errno on failure
