.TH "cxlflash_manage_lun" 9 "cxlflash_manage_lun" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cxlflash_manage_lun \- handles LUN management activities
.SH SYNOPSIS
.B "int" cxlflash_manage_lun
.BI "(struct scsi_device *sdev "  ","
.BI "struct dk_cxlflash_manage_lun *manage "  ");"
.SH ARGUMENTS
.IP "sdev" 12
SCSI device associated with LUN.
.IP "manage" 12
Manage ioctl data structure.
.SH "DESCRIPTION"
This routine is used to notify the driver about a LUN's WWID and associate
SCSI devices (sdev) with a global LUN instance. Additionally it serves to
change a LUN's operating mode: legacy or superpipe.
.SH "RETURN"
0 on success, -errno on failure
