.TH "cxlflash_show_port_lun_table" 9 "cxlflash_show_port_lun_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
cxlflash_show_port_lun_table \- queries and presents the port LUN table
.SH SYNOPSIS
.B "ssize_t" cxlflash_show_port_lun_table
.BI "(u32 port "  ","
.BI "struct cxlflash_cfg *cfg "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "port" 12
Desired port for status reporting.
.IP "cfg" 12
Internal structure associated with the host.
.IP "buf" 12
Buffer of length PAGE_SIZE to report back port status in ASCII.
.SH "RETURN"
The size of the ASCII string returned in \fIbuf\fP or -EINVAL.
