.TH "d_drop" 9 "d_drop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
d_drop \- drop a dentry
.SH SYNOPSIS
.B "void" d_drop
.BI "(struct dentry *dentry "  ");"
.SH ARGUMENTS
.IP "dentry" 12
dentry to drop
.SH "DESCRIPTION"
\fBd_drop\fP unhashes the entry from the parent dentry hashes, so that it won't
be found through a VFS lookup any more. Note that this is different from
deleting the dentry - d_delete will try to mark the dentry negative if
possible, giving a successful _negative_ lookup, while d_drop will
just make the cache lookup fail.

\fBd_drop\fP is used mainly for stuff that wants to invalidate a dentry for some
reason (NFS timeouts or autofs deletes).

__d_drop requires dentry->d_lock

___d_drop doesn't mark dentry as "unhashed"
(dentry->d_hash.pprev will be LIST_POISON2, not NULL).
