.TH "d_rehash" 9 "d_rehash" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
d_rehash \- add an entry back to the hash
.SH SYNOPSIS
.B "void" d_rehash
.BI "(struct dentry * entry "  ");"
.SH ARGUMENTS
.IP "entry" 12
dentry to add to the hash
.SH "DESCRIPTION"
Adds a dentry to the hash according to its name.
