.TH "da8xx_cfgchip_register_usb1_clk48" 9 "da8xx_cfgchip_register_usb1_clk48" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
da8xx_cfgchip_register_usb1_clk48 \- Register a new USB 1.1 PHY clock
.SH SYNOPSIS
.B "struct da8xx_usb1_clk48 *" da8xx_cfgchip_register_usb1_clk48
.BI "(struct device *dev "  ","
.BI "struct regmap *regmap "  ");"
.SH ARGUMENTS
.IP "dev" 12
The device
.IP "regmap" 12
The CFGCHIP regmap
