.TH "davinci_spi_bufs" 9 "davinci_spi_bufs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
davinci_spi_bufs \- functions which will handle transfer data
.SH SYNOPSIS
.B "int" davinci_spi_bufs
.BI "(struct spi_device *spi "  ","
.BI "struct spi_transfer *t "  ");"
.SH ARGUMENTS
.IP "spi" 12
spi device on which data transfer to be done
.IP "t" 12
spi transfer in which transfer info is filled
.SH "DESCRIPTION"
This function will put data to be transferred into data register
of SPI controller and then wait until the completion will be marked
by the IRQ Handler.
