.TH "db8500_prcmu_get_reset_code" 9 "db8500_prcmu_get_reset_code" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
db8500_prcmu_get_reset_code \- Retrieve SW reset reason code
.SH SYNOPSIS
.B "u16" db8500_prcmu_get_reset_code
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Retrieves the reset reason code stored by \fBprcmu_system_reset\fP before
last restart.
