.TH "dbg_check_lpt_nodes" 9 "dbg_check_lpt_nodes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dbg_check_lpt_nodes \- check nnodes and pnodes.
.SH SYNOPSIS
.B "int" dbg_check_lpt_nodes
.BI "(struct ubifs_info *c "  ","
.BI "struct ubifs_cnode *cnode "  ","
.BI "int row "  ","
.BI "int col "  ");"
.SH ARGUMENTS
.IP "c" 12
the UBIFS file-system description object
.IP "cnode" 12
next cnode (nnode or pnode) to check
.IP "row" 12
row of cnode (root is zero)
.IP "col" 12
column of cnode (leftmost is zero)
.SH "DESCRIPTION"
This function returns 0 on success and a negative error code on failure.
