.TH "dc_stream_configure_crc" 9 "dc_stream_configure_crc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dc_stream_configure_crc \- Configure CRC capture for the given stream.
.SH SYNOPSIS
.B "bool" dc_stream_configure_crc
.BI "(struct dc *dc "  ","
.BI "struct dc_stream_state *stream "  ","
.BI "struct crc_params *crc_window "  ","
.BI "bool enable "  ","
.BI "bool continuous "  ");"
.SH ARGUMENTS
.IP "dc" 12
DC Object
.IP "stream" 12
The stream to configure CRC on.
.IP "crc_window" 12
CRC window (x/y start/end) information
.IP "enable" 12
Enable CRC if true, disable otherwise.
.IP "continuous" 12
Capture CRC on every frame if true. Otherwise, only capture
once.
.SH "DESCRIPTION"
By default, only CRC0 is configured, and the entire frame is used to
calculate the crc.
