.TH "dccp_ackvec_input" 9 "dccp_ackvec_input" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dccp_ackvec_input \- Register incoming packet in the buffer
.SH SYNOPSIS
.B "void" dccp_ackvec_input
.BI "(struct dccp_ackvec *av "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "av" 12
Ack Vector to register packet to
.IP "skb" 12
Packet to register
