.TH "dccp_feat_entry_new" 9 "dccp_feat_entry_new" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dccp_feat_entry_new \- Central list update routine (called by all others)
.SH SYNOPSIS
.B "struct dccp_feat_entry *" dccp_feat_entry_new
.BI "(struct list_head *head "  ","
.BI "u8 feat "  ","
.BI "bool local "  ");"
.SH ARGUMENTS
.IP "head" 12
list to add to
.IP "feat" 12
feature number
.IP "local" 12
whether the local (1) or remote feature with number \fIfeat\fP is meant
.SH "DESCRIPTION"
This is the only constructor and serves to ensure the above invariants.
