.TH "dccp_feat_nn_get" 9 "dccp_feat_nn_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dccp_feat_nn_get \- Query current/pending value of NN feature
.SH SYNOPSIS
.B "u64" dccp_feat_nn_get
.BI "(struct sock *sk "  ","
.BI "u8 feat "  ");"
.SH ARGUMENTS
.IP "sk" 12
DCCP socket of an established connection
.IP "feat" 12
NN feature number from dccp_feature_numbers
.SH "DESCRIPTION"
For a known NN feature, returns value currently being negotiated, or
current (confirmed) value if no negotiation is going on.
