.TH "debug_object_assert_init" 9 "debug_object_assert_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
debug_object_assert_init \- debug checks when object should be init-ed
.SH SYNOPSIS
.B "void" debug_object_assert_init
.BI "(void *addr "  ","
.BI "const struct debug_obj_descr *descr "  ");"
.SH ARGUMENTS
.IP "addr" 12
address of the object
.IP "descr" 12
pointer to an object specific debug description structure
