.TH "deliver_netinfo_thread" 9 "deliver_netinfo_thread" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
deliver_netinfo_thread \- thread to deliver network status to mostcore
.SH SYNOPSIS
.B "int" deliver_netinfo_thread
.BI "(void *data "  ");"
.SH ARGUMENTS
.IP "data" 12
private data
.SH "DESCRIPTION"
Wait for network status and deliver it to mostcore once it is received
