.TH "dev_get_by_index_rcu" 9 "dev_get_by_index_rcu" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_get_by_index_rcu \- find a device by its ifindex
.SH SYNOPSIS
.B "struct net_device *" dev_get_by_index_rcu
.BI "(struct net *net "  ","
.BI "int ifindex "  ");"
.SH ARGUMENTS
.IP "net" 12
the applicable net namespace
.IP "ifindex" 12
index of device

Search for an interface by index. Returns NULL if the device
is not found or a pointer to the device. The device has not
had its reference counter increased so the caller must be careful
about locking. The caller must hold RCU lock.
