.TH "dev_pm_opp_unregister_set_opp_helper" 9 "dev_pm_opp_unregister_set_opp_helper" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_pm_opp_unregister_set_opp_helper \- Releases resources blocked for set_opp helper
.SH SYNOPSIS
.B "void" dev_pm_opp_unregister_set_opp_helper
.BI "(struct opp_table *opp_table "  ");"
.SH ARGUMENTS
.IP "opp_table" 12
OPP table returned from \fBdev_pm_opp_register_set_opp_helper\fP.
.SH "DESCRIPTION"
Release resources blocked for platform specific set_opp helper.
