.TH "dev_pm_opp_get_max_transition_latency" 9 "dev_pm_opp_get_max_transition_latency" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_pm_opp_get_max_transition_latency \- Get max transition latency in nanoseconds
.SH SYNOPSIS
.B "unsigned long" dev_pm_opp_get_max_transition_latency
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device for which we do this operation
.SH "RETURN"
This function returns the max transition latency, in nanoseconds, to
switch from one OPP to other.
