.TH "dev_pm_opp_sync_regulators" 9 "dev_pm_opp_sync_regulators" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dev_pm_opp_sync_regulators \- Sync state of voltage regulators
.SH SYNOPSIS
.B "int" dev_pm_opp_sync_regulators
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device for which we do this operation
.SH "DESCRIPTION"
Sync voltage state of the OPP table regulators.
.SH "RETURN"
0 on success or a negative error value.
