.TH "devfreq_monitor_resume" 9 "devfreq_monitor_resume" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devfreq_monitor_resume \- Resume load monitoring of a devfreq instance
.SH SYNOPSIS
.B "void" devfreq_monitor_resume
.BI "(struct devfreq *devfreq "  ");"
.SH ARGUMENTS
.IP "devfreq" 12
the devfreq instance.
.SH "DESCRIPTION"
Helper function to resume devfreq device load monitoring. Function
to be called from governor in response to DEVFREQ_GOV_RESUME
event or when polling interval is set to non-zero.
