.TH "device_unblock_probing" 9 "device_unblock_probing" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
device_unblock_probing \- Unblock/enable device's probes
.SH SYNOPSIS
.B "void" device_unblock_probing
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

It will restore normal behavior and trigger re-probing of deferred
devices.
