.TH "device_alloc" 9 "device_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
device_alloc \- Allocate a new device instance. This create the devices instance and sets up all the data items. The adapter instance is required to obtain confiuration information for this device. This does *not* add this device to the adapters device list.
.SH SYNOPSIS
.B "struct DeviceCtlBlk *" device_alloc
.BI "(struct AdapterCtlBlk *acb "  ","
.BI "u8 target "  ","
.BI "u8 lun "  ");"
.SH ARGUMENTS
.IP "acb" 12
The adapter to obtain configuration information from.
.IP "target" 12
The target for the new device.
.IP "lun" 12
The lun for the new device.
.SH "DESCRIPTION"
Return the new device if successful or NULL on failure.
