.TH "devlink_param_value_str_fill" 9 "devlink_param_value_str_fill" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devlink_param_value_str_fill \- Safely fill-up the string preventing from overflow of the preallocated buffer
.SH SYNOPSIS
.B "void" devlink_param_value_str_fill
.BI "(union devlink_param_value *dst_val "  ","
.BI "const char *src "  ");"
.SH ARGUMENTS
.IP "dst_val" 12
destination devlink_param_value
.IP "src" 12
source buffer
