.TH "devlink_port_param_driverinit_value_get" 9 "devlink_port_param_driverinit_value_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devlink_port_param_driverinit_value_get \- get configuration parameter value for driver initializing
.SH SYNOPSIS
.B "int" devlink_port_param_driverinit_value_get
.BI "(struct devlink_port *devlink_port "  ","
.BI "u32 param_id "  ","
.BI "union devlink_param_value *init_val "  ");"
.SH ARGUMENTS
.IP "devlink_port" 12
devlink_port
.IP "param_id" 12
parameter ID
.IP "init_val" 12
value of parameter in driverinit configuration mode

This function should be used by the driver to get driverinit
configuration for initialization after reload command.
