.TH "devm_extcon_dev_free" 9 "devm_extcon_dev_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_extcon_dev_free \- Resource-managed extcon_dev_unregister()
.SH SYNOPSIS
.B "void" devm_extcon_dev_free
.BI "(struct device *dev "  ","
.BI "struct extcon_dev *edev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device owning the extcon device being created
.IP "edev" 12
the extcon device to be freed
.SH "DESCRIPTION"
Free the memory that is allocated with \fBdevm_extcon_dev_allocate\fP
function.
