.TH "devm_release_resource" 9 "devm_release_resource" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_release_resource \- release a previously requested resource
.SH SYNOPSIS
.B "void" devm_release_resource
.BI "(struct device *dev "  ","
.BI "struct resource *new "  ");"
.SH ARGUMENTS
.IP "dev" 12
device for which to release the resource
.IP "new" 12
descriptor of the resource to release
.SH "DESCRIPTION"
Releases a resource previously requested using \fBdevm_request_resource\fP.
