.TH "devm_free_irq" 9 "devm_free_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_free_irq \- free an interrupt
.SH SYNOPSIS
.B "void" devm_free_irq
.BI "(struct device *dev "  ","
.BI "unsigned int irq "  ","
.BI "void *dev_id "  ");"
.SH ARGUMENTS
.IP "dev" 12
device to free interrupt for
.IP "irq" 12
Interrupt line to free
.IP "dev_id" 12
Device identity to free

Except for the extra \fIdev\fP argument, this function takes the
same arguments and performs the same function as \fBfree_irq\fP.
This function instead of \fBfree_irq\fP should be used to manually
free IRQs allocated with \fBdevm_request_irq\fP.
