.TH "devm_nvmem_device_get" 9 "devm_nvmem_device_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_nvmem_device_get \- Get nvmem cell of device form a given id
.SH SYNOPSIS
.B "struct nvmem_device *" devm_nvmem_device_get
.BI "(struct device *dev "  ","
.BI "const char *id "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device that requests the nvmem device.
.IP "id" 12
name id for the requested nvmem device.
.SH "RETURN"
\fBERR_PTR\fP on error or a valid pointer to a struct nvmem_cell
on success.  The nvmem_cell will be freed by the automatically once the
device is freed.
