.TH "devm_spi_mem_dirmap_destroy" 9 "devm_spi_mem_dirmap_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_spi_mem_dirmap_destroy \- Destroy a direct mapping descriptor attached to a device
.SH SYNOPSIS
.B "void" devm_spi_mem_dirmap_destroy
.BI "(struct device *dev "  ","
.BI "struct spi_mem_dirmap_desc *desc "  ");"
.SH ARGUMENTS
.IP "dev" 12
device the dirmap desc is attached to
.IP "desc" 12
the direct mapping descriptor to destroy
.SH "DESCRIPTION"
devm_ variant of the \fBspi_mem_dirmap_destroy\fP function. See
\fBspi_mem_dirmap_destroy\fP for more details.
