.TH "devm_gpiod_unhinge" 9 "devm_gpiod_unhinge" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_gpiod_unhinge \- Remove resource management from a gpio descriptor
.SH SYNOPSIS
.B "void" devm_gpiod_unhinge
.BI "(struct device *dev "  ","
.BI "struct gpio_desc *desc "  ");"
.SH ARGUMENTS
.IP "dev" 12
GPIO consumer
.IP "desc" 12
GPIO descriptor to remove resource management from
.SH "DESCRIPTION"
Remove resource management from a GPIO descriptor. This is needed when
you want to hand over lifecycle management of a descriptor to another
mechanism.
