.TH "devm_fpga_mgr_register" 9 "devm_fpga_mgr_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_fpga_mgr_register \- resource managed variant of fpga_mgr_register()
.SH SYNOPSIS
.B "int" devm_fpga_mgr_register
.BI "(struct device *dev "  ","
.BI "struct fpga_manager *mgr "  ");"
.SH ARGUMENTS
.IP "dev" 12
managing device for this FPGA manager
.IP "mgr" 12
fpga manager struct
.SH "DESCRIPTION"
This is the devres variant of \fBfpga_mgr_register\fP for which the unregister
function will be called automatically when the managing device is detached.
