.TH "devm_blk_ksm_init" 9 "devm_blk_ksm_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_blk_ksm_init \- Resource-managed blk_ksm_init()
.SH SYNOPSIS
.B "int" devm_blk_ksm_init
.BI "(struct device *dev "  ","
.BI "struct blk_keyslot_manager *ksm "  ","
.BI "unsigned int num_slots "  ");"
.SH ARGUMENTS
.IP "dev" 12
The device which owns the blk_keyslot_manager.
.IP "ksm" 12
The blk_keyslot_manager to initialize.
.IP "num_slots" 12
The number of key slots to manage.
.SH "DESCRIPTION"
Like \fBblk_ksm_init\fP, but causes \fBblk_ksm_destroy\fP to be called automatically
on driver detach.
.SH "RETURN"
0 on success, or else a negative error code.
