.TH "devm_pwm_get" 9 "devm_pwm_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devm_pwm_get \- resource managed pwm_get()
.SH SYNOPSIS
.B "struct pwm_device *" devm_pwm_get
.BI "(struct device *dev "  ","
.BI "const char *con_id "  ");"
.SH ARGUMENTS
.IP "dev" 12
device for PWM consumer
.IP "con_id" 12
consumer name
.SH "DESCRIPTION"
This function performs like \fBpwm_get\fP but the acquired PWM device will
automatically be released on driver detach.
.SH "RETURN"
A pointer to the requested PWM device or an \fBERR_PTR\fP-encoded
error code on failure.
