.TH "devpts_pty_kill" 9 "devpts_pty_kill" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
devpts_pty_kill \- - remove inode form /dev/pts/
.SH SYNOPSIS
.B "void" devpts_pty_kill
.BI "(struct dentry *dentry "  ");"
.SH ARGUMENTS
.IP "dentry" 12
-- undescribed --
.SH "DESCRIPTION"
This is an inverse operation of devpts_pty_new.
