.TH "dfl_fme_destroy_region" 9 "dfl_fme_destroy_region" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dfl_fme_destroy_region \- destroy fme region
.SH SYNOPSIS
.B "void" dfl_fme_destroy_region
.BI "(struct dfl_fme_region *fme_region "  ");"
.SH ARGUMENTS
.IP "fme_region" 12
fme region to destroy
