.TH "dfll_pwm_set_output_enabled" 9 "dfll_pwm_set_output_enabled" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dfll_pwm_set_output_enabled \- enable/disable PWM voltage requests
.SH SYNOPSIS
.B "int" dfll_pwm_set_output_enabled
.BI "(struct tegra_dfll *td "  ","
.BI "bool enable "  ");"
.SH ARGUMENTS
.IP "td" 12
DFLL instance
.IP "enable" 12
whether to enable or disable the PWM voltage requests
.SH "DESCRIPTION"
Set the master enable control for PWM control value updates. If disabled,
then the PWM signal is not driven. Also configure the PWM output pad
to the appropriate state.
