.TH "dfs_cache_update_vol" 9 "dfs_cache_update_vol" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dfs_cache_update_vol \- update vol info in DFS cache after failover
.SH SYNOPSIS
.B "int" dfs_cache_update_vol
.BI "(const char *fullpath "  ","
.BI "struct TCP_Server_Info *server "  ");"
.SH ARGUMENTS
.IP "fullpath" 12
fullpath to look up in volume list.
.IP "server" 12
TCP ses pointer.
.SH "DESCRIPTION"
Return zero if volume was updated, otherwise non-zero.
