.TH "dfs_cache_get_tgt_referral" 9 "dfs_cache_get_tgt_referral" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dfs_cache_get_tgt_referral \- returns a DFS referral (@ref) from a given target iterator (@it).
.SH SYNOPSIS
.B "int" dfs_cache_get_tgt_referral
.BI "(const char *path "  ","
.BI "const struct dfs_cache_tgt_iterator *it "  ","
.BI "struct dfs_info3_param *ref "  ");"
.SH ARGUMENTS
.IP "path" 12
path to lookup in DFS referral cache.
.IP "it" 12
DFS target iterator.
.IP "ref" 12
DFS referral pointer to set up the gathered information.
.SH "DESCRIPTION"
Return zero if the DFS referral was set up correctly, otherwise non-zero.
