.TH "diag_ftp_startup" 9 "diag_ftp_startup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
diag_ftp_startup \- startup of FTP services, when running on z/VM
.SH SYNOPSIS
.B "int" diag_ftp_startup
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
0 on success, else an (negative) error code
