.TH "disable_hardirq" 9 "disable_hardirq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
disable_hardirq \- disables an irq and waits for hardirq completion
.SH SYNOPSIS
.B "bool" disable_hardirq
.BI "(unsigned int irq "  ");"
.SH ARGUMENTS
.IP "irq" 12
Interrupt to disable

Disable the selected interrupt line.  Enables and Disables are
nested.
This function waits for any pending hard IRQ handlers for this
interrupt to complete before returning. If you use this function while
holding a resource the hard IRQ handler may need you will deadlock.

When used to optimistically disable an interrupt from atomic context
the return value must be checked.
.SH "RETURN"
false if a threaded handler is active.

This function may be called - with care - from IRQ context.
