.TH "dm_parse_devices" 9 "dm_parse_devices" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dm_parse_devices \- parse "dm-mod.create=" argument
.SH SYNOPSIS
.B "int" dm_parse_devices
.BI "(struct list_head *devices "  ","
.BI "char *str "  ");"
.SH ARGUMENTS
.IP "devices" 12
list of struct dm_device to store the parsed information.
.IP "str" 12
the pointer to a string with the format:
<device>[;<device>+]
