.TH "dma_tasklet" 9 "dma_tasklet" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dma_tasklet \- DMA IRQ tasklet
.SH SYNOPSIS
.B "void" dma_tasklet
.BI "(struct tasklet_struct *t "  ");"
.SH ARGUMENTS
.IP "t" 12
tasklet argument (bam controller structure)
.SH "DESCRIPTION"
Sets up next DMA operation and then processes all completed transactions
