.TH "dma_fifo_out_complete" 9 "dma_fifo_out_complete" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dma_fifo_out_complete \- marks pended dma as completed
.SH SYNOPSIS
.B "int" dma_fifo_out_complete
.BI "(struct dma_fifo *fifo "  ","
.BI "struct dma_pending *complete "  ");"
.SH ARGUMENTS
.IP "fifo" 12
address of in-place "struct dma_fifo" which was read from
.IP "complete" 12
address of structure for previously pended dma to mark completed
