.TH "dma_resv_list_alloc" 9 "dma_resv_list_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dma_resv_list_alloc \- allocate fence list
.SH SYNOPSIS
.B "struct dma_resv_list *" dma_resv_list_alloc
.BI "(unsigned int shared_max "  ");"
.SH ARGUMENTS
.IP "shared_max" 12
number of fences we need space for
.SH "DESCRIPTION"
Allocate a new dma_resv_list and make sure to correctly initialize
shared_max.
