.TH "dns_resolve_server_name_to_ip" 9 "dns_resolve_server_name_to_ip" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dns_resolve_server_name_to_ip \- Resolve UNC server name to ip address.
.SH SYNOPSIS
.B "int" dns_resolve_server_name_to_ip
.BI "(const char *unc "  ","
.BI "char **ip_addr "  ");"
.SH ARGUMENTS
.IP "unc" 12
UNC path specifying the server (with '/' as delimiter)
.IP "ip_addr" 12
Where to return the IP address.
.SH "DESCRIPTION"
The IP address will be returned in string form, and the caller is
responsible for freeing it.

Returns length of result on success, -ve on error.
