.TH "do_disable_cpu_turbo" 9 "do_disable_cpu_turbo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
do_disable_cpu_turbo \- internal turbo disable function
.SH SYNOPSIS
.B "void" do_disable_cpu_turbo
.BI "(void *data "  ");"
.SH ARGUMENTS
.IP "data" 12
unused
.SH "DESCRIPTION"
Internal function for actually updating MSRs.  When we enable/disable
turbo, we need to do it on each CPU; this function is the one called
by \fBon_each_cpu\fP when needed.
