.TH "do_identify" 9 "do_identify" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
do_identify \- identify a drive
.SH SYNOPSIS
.B "void" do_identify
.BI "(ide_drive_t *drive "  ","
.BI "u8 cmd "  ","
.BI "u16 *id "  ");"
.SH ARGUMENTS
.IP "drive" 12
drive to identify 
.IP "cmd" 12
command used
.IP "id" 12
buffer for IDENTIFY data

Called when we have issued a drive identify command to
read and parse the results. This function is run with
interrupts disabled. 
