.TH "dp_ctrl_host_deinit" 9 "dp_ctrl_host_deinit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dp_ctrl_host_deinit \- Uninitialize DP controller
.SH SYNOPSIS
.B "void" dp_ctrl_host_deinit
.BI "(struct dp_ctrl *dp_ctrl "  ");"
.SH ARGUMENTS
.IP "dp_ctrl" 12
Display Port Driver data
.SH "DESCRIPTION"
Perform required steps to uninitialize DP controller
and its resources.
