.TH "dp_catalog_ctrl_reset" 9 "dp_catalog_ctrl_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dp_catalog_ctrl_reset \- reset DP controller
.SH SYNOPSIS
.B "void" dp_catalog_ctrl_reset
.BI "(struct dp_catalog *dp_catalog "  ");"
.SH ARGUMENTS
.IP "dp_catalog" 12
DP catalog structure
.SH "RETURN"
void
.SH "DESCRIPTION"
This function reset the DP controller
.SH "NOTE"
reset DP controller will also clear any pending HPD related interrupts
