.TH "dpni_set_tx_shaping" 9 "dpni_set_tx_shaping" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dpni_set_tx_shaping \- Set the transmit shaping
.SH SYNOPSIS
.B "int" dpni_set_tx_shaping
.BI "(struct fsl_mc_io *mc_io "  ","
.BI "u32 cmd_flags "  ","
.BI "u16 token "  ","
.BI "const struct dpni_tx_shaping_cfg *tx_cr_shaper "  ","
.BI "const struct dpni_tx_shaping_cfg *tx_er_shaper "  ","
.BI "int coupled "  ");"
.SH ARGUMENTS
.IP "mc_io" 12
Pointer to MC portal's I/O object
.IP "cmd_flags" 12
Command flags; one or more of 'MC_CMD_FLAG_'
.IP "token" 12
Token of DPNI object
.IP "tx_cr_shaper" 12
TX committed rate shaping configuration
.IP "tx_er_shaper" 12
TX excess rate shaping configuration
.IP "coupled" 12
Committed and excess rate shapers are coupled
.SH "RETURN"
'0' on Success; Error code otherwise.
