.TH "dprc_probe" 9 "dprc_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dprc_probe \- callback invoked when a DPRC is being bound to this driver
.SH SYNOPSIS
.B "int" dprc_probe
.BI "(struct fsl_mc_device *mc_dev "  ");"
.SH ARGUMENTS
.IP "mc_dev" 12
Pointer to fsl-mc device representing a DPRC
.SH "DESCRIPTION"
It opens the physical DPRC in the MC.
It scans the DPRC to discover the MC objects contained in it.
It creates the interrupt pool for the MC bus associated with the DPRC.
It configures the interrupts for the DPRC device itself.
