.TH "dprc_open" 9 "dprc_open" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dprc_open \- Open DPRC object for use
.SH SYNOPSIS
.B "int" dprc_open
.BI "(struct fsl_mc_io *mc_io "  ","
.BI "u32 cmd_flags "  ","
.BI "int container_id "  ","
.BI "u16 *token "  ");"
.SH ARGUMENTS
.IP "mc_io" 12
Pointer to MC portal's I/O object
.IP "cmd_flags" 12
Command flags; one or more of 'MC_CMD_FLAG_'
.IP "container_id" 12
Container ID to open
.IP "token" 12
Returned token of DPRC object
.SH "RETURN"
'0' on Success; Error code otherwise.
.SH "DESCRIPTION"
\fIwarning\fP     Required before any operation on the object.
