.TH "dpu_vbif_set_ot_limit" 9 "dpu_vbif_set_ot_limit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dpu_vbif_set_ot_limit \- set OT based on usecase & configuration parameters
.SH SYNOPSIS
.B "void" dpu_vbif_set_ot_limit
.BI "(struct dpu_kms *dpu_kms "  ","
.BI "struct dpu_vbif_set_ot_params *params "  ");"
.SH ARGUMENTS
.IP "dpu_kms" 12
DPU handler
.IP "params" 12
Pointer to usecase parameters
.SH "DESCRIPTION"
Note this function would block waiting for bus halt.
