.TH "dpu_hw_blk_get" 9 "dpu_hw_blk_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dpu_hw_blk_get \- get hw_blk from free pool
.SH SYNOPSIS
.B "struct dpu_hw_blk *" dpu_hw_blk_get
.BI "(struct dpu_hw_blk *hw_blk "  ","
.BI "u32 type "  ","
.BI "int id "  ");"
.SH ARGUMENTS
.IP "hw_blk" 12
if specified, increment reference count only
.IP "type" 12
if hw_blk is not specified, allocate the next available of this type
.IP "id" 12
if specified (>= 0), allocate the given instance of the above type
.SH "RETURN"
pointer to hw block object
