.TH "drbd_bm_write" 9 "drbd_bm_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drbd_bm_write \- Write the whole bitmap to its on disk location.
.SH SYNOPSIS
.B "int" drbd_bm_write
.BI "(struct drbd_device *device "  ");"
.SH ARGUMENTS
.IP "device" 12
DRBD device.
.SH "DESCRIPTION"
Will only write pages that have changed since last IO.
