.TH "drbd_insert_interval" 9 "drbd_insert_interval" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drbd_insert_interval \- insert a new interval into a tree
.SH SYNOPSIS
.B "bool" drbd_insert_interval
.BI "(struct rb_root *root "  ","
.BI "struct drbd_interval *this "  ");"
.SH ARGUMENTS
.IP "root" 12
-- undescribed --
.IP "this" 12
-- undescribed --
