.TH "drbd_send_current_state" 9 "drbd_send_current_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drbd_send_current_state \- Sends the drbd state to the peer
.SH SYNOPSIS
.B "int" drbd_send_current_state
.BI "(struct drbd_peer_device *peer_device "  ");"
.SH ARGUMENTS
.IP "peer_device" 12
DRBD peer device.
