.TH "drbd_bm_write_lazy" 9 "drbd_bm_write_lazy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drbd_bm_write_lazy \- Write bitmap pages 0 to @upper_idx-1, if they have changed.
.SH SYNOPSIS
.B "int" drbd_bm_write_lazy
.BI "(struct drbd_device *device "  ","
.BI "unsigned upper_idx "  ");"
.SH ARGUMENTS
.IP "device" 12
DRBD device.
.IP "upper_idx" 12
0: write all changed pages; +ve: page index to stop scanning for changed pages
