.TH "drm_mode_object_put" 9 "drm_mode_object_put" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_mode_object_put \- release a mode object reference
.SH SYNOPSIS
.B "void" drm_mode_object_put
.BI "(struct drm_mode_object *obj "  ");"
.SH ARGUMENTS
.IP "obj" 12
DRM mode object
.SH "DESCRIPTION"
This function decrements the object's refcount if it is a refcounted modeset
object. It is a no-op on any other object. This is used to drop references
acquired with \fBdrm_mode_object_get\fP.
