.TH "drm_atomic_get_private_obj_state" 9 "drm_atomic_get_private_obj_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_atomic_get_private_obj_state \- get private object state
.SH SYNOPSIS
.B "struct drm_private_state *" drm_atomic_get_private_obj_state
.BI "(struct drm_atomic_state *state "  ","
.BI "struct drm_private_obj *obj "  ");"
.SH ARGUMENTS
.IP "state" 12
global atomic state
.IP "obj" 12
private object to get the state for
.SH "DESCRIPTION"
This function returns the private object state for the given private object,
allocating the state if needed. It will also grab the relevant private
object lock to make sure that the state is consistent.

Either the allocated state or the error code encoded into a pointer.
.SH "RETURN"
