.TH "drm_crtc_vblank_put" 9 "drm_crtc_vblank_put" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_crtc_vblank_put \- give up ownership of vblank events
.SH SYNOPSIS
.B "void" drm_crtc_vblank_put
.BI "(struct drm_crtc *crtc "  ");"
.SH ARGUMENTS
.IP "crtc" 12
which counter to give up
.SH "DESCRIPTION"
Release ownership of a given vblank counter, turning off interrupts
if possible. Disable interrupts after drm_vblank_offdelay milliseconds.
