.TH "drm_mm_takedown" 9 "drm_mm_takedown" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_mm_takedown \- clean up a drm_mm allocator
.SH SYNOPSIS
.B "void" drm_mm_takedown
.BI "(struct drm_mm *mm "  ");"
.SH ARGUMENTS
.IP "mm" 12
drm_mm allocator to clean up
.SH "DESCRIPTION"
Note that it is a bug to call this function on an allocator which is not
clean.
