.TH "drm_display_mode_from_cea_vic" 9 "drm_display_mode_from_cea_vic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_display_mode_from_cea_vic \- return a mode for CEA VIC
.SH SYNOPSIS
.B "struct drm_display_mode *" drm_display_mode_from_cea_vic
.BI "(struct drm_device *dev "  ","
.BI "u8 video_code "  ");"
.SH ARGUMENTS
.IP "dev" 12
DRM device
.IP "video_code" 12
CEA VIC of the mode
.SH "DESCRIPTION"
Creates a new mode matching the specified CEA VIC.
.SH "RETURN"
A new drm_display_mode on success or NULL on failure
