.TH "drm_atomic_private_obj_init" 9 "drm_atomic_private_obj_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_atomic_private_obj_init \- initialize private object
.SH SYNOPSIS
.B "void" drm_atomic_private_obj_init
.BI "(struct drm_device *dev "  ","
.BI "struct drm_private_obj *obj "  ","
.BI "struct drm_private_state *state "  ","
.BI "const struct drm_private_state_funcs *funcs "  ");"
.SH ARGUMENTS
.IP "dev" 12
DRM device this object will be attached to
.IP "obj" 12
private object
.IP "state" 12
initial private object state
.IP "funcs" 12
pointer to the struct of function pointers that identify the object
type
.SH "DESCRIPTION"
Initialize the private object, which can be embedded into any
driver private object that needs its own atomic state.
