.TH "drm_connector_attach_tv_margin_properties" 9 "drm_connector_attach_tv_margin_properties" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_connector_attach_tv_margin_properties \- attach TV connector margin properties
.SH SYNOPSIS
.B "void" drm_connector_attach_tv_margin_properties
.BI "(struct drm_connector *connector "  ");"
.SH ARGUMENTS
.IP "connector" 12
DRM connector
.SH "DESCRIPTION"
Called by a driver when it needs to attach TV margin props to a connector.
Typically used on SDTV and HDMI connectors.
