.TH "drm_gem_ttm_vunmap" 9 "drm_gem_ttm_vunmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_gem_ttm_vunmap \- vunmap &ttm_buffer_object
.SH SYNOPSIS
.B "void" drm_gem_ttm_vunmap
.BI "(struct drm_gem_object *gem "  ","
.BI "struct dma_buf_map *map "  ");"
.SH ARGUMENTS
.IP "gem" 12
GEM object.
.IP "map" 12
dma-buf mapping.
.SH "DESCRIPTION"
Unmaps a GEM object with \fBttm_bo_vunmap\fP. This function can be used as
\fIdrm_gem_object_funcs.vmap\fP callback.
