.TH "drm_dp_lttpr_max_link_rate" 9 "drm_dp_lttpr_max_link_rate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_dp_lttpr_max_link_rate \- get the maximum link rate supported by all LTTPRs
.SH SYNOPSIS
.B "int" drm_dp_lttpr_max_link_rate
.BI "(const u8 caps[DP_LTTPR_COMMON_CAP_SIZE] "  ");"
.SH ARGUMENTS
.IP "caps" 12
LTTPR common capabilities
.SH "DESCRIPTION"
Returns the maximum link rate supported by all detected LTTPRs.
