.TH "drm_mode_object_get" 9 "drm_mode_object_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_mode_object_get \- acquire a mode object reference
.SH SYNOPSIS
.B "void" drm_mode_object_get
.BI "(struct drm_mode_object *obj "  ");"
.SH ARGUMENTS
.IP "obj" 12
DRM mode object
.SH "DESCRIPTION"
This function increments the object's refcount if it is a refcounted modeset
object. It is a no-op on any other object. References should be dropped again
by calling \fBdrm_mode_object_put\fP.
