.TH "drm_bridge_hpd_notify" 9 "drm_bridge_hpd_notify" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_bridge_hpd_notify \- notify hot plug detection events
.SH SYNOPSIS
.B "void" drm_bridge_hpd_notify
.BI "(struct drm_bridge *bridge "  ","
.BI "enum drm_connector_status status "  ");"
.SH ARGUMENTS
.IP "bridge" 12
bridge control structure
.IP "status" 12
output connection status
.SH "DESCRIPTION"
Bridge drivers shall call this function to report hot plug events when they
detect a change in the output status, when hot plug detection has been
enabled by \fBdrm_bridge_hpd_enable\fP.

This function shall be called in a context that can sleep.
