.TH "drm_gem_vram_object_vmap" 9 "drm_gem_vram_object_vmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_gem_vram_object_vmap \-  Implements &struct drm_gem_object_funcs.vmap
.SH SYNOPSIS
.B "int" drm_gem_vram_object_vmap
.BI "(struct drm_gem_object *gem "  ","
.BI "struct dma_buf_map *map "  ");"
.SH ARGUMENTS
.IP "gem" 12
The GEM object to map
.IP "map" 12
Returns the kernel virtual address of the VRAM GEM object's backing
store.
.SH "RETURN"
0 on success, or a negative error code otherwise.
