.TH "drm_gem_dma_resv_wait" 9 "drm_gem_dma_resv_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_gem_dma_resv_wait \- Wait on GEM object's reservation's objects shared and/or exclusive fences.
.SH SYNOPSIS
.B "long" drm_gem_dma_resv_wait
.BI "(struct drm_file *filep "  ","
.BI "u32 handle "  ","
.BI "bool wait_all "  ","
.BI "unsigned long timeout "  ");"
.SH ARGUMENTS
.IP "filep" 12
DRM file private date
.IP "handle" 12
userspace handle
.IP "wait_all" 12
if true, wait on all fences, else wait on just exclusive fence
.IP "timeout" 12
timeout value in jiffies or zero to return immediately
.SH "RETURN"
.SH "DESCRIPTION"
Returns -ERESTARTSYS if interrupted, 0 if the wait timed out, or
greater than 0 on success.
