.TH "drm_prime_get_contiguous_size" 9 "drm_prime_get_contiguous_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_prime_get_contiguous_size \- returns the contiguous size of the buffer
.SH SYNOPSIS
.B "unsigned long" drm_prime_get_contiguous_size
.BI "(struct sg_table *sgt "  ");"
.SH ARGUMENTS
.IP "sgt" 12
sg_table describing the buffer to check
.SH "DESCRIPTION"
This helper calculates the contiguous size in the DMA address space
of the the buffer described by the provided sg_table.

This is useful for implementing
\fIdrm_gem_object_funcs.gem_prime_import_sg_table\fP.
