.TH "drm_panel_bridge_remove" 9 "drm_panel_bridge_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_panel_bridge_remove \- Unregisters and frees a drm_bridge created by drm_panel_bridge_add().
.SH SYNOPSIS
.B "void" drm_panel_bridge_remove
.BI "(struct drm_bridge *bridge "  ");"
.SH ARGUMENTS
.IP "bridge" 12
The drm_bridge being freed.
