.TH "drm_debugfs_create_files" 9 "drm_debugfs_create_files" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_debugfs_create_files \- Initialize a given set of debugfs files for DRM minor
.SH SYNOPSIS
.B "void" drm_debugfs_create_files
.BI "(const struct drm_info_list *files "  ","
.BI "int count "  ","
.BI "struct dentry *root "  ","
.BI "struct drm_minor *minor "  ");"
.SH ARGUMENTS
.IP "files" 12
The array of files to create
.IP "count" 12
The number of files given
.IP "root" 12
DRI debugfs dir entry.
.IP "minor" 12
device minor number
.SH "DESCRIPTION"
Create a given set of debugfs files represented by an array of
\fIstruct drm_info_list\fP in the given root directory. These files will be removed
automatically on \fBdrm_debugfs_cleanup\fP.
