.TH "drm_flip_work_queue_task" 9 "drm_flip_work_queue_task" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_flip_work_queue_task \- queue a specific task
.SH SYNOPSIS
.B "void" drm_flip_work_queue_task
.BI "(struct drm_flip_work *work "  ","
.BI "struct drm_flip_task *task "  ");"
.SH ARGUMENTS
.IP "work" 12
the flip-work
.IP "task" 12
the task to handle
.SH "DESCRIPTION"
Queues task, that will later be run (passed back to drm_flip_func_t
func) on a work queue after \fBdrm_flip_work_commit\fP is called.
