.TH "drm_event_cancel_free" 9 "drm_event_cancel_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_event_cancel_free \- free a DRM event and release its space
.SH SYNOPSIS
.B "void" drm_event_cancel_free
.BI "(struct drm_device *dev "  ","
.BI "struct drm_pending_event *p "  ");"
.SH ARGUMENTS
.IP "dev" 12
DRM device
.IP "p" 12
tracking structure for the pending event
.SH "DESCRIPTION"
This function frees the event \fIp\fP initialized with \fBdrm_event_reserve_init\fP
and releases any allocated space. It is used to cancel an event when the
nonblocking operation could not be submitted and needed to be aborted.
