.TH "drm_modeset_lock_single_interruptible" 9 "drm_modeset_lock_single_interruptible" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_modeset_lock_single_interruptible \- take a single modeset lock
.SH SYNOPSIS
.B "int" drm_modeset_lock_single_interruptible
.BI "(struct drm_modeset_lock *lock "  ");"
.SH ARGUMENTS
.IP "lock" 12
lock to take
.SH "DESCRIPTION"
This function behaves as \fBdrm_modeset_lock\fP with a NULL context,
but performs interruptible waits.

This function returns 0 on success, or -ERESTARTSYS when interrupted.
