.TH "drm_vram_mm_debugfs_init" 9 "drm_vram_mm_debugfs_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_vram_mm_debugfs_init \- Register VRAM MM debugfs file.
.SH SYNOPSIS
.B "void" drm_vram_mm_debugfs_init
.BI "(struct drm_minor *minor "  ");"
.SH ARGUMENTS
.IP "minor" 12
drm minor device.
