.TH "drm_dev_has_vblank" 9 "drm_dev_has_vblank" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_dev_has_vblank \- test if vblanking has been initialized for a device
.SH SYNOPSIS
.B "bool" drm_dev_has_vblank
.BI "(const struct drm_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device
.SH "DESCRIPTION"
Drivers may call this function to test if vblank support is
initialized for a device. For most hardware this means that vblanking
can also be enabled.

Atomic helpers use this function to initialize
\fIdrm_crtc_state.no_vblank\fP. See also \fBdrm_atomic_helper_check_modeset\fP.
.SH "RETURN"
True if vblanking has been initialized for the given device, false
otherwise.
