.TH "drm_fb_helper_debug_leave" 9 "drm_fb_helper_debug_leave" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_fb_helper_debug_leave \- implementation for &fb_ops.fb_debug_leave
.SH SYNOPSIS
.B "int" drm_fb_helper_debug_leave
.BI "(struct fb_info *info "  ");"
.SH ARGUMENTS
.IP "info" 12
fbdev registered by the helper
