.TH "drm_crtc_check_viewport" 9 "drm_crtc_check_viewport" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_crtc_check_viewport \- Checks that a framebuffer is big enough for the CRTC viewport
.SH SYNOPSIS
.B "int" drm_crtc_check_viewport
.BI "(const struct drm_crtc *crtc "  ","
.BI "int x "  ","
.BI "int y "  ","
.BI "const struct drm_display_mode *mode "  ","
.BI "const struct drm_framebuffer *fb "  ");"
.SH ARGUMENTS
.IP "crtc" 12
CRTC that framebuffer will be displayed on
.IP "x" 12
x panning
.IP "y" 12
y panning
.IP "mode" 12
mode that framebuffer will be displayed under
.IP "fb" 12
framebuffer to check size of
