.TH "drm_self_refresh_helper_init" 9 "drm_self_refresh_helper_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_self_refresh_helper_init \- Initializes self refresh helpers for a crtc
.SH SYNOPSIS
.B "int" drm_self_refresh_helper_init
.BI "(struct drm_crtc *crtc "  ");"
.SH ARGUMENTS
.IP "crtc" 12
the crtc which supports self refresh supported displays
.SH "DESCRIPTION"
Returns zero if successful or -errno on failure
