.TH "drm_plane_create_alpha_property" 9 "drm_plane_create_alpha_property" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
drm_plane_create_alpha_property \- create a new alpha property
.SH SYNOPSIS
.B "int" drm_plane_create_alpha_property
.BI "(struct drm_plane *plane "  ");"
.SH ARGUMENTS
.IP "plane" 12
drm plane
.SH "DESCRIPTION"
This function creates a generic, mutable, alpha property and enables support
for it in the DRM core. It is attached to \fIplane\fP.

The alpha property will be allowed to be within the bounds of 0
(transparent) to 0xffff (opaque).
.SH "RETURN"
0 on success, negative error code on failure.
