.TH "ds1685_rtc_bin2bcd" 9 "ds1685_rtc_bin2bcd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ds1685_rtc_bin2bcd \- bin2bcd wrapper in case platform doesn't support BCD.
.SH SYNOPSIS
.B "u8" ds1685_rtc_bin2bcd
.BI "(struct ds1685_priv *rtc "  ","
.BI "u8 val "  ","
.BI "u8 bin_mask "  ","
.BI "u8 bcd_mask "  ");"
.SH ARGUMENTS
.IP "rtc" 12
pointer to the ds1685 rtc structure.
.IP "val" 12
u8 time value to consider converting.
.IP "bin_mask" 12
u8 mask value if BIN mode is used.
.IP "bcd_mask" 12
u8 mask value if BCD mode is used.
.SH "DESCRIPTION"
Returns the value, converted to BCD if originally in BIN and bcd_mode TRUE.
