.TH "ds1685_rtc_end_data_access" 9 "ds1685_rtc_end_data_access" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ds1685_rtc_end_data_access \- end data access on the rtc.
.SH SYNOPSIS
.B "void" ds1685_rtc_end_data_access
.BI "(struct ds1685_priv *rtc "  ");"
.SH ARGUMENTS
.IP "rtc" 12
pointer to the ds1685 rtc structure.
.SH "DESCRIPTION"
This ends what was started by ds1685_rtc_begin_data_access:
- Switches the rtc back to bank 0.
- Clears the SET bit in Control Register B.
