.TH "ds1685_rtc_alarm_irq_enable" 9 "ds1685_rtc_alarm_irq_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ds1685_rtc_alarm_irq_enable \- replaces ioctl() RTC_AIE on/off.
.SH SYNOPSIS
.B "int" ds1685_rtc_alarm_irq_enable
.BI "(struct device *dev "  ","
.BI "unsigned int enabled "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to device structure.
.IP "enabled" 12
flag indicating whether to enable or disable.
