.TH "dvb_frontend_swzigzag_autotune" 9 "dvb_frontend_swzigzag_autotune" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dvb_frontend_swzigzag_autotune \- Performs automatic twiddling of frontend parameters.
.SH SYNOPSIS
.B "int" dvb_frontend_swzigzag_autotune
.BI "(struct dvb_frontend *fe "  ","
.BI "int check_wrapped "  ");"
.SH ARGUMENTS
.IP "fe" 12
The frontend concerned.
.IP "check_wrapped" 12
Checks if an iteration has completed.
DO NOT SET ON THE FIRST ATTEMPT.
.SH "RETURN"
Number of complete iterations that have been performed.
