.TH "dwc2_enable_host_interrupts" 9 "dwc2_enable_host_interrupts" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc2_enable_host_interrupts \- Enables the Host mode interrupts
.SH SYNOPSIS
.B "void" dwc2_enable_host_interrupts
.BI "(struct dwc2_hsotg *hsotg "  ");"
.SH ARGUMENTS
.IP "hsotg" 12
Programming view of DWC_otg controller
