.TH "dwc2_hsotg_complete_in" 9 "dwc2_hsotg_complete_in" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc2_hsotg_complete_in \- complete IN transfer
.SH SYNOPSIS
.B "void" dwc2_hsotg_complete_in
.BI "(struct dwc2_hsotg *hsotg "  ","
.BI "struct dwc2_hsotg_ep *hs_ep "  ");"
.SH ARGUMENTS
.IP "hsotg" 12
The device state.
.IP "hs_ep" 12
The endpoint that has just completed.
.SH "DESCRIPTION"
An IN transfer has been completed, update the transfer's state and then
call the relevant completion routines.
