.TH "dwc2_uframe_schedule_hs" 9 "dwc2_uframe_schedule_hs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc2_uframe_schedule_hs \- Schedule a QH for a periodic high speed xfer.
.SH SYNOPSIS
.B "int" dwc2_uframe_schedule_hs
.BI "(struct dwc2_hsotg *hsotg "  ","
.BI "struct dwc2_qh *qh "  ");"
.SH ARGUMENTS
.IP "hsotg" 12
The HCD state structure for the DWC OTG controller.
.IP "qh" 12
QH for the periodic transfer.
.SH "DESCRIPTION"

Basically this just wraps \fBdwc2_hs_pmap_schedule\fP to provide a clean
interface.
