.TH "dwc2_handle_usb_port_intr" 9 "dwc2_handle_usb_port_intr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc2_handle_usb_port_intr \- handles OTG PRTINT interrupts. When the PRTINT interrupt fires, there are certain status bits in the Host Port that needs to get cleared.
.SH SYNOPSIS
.B "void" dwc2_handle_usb_port_intr
.BI "(struct dwc2_hsotg *hsotg "  ");"
.SH ARGUMENTS
.IP "hsotg" 12
Programming view of DWC_otg controller
