.TH "dwc2_hsotg_handle_outdone" 9 "dwc2_hsotg_handle_outdone" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc2_hsotg_handle_outdone \- handle receiving OutDone/SetupDone from RXFIFO
.SH SYNOPSIS
.B "void" dwc2_hsotg_handle_outdone
.BI "(struct dwc2_hsotg *hsotg "  ","
.BI "int epnum "  ");"
.SH ARGUMENTS
.IP "hsotg" 12
The device instance
.IP "epnum" 12
The endpoint received from
.SH "DESCRIPTION"
The RXFIFO has delivered an OutDone event, which means that the data
transfer for an OUT endpoint has been completed, either by a short
packet or by the finish of a transfer.
