.TH "dwc3_qcom_interconnect_exit" 9 "dwc3_qcom_interconnect_exit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc3_qcom_interconnect_exit \- Release interconnect path handles
.SH SYNOPSIS
.B "void" dwc3_qcom_interconnect_exit
.BI "(struct dwc3_qcom *qcom "  ");"
.SH ARGUMENTS
.IP "qcom" 12
Pointer to the concerned usb core.
.SH "DESCRIPTION"
This function is used to release interconnect path handle.
