.TH "dwc3_gadget_init" 9 "dwc3_gadget_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dwc3_gadget_init \- initializes gadget related registers
.SH SYNOPSIS
.B "int" dwc3_gadget_init
.BI "(struct dwc3 *dwc "  ");"
.SH ARGUMENTS
.IP "dwc" 12
pointer to our controller context structure
.SH "DESCRIPTION"
Returns 0 on success otherwise negative errno.
