.TH "dynevent_create" 9 "dynevent_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
dynevent_create \- Create the dynamic event contained in dynevent_cmd
.SH SYNOPSIS
.B "int" dynevent_create
.BI "(struct dynevent_cmd *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
The dynevent_cmd object containing the dynamic event creation command
.SH "DESCRIPTION"
Once a dynevent_cmd object has been successfully built up via the
\fBdynevent_cmd_init\fP, \fBdynevent_arg_add\fP and \fBdynevent_arg_pair_add\fP
functions, this function runs the final command to actually create
the event.
.SH "RETURN"
0 if the event was successfully created, error otherwise.
