.TH "e1000_init_mbx_params_vf" 9 "e1000_init_mbx_params_vf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
e1000_init_mbx_params_vf \- set initial values for VF mailbox
.SH SYNOPSIS
.B "s32" e1000_init_mbx_params_vf
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure

Initializes the hw->mbx struct to correct values for VF mailbox
