.TH "e1000_valid_nvm_bank_detect_ich8lan" 9 "e1000_valid_nvm_bank_detect_ich8lan" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
e1000_valid_nvm_bank_detect_ich8lan \- finds out the valid bank 0 or 1
.SH SYNOPSIS
.B "s32" e1000_valid_nvm_bank_detect_ich8lan
.BI "(struct e1000_hw *hw "  ","
.BI "u32 *bank "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "bank" 12
pointer to the variable that returns the active bank

Reads signature byte from the NVM using the flash access registers.
Word 0x13 bits 15:14 = 10b indicate a valid signature for that bank.
