.TH "e1000_flash_cycle_init_ich8lan" 9 "e1000_flash_cycle_init_ich8lan" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
e1000_flash_cycle_init_ich8lan \- Initialize flash
.SH SYNOPSIS
.B "s32" e1000_flash_cycle_init_ich8lan
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure

This function does initial flash setup so that a new read/write/erase cycle
can be started.
