.TH "e1000_check_64k_bound" 9 "e1000_check_64k_bound" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
e1000_check_64k_bound \- check that memory doesn't cross 64kB boundary
.SH SYNOPSIS
.B "bool" e1000_check_64k_bound
.BI "(struct e1000_adapter *adapter "  ","
.BI "void *start "  ","
.BI "unsigned long len "  ");"
.SH ARGUMENTS
.IP "adapter" 12
address of board private structure
.IP "start" 12
address of beginning of memory
.IP "len" 12
length of memory
