.TH "e1000_check_mng_mode_ich8lan" 9 "e1000_check_mng_mode_ich8lan" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
e1000_check_mng_mode_ich8lan \- Checks management mode
.SH SYNOPSIS
.B "bool" e1000_check_mng_mode_ich8lan
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure

This checks if the adapter has any manageability enabled.
This is a function pointer entry point only called by read/write
routines for the PHY and NVM parts.
