.TH "early_init_fdt_scan_reserved_mem" 9 "early_init_fdt_scan_reserved_mem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
early_init_fdt_scan_reserved_mem \- create reserved memory regions
.SH SYNOPSIS
.B "void" early_init_fdt_scan_reserved_mem
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This function grabs memory from early allocator for device exclusive use
defined in device tree structures. It should be called by arch specific code
once the early allocator (i.e. memblock) has been fully activated.
