.TH "ebitmap_netlbl_import" 9 "ebitmap_netlbl_import" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ebitmap_netlbl_import \- Import a NetLabel category bitmap into an ebitmap
.SH SYNOPSIS
.B "int" ebitmap_netlbl_import
.BI "(struct ebitmap *ebmap "  ","
.BI "struct netlbl_lsm_catmap *catmap "  ");"
.SH ARGUMENTS
.IP "ebmap" 12
the ebitmap to import
.IP "catmap" 12
the NetLabel category bitmap
.SH "DESCRIPTION"
Import a NetLabel category bitmap into a SELinux extensibile bitmap.
Returns zero on success, negative values on error.
