.TH "echo_set_canon_col" 9 "echo_set_canon_col" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
echo_set_canon_col \- add operation to set the canon column
.SH SYNOPSIS
.B "void" echo_set_canon_col
.BI "(struct n_tty_data *ldata "  ");"
.SH ARGUMENTS
.IP "ldata" 12
n_tty data

Add an operation to the echo buffer to set the canon column
to the current column.
