.TH "echo_char" 9 "echo_char" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
echo_char \- echo a character
.SH SYNOPSIS
.B "void" echo_char
.BI "(unsigned char c "  ","
.BI "struct tty_struct *tty "  ");"
.SH ARGUMENTS
.IP "c" 12
unicode byte to echo
.IP "tty" 12
terminal device

Echo user input back onto the screen. This must be called only when
L_ECHO(tty) is true. Called from the driver receive_buf path.

This variant tags control characters to be echoed as "^X"
(where X is the letter representing the control char).
