.TH "ecryptfs_spawn_daemon" 9 "ecryptfs_spawn_daemon" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ecryptfs_spawn_daemon \- Create and initialize a new daemon struct
.SH SYNOPSIS
.B "int" ecryptfs_spawn_daemon
.BI "(struct ecryptfs_daemon **daemon "  ","
.BI "struct file *file "  ");"
.SH ARGUMENTS
.IP "daemon" 12
Pointer to set to newly allocated daemon struct
.IP "file" 12
File used when opening /dev/ecryptfs
.SH "DESCRIPTION"
Must be called ceremoniously while in possession of
ecryptfs_sacred_daemon_hash_mux

Returns zero on success; non-zero otherwise
