.TH "ecryptfs_read_headers_virt" 9 "ecryptfs_read_headers_virt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ecryptfs_read_headers_virt \- 
.SH SYNOPSIS
.B "int" ecryptfs_read_headers_virt
.BI "(char *page_virt "  ","
.BI "struct ecryptfs_crypt_stat *crypt_stat "  ","
.BI "struct dentry *ecryptfs_dentry "  ","
.BI "int validate_header_size "  ");"
.SH ARGUMENTS
.IP "page_virt" 12
The virtual address into which to read the headers
.IP "crypt_stat" 12
The cryptographic context
.IP "ecryptfs_dentry" 12
The eCryptfs dentry
.IP "validate_header_size" 12
Whether to validate the header size while reading
.SH "DESCRIPTION"
Read/parse the header data. The header format is detailed in the
comment block for the \fBecryptfs_write_headers_virt\fP function.

Returns zero on success
