.TH "eeh_pe_restore_bars" 9 "eeh_pe_restore_bars" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeh_pe_restore_bars \- Restore the PCI config space info
.SH SYNOPSIS
.B "void" eeh_pe_restore_bars
.BI "(struct eeh_pe *pe "  ");"
.SH ARGUMENTS
.IP "pe" 12
EEH PE
.SH "DESCRIPTION"
This routine performs a recursive walk to the children
of this device as well.
