.TH "eeh_report_failure" 9 "eeh_report_failure" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeh_report_failure \- Tell device driver that device is dead.
.SH SYNOPSIS
.B "enum pci_ers_result" eeh_report_failure
.BI "(struct eeh_dev *edev "  ","
.BI "struct pci_dev *pdev "  ","
.BI "struct pci_driver *driver "  ");"
.SH ARGUMENTS
.IP "edev" 12
eeh device
.IP "pdev" 12
-- undescribed --
.IP "driver" 12
device's PCI driver
.SH "DESCRIPTION"
This informs the device driver that the device is permanently
dead, and that no further recovery attempts will be made on it.
