.TH "eeh_pe_alloc" 9 "eeh_pe_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeh_pe_alloc \- Allocate PE
.SH SYNOPSIS
.B "struct eeh_pe *" eeh_pe_alloc
.BI "(struct pci_controller *phb "  ","
.BI "int type "  ");"
.SH ARGUMENTS
.IP "phb" 12
PCI controller
.IP "type" 12
PE type
.SH "DESCRIPTION"
Allocate PE instance dynamically.
