.TH "eeh_addr_cache_insert_dev" 9 "eeh_addr_cache_insert_dev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeh_addr_cache_insert_dev \- Add a device to the address cache
.SH SYNOPSIS
.B "void" eeh_addr_cache_insert_dev
.BI "(struct pci_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
PCI device whose I/O addresses we are interested in.
.SH "DESCRIPTION"
In order to support the fast lookup of devices based on addresses,
we maintain a cache of devices that can be quickly searched.
This routine adds a device to that cache.
