.TH "eeh_pe_state_clear" 9 "eeh_pe_state_clear" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeh_pe_state_clear \- Clear state for the PE
.SH SYNOPSIS
.B "void" eeh_pe_state_clear
.BI "(struct eeh_pe *root "  ","
.BI "int state "  ","
.BI "bool include_passed "  ");"
.SH ARGUMENTS
.IP "root" 12
-- undescribed --
.IP "state" 12
state
.IP "include_passed" 12
include passed-through devices?
.SH "DESCRIPTION"
The function is used to clear the indicated state from the
given PE. Besides, we also clear the check count of the PE
as well.
