.TH "eeprom_93cx6_readb" 9 "eeprom_93cx6_readb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeprom_93cx6_readb \- Read a byte from eeprom
.SH SYNOPSIS
.B "void" eeprom_93cx6_readb
.BI "(struct eeprom_93cx6 *eeprom "  ","
.BI "const u8 byte "  ","
.BI "u8 *data "  ");"
.SH ARGUMENTS
.IP "eeprom" 12
Pointer to eeprom structure
.IP "byte" 12
Byte index from where we should start reading
.IP "data" 12
target pointer where the information will have to be stored
.SH "DESCRIPTION"
This function will read a byte of the eeprom data
into the given data pointer.
