.TH "eeprom_93cx6_multireadb" 9 "eeprom_93cx6_multireadb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eeprom_93cx6_multireadb \- Read multiple bytes from eeprom
.SH SYNOPSIS
.B "void" eeprom_93cx6_multireadb
.BI "(struct eeprom_93cx6 *eeprom "  ","
.BI "const u8 byte "  ","
.BI "u8 *data "  ","
.BI "const u16 bytes "  ");"
.SH ARGUMENTS
.IP "eeprom" 12
Pointer to eeprom structure
.IP "byte" 12
Index from where we should start reading
.IP "data" 12
target pointer where the information will have to be stored
.IP "bytes" 12
Number of bytes that should be read.
.SH "DESCRIPTION"
This function will read all requested bytes from the eeprom,
this is done by calling \fBeeprom_93cx6_readb\fP multiple times.
