.TH "ehci_hcd_omap_remove" 9 "ehci_hcd_omap_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ehci_hcd_omap_remove \- shutdown processing for EHCI HCDs
.SH SYNOPSIS
.B "int" ehci_hcd_omap_remove
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
USB Host Controller being removed
.SH "DESCRIPTION"
Reverses the effect of \fBusb_ehci_hcd_omap_probe\fP, first invoking
the HCD's \fBstop\fP method.  It is always called from a thread
context, normally "rmmod", "apmd", or something similar.
