.TH "eic_show" 9 "eic_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eic_show \- show Electronic Identification Code in sysfs
.SH SYNOPSIS
.B "ssize_t" eic_show
.BI "(struct device *dev "  ","
.BI "struct device_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "dev" 12
device
.IP "attr" 12
device attribute
.IP "buf" 12
sysfs buffer (PAGE_SIZE) where EIC is written
.SH "DESCRIPTION"
Will be called on read access to eic sysfs attribute.
Returns number of bytes written into buffer, negative errno on error.
