.TH "elm_load_syndrome" 9 "elm_load_syndrome" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
elm_load_syndrome \- Load ELM syndrome reg
.SH SYNOPSIS
.B "void" elm_load_syndrome
.BI "(struct elm_info *info "  ","
.BI "struct elm_errorvec *err_vec "  ","
.BI "u8 *ecc "  ");"
.SH ARGUMENTS
.IP "info" 12
elm info
.IP "err_vec" 12
elm error vectors
.IP "ecc" 12
buffer with calculated ecc
.SH "DESCRIPTION"
Load syndrome fragment registers with calculated ecc in reverse order.
