.TH "emac_dev_xmit" 9 "emac_dev_xmit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
emac_dev_xmit \- EMAC Transmit function
.SH SYNOPSIS
.B "int" emac_dev_xmit
.BI "(struct sk_buff *skb "  ","
.BI "struct net_device *ndev "  ");"
.SH ARGUMENTS
.IP "skb" 12
SKB pointer
.IP "ndev" 12
The DaVinci EMAC network adapter
.SH "DESCRIPTION"
Called by the system to transmit a packet  - we queue the packet in
EMAC hardware transmit queue

Returns success(NETDEV_TX_OK) or error code (typically out of desc's)
