.TH "emac_int_disable" 9 "emac_int_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
emac_int_disable \- Disable EMAC module interrupt (from adapter)
.SH SYNOPSIS
.B "void" emac_int_disable
.BI "(struct emac_priv *priv "  ");"
.SH ARGUMENTS
.IP "priv" 12
The DaVinci EMAC private adapter structure
.SH "DESCRIPTION"
Disable EMAC interrupt on the adapter
