.TH "emulate_delivery_system" 9 "emulate_delivery_system" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
emulate_delivery_system \- emulate a DVBv5 delivery system with a DVBv3 type
.SH SYNOPSIS
.B "int" emulate_delivery_system
.BI "(struct dvb_frontend *fe "  ","
.BI "u32 delsys "  ");"
.SH ARGUMENTS
.IP "fe" 12
struct frontend;
.IP "delsys" 12
DVBv5 type that will be used for emulation
.SH "DESCRIPTION"
Provides emulation for delivery systems that are compatible with the old
DVBv3 call. Among its usages, it provices support for ISDB-T, and allows
using a DVB-S2 only frontend just like it were a DVB-S, if the frontend
parameters are compatible with DVB-S spec.
