.TH "enable_cmf" 9 "enable_cmf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
enable_cmf \- switch on the channel measurement for a specific device
.SH SYNOPSIS
.B "int" enable_cmf
.BI "(struct ccw_device *cdev "  ");"
.SH ARGUMENTS
.IP "cdev" 12
The ccw device to be enabled

Enable channel measurements for \fIcdev\fP. If this is called on a device
for which channel measurement is already enabled a reset of the
measurement data is triggered.
.SH "RETURN"
0 for success or a negative error value.
.SH "CONTEXT"
non-atomic
