.TH "enclosure_component_alloc" 9 "enclosure_component_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
enclosure_component_alloc \- prepare a new enclosure component
.SH SYNOPSIS
.B "struct enclosure_component *" enclosure_component_alloc
.BI "(struct enclosure_device *edev "  ","
.BI "unsigned int number "  ","
.BI "enum enclosure_component_type type "  ","
.BI "const char *name "  ");"
.SH ARGUMENTS
.IP "edev" 12
the enclosure to add the component
.IP "number" 12
the device number
.IP "type" 12
the type of component being added
.IP "name" 12
an optional name to appear in sysfs (leave NULL if none)
.SH "DESCRIPTION"
The name is optional for enclosures that give their components a unique
name.  If not, leave the field NULL and a name will be assigned.

Returns a pointer to the enclosure component or an error.
