.TH "ensure_wear_leveling" 9 "ensure_wear_leveling" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ensure_wear_leveling \- schedule wear-leveling if it is needed.
.SH SYNOPSIS
.B "int" ensure_wear_leveling
.BI "(struct ubi_device *ubi "  ","
.BI "int nested "  ");"
.SH ARGUMENTS
.IP "ubi" 12
UBI device description object
.IP "nested" 12
set to non-zero if this function is called from UBI worker
.SH "DESCRIPTION"
This function checks if it is time to start wear-leveling and schedules it
if yes. This function returns zero in case of success and a negative error
code in case of failure.
