.TH "ep93xx_spi_dma_prepare" 9 "ep93xx_spi_dma_prepare" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ep93xx_spi_dma_prepare \- prepares a DMA transfer
.SH SYNOPSIS
.B "struct dma_async_tx_descriptor *" ep93xx_spi_dma_prepare
.BI "(struct spi_master *master "  ","
.BI "enum dma_data_direction dir "  ");"
.SH ARGUMENTS
.IP "master" 12
SPI master
.IP "dir" 12
DMA transfer direction
.SH "DESCRIPTION"
Function configures the DMA, maps the buffer and prepares the DMA
descriptor. Returns a valid DMA descriptor in case of success and ERR_PTR
in case of failure.
