.TH "ep93xx_spi_calc_divisors" 9 "ep93xx_spi_calc_divisors" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ep93xx_spi_calc_divisors \- calculates SPI clock divisors
.SH SYNOPSIS
.B "int" ep93xx_spi_calc_divisors
.BI "(struct spi_master *master "  ","
.BI "u32 rate "  ","
.BI "u8 *div_cpsr "  ","
.BI "u8 *div_scr "  ");"
.SH ARGUMENTS
.IP "master" 12
SPI master
.IP "rate" 12
desired SPI output clock rate
.IP "div_cpsr" 12
pointer to return the cpsr (pre-scaler) divider
.IP "div_scr" 12
pointer to return the scr divider
