.TH "ep93xx_dma_free_chan_resources" 9 "ep93xx_dma_free_chan_resources" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ep93xx_dma_free_chan_resources \- release resources for the channel
.SH SYNOPSIS
.B "void" ep93xx_dma_free_chan_resources
.BI "(struct dma_chan *chan "  ");"
.SH ARGUMENTS
.IP "chan" 12
channel
.SH "DESCRIPTION"
Function releases all the resources allocated for the given channel.
The channel must be idle when this is called.
