.TH "epf_ntb_epc_create_interface" 9 "epf_ntb_epc_create_interface" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
epf_ntb_epc_create_interface \- Create and initialize NTB EPC interface
.SH SYNOPSIS
.B "int" epf_ntb_epc_create_interface
.BI "(struct epf_ntb *ntb "  ","
.BI "struct pci_epc *epc "  ","
.BI "enum pci_epc_interface_type type "  ");"
.SH ARGUMENTS
.IP "ntb" 12
NTB device that facilitates communication between HOST1 and HOST2
.IP "epc" 12
struct pci_epc to which a particular NTB interface should be associated
.IP "type" 12
PRIMARY interface or SECONDARY interface
.SH "DESCRIPTION"
Allocate memory for NTB EPC interface and initialize it.
