.TH "epf_ntb_db_mw_bar_init" 9 "epf_ntb_db_mw_bar_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
epf_ntb_db_mw_bar_init \- Configure Doorbell and Memory window BARs
.SH SYNOPSIS
.B "int" epf_ntb_db_mw_bar_init
.BI "(struct epf_ntb *ntb "  ","
.BI "enum pci_epc_interface_type type "  ");"
.SH ARGUMENTS
.IP "ntb" 12
NTB device that facilitates communication between HOST1 and HOST2
.IP "type" 12
PRIMARY interface or SECONDARY interface
.SH "DESCRIPTION"
Wrapper for \fBepf_ntb_alloc_peer_mem\fP and \fBpci_epc_set_bar\fP that allocates
memory in OB address space of HOST2 and configures BAR of HOST1
