.TH "epf_ntb_configure_interrupt" 9 "epf_ntb_configure_interrupt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
epf_ntb_configure_interrupt \- Configure MSI/MSI-X capaiblity
.SH SYNOPSIS
.B "int" epf_ntb_configure_interrupt
.BI "(struct epf_ntb *ntb "  ","
.BI "enum pci_epc_interface_type type "  ");"
.SH ARGUMENTS
.IP "ntb" 12
NTB device that facilitates communication between HOST1 and HOST2
.IP "type" 12
PRIMARY interface or SECONDARY interface
.SH "DESCRIPTION"
Configure MSI/MSI-X capability for each interface with number of
interrupts equal to "db_count" configfs entry.
