.TH "eth_type_trans" 9 "eth_type_trans" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eth_type_trans \- determine the packet's protocol ID.
.SH SYNOPSIS
.B "__be16" eth_type_trans
.BI "(struct sk_buff *skb "  ","
.BI "struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "skb" 12
received socket data
.IP "dev" 12
receiving network device
.SH "DESCRIPTION"
The rule here is that we
assume 802.3 if the type field is short enough to be a length.
This is normal practice and works for any 'now in use' protocol.
