.TH "ethnl_bitmap32_not_zero" 9 "ethnl_bitmap32_not_zero" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ethnl_bitmap32_not_zero \- Check if any bit is set in an interval
.SH SYNOPSIS
.B "bool" ethnl_bitmap32_not_zero
.BI "(const u32 *map "  ","
.BI "unsigned int start "  ","
.BI "unsigned int end "  ");"
.SH ARGUMENTS
.IP "map" 12
bitmap to test
.IP "start" 12
beginning of the interval
.IP "end" 12
end of the interval
.SH "RETURN"
true if there is non-zero bit with  index \fIstart\fP <= i < \fIend\fP,
false if the whole interval is zero
