.TH "ethnl_bitset32_size" 9 "ethnl_bitset32_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ethnl_bitset32_size \- Calculate size of bitset nested attribute
.SH SYNOPSIS
.B "int" ethnl_bitset32_size
.BI "(const u32 *val "  ","
.BI "const u32 *mask "  ","
.BI "unsigned int nbits "  ","
.BI "ethnl_string_array_t names "  ","
.BI "bool compact "  ");"
.SH ARGUMENTS
.IP "val" 12
value bitmap (u32 based)
.IP "mask" 12
mask bitmap (u32 based, optional)
.IP "nbits" 12
bit length of the bitset
.IP "names" 12
array of bit names (optional)
.IP "compact" 12
assume compact format for output
.SH "DESCRIPTION"
Estimate length of netlink attribute composed by a later call to
\fBethnl_put_bitset32\fP call with the same arguments.
.SH "RETURN"
negative error code or attribute length estimate
