.TH "eventfd_fget" 9 "eventfd_fget" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
eventfd_fget \- Acquire a reference of an eventfd file descriptor.
.SH SYNOPSIS
.B "struct file *" eventfd_fget
.BI "(int fd "  ");"
.SH ARGUMENTS
.IP "fd" 12
[in] Eventfd file descriptor.
.SH "DESCRIPTION"
Returns a pointer to the eventfd file structure in case of success, or the
following error pointer:

-EBADF    : Invalid \fIfd\fP file descriptor.
-EINVAL   : The \fIfd\fP file descriptor is not an eventfd file.
