.TH "ext4_double_down_write_data_sem" 9 "ext4_double_down_write_data_sem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ext4_double_down_write_data_sem \- write lock two inodes's i_data_sem
.SH SYNOPSIS
.B "void" ext4_double_down_write_data_sem
.BI "(struct inode *first "  ","
.BI "struct inode *second "  ");"
.SH ARGUMENTS
.IP "first" 12
inode to be locked
.IP "second" 12
inode to be locked
.SH "DESCRIPTION"
Acquire write lock of i_data_sem of the two inodes
