.TH "exynos5_dmc_align_bypass_dram_timings" 9 "exynos5_dmc_align_bypass_dram_timings" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
exynos5_dmc_align_bypass_dram_timings \- Chooses and sets DRAM timings
.SH SYNOPSIS
.B "int" exynos5_dmc_align_bypass_dram_timings
.BI "(struct exynos5_dmc *dmc "  ","
.BI "unsigned long target_rate "  ");"
.SH ARGUMENTS
.IP "dmc" 12
device for which it is going to be set
.IP "target_rate" 12
new frequency which is chosen to be final
.SH "DESCRIPTION"
Function changes the DRAM timings for the temporary 'bypass' mode.
