.TH "exynos5_dmc_remove" 9 "exynos5_dmc_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
exynos5_dmc_remove \- Remove function for the platform device
.SH SYNOPSIS
.B "int" exynos5_dmc_remove
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
platform device which is going to be removed
.SH "DESCRIPTION"
The function relies on 'devm' framework function which automatically
clean the device's resources. It just calls explicitly disable function for
the performance counters.
