.TH "fas216_message" 9 "fas216_message" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fas216_message \- handle a function done interrupt from FAS216 chip
.SH SYNOPSIS
.B "void" fas216_message
.BI "(FAS216_Info *info "  ");"
.SH ARGUMENTS
.IP "info" 12
interface which caused function done interrupt
.SH "DESCRIPTION"
Handle a function done interrupt from FAS216 chip
