.TH "fas216_eh_host_reset" 9 "fas216_eh_host_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fas216_eh_host_reset \- Reset the host associated with this command
.SH SYNOPSIS
.B "int" fas216_eh_host_reset
.BI "(struct scsi_cmnd *SCpnt "  ");"
.SH ARGUMENTS
.IP "SCpnt" 12
command specifing host to reset
.SH "DESCRIPTION"
Reset the host associated with this command.
.SH "RETURN"
FAILED if unable to reset.
.SH "NOTES"
io_request_lock is taken, and irqs are disabled
