.TH "fast_to_acquire" 9 "fast_to_acquire" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fast_to_acquire \- determine if a resource group will be fast to acquire
.SH SYNOPSIS
.B "int" fast_to_acquire
.BI "(struct gfs2_rgrpd *rgd "  ");"
.SH ARGUMENTS
.IP "rgd" 12
-- undescribed --
.SH "DESCRIPTION"

If this is one of our preferred rgrps, it should be quicker to acquire,
because we tried to set ourselves up as dlm lock master.
