.TH "fat_parse_short" 9 "fat_parse_short" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fat_parse_short \- Parse MS-DOS (short) directory entry.
.SH SYNOPSIS
.B "int" fat_parse_short
.BI "(struct super_block *sb "  ","
.BI "const struct msdos_dir_entry *de "  ","
.BI "unsigned char *name "  ","
.BI "int dot_hidden "  ");"
.SH ARGUMENTS
.IP "sb" 12
superblock
.IP "de" 12
directory entry to parse
.IP "name" 12
FAT_MAX_SHORT_SIZE array in which to place extracted name
.IP "dot_hidden" 12
Nonzero == prepend '.' to names with ATTR_HIDDEN
.SH "DESCRIPTION"
Returns the number of characters extracted into 'name'.
