.TH "fb_destroy_modedb" 9 "fb_destroy_modedb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fb_destroy_modedb \- destroys mode database
.SH SYNOPSIS
.B "void" fb_destroy_modedb
.BI "(struct fb_videomode *modedb "  ");"
.SH ARGUMENTS
.IP "modedb" 12
mode database to destroy
.SH "DESCRIPTION"
Destroy mode database created by fb_create_modedb
