.TH "fb_find_nearest_mode" 9 "fb_find_nearest_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fb_find_nearest_mode \- find closest videomode
.SH SYNOPSIS
.B "const struct fb_videomode *" fb_find_nearest_mode
.BI "(const struct fb_videomode *mode "  ","
.BI "struct list_head *head "  ");"
.SH ARGUMENTS
.IP "mode" 12
pointer to struct fb_videomode
.IP "head" 12
pointer to modelist
.SH "DESCRIPTION"
Finds best matching videomode, smaller or greater in dimension.
If more than 1 videomode is found, will return the videomode with
the closest refresh rate.
