.TH "fb_get_hfreq" 9 "fb_get_hfreq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fb_get_hfreq \- estimate hsync
.SH SYNOPSIS
.B "u32" fb_get_hfreq
.BI "(u32 vfreq "  ","
.BI "u32 yres "  ");"
.SH ARGUMENTS
.IP "vfreq" 12
vertical refresh rate
.IP "yres" 12
vertical resolution
.SH "DESCRIPTION"

(yres + front_port) * vfreq * 1000000
hfreq = -------------------------------------
(1000000 - (vfreq * FLYBACK)
