.TH "fb_set_suspend" 9 "fb_set_suspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fb_set_suspend \- low level driver signals suspend
.SH SYNOPSIS
.B "void" fb_set_suspend
.BI "(struct fb_info *info "  ","
.BI "int state "  ");"
.SH ARGUMENTS
.IP "info" 12
framebuffer affected
.IP "state" 12
0 = resuming, !=0 = suspending

This is meant to be used by low level drivers to
signal suspend/resume to the core & clients.
It must be called with the console semaphore held
