.TH "fb_videomode_to_modelist" 9 "fb_videomode_to_modelist" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fb_videomode_to_modelist \- convert mode array to mode list
.SH SYNOPSIS
.B "void" fb_videomode_to_modelist
.BI "(const struct fb_videomode *modedb "  ","
.BI "int num "  ","
.BI "struct list_head *head "  ");"
.SH ARGUMENTS
.IP "modedb" 12
array of struct fb_videomode
.IP "num" 12
number of entries in array
.IP "head" 12
struct list_head of modelist
