.TH "fbmem_init" 9 "fbmem_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fbmem_init \- init frame buffer subsystem
.SH SYNOPSIS
.B "int" fbmem_init
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Initialize the frame buffer subsystem.
.SH "NOTE"
This function is _only_ to be called by drivers/char/mem.c.
