.TH "fc_disc_done" 9 "fc_disc_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_disc_done \- Discovery has been completed
.SH SYNOPSIS
.B "void" fc_disc_done
.BI "(struct fc_disc *disc "  ","
.BI "enum fc_disc_event event "  ");"
.SH ARGUMENTS
.IP "disc" 12
The discovery context
.IP "event" 12
The discovery completion status
