.TH "fc_disc_config" 9 "fc_disc_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_disc_config \- Configure the discovery layer for a local port
.SH SYNOPSIS
.B "void" fc_disc_config
.BI "(struct fc_lport *lport "  ","
.BI "void *priv "  ");"
.SH ARGUMENTS
.IP "lport" 12
The local port that needs the discovery layer to be configured
.IP "priv" 12
Private data structre for users of the discovery layer
