.TH "fc_exch_resp" 9 "fc_exch_resp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_exch_resp \- Allocate a new exchange for a response frame
.SH SYNOPSIS
.B "struct fc_exch *" fc_exch_resp
.BI "(struct fc_lport *lport "  ","
.BI "struct fc_exch_mgr *mp "  ","
.BI "struct fc_frame *fp "  ");"
.SH ARGUMENTS
.IP "lport" 12
The local port that the exchange was for
.IP "mp" 12
The exchange manager to allocate the exchange from
.IP "fp" 12
The response frame
.SH "DESCRIPTION"
Sets the responder ID in the frame header.
