.TH "fc_exch_timer_set" 9 "fc_exch_timer_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_exch_timer_set \- Lock the exchange and set the timer
.SH SYNOPSIS
.B "void" fc_exch_timer_set
.BI "(struct fc_exch *ep "  ","
.BI "unsigned int timer_msec "  ");"
.SH ARGUMENTS
.IP "ep" 12
The exchange whose timer will start
.IP "timer_msec" 12
The timeout period
