.TH "fc_exch_abort_locked" 9 "fc_exch_abort_locked" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_exch_abort_locked \- Abort an exchange
.SH SYNOPSIS
.B "int" fc_exch_abort_locked
.BI "(struct fc_exch *ep "  ","
.BI "unsigned int timer_msec "  ");"
.SH ARGUMENTS
.IP "ep" 12
The exchange to be aborted
.IP "timer_msec" 12
The period of time to wait before aborting
.SH "DESCRIPTION"
Abort an exchange and sequence. Generally called because of a
exchange timeout or an abort from the upper layer.

A timer_msec can be specified for abort timeout, if non-zero
timer_msec value is specified then exchange resp handler
will be called with timeout error if no response to abort.

Locking notes:  Called with exch lock held

Return value: 0 on success else error code
