.TH "fc_fill_hdr" 9 "fc_fill_hdr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_fill_hdr \- fill FC header fields based on request
.SH SYNOPSIS
.B "void" fc_fill_hdr
.BI "(struct fc_frame *fp "  ","
.BI "const struct fc_frame *in_fp "  ","
.BI "enum fc_rctl r_ctl "  ","
.BI "u32 f_ctl "  ","
.BI "u16 seq_cnt "  ","
.BI "u32 parm_offset "  ");"
.SH ARGUMENTS
.IP "fp" 12
reply frame containing header to be filled in
.IP "in_fp" 12
request frame containing header to use in filling in reply
.IP "r_ctl" 12
R_CTL value for header
.IP "f_ctl" 12
F_CTL value for header, with 0 pad
.IP "seq_cnt" 12
sequence count for the header, ignored if frame has a sequence
.IP "parm_offset" 12
parameter / offset value
