.TH "fc_get_event_number" 9 "fc_get_event_number" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_get_event_number \- Obtain the next sequential FC event number
.SH SYNOPSIS
.B "u32" fc_get_event_number
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "NOTES"
We could have inlined this, but it would have required fc_event_seq to
be exposed. For now, live with the subroutine call.
Atomic used to avoid lock/unlock...
