.TH "fc_rport_work" 9 "fc_rport_work" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_rport_work \- Handler for remote port events in the rport_event_queue
.SH SYNOPSIS
.B "void" fc_rport_work
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
Handle to the remote port being dequeued
.SH "DESCRIPTION"
Reference counting: drops kref on return
