.TH "fc_rport_login_complete" 9 "fc_rport_login_complete" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_rport_login_complete \- Handle parameters and completion of p-mp login.
.SH SYNOPSIS
.B "int" fc_rport_login_complete
.BI "(struct fc_rport_priv *rdata "  ","
.BI "struct fc_frame *fp "  ");"
.SH ARGUMENTS
.IP "rdata" 12
The remote port which we logged into or which logged into us.
.IP "fp" 12
The FLOGI or PLOGI request or response frame
.SH "DESCRIPTION"
Returns non-zero error if a problem is detected with the frame.
Does not free the frame.

This is only used in point-to-multipoint mode for FIP currently.
