.TH "fc_set_rport_loss_tmo" 9 "fc_set_rport_loss_tmo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fc_set_rport_loss_tmo \- Set the remote port loss timeout
.SH SYNOPSIS
.B "void" fc_set_rport_loss_tmo
.BI "(struct fc_rport *rport "  ","
.BI "u32 timeout "  ");"
.SH ARGUMENTS
.IP "rport" 12
The remote port that gets a new timeout value
.IP "timeout" 12
The new timeout value (in seconds)
