.TH "fcoe_ctlr_vn_beacon" 9 "fcoe_ctlr_vn_beacon" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_ctlr_vn_beacon \- handle received beacon.
.SH SYNOPSIS
.B "void" fcoe_ctlr_vn_beacon
.BI "(struct fcoe_ctlr *fip "  ","
.BI "struct fcoe_rport *new "  ");"
.SH ARGUMENTS
.IP "fip" 12
The FCoE controller that received the frame
.IP "new" 12
newly-parsed FCoE rport from the Beacon
.SH "DESCRIPTION"
Called with ctlr_mutex held.
