.TH "fcoe_ctlr_device_release" 9 "fcoe_ctlr_device_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_ctlr_device_release \- Release the FIP ctlr memory
.SH SYNOPSIS
.B "void" fcoe_ctlr_device_release
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Pointer to the FIP ctlr's embedded device
.SH "DESCRIPTION"
Called when the last FIP ctlr reference is released.
