.TH "fcoe_ctlr_flogi_send" 9 "fcoe_ctlr_flogi_send" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_ctlr_flogi_send \- Handle sending of FIP FLOGI.
.SH SYNOPSIS
.B "void" fcoe_ctlr_flogi_send
.BI "(struct fcoe_ctlr *fip "  ");"
.SH ARGUMENTS
.IP "fip" 12
The FCoE controller that timed out
.SH "DESCRIPTION"
Done here because \fBfcoe_ctlr_els_send\fP can't get mutex.

Called with ctlr_mutex held.  The caller must not hold ctlr_lock.
