.TH "fcoe_disable" 9 "fcoe_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fcoe_disable \- Disables a FCoE interface
.SH SYNOPSIS
.B "int" fcoe_disable
.BI "(struct net_device *netdev "  ");"
.SH ARGUMENTS
.IP "netdev" 12
The net_device object the Ethernet interface to create on
.SH "DESCRIPTION"
Called from fcoe transport.

Deprecated: use \fBfcoe_ctlr_enabled\fP
.SH "RETURN"
0 for success
