.TH "fdt_find_add_string_" 9 "fdt_find_add_string_" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fdt_find_add_string_ \- Find or allocate a string
.SH SYNOPSIS
.B "int" fdt_find_add_string_
.BI "(void *fdt "  ","
.BI "const char *s "  ","
.BI "int *allocated "  ");"
.SH ARGUMENTS
.IP "fdt" 12
pointer to the device tree to check/adjust
.IP "s" 12
string to find/add
.IP "allocated" 12
Set to 0 if the string was found, 1 if not found and so
allocated. Ignored if can_assume(NO_ROLLBACK)
\fIreturn\fP offset of string in the string table (whether found or added)
