.TH "fimc_get_sensor_frame_desc" 9 "fimc_get_sensor_frame_desc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fimc_get_sensor_frame_desc \- query the sensor for media bus frame parameters
.SH SYNOPSIS
.B "int" fimc_get_sensor_frame_desc
.BI "(struct v4l2_subdev *sensor "  ","
.BI "struct v4l2_plane_pix_format *plane_fmt "  ","
.BI "unsigned int num_planes "  ","
.BI "bool try "  ");"
.SH ARGUMENTS
.IP "sensor" 12
pointer to the sensor subdev
.IP "plane_fmt" 12
provides plane sizes corresponding to the frame layout entries
.IP "num_planes" 12
number of planes
.IP "try" 12
true to set the frame parameters, false to query only
.SH "DESCRIPTION"
This function is used by this driver only for compressed/blob data formats.
