.TH "find_vm_area" 9 "find_vm_area" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
find_vm_area \- find a continuous kernel virtual area
.SH SYNOPSIS
.B "struct vm_struct *" find_vm_area
.BI "(const void *addr "  ");"
.SH ARGUMENTS
.IP "addr" 12
base address
.SH "DESCRIPTION"
Search for the kernel VM area starting at \fIaddr\fP, and return it.
It is up to the caller to do all required locking to keep the returned
pointer valid.
.SH "RETURN"
the area descriptor on success or NULL on failure.
