.TH "first_non_ff" 9 "first_non_ff" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
first_non_ff \- find offset of the first non-0xff byte.
.SH SYNOPSIS
.B "int" first_non_ff
.BI "(void *buf "  ","
.BI "int len "  ");"
.SH ARGUMENTS
.IP "buf" 12
buffer to search in
.IP "len" 12
length of buffer
.SH "DESCRIPTION"
This function returns offset of the first non-0xff byte in \fIbuf\fP or -1 if
the buffer contains only 0xff bytes.
