.TH "first_dirty_cnode" 9 "first_dirty_cnode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
first_dirty_cnode \- find first dirty cnode.
.SH SYNOPSIS
.B "struct ubifs_cnode *" first_dirty_cnode
.BI "(const struct ubifs_info *c "  ","
.BI "struct ubifs_nnode *nnode "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "nnode" 12
nnode at which to start
.SH "DESCRIPTION"
This function returns the first dirty cnode or NULL if there is not one.
