.TH "flexonenand_get_size" 9 "flexonenand_get_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
flexonenand_get_size \- Fill up fields in onenand_chip and mtd_info boundary[], diesize[], mtd->size, mtd->erasesize
.SH SYNOPSIS
.B "void" flexonenand_get_size
.BI "(struct mtd_info *mtd "  ");"
.SH ARGUMENTS
.IP "mtd" 12
- MTD device structure
