.TH "flexonenand_addr" 9 "flexonenand_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
flexonenand_addr \- Return address of the block
.SH SYNOPSIS
.B "loff_t" flexonenand_addr
.BI "(struct onenand_chip *this "  ","
.BI "int block "  ");"
.SH ARGUMENTS
.IP "this" 12
OneNAND device structure
.IP "block" 12
Block number on Flex-OneNAND
.SH "DESCRIPTION"
Return address of the block
