.TH "fm10k_fifo_enqueue" 9 "fm10k_fifo_enqueue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_fifo_enqueue \- Enqueues the message to the tail of the FIFO
.SH SYNOPSIS
.B "s32" fm10k_fifo_enqueue
.BI "(struct fm10k_mbx_fifo *fifo "  ","
.BI "const u32 *msg "  ");"
.SH ARGUMENTS
.IP "fifo" 12
pointer to FIFO
.IP "msg" 12
message array to read

This function enqueues a message up to the size specified by the length
contained in the first DWORD of the message and will place at the tail
of the FIFO.  It will return 0 on success, or a negative value on error.
