.TH "fm10k_qv_free_irq" 9 "fm10k_qv_free_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_qv_free_irq \- release interrupts associated with queue vectors
.SH SYNOPSIS
.B "void" fm10k_qv_free_irq
.BI "(struct fm10k_intfc *interface "  ");"
.SH ARGUMENTS
.IP "interface" 12
board private structure
.SH "DESCRIPTION"
Release all interrupts associated with this interface
