.TH "fm10k_configure_swpri_map" 9 "fm10k_configure_swpri_map" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_configure_swpri_map \- Configure Receive SWPRI to PC mapping
.SH SYNOPSIS
.B "void" fm10k_configure_swpri_map
.BI "(struct fm10k_intfc *interface "  ");"
.SH ARGUMENTS
.IP "interface" 12
board private structure
.SH "DESCRIPTION"
Configure the SWPRI to PC mapping for the port.
