.TH "fm10k_mbx_head_sub" 9 "fm10k_mbx_head_sub" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_mbx_head_sub \- Determine new head value with subtracted offset
.SH SYNOPSIS
.B "u16" fm10k_mbx_head_sub
.BI "(struct fm10k_mbx_info *mbx "  ","
.BI "u16 offset "  ");"
.SH ARGUMENTS
.IP "mbx" 12
pointer to mailbox
.IP "offset" 12
length to add to head offset

This function takes the local head index and recomputes it for
a given length added as an offset.
