.TH "fm10k_tlv_attr_get_null_string" 9 "fm10k_tlv_attr_get_null_string" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_tlv_attr_get_null_string \- Get null terminated string from attribute
.SH SYNOPSIS
.B "s32" fm10k_tlv_attr_get_null_string
.BI "(u32 *attr "  ","
.BI "unsigned char *string "  ");"
.SH ARGUMENTS
.IP "attr" 12
Pointer to attribute
.IP "string" 12
Pointer to location of destination string

This function pulls the string back out of the attribute and will place
it in the array pointed by by string.  It will return success if provided
with a valid pointers.
