.TH "fm10k_mbx_tail_sub" 9 "fm10k_mbx_tail_sub" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fm10k_mbx_tail_sub \- Determine new tail value with subtracted offset
.SH SYNOPSIS
.B "u16" fm10k_mbx_tail_sub
.BI "(struct fm10k_mbx_info *mbx "  ","
.BI "u16 offset "  ");"
.SH ARGUMENTS
.IP "mbx" 12
pointer to mailbox
.IP "offset" 12
length to add to tail offset

This function takes the local tail index and recomputes it for
a given length added as an offset.
