.TH "fman_port_get_device" 9 "fman_port_get_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fman_port_get_device \- 
.SH SYNOPSIS
.B "struct device *" fman_port_get_device
.BI "(struct fman_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
Pointer to the FMan port device
.SH "DESCRIPTION"
Get the 'struct device' associated to the specified FMan port device
.SH "RETURN"
pointer to associated 'struct device'
