.TH "frame_vector_create" 9 "frame_vector_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
frame_vector_create \- allocate & initialize structure for pinned pfns
.SH SYNOPSIS
.B "struct frame_vector *" frame_vector_create
.BI "(unsigned int nr_frames "  ");"
.SH ARGUMENTS
.IP "nr_frames" 12
number of pfns slots we should reserve
.SH "DESCRIPTION"
Allocate and initialize struct pinned_pfns to be able to hold \fInr_pfns\fP
pfns.
