.TH "frame_vector_to_pfns" 9 "frame_vector_to_pfns" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
frame_vector_to_pfns \- convert frame vector to contain pfns
.SH SYNOPSIS
.B "void" frame_vector_to_pfns
.BI "(struct frame_vector *vec "  ");"
.SH ARGUMENTS
.IP "vec" 12
frame vector to convert
.SH "DESCRIPTION"
Convert \fIvec\fP to contain array of pfns.
