.TH "freezer_apply_state" 9 "freezer_apply_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
freezer_apply_state \- apply state change to a single cgroup_freezer
.SH SYNOPSIS
.B "void" freezer_apply_state
.BI "(struct freezer *freezer "  ","
.BI "bool freeze "  ","
.BI "unsigned int state "  ");"
.SH ARGUMENTS
.IP "freezer" 12
freezer to apply state change to
.IP "freeze" 12
whether to freeze or unfreeze
.IP "state" 12
CGROUP_FREEZING_* flag to set or clear
.SH "DESCRIPTION"
Set or clear \fIstate\fP on \fIcgroup\fP according to \fIfreeze\fP, and perform
freezing or thawing as necessary.
