.TH "free_image_page" 9 "free_image_page" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
free_image_page \- Free a page allocated for hibernation image.
.SH SYNOPSIS
.B "void" free_image_page
.BI "(void *addr "  ","
.BI "int clear_nosave_free "  ");"
.SH ARGUMENTS
.IP "addr" 12
Address of the page to free.
.IP "clear_nosave_free" 12
If set, clear the PageNosaveFree bit for the page.
.SH "DESCRIPTION"
The page to free should have been allocated by \fBget_image_page\fP (page flags
set by it are affected).
