.TH "fsl_rio_tx_handler" 9 "fsl_rio_tx_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fsl_rio_tx_handler \- MPC85xx outbound message interrupt handler
.SH SYNOPSIS
.B "irqreturn_t" fsl_rio_tx_handler
.BI "(int irq "  ","
.BI "void *dev_instance "  ");"
.SH ARGUMENTS
.IP "irq" 12
Linux interrupt number
.IP "dev_instance" 12
Pointer to interrupt-specific data
.SH "DESCRIPTION"
Handles outbound message interrupts. Executes a register outbound
mailbox event handler and acks the interrupt occurrence.
