.TH "fsl_diu_name_to_port" 9 "fsl_diu_name_to_port" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fsl_diu_name_to_port \- convert a port name to a monitor port enum
.SH SYNOPSIS
.B "enum fsl_diu_monitor_port" fsl_diu_name_to_port
.BI "(const char *s "  ");"
.SH ARGUMENTS
.IP "s" 12
-- undescribed --
.SH "DESCRIPTION"

Takes the name of a monitor port ("dvi", "lvds", or "dlvds") and returns
the enum fsl_diu_monitor_port that corresponds to that string.

For compatibility with older versions, a number ("0", "1", or "2") is also
supported.

If the string is unknown, DVI is assumed.

If the particular port is not supported by the platform, another port
(platform-specific) is chosen instead.
