.TH "fsldma_run_tx_complete_actions" 9 "fsldma_run_tx_complete_actions" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fsldma_run_tx_complete_actions \- cleanup a single link descriptor
.SH SYNOPSIS
.B "dma_cookie_t" fsldma_run_tx_complete_actions
.BI "(struct fsldma_chan *chan "  ","
.BI "struct fsl_desc_sw *desc "  ","
.BI "dma_cookie_t cookie "  ");"
.SH ARGUMENTS
.IP "chan" 12
Freescale DMA channel
.IP "desc" 12
descriptor to cleanup and free
.IP "cookie" 12
Freescale DMA transaction identifier
.SH "DESCRIPTION"
This function is used on a descriptor which has been executed by the DMA
controller. It will run any callbacks, submit any dependencies.
