.TH "fsverity_ioctl_enable" 9 "fsverity_ioctl_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fsverity_ioctl_enable \- enable verity on a file
.SH SYNOPSIS
.B "int" fsverity_ioctl_enable
.BI "(struct file *filp "  ","
.BI "const void __user *uarg "  ");"
.SH ARGUMENTS
.IP "filp" 12
file to enable verity on
.IP "uarg" 12
user pointer to fsverity_enable_arg
.SH "DESCRIPTION"
Enable fs-verity on a file.  See the "FS_IOC_ENABLE_VERITY" section of
Documentation/filesystems/fsverity.rst for the documentation.
.SH "RETURN"
0 on success, -errno on failure
