.TH "ftrace_graph_is_dead" 9 "ftrace_graph_is_dead" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ftrace_graph_is_dead \- returns true if ftrace_graph_stop() was called
.SH SYNOPSIS
.B "bool" ftrace_graph_is_dead
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

\fBftrace_graph_stop\fP is called when a severe error is detected in
the function graph tracing. This function is called by the critical
paths of function graph to keep those paths from doing any more harm.
