.TH "ftrace_func_mapper_remove_ip" 9 "ftrace_func_mapper_remove_ip" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ftrace_func_mapper_remove_ip \- Remove an ip from the mapping
.SH SYNOPSIS
.B "void *" ftrace_func_mapper_remove_ip
.BI "(struct ftrace_func_mapper *mapper "  ","
.BI "unsigned long ip "  ");"
.SH ARGUMENTS
.IP "mapper" 12
The mapper that has the ip maps
.IP "ip" 12
The instruction pointer address to remove the data from
.SH "DESCRIPTION"
Returns the data if it is found, otherwise NULL.
Note, if the data pointer is used as the data itself, (see 
\fBftrace_func_mapper_find_ip\fP, then the return value may be meaningless,
if the data pointer was set to zero.
