.TH "ftrace_get_addr_new" 9 "ftrace_get_addr_new" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ftrace_get_addr_new \- Get the call address to set to
.SH SYNOPSIS
.B "unsigned long" ftrace_get_addr_new
.BI "(struct dyn_ftrace *rec "  ");"
.SH ARGUMENTS
.IP "rec" 12
The ftrace record descriptor
.SH "DESCRIPTION"
If the record has the FTRACE_FL_REGS set, that means that it
wants to convert to a callback that saves all regs. If FTRACE_FL_REGS
is not set, then it wants to convert to the normal callback.

Returns the address of the trampoline to set to
