.TH "fw_load_sysfs_fallback" 9 "fw_load_sysfs_fallback" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fw_load_sysfs_fallback \- load a firmware via the sysfs fallback mechanism
.SH SYNOPSIS
.B "int" fw_load_sysfs_fallback
.BI "(struct fw_sysfs *fw_sysfs "  ","
.BI "long timeout "  ");"
.SH ARGUMENTS
.IP "fw_sysfs" 12
firmware sysfs information for the firmware to load
.IP "timeout" 12
timeout to wait for the load
.SH "DESCRIPTION"
In charge of constructing a sysfs fallback interface for firmware loading.
