.TH "fwcaps32_to_caps16" 9 "fwcaps32_to_caps16" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fwcaps32_to_caps16 \- convert 32-bit Port Capabilities to 16-bits
.SH SYNOPSIS
.B "fw_port_cap16_t" fwcaps32_to_caps16
.BI "(fw_port_cap32_t caps32 "  ");"
.SH ARGUMENTS
.IP "caps32" 12
a 32-bit Port Capabilities value

Returns the equivalent 16-bit Port Capabilities value.  Note that
not all 32-bit Port Capabilities can be represented in the 16-bit
Port Capabilities and some fields/values may not make it.
