.TH "fwnode_graph_parse_endpoint" 9 "fwnode_graph_parse_endpoint" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fwnode_graph_parse_endpoint \- parse common endpoint node properties
.SH SYNOPSIS
.B "int" fwnode_graph_parse_endpoint
.BI "(const struct fwnode_handle *fwnode "  ","
.BI "struct fwnode_endpoint *endpoint "  ");"
.SH ARGUMENTS
.IP "fwnode" 12
pointer to endpoint fwnode_handle
.IP "endpoint" 12
pointer to the fwnode endpoint data structure
.SH "DESCRIPTION"
Parse \fIfwnode\fP representing a graph endpoint node and store the
information in \fIendpoint\fP. The caller must hold a reference to
\fIfwnode\fP.
