.TH "fwnode_get_named_child_node" 9 "fwnode_get_named_child_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
fwnode_get_named_child_node \- Return first matching named child node handle
.SH SYNOPSIS
.B "struct fwnode_handle *" fwnode_get_named_child_node
.BI "(const struct fwnode_handle *fwnode "  ","
.BI "const char *childname "  ");"
.SH ARGUMENTS
.IP "fwnode" 12
Firmware node to find the named child node for.
.IP "childname" 12
String to match child node name against.
