.TH "gaudi_init_protection_bits" 9 "gaudi_init_protection_bits" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gaudi_init_protection_bits \- Initialize protection bits of specific registers
.SH SYNOPSIS
.B "void" gaudi_init_protection_bits
.BI "(struct hl_device *hdev "  ");"
.SH ARGUMENTS
.IP "hdev" 12
pointer to hl_device structure
.SH "DESCRIPTION"
All protection bits are 1 by default, means not protected. Need to set to 0
each bit that belongs to a protected register.
