.TH "gelic_card_disable_txdmac" 9 "gelic_card_disable_txdmac" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gelic_card_disable_txdmac \- disables the transmit DMA controller
.SH SYNOPSIS
.B "void" gelic_card_disable_txdmac
.BI "(struct gelic_card *card "  ");"
.SH ARGUMENTS
.IP "card" 12
card structure
.SH "DESCRIPTION"
gelic_card_disable_txdmac terminates processing on the DMA controller by
turing off DMA and issuing a force end
