.TH "gelic_card_decode_one_descr" 9 "gelic_card_decode_one_descr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gelic_card_decode_one_descr \- processes an rx descriptor
.SH SYNOPSIS
.B "int" gelic_card_decode_one_descr
.BI "(struct gelic_card *card "  ");"
.SH ARGUMENTS
.IP "card" 12
card structure
.SH "DESCRIPTION"
returns 1 if a packet has been sent to the stack, otherwise 0

processes an rx descriptor by iommu-unmapping the data buffer and passing
the packet up to the stack
