.TH "geni_se_rx_dma_prep" 9 "geni_se_rx_dma_prep" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
geni_se_rx_dma_prep \- Prepare the serial engine for RX DMA transfer
.SH SYNOPSIS
.B "int" geni_se_rx_dma_prep
.BI "(struct geni_se *se "  ","
.BI "void *buf "  ","
.BI "size_t len "  ","
.BI "dma_addr_t *iova "  ");"
.SH ARGUMENTS
.IP "se" 12
Pointer to the concerned serial engine.
.IP "buf" 12
Pointer to the RX buffer.
.IP "len" 12
Length of the RX buffer.
.IP "iova" 12
Pointer to store the mapped DMA address.
.SH "DESCRIPTION"
This function is used to prepare the buffers for DMA RX.
.SH "RETURN"
0 on success, standard Linux error codes on failure.
