.TH "geni_se_resources_on" 9 "geni_se_resources_on" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
geni_se_resources_on \- Turn on resources associated with the serial engine
.SH SYNOPSIS
.B "int" geni_se_resources_on
.BI "(struct geni_se *se "  ");"
.SH ARGUMENTS
.IP "se" 12
Pointer to the concerned serial engine.
.SH "RETURN"
0 on success, standard Linux error codes on failure/error.
