.TH "genphy_read_abilities" 9 "genphy_read_abilities" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genphy_read_abilities \- read PHY abilities from Clause 22 registers
.SH SYNOPSIS
.B "int" genphy_read_abilities
.BI "(struct phy_device *phydev "  ");"
.SH ARGUMENTS
.IP "phydev" 12
target phy_device struct
.SH "DESCRIPTION"
Reads the PHY's abilities and populates
phydev->supported accordingly.
.SH "RETURN"
0 on success, < 0 on failure
