.TH "genphy_update_link" 9 "genphy_update_link" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genphy_update_link \- update link status in @phydev
.SH SYNOPSIS
.B "int" genphy_update_link
.BI "(struct phy_device *phydev "  ");"
.SH ARGUMENTS
.IP "phydev" 12
target phy_device struct
.SH "DESCRIPTION"
Update the value in phydev->link to reflect the
current link value.  In order to do this, we need to read
the status register twice, keeping the second value.
