.TH "genwqe_check_ddcb_queue" 9 "genwqe_check_ddcb_queue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genwqe_check_ddcb_queue \- Checks DDCB queue for completed work equests.
.SH SYNOPSIS
.B "int" genwqe_check_ddcb_queue
.BI "(struct genwqe_dev *cd "  ","
.BI "struct ddcb_queue *queue "  ");"
.SH ARGUMENTS
.IP "cd" 12
pointer to genwqe device descriptor
.IP "queue" 12
queue to be checked
.SH "RETURN"
Number of DDCBs which were finished
