.TH "genwqe_dev_alloc" 9 "genwqe_dev_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genwqe_dev_alloc \- Create and prepare a new card descriptor
.SH SYNOPSIS
.B "struct genwqe_dev *" genwqe_dev_alloc
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
Pointer to card descriptor, or ERR_PTR(err) on error
