.TH "genwqe_remove" 9 "genwqe_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
genwqe_remove \- Called when device is removed (hot-plugable)
.SH SYNOPSIS
.B "void" genwqe_remove
.BI "(struct pci_dev *pci_dev "  ");"
.SH ARGUMENTS
.IP "pci_dev" 12
PCI device information struct
.SH "DESCRIPTION"
Or when driver is unloaded respecitively when unbind is done.
