.TH "get_cmdline" 9 "get_cmdline" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_cmdline \- copy the cmdline value to a buffer.
.SH SYNOPSIS
.B "int" get_cmdline
.BI "(struct task_struct *task "  ","
.BI "char *buffer "  ","
.BI "int buflen "  ");"
.SH ARGUMENTS
.IP "task" 12
the task whose cmdline value to copy.
.IP "buffer" 12
the buffer to copy to.
.IP "buflen" 12
the length of the buffer. Larger cmdline values are truncated
to this length.
.SH "RETURN"
the size of the cmdline field copied. Note that the copy does
not guarantee an ending NULL byte.
