.TH "get_int_prop" 9 "get_int_prop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_int_prop \- Decode a u32 from a device tree property
.SH SYNOPSIS
.B "u32" get_int_prop
.BI "(struct device_node *np "  ","
.BI "const char *name "  ","
.BI "u32 def "  ");"
.SH ARGUMENTS
.IP "np" 12
-- undescribed --
.IP "name" 12
-- undescribed --
.IP "def" 12
-- undescribed --
