.TH "get_free_pending_entry" 9 "get_free_pending_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_free_pending_entry \- get free entry from pending queue @param pqinfo: pending_qinfo structure @param qno: queue number
.SH SYNOPSIS
.B "struct pending_entry *" get_free_pending_entry
.BI "(struct pending_queue *q "  ","
.BI "int qlen "  ");"
.SH ARGUMENTS
.IP "q" 12
-- undescribed --
.IP "qlen" 12
-- undescribed --
