.TH "get_next_path_rr" 9 "get_next_path_rr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_next_path_rr \- Returns path in round-robin fashion.
.SH SYNOPSIS
.B "struct rtrs_clt_sess *" get_next_path_rr
.BI "(struct path_it *it "  ");"
.SH ARGUMENTS
.IP "it" 12
the path pointer
.SH "DESCRIPTION"
Related to \fIMP_POLICY_RR\fP

Locks:
\fBrcu_read_lock\fP must be hold.
