.TH "get_linkdowndefaultstate" 9 "get_linkdowndefaultstate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_linkdowndefaultstate \- get the default linkdown state
.SH SYNOPSIS
.B "int" get_linkdowndefaultstate
.BI "(struct qib_pportdata *ppd "  ");"
.SH ARGUMENTS
.IP "ppd" 12
the physical port data
.SH "DESCRIPTION"
Returns zero if the default is POLL, 1 if the default is SLEEP.
