.TH "get_pcc_channel" 9 "get_pcc_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_pcc_channel \- Given a PCC subspace idx, get the respective mbox_channel.
.SH SYNOPSIS
.B "struct mbox_chan *" get_pcc_channel
.BI "(int id "  ");"
.SH ARGUMENTS
.IP "id" 12
PCC subspace index.
.SH "RETURN"
ERR_PTR(errno) if error, else pointer
to mbox channel.
