.TH "get_desc" 9 "get_desc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_desc \- Obtain contents of a segment descriptor
.SH SYNOPSIS
.B "bool" get_desc
.BI "(struct desc_struct *out "  ","
.BI "unsigned short sel "  ");"
.SH ARGUMENTS
.IP "out" 12
Segment descriptor contents on success
.IP "sel" 12
Segment selector
.SH "DESCRIPTION"
Given a segment selector, obtain a pointer to the segment descriptor.
Both global and local descriptor tables are supported.

True on success, false on failure.

NULL on error.
.SH "RETURN"
