.TH "get_fsp_rec_tov" 9 "get_fsp_rec_tov" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
get_fsp_rec_tov \- Helper function to get REC_TOV
.SH SYNOPSIS
.B "unsigned int" get_fsp_rec_tov
.BI "(struct fc_fcp_pkt *fsp "  ");"
.SH ARGUMENTS
.IP "fsp" 12
the FCP packet
.SH "DESCRIPTION"
Returns rec tov in jiffies as rpriv->e_d_tov + 1 second
