.TH "gfs2_meta_read" 9 "gfs2_meta_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_meta_read \- Read a block from disk
.SH SYNOPSIS
.B "int" gfs2_meta_read
.BI "(struct gfs2_glock *gl "  ","
.BI "u64 blkno "  ","
.BI "int flags "  ","
.BI "int rahead "  ","
.BI "struct buffer_head **bhp "  ");"
.SH ARGUMENTS
.IP "gl" 12
The glock covering the block
.IP "blkno" 12
The block number
.IP "flags" 12
flags
.IP "rahead" 12
-- undescribed --
.IP "bhp" 12
the place where the buffer is returned (NULL on failure)
.SH "RETURN"
errno
