.TH "gfs2_lock_fs_check_clean" 9 "gfs2_lock_fs_check_clean" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_lock_fs_check_clean \- Stop all writes to the FS and check that all journals are clean
.SH SYNOPSIS
.B "int" gfs2_lock_fs_check_clean
.BI "(struct gfs2_sbd *sdp "  ");"
.SH ARGUMENTS
.IP "sdp" 12
the file system
.SH "RETURN"
errno
