.TH "gfs2_rgrpd_get_next" 9 "gfs2_rgrpd_get_next" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_rgrpd_get_next \- get the next RG
.SH SYNOPSIS
.B "struct gfs2_rgrpd *" gfs2_rgrpd_get_next
.BI "(struct gfs2_rgrpd *rgd "  ");"
.SH ARGUMENTS
.IP "rgd" 12
the resource group descriptor
.SH "RETURN"
The next rgrp
