.TH "gfs2_jdata_writepages" 9 "gfs2_jdata_writepages" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_jdata_writepages \- Write a bunch of dirty pages back to disk
.SH SYNOPSIS
.B "int" gfs2_jdata_writepages
.BI "(struct address_space *mapping "  ","
.BI "struct writeback_control *wbc "  ");"
.SH ARGUMENTS
.IP "mapping" 12
The mapping to write
.IP "wbc" 12
The writeback control
