.TH "gfs2_permission" 9 "gfs2_permission" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_permission \- 
.SH SYNOPSIS
.B "int" gfs2_permission
.BI "(struct user_namespace *mnt_userns "  ","
.BI "struct inode *inode "  ","
.BI "int mask "  ");"
.SH ARGUMENTS
.IP "mnt_userns" 12
-- undescribed --
.IP "inode" 12
The inode
.IP "mask" 12
The mask to be tested
.SH "DESCRIPTION"
This may be called from the VFS directly, or from within GFS2 with the
inode locked, so we look to see if the glock is already locked and only
lock the glock if its not already been done.
.SH "RETURN"
errno
