.TH "gfs2_drevalidate" 9 "gfs2_drevalidate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_drevalidate \- Check directory lookup consistency
.SH SYNOPSIS
.B "int" gfs2_drevalidate
.BI "(struct dentry *dentry "  ","
.BI "unsigned int flags "  ");"
.SH ARGUMENTS
.IP "dentry" 12
the mapping to check
.IP "flags" 12
lookup flags
.SH "DESCRIPTION"
Check to make sure the lookup necessary to arrive at this inode from its
parent is still good.
.SH "RETURN"
1 if the dentry is ok, 0 if it isn't
