.TH "gfs2_free_meta" 9 "gfs2_free_meta" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfs2_free_meta \- free a contiguous run of data block(s)
.SH SYNOPSIS
.B "void" gfs2_free_meta
.BI "(struct gfs2_inode *ip "  ","
.BI "struct gfs2_rgrpd *rgd "  ","
.BI "u64 bstart "  ","
.BI "u32 blen "  ");"
.SH ARGUMENTS
.IP "ip" 12
the inode these blocks are being freed from
.IP "rgd" 12
the resource group the blocks are in
.IP "bstart" 12
first block of a run of contiguous blocks
.IP "blen" 12
the length of the block run
