.TH "gfx_v7_0_init_compute_vmid" 9 "gfx_v7_0_init_compute_vmid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfx_v7_0_init_compute_vmid \- gart enable
.SH SYNOPSIS
.B "void" gfx_v7_0_init_compute_vmid
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Initialize compute vmid sh_mem registers
