.TH "gfx_v7_0_rlc_stop" 9 "gfx_v7_0_rlc_stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gfx_v7_0_rlc_stop \- stop the RLC ME
.SH SYNOPSIS
.B "void" gfx_v7_0_rlc_stop
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Halt the RLC ME (MicroEngine) (CIK).
