.TH "gpiod_put" 9 "gpiod_put" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gpiod_put \- dispose of a GPIO descriptor
.SH SYNOPSIS
.B "void" gpiod_put
.BI "(struct gpio_desc *desc "  ");"
.SH ARGUMENTS
.IP "desc" 12
GPIO descriptor to dispose of
.SH "DESCRIPTION"
No descriptor can be used after \fBgpiod_put\fP has been called on it.
