.TH "gpiotools_set_values" 9 "gpiotools_set_values" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gpiotools_set_values \- Set the value of gpio(s)
.SH SYNOPSIS
.B "int" gpiotools_set_values
.BI "(const int fd "  ","
.BI "struct gpio_v2_line_values *values "  ");"
.SH ARGUMENTS
.IP "fd" 12
The fd returned by
\fBgpiotools_request_line\fP.
.IP "values" 12
The array of values want to set.
.SH "RETURN"
On success return 0;
On failure return the errno.
