.TH "gpiod_set_debounce" 9 "gpiod_set_debounce" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gpiod_set_debounce \- sets @debounce time for a GPIO
.SH SYNOPSIS
.B "int" gpiod_set_debounce
.BI "(struct gpio_desc *desc "  ","
.BI "unsigned int debounce "  ");"
.SH ARGUMENTS
.IP "desc" 12
descriptor of the GPIO for which to set debounce time
.IP "debounce" 12
debounce time in microseconds
.SH "RETURN"
0 on success, -ENOTSUPP if the controller doesn't support setting the
debounce time.
