.TH "gpiod_to_irq" 9 "gpiod_to_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gpiod_to_irq \- return the IRQ corresponding to a GPIO
.SH SYNOPSIS
.B "int" gpiod_to_irq
.BI "(const struct gpio_desc *desc "  ");"
.SH ARGUMENTS
.IP "desc" 12
gpio whose IRQ will be returned (already requested)
.SH "DESCRIPTION"
Return the IRQ corresponding to the passed GPIO, or an error code in case of
error.
