.TH "gsm_queue" 9 "gsm_queue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gsm_queue \- a GSM frame is ready to process
.SH SYNOPSIS
.B "void" gsm_queue
.BI "(struct gsm_mux *gsm "  ");"
.SH ARGUMENTS
.IP "gsm" 12
pointer to our gsm mux

At this point in time a frame has arrived and been demangled from
the line encoding. All the differences between the encodings have
been handled below us and the frame is unpacked into the structures.
The fcs holds the header FCS but any data FCS must be added here.
