.TH "gsm_control_rls" 9 "gsm_control_rls" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gsm_control_rls \- remote line status
.SH SYNOPSIS
.B "void" gsm_control_rls
.BI "(struct gsm_mux *gsm "  ","
.BI "const u8 *data "  ","
.BI "int clen "  ");"
.SH ARGUMENTS
.IP "gsm" 12
GSM channel
.IP "data" 12
data bytes
.IP "clen" 12
data length

The modem sends us a two byte message on the control channel whenever
it wishes to send us an error state from the virtual link. Stuff
this into the uplink tty if present
