.TH "gtm_put_timer16" 9 "gtm_put_timer16" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
gtm_put_timer16 \- release 16 bits GTM timer
.SH SYNOPSIS
.B "void" gtm_put_timer16
.BI "(struct gtm_timer *tmr "  ");"
.SH ARGUMENTS
.IP "tmr" 12
pointer to the gtm_timer structure obtained from gtm_get_timer
.SH "CONTEXT"
any
.SH "DESCRIPTION"
This function releases GTM timer so others may request it.
