.TH "handle_drvrcmd" 9 "handle_drvrcmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
handle_drvrcmd \- Checks if the opcode is a driver cmd and if it is, handles it.
.SH SYNOPSIS
.B "int" handle_drvrcmd
.BI "(void __user *arg "  ","
.BI "uint8_t old_ioctl "  ","
.BI "int *rval "  ");"
.SH ARGUMENTS
.IP "arg" 12
packet sent by the user app
.IP "old_ioctl" 12
mimd if 1; uioc otherwise
.IP "rval" 12
pointer for command's returned value (not function status)
