.TH "handle_event" 9 "handle_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
handle_event \- inbound virtqueue message workqueue function
.SH SYNOPSIS
.B "irqreturn_t" handle_event
.BI "(int irq "  ","
.BI "void *p "  ");"
.SH ARGUMENTS
.IP "irq" 12
-- undescribed --
.IP "p" 12
-- undescribed --
.SH "DESCRIPTION"

This function is registered as a kernel thread and is scheduled by the
kernel handler.
