.TH "hda_get_autocfg_input_label" 9 "hda_get_autocfg_input_label" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hda_get_autocfg_input_label \- Get a label for the given input
.SH SYNOPSIS
.B "const char *" hda_get_autocfg_input_label
.BI "(struct hda_codec *codec "  ","
.BI "const struct auto_pin_cfg *cfg "  ","
.BI "int input "  ");"
.SH ARGUMENTS
.IP "codec" 12
the HDA codec
.IP "cfg" 12
the parsed pin configuration
.IP "input" 12
the input index number
.SH "DESCRIPTION"
Get a label for the given input pin defined by the autocfg item.
Unlike \fBhda_get_input_pin_label\fP, this function checks all inputs
defined in autocfg and avoids the redundant mic/line prefix as much as
possible.
