.TH "hfa384x_cmd_wait" 9 "hfa384x_cmd_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hfa384x_cmd_wait \- Issue a Prism2 command and busy wait for completion
.SH SYNOPSIS
.B "int" hfa384x_cmd_wait
.BI "(struct net_device *dev "  ","
.BI "u16 cmd "  ","
.BI "u16 param0 "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to net_device
.IP "cmd" 12
Prism2 command code (HFA384X_CMD_CODE_*)
.IP "param0" 12
value for Param0 register
