.TH "hid_hw_close" 9 "hid_hw_close" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hid_hw_close \- signal underlaying HW to stop delivering events
.SH SYNOPSIS
.B "void" hid_hw_close
.BI "(struct hid_device *hdev "  ");"
.SH ARGUMENTS
.IP "hdev" 12
hid device
.SH "DESCRIPTION"
This function indicates that we are not interested in the events
from this device anymore. Delivery of events may or may not stop,
depending on the number of users still outstanding.
