.TH "hih6130_rh_ticks_to_per_cent_mille" 9 "hih6130_rh_ticks_to_per_cent_mille" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hih6130_rh_ticks_to_per_cent_mille \- convert raw humidity ticks to one-thousandths of a percent relative humidity
.SH SYNOPSIS
.B "int" hih6130_rh_ticks_to_per_cent_mille
.BI "(int ticks "  ");"
.SH ARGUMENTS
.IP "ticks" 12
humidity ticks value received from sensor
