.TH "hinic_init_txq" 9 "hinic_init_txq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_init_txq \- Initialize the Tx Queue
.SH SYNOPSIS
.B "int" hinic_init_txq
.BI "(struct hinic_txq *txq "  ","
.BI "struct hinic_sq *sq "  ","
.BI "struct net_device *netdev "  ");"
.SH ARGUMENTS
.IP "txq" 12
Logical Tx Queue
.IP "sq" 12
Hardware Tx Queue to connect the Logical queue with
.IP "netdev" 12
network device to connect the Logical queue with
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
