.TH "hinic_set_pf_action" 9 "hinic_set_pf_action" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_set_pf_action \- set action on pf channel
.SH SYNOPSIS
.B "void" hinic_set_pf_action
.BI "(struct hinic_hwif *hwif "  ","
.BI "enum hinic_pf_action action "  ");"
.SH ARGUMENTS
.IP "hwif" 12
the HW interface of a pci function device
.IP "action" 12
action on pf channel
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
