.TH "hinic_rq_write_wqe" 9 "hinic_rq_write_wqe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hinic_rq_write_wqe \- write the wqe to the rq
.SH SYNOPSIS
.B "void" hinic_rq_write_wqe
.BI "(struct hinic_rq *rq "  ","
.BI "u16 prod_idx "  ","
.BI "struct hinic_rq_wqe *rq_wqe "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "rq" 12
recv queue
.IP "prod_idx" 12
pi of the wqe
.IP "rq_wqe" 12
the wqe to write
.IP "skb" 12
skb to save
