.TH "hisi_qm_stop" 9 "hisi_qm_stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hisi_qm_stop \- Stop a qm.
.SH SYNOPSIS
.B "int" hisi_qm_stop
.BI "(struct hisi_qm *qm "  ","
.BI "enum qm_stop_reason r "  ");"
.SH ARGUMENTS
.IP "qm" 12
The qm which will be stopped.
.IP "r" 12
The reason to stop qm.
.SH "DESCRIPTION"
This function stops qm and its qps, then qm can not accept request.
Related resources are not released at this state, we can use hisi_qm_start
to let qm start again.
