.TH "hl_hw_block_mmap" 9 "hl_hw_block_mmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hl_hw_block_mmap \- mmap a hw block to user.
.SH SYNOPSIS
.B "int" hl_hw_block_mmap
.BI "(struct hl_fpriv *hpriv "  ","
.BI "struct vm_area_struct *vma "  ");"
.SH ARGUMENTS
.IP "hpriv" 12
pointer to the private data of the fd
.IP "vma" 12
pointer to vm_area_struct of the process
.SH "DESCRIPTION"
Driver increments context reference for every HW block mapped in order
to prevent user from closing FD without unmapping first
