.TH "hl_irq_handler_cq" 9 "hl_irq_handler_cq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hl_irq_handler_cq \- irq handler for completion queue
.SH SYNOPSIS
.B "irqreturn_t" hl_irq_handler_cq
.BI "(int irq "  ","
.BI "void *arg "  ");"
.SH ARGUMENTS
.IP "irq" 12
irq number
.IP "arg" 12
pointer to completion queue structure
