.TH "hl_pci_bars_map" 9 "hl_pci_bars_map" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hl_pci_bars_map \- Map PCI BARs.
.SH SYNOPSIS
.B "int" hl_pci_bars_map
.BI "(struct hl_device *hdev "  ","
.BI "const char * const name[3] "  ","
.BI "bool is_wc[3] "  ");"
.SH ARGUMENTS
.IP "hdev" 12
Pointer to hl_device structure.
.IP "name" 12
Array of BAR names.
.IP "is_wc" 12
Array with flag per BAR whether a write-combined mapping is needed.
.SH "DESCRIPTION"
Request PCI regions and map them to kernel virtual addresses.
.SH "RETURN"
0 on success, non-zero for failure.
