.TH "hmcdrv_ftp_shutdown" 9 "hmcdrv_ftp_shutdown" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hmcdrv_ftp_shutdown \- shutdown of HMC drive FTP functionality for a dedicated (owner) instance
.SH SYNOPSIS
.B "void" hmcdrv_ftp_shutdown
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
