.TH "hns_rcb_get_queue_mode" 9 "hns_rcb_get_queue_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hns_rcb_get_queue_mode \- get max VM number and max ring number per VM accordding to dsaf mode
.SH SYNOPSIS
.B "void" hns_rcb_get_queue_mode
.BI "(enum dsaf_mode dsaf_mode "  ","
.BI "u16 *max_vfn "  ","
.BI "u16 *max_q_per_vf "  ");"
.SH ARGUMENTS
.IP "dsaf_mode" 12
dsaf mode
.IP "max_vfn" 12
max vfn number
.IP "max_q_per_vf" 12
max ring number per vm
