.TH "hns_dsaf_tbl_line_cfg" 9 "hns_dsaf_tbl_line_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hns_dsaf_tbl_line_cfg \- tbl
.SH SYNOPSIS
.B "void" hns_dsaf_tbl_line_cfg
.BI "(struct dsaf_device *dsaf_dev "  ","
.BI "struct dsaf_tbl_line_cfg *tbl_lin "  ");"
.SH ARGUMENTS
.IP "dsaf_dev" 12
dsa fabric id
.IP "tbl_lin" 12
addr
