.TH "hns_dsaf_stp_port_type_cfg" 9 "hns_dsaf_stp_port_type_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hns_dsaf_stp_port_type_cfg \- cfg stp type
.SH SYNOPSIS
.B "void" hns_dsaf_stp_port_type_cfg
.BI "(struct dsaf_device *dsaf_dev "  ","
.BI "enum dsaf_stp_port_type port_type "  ");"
.SH ARGUMENTS
.IP "dsaf_dev" 12
dsa fabric id
.IP "port_type" 12
array
