.TH "hns_xgmac_rx_enable" 9 "hns_xgmac_rx_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hns_xgmac_rx_enable \- xgmac port rx enable
.SH SYNOPSIS
.B "void" hns_xgmac_rx_enable
.BI "(struct mac_driver *drv "  ","
.BI "u32 value "  ");"
.SH ARGUMENTS
.IP "drv" 12
mac driver
.IP "value" 12
value of enable
