.TH "hppb_probe" 9 "hppb_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hppb_probe \- Determine if the hppb driver should claim this device.
.SH SYNOPSIS
.B "int" hppb_probe
.BI "(struct parisc_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
The device which has been found
.SH "DESCRIPTION"
Determine if hppb driver should claim this chip (return 0) or not 
(return 1). If so, initialize the chip and tell other partners in crime 
they have work to do.
