.TH "hpt3xn_calibrate_dpll" 9 "hpt3xn_calibrate_dpll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hpt3xn_calibrate_dpll \- Calibrate the DPLL loop
.SH SYNOPSIS
.B "int" hpt3xn_calibrate_dpll
.BI "(struct pci_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
PCI device

Perform a calibration cycle on the HPT3xN DPLL. Returns 1 if this
succeeds
