.TH "hpt370_filter" 9 "hpt370_filter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hpt370_filter \- mode selection filter
.SH SYNOPSIS
.B "unsigned long" hpt370_filter
.BI "(struct ata_device *adev "  ","
.BI "unsigned long mask "  ");"
.SH ARGUMENTS
.IP "adev" 12
ATA device

Block UDMA on devices that cause trouble with this controller.
.IP "mask" 12
-- undescribed --
