.TH "hpt372n_filter" 9 "hpt372n_filter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hpt372n_filter \- mode selection filter
.SH SYNOPSIS
.B "unsigned long" hpt372n_filter
.BI "(struct ata_device *adev "  ","
.BI "unsigned long mask "  ");"
.SH ARGUMENTS
.IP "adev" 12
ATA device
.IP "mask" 12
mode mask

The Marvell bridge chips used on the HighPoint SATA cards do not seem
to support the UltraDMA modes 1, 2, and 3 as well as any MWDMA modes...
