.TH "hrtimer_get_next_event" 9 "hrtimer_get_next_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hrtimer_get_next_event \- get the time until next expiry event
.SH SYNOPSIS
.B "u64" hrtimer_get_next_event
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Returns the next expiry time or KTIME_MAX if no timer is pending.
