.TH "hvc_iucv_sndbuf_work" 9 "hvc_iucv_sndbuf_work" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hvc_iucv_sndbuf_work \- Send buffered data over IUCV
.SH SYNOPSIS
.B "void" hvc_iucv_sndbuf_work
.BI "(struct work_struct *work "  ");"
.SH ARGUMENTS
.IP "work" 12
Work structure.
.SH "DESCRIPTION"
This work queue function sends buffered output data over IUCV and,
if not all buffered data could be sent, reschedules itself.
