.TH "hvc_iucv_pm_restore_thaw" 9 "hvc_iucv_pm_restore_thaw" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hvc_iucv_pm_restore_thaw \- Thaw and restore PM callback
.SH SYNOPSIS
.B "int" hvc_iucv_pm_restore_thaw
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
IUVC HVC terminal device
.SH "DESCRIPTION"
Wake up the HVC thread to trigger hang-up and respective
HVC back-end notifier invocations.
