.TH "hw_add_wol_bcast" 9 "hw_add_wol_bcast" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hw_add_wol_bcast \- add broadcast pattern
.SH SYNOPSIS
.B "void" hw_add_wol_bcast
.BI "(struct ksz_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware instance.
.SH "DESCRIPTION"
This routine is used to add broadcast pattern for waking up the host.
