.TH "hw_breakpoint_slot_setup" 9 "hw_breakpoint_slot_setup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hw_breakpoint_slot_setup \- Find and setup a perf slot according to operations
.SH SYNOPSIS
.B "int" hw_breakpoint_slot_setup
.BI "(struct perf_event **slots "  ","
.BI "int max_slots "  ","
.BI "struct perf_event *bp "  ","
.BI "enum hw_breakpoint_ops ops "  ");"
.SH ARGUMENTS
.IP "slots" 12
pointer to array of slots
.IP "max_slots" 12
max number of slots
.IP "bp" 12
perf_event to setup
.IP "ops" 12
operation to be carried out on the slot
.SH "RETURN"
slot index on success
-ENOSPC if no slot is available/matches
-EINVAL on wrong operations parameter
