.TH "hw_set_desc_base" 9 "hw_set_desc_base" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hw_set_desc_base \- set descriptor base addresses
.SH SYNOPSIS
.B "void" hw_set_desc_base
.BI "(struct ksz_hw *hw "  ","
.BI "u32 tx_addr "  ","
.BI "u32 rx_addr "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware instance.
.IP "tx_addr" 12
The transmit descriptor base.
.IP "rx_addr" 12
The receive descriptor base.
.SH "DESCRIPTION"
This routine programs the descriptor base addresses after reset.
