.TH "hw_set_wol_frame" 9 "hw_set_wol_frame" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hw_set_wol_frame \- program Wake-on-LAN pattern
.SH SYNOPSIS
.B "void" hw_set_wol_frame
.BI "(struct ksz_hw *hw "  ","
.BI "int i "  ","
.BI "uint mask_size "  ","
.BI "const u8 *mask "  ","
.BI "uint frame_size "  ","
.BI "const u8 *pattern "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware instance.
.IP "i" 12
The frame index.
.IP "mask_size" 12
The size of the mask.
.IP "mask" 12
Mask to ignore certain bytes in the pattern.
.IP "frame_size" 12
The size of the frame.
.IP "pattern" 12
The frame data.
.SH "DESCRIPTION"
This routine is used to program Wake-on-LAN pattern.
