.TH "hwi_write_buffer" 9 "hwi_write_buffer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hwi_write_buffer \- Populate the WRB with task info
.SH SYNOPSIS
.B "int" hwi_write_buffer
.BI "(struct iscsi_wrb *pwrb "  ","
.BI "struct iscsi_task *task "  ");"
.SH ARGUMENTS
.IP "pwrb" 12
ptr to the WRB entry
.IP "task" 12
iscsi task which is to be executed
