.TH "hwif_ready" 9 "hwif_ready" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
hwif_ready \- test if the HW is ready for use
.SH SYNOPSIS
.B "int" hwif_ready
.BI "(struct hinic_hwif *hwif "  ");"
.SH ARGUMENTS
.IP "hwif" 12
the HW interface of a pci function device
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
