.TH "i2c_adapter_trylock_bus" 9 "i2c_adapter_trylock_bus" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i2c_adapter_trylock_bus \- Try to get exclusive access to an I2C bus segment
.SH SYNOPSIS
.B "int" i2c_adapter_trylock_bus
.BI "(struct i2c_adapter *adapter "  ","
.BI "unsigned int flags "  ");"
.SH ARGUMENTS
.IP "adapter" 12
Target I2C bus segment
.IP "flags" 12
I2C_LOCK_ROOT_ADAPTER trylocks the root i2c adapter, I2C_LOCK_SEGMENT
trylocks only this branch in the adapter tree
