.TH "i2c_detect_slave_mode" 9 "i2c_detect_slave_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i2c_detect_slave_mode \- detect operation mode
.SH SYNOPSIS
.B "bool" i2c_detect_slave_mode
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
The device owning the bus
.SH "DESCRIPTION"
This checks the device nodes for an I2C slave by checking the address
used in the reg property. If the address match the I2C_OWN_SLAVE_ADDRESS
flag this means the device is configured to act as a I2C slave and it will
be listening at that address.

Returns true if an I2C own slave address is detected, otherwise returns
false.
