.TH "i2c_smbus_read_block_data" 9 "i2c_smbus_read_block_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i2c_smbus_read_block_data \- SMBus "block read" protocol
.SH SYNOPSIS
.B "s32" i2c_smbus_read_block_data
.BI "(const struct i2c_client *client "  ","
.BI "u8 command "  ","
.BI "u8 *values "  ");"
.SH ARGUMENTS
.IP "client" 12
Handle to slave device
.IP "command" 12
Byte interpreted by slave
.IP "values" 12
Byte array into which data will be read; big enough to hold
the data returned by the slave.  SMBus allows at most 32 bytes.
.SH "DESCRIPTION"
This executes the SMBus "block read" protocol, returning negative errno
else the number of data bytes in the slave's response.

Note that using this function requires that the client's adapter support
the I2C_FUNC_SMBUS_READ_BLOCK_DATA functionality.  Not all adapter drivers
support this; its emulation through I2C messaging relies on a specific
mechanism (I2C_M_RECV_LEN) which may not be implemented.
