.TH "i2c_acpi_find_bus_speed" 9 "i2c_acpi_find_bus_speed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i2c_acpi_find_bus_speed \- find I2C bus speed from ACPI
.SH SYNOPSIS
.B "u32" i2c_acpi_find_bus_speed
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
The device owning the bus
.SH "DESCRIPTION"
Find the I2C bus speed by walking the ACPI namespace for all I2C slaves
devices connected to this bus and use the speed of slowest device.

Returns the speed in Hz or zero
