.TH "i3c_master_queue_ibi" 9 "i3c_master_queue_ibi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i3c_master_queue_ibi \- Queue an IBI
.SH SYNOPSIS
.B "void" i3c_master_queue_ibi
.BI "(struct i3c_dev_desc *dev "  ","
.BI "struct i3c_ibi_slot *slot "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device this IBI is coming from
.IP "slot" 12
the IBI slot used to store the payload
.SH "DESCRIPTION"
Queue an IBI to the controller workqueue. The IBI handler attached to
the dev will be called from a workqueue context.
