.TH "i40e_check_asq_alive" 9 "i40e_check_asq_alive" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_check_asq_alive \- 
.SH SYNOPSIS
.B "bool" i40e_check_asq_alive
.BI "(struct i40e_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hw struct
.SH "DESCRIPTION"
Returns true if Queue is enabled else false.
