.TH "i40e_dcbnl_ieee_setets" 9 "i40e_dcbnl_ieee_setets" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_dcbnl_ieee_setets \- set IEEE ETS configuration
.SH SYNOPSIS
.B "int" i40e_dcbnl_ieee_setets
.BI "(struct net_device *netdev "  ","
.BI "struct ieee_ets *ets "  ");"
.SH ARGUMENTS
.IP "netdev" 12
the corresponding netdev
.IP "ets" 12
structure to hold the ETS information
.SH "DESCRIPTION"
Set IEEE ETS configuration
