.TH "i40e_validate_vf" 9 "i40e_validate_vf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_validate_vf \- 
.SH SYNOPSIS
.B "int" i40e_validate_vf
.BI "(struct i40e_pf *pf "  ","
.BI "int vf_id "  ");"
.SH ARGUMENTS
.IP "pf" 12
the physical function
.IP "vf_id" 12
VF identifier
.SH "DESCRIPTION"
Check that the VF is enabled and the VSI exists.

Returns 0 on success, negative on failure
