.TH "i40e_ddp_profiles_eq" 9 "i40e_ddp_profiles_eq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_ddp_profiles_eq \- checks if DDP profiles are the equivalent
.SH SYNOPSIS
.B "bool" i40e_ddp_profiles_eq
.BI "(struct i40e_profile_info *a "  ","
.BI "struct i40e_profile_info *b "  ");"
.SH ARGUMENTS
.IP "a" 12
new profile info
.IP "b" 12
old profile info
.SH "DESCRIPTION"
checks if DDP profiles are the equivalent.
Returns true if profiles are the same.
