.TH "i40e_hw_dcb_config" 9 "i40e_hw_dcb_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_hw_dcb_config \- Program new DCBX settings into HW
.SH SYNOPSIS
.B "int" i40e_hw_dcb_config
.BI "(struct i40e_pf *pf "  ","
.BI "struct i40e_dcbx_config *new_cfg "  ");"
.SH ARGUMENTS
.IP "pf" 12
PF being configured
.IP "new_cfg" 12
New DCBX configuration
.SH "DESCRIPTION"
Program DCB settings into HW and reconfigure VEB/VSIs on
given PF
