.TH "i40e_config_rss" 9 "i40e_config_rss" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_config_rss \- Configure RSS keys and lut
.SH SYNOPSIS
.B "int" i40e_config_rss
.BI "(struct i40e_vsi *vsi "  ","
.BI "u8 *seed "  ","
.BI "u8 *lut "  ","
.BI "u16 lut_size "  ");"
.SH ARGUMENTS
.IP "vsi" 12
Pointer to VSI structure
.IP "seed" 12
RSS hash seed
.IP "lut" 12
Lookup table
.IP "lut_size" 12
Lookup table size
.SH "DESCRIPTION"
Returns 0 on success, negative on failure
