.TH "i40e_vsi_map_rings_to_vectors" 9 "i40e_vsi_map_rings_to_vectors" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_vsi_map_rings_to_vectors \- Maps descriptor rings to vectors
.SH SYNOPSIS
.B "void" i40e_vsi_map_rings_to_vectors
.BI "(struct i40e_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI being configured
.SH "DESCRIPTION"
This function maps descriptor rings to the queue-specific vectors
we were allotted through the MSI-X enabling code.  Ideally, we'd have
one vector per queue pair, but on a constrained vector budget, we
group the queue pairs as "efficiently" as possible.
