.TH "i40e_get_rx_buffer" 9 "i40e_get_rx_buffer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_get_rx_buffer \- Fetch Rx buffer and synchronize data for use
.SH SYNOPSIS
.B "struct i40e_rx_buffer *" i40e_get_rx_buffer
.BI "(struct i40e_ring *rx_ring "  ","
.BI "const unsigned int size "  ","
.BI "int *rx_buffer_pgcnt "  ");"
.SH ARGUMENTS
.IP "rx_ring" 12
rx descriptor ring to transact packets on
.IP "size" 12
size of buffer to add to skb
.IP "rx_buffer_pgcnt" 12
buffer page refcount
.SH "DESCRIPTION"
This function will pull an Rx buffer from the ring and synchronize it
for use by the CPU.
