.TH "i40e_dcbnl_find_app" 9 "i40e_dcbnl_find_app" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_dcbnl_find_app \- Search APP in given DCB config
.SH SYNOPSIS
.B "bool" i40e_dcbnl_find_app
.BI "(struct i40e_dcbx_config *cfg "  ","
.BI "struct i40e_dcb_app_priority_table *app "  ");"
.SH ARGUMENTS
.IP "cfg" 12
DCBX configuration data
.IP "app" 12
APP to search for
.SH "DESCRIPTION"
Find given APP in the DCB configuration
