.TH "i40e_ndo_set_vf_link_state" 9 "i40e_ndo_set_vf_link_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_ndo_set_vf_link_state \- 
.SH SYNOPSIS
.B "int" i40e_ndo_set_vf_link_state
.BI "(struct net_device *netdev "  ","
.BI "int vf_id "  ","
.BI "int link "  ");"
.SH ARGUMENTS
.IP "netdev" 12
network interface device structure
.IP "vf_id" 12
VF identifier
.IP "link" 12
required link state
.SH "DESCRIPTION"
Set the link state of a specified VF, regardless of physical link state
