.TH "i40e_dbg_dump_veb_seid" 9 "i40e_dbg_dump_veb_seid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_dbg_dump_veb_seid \- handles dump stats of a single given veb
.SH SYNOPSIS
.B "void" i40e_dbg_dump_veb_seid
.BI "(struct i40e_pf *pf "  ","
.BI "int seid "  ");"
.SH ARGUMENTS
.IP "pf" 12
the i40e_pf created in command write
.IP "seid" 12
the seid the user put in
