.TH "i40e_change_filter_num" 9 "i40e_change_filter_num" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_change_filter_num \- Prepare and program fdir filter
.SH SYNOPSIS
.B "void" i40e_change_filter_num
.BI "(bool ipv4 "  ","
.BI "bool add "  ","
.BI "u16 *ipv4_filter_num "  ","
.BI "u16 *ipv6_filter_num "  ");"
.SH ARGUMENTS
.IP "ipv4" 12
is layer 3 packet of version 4 or 6
.IP "add" 12
add or delete filter
.IP "ipv4_filter_num" 12
field to update
.IP "ipv6_filter_num" 12
field to update
.SH "DESCRIPTION"
Update filter number field for pf.
