.TH "i40e_vsi_free_q_vectors" 9 "i40e_vsi_free_q_vectors" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_vsi_free_q_vectors \- Free memory allocated for interrupt vectors
.SH SYNOPSIS
.B "void" i40e_vsi_free_q_vectors
.BI "(struct i40e_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI being un-configured
.SH "DESCRIPTION"
This frees the memory allocated to the q_vectors and
deletes references to the NAPI struct.
