.TH "i40e_vc_get_pf_queue_id" 9 "i40e_vc_get_pf_queue_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_vc_get_pf_queue_id \- 
.SH SYNOPSIS
.B "u16" i40e_vc_get_pf_queue_id
.BI "(struct i40e_vf *vf "  ","
.BI "u16 vsi_id "  ","
.BI "u8 vsi_queue_id "  ");"
.SH ARGUMENTS
.IP "vf" 12
pointer to the VF info
.IP "vsi_id" 12
id of VSI as provided by the FW
.IP "vsi_queue_id" 12
vsi relative queue id
.SH "DESCRIPTION"
return PF relative queue id
