.TH "i40e_dcbnl_ieee_getpfc" 9 "i40e_dcbnl_ieee_getpfc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_dcbnl_ieee_getpfc \- retrieve local IEEE PFC configuration
.SH SYNOPSIS
.B "int" i40e_dcbnl_ieee_getpfc
.BI "(struct net_device *dev "  ","
.BI "struct ieee_pfc *pfc "  ");"
.SH ARGUMENTS
.IP "dev" 12
the corresponding netdev
.IP "pfc" 12
structure to hold the PFC information
.SH "DESCRIPTION"
Returns local IEEE PFC configuration
