.TH "i40e_config_vf_promiscuous_mode" 9 "i40e_config_vf_promiscuous_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_config_vf_promiscuous_mode \- 
.SH SYNOPSIS
.B "i40e_status" i40e_config_vf_promiscuous_mode
.BI "(struct i40e_vf *vf "  ","
.BI "u16 vsi_id "  ","
.BI "bool allmulti "  ","
.BI "bool alluni "  ");"
.SH ARGUMENTS
.IP "vf" 12
pointer to the VF info
.IP "vsi_id" 12
VSI id
.IP "allmulti" 12
set MAC L2 layer multicast promiscuous enable/disable
.IP "alluni" 12
set MAC L2 layer unicast promiscuous enable/disable
.SH "DESCRIPTION"
Called from the VF to configure the promiscuous mode of
VF vsis and from the VF reset path to reset promiscuous mode.
