.TH "i40e_calculate_l2fpm_size" 9 "i40e_calculate_l2fpm_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_calculate_l2fpm_size \- calculates layer 2 FPM memory size
.SH SYNOPSIS
.B "u64" i40e_calculate_l2fpm_size
.BI "(u32 txq_num "  ","
.BI "u32 rxq_num "  ","
.BI "u32 fcoe_cntx_num "  ","
.BI "u32 fcoe_filt_num "  ");"
.SH ARGUMENTS
.IP "txq_num" 12
number of Tx queues needing backing context
.IP "rxq_num" 12
number of Rx queues needing backing context
.IP "fcoe_cntx_num" 12
amount of FCoE statefull contexts needing backing context
.IP "fcoe_filt_num" 12
number of FCoE filters needing backing context
.SH "DESCRIPTION"
Calculates the maximum amount of memory for the function required, based
on the number of resources it must provide context for.
