.TH "i40e_dbg_dump_vsi_no_seid" 9 "i40e_dbg_dump_vsi_no_seid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_dbg_dump_vsi_no_seid \- handles dump vsi write into command datum
.SH SYNOPSIS
.B "void" i40e_dbg_dump_vsi_no_seid
.BI "(struct i40e_pf *pf "  ");"
.SH ARGUMENTS
.IP "pf" 12
the i40e_pf created in command write
