.TH "i40e_init_msix" 9 "i40e_init_msix" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_init_msix \- Setup the MSIX capability
.SH SYNOPSIS
.B "int" i40e_init_msix
.BI "(struct i40e_pf *pf "  ");"
.SH ARGUMENTS
.IP "pf" 12
board private structure
.SH "DESCRIPTION"
Work with the OS to set up the MSIX vectors needed.

Returns the number of vectors reserved or negative on failure
