.TH "i40e_aq_get_link_info" 9 "i40e_aq_get_link_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_aq_get_link_info \- 
.SH SYNOPSIS
.B "i40e_status" i40e_aq_get_link_info
.BI "(struct i40e_hw *hw "  ","
.BI "bool enable_lse "  ","
.BI "struct i40e_link_status *link "  ","
.BI "struct i40e_asq_cmd_details *cmd_details "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hw struct
.IP "enable_lse" 12
enable/disable LinkStatusEvent reporting
.IP "link" 12
pointer to link status structure - optional
.IP "cmd_details" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Returns the link status of the adapter.
