.TH "i40e_dcb_hw_rx_ets_bw_config" 9 "i40e_dcb_hw_rx_ets_bw_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_dcb_hw_rx_ets_bw_config \- 
.SH SYNOPSIS
.B "void" i40e_dcb_hw_rx_ets_bw_config
.BI "(struct i40e_hw *hw "  ","
.BI "u8 *bw_share "  ","
.BI "u8 *mode "  ","
.BI "u8 *prio_type "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hw struct
.IP "bw_share" 12
Bandwidth share indexed per traffic class
.IP "mode" 12
Strict Priority or Round Robin mode between UP sharing same
traffic class
.IP "prio_type" 12
TC is ETS enabled or strict priority
.SH "DESCRIPTION"
Configure HW Rx ETS bandwidth as part of DCB configuration.
