.TH "i40e_ptp_feature_enable" 9 "i40e_ptp_feature_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_ptp_feature_enable \- Enable/disable ancillary features of the PHC subsystem
.SH SYNOPSIS
.B "int" i40e_ptp_feature_enable
.BI "(struct ptp_clock_info *ptp "  ","
.BI "struct ptp_clock_request *rq "  ","
.BI "int on "  ");"
.SH ARGUMENTS
.IP "ptp" 12
The PTP clock structure
.IP "rq" 12
The requested feature to change
.IP "on" 12
Enable/disable flag
.SH "DESCRIPTION"
The XL710 does not support any of the ancillary features of the PHC
subsystem, so this function may just return.
