.TH "i40e_vsi_setup_queue_map" 9 "i40e_vsi_setup_queue_map" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_vsi_setup_queue_map \- Setup a VSI queue map based on enabled_tc
.SH SYNOPSIS
.B "void" i40e_vsi_setup_queue_map
.BI "(struct i40e_vsi *vsi "  ","
.BI "struct i40e_vsi_context *ctxt "  ","
.BI "u8 enabled_tc "  ","
.BI "bool is_add "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI being setup
.IP "ctxt" 12
VSI context structure
.IP "enabled_tc" 12
Enabled TCs bitmap
.IP "is_add" 12
True if called before Add VSI
.SH "DESCRIPTION"
Setup VSI queue mapping for enabled traffic classes.
