.TH "i40e_config_rss_aq" 9 "i40e_config_rss_aq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_config_rss_aq \- Prepare for RSS using AQ commands
.SH SYNOPSIS
.B "int" i40e_config_rss_aq
.BI "(struct i40e_vsi *vsi "  ","
.BI "const u8 *seed "  ","
.BI "u8 *lut "  ","
.BI "u16 lut_size "  ");"
.SH ARGUMENTS
.IP "vsi" 12
vsi structure
.IP "seed" 12
RSS hash seed
.IP "lut" 12
pointer to lookup table of lut_size
.IP "lut_size" 12
size of the lookup table
