.TH "i40e_alloc_vfs" 9 "i40e_alloc_vfs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_alloc_vfs \- 
.SH SYNOPSIS
.B "int" i40e_alloc_vfs
.BI "(struct i40e_pf *pf "  ","
.BI "u16 num_alloc_vfs "  ");"
.SH ARGUMENTS
.IP "pf" 12
pointer to the PF structure
.IP "num_alloc_vfs" 12
number of VFs to allocate
.SH "DESCRIPTION"
allocate VF resources
