.TH "i40e_notify_client_of_vf_msg" 9 "i40e_notify_client_of_vf_msg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_notify_client_of_vf_msg \- call the client vf message callback
.SH SYNOPSIS
.B "void" i40e_notify_client_of_vf_msg
.BI "(struct i40e_vsi *vsi "  ","
.BI "u32 vf_id "  ","
.BI "u8 *msg "  ","
.BI "u16 len "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI with the message
.IP "vf_id" 12
the absolute VF id that sent the message
.IP "msg" 12
message buffer
.IP "len" 12
length of the message
.SH "DESCRIPTION"
If there is a client to this VSI, call the client
