.TH "i40e_init_arq" 9 "i40e_init_arq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_init_arq \- initialize ARQ
.SH SYNOPSIS
.B "i40e_status" i40e_init_arq
.BI "(struct i40e_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure

The main initialization routine for the Admin Receive (Event) Queue.
Prior to calling this function, drivers *MUST* set the following fields
in the hw->aq structure:
- hw->aq.num_asq_entries
- hw->aq.arq_buf_size

Do *NOT* hold the lock when calling this as the memory allocation routines
called are not going to be atomic context safe
