.TH "i40e_parse_cee_pgcfg_tlv" 9 "i40e_parse_cee_pgcfg_tlv" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_parse_cee_pgcfg_tlv \- 
.SH SYNOPSIS
.B "void" i40e_parse_cee_pgcfg_tlv
.BI "(struct i40e_cee_feat_tlv *tlv "  ","
.BI "struct i40e_dcbx_config *dcbcfg "  ");"
.SH ARGUMENTS
.IP "tlv" 12
CEE DCBX PG CFG TLV
.IP "dcbcfg" 12
Local store to update ETS CFG data
.SH "DESCRIPTION"
Parses CEE DCBX PG CFG TLV
