.TH "i40e_free_macvlan_channels" 9 "i40e_free_macvlan_channels" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_free_macvlan_channels \- 
.SH SYNOPSIS
.B "void" i40e_free_macvlan_channels
.BI "(struct i40e_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI we want to access
.SH "DESCRIPTION"
This function frees the Qs of the channel VSI from
the stack and also deletes the channel VSIs which
serve as macvlans.
