.TH "i40e_del_fdir_entry" 9 "i40e_del_fdir_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_del_fdir_entry \- Deletes a Flow Director filter entry
.SH SYNOPSIS
.B "int" i40e_del_fdir_entry
.BI "(struct i40e_vsi *vsi "  ","
.BI "struct ethtool_rxnfc *cmd "  ");"
.SH ARGUMENTS
.IP "vsi" 12
Pointer to the targeted VSI
.IP "cmd" 12
The command to get or set Rx flow classification rules
.SH "DESCRIPTION"
The function removes a Flow Director filter entry from the
hlist of the corresponding PF

Returns 0 on success
