.TH "i40e_vsi_setup_vectors" 9 "i40e_vsi_setup_vectors" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40e_vsi_setup_vectors \- Set up the q_vectors for the given VSI
.SH SYNOPSIS
.B "int" i40e_vsi_setup_vectors
.BI "(struct i40e_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "vsi" 12
ptr to the VSI
.SH "DESCRIPTION"
This should only be called after \fBi40e_vsi_mem_alloc\fP which allocates the
corresponding SW VSI structure and initializes num_queue_pairs for the
newly allocated VSI.

Returns 0 on success or negative on failure
