.TH "i40iw_sc_set_hmc_resource_profile" 9 "i40iw_sc_set_hmc_resource_profile" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_sc_set_hmc_resource_profile \- cqp wqe for hmc profile
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_sc_set_hmc_resource_profile
.BI "(struct i40iw_sc_cqp *cqp "  ","
.BI "u64 scratch "  ","
.BI "u8 hmc_profile_type "  ","
.BI "u8 vf_num "  ","
.BI "bool post_sq "  ","
.BI "bool poll_registers "  ");"
.SH ARGUMENTS
.IP "cqp" 12
struct for cqp hw
.IP "scratch" 12
u64 saved to be used during cqp completion
.IP "hmc_profile_type" 12
type of profile to set
.IP "vf_num" 12
vf number for profile
.IP "post_sq" 12
flag for cqp db to ring
.IP "poll_registers" 12
flag to poll register for cqp completion
