.TH "i40iw_allocate_dma_mem" 9 "i40iw_allocate_dma_mem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_allocate_dma_mem \- Memory alloc helper fn
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_allocate_dma_mem
.BI "(struct i40iw_hw *hw "  ","
.BI "struct i40iw_dma_mem *mem "  ","
.BI "u64 size "  ","
.BI "u32 alignment "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "mem" 12
ptr to mem struct to fill out
.IP "size" 12
size of memory requested
.IP "alignment" 12
what to align the allocation to
