.TH "i40iw_vf_clear_to_send" 9 "i40iw_vf_clear_to_send" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_vf_clear_to_send \- wait to send virtual channel message
.SH SYNOPSIS
.B "bool" i40iw_vf_clear_to_send
.BI "(struct i40iw_sc_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
iwarp device *
Wait for until virtual channel is clear
before sending the next message
.SH "DESCRIPTION"
Returns false if error
Returns true if clear to send
