.TH "i40iw_hw_modify_qp" 9 "i40iw_hw_modify_qp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_hw_modify_qp \- setup cqp for modify qp
.SH SYNOPSIS
.B "void" i40iw_hw_modify_qp
.BI "(struct i40iw_device *iwdev "  ","
.BI "struct i40iw_qp *iwqp "  ","
.BI "struct i40iw_modify_qp_info *info "  ","
.BI "bool wait "  ");"
.SH ARGUMENTS
.IP "iwdev" 12
iwarp device
.IP "iwqp" 12
qp ptr (user or kernel)
.IP "info" 12
info for modify qp
.IP "wait" 12
flag to wait or not for modify qp completion
