.TH "i40iw_cm_init_tsa_conn" 9 "i40iw_cm_init_tsa_conn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_cm_init_tsa_conn \- setup qp for RTS
.SH SYNOPSIS
.B "void" i40iw_cm_init_tsa_conn
.BI "(struct i40iw_qp *iwqp "  ","
.BI "struct i40iw_cm_node *cm_node "  ");"
.SH ARGUMENTS
.IP "iwqp" 12
associate qp for the connection
.IP "cm_node" 12
connection's node
