.TH "i40iw_cq_request_notification" 9 "i40iw_cq_request_notification" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_cq_request_notification \- cq notification request (door bell)
.SH SYNOPSIS
.B "void" i40iw_cq_request_notification
.BI "(struct i40iw_cq_uk *cq "  ","
.BI "enum i40iw_completion_notify cq_notify "  ");"
.SH ARGUMENTS
.IP "cq" 12
hw cq
.IP "cq_notify" 12
notification type
