.TH "i40iw_sc_manage_hmc_pm_func_table_done" 9 "i40iw_sc_manage_hmc_pm_func_table_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_sc_manage_hmc_pm_func_table_done \- wait for cqp wqe completion for function table
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_sc_manage_hmc_pm_func_table_done
.BI "(struct i40iw_sc_cqp *cqp "  ");"
.SH ARGUMENTS
.IP "cqp" 12
struct for cqp hw
