.TH "i40iw_ieq_handle_exception" 9 "i40iw_ieq_handle_exception" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_ieq_handle_exception \- handle qp's exception
.SH SYNOPSIS
.B "void" i40iw_ieq_handle_exception
.BI "(struct i40iw_puda_rsrc *ieq "  ","
.BI "struct i40iw_sc_qp *qp "  ","
.BI "struct i40iw_puda_buf *buf "  ");"
.SH ARGUMENTS
.IP "ieq" 12
ieq resource
.IP "qp" 12
qp receiving excpetion
.IP "buf" 12
receive buffer
