.TH "i40iw_receive_ilq" 9 "i40iw_receive_ilq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_receive_ilq \- recv an ETHERNET packet, and process it through CM
.SH SYNOPSIS
.B "void" i40iw_receive_ilq
.BI "(struct i40iw_sc_vsi *vsi "  ","
.BI "struct i40iw_puda_buf *rbuf "  ");"
.SH ARGUMENTS
.IP "vsi" 12
pointer to the vsi structure
.IP "rbuf" 12
receive buffer
