.TH "i40iw_form_cm_frame" 9 "i40iw_form_cm_frame" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_form_cm_frame \- get a free packet and build frame
.SH SYNOPSIS
.B "struct i40iw_puda_buf *" i40iw_form_cm_frame
.BI "(struct i40iw_cm_node *cm_node "  ","
.BI "struct i40iw_kmem_info *options "  ","
.BI "struct i40iw_kmem_info *hdr "  ","
.BI "struct i40iw_kmem_info *pdata "  ","
.BI "u8 flags "  ");"
.SH ARGUMENTS
.IP "cm_node" 12
connection's node ionfo to use in frame
.IP "options" 12
pointer to options info
.IP "hdr" 12
pointer mpa header
.IP "pdata" 12
pointer to private data
.IP "flags" 12
indicates FIN or ACK
