.TH "i40iw_query_gid" 9 "i40iw_query_gid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_query_gid \- Query port GID
.SH SYNOPSIS
.B "int" i40iw_query_gid
.BI "(struct ib_device *ibdev "  ","
.BI "u8 port "  ","
.BI "int index "  ","
.BI "union ib_gid *gid "  ");"
.SH ARGUMENTS
.IP "ibdev" 12
device pointer from stack
.IP "port" 12
port number
.IP "index" 12
Entry index
.IP "gid" 12
Global ID
