.TH "i40iw_ipv6_is_loopback" 9 "i40iw_ipv6_is_loopback" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_ipv6_is_loopback \- check if loopback
.SH SYNOPSIS
.B "bool" i40iw_ipv6_is_loopback
.BI "(u32 *loc_addr "  ","
.BI "u32 *rem_addr "  ");"
.SH ARGUMENTS
.IP "loc_addr" 12
local addr to compare
.IP "rem_addr" 12
remote address
