.TH "i40iw_ieq_get_qp" 9 "i40iw_ieq_get_qp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_ieq_get_qp \- get qp based on quad in puda buffer
.SH SYNOPSIS
.B "struct i40iw_sc_qp *" i40iw_ieq_get_qp
.BI "(struct i40iw_sc_dev *dev "  ","
.BI "struct i40iw_puda_buf *buf "  ");"
.SH ARGUMENTS
.IP "dev" 12
hardware control device structure
.IP "buf" 12
receive puda buffer on exception q
