.TH "i40iw_del_multiple_qhash" 9 "i40iw_del_multiple_qhash" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i40iw_del_multiple_qhash \- Remove qhash and child listens
.SH SYNOPSIS
.B "enum i40iw_status_code" i40iw_del_multiple_qhash
.BI "(struct i40iw_device *iwdev "  ","
.BI "struct i40iw_cm_info *cm_info "  ","
.BI "struct i40iw_cm_listener *cm_parent_listen_node "  ");"
.SH ARGUMENTS
.IP "iwdev" 12
iWarp device
.IP "cm_info" 12
CM info for parent listen node
.IP "cm_parent_listen_node" 12
The parent listen node
