.TH "i810fb_getcolreg" 9 "i810fb_getcolreg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i810fb_getcolreg \- gets red, green and blue values of the hardware DAC
.SH SYNOPSIS
.B "int" i810fb_getcolreg
.BI "(u8 regno "  ","
.BI "u8 *red "  ","
.BI "u8 *green "  ","
.BI "u8 *blue "  ","
.BI "u8 *transp "  ","
.BI "struct fb_info *info "  ");"
.SH ARGUMENTS
.IP "regno" 12
DAC index
.IP "red" 12
red
.IP "green" 12
green
.IP "blue" 12
blue
.IP "transp" 12
transparency (alpha)
.IP "info" 12
pointer to fb_info
.SH "DESCRIPTION"
Gets the red, green and blue values of the hardware DAC as pointed by \fIregno\fP
and writes them to \fIred\fP, \fIgreen\fP and \fIblue\fP respectively
