.TH "i810_protect_regs" 9 "i810_protect_regs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
i810_protect_regs \- allows rw/ro mode of certain VGA registers
.SH SYNOPSIS
.B "void" i810_protect_regs
.BI "(u8 __iomem *mmio "  ","
.BI "int mode "  ");"
.SH ARGUMENTS
.IP "mmio" 12
address of register space
.IP "mode" 12
protect/unprotect
.SH "DESCRIPTION"
The IBM VGA standard allows protection of certain VGA registers.  
This will  protect or unprotect them. 
