.TH "iavf_free_all_rx_resources" 9 "iavf_free_all_rx_resources" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_free_all_rx_resources \- Free Rx Resources for All Queues
.SH SYNOPSIS
.B "void" iavf_free_all_rx_resources
.BI "(struct iavf_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure
.SH "DESCRIPTION"
Free all receive software resources
