.TH "iavf_acquire_msix_vectors" 9 "iavf_acquire_msix_vectors" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_acquire_msix_vectors \- Setup the MSIX capability
.SH SYNOPSIS
.B "int" iavf_acquire_msix_vectors
.BI "(struct iavf_adapter *adapter "  ","
.BI "int vectors "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure
.IP "vectors" 12
number of vectors to request
.SH "DESCRIPTION"
Work with the OS to set up the MSIX vectors needed.

Returns 0 on success, negative on failure
