.TH "iavf_irq_affinity_notify" 9 "iavf_irq_affinity_notify" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_irq_affinity_notify \- Callback for affinity changes
.SH SYNOPSIS
.B "void" iavf_irq_affinity_notify
.BI "(struct irq_affinity_notify *notify "  ","
.BI "const cpumask_t *mask "  ");"
.SH ARGUMENTS
.IP "notify" 12
context as to what irq was changed
.IP "mask" 12
the new affinity mask
.SH "DESCRIPTION"
This is a callback function used by the irq_set_affinity_notifier function
so that we may register to receive changes to the irq affinity masks.
