.TH "iavf_get_msglevel" 9 "iavf_get_msglevel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_get_msglevel \- Get debug message level
.SH SYNOPSIS
.B "u32" iavf_get_msglevel
.BI "(struct net_device *netdev "  ");"
.SH ARGUMENTS
.IP "netdev" 12
network interface device structure
.SH "DESCRIPTION"
Returns current debug message level.
