.TH "iavf_set_ethtool_ops" 9 "iavf_set_ethtool_ops" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iavf_set_ethtool_ops \- Initialize ethtool ops struct
.SH SYNOPSIS
.B "void" iavf_set_ethtool_ops
.BI "(struct net_device *netdev "  ");"
.SH ARGUMENTS
.IP "netdev" 12
network interface device structure
.SH "DESCRIPTION"
Sets ethtool ops struct in our netdev so that ethtool can call
our functions.
