.TH "ib_dealloc_xrcd_user" 9 "ib_dealloc_xrcd_user" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ib_dealloc_xrcd_user \- Deallocates an XRC domain.
.SH SYNOPSIS
.B "int" ib_dealloc_xrcd_user
.BI "(struct ib_xrcd *xrcd "  ","
.BI "struct ib_udata *udata "  ");"
.SH ARGUMENTS
.IP "xrcd" 12
The XRC domain to deallocate.
.IP "udata" 12
Valid user data or NULL for kernel object
