.TH "ib_dispatch_event" 9 "ib_dispatch_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ib_dispatch_event \- Dispatch an asynchronous event
.SH SYNOPSIS
.B "void" ib_dispatch_event
.BI "(const struct ib_event *event "  ");"
.SH ARGUMENTS
.IP "event" 12
Event to dispatch
.SH "DESCRIPTION"
Low-level drivers must call \fBib_dispatch_event\fP to dispatch the
event to all registered event handlers when an asynchronous event
occurs.
