.TH "ib_modify_port" 9 "ib_modify_port" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ib_modify_port \- Modifies the attributes for the specified port.
.SH SYNOPSIS
.B "int" ib_modify_port
.BI "(struct ib_device *device "  ","
.BI "u8 port_num "  ","
.BI "int port_modify_mask "  ","
.BI "struct ib_port_modify *port_modify "  ");"
.SH ARGUMENTS
.IP "device" 12
The device to modify.
.IP "port_num" 12
The number of the port to modify.
.IP "port_modify_mask" 12
Mask used to specify which attributes of the port
to change.
.IP "port_modify" 12
New attribute values for the port.
.SH "DESCRIPTION"
\fBib_modify_port\fP changes a port's attributes as specified by the
\fIport_modify_mask\fP and \fIport_modify\fP structure.
