.TH "ib_resolve_eth_dmac" 9 "ib_resolve_eth_dmac" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ib_resolve_eth_dmac \- Resolve destination mac address
.SH SYNOPSIS
.B "int" ib_resolve_eth_dmac
.BI "(struct ib_device *device "  ","
.BI "struct rdma_ah_attr *ah_attr "  ");"
.SH ARGUMENTS
.IP "device" 12
Device to consider
.IP "ah_attr" 12
address handle attribute which describes the
source and destination parameters
\fBib_resolve_eth_dmac\fP resolves destination mac address and L3 hop limit It
returns 0 on success or appropriate error code. It initializes the
necessary ah_attr fields when call is successful.
