.TH "ibmvscsis_handle_init_compl_msg" 9 "ibmvscsis_handle_init_compl_msg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvscsis_handle_init_compl_msg \- Respond to an Init Complete Message
.SH SYNOPSIS
.B "long" ibmvscsis_handle_init_compl_msg
.BI "(struct scsi_info *vscsi "  ");"
.SH ARGUMENTS
.IP "vscsi" 12
Pointer to our adapter structure
.SH "DESCRIPTION"
Must be called with interrupt lock held.
