.TH "ibmvfc_gather_partition_info" 9 "ibmvfc_gather_partition_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvfc_gather_partition_info \- Gather info about the LPAR
.SH SYNOPSIS
.B "void" ibmvfc_gather_partition_info
.BI "(struct ibmvfc_host *vhost "  ");"
.SH ARGUMENTS
.IP "vhost" 12
-- undescribed --
.SH "DESCRIPTION"

Return value:
none
