.TH "ibmvscsi_eh_device_reset_handler" 9 "ibmvscsi_eh_device_reset_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvscsi_eh_device_reset_handler \- Reset a single LUN...from scsi host template send this over to the server and wait synchronously for the response
.SH SYNOPSIS
.B "int" ibmvscsi_eh_device_reset_handler
.BI "(struct scsi_cmnd *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
-- undescribed --
