.TH "ibmvfc_match_evt" 9 "ibmvfc_match_evt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvfc_match_evt \- Match function for specified event
.SH SYNOPSIS
.B "int" ibmvfc_match_evt
.BI "(struct ibmvfc_event *evt "  ","
.BI "void *match "  ");"
.SH ARGUMENTS
.IP "evt" 12
ibmvfc event struct
.IP "match" 12
event to match
.SH "RETURN"
1 if event matches key / 0 if event does not match key
