.TH "ibmvscsis_send_init_message" 9 "ibmvscsis_send_init_message" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvscsis_send_init_message \- send initialize message to the client
.SH SYNOPSIS
.B "long" ibmvscsis_send_init_message
.BI "(struct scsi_info *vscsi "  ","
.BI "u8 format "  ");"
.SH ARGUMENTS
.IP "vscsi" 12
Pointer to our adapter structure
.IP "format" 12
Which Init Message format to send
.SH "DESCRIPTION"
EXECUTION ENVIRONMENT:
Interrupt environment interrupt lock held
