.TH "ibmvfc_send_crq_init_complete" 9 "ibmvfc_send_crq_init_complete" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvfc_send_crq_init_complete \- Send a CRQ init complete message
.SH SYNOPSIS
.B "int" ibmvfc_send_crq_init_complete
.BI "(struct ibmvfc_host *vhost "  ");"
.SH ARGUMENTS
.IP "vhost" 12
ibmvfc host struct
.SH "DESCRIPTION"
Return value:
0 on success / other on failure
