.TH "ibmvfc_map_sg_list" 9 "ibmvfc_map_sg_list" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvfc_map_sg_list \- Initialize scatterlist
.SH SYNOPSIS
.B "void" ibmvfc_map_sg_list
.BI "(struct scsi_cmnd *scmd "  ","
.BI "int nseg "  ","
.BI "struct srp_direct_buf *md "  ");"
.SH ARGUMENTS
.IP "scmd" 12
scsi command struct
.IP "nseg" 12
number of scatterlist segments
.IP "md" 12
memory descriptor list to initialize
