.TH "ibmvfc_valid_event" 9 "ibmvfc_valid_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ibmvfc_valid_event \- Determines if event is valid.
.SH SYNOPSIS
.B "int" ibmvfc_valid_event
.BI "(struct ibmvfc_event_pool *pool "  ","
.BI "struct ibmvfc_event *evt "  ");"
.SH ARGUMENTS
.IP "pool" 12
event_pool that contains the event
.IP "evt" 12
ibmvfc event to be checked for validity
.SH "DESCRIPTION"
Return value:
1 if event is valid / 0 if event is not valid
