.TH "ice_vsi_alloc" 9 "ice_vsi_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_vsi_alloc \- Allocates the next available struct VSI in the PF
.SH SYNOPSIS
.B "struct ice_vsi *" ice_vsi_alloc
.BI "(struct ice_pf *pf "  ","
.BI "enum ice_vsi_type vsi_type "  ","
.BI "u16 vf_id "  ");"
.SH ARGUMENTS
.IP "pf" 12
board private structure
.IP "vsi_type" 12
type of VSI
.IP "vf_id" 12
ID of the VF being configured
.SH "DESCRIPTION"
returns a pointer to a VSI on success, NULL on failure.
