.TH "ice_sched_get_srl_node" 9 "ice_sched_get_srl_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_sched_get_srl_node \- get shared rate limit node
.SH SYNOPSIS
.B "struct ice_sched_node *" ice_sched_get_srl_node
.BI "(struct ice_sched_node *node "  ","
.BI "u8 srl_layer "  ");"
.SH ARGUMENTS
.IP "node" 12
tree node
.IP "srl_layer" 12
shared rate limit layer
.SH "DESCRIPTION"
This function returns SRL node to be used for shared rate limit purpose.
The caller needs to hold scheduler lock.
