.TH "ice_init_pkg_hints" 9 "ice_init_pkg_hints" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_init_pkg_hints \- 
.SH SYNOPSIS
.B "void" ice_init_pkg_hints
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_seg *ice_seg "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "ice_seg" 12
pointer to the segment of the package scan (non-NULL)
.SH "DESCRIPTION"
This function will scan the package and save off relevant information
(hints or metadata) for driver use. The ice_seg parameter must not be NULL
since the first call to ice_enum_labels requires a pointer to an actual
ice_seg structure.
