.TH "ice_aq_add_sched_elems" 9 "ice_aq_add_sched_elems" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_add_sched_elems \- adds scheduling element
.SH SYNOPSIS
.B "enum ice_status" ice_aq_add_sched_elems
.BI "(struct ice_hw *hw "  ","
.BI "u16 grps_req "  ","
.BI "struct ice_aqc_add_elem *buf "  ","
.BI "u16 buf_size "  ","
.BI "u16 *grps_added "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "grps_req" 12
the number of groups that are requested to be added
.IP "buf" 12
pointer to buffer
.IP "buf_size" 12
buffer size in bytes
.IP "grps_added" 12
returns total number of groups added
.IP "cd" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Add scheduling elements (0x0401)
