.TH "ice_vsi_kill_vlan" 9 "ice_vsi_kill_vlan" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_vsi_kill_vlan \- Remove VSI membership for a given VLAN
.SH SYNOPSIS
.B "int" ice_vsi_kill_vlan
.BI "(struct ice_vsi *vsi "  ","
.BI "u16 vid "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI being configured
.IP "vid" 12
VLAN ID to be removed
.SH "DESCRIPTION"
Returns 0 on success and negative on failure
