.TH "ice_xdp_alloc_setup_rings" 9 "ice_xdp_alloc_setup_rings" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_xdp_alloc_setup_rings \- Allocate and setup Tx rings for XDP
.SH SYNOPSIS
.B "int" ice_xdp_alloc_setup_rings
.BI "(struct ice_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "vsi" 12
VSI to setup Tx rings used by XDP
.SH "DESCRIPTION"
Return 0 on success and negative value on error
