.TH "ice_lag_unlink" 9 "ice_lag_unlink" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_lag_unlink \- handle unlink event
.SH SYNOPSIS
.B "void" ice_lag_unlink
.BI "(struct ice_lag *lag "  ","
.BI "struct netdev_notifier_changeupper_info *info "  ");"
.SH ARGUMENTS
.IP "lag" 12
LAG info struct
.IP "info" 12
info from netdev notification
