.TH "ice_parse_dev_caps" 9 "ice_parse_dev_caps" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_parse_dev_caps \- Parse device capabilities
.SH SYNOPSIS
.B "void" ice_parse_dev_caps
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_hw_dev_caps *dev_p "  ","
.BI "void *buf "  ","
.BI "u32 cap_count "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "dev_p" 12
pointer to device capabilities structure
.IP "buf" 12
buffer containing the device capability records
.IP "cap_count" 12
the number of capabilities
.SH "DESCRIPTION"
Helper device to parse device (0x000B) capabilities list. For
capabilities shared between device and function, this relies on
ice_parse_common_caps.

Loop through the list of provided capabilities and extract the relevant
data into the device capabilities structured.
