.TH "ice_get_inactive_nvm_ver" 9 "ice_get_inactive_nvm_ver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_get_inactive_nvm_ver \- Read Option ROM version from the inactive bank
.SH SYNOPSIS
.B "enum ice_status" ice_get_inactive_nvm_ver
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_nvm_info *nvm "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "nvm" 12
storage for Option ROM version information
.SH "DESCRIPTION"
Reads the NVM EETRACK ID, Map version, and security revision of the
inactive NVM bank. Used to access version data for a pending update that
has not yet been activated.
