.TH "ice_clean_xdp_tx_buf" 9 "ice_clean_xdp_tx_buf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_clean_xdp_tx_buf \- Free and unmap XDP Tx buffer
.SH SYNOPSIS
.B "void" ice_clean_xdp_tx_buf
.BI "(struct ice_ring *xdp_ring "  ","
.BI "struct ice_tx_buf *tx_buf "  ");"
.SH ARGUMENTS
.IP "xdp_ring" 12
XDP Tx ring
.IP "tx_buf" 12
Tx buffer to clean
