.TH "ice_calc_vf_reg_idx" 9 "ice_calc_vf_reg_idx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_calc_vf_reg_idx \- Calculate the VF's register index in the PF space
.SH SYNOPSIS
.B "int" ice_calc_vf_reg_idx
.BI "(struct ice_vf *vf "  ","
.BI "struct ice_q_vector *q_vector "  ");"
.SH ARGUMENTS
.IP "vf" 12
VF to calculate the register index for
.IP "q_vector" 12
a q_vector associated to the VF
