.TH "ice_search_res" 9 "ice_search_res" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_search_res \- Search the tracker for a block of resources
.SH SYNOPSIS
.B "int" ice_search_res
.BI "(struct ice_res_tracker *res "  ","
.BI "u16 needed "  ","
.BI "u16 id "  ");"
.SH ARGUMENTS
.IP "res" 12
pointer to the resource
.IP "needed" 12
size of the block needed
.IP "id" 12
identifier to track owner
.SH "DESCRIPTION"
Returns the base item index of the block, or -ENOMEM for error
