.TH "ice_features_check" 9 "ice_features_check" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_features_check \- Validate encapsulated packet conforms to limits
.SH SYNOPSIS
.B "netdev_features_t" ice_features_check
.BI "(struct sk_buff *skb "  ","
.BI "struct net_device __always_unused *netdev "  ","
.BI "netdev_features_t features "  ");"
.SH ARGUMENTS
.IP "skb" 12
skb buffer
.IP "netdev" 12
This port's netdev
.IP "features" 12
Offload features that the stack believes apply
