.TH "ice_sched_replay_agg" 9 "ice_sched_replay_agg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_sched_replay_agg \- recreate aggregator node(s)
.SH SYNOPSIS
.B "void" ice_sched_replay_agg
.BI "(struct ice_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.SH "DESCRIPTION"
This function recreate aggregator type nodes which are not replayed earlier.
It also replay aggregator BW information. These aggregator nodes are not
associated with VSI type node yet.
