.TH "ice_acquire_res" 9 "ice_acquire_res" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_acquire_res \- 
.SH SYNOPSIS
.B "enum ice_status" ice_acquire_res
.BI "(struct ice_hw *hw "  ","
.BI "enum ice_aq_res_ids res "  ","
.BI "enum ice_aq_res_access_type access "  ","
.BI "u32 timeout "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "res" 12
resource ID
.IP "access" 12
access type (read or write)
.IP "timeout" 12
timeout in milliseconds
.SH "DESCRIPTION"
This function will attempt to acquire the ownership of a resource.
