.TH "ice_add_prof_id_flow" 9 "ice_add_prof_id_flow" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_add_prof_id_flow \- add profile flow
.SH SYNOPSIS
.B "enum ice_status" ice_add_prof_id_flow
.BI "(struct ice_hw *hw "  ","
.BI "enum ice_block blk "  ","
.BI "u16 vsi "  ","
.BI "u64 hdl "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "blk" 12
hardware block
.IP "vsi" 12
the VSI to enable with the profile specified by ID
.IP "hdl" 12
profile handle
.SH "DESCRIPTION"
Calling this function will update the hardware tables to enable the
profile indicated by the ID parameter for the VSIs specified in the VSI
array. Once successfully called, the flow will be enabled.
