.TH "ice_vc_request_qs_msg" 9 "ice_vc_request_qs_msg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_vc_request_qs_msg \- 
.SH SYNOPSIS
.B "int" ice_vc_request_qs_msg
.BI "(struct ice_vf *vf "  ","
.BI "u8 *msg "  ");"
.SH ARGUMENTS
.IP "vf" 12
pointer to the VF info
.IP "msg" 12
pointer to the msg buffer
.SH "DESCRIPTION"
VFs get a default number of queues but can use this message to request a
different number. If the request is successful, PF will reset the VF and
return 0. If unsuccessful, PF will send message informing VF of number of
available queue pairs via virtchnl message response to VF.
