.TH "ice_destroy_all_ctrlq" 9 "ice_destroy_all_ctrlq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_destroy_all_ctrlq \- exit routine for all control queues
.SH SYNOPSIS
.B "void" ice_destroy_all_ctrlq
.BI "(struct ice_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.SH "DESCRIPTION"
This function shuts down all the control queues and then destroys the
control queue locks. It should be called once during driver unload. The
driver should call ice_shutdown_all_ctrlq if it needs to shut down and
reinitialize control queues, such as in response to a reset event.
