.TH "ice_alloc_hw_res" 9 "ice_alloc_hw_res" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_alloc_hw_res \- allocate resource
.SH SYNOPSIS
.B "enum ice_status" ice_alloc_hw_res
.BI "(struct ice_hw *hw "  ","
.BI "u16 type "  ","
.BI "u16 num "  ","
.BI "bool btm "  ","
.BI "u16 *res "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "type" 12
type of resource
.IP "num" 12
number of resources to allocate
.IP "btm" 12
allocate from bottom
.IP "res" 12
pointer to array that will receive the resources
