.TH "ice_globalq_to_pfq" 9 "ice_globalq_to_pfq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_globalq_to_pfq \- convert from global queue index to PF space queue index
.SH SYNOPSIS
.B "u32" ice_globalq_to_pfq
.BI "(struct ice_pf *pf "  ","
.BI "u32 globalq "  ");"
.SH ARGUMENTS
.IP "pf" 12
PF used for conversion
.IP "globalq" 12
global queue index used to convert to PF space queue index
