.TH "ice_vc_isvalid_q_id" 9 "ice_vc_isvalid_q_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_vc_isvalid_q_id \- 
.SH SYNOPSIS
.B "bool" ice_vc_isvalid_q_id
.BI "(struct ice_vf *vf "  ","
.BI "u16 vsi_id "  ","
.BI "u8 qid "  ");"
.SH ARGUMENTS
.IP "vf" 12
pointer to the VF info
.IP "vsi_id" 12
VSI ID
.IP "qid" 12
VSI relative queue ID
.SH "DESCRIPTION"
check for the valid queue ID
