.TH "ice_update_port_tc_tree_cfg" 9 "ice_update_port_tc_tree_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_update_port_tc_tree_cfg \- update TC tree configuration
.SH SYNOPSIS
.B "enum ice_status" ice_update_port_tc_tree_cfg
.BI "(struct ice_port_info *pi "  ","
.BI "struct ice_aqc_port_ets_elem *buf "  ");"
.SH ARGUMENTS
.IP "pi" 12
port information structure
.IP "buf" 12
pointer to buffer
.SH "DESCRIPTION"
update the SW DB with the new TC changes
