.TH "ice_tcam_ent_rsrc_type" 9 "ice_tcam_ent_rsrc_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_tcam_ent_rsrc_type \- get TCAM entry resource type for a block type
.SH SYNOPSIS
.B "bool" ice_tcam_ent_rsrc_type
.BI "(enum ice_block blk "  ","
.BI "u16 *rsrc_type "  ");"
.SH ARGUMENTS
.IP "blk" 12
the block type
.IP "rsrc_type" 12
pointer to variable to receive the resource type
