.TH "ice_free_res" 9 "ice_free_res" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_free_res \- free a block of resources
.SH SYNOPSIS
.B "int" ice_free_res
.BI "(struct ice_res_tracker *res "  ","
.BI "u16 index "  ","
.BI "u16 id "  ");"
.SH ARGUMENTS
.IP "res" 12
pointer to the resource
.IP "index" 12
starting index previously returned by ice_get_res
.IP "id" 12
identifier to track owner
.SH "DESCRIPTION"
Returns number of resources freed
