.TH "ice_create_init_fdir_rule" 9 "ice_create_init_fdir_rule" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_create_init_fdir_rule \- 
.SH SYNOPSIS
.B "int" ice_create_init_fdir_rule
.BI "(struct ice_pf *pf "  ","
.BI "enum ice_fltr_ptype flow "  ");"
.SH ARGUMENTS
.IP "pf" 12
PF structure
.IP "flow" 12
filter enum
.SH "DESCRIPTION"
Return error value or 0 on success.
