.TH "ice_update_vsi_tx_ring_stats" 9 "ice_update_vsi_tx_ring_stats" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_update_vsi_tx_ring_stats \- Update VSI Tx ring stats counters
.SH SYNOPSIS
.B "void" ice_update_vsi_tx_ring_stats
.BI "(struct ice_vsi *vsi "  ","
.BI "struct ice_ring **rings "  ","
.BI "u16 count "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI to be updated
.IP "rings" 12
rings to work on
.IP "count" 12
number of rings
