.TH "ice_flow_proc_seg_hdrs" 9 "ice_flow_proc_seg_hdrs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_flow_proc_seg_hdrs \- process protocol headers present in pkt segments
.SH SYNOPSIS
.B "enum ice_status" ice_flow_proc_seg_hdrs
.BI "(struct ice_flow_prof_params *params "  ");"
.SH ARGUMENTS
.IP "params" 12
information about the flow to be processed
.SH "DESCRIPTION"
This function identifies the packet types associated with the protocol
headers being present in packet segments of the specified flow profile.
