.TH "ice_flow_add_entry" 9 "ice_flow_add_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_flow_add_entry \- Add a flow entry
.SH SYNOPSIS
.B "enum ice_status" ice_flow_add_entry
.BI "(struct ice_hw *hw "  ","
.BI "enum ice_block blk "  ","
.BI "u64 prof_id "  ","
.BI "u64 entry_id "  ","
.BI "u16 vsi_handle "  ","
.BI "enum ice_flow_priority prio "  ","
.BI "void *data "  ","
.BI "u64 *entry_h "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "blk" 12
classification stage
.IP "prof_id" 12
ID of the profile to add a new flow entry to
.IP "entry_id" 12
unique ID to identify this flow entry
.IP "vsi_handle" 12
software VSI handle for the flow entry
.IP "prio" 12
priority of the flow entry
.IP "data" 12
pointer to a data buffer containing flow entry's match values/masks
.IP "entry_h" 12
pointer to buffer that receives the new flow entry's handle
