.TH "ice_pkg_buf_alloc" 9 "ice_pkg_buf_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_pkg_buf_alloc \- 
.SH SYNOPSIS
.B "struct ice_buf_build *" ice_pkg_buf_alloc
.BI "(struct ice_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.SH "DESCRIPTION"
Allocates a package buffer and returns a pointer to the buffer header.
.SH "NOTE"
all package contents must be in Little Endian form.
