.TH "ice_sched_add_elems" 9 "ice_sched_add_elems" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_sched_add_elems \- add nodes to HW and SW DB
.SH SYNOPSIS
.B "enum ice_status" ice_sched_add_elems
.BI "(struct ice_port_info *pi "  ","
.BI "struct ice_sched_node *tc_node "  ","
.BI "struct ice_sched_node *parent "  ","
.BI "u8 layer "  ","
.BI "u16 num_nodes "  ","
.BI "u16 *num_nodes_added "  ","
.BI "u32 *first_node_teid "  ");"
.SH ARGUMENTS
.IP "pi" 12
port information structure
.IP "tc_node" 12
pointer to the branch node
.IP "parent" 12
pointer to the parent node
.IP "layer" 12
layer number to add nodes
.IP "num_nodes" 12
number of nodes
.IP "num_nodes_added" 12
pointer to num nodes added
.IP "first_node_teid" 12
if new nodes are added then return the TEID of first node
.SH "DESCRIPTION"
This function add nodes to HW as well as to SW DB for a given layer
