.TH "ice_flow_rem_entry" 9 "ice_flow_rem_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_flow_rem_entry \- Remove a flow entry
.SH SYNOPSIS
.B "enum ice_status" ice_flow_rem_entry
.BI "(struct ice_hw *hw "  ","
.BI "enum ice_block blk "  ","
.BI "u64 entry_h "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "blk" 12
classification stage
.IP "entry_h" 12
handle to the flow entry to be removed
