.TH "ice_pf_dis_all_vsi" 9 "ice_pf_dis_all_vsi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_pf_dis_all_vsi \- Pause all VSIs on a PF
.SH SYNOPSIS
.B "void" ice_pf_dis_all_vsi
.BI "(struct ice_pf *pf "  ","
.BI "bool locked "  ");"
.SH ARGUMENTS
.IP "pf" 12
the PF
.IP "locked" 12
is the rtnl_lock already held
