.TH "ice_get_link_status" 9 "ice_get_link_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_get_link_status \- get status of the HW network link
.SH SYNOPSIS
.B "enum ice_status" ice_get_link_status
.BI "(struct ice_port_info *pi "  ","
.BI "bool *link_up "  ");"
.SH ARGUMENTS
.IP "pi" 12
port information structure
.IP "link_up" 12
pointer to bool (true/false = linkup/linkdown)
.SH "DESCRIPTION"
Variable link_up is true if link is up, false if link is down.
The variable link_up is invalid if status is non zero. As a
result of this call, link status reporting becomes enabled
