.TH "ice_service_task_stop" 9 "ice_service_task_stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_service_task_stop \- stop service task and cancel works
.SH SYNOPSIS
.B "int" ice_service_task_stop
.BI "(struct ice_pf *pf "  ");"
.SH ARGUMENTS
.IP "pf" 12
board private structure
.SH "DESCRIPTION"
Return 0 if the __ICE_SERVICE_DIS bit was not already set,
1 otherwise.
