.TH "ice_vsi_open_ctrl" 9 "ice_vsi_open_ctrl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_vsi_open_ctrl \- open control VSI for use
.SH SYNOPSIS
.B "int" ice_vsi_open_ctrl
.BI "(struct ice_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI to open
.SH "DESCRIPTION"
Initialization of the Control VSI

Returns 0 on success, negative value on error
