.TH "ice_remove_eth_mac" 9 "ice_remove_eth_mac" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_remove_eth_mac \- Remove an ethertype (or MAC) based filter rule
.SH SYNOPSIS
.B "enum ice_status" ice_remove_eth_mac
.BI "(struct ice_hw *hw "  ","
.BI "struct list_head *em_list "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.IP "em_list" 12
list of ethertype or ethertype MAC entries
