.TH "ice_aq_get_cee_dcb_cfg" 9 "ice_aq_get_cee_dcb_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_get_cee_dcb_cfg \- 
.SH SYNOPSIS
.B "enum ice_status" ice_aq_get_cee_dcb_cfg
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_aqc_get_cee_dcb_cfg_resp *buff "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "buff" 12
response buffer that stores CEE operational configuration
.IP "cd" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Get CEE DCBX mode operational configuration from firmware (0x0A07)
