.TH "ice_validate_vf_id" 9 "ice_validate_vf_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_validate_vf_id \- helper to check if VF ID is valid
.SH SYNOPSIS
.B "int" ice_validate_vf_id
.BI "(struct ice_pf *pf "  ","
.BI "u16 vf_id "  ");"
.SH ARGUMENTS
.IP "pf" 12
pointer to the PF structure
.IP "vf_id" 12
the ID of the VF to check
