.TH "ice_vsi_set_rss_params" 9 "ice_vsi_set_rss_params" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_vsi_set_rss_params \- Setup RSS capabilities per VSI type
.SH SYNOPSIS
.B "void" ice_vsi_set_rss_params
.BI "(struct ice_vsi *vsi "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI being configured
