.TH "ice_qvec_ena_irq" 9 "ice_qvec_ena_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_qvec_ena_irq \- Enable IRQ for given queue vector
.SH SYNOPSIS
.B "void" ice_qvec_ena_irq
.BI "(struct ice_vsi *vsi "  ","
.BI "struct ice_q_vector *q_vector "  ");"
.SH ARGUMENTS
.IP "vsi" 12
the VSI that contains queue vector
.IP "q_vector" 12
queue vector
