.TH "ice_fdir_comp_rules" 9 "ice_fdir_comp_rules" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_fdir_comp_rules \- compare 2 filters
.SH SYNOPSIS
.B "bool" ice_fdir_comp_rules
.BI "(struct ice_fdir_fltr *a "  ","
.BI "struct ice_fdir_fltr *b "  ","
.BI "bool v6 "  ");"
.SH ARGUMENTS
.IP "a" 12
a Flow Director filter data structure
.IP "b" 12
a Flow Director filter data structure
.IP "v6" 12
bool true if v6 filter
.SH "DESCRIPTION"
Returns true if the filters match
