.TH "ice_fltr_add_mac" 9 "ice_fltr_add_mac" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_fltr_add_mac \- add single MAC filter
.SH SYNOPSIS
.B "enum ice_status" ice_fltr_add_mac
.BI "(struct ice_vsi *vsi "  ","
.BI "const u8 *mac "  ","
.BI "enum ice_sw_fwd_act_type action "  ");"
.SH ARGUMENTS
.IP "vsi" 12
pointer to VSI struct
.IP "mac" 12
MAC to add
.IP "action" 12
action to be performed on filter match
