.TH "ice_sched_is_leaf_node_present" 9 "ice_sched_is_leaf_node_present" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_sched_is_leaf_node_present \- check for a leaf node in the sub-tree
.SH SYNOPSIS
.B "bool" ice_sched_is_leaf_node_present
.BI "(struct ice_sched_node *node "  ");"
.SH ARGUMENTS
.IP "node" 12
pointer to the sub-tree node
.SH "DESCRIPTION"
This function checks for a leaf node presence in a given sub-tree node.
