.TH "ice_aq_get_fw_ver" 9 "ice_aq_get_fw_ver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_aq_get_fw_ver \- 
.SH SYNOPSIS
.B "enum ice_status" ice_aq_get_fw_ver
.BI "(struct ice_hw *hw "  ","
.BI "struct ice_sq_cd *cd "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW struct
.IP "cd" 12
pointer to command details structure or NULL
.SH "DESCRIPTION"
Get the firmware version (0x0001) from the admin queue commands
