.TH "ice_devlink_unregister" 9 "ice_devlink_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_devlink_unregister \- Unregister devlink resources for this PF.
.SH SYNOPSIS
.B "void" ice_devlink_unregister
.BI "(struct ice_pf *pf "  ");"
.SH ARGUMENTS
.IP "pf" 12
the PF structure to cleanup
.SH "DESCRIPTION"
Releases resources used by devlink and cleans up associated memory.
