.TH "ice_xmit_xdp_ring" 9 "ice_xmit_xdp_ring" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ice_xmit_xdp_ring \- submit single packet to XDP ring for transmission
.SH SYNOPSIS
.B "int" ice_xmit_xdp_ring
.BI "(void *data "  ","
.BI "u16 size "  ","
.BI "struct ice_ring *xdp_ring "  ");"
.SH ARGUMENTS
.IP "data" 12
packet data pointer
.IP "size" 12
packet data size
.IP "xdp_ring" 12
XDP ring for transmission
