.TH "ide_find_port_slot" 9 "ide_find_port_slot" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ide_find_port_slot \- find free port slot
.SH SYNOPSIS
.B "int" ide_find_port_slot
.BI "(const struct ide_port_info *d "  ");"
.SH ARGUMENTS
.IP "d" 12
IDE port info

Return the new port slot index or -ENOENT if we are out of free slots.
