.TH "ide_unregister" 9 "ide_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ide_unregister \- free an IDE interface
.SH SYNOPSIS
.B "void" ide_unregister
.BI "(ide_hwif_t *hwif "  ");"
.SH ARGUMENTS
.IP "hwif" 12
IDE interface

Perform the final unregister of an IDE interface.

Locking:
The caller must not hold the IDE locks.

It is up to the caller to be sure there is no pending I/O here,
and that the interface will not be reopened (present/vanishing
locking isn't yet done BTW).
