.TH "ide_complete_pm_rq" 9 "ide_complete_pm_rq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ide_complete_pm_rq \- end the current Power Management request
.SH SYNOPSIS
.B "void" ide_complete_pm_rq
.BI "(ide_drive_t *drive "  ","
.BI "struct request *rq "  ");"
.SH ARGUMENTS
.IP "drive" 12
target drive
.IP "rq" 12
request

This function cleans up the current PM request and stops the queue
if necessary.
