.TH "idle_inject_wakeup" 9 "idle_inject_wakeup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
idle_inject_wakeup \- Wake up idle injection threads
.SH SYNOPSIS
.B "void" idle_inject_wakeup
.BI "(struct idle_inject_device *ii_dev "  ");"
.SH ARGUMENTS
.IP "ii_dev" 12
target idle injection device
.SH "DESCRIPTION"
Every idle injection task associated with the given idle injection device
and running on an online CPU will be woken up.
