.TH "idle_cpu_without" 9 "idle_cpu_without" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
idle_cpu_without \- would a given CPU be idle without p ?
.SH SYNOPSIS
.B "int" idle_cpu_without
.BI "(int cpu "  ","
.BI "struct task_struct *p "  ");"
.SH ARGUMENTS
.IP "cpu" 12
the processor on which idleness is tested.
.IP "p" 12
task which should be ignored.
.SH "RETURN"
1 if the CPU would be idle. 0 otherwise.
