.TH "if_usb_issue_boot_command" 9 "if_usb_issue_boot_command" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
if_usb_issue_boot_command \- Issue boot command to Boot2.
.SH SYNOPSIS
.B "int" if_usb_issue_boot_command
.BI "(struct if_usb_card *cardp "  ","
.BI "int ivalue "  ");"
.SH ARGUMENTS
.IP "cardp" 12
pointer if_usb_card
.IP "ivalue" 12
1 boots from FW by USB-Download, 2 boots from FW in EEPROM.
.SH "RETURN"
0
