.TH "igb_check_polarity_igp" 9 "igb_check_polarity_igp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_check_polarity_igp \- Checks the polarity.
.SH SYNOPSIS
.B "s32" igb_check_polarity_igp
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure

Success returns 0, Failure returns -E1000_ERR_PHY (-2)

Polarity is determined based on the PHY port status register, and the
current speed (since there is no polarity at 100Mbps).
