.TH "igb_vfta_set" 9 "igb_vfta_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_vfta_set \- enable or disable vlan in VLAN filter table
.SH SYNOPSIS
.B "s32" igb_vfta_set
.BI "(struct e1000_hw *hw "  ","
.BI "u32 vlan "  ","
.BI "u32 vind "  ","
.BI "bool vlan_on "  ","
.BI "bool vlvf_bypass "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "vlan" 12
VLAN id to add or remove
.IP "vind" 12
VMDq output index that maps queue to VLAN id
.IP "vlan_on" 12
if true add filter, if false remove
.IP "vlvf_bypass" 12
skip VLVF if no match is found

Sets or clears a bit in the VLAN filter table array based on VLAN id
and if we are adding or removing the filter
