.TH "igb_find_vlvf_slot" 9 "igb_find_vlvf_slot" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_find_vlvf_slot \- find the VLAN id or the first empty slot
.SH SYNOPSIS
.B "s32" igb_find_vlvf_slot
.BI "(struct e1000_hw *hw "  ","
.BI "u32 vlan "  ","
.BI "bool vlvf_bypass "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
.IP "vlan" 12
VLAN id to write to VLAN filter
.IP "vlvf_bypass" 12
skip VLVF if no match is found

return the VLVF index where this VLAN id should be placed
