.TH "igb_vmdq_set_anti_spoofing_pf" 9 "igb_vmdq_set_anti_spoofing_pf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_vmdq_set_anti_spoofing_pf \- enable or disable anti-spoofing
.SH SYNOPSIS
.B "void" igb_vmdq_set_anti_spoofing_pf
.BI "(struct e1000_hw *hw "  ","
.BI "bool enable "  ","
.BI "int pf "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware struct
.IP "enable" 12
state to enter, either enabled or disabled
.IP "pf" 12
Physical Function pool - do not set anti-spoofing for the PF

enables/disables L2 switch anti-spoofing functionality.
