.TH "igb_acquire_swfw_sync_i210" 9 "igb_acquire_swfw_sync_i210" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_acquire_swfw_sync_i210 \- Acquire SW/FW semaphore
.SH SYNOPSIS
.B "s32" igb_acquire_swfw_sync_i210
.BI "(struct e1000_hw *hw "  ","
.BI "u16 mask "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "mask" 12
specifies which semaphore to acquire

Acquire the SW/FW semaphore to access the PHY or NVM.  The mask
will also specify which port we're acquiring the lock for.
