.TH "igb_release_phy_82575" 9 "igb_release_phy_82575" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_release_phy_82575 \- Release rights to access PHY
.SH SYNOPSIS
.B "void" igb_release_phy_82575
.BI "(struct e1000_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure

A wrapper to release access rights to the correct PHY.  This is a
function pointer entry point called by the api module.
