.TH "igb_configure_tx" 9 "igb_configure_tx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igb_configure_tx \- Configure transmit Unit after Reset
.SH SYNOPSIS
.B "void" igb_configure_tx
.BI "(struct igb_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure

Configure the Tx unit of the MAC after a reset.
