.TH "igc_power_down_phy_copper_base" 9 "igc_power_down_phy_copper_base" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igc_power_down_phy_copper_base \- Remove link during PHY power down
.SH SYNOPSIS
.B "void" igc_power_down_phy_copper_base
.BI "(struct igc_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.SH "DESCRIPTION"
In the case of a PHY power down to save power, or to turn off link during a
driver unload, or wake on lan is not enabled, remove the link.
