.TH "igc_phy_hw_reset" 9 "igc_phy_hw_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igc_phy_hw_reset \- PHY hardware reset
.SH SYNOPSIS
.B "s32" igc_phy_hw_reset
.BI "(struct igc_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.SH "DESCRIPTION"
Verify the reset block is not blocking us from resetting.  Acquire
semaphore (if necessary) and read/set/write the device control reset
bit in the PHY.  Wait the appropriate delay time for the device to
reset and release the semaphore (if necessary).
