.TH "igc_release_swfw_sync_i225" 9 "igc_release_swfw_sync_i225" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igc_release_swfw_sync_i225 \- Release SW/FW semaphore
.SH SYNOPSIS
.B "void" igc_release_swfw_sync_i225
.BI "(struct igc_hw *hw "  ","
.BI "u16 mask "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the HW structure
.IP "mask" 12
specifies which semaphore to acquire
.SH "DESCRIPTION"
Release the SW/FW semaphore used to access the PHY or NVM.  The mask
will also specify which port we're releasing the lock for.
