.TH "igc_del_etype_filter" 9 "igc_del_etype_filter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
igc_del_etype_filter \- Delete ethertype filter
.SH SYNOPSIS
.B "void" igc_del_etype_filter
.BI "(struct igc_adapter *adapter "  ","
.BI "u16 etype "  ");"
.SH ARGUMENTS
.IP "adapter" 12
Pointer to adapter where the filter should be deleted from
.IP "etype" 12
Ethertype value
