.TH "iio_hw_consumer_alloc" 9 "iio_hw_consumer_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iio_hw_consumer_alloc \- Allocate IIO hardware consumer
.SH SYNOPSIS
.B "struct iio_hw_consumer *" iio_hw_consumer_alloc
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Pointer to consumer device.
.SH "DESCRIPTION"
Returns a valid iio_hw_consumer on success or a \fBERR_PTR\fP on failure.
