.TH "iio_read_mount_matrix" 9 "iio_read_mount_matrix" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iio_read_mount_matrix \- retrieve iio device mounting matrix from device "mount-matrix" property
.SH SYNOPSIS
.B "int" iio_read_mount_matrix
.BI "(struct device *dev "  ","
.BI "const char *propname "  ","
.BI "struct iio_mount_matrix *matrix "  ");"
.SH ARGUMENTS
.IP "dev" 12
device the mounting matrix property is assigned to
.IP "propname" 12
device specific mounting matrix property name
.IP "matrix" 12
where to store retrieved matrix
.SH "DESCRIPTION"
If device is assigned no mounting matrix property, a default 3x3 identity
matrix will be filled in.
.SH "RETURN"
0 if success, or a negative error code on failure.
