.TH "img_ascii_lcd_remove" 9 "img_ascii_lcd_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
img_ascii_lcd_remove \- remove an LCD display device
.SH SYNOPSIS
.B "int" img_ascii_lcd_remove
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
the LCD platform device
.SH "DESCRIPTION"
Remove an LCD display device, freeing private resources & ensuring that the
driver stops using the LCD display registers.
.SH "RETURN"
0
