.TH "imx334_stop_streaming" 9 "imx334_stop_streaming" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
imx334_stop_streaming \- Stop sensor stream
.SH SYNOPSIS
.B "int" imx334_stop_streaming
.BI "(struct imx334 *imx334 "  ");"
.SH ARGUMENTS
.IP "imx334" 12
pointer to imx334 device
.SH "RETURN"
0 if successful, error code otherwise.
