.TH "inc_ep_stats_reqs" 9 "inc_ep_stats_reqs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
inc_ep_stats_reqs \- Update ep stats counts
.SH SYNOPSIS
.B "void" inc_ep_stats_reqs
.BI "(struct pxa_ep *ep "  ","
.BI "int is_in "  ");"
.SH ARGUMENTS
.IP "ep" 12
physical endpoint
.IP "is_in" 12
ep direction (USB_DIR_IN or 0)
