.TH "init_hwif_piix" 9 "init_hwif_piix" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
init_hwif_piix \- fill in the hwif for the PIIX
.SH SYNOPSIS
.B "void" init_hwif_piix
.BI "(ide_hwif_t *hwif "  ");"
.SH ARGUMENTS
.IP "hwif" 12
IDE interface

Set up the ide_hwif_t for the PIIX interface according to the
capabilities of the hardware.
