.TH "initio_se2_rd" 9 "initio_se2_rd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
initio_se2_rd \- read E2PROM word
.SH SYNOPSIS
.B "u16" initio_se2_rd
.BI "(unsigned long base "  ","
.BI "u8 addr "  ");"
.SH ARGUMENTS
.IP "base" 12
Base of InitIO controller
.IP "addr" 12
Address of word in E2PROM

Read a word from the NV E2PROM device
