.TH "input_get_timestamp" 9 "input_get_timestamp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
input_get_timestamp \- get timestamp for input events
.SH SYNOPSIS
.B "ktime_t *" input_get_timestamp
.BI "(struct input_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
input device to get timestamp from
.SH "DESCRIPTION"
A valid timestamp is a timestamp of non-zero value.
