.TH "input_get_new_minor" 9 "input_get_new_minor" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
input_get_new_minor \- allocates a new input minor number
.SH SYNOPSIS
.B "int" input_get_new_minor
.BI "(int legacy_base "  ","
.BI "unsigned int legacy_num "  ","
.BI "bool allow_dynamic "  ");"
.SH ARGUMENTS
.IP "legacy_base" 12
beginning or the legacy range to be searched
.IP "legacy_num" 12
size of legacy range
.IP "allow_dynamic" 12
whether we can also take ID from the dynamic range
.SH "DESCRIPTION"
This function allocates a new device minor for from input major namespace.
Caller can request legacy minor by specifying \fIlegacy_base\fP and \fIlegacy_num\fP
parameters and whether ID can be allocated from dynamic range if there are
no free IDs in legacy range.
