.TH "input_mt_drop_unused" 9 "input_mt_drop_unused" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
input_mt_drop_unused \- Inactivate slots not seen in this frame
.SH SYNOPSIS
.B "void" input_mt_drop_unused
.BI "(struct input_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
input device with allocated MT slots
.SH "DESCRIPTION"
Lift all slots not seen since the last call to this function.
