.TH "insn_get_length" 9 "insn_get_length" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
insn_get_length \- Get the length of instruction
.SH SYNOPSIS
.B "void" insn_get_length
.BI "(struct insn *insn "  ");"
.SH ARGUMENTS
.IP "insn" 12
\fIstruct insn\fP containing instruction
.SH "DESCRIPTION"
If necessary, first collects the instruction up to and including the
immediates bytes.
