.TH "insn_get_immediate" 9 "insn_get_immediate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
insn_get_immediate \- Get the immediates of instruction
.SH SYNOPSIS
.B "void" insn_get_immediate
.BI "(struct insn *insn "  ");"
.SH ARGUMENTS
.IP "insn" 12
\fIstruct insn\fP containing instruction
.SH "DESCRIPTION"
If necessary, first collects the instruction up to and including the
displacement bytes.
Basically, most of immediates are sign-expanded. Unsigned-value can be
get by bit masking with ((1 << (nbytes * 8)) - 1)
