.TH "intel_crtc_debugfs_add" 9 "intel_crtc_debugfs_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_crtc_debugfs_add \- add i915 specific crtc debugfs files
.SH SYNOPSIS
.B "int" intel_crtc_debugfs_add
.BI "(struct drm_crtc *crtc "  ");"
.SH ARGUMENTS
.IP "crtc" 12
pointer to a drm_crtc
.SH "DESCRIPTION"
Returns 0 on success, negative error codes on error.

Failure to add debugfs entries should generally be ignored.
