.TH "intel_vgpu_detect" 9 "intel_vgpu_detect" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_vgpu_detect \- detect virtual GPU
.SH SYNOPSIS
.B "void" intel_vgpu_detect
.BI "(struct drm_i915_private *dev_priv "  ");"
.SH ARGUMENTS
.IP "dev_priv" 12
i915 device private
.SH "DESCRIPTION"
This function is called at the initialization stage, to detect whether
running on a vGPU.
