.TH "intel_dpll_get_hw_state" 9 "intel_dpll_get_hw_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_dpll_get_hw_state \- readout the DPLL's hardware state
.SH SYNOPSIS
.B "bool" intel_dpll_get_hw_state
.BI "(struct drm_i915_private *i915 "  ","
.BI "struct intel_shared_dpll *pll "  ","
.BI "struct intel_dpll_hw_state *hw_state "  ");"
.SH ARGUMENTS
.IP "i915" 12
i915 device
.IP "pll" 12
DPLL for which to calculate the output frequency
.IP "hw_state" 12
DPLL's hardware state
.SH "DESCRIPTION"
Read out \fIpll\fP's hardware state into \fIhw_state\fP.
