.TH "intel_plane_destroy_state" 9 "intel_plane_destroy_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_plane_destroy_state \- destroy plane state
.SH SYNOPSIS
.B "void" intel_plane_destroy_state
.BI "(struct drm_plane *plane "  ","
.BI "struct drm_plane_state *state "  ");"
.SH ARGUMENTS
.IP "plane" 12
drm plane
.IP "state" 12
state object to destroy
.SH "DESCRIPTION"
Destroys the plane state (both common and Intel-specific) for the
specified plane.
