.TH "intel_vgpu_init_gtt" 9 "intel_vgpu_init_gtt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_vgpu_init_gtt \- initialize per-vGPU graphics memory virulization
.SH SYNOPSIS
.B "int" intel_vgpu_init_gtt
.BI "(struct intel_vgpu *vgpu "  ");"
.SH ARGUMENTS
.IP "vgpu" 12
a vGPU
.SH "DESCRIPTION"
This function is used to initialize per-vGPU graphics memory virtualization
components.
.SH "RETURN"
Zero on success, error code if failed.
