.TH "intel_power_domains_cleanup" 9 "intel_power_domains_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_power_domains_cleanup \- clean up power domains resources
.SH SYNOPSIS
.B "void" intel_power_domains_cleanup
.BI "(struct drm_i915_private *dev_priv "  ");"
.SH ARGUMENTS
.IP "dev_priv" 12
i915 device instance
.SH "DESCRIPTION"
Release any resources acquired by \fBintel_power_domains_init\fP
