.TH "intel_sst_reset_dsp_mrfld" 9 "intel_sst_reset_dsp_mrfld" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_sst_reset_dsp_mrfld \- Resetting SST DSP
.SH SYNOPSIS
.B "int" intel_sst_reset_dsp_mrfld
.BI "(struct intel_sst_drv *sst_drv_ctx "  ");"
.SH ARGUMENTS
.IP "sst_drv_ctx" 12
intel_sst_drv context pointer
.SH "DESCRIPTION"
This resets DSP in case of MRFLD platfroms
