.TH "intel_pt_ff_cb" 9 "intel_pt_ff_cb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_pt_ff_cb \- fast forward lookahead callback.
.SH SYNOPSIS
.B "int" intel_pt_ff_cb
.BI "(struct intel_pt_buffer *buffer "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "buffer" 12
Intel PT trace buffer
.IP "data" 12
opaque pointer to fast forward data (struct fast_forward_data)
.SH "DESCRIPTION"
Determine if \fIbuffer\fP trace is past the fast forward timestamp.
.SH "RETURN"
1 (stop lookahead) if \fIbuffer\fP trace is past the fast forward
timestamp, and 0 otherwise.
