.TH "intel_wm_need_update" 9 "intel_wm_need_update" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_wm_need_update \- Check whether watermarks need updating
.SH SYNOPSIS
.B "bool" intel_wm_need_update
.BI "(const struct intel_plane_state *cur "  ","
.BI "struct intel_plane_state *new "  ");"
.SH ARGUMENTS
.IP "cur" 12
current plane state
.IP "new" 12
new plane state
.SH "DESCRIPTION"
Check current plane state versus the new one to determine whether
watermarks need to be recalculated.

Returns true or false.
