.TH "intel_vgpu_gpa_to_mmio_offset" 9 "intel_vgpu_gpa_to_mmio_offset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_vgpu_gpa_to_mmio_offset \- translate a GPA to MMIO offset
.SH SYNOPSIS
.B "int" intel_vgpu_gpa_to_mmio_offset
.BI "(struct intel_vgpu *vgpu "  ","
.BI "u64 gpa "  ");"
.SH ARGUMENTS
.IP "vgpu" 12
a vGPU
.IP "gpa" 12
guest physical address
.SH "RETURN"
Zero on success, negative error code if failed
