.TH "intel_xpower_pmic_get_raw_temp" 9 "intel_xpower_pmic_get_raw_temp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_xpower_pmic_get_raw_temp \- Get raw temperature reading from the PMIC
.SH SYNOPSIS
.B "int" intel_xpower_pmic_get_raw_temp
.BI "(struct regmap *regmap "  ","
.BI "int reg "  ");"
.SH ARGUMENTS
.IP "regmap" 12
regmap of the PMIC device
.IP "reg" 12
register to get the reading
.SH "DESCRIPTION"
Return a positive value on success, errno on failure.
