.TH "intel_gvt_clean_device" 9 "intel_gvt_clean_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
intel_gvt_clean_device \- clean a GVT device
.SH SYNOPSIS
.B "void" intel_gvt_clean_device
.BI "(struct drm_i915_private *i915 "  ");"
.SH ARGUMENTS
.IP "i915" 12
i915 private
.SH "DESCRIPTION"
This function is called at the driver unloading stage, to free the
resources owned by a GVT device.
