.TH "inv_icm42600_irq_init" 9 "inv_icm42600_irq_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
inv_icm42600_irq_init \- initialize int pin and interrupt handler
.SH SYNOPSIS
.B "int" inv_icm42600_irq_init
.BI "(struct inv_icm42600_state *st "  ","
.BI "int irq "  ","
.BI "int irq_type "  ","
.BI "bool open_drain "  ");"
.SH ARGUMENTS
.IP "st" 12
driver internal state
.IP "irq" 12
irq number
.IP "irq_type" 12
irq trigger type
.IP "open_drain" 12
true if irq is open drain, false for push-pull
.SH "DESCRIPTION"
Returns 0 on success, a negative error code otherwise.
