.TH "ipa_endpoint_suspend_aggr" 9 "ipa_endpoint_suspend_aggr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipa_endpoint_suspend_aggr \- Emulate suspend interrupt
.SH SYNOPSIS
.B "void" ipa_endpoint_suspend_aggr
.BI "(struct ipa_endpoint *endpoint "  ");"
.SH ARGUMENTS
.IP "endpoint" 12
Endpoint on which to emulate a suspend

Emulate suspend IPA interrupt to unsuspend an endpoint suspended
with an open aggregation frame.  This is to work around a hardware
issue in IPA version 3.5.1 where the suspend interrupt will not be
generated when it should be.
