.TH "ipi_get_hwirq" 9 "ipi_get_hwirq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipi_get_hwirq \- Get the hwirq associated with an IPI to a cpu
.SH SYNOPSIS
.B "irq_hw_number_t" ipi_get_hwirq
.BI "(unsigned int irq "  ","
.BI "unsigned int cpu "  ");"
.SH ARGUMENTS
.IP "irq" 12
linux irq number
.IP "cpu" 12
the target cpu
.SH "DESCRIPTION"
When dealing with coprocessors IPI, we need to inform the coprocessor of
the hwirq it needs to use to receive and send IPIs.

Returns hwirq value on success and INVALID_HWIRQ on failure.
