.TH "ipr_copy_ucode_buffer" 9 "ipr_copy_ucode_buffer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_copy_ucode_buffer \- Copy user buffer to kernel buffer
.SH SYNOPSIS
.B "int" ipr_copy_ucode_buffer
.BI "(struct ipr_sglist *sglist "  ","
.BI "u8 *buffer "  ","
.BI "u32 len "  ");"
.SH ARGUMENTS
.IP "sglist" 12
scatter/gather list pointer
.IP "buffer" 12
buffer pointer
.IP "len" 12
buffer length
.SH "DESCRIPTION"
Copy a microcode image from a user buffer into a buffer allocated by
ipr_alloc_ucode_buffer

Return value:
0 on success / other on failure
