.TH "ipr_get_chip_info" 9 "ipr_get_chip_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_get_chip_info \- Find adapter chip information
.SH SYNOPSIS
.B "const struct ipr_chip_t *" ipr_get_chip_info
.BI "(const struct pci_device_id *dev_id "  ");"
.SH ARGUMENTS
.IP "dev_id" 12
PCI device id struct
.SH "DESCRIPTION"
Return value:
ptr to chip information on success / NULL on failure
