.TH "ipr_ata_post_internal" 9 "ipr_ata_post_internal" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_ata_post_internal \- Cleanup after an internal command
.SH SYNOPSIS
.B "void" ipr_ata_post_internal
.BI "(struct ata_queued_cmd *qc "  ");"
.SH ARGUMENTS
.IP "qc" 12
ATA queued command
.SH "DESCRIPTION"
Return value:
none
