.TH "ipr_change_queue_depth" 9 "ipr_change_queue_depth" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_change_queue_depth \- Change the device's queue depth
.SH SYNOPSIS
.B "int" ipr_change_queue_depth
.BI "(struct scsi_device *sdev "  ","
.BI "int qdepth "  ");"
.SH ARGUMENTS
.IP "sdev" 12
scsi device struct
.IP "qdepth" 12
depth to set
.SH "DESCRIPTION"
Return value:
actual depth set
