.TH "ipr_free_ucode_buffer" 9 "ipr_free_ucode_buffer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_free_ucode_buffer \- Frees a microcode download buffer
.SH SYNOPSIS
.B "void" ipr_free_ucode_buffer
.BI "(struct ipr_sglist *sglist "  ");"
.SH ARGUMENTS
.IP "sglist" 12
scatter/gather list pointer
.SH "DESCRIPTION"
Free a DMA'able ucode download buffer previously allocated with
ipr_alloc_ucode_buffer

Return value:
nothing
