.TH "ipr_invalid_adapter" 9 "ipr_invalid_adapter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_invalid_adapter \- Determine if this adapter is supported on this hardware
.SH SYNOPSIS
.B "int" ipr_invalid_adapter
.BI "(struct ipr_ioa_cfg *ioa_cfg "  ");"
.SH ARGUMENTS
.IP "ioa_cfg" 12
ioa cfg struct
.SH "DESCRIPTION"
Adapters that use Gemstone revision < 3.1 do not work reliably on
certain pSeries hardware. This function determines if the given
adapter is in one of these confgurations or not.

Return value:
1 if adapter is not supported / 0 if adapter is supported
