.TH "ipr_halt" 9 "ipr_halt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ipr_halt \- Issue shutdown prepare to all adapters
.SH SYNOPSIS
.B "int" ipr_halt
.BI "(struct notifier_block *nb "  ","
.BI "ulong event "  ","
.BI "void *buf "  ");"
.SH ARGUMENTS
.IP "nb" 12
Notifier block
.IP "event" 12
Notifier event
.IP "buf" 12
Notifier data (unused)
.SH "DESCRIPTION"
Return value:
NOTIFY_OK on success / NOTIFY_DONE on failure
