.TH "ips_gpu_raise" 9 "ips_gpu_raise" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ips_gpu_raise \- raise GPU power clamp
.SH SYNOPSIS
.B "void" ips_gpu_raise
.BI "(struct ips_driver *ips "  ");"
.SH ARGUMENTS
.IP "ips" 12
IPS driver struct
.SH "DESCRIPTION"
Raise the GPU frequency/power if possible.  We need to call into the
i915 driver in this case.
