.TH "irq_gc_set_wake" 9 "irq_gc_set_wake" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
irq_gc_set_wake \- Set/clr wake bit for an interrupt
.SH SYNOPSIS
.B "int" irq_gc_set_wake
.BI "(struct irq_data *d "  ","
.BI "unsigned int on "  ");"
.SH ARGUMENTS
.IP "d" 12
irq_data
.IP "on" 12
Indicates whether the wake bit should be set or cleared
.SH "DESCRIPTION"
For chips where the wake from suspend functionality is not
configured in a separate register and the wakeup active state is
just stored in a bitmask.
