.TH "irq_chip_pm_put" 9 "irq_chip_pm_put" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
irq_chip_pm_put \- Disable power for an IRQ chip
.SH SYNOPSIS
.B "int" irq_chip_pm_put
.BI "(struct irq_data *data "  ");"
.SH ARGUMENTS
.IP "data" 12
Pointer to interrupt specific data
.SH "DESCRIPTION"
Disable the power to the IRQ chip referenced by the interrupt data
structure, belongs. Note that power will only be disabled, once this
function has been called for all IRQs that have called \fBirq_chip_pm_get\fP.
