.TH "irq_set_chip" 9 "irq_set_chip" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
irq_set_chip \- set the irq chip for an irq
.SH SYNOPSIS
.B "int" irq_set_chip
.BI "(unsigned int irq "  ","
.BI "struct irq_chip *chip "  ");"
.SH ARGUMENTS
.IP "irq" 12
irq number
.IP "chip" 12
pointer to irq chip description structure
