.TH "irq_get_default_host" 9 "irq_get_default_host" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
irq_get_default_host \- Retrieve the "default" irq domain
.SH SYNOPSIS
.B "struct irq_domain *" irq_get_default_host
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "RETURN"
the default domain, if any.
.SH "DESCRIPTION"
Modern code should never use this. This should only be used on
systems that cannot implement a firmware->fwnode mapping (which
both DT and ACPI provide).
