.TH "is_boot_sector_ntfs" 9 "is_boot_sector_ntfs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
is_boot_sector_ntfs \- check whether a boot sector is a valid NTFS boot sector
.SH SYNOPSIS
.B "bool" is_boot_sector_ntfs
.BI "(const struct super_block *sb "  ","
.BI "const NTFS_BOOT_SECTOR *b "  ","
.BI "const bool silent "  ");"
.SH ARGUMENTS
.IP "sb" 12
Super block of the device to which \fIb\fP belongs.
.IP "b" 12
Boot sector of device \fIsb\fP to check.
.IP "silent" 12
If 'true', all output will be silenced.
.SH "DESCRIPTION"
\fBis_boot_sector_ntfs\fP checks whether the boot sector \fIb\fP is a valid NTFS boot
sector. Returns 'true' if it is valid and 'false' if not.

\fIsb\fP is only needed for warning/error output, i.e. it can be NULL when silent
is 'true'.
