.TH "is_module_percpu_address" 9 "is_module_percpu_address" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
is_module_percpu_address \- test whether address is from module static percpu
.SH SYNOPSIS
.B "bool" is_module_percpu_address
.BI "(unsigned long addr "  ");"
.SH ARGUMENTS
.IP "addr" 12
address to test
.SH "DESCRIPTION"
Test whether \fIaddr\fP belongs to module static percpu area.
.SH "RETURN"
true if \fIaddr\fP is from module static percpu area
