.TH "isci_task_send_lu_reset_sas" 9 "isci_task_send_lu_reset_sas" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
isci_task_send_lu_reset_sas \- This function is called by of the SAS Domain Template functions.
.SH SYNOPSIS
.B "int" isci_task_send_lu_reset_sas
.BI "(struct isci_host *isci_host "  ","
.BI "struct isci_remote_device *isci_device "  ","
.BI "u8 *lun "  ");"
.SH ARGUMENTS
.IP "isci_host" 12
-- undescribed --
.IP "isci_device" 12
-- undescribed --
.IP "lun" 12
This parameter specifies the lun to be reset.
.SH "DESCRIPTION"
status, zero indicates success.
