.TH "isci_request_set_open_reject_status" 9 "isci_request_set_open_reject_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
isci_request_set_open_reject_status \- This function prepares the I/O completion for OPEN_REJECT conditions.
.SH SYNOPSIS
.B "void" isci_request_set_open_reject_status
.BI "(struct isci_request *request "  ","
.BI "struct sas_task *task "  ","
.BI "enum service_response *response_ptr "  ","
.BI "enum exec_status *status_ptr "  ","
.BI "enum sas_open_rej_reason open_rej_reason "  ");"
.SH ARGUMENTS
.IP "request" 12
This parameter is the completed isci_request object.
.IP "task" 12
-- undescribed --
.IP "response_ptr" 12
This parameter specifies the service response for the I/O.
.IP "status_ptr" 12
This parameter specifies the exec status for the I/O.
.IP "open_rej_reason" 12
This parameter specifies the encoded reason for the
abandon-class reject.
.SH "DESCRIPTION"
none.
