.TH "isci_remote_device_stop" 9 "isci_remote_device_stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
isci_remote_device_stop \- This function is called internally to stop the remote device.
.SH SYNOPSIS
.B "enum sci_status" isci_remote_device_stop
.BI "(struct isci_host *ihost "  ","
.BI "struct isci_remote_device *idev "  ");"
.SH ARGUMENTS
.IP "ihost" 12
-- undescribed --
.IP "idev" 12
-- undescribed --
.SH "DESCRIPTION"
The status of the ihost request to stop.
