.TH "isci_port_link_down" 9 "isci_port_link_down" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
isci_port_link_down \- This function is called by the sci core when a link becomes inactive.
.SH SYNOPSIS
.B "void" isci_port_link_down
.BI "(struct isci_host *isci_host "  ","
.BI "struct isci_phy *isci_phy "  ","
.BI "struct isci_port *isci_port "  ");"
.SH ARGUMENTS
.IP "isci_host" 12
This parameter specifies the isci host object.
.IP "isci_phy" 12
-- undescribed --
.IP "isci_port" 12
-- undescribed --
