.TH "iscsi_suspend_queue" 9 "iscsi_suspend_queue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iscsi_suspend_queue \- suspend iscsi_queuecommand
.SH SYNOPSIS
.B "void" iscsi_suspend_queue
.BI "(struct iscsi_conn *conn "  ");"
.SH ARGUMENTS
.IP "conn" 12
iscsi conn to stop queueing IO on
.SH "DESCRIPTION"
This grabs the session frwd_lock to make sure no one is in
xmit_task/queuecommand, and then sets suspend to prevent
new commands from being queued. This only needs to be called
by offload drivers that need to sync a path like ep disconnect
with the iscsi_queuecommand/xmit_task. To start IO again libiscsi
will call iscsi_start_tx and iscsi_unblock_session when in FFP.
