.TH "iscsi_tcp_hdr_dissect" 9 "iscsi_tcp_hdr_dissect" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iscsi_tcp_hdr_dissect \- process PDU header
.SH SYNOPSIS
.B "int" iscsi_tcp_hdr_dissect
.BI "(struct iscsi_conn *conn "  ","
.BI "struct iscsi_hdr *hdr "  ");"
.SH ARGUMENTS
.IP "conn" 12
iSCSI connection
.IP "hdr" 12
PDU header
.SH "DESCRIPTION"
This function analyzes the header of the PDU received,
and performs several sanity checks. If the PDU is accompanied
by data, the receive buffer is set up to copy the incoming data
to the correct location.
