.TH "iscsi_boot_create_host_kset" 9 "iscsi_boot_create_host_kset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iscsi_boot_create_host_kset \- creates root sysfs tree for a scsi host
.SH SYNOPSIS
.B "struct iscsi_boot_kset *" iscsi_boot_create_host_kset
.BI "(unsigned int hostno "  ");"
.SH ARGUMENTS
.IP "hostno" 12
host number of scsi host
