.TH "iser_conn_release" 9 "iser_conn_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iser_conn_release \- Frees all conn objects and deallocs conn descriptor
.SH SYNOPSIS
.B "void" iser_conn_release
.BI "(struct iser_conn *iser_conn "  ");"
.SH ARGUMENTS
.IP "iser_conn" 12
iSER connection context
