.TH "ish_event_cb" 9 "ish_event_cb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ish_event_cb \- bus driver callback for incoming message
.SH SYNOPSIS
.B "void" ish_event_cb
.BI "(struct ishtp_cl_device *cl_device "  ");"
.SH ARGUMENTS
.IP "cl_device" 12
ISHTP client device for which this message is targeted.
.SH "DESCRIPTION"
Remove the packet from the list and process the message by calling
process_recv.
