.TH "ish_hw_start" 9 "ish_hw_start" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ish_hw_start \- Start ISH HW
.SH SYNOPSIS
.B "int" ish_hw_start
.BI "(struct ishtp_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
ishtp device pointer
.SH "DESCRIPTION"
Set host to ready state and wait for FW reset
.SH "RETURN"
0 for success else error fault code
