.TH "ish_hw_reset" 9 "ish_hw_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ish_hw_reset \- Call HW reset IPC callback
.SH SYNOPSIS
.B "int" ish_hw_reset
.BI "(struct ishtp_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
-- undescribed --
.SH "DESCRIPTION"

This interface is used to reset HW in case of error.
.SH "RETURN"
value from IPC hw_reset callback
