.TH "ishtp_recv" 9 "ishtp_recv" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_recv \- process ishtp message
.SH SYNOPSIS
.B "void" ishtp_recv
.BI "(struct ishtp_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
ishtp device
.SH "DESCRIPTION"
If a message with valid header and size is received, then
this function calls appropriate handler. The host or firmware
address is zero, then they are host bus management message,
otherwise they are message fo clients.
