.TH "ishtp_hbm_cl_hdr" 9 "ishtp_hbm_cl_hdr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_hbm_cl_hdr \- construct client hbm header
.SH SYNOPSIS
.B "void" ishtp_hbm_cl_hdr
.BI "(struct ishtp_cl *cl "  ","
.BI "uint8_t hbm_cmd "  ","
.BI "void *buf "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "cl" 12
client
.IP "hbm_cmd" 12
host bus message command
.IP "buf" 12
buffer for cl header
.IP "len" 12
buffer length
.SH "DESCRIPTION"
Initialize HBM buffer
