.TH "ishtp_hbm_dispatch" 9 "ishtp_hbm_dispatch" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_hbm_dispatch \- HBM dispatch function
.SH SYNOPSIS
.B "void" ishtp_hbm_dispatch
.BI "(struct ishtp_device *dev "  ","
.BI "struct ishtp_bus_message *hdr "  ");"
.SH ARGUMENTS
.IP "dev" 12
ISHTP device instance
.IP "hdr" 12
bus message
.SH "DESCRIPTION"
Bottom half read routine after ISR to handle the read bus message cmd
processing
