.TH "ishtp_cl_read_complete" 9 "ishtp_cl_read_complete" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_cl_read_complete \- read complete
.SH SYNOPSIS
.B "void" ishtp_cl_read_complete
.BI "(struct ishtp_cl_rb *rb "  ");"
.SH ARGUMENTS
.IP "rb" 12
Pointer to client request block
.SH "DESCRIPTION"
If the message is completely received call \fBishtp_cl_bus_rx_event\fP
to process message
