.TH "ishtp_cl_bus_match" 9 "ishtp_cl_bus_match" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_cl_bus_match \- Bus match() callback
.SH SYNOPSIS
.B "int" ishtp_cl_bus_match
.BI "(struct device *dev "  ","
.BI "struct device_driver *drv "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device structure
.IP "drv" 12
the driver structure
.SH "DESCRIPTION"
This is a bus match callback, called when a new ishtp_cl_device is
registered during ishtp bus client enumeration. Use the guid_t in
drv and dev to decide whether they match or not.
.SH "RETURN"
1 if dev & drv matches, 0 otherwise.
