.TH "ishtp_read_list_flush" 9 "ishtp_read_list_flush" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_read_list_flush \- Flush read queue
.SH SYNOPSIS
.B "void" ishtp_read_list_flush
.BI "(struct ishtp_cl *cl "  ");"
.SH ARGUMENTS
.IP "cl" 12
ishtp client instance
.SH "DESCRIPTION"
Used to remove all entries from read queue for a client
