.TH "ishtp_cl_io_rb_recycle" 9 "ishtp_cl_io_rb_recycle" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ishtp_cl_io_rb_recycle \- Recycle IO request blocks
.SH SYNOPSIS
.B "int" ishtp_cl_io_rb_recycle
.BI "(struct ishtp_cl_rb *rb "  ");"
.SH ARGUMENTS
.IP "rb" 12
IO request block
.SH "DESCRIPTION"
Re-append rb to its client's free list and send flow control if needed
.SH "RETURN"
0 on success else -EFAULT
