.TH "ismt_access" 9 "ismt_access" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ismt_access \- process an SMBus command
.SH SYNOPSIS
.B "int" ismt_access
.BI "(struct i2c_adapter *adap "  ","
.BI "u16 addr "  ","
.BI "unsigned short flags "  ","
.BI "char read_write "  ","
.BI "u8 command "  ","
.BI "int size "  ","
.BI "union i2c_smbus_data *data "  ");"
.SH ARGUMENTS
.IP "adap" 12
the i2c host adapter
.IP "addr" 12
address of the i2c/SMBus target
.IP "flags" 12
command options
.IP "read_write" 12
read from or write to device
.IP "command" 12
the i2c/SMBus command to issue
.IP "size" 12
SMBus transaction type
.IP "data" 12
read/write data buffer
