.TH "isst_if_cdev_unregister" 9 "isst_if_cdev_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
isst_if_cdev_unregister \- Unregister callback for IOCTL
.SH SYNOPSIS
.B "void" isst_if_cdev_unregister
.BI "(int device_type "  ");"
.SH ARGUMENTS
.IP "device_type" 12
The device type to unregister.
.SH "DESCRIPTION"
This function unregisters the previously registered callback. If this
is the last callback unregistering, then misc device is removed.
.SH "RETURN"
None.
