.TH "iudma_init" 9 "iudma_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iudma_init \- One-time initialization of all IUDMA channels.
.SH SYNOPSIS
.B "int" iudma_init
.BI "(struct bcm63xx_udc *udc "  ");"
.SH ARGUMENTS
.IP "udc" 12
Reference to the device controller.
.SH "DESCRIPTION"
Enable DMA, flush channels, and enable global IUDMA IRQs.
