.TH "iwl_dump_ini_mem" 9 "iwl_dump_ini_mem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
iwl_dump_ini_mem \- 
.SH SYNOPSIS
.B "u32" iwl_dump_ini_mem
.BI "(struct iwl_fw_runtime *fwrt "  ","
.BI "struct list_head *list "  ","
.BI "struct iwl_dump_ini_region_data *reg_data "  ","
.BI "const struct iwl_dump_ini_mem_ops *ops "  ");"
.SH ARGUMENTS
.IP "fwrt" 12
fw runtime struct
.IP "list" 12
list to add the dump tlv to
.IP "reg_data" 12
memory region
.IP "ops" 12
memory dump operations
.SH "DESCRIPTION"

Creates a dump tlv and copy a memory region into it.
Returns the size of the current dump tlv or 0 if failed
