.TH "ixgbe_ptp_set_ts_config" 9 "ixgbe_ptp_set_ts_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_ptp_set_ts_config \- user entry point for timestamp mode
.SH SYNOPSIS
.B "int" ixgbe_ptp_set_ts_config
.BI "(struct ixgbe_adapter *adapter "  ","
.BI "struct ifreq *ifr "  ");"
.SH ARGUMENTS
.IP "adapter" 12
pointer to adapter struct
.IP "ifr" 12
ioctl data
.SH "DESCRIPTION"
Set hardware to requested mode. If unsupported, return an error with no
changes. Otherwise, store the mode for future reference.
