.TH "ixgbe_mii_bus_init" 9 "ixgbe_mii_bus_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_mii_bus_init \- mii_bus structure setup
.SH SYNOPSIS
.B "s32" ixgbe_mii_bus_init
.BI "(struct ixgbe_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
.SH "DESCRIPTION"
Returns 0 on success, negative on failure

ixgbe_mii_bus_init initializes a mii_bus structure in adapter
