.TH "ixgbevf_init_ipsec_offload" 9 "ixgbevf_init_ipsec_offload" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbevf_init_ipsec_offload \- initialize registers for IPsec operation
.SH SYNOPSIS
.B "void" ixgbevf_init_ipsec_offload
.BI "(struct ixgbevf_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure
