.TH "ixgbe_release_eeprom_semaphore" 9 "ixgbe_release_eeprom_semaphore" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_release_eeprom_semaphore \- Release hardware semaphore
.SH SYNOPSIS
.B "void" ixgbe_release_eeprom_semaphore
.BI "(struct ixgbe_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure

This function clears hardware semaphore bits.
