.TH "ixgbe_need_crosstalk_fix" 9 "ixgbe_need_crosstalk_fix" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_need_crosstalk_fix \- Determine if we need to do cross talk fix
.SH SYNOPSIS
.B "bool" ixgbe_need_crosstalk_fix
.BI "(struct ixgbe_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure

Contains the logic to identify if we need to verify link for the
crosstalk fix
