.TH "ixgbe_get_etk_id" 9 "ixgbe_get_etk_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_get_etk_id \- Return Etrack ID from EEPROM
.SH SYNOPSIS
.B "void" ixgbe_get_etk_id
.BI "(struct ixgbe_hw *hw "  ","
.BI "struct ixgbe_nvm_version *nvm_ver "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
.IP "nvm_ver" 12
pointer to output structure

word read errors will return 0xFFFF
