.TH "ixgbe_check_fw_error" 9 "ixgbe_check_fw_error" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_check_fw_error \- Check firmware for errors
.SH SYNOPSIS
.B "bool" ixgbe_check_fw_error
.BI "(struct ixgbe_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
the adapter private structure
.SH "DESCRIPTION"
Check firmware errors in register FWSM
