.TH "ixgbe_read_i2c_combined_generic" 9 "ixgbe_read_i2c_combined_generic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_read_i2c_combined_generic \- Perform I2C read combined operation
.SH SYNOPSIS
.B "s32" ixgbe_read_i2c_combined_generic
.BI "(struct ixgbe_hw *hw "  ","
.BI "u8 addr "  ","
.BI "u16 reg "  ","
.BI "u16 *val "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to the hardware structure
.IP "addr" 12
I2C bus address to read from
.IP "reg" 12
I2C device register to read from
.IP "val" 12
pointer to location to receive read value
.SH "DESCRIPTION"
Returns an error code on error.
