.TH "ixgbe_setup_fc_backplane_x550em_a" 9 "ixgbe_setup_fc_backplane_x550em_a" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_setup_fc_backplane_x550em_a \- Set up flow control
.SH SYNOPSIS
.B "s32" ixgbe_setup_fc_backplane_x550em_a
.BI "(struct ixgbe_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure

Called at init time to set up flow control.
