.TH "ixgbe_init_hw_generic" 9 "ixgbe_init_hw_generic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_init_hw_generic \- Generic hardware initialization
.SH SYNOPSIS
.B "s32" ixgbe_init_hw_generic
.BI "(struct ixgbe_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure

Initialize the hardware by resetting the hardware, filling the bus info
structure and media type, clears all on chip counters, initializes receive
address registers, multicast table, VLAN filter table, calls routine to set
up link and flow control settings, and leaves transmit and receive units
disabled and uninitialized
