.TH "ixgbe_ipsec_add_sa" 9 "ixgbe_ipsec_add_sa" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_ipsec_add_sa \- program device with a security association
.SH SYNOPSIS
.B "int" ixgbe_ipsec_add_sa
.BI "(struct xfrm_state *xs "  ");"
.SH ARGUMENTS
.IP "xs" 12
pointer to transformer state struct
