.TH "ixgbe_reset_pipeline_82599" 9 "ixgbe_reset_pipeline_82599" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_reset_pipeline_82599 \- perform pipeline reset
.SH SYNOPSIS
.B "s32" ixgbe_reset_pipeline_82599
.BI "(struct ixgbe_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
.SH "DESCRIPTION"
Reset pipeline by asserting Restart_AN together with LMS change to ensure
full pipeline reset.  Note - We must hold the SW/FW semaphore before writing
to AUTOC, so this function assumes the semaphore is held.
