.TH "ixgbevf_poll" 9 "ixgbevf_poll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbevf_poll \- NAPI polling calback
.SH SYNOPSIS
.B "int" ixgbevf_poll
.BI "(struct napi_struct *napi "  ","
.BI "int budget "  ");"
.SH ARGUMENTS
.IP "napi" 12
napi struct with our devices info in it
.IP "budget" 12
amount of work driver is allowed to do this pass, in packets
.SH "DESCRIPTION"
This function will clean more than one or more rings associated with a
q_vector.
