.TH "ixgbe_calc_eeprom_checksum_generic" 9 "ixgbe_calc_eeprom_checksum_generic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_calc_eeprom_checksum_generic \- Calculates and returns the checksum
.SH SYNOPSIS
.B "s32" ixgbe_calc_eeprom_checksum_generic
.BI "(struct ixgbe_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
