.TH "ixgbe_write_eewr_buffer_generic" 9 "ixgbe_write_eewr_buffer_generic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_write_eewr_buffer_generic \- Write EEPROM word(s) using EEWR
.SH SYNOPSIS
.B "s32" ixgbe_write_eewr_buffer_generic
.BI "(struct ixgbe_hw *hw "  ","
.BI "u16 offset "  ","
.BI "u16 words "  ","
.BI "u16 *data "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
.IP "offset" 12
offset of  word in the EEPROM to write
.IP "words" 12
number of words
.IP "data" 12
word(s) write to the EEPROM

Write a 16 bit word(s) to the EEPROM using the EEWR register.
