.TH "ixgbe_identify_phy_generic" 9 "ixgbe_identify_phy_generic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_identify_phy_generic \- Get physical layer module
.SH SYNOPSIS
.B "s32" ixgbe_identify_phy_generic
.BI "(struct ixgbe_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure

Determines the physical layer module found on the current adapter.
