.TH "ixgbe_cache_ring_dcb" 9 "ixgbe_cache_ring_dcb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_cache_ring_dcb \- Descriptor ring to register mapping for DCB
.SH SYNOPSIS
.B "bool" ixgbe_cache_ring_dcb
.BI "(struct ixgbe_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure to initialize
.SH "DESCRIPTION"
Cache the descriptor ring offsets for DCB to the assigned rings.
