.TH "ixgbe_stop_ipsec_offload" 9 "ixgbe_stop_ipsec_offload" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_stop_ipsec_offload \- tear down the ipsec offload
.SH SYNOPSIS
.B "void" ixgbe_stop_ipsec_offload
.BI "(struct ixgbe_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure
