.TH "ixgbe_cache_ring_rss" 9 "ixgbe_cache_ring_rss" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_cache_ring_rss \- Descriptor ring to register mapping for RSS
.SH SYNOPSIS
.B "bool" ixgbe_cache_ring_rss
.BI "(struct ixgbe_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
board private structure to initialize
.SH "DESCRIPTION"
Cache the descriptor ring offsets for RSS to the assigned rings.
