.TH "ixgbe_setup_mac_link_X540" 9 "ixgbe_setup_mac_link_X540" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixgbe_setup_mac_link_X540 \- Set the auto advertised capabilitires
.SH SYNOPSIS
.B "s32" ixgbe_setup_mac_link_X540
.BI "(struct ixgbe_hw *hw "  ","
.BI "ixgbe_link_speed speed "  ","
.BI "bool autoneg_wait_to_complete "  ");"
.SH ARGUMENTS
.IP "hw" 12
pointer to hardware structure
.IP "speed" 12
new link speed
.IP "autoneg_wait_to_complete" 12
true when waiting for completion is needed
