.TH "ixp4xx_irq_init" 9 "ixp4xx_irq_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ixp4xx_irq_init \- Function to initialize the irqchip from boardfiles
.SH SYNOPSIS
.B "void" ixp4xx_irq_init
.BI "(resource_size_t irqbase "  ","
.BI "bool is_356 "  ");"
.SH ARGUMENTS
.IP "irqbase" 12
physical base for the irq controller
.IP "is_356" 12
if this is an IXP43x, IXP45x or IXP46x SoC variant
