.TH "jbd2_mark_journal_empty" 9 "jbd2_mark_journal_empty" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
jbd2_mark_journal_empty \- Mark on disk journal as empty.
.SH SYNOPSIS
.B "void" jbd2_mark_journal_empty
.BI "(journal_t *journal "  ","
.BI "int write_op "  ");"
.SH ARGUMENTS
.IP "journal" 12
The journal to update.
.IP "write_op" 12
With which operation should we write the journal sb
.SH "DESCRIPTION"
Update a journal's dynamic superblock fields to show that journal is empty.
Write updated superblock to disk waiting for IO to complete.
