.TH "jbd2_journal_force_commit" 9 "jbd2_journal_force_commit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
jbd2_journal_force_commit \- force any uncommitted transactions
.SH SYNOPSIS
.B "int" jbd2_journal_force_commit
.BI "(journal_t *journal "  ");"
.SH ARGUMENTS
.IP "journal" 12
journal to force
.SH "DESCRIPTION"
Caller want unconditional commit. We can only force the running transaction
if we don't have an active handle, otherwise, we will deadlock.
