.TH "kbuffer_ptr_delta" 9 "kbuffer_ptr_delta" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kbuffer_ptr_delta \- read the delta field from a record
.SH SYNOPSIS
.B "unsigned int" kbuffer_ptr_delta
.BI "(struct kbuffer *kbuf "  ","
.BI "void *ptr "  ");"
.SH ARGUMENTS
.IP "kbuf" 12
The kbuffer to load
.IP "ptr" 12
The record in the buffe.
.SH "DESCRIPTION"
Return the timestamp delta from a record
