.TH "kempld_get_info" 9 "kempld_get_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kempld_get_info \- update device specific information
.SH SYNOPSIS
.B "int" kempld_get_info
.BI "(struct kempld_device_data *pld "  ");"
.SH ARGUMENTS
.IP "pld" 12
kempld_device_data structure describing the PLD
.SH "DESCRIPTION"
This function calls the configured board specific kempld_get_info_XXXX
function which is responsible for gathering information about the specific
hardware. The information is then stored within the pld structure.
