.TH "kernfs_put_active" 9 "kernfs_put_active" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kernfs_put_active \- put an active reference to kernfs_node
.SH SYNOPSIS
.B "void" kernfs_put_active
.BI "(struct kernfs_node *kn "  ");"
.SH ARGUMENTS
.IP "kn" 12
kernfs_node to put an active reference to

Put an active reference to \fIkn\fP.  This function is noop if \fIkn\fP
is NULL.
