.TH "kernel_listen" 9 "kernel_listen" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kernel_listen \- move socket to listening state (kernel space)
.SH SYNOPSIS
.B "int" kernel_listen
.BI "(struct socket *sock "  ","
.BI "int backlog "  ");"
.SH ARGUMENTS
.IP "sock" 12
socket
.IP "backlog" 12
pending connections queue size

Returns 0 or an error.
