.TH "kernfs_get_active" 9 "kernfs_get_active" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kernfs_get_active \- get an active reference to kernfs_node
.SH SYNOPSIS
.B "struct kernfs_node *" kernfs_get_active
.BI "(struct kernfs_node *kn "  ");"
.SH ARGUMENTS
.IP "kn" 12
kernfs_node to get an active reference to

Get an active reference of \fIkn\fP.  This function is noop if \fIkn\fP
is NULL.
.SH "RETURN"
Pointer to \fIkn\fP on success, NULL on failure.
