.TH "kernfs_super_ns" 9 "kernfs_super_ns" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kernfs_super_ns \- determine the namespace tag of a kernfs super_block
.SH SYNOPSIS
.B "const void *" kernfs_super_ns
.BI "(struct super_block *sb "  ");"
.SH ARGUMENTS
.IP "sb" 12
super_block of interest
.SH "DESCRIPTION"
Return the namespace tag associated with kernfs super_block \fIsb\fP.
