.TH "keystone_timer_barrier" 9 "keystone_timer_barrier" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
keystone_timer_barrier \- write memory barrier use explicit barrier to avoid using readl/writel non relaxed function variants, because in our case non relaxed variants hide the true places where barrier is needed.
.SH SYNOPSIS
.B "void" keystone_timer_barrier
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
