.TH "kfree_const" 9 "kfree_const" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kfree_const \- conditionally free memory
.SH SYNOPSIS
.B "void" kfree_const
.BI "(const void *x "  ");"
.SH ARGUMENTS
.IP "x" 12
pointer to the memory
.SH "DESCRIPTION"
Function calls kfree only if \fIx\fP is not in .rodata section.
