.TH "klp_shadow_free_all" 9 "klp_shadow_free_all" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
klp_shadow_free_all \- detach and free all <*, id> shadow variables
.SH SYNOPSIS
.B "void" klp_shadow_free_all
.BI "(unsigned long id "  ","
.BI "klp_shadow_dtor_t dtor "  ");"
.SH ARGUMENTS
.IP "id" 12
data identifier
.IP "dtor" 12
custom callback that can be used to unregister the variable
and/or free data that the shadow variable points to (optional)
.SH "DESCRIPTION"
This function releases the memory for all <*, id> shadow variable
instances, callers should stop referencing them accordingly.
