.TH "kmemleak_alloc_phys" 9 "kmemleak_alloc_phys" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kmemleak_alloc_phys \- similar to kmemleak_alloc but taking a physical address argument
.SH SYNOPSIS
.B "void __ref" kmemleak_alloc_phys
.BI "(phys_addr_t phys "  ","
.BI "size_t size "  ","
.BI "int min_count "  ","
.BI "gfp_t gfp "  ");"
.SH ARGUMENTS
.IP "phys" 12
physical address of the object
.IP "size" 12
size of the object
.IP "min_count" 12
minimum number of references to this object.
See \fBkmemleak_alloc\fP
.IP "gfp" 12
\fBkmalloc\fP flags used for kmemleak internal memory allocations
