.TH "kmemleak_free_part_phys" 9 "kmemleak_free_part_phys" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kmemleak_free_part_phys \- similar to kmemleak_free_part but taking a physical address argument
.SH SYNOPSIS
.B "void __ref" kmemleak_free_part_phys
.BI "(phys_addr_t phys "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "phys" 12
physical address if the beginning or inside an object. This
also represents the start of the range to be freed
.IP "size" 12
size to be unregistered
