.TH "knav_dma_open_channel" 9 "knav_dma_open_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
knav_dma_open_channel \- try to setup an exclusive slave channel
.SH SYNOPSIS
.B "void *" knav_dma_open_channel
.BI "(struct device *dev "  ","
.BI "const char *name "  ","
.BI "struct knav_dma_cfg *config "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to client device structure
.IP "name" 12
slave channel name
.IP "config" 12
dma configuration parameters
.SH "DESCRIPTION"
Returns pointer to appropriate DMA channel on success or error.
