.TH "ks8851_rdreg16_spi" 9 "ks8851_rdreg16_spi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ks8851_rdreg16_spi \- read 16 bit register from device via SPI
.SH SYNOPSIS
.B "unsigned int" ks8851_rdreg16_spi
.BI "(struct ks8851_net *ks "  ","
.BI "unsigned int reg "  ");"
.SH ARGUMENTS
.IP "ks" 12
The chip information
.IP "reg" 12
The register address
.SH "DESCRIPTION"
Read a 16bit register from the chip, returning the result
