.TH "ks8851_phy_reg" 9 "ks8851_phy_reg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ks8851_phy_reg \- convert MII register into a KS8851 register
.SH SYNOPSIS
.B "int" ks8851_phy_reg
.BI "(int reg "  ");"
.SH ARGUMENTS
.IP "reg" 12
MII register number.
.SH "DESCRIPTION"
Return the KS8851 register number for the corresponding MII PHY register
if possible. Return zero if the MII register has no direct mapping to the
KS8851 register set.
