.TH "ks8851_read_mac_addr" 9 "ks8851_read_mac_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ks8851_read_mac_addr \- read mac address from device registers
.SH SYNOPSIS
.B "void" ks8851_read_mac_addr
.BI "(struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
The network device
.SH "DESCRIPTION"
Update our copy of the KS8851 MAC address from the registers of \fIdev\fP.
