.TH "ks_pcie_clear_dbi_mode" 9 "ks_pcie_clear_dbi_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ks_pcie_clear_dbi_mode \- Disable DBI mode
.SH SYNOPSIS
.B "void" ks_pcie_clear_dbi_mode
.BI "(struct keystone_pcie *ks_pcie "  ");"
.SH ARGUMENTS
.IP "ks_pcie" 12
-- undescribed --
.SH "DESCRIPTION"

Since modification of dbi_cs2 involves different clock domain, read the
status back to ensure the transition is complete.
