.TH "kstrndup" 9 "kstrndup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kstrndup \- allocate space for and copy an existing string
.SH SYNOPSIS
.B "char *" kstrndup
.BI "(const char *s "  ","
.BI "size_t max "  ","
.BI "gfp_t gfp "  ");"
.SH ARGUMENTS
.IP "s" 12
the string to duplicate
.IP "max" 12
read at most \fImax\fP chars from \fIs\fP
.IP "gfp" 12
the GFP mask used in the \fBkmalloc\fP call when allocating memory
.SH "NOTE"
Use \fBkmemdup_nul\fP instead if the size is known exactly.
.SH "RETURN"
newly allocated copy of \fIs\fP or NULL in case of error
