.TH "ksz_init_rx_buffers" 9 "ksz_init_rx_buffers" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ksz_init_rx_buffers \- initialize receive descriptors
.SH SYNOPSIS
.B "void" ksz_init_rx_buffers
.BI "(struct dev_info *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
Adapter information structure.
.SH "DESCRIPTION"
This routine initializes DMA buffers for receiving.
