.TH "ksz_free_buffers" 9 "ksz_free_buffers" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ksz_free_buffers \- free buffers used in the descriptors
.SH SYNOPSIS
.B "void" ksz_free_buffers
.BI "(struct dev_info *adapter "  ","
.BI "struct ksz_desc_info *desc_info "  ","
.BI "int direction "  ");"
.SH ARGUMENTS
.IP "adapter" 12
Adapter information structure.
.IP "desc_info" 12
Descriptor information structure.
.IP "direction" 12
to or from device
.SH "DESCRIPTION"
This local routine frees buffers used in the DMA buffers.
