.TH "kthread_func" 9 "kthread_func" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kthread_func \- return the function specified on kthread creation
.SH SYNOPSIS
.B "void *" kthread_func
.BI "(struct task_struct *task "  ");"
.SH ARGUMENTS
.IP "task" 12
kthread task in question
.SH "DESCRIPTION"
Returns NULL if the task is not a kthread.
