.TH "kthread_blkcg" 9 "kthread_blkcg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kthread_blkcg \- get associated blkcg css of current kthread
.SH SYNOPSIS
.B "struct cgroup_subsys_state *" kthread_blkcg
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Current thread must be a kthread.
