.TH "kvm_vz_save_guesttlb" 9 "kvm_vz_save_guesttlb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kvm_vz_save_guesttlb \- Save a range of guest TLB entries.
.SH SYNOPSIS
.B "void" kvm_vz_save_guesttlb
.BI "(struct kvm_mips_tlb *buf "  ","
.BI "unsigned int index "  ","
.BI "unsigned int count "  ");"
.SH ARGUMENTS
.IP "buf" 12
Buffer to write TLB entries into.
.IP "index" 12
Start index.
.IP "count" 12
Number of entries to save.
.SH "DESCRIPTION"
Save a range of guest TLB entries. The caller must ensure interrupts are
disabled.
