.TH "kvm_mips_config1_wrmask" 9 "kvm_mips_config1_wrmask" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kvm_mips_config1_wrmask \- Find mask of writable bits in guest Config1
.SH SYNOPSIS
.B "unsigned int" kvm_mips_config1_wrmask
.BI "(struct kvm_vcpu *vcpu "  ");"
.SH ARGUMENTS
.IP "vcpu" 12
Virtual CPU.
.SH "DESCRIPTION"
Finds the mask of bits which are writable in the guest's Config1 CP0
register, by userland (currently read-only to the guest).
