.TH "kvm_pmu_set_counter_value" 9 "kvm_pmu_set_counter_value" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
kvm_pmu_set_counter_value \- set PMU counter value
.SH SYNOPSIS
.B "void" kvm_pmu_set_counter_value
.BI "(struct kvm_vcpu *vcpu "  ","
.BI "u64 select_idx "  ","
.BI "u64 val "  ");"
.SH ARGUMENTS
.IP "vcpu" 12
The vcpu pointer
.IP "select_idx" 12
The counter index
.IP "val" 12
The counter value
