.TH "ladder_do_selection" 9 "ladder_do_selection" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ladder_do_selection \- prepares private data for a state change
.SH SYNOPSIS
.B "void" ladder_do_selection
.BI "(struct cpuidle_device *dev "  ","
.BI "struct ladder_device *ldev "  ","
.BI "int old_idx "  ","
.BI "int new_idx "  ");"
.SH ARGUMENTS
.IP "dev" 12
-- undescribed --
.IP "ldev" 12
the ladder device
.IP "old_idx" 12
the current state index
.IP "new_idx" 12
the new target state index
