.TH "lbs_get_reg" 9 "lbs_get_reg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lbs_get_reg \- Read a MAC, Baseband, or RF register
.SH SYNOPSIS
.B "int" lbs_get_reg
.BI "(struct lbs_private *priv "  ","
.BI "u16 reg "  ","
.BI "u16 offset "  ","
.BI "u32 *value "  ");"
.SH ARGUMENTS
.IP "priv" 12
pointer to \fIstruct lbs_private\fP
.IP "reg" 12
register command, one of CMD_MAC_REG_ACCESS,
CMD_BBP_REG_ACCESS, or CMD_RF_REG_ACCESS
.IP "offset" 12
byte offset of the register to get
.IP "value" 12
on success, the value of the register at 'offset'
.SH "RETURN"
0 on success, error code on failure
