.TH "lbs_set_monitor_mode" 9 "lbs_set_monitor_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lbs_set_monitor_mode \- Enable or disable monitor mode (only implemented on OLPC usb8388 FW)
.SH SYNOPSIS
.B "int" lbs_set_monitor_mode
.BI "(struct lbs_private *priv "  ","
.BI "int enable "  ");"
.SH ARGUMENTS
.IP "priv" 12
A pointer to \fIstruct lbs_private\fP structure
.IP "enable" 12
1 to enable monitor mode, 0 to disable
.SH "RETURN"
0 on success, error on failure
