.TH "lbs_tx_lockup_handler" 9 "lbs_tx_lockup_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lbs_tx_lockup_handler \- handles the timeout of the passing of TX frames to the hardware. This is known to frequently happen with SD8686 when waking up after a Wake-on-WLAN-triggered resume.
.SH SYNOPSIS
.B "void" lbs_tx_lockup_handler
.BI "(struct timer_list *t "  ");"
.SH ARGUMENTS
.IP "t" 12
Context from which to retrieve a \fIstruct lbs_private\fP pointer
