.TH "lbs_set_11d_domain_info" 9 "lbs_set_11d_domain_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lbs_set_11d_domain_info \- Send regulatory and 802.11d domain information to the firmware
.SH SYNOPSIS
.B "int" lbs_set_11d_domain_info
.BI "(struct lbs_private *priv "  ");"
.SH ARGUMENTS
.IP "priv" 12
pointer to \fIstruct lbs_private\fP
.SH "RETURN"
0 on success, error code on failure
