.TH "lbtf_update_hw_spec" 9 "lbtf_update_hw_spec" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lbtf_update_hw_spec \- Updates the hardware details.
.SH SYNOPSIS
.B "int" lbtf_update_hw_spec
.BI "(struct lbtf_private *priv "  ");"
.SH ARGUMENTS
.IP "priv" 12
A pointer to struct lbtf_private structure
.SH "RETURN"
0 on success, error on failure
