.TH "lc_index_of" 9 "lc_index_of" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lc_index_of \- 
.SH SYNOPSIS
.B "unsigned int" lc_index_of
.BI "(struct lru_cache *lc "  ","
.BI "struct lc_element *e "  ");"
.SH ARGUMENTS
.IP "lc" 12
the lru cache to operate on
.IP "e" 12
the element to query for its index position in lc->element
