.TH "ldm_frag_commit" 9 "ldm_frag_commit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ldm_frag_commit \- Validate fragmented VBLKs and add them to the database
.SH SYNOPSIS
.B "bool" ldm_frag_commit
.BI "(struct list_head *frags "  ","
.BI "struct ldmdb *ldb "  ");"
.SH ARGUMENTS
.IP "frags" 12
Linked list of VBLK fragments
.IP "ldb" 12
Cache of the database structures
.SH "DESCRIPTION"
Now that all the fragmented VBLKs have been collected, they must be added to
the database for later use.
.SH "RETURN"
'true'   All the fragments we added successfully
'false'  One or more of the fragments we invalid
