.TH "ldm_ldmdb_add" 9 "ldm_ldmdb_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ldm_ldmdb_add \- Adds a raw VBLK entry to the ldmdb database
.SH SYNOPSIS
.B "bool" ldm_ldmdb_add
.BI "(u8 *data "  ","
.BI "int len "  ","
.BI "struct ldmdb *ldb "  ");"
.SH ARGUMENTS
.IP "data" 12
Raw VBLK to add to the database
.IP "len" 12
Size of the raw VBLK
.IP "ldb" 12
Cache of the database structures
.SH "DESCRIPTION"
The VBLKs are sorted into categories.  Partitions are also sorted by offset.

N.B.  This function does not check the validity of the VBLKs.
.SH "RETURN"
'true'   The VBLK was added
'false'  An error occurred
