.TH "leaf_dealloc" 9 "leaf_dealloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
leaf_dealloc \- Deallocate a directory leaf
.SH SYNOPSIS
.B "int" leaf_dealloc
.BI "(struct gfs2_inode *dip "  ","
.BI "u32 index "  ","
.BI "u32 len "  ","
.BI "u64 leaf_no "  ","
.BI "struct buffer_head *leaf_bh "  ","
.BI "int last_dealloc "  ");"
.SH ARGUMENTS
.IP "dip" 12
the directory
.IP "index" 12
the hash table offset in the directory
.IP "len" 12
the number of pointers to this leaf
.IP "leaf_no" 12
the leaf number
.IP "leaf_bh" 12
buffer_head for the starting leaf
last_dealloc: 1 if this is the final dealloc for the leaf, else 0
.IP "last_dealloc" 12
-- undescribed --
.SH "RETURN"
errno
