.TH "led_classdev_suspend" 9 "led_classdev_suspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
led_classdev_suspend \- suspend an led_classdev.
.SH SYNOPSIS
.B "void" led_classdev_suspend
.BI "(struct led_classdev *led_cdev "  ");"
.SH ARGUMENTS
.IP "led_cdev" 12
the led_classdev to suspend.
