.TH "linear_range_get_max_value" 9 "linear_range_get_max_value" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
linear_range_get_max_value \- return the largest value in a range
.SH SYNOPSIS
.B "unsigned int" linear_range_get_max_value
.BI "(const struct linear_range *r "  ");"
.SH ARGUMENTS
.IP "r" 12
pointer to linear range where value is looked from
.SH "RETURN"
the largest value in the given range
