.TH "link_new_ver" 9 "link_new_ver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
link_new_ver \- Create a new physical link config from the old version of source.
.SH SYNOPSIS
.B "int" link_new_ver
.BI "(struct soc_tplg *tplg "  ","
.BI "struct snd_soc_tplg_link_config *src "  ","
.BI "struct snd_soc_tplg_link_config **link "  ");"
.SH ARGUMENTS
.IP "tplg" 12
topology context
.IP "src" 12
old version of phyical link config as a source
.IP "link" 12
latest version of physical link config created from the source
.SH "DESCRIPTION"
Support from vesion 4. User need free the returned link config manually.
