.TH "liquidio_ptp_enable" 9 "liquidio_ptp_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
liquidio_ptp_enable \- Check if PTP is enabled
.SH SYNOPSIS
.B "int" liquidio_ptp_enable
.BI "(struct ptp_clock_info __maybe_unused *ptp "  ","
.BI "struct ptp_clock_request __maybe_unused *rq "  ","
.BI "int __maybe_unused on "  ");"
.SH ARGUMENTS
.IP "ptp" 12
PTP clock info
.IP "rq" 12
request
.IP "on" 12
is it on
