.TH "liquidio_destroy_nic_device" 9 "liquidio_destroy_nic_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
liquidio_destroy_nic_device \- Destroy NIC device interface
.SH SYNOPSIS
.B "void" liquidio_destroy_nic_device
.BI "(struct octeon_device *oct "  ","
.BI "int ifidx "  ");"
.SH ARGUMENTS
.IP "oct" 12
octeon device
.IP "ifidx" 12
which interface to destroy
.SH "DESCRIPTION"
Cleanup associated with each interface for an Octeon device  when NIC
module is being unloaded or if initialization fails during load.
