.TH "liquidio_push_packet" 9 "liquidio_push_packet" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
liquidio_push_packet \- Routine to push packets arriving on Octeon interface upto network layer.
.SH SYNOPSIS
.B "void" liquidio_push_packet
.BI "(u32 __maybe_unused octeon_id "  ","
.BI "void *skbuff "  ","
.BI "u32 len "  ","
.BI "union octeon_rh *rh "  ","
.BI "void *param "  ","
.BI "void *arg "  ");"
.SH ARGUMENTS
.IP "octeon_id" 12
octeon device id.
.IP "skbuff" 12
skbuff struct to be passed to network layer.
.IP "len" 12
size of total data received.
.IP "rh" 12
Control header associated with the packet
.IP "param" 12
additional control data with the packet
.IP "arg" 12
farg registered in droq_ops
