.TH "llc_pdu_init_as_rnr_rsp" 9 "llc_pdu_init_as_rnr_rsp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
llc_pdu_init_as_rnr_rsp \- builds RNR response pdu
.SH SYNOPSIS
.B "void" llc_pdu_init_as_rnr_rsp
.BI "(struct sk_buff *skb "  ","
.BI "u8 f_bit "  ","
.BI "u8 nr "  ");"
.SH ARGUMENTS
.IP "skb" 12
Address of the frame to build
.IP "f_bit" 12
The F bit to set in the PDU
.IP "nr" 12
The seq. number of the expected data PDU from the remote

Builds a pdu frame as an RNR response.
