.TH "llc_sap_action_send_xid_r" 9 "llc_sap_action_send_xid_r" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
llc_sap_action_send_xid_r \- send XID PDU resp to MAC for received XID
.SH SYNOPSIS
.B "int" llc_sap_action_send_xid_r
.BI "(struct llc_sap *sap "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "sap" 12
SAP
.IP "skb" 12
the event to send

Send XID response PDU to MAC in response to an earlier received XID
command PDU. Verify event is a PDU type event
