.TH "llc_sap_action_send_xid_c" 9 "llc_sap_action_send_xid_c" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
llc_sap_action_send_xid_c \- send XID PDU as response to XID REQ
.SH SYNOPSIS
.B "int" llc_sap_action_send_xid_c
.BI "(struct llc_sap *sap "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "sap" 12
SAP
.IP "skb" 12
the event to send

Send a XID command PDU to MAC layer in response to a XID REQUEST
primitive from the network layer. Verify event is a primitive type
event. Verify the primitive is a XID REQUEST.
