.TH "loader_ishtp_cl_probe" 9 "loader_ishtp_cl_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
loader_ishtp_cl_probe \- ISH-TP client driver probe
.SH SYNOPSIS
.B "int" loader_ishtp_cl_probe
.BI "(struct ishtp_cl_device *cl_device "  ");"
.SH ARGUMENTS
.IP "cl_device" 12
ISH-TP client device instance
.SH "DESCRIPTION"
This function gets called on device create on ISH-TP bus
.SH "RETURN"
0 for success, negative error code for failure
