.TH "loader_init" 9 "loader_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
loader_init \- Init function for ISH-TP client
.SH SYNOPSIS
.B "int" loader_init
.BI "(struct ishtp_cl *loader_ishtp_cl "  ","
.BI "int reset "  ");"
.SH ARGUMENTS
.IP "loader_ishtp_cl" 12
ISH-TP client instance
.IP "reset" 12
true if called for init after reset
.SH "RETURN"
0 for success, negative error code for failure
