.TH "locks_translate_pid" 9 "locks_translate_pid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
locks_translate_pid \- translate a file_lock's fl_pid number into a namespace
.SH SYNOPSIS
.B "pid_t" locks_translate_pid
.BI "(struct file_lock *fl "  ","
.BI "struct pid_namespace *ns "  ");"
.SH ARGUMENTS
.IP "fl" 12
The file_lock who's fl_pid should be translated
.IP "ns" 12
The namespace into which the pid should be translated
.SH "DESCRIPTION"
Used to tranlate a fl_pid into a namespace virtual pid number
