.TH "lookup_swap_cgroup_id" 9 "lookup_swap_cgroup_id" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lookup_swap_cgroup_id \- lookup mem_cgroup id tied to swap entry
.SH SYNOPSIS
.B "unsigned short" lookup_swap_cgroup_id
.BI "(swp_entry_t ent "  ");"
.SH ARGUMENTS
.IP "ent" 12
swap entry to be looked up.
.SH "DESCRIPTION"
Returns ID of mem_cgroup at success. 0 at failure. (0 is invalid ID)
