.TH "lookup_memtype" 9 "lookup_memtype" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lookup_memtype \- Looksup the memory type for a physical address
.SH SYNOPSIS
.B "enum page_cache_mode" lookup_memtype
.BI "(u64 paddr "  ");"
.SH ARGUMENTS
.IP "paddr" 12
physical address of which memory type needs to be looked up
.SH "DESCRIPTION"
Only to be called when PAT is enabled

Returns _PAGE_CACHE_MODE_WB, _PAGE_CACHE_MODE_WC, _PAGE_CACHE_MODE_UC_MINUS
or _PAGE_CACHE_MODE_WT.
