.TH "lpfc_sli4_init_rpi_hdrs" 9 "lpfc_sli4_init_rpi_hdrs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_init_rpi_hdrs \- Post the rpi header memory region to the port
.SH SYNOPSIS
.B "int" lpfc_sli4_init_rpi_hdrs
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine is invoked to post rpi header templates to the
port for those SLI4 ports that do not support extents.  This routine
posts a PAGE_SIZE memory region to the port to hold up to
PAGE_SIZE modulo 64 rpi context headers.  This is an initialization routine
and should be called only when interrupts are disabled.

Return codes
0 - successful
-ERROR - otherwise.
