.TH "lpfc_sli4_cq_event_pool_destroy" 9 "lpfc_sli4_cq_event_pool_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_cq_event_pool_destroy \- Free completion-queue event free pool
.SH SYNOPSIS
.B "void" lpfc_sli4_cq_event_pool_destroy
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine is invoked to free the pool of completion queue events at
driver unload time. Note that, it is the responsibility of the driver
cleanup routine to free all the outstanding completion-queue events
allocated from this pool back into the pool before invoking this routine
to destroy the pool.
