.TH "lpfc_nvme_ls_req" 9 "lpfc_nvme_ls_req" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_nvme_ls_req \- Issue an NVME Link Service request
.SH SYNOPSIS
.B "int" lpfc_nvme_ls_req
.BI "(struct nvme_fc_local_port *pnvme_lport "  ","
.BI "struct nvme_fc_remote_port *pnvme_rport "  ","
.BI "struct nvmefc_ls_req *pnvme_lsreq "  ");"
.SH ARGUMENTS
.IP "pnvme_lport" 12
Transport localport that LS is to be issued from.
.IP "pnvme_rport" 12
Transport remoteport that LS is to be sent to.
.IP "pnvme_lsreq" 12
the transport nvme_ls_req structure for the LS
.SH "DESCRIPTION"
Driver registers this routine to handle any link service request
from the nvme_fc transport to a remote nvme-aware port.

Return value :
0 - Success
non-zero: various error codes, in form of -Exxx
