.TH "lpfc_bsg_sli_cfg_write_cmd_ext" 9 "lpfc_bsg_sli_cfg_write_cmd_ext" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_bsg_sli_cfg_write_cmd_ext \- sli_config non-embedded mailbox cmd write
.SH SYNOPSIS
.B "int" lpfc_bsg_sli_cfg_write_cmd_ext
.BI "(struct lpfc_hba *phba "  ","
.BI "struct bsg_job *job "  ","
.BI "enum nemb_type nemb_tp "  ","
.BI "struct lpfc_dmabuf *dmabuf "  ");"
.SH ARGUMENTS
.IP "phba" 12
Pointer to HBA context object.
.IP "job" 12
Pointer to the job object.
.IP "nemb_tp" 12
Enumerate of non-embedded mailbox command type.
.IP "dmabuf" 12
Pointer to a DMA buffer descriptor.
.SH "DESCRIPTION"
This routine performs SLI_CONFIG (0x9B) write mailbox command operation with
non-embedded external bufffers.
