.TH "lpfc_adjust_pvt_pool_count" 9 "lpfc_adjust_pvt_pool_count" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_adjust_pvt_pool_count \- Adjust private pool count
.SH SYNOPSIS
.B "void" lpfc_adjust_pvt_pool_count
.BI "(struct lpfc_hba *phba "  ","
.BI "u32 hwqid "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.IP "hwqid" 12
belong to which HWQ.
.SH "DESCRIPTION"
This routine moves some XRIs from private to public pool when private pool
is not busy.
