.TH "lpfc_get_host_symbolic_name" 9 "lpfc_get_host_symbolic_name" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_get_host_symbolic_name \- Copy symbolic name into the scsi host
.SH SYNOPSIS
.B "void" lpfc_get_host_symbolic_name
.BI "(struct Scsi_Host *shost "  ");"
.SH ARGUMENTS
.IP "shost" 12
kernel scsi host pointer.
