.TH "lpfc_update_rcv_time_stamp" 9 "lpfc_update_rcv_time_stamp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_update_rcv_time_stamp \- Update vport's rcv seq time stamp
.SH SYNOPSIS
.B "void" lpfc_update_rcv_time_stamp
.BI "(struct lpfc_vport *vport "  ");"
.SH ARGUMENTS
.IP "vport" 12
The vport to work on.
.SH "DESCRIPTION"
This function updates the receive sequence time stamp for this vport. The
receive sequence time stamp indicates the time that the last frame of the
the sequence that has been idle for the longest amount of time was received.
the driver uses this time stamp to indicate if any received sequences have
timed out.
