.TH "lpfc_sli4_free_xri" 9 "lpfc_sli4_free_xri" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_free_xri \- Release an xri for reuse.
.SH SYNOPSIS
.B "void" lpfc_sli4_free_xri
.BI "(struct lpfc_hba *phba "  ","
.BI "int xri "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.IP "xri" 12
xri to release.
.SH "DESCRIPTION"
This routine is invoked to release an xri to the pool of
available rpis maintained by the driver.
