.TH "lpfc_jedec_to_ascii" 9 "lpfc_jedec_to_ascii" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_jedec_to_ascii \- Hex to ascii convertor according to JEDEC rules
.SH SYNOPSIS
.B "void" lpfc_jedec_to_ascii
.BI "(int incr "  ","
.BI "char hdw[] "  ");"
.SH ARGUMENTS
.IP "incr" 12
integer to convert.
.IP "hdw" 12
ascii string holding converted integer plus a string terminator.
.SH "DESCRIPTION"
JEDEC Joint Electron Device Engineering Council.
Convert a 32 bit integer composed of 8 nibbles into an 8 byte ascii
character string. The string is then terminated with a NULL in byte 9.
Hex 0-9 becomes ascii '0' to '9'.
Hex a-f becomes ascii '=' to 'B' capital B.
.SH "NOTES"
Coded for 32 bit integers only.
