.TH "lpfc_soft_wwpn_show" 9 "lpfc_soft_wwpn_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_soft_wwpn_show \- Return the cfg soft ww port name of the adapter
.SH SYNOPSIS
.B "ssize_t" lpfc_soft_wwpn_show
.BI "(struct device *dev "  ","
.BI "struct device_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "dev" 12
class device that is converted into a Scsi_host.
.IP "attr" 12
device attribute, not used.
.IP "buf" 12
on return contains the wwpn in hexadecimal.
.SH "RETURN"
size of formatted string.
