.TH "lpfc_sriov_hw_max_virtfn_show" 9 "lpfc_sriov_hw_max_virtfn_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sriov_hw_max_virtfn_show \- Return maximum number of virtual functions
.SH SYNOPSIS
.B "ssize_t" lpfc_sriov_hw_max_virtfn_show
.BI "(struct device *dev "  ","
.BI "struct device_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "dev" 12
class converted to a Scsi_host structure.
.IP "attr" 12
device attribute, not used.
.IP "buf" 12
on return contains the formatted support level.
.SH "DESCRIPTION"
Returns the maximum number of virtual functions a physical function can
support, 0 will be returned if called on virtual function.
.SH "RETURN"
size of formatted string.
