.TH "lpfc_sli4_get_ctl_attr" 9 "lpfc_sli4_get_ctl_attr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_get_ctl_attr \- Retrieve SLI4 device controller attributes
.SH SYNOPSIS
.B "int" lpfc_sli4_get_ctl_attr
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine retrieves SLI4 device physical port name this PCI function
is attached to.

Return codes
0 - successful
otherwise - failed to retrieve controller attributes
