.TH "lpfc_sli_enable_msix" 9 "lpfc_sli_enable_msix" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli_enable_msix \- Enable MSI-X interrupt mode on SLI-3 device
.SH SYNOPSIS
.B "int" lpfc_sli_enable_msix
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine is invoked to enable the MSI-X interrupt vectors to device
with SLI-3 interface specs.

Return codes
0 - successful
other values - error
