.TH "lpfc_copy_fcf_record" 9 "lpfc_copy_fcf_record" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_copy_fcf_record \- Copy fcf information to lpfc_hba.
.SH SYNOPSIS
.B "void" lpfc_copy_fcf_record
.BI "(struct lpfc_fcf_rec *fcf_rec "  ","
.BI "struct fcf_record *new_fcf_record "  ");"
.SH ARGUMENTS
.IP "fcf_rec" 12
pointer to driver fcf record.
.IP "new_fcf_record" 12
pointer to fcf record.
.SH "DESCRIPTION"
This routine copies the FCF information from the FCF
record to lpfc_hba data structure.
