.TH "lpfc_scsi_prep_cmnd" 9 "lpfc_scsi_prep_cmnd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_scsi_prep_cmnd \- Wrapper func for convert scsi cmnd to FCP info unit
.SH SYNOPSIS
.B "int" lpfc_scsi_prep_cmnd
.BI "(struct lpfc_vport *vport "  ","
.BI "struct lpfc_io_buf *lpfc_cmd "  ","
.BI "struct lpfc_nodelist *pnode "  ");"
.SH ARGUMENTS
.IP "vport" 12
The virtual port for which this call is being executed.
.IP "lpfc_cmd" 12
The scsi command which needs to send.
.IP "pnode" 12
Pointer to lpfc_nodelist.
.SH "DESCRIPTION"
This routine initializes fcp_cmnd and iocb data structure from scsi command
to transfer for device with SLI3 interface spec.
