.TH "lpfc_npiv_info_show" 9 "lpfc_npiv_info_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_npiv_info_show \- Return text about NPIV support for the adapter
.SH SYNOPSIS
.B "ssize_t" lpfc_npiv_info_show
.BI "(struct device *dev "  ","
.BI "struct device_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "dev" 12
class device that is converted into a Scsi_host.
.IP "attr" 12
device attribute, not used.
.IP "buf" 12
text that must be interpreted to determine if npiv is supported.
.SH "DESCRIPTION"
Buffer will contain text indicating npiv is not suppoerted on the port,
the port is an NPIV physical port, or it is an npiv virtual port with
the id of the vport.
.SH "RETURN"
size of formatted string.
