.TH "lpfc_sli4_sp_handle_async_event" 9 "lpfc_sli4_sp_handle_async_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_sp_handle_async_event \- Handle an asynchronous event
.SH SYNOPSIS
.B "bool" lpfc_sli4_sp_handle_async_event
.BI "(struct lpfc_hba *phba "  ","
.BI "struct lpfc_mcqe *mcqe "  ");"
.SH ARGUMENTS
.IP "phba" 12
Pointer to HBA context object.
.IP "mcqe" 12
Pointer to mailbox completion queue entry.
.SH "DESCRIPTION"
This routine process a mailbox completion queue entry with asynchronous
event.
.SH "RETURN"
true if work posted to worker thread, otherwise false.
