.TH "lpfc_sli4_read_fcf_rec" 9 "lpfc_sli4_read_fcf_rec" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_read_fcf_rec \- Read hba fcf record for update eligible fcf bmask.
.SH SYNOPSIS
.B "int" lpfc_sli4_read_fcf_rec
.BI "(struct lpfc_hba *phba "  ","
.BI "uint16_t fcf_index "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.IP "fcf_index" 12
FCF table entry offset.
.SH "DESCRIPTION"
This routine is invoked to read an FCF record indicated by \fIfcf_index\fP to
determine whether it's eligible for FLOGI roundrobin failover list.

Return 0 if the mailbox command is submitted successfully, none 0
otherwise.
