.TH "lpfc_soft_wwn_enable_store" 9 "lpfc_soft_wwn_enable_store" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_soft_wwn_enable_store \- Allows setting of the wwn if the key is valid
.SH SYNOPSIS
.B "ssize_t" lpfc_soft_wwn_enable_store
.BI "(struct device *dev "  ","
.BI "struct device_attribute *attr "  ","
.BI "const char *buf "  ","
.BI "size_t count "  ");"
.SH ARGUMENTS
.IP "dev" 12
class device that is converted into a Scsi_host.
.IP "attr" 12
device attribute, not used.
.IP "buf" 12
containing the string lpfc_soft_wwn_key.
.IP "count" 12
must be size of lpfc_soft_wwn_key.
.SH "RETURN"
-EINVAL if the buffer does not contain lpfc_soft_wwn_key
length of buf indicates success
