.TH "lpfc_els_rcv_fpin_li" 9 "lpfc_els_rcv_fpin_li" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_els_rcv_fpin_li \- Process an FPIN Link Integrity Event.
.SH SYNOPSIS
.B "void" lpfc_els_rcv_fpin_li
.BI "(struct lpfc_vport *vport "  ","
.BI "struct fc_tlv_desc *tlv "  ");"
.SH ARGUMENTS
.IP "vport" 12
Pointer to vport object.
.IP "tlv" 12
Pointer to the Link Integrity Notification Descriptor.
.SH "DESCRIPTION"
This function processes a link integrity FPIN event by
logging a message
