.TH "lpfc_offline" 9 "lpfc_offline" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_offline \- Bring a HBA offline
.SH SYNOPSIS
.B "void" lpfc_offline
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine actually brings a HBA offline. It stops all the timers
associated with the HBA, brings down the SLI layer, and eventually
marks the HBA as in offline state for the upper layer protocol.
