.TH "lpfc_eq_destroy" 9 "lpfc_eq_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_eq_destroy \- Destroy an event Queue on the HBA
.SH SYNOPSIS
.B "int" lpfc_eq_destroy
.BI "(struct lpfc_hba *phba "  ","
.BI "struct lpfc_queue *eq "  ");"
.SH ARGUMENTS
.IP "phba" 12
HBA structure that indicates port to destroy a queue on.
.IP "eq" 12
The queue structure associated with the queue to destroy.
.SH "DESCRIPTION"
This function destroys a queue, as detailed in \fIeq\fP by sending an mailbox
command, specific to the type of queue, to the HBA.

The \fIeq\fP struct is used to get the queue ID of the queue to destroy.

On success this function will return a zero. If the queue destroy mailbox
command fails this function will return -ENXIO.
