.TH "lpfc_info" 9 "lpfc_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_info \- Info entry point of scsi_host_template data structure
.SH SYNOPSIS
.B "const char *" lpfc_info
.BI "(struct Scsi_Host *host "  ");"
.SH ARGUMENTS
.IP "host" 12
The scsi host for which this call is being executed.
.SH "DESCRIPTION"
This routine provides module information about hba.

Reutrn code:
Pointer to char - Success.
