.TH "lpfc_alloc_bucket" 9 "lpfc_alloc_bucket" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_alloc_bucket \- Allocate data buffer required for statistical data
.SH SYNOPSIS
.B "void" lpfc_alloc_bucket
.BI "(struct lpfc_vport *vport "  ");"
.SH ARGUMENTS
.IP "vport" 12
Pointer to vport object.
.SH "DESCRIPTION"
This function allocates data buffer required for all the FC
nodes of the vport to collect statistical data.
