.TH "lpfc_sli4_parse_latt_fault" 9 "lpfc_sli4_parse_latt_fault" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_parse_latt_fault \- Parse sli4 link-attention link fault code
.SH SYNOPSIS
.B "void" lpfc_sli4_parse_latt_fault
.BI "(struct lpfc_hba *phba "  ","
.BI "struct lpfc_acqe_link *acqe_link "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.IP "acqe_link" 12
pointer to the async link completion queue entry.
.SH "DESCRIPTION"
This routine is to parse the SLI4 link-attention link fault code.
