.TH "lpfc_sli4_cq_get" 9 "lpfc_sli4_cq_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_sli4_cq_get \- Gets the next valid CQE from a CQ
.SH SYNOPSIS
.B "struct lpfc_cqe *" lpfc_sli4_cq_get
.BI "(struct lpfc_queue *q "  ");"
.SH ARGUMENTS
.IP "q" 12
The Completion Queue to get the first valid CQE from
.SH "DESCRIPTION"
This routine will get the first valid Completion Queue Entry from \fIq\fP, update
the queue's internal hba index, and return the CQE. If no valid CQEs are in
the Queue (no more work to do), or the Queue is full of CQEs that have been
processed, but not popped back to the HBA then this routine will return NULL.
