.TH "lpfc_setup_cq_lookup" 9 "lpfc_setup_cq_lookup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_setup_cq_lookup \- Setup the CQ lookup table
.SH SYNOPSIS
.B "void" lpfc_setup_cq_lookup
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine will populate the cq_lookup table by all
available CQ queue_id's.
