.TH "lpfc_post_rcv_buf" 9 "lpfc_post_rcv_buf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpfc_post_rcv_buf \- Post the initial receive IOCB buffers to ELS ring
.SH SYNOPSIS
.B "int" lpfc_post_rcv_buf
.BI "(struct lpfc_hba *phba "  ");"
.SH ARGUMENTS
.IP "phba" 12
pointer to lpfc hba data structure.
.SH "DESCRIPTION"
This routine posts initial receive IOCB buffers to the ELS ring. The
current number of initial IOCB buffers specified by LPFC_BUF_RING0 is
set to 64 IOCBs. SLI3 only.

Return codes
0 - success (currently always success)
