.TH "lpt_gc" 9 "lpt_gc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
lpt_gc \- LPT garbage collection.
.SH SYNOPSIS
.B "int" lpt_gc
.BI "(struct ubifs_info *c "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.SH "DESCRIPTION"
Select a LPT LEB for LPT garbage collection and call '\fBlpt_gc_lnum\fP'.
Returns 0 on success and a negative error code on failure.
