.TH "ltq_mm_save_regs" 9 "ltq_mm_save_regs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ltq_mm_save_regs \- Set initial values of GPIO pins
.SH SYNOPSIS
.B "void" ltq_mm_save_regs
.BI "(struct of_mm_gpio_chip *mm_gc "  ");"
.SH ARGUMENTS
.IP "mm_gc" 12
pointer to memory mapped GPIO chip structure
