.TH "mac_vmode_to_var" 9 "mac_vmode_to_var" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mac_vmode_to_var \- converts vmode/cmode pair to var structure
.SH SYNOPSIS
.B "int" mac_vmode_to_var
.BI "(int vmode "  ","
.BI "int cmode "  ","
.BI "struct fb_var_screeninfo *var "  ");"
.SH ARGUMENTS
.IP "vmode" 12
MacOS video mode
.IP "cmode" 12
MacOS color mode
.IP "var" 12
frame buffer video mode structure

Converts a MacOS vmode/cmode pair to a frame buffer video
mode structure.

Returns negative errno on error, or zero for success.
