.TH "macio_pci_add_devices" 9 "macio_pci_add_devices" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
macio_pci_add_devices \- Adds sub-devices of mac-io to the device tree
.SH SYNOPSIS
.B "void" macio_pci_add_devices
.BI "(struct macio_chip *chip "  ");"
.SH ARGUMENTS
.IP "chip" 12
pointer to the macio_chip holding the devices
.SH "DESCRIPTION"
This function will do the job of extracting devices from the
Open Firmware device tree, build macio_dev structures and add
them to the Linux device tree.

For now, childs of media-bay are added now as well. This will
change rsn though.
