.TH "macio_release_dev" 9 "macio_release_dev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
macio_release_dev \- free a macio device structure when all users of it are finished.
.SH SYNOPSIS
.B "void" macio_release_dev
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device that's been disconnected
.SH "DESCRIPTION"
Will be called only by the device core when all users of this macio device
are done. This currently means never as we don't hot remove any macio
device yet, though that will happen with mediabay based devices in a later
implementation.
