.TH "map_sg_data" 9 "map_sg_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
map_sg_data \- - Maps dma for a scatterlist and initializes descriptor fields
.SH SYNOPSIS
.B "int" map_sg_data
.BI "(struct scsi_cmnd *cmd "  ","
.BI "struct srp_event_struct *evt_struct "  ","
.BI "struct srp_cmd *srp_cmd "  ","
.BI "struct device *dev "  ");"
.SH ARGUMENTS
.IP "cmd" 12
struct scsi_cmnd with the scatterlist
.IP "evt_struct" 12
-- undescribed --
.IP "srp_cmd" 12
srp_cmd that contains the memory descriptor
.IP "dev" 12
device for which to map dma memory
.SH "DESCRIPTION"
Called by \fBmap_data_for_srp_cmd\fP when building srp cmd from scsi cmd.
Returns 1 on success.
