.TH "map_device_va" 9 "map_device_va" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
map_device_va \- map the given memory.
.SH SYNOPSIS
.B "int" map_device_va
.BI "(struct hl_ctx *ctx "  ","
.BI "struct hl_mem_in *args "  ","
.BI "u64 *device_addr "  ");"
.SH ARGUMENTS
.IP "ctx" 12
pointer to the context structure.
.IP "args" 12
host parameters with handle/host virtual address.
.IP "device_addr" 12
pointer to result device virtual address.
.SH "DESCRIPTION"
This function does the following:
- If given a physical device memory handle, map to a device virtual block
and return the start address of this block.
- If given a host virtual address and size, find the related physical pages,
map a device virtual block to this pages and return the start address of
this block.
