.TH "maple_driver_unregister" 9 "maple_driver_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
maple_driver_unregister \- unregister a maple driver.
.SH SYNOPSIS
.B "void" maple_driver_unregister
.BI "(struct maple_driver *drv "  ");"
.SH ARGUMENTS
.IP "drv" 12
maple driver to unregister.
.SH "DESCRIPTION"
Cleans up after \fBmaple_driver_register\fP. To be invoked in the exit
path of any module drivers.
