.TH "marvell_pre_reset" 9 "marvell_pre_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
marvell_pre_reset \- probe begin
.SH SYNOPSIS
.B "int" marvell_pre_reset
.BI "(struct ata_link *link "  ","
.BI "unsigned long deadline "  ");"
.SH ARGUMENTS
.IP "link" 12
link
.IP "deadline" 12
deadline jiffies for the operation

Perform the PATA port setup we need.
