.TH "match_strlcpy" 9 "match_strlcpy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
match_strlcpy \- Copy the characters from a substring_t to a sized buffer
.SH SYNOPSIS
.B "size_t" match_strlcpy
.BI "(char *dest "  ","
.BI "const substring_t *src "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "dest" 12
where to copy to
.IP "src" 12
\fIsubstring_t\fP to copy
.IP "size" 12
size of destination buffer
.SH "DESCRIPTION"
Copy the characters in \fIsubstring_t\fP \fIsrc\fP to the
c-style string \fIdest\fP.  Copy no more than \fIsize\fP - 1 characters, plus
the terminating NUL.  Return length of \fIsrc\fP.
