.TH "mcb_device_register" 9 "mcb_device_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mcb_device_register \- Register a mcb_device
.SH SYNOPSIS
.B "int" mcb_device_register
.BI "(struct mcb_bus *bus "  ","
.BI "struct mcb_device *dev "  ");"
.SH ARGUMENTS
.IP "bus" 12
The \fImcb_bus\fP of the device
.IP "dev" 12
The \fImcb_device\fP
.SH "DESCRIPTION"
Register a specific \fImcb_device\fP at a \fImcb_bus\fP and the system itself.
