.TH "mcb_get_resource" 9 "mcb_get_resource" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mcb_get_resource \- get a resource for a mcb device
.SH SYNOPSIS
.B "struct resource *" mcb_get_resource
.BI "(struct mcb_device *dev "  ","
.BI "unsigned int type "  ");"
.SH ARGUMENTS
.IP "dev" 12
the mcb device
.IP "type" 12
the type of resource
