.TH "mcb_release_bus" 9 "mcb_release_bus" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mcb_release_bus \- Free a @mcb_bus
.SH SYNOPSIS
.B "void" mcb_release_bus
.BI "(struct mcb_bus *bus "  ");"
.SH ARGUMENTS
.IP "bus" 12
The \fImcb_bus\fP to release
.SH "DESCRIPTION"
Release an allocated \fImcb_bus\fP from the system.
