.TH "mdio_bus_match" 9 "mdio_bus_match" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mdio_bus_match \- determine if given MDIO driver supports the given MDIO device
.SH SYNOPSIS
.B "int" mdio_bus_match
.BI "(struct device *dev "  ","
.BI "struct device_driver *drv "  ");"
.SH ARGUMENTS
.IP "dev" 12
target MDIO device
.IP "drv" 12
given MDIO driver
.SH "DESCRIPTION"
Given a MDIO device, and a MDIO driver, return 1 if
the driver supports the device.  Otherwise, return 0. This may
require calling the devices own match function, since different classes
of MDIO devices have different match criteria.
