.TH "mdio_mii_ioctl" 9 "mdio_mii_ioctl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mdio_mii_ioctl \- MII ioctl interface for MDIO (clause 22 or 45) PHYs
.SH SYNOPSIS
.B "int" mdio_mii_ioctl
.BI "(const struct mdio_if_info *mdio "  ","
.BI "struct mii_ioctl_data *mii_data "  ","
.BI "int cmd "  ");"
.SH ARGUMENTS
.IP "mdio" 12
MDIO interface
.IP "mii_data" 12
MII ioctl data structure
.IP "cmd" 12
MII ioctl command
.SH "DESCRIPTION"
Returns 0 on success, negative on error.
