.TH "mdio_read" 9 "mdio_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mdio_read \- read PHY register
.SH SYNOPSIS
.B "int" mdio_read
.BI "(struct net_device *dev "  ","
.BI "int phy_id "  ","
.BI "int reg_num "  ");"
.SH ARGUMENTS
.IP "dev" 12
Network device.
.IP "phy_id" 12
The PHY id.
.IP "reg_num" 12
The register number.
.SH "DESCRIPTION"
This function returns the PHY register value.

Return the register value.
