.TH "mdiobus_release" 9 "mdiobus_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mdiobus_release \- mii_bus device release callback
.SH SYNOPSIS
.B "void" mdiobus_release
.BI "(struct device *d "  ");"
.SH ARGUMENTS
.IP "d" 12
the target struct device that contains the mii_bus
.SH "DESCRIPTION"
called when the last reference to an mii_bus is
dropped, to free the underlying memory.
