.TH "media_device_init" 9 "media_device_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
media_device_init \- initialize a media device
.SH SYNOPSIS
.B "void" media_device_init
.BI "(struct media_device *mdev "  ");"
.SH ARGUMENTS
.IP "mdev" 12
The media device
.SH "DESCRIPTION"
The caller is responsible for initializing the media device before
registration. The following fields must be set:

- dev must point to the parent device
- model must be filled with the device model name
