.TH "megaraid_alloc_cmd_packets" 9 "megaraid_alloc_cmd_packets" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_alloc_cmd_packets \- allocate shared mailbox
.SH SYNOPSIS
.B "int" megaraid_alloc_cmd_packets
.BI "(adapter_t *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
soft state of the raid controller
.SH "DESCRIPTION"
Allocate and align the shared mailbox. This mailbox is used to issue
all the commands. For IO based controllers, the mailbox is also registered
with the FW. Allocate memory for all commands as well.
This is our big allocator.
