.TH "megaraid_mbox_support_random_del" 9 "megaraid_mbox_support_random_del" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_mbox_support_random_del \- Do we support random deletion
.SH SYNOPSIS
.B "int" megaraid_mbox_support_random_del
.BI "(adapter_t *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
soft state for the controller
.SH "DESCRIPTION"
Determine if the firmware supports random deletion.
.SH "RETURN"
1 is operation supported, 0 otherwise
