.TH "megasas_generic_reset" 9 "megasas_generic_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megasas_generic_reset \- Generic reset routine
.SH SYNOPSIS
.B "int" megasas_generic_reset
.BI "(struct scsi_cmnd *scmd "  ");"
.SH ARGUMENTS
.IP "scmd" 12
Mid-layer SCSI command
.SH "DESCRIPTION"
This routine implements a generic reset handler for device, bus and host
reset requests. Device, bus and host specific reset handlers can use this
function after they do their specific tasks.
