.TH "megaraid_free_cmd_packets" 9 "megaraid_free_cmd_packets" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_free_cmd_packets \- free memory
.SH SYNOPSIS
.B "void" megaraid_free_cmd_packets
.BI "(adapter_t *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
soft state of the raid controller
.SH "DESCRIPTION"
Release memory resources allocated for commands.
