.TH "megaraid_cmm_unregister" 9 "megaraid_cmm_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megaraid_cmm_unregister \- un-register with the management module
.SH SYNOPSIS
.B "int" megaraid_cmm_unregister
.BI "(adapter_t *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
HBA soft state
.SH "DESCRIPTION"
Un-register with the management module.
FIXME: mgmt module must return failure for unregister if it has pending
commands in LLD.
