.TH "megasas_build_ldio_fusion" 9 "megasas_build_ldio_fusion" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
megasas_build_ldio_fusion \- Prepares IOs to devices
.SH SYNOPSIS
.B "void" megasas_build_ldio_fusion
.BI "(struct megasas_instance *instance "  ","
.BI "struct scsi_cmnd *scp "  ","
.BI "struct megasas_cmd_fusion *cmd "  ");"
.SH ARGUMENTS
.IP "instance" 12
Adapter soft state
.IP "scp" 12
SCSI command
.IP "cmd" 12
Command to be prepared
.SH "DESCRIPTION"
Prepares the io_request and chain elements (sg_frame) for IO
The IO can be for PD (Fast Path) or LD
