.TH "mei_txe_sec_reg_read_silent" 9 "mei_txe_sec_reg_read_silent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_txe_sec_reg_read_silent \- Reads 32bit data from the SeC BAR
.SH SYNOPSIS
.B "u32" mei_txe_sec_reg_read_silent
.BI "(struct mei_txe_hw *hw "  ","
.BI "unsigned long offset "  ");"
.SH ARGUMENTS
.IP "hw" 12
the txe hardware structure
.IP "offset" 12
register offset
.SH "DESCRIPTION"
Doesn't check for aliveness while Reads 32bit data from the SeC BAR
.SH "RETURN"
register value
