.TH "mei_io_tx_list_free_cl" 9 "mei_io_tx_list_free_cl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_io_tx_list_free_cl \- removes cb belonging to the cl and free them
.SH SYNOPSIS
.B "void" mei_io_tx_list_free_cl
.BI "(struct list_head *head "  ","
.BI "const struct mei_cl *cl "  ","
.BI "const struct file *fp "  ");"
.SH ARGUMENTS
.IP "head" 12
An instance of our list structure
.IP "cl" 12
host client
.IP "fp" 12
file pointer (matching cb file object), may be NULL
