.TH "mei_cl_bus_vtag" 9 "mei_cl_bus_vtag" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_cl_bus_vtag \- get bus vtag entry wrapper The tag for bus client is always first.
.SH SYNOPSIS
.B "struct mei_cl_vtag *" mei_cl_bus_vtag
.BI "(struct mei_cl *cl "  ");"
.SH ARGUMENTS
.IP "cl" 12
host client
.SH "RETURN"
bus vtag or NULL
