.TH "mei_txe_br_reg_read" 9 "mei_txe_br_reg_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_txe_br_reg_read \- Reads 32bit data from the Bridge BAR
.SH SYNOPSIS
.B "u32" mei_txe_br_reg_read
.BI "(struct mei_txe_hw *hw "  ","
.BI "unsigned long offset "  ");"
.SH ARGUMENTS
.IP "hw" 12
the txe hardware structure
.IP "offset" 12
offset from which to read the data
.SH "RETURN"
the byte read.
