.TH "mei_cldev_unregister_callbacks" 9 "mei_cldev_unregister_callbacks" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_cldev_unregister_callbacks \- internal wrapper for unregistering callbacks.
.SH SYNOPSIS
.B "void" mei_cldev_unregister_callbacks
.BI "(struct mei_cl_device *cldev "  ");"
.SH ARGUMENTS
.IP "cldev" 12
client device
