.TH "mei_cl_disconnect" 9 "mei_cl_disconnect" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_cl_disconnect \- disconnect host client from the me one
.SH SYNOPSIS
.B "int" mei_cl_disconnect
.BI "(struct mei_cl *cl "  ");"
.SH ARGUMENTS
.IP "cl" 12
host client
.SH "DESCRIPTION"
Locking: called under "dev->device_lock" lock
.SH "RETURN"
0 on success, <0 on failure.
