.TH "mei_txe_aliveness_poll" 9 "mei_txe_aliveness_poll" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mei_txe_aliveness_poll \- waits for aliveness to settle
.SH SYNOPSIS
.B "int" mei_txe_aliveness_poll
.BI "(struct mei_device *dev "  ","
.BI "u32 expected "  ");"
.SH ARGUMENTS
.IP "dev" 12
the device structure
.IP "expected" 12
expected aliveness value
.SH "DESCRIPTION"
Polls for HICR_HOST_ALIVENESS_RESP.ALIVENESS_RESP to be set
.SH "RETURN"
0 if the expected value was received, -ETIME otherwise
