.TH "memblock_set_node" 9 "memblock_set_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
memblock_set_node \- set node ID on memblock regions
.SH SYNOPSIS
.B "int __init_memblock" memblock_set_node
.BI "(phys_addr_t base "  ","
.BI "phys_addr_t size "  ","
.BI "struct memblock_type *type "  ","
.BI "int nid "  ");"
.SH ARGUMENTS
.IP "base" 12
base of area to set node ID for
.IP "size" 12
size of area to set node ID for
.IP "type" 12
memblock type to set node ID for
.IP "nid" 12
node ID to set
.SH "DESCRIPTION"
Set the nid of memblock \fItype\fP regions in [\fIbase\fP, \fIbase\fP + \fIsize\fP) to \fInid\fP.
Regions which cross the area boundaries are split as necessary.
.SH "RETURN"
0 on success, -errno on failure.
