.TH "men_z135_enable_ms" 9 "men_z135_enable_ms" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
men_z135_enable_ms \- Enable Modem Status
.SH SYNOPSIS
.B "void" men_z135_enable_ms
.BI "(struct uart_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
the port
.SH "DESCRIPTION"
Enable Modem Status IRQ.
