.TH "men_z135_get_mctrl" 9 "men_z135_get_mctrl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
men_z135_get_mctrl \- Get modem control lines
.SH SYNOPSIS
.B "unsigned int" men_z135_get_mctrl
.BI "(struct uart_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
The UART port
.SH "DESCRIPTION"
Retruns the current state of modem control inputs.
