.TH "mesh_queue_preq" 9 "mesh_queue_preq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mesh_queue_preq \- queue a PREQ to a given destination
.SH SYNOPSIS
.B "void" mesh_queue_preq
.BI "(struct mesh_path *mpath "  ","
.BI "u8 flags "  ");"
.SH ARGUMENTS
.IP "mpath" 12
mesh path to discover
.IP "flags" 12
special attributes of the PREQ to be sent
.SH "DESCRIPTION"
Locking: the function must be called from within a rcu read lock block.
