.TH "mesh_path_flush_by_iface" 9 "mesh_path_flush_by_iface" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mesh_path_flush_by_iface \- Deletes all mesh paths associated with a given iface
.SH SYNOPSIS
.B "void" mesh_path_flush_by_iface
.BI "(struct ieee80211_sub_if_data *sdata "  ");"
.SH ARGUMENTS
.IP "sdata" 12
interface data to match
.SH "DESCRIPTION"

This function deletes both mesh paths as well as mesh portal paths.
