.TH "mesh_path_flush_pending" 9 "mesh_path_flush_pending" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mesh_path_flush_pending \- free the pending queue of a mesh path
.SH SYNOPSIS
.B "void" mesh_path_flush_pending
.BI "(struct mesh_path *mpath "  ");"
.SH ARGUMENTS
.IP "mpath" 12
mesh path whose queue has to be freed
.SH "DESCRIPTION"
Locking: the function must me called within a rcu_read_lock region
