.TH "meson8_pmx_disable_other_groups" 9 "meson8_pmx_disable_other_groups" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
meson8_pmx_disable_other_groups \- disable other groups using a given pin
.SH SYNOPSIS
.B "void" meson8_pmx_disable_other_groups
.BI "(struct meson_pinctrl *pc "  ","
.BI "unsigned int pin "  ","
.BI "int sel_group "  ");"
.SH ARGUMENTS
.IP "pc" 12
meson pin controller device
.IP "pin" 12
number of the pin
.IP "sel_group" 12
index of the selected group, or -1 if none
.SH "DESCRIPTION"
The function disables all pinmux groups using a pin except the
selected one. If \fIsel_group\fP is -1 all groups are disabled, leaving
the pin in GPIO mode.
