.TH "message_show" 9 "message_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
message_show \- read message via sysfs
.SH SYNOPSIS
.B "ssize_t" message_show
.BI "(struct device *dev "  ","
.BI "struct device_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "dev" 12
the LCD device
.IP "attr" 12
the LCD message attribute
.IP "buf" 12
the buffer to read the message into
.SH "DESCRIPTION"
Read the current message being displayed or scrolled across the LCD display
into \fIbuf\fP, for reads from sysfs.
.SH "RETURN"
the number of characters written to \fIbuf\fP
