.TH "mipi_dbi_poweron_reset" 9 "mipi_dbi_poweron_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mipi_dbi_poweron_reset \- MIPI DBI poweron and reset
.SH SYNOPSIS
.B "int" mipi_dbi_poweron_reset
.BI "(struct mipi_dbi_dev *dbidev "  ");"
.SH ARGUMENTS
.IP "dbidev" 12
MIPI DBI device structure
.SH "DESCRIPTION"
This function enables the regulator if used and does a hardware and software
reset.
.SH "RETURN"
Zero on success, or a negative error code.
