.TH "mipi_dsi_device_register_full" 9 "mipi_dsi_device_register_full" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mipi_dsi_device_register_full \- create a MIPI DSI device
.SH SYNOPSIS
.B "struct mipi_dsi_device *" mipi_dsi_device_register_full
.BI "(struct mipi_dsi_host *host "  ","
.BI "const struct mipi_dsi_device_info *info "  ");"
.SH ARGUMENTS
.IP "host" 12
DSI host to which this device is connected
.IP "info" 12
pointer to template containing DSI device information
.SH "DESCRIPTION"
Create a MIPI DSI device by using the device information provided by
mipi_dsi_device_info template
.SH "RETURN"
A pointer to the newly created MIPI DSI device, or, a pointer encoded
with an error
