.TH "mipi_dsi_compression_mode" 9 "mipi_dsi_compression_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mipi_dsi_compression_mode \- enable/disable DSC on the peripheral
.SH SYNOPSIS
.B "ssize_t" mipi_dsi_compression_mode
.BI "(struct mipi_dsi_device *dsi "  ","
.BI "bool enable "  ");"
.SH ARGUMENTS
.IP "dsi" 12
DSI peripheral device
.IP "enable" 12
Whether to enable or disable the DSC
.SH "DESCRIPTION"
Enable or disable Display Stream Compression on the peripheral using the
default Picture Parameter Set and VESA DSC 1.1 algorithm.
.SH "RETURN"
0 on success or a negative error code on failure.
