.TH "mips_cdmm_bus_discover" 9 "mips_cdmm_bus_discover" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mips_cdmm_bus_discover \- Discover the devices on the CDMM bus.
.SH SYNOPSIS
.B "void" mips_cdmm_bus_discover
.BI "(struct mips_cdmm_bus *bus "  ");"
.SH ARGUMENTS
.IP "bus" 12
CDMM bus information, must already be set up.
