.TH "mite_ack_linkc" 9 "mite_ack_linkc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mite_ack_linkc \- Check and ack the LINKC interrupt,
.SH SYNOPSIS
.B "void" mite_ack_linkc
.BI "(struct mite_channel *mite_chan "  ","
.BI "struct comedi_subdevice *s "  ","
.BI "bool sync "  ");"
.SH ARGUMENTS
.IP "mite_chan" 12
MITE dma channel.
.IP "s" 12
COMEDI subdevice.
.IP "sync" 12
flag to force a \fBmite_sync_dma\fP.
.SH "DESCRIPTION"
This will also ack the DONE interrupt if active.
