.TH "mma9551_set_power_state" 9 "mma9551_set_power_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mma9551_set_power_state \- sets runtime PM state
.SH SYNOPSIS
.B "int" mma9551_set_power_state
.BI "(struct i2c_client *client "  ","
.BI "bool on "  ");"
.SH ARGUMENTS
.IP "client" 12
I2C client
.IP "on" 12
Use true to power on device, false to power off
.SH "DESCRIPTION"
Resume or suspend the device using Runtime PM.
The device will suspend after the autosuspend delay.
.SH "RETURN"
0 on success, negative value on failure.
