.TH "mmc_of_parse_voltage" 9 "mmc_of_parse_voltage" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mmc_of_parse_voltage \- return mask of supported voltages
.SH SYNOPSIS
.B "int" mmc_of_parse_voltage
.BI "(struct device_node *np "  ","
.BI "u32 *mask "  ");"
.SH ARGUMENTS
.IP "np" 12
The device node need to be parsed.
.IP "mask" 12
mask of voltages available for MMC/SD/SDIO
.SH "DESCRIPTION"
Parse the "voltage-ranges" DT property, returning zero if it is not
found, negative errno if the voltage-range specification is invalid,
or one if the voltage-range is specified and successfully parsed.
