.TH "mmc_cqe_post_req" 9 "mmc_cqe_post_req" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mmc_cqe_post_req \- CQE post process of a completed MMC request
.SH SYNOPSIS
.B "void" mmc_cqe_post_req
.BI "(struct mmc_host *host "  ","
.BI "struct mmc_request *mrq "  ");"
.SH ARGUMENTS
.IP "host" 12
MMC host
.IP "mrq" 12
MMC request to be processed
