.TH "mmc_rpmb_ioctl" 9 "mmc_rpmb_ioctl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mmc_rpmb_ioctl \- ioctl handler for the RPMB chardev
.SH SYNOPSIS
.B "long" mmc_rpmb_ioctl
.BI "(struct file *filp "  ","
.BI "unsigned int cmd "  ","
.BI "unsigned long arg "  ");"
.SH ARGUMENTS
.IP "filp" 12
the character device file
.IP "cmd" 12
the \fBioctl\fP command
.IP "arg" 12
the argument from userspace
.SH "DESCRIPTION"
This will essentially just redirect the \fBioctl\fPs coming in over to
the main block device spawning the RPMB character device.
