.TH "most_stop_channel" 9 "most_stop_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
most_stop_channel \- stops a running channel
.SH SYNOPSIS
.B "int" most_stop_channel
.BI "(struct most_interface *iface "  ","
.BI "int id "  ","
.BI "struct most_component *comp "  ");"
.SH ARGUMENTS
.IP "iface" 12
pointer to interface instance
.IP "id" 12
channel ID
.IP "comp" 12
driver component
