.TH "most_start_channel" 9 "most_start_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
most_start_channel \- prepares a channel for communication
.SH SYNOPSIS
.B "int" most_start_channel
.BI "(struct most_interface *iface "  ","
.BI "int id "  ","
.BI "struct most_component *comp "  ");"
.SH ARGUMENTS
.IP "iface" 12
pointer to interface instance
.IP "id" 12
channel ID
.IP "comp" 12
driver component
.SH "DESCRIPTION"
This prepares the channel for usage. Cross-checks whether the
channel's been properly configured.

Returns 0 on success or error code otherwise.
