.TH "move_nodes" 9 "move_nodes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
move_nodes \- move nodes.
.SH SYNOPSIS
.B "int" move_nodes
.BI "(struct ubifs_info *c "  ","
.BI "struct ubifs_scan_leb *sleb "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "sleb" 12
describes the LEB to move nodes from
.SH "DESCRIPTION"
This function moves valid nodes from data LEB described by \fIsleb\fP to the GC
journal head. This function returns zero in case of success, -EAGAIN if
commit is required, and other negative error codes in case of other
failures.
