.TH "mpc8610_hpcd_startup" 9 "mpc8610_hpcd_startup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpc8610_hpcd_startup \- program the board with various hardware parameters
.SH SYNOPSIS
.B "int" mpc8610_hpcd_startup
.BI "(struct snd_pcm_substream *substream "  ");"
.SH ARGUMENTS
.IP "substream" 12
-- undescribed --
.SH "DESCRIPTION"

This function takes board-specific information, like clock frequencies
and serial data formats, and passes that information to the codec and
transport drivers.
