.TH "mpt3sas_wait_for_ioc" 9 "mpt3sas_wait_for_ioc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt3sas_wait_for_ioc \- IOC's operational state is checked here.
.SH SYNOPSIS
.B "int" mpt3sas_wait_for_ioc
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "int timeout "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "timeout" 12
timeout in seconds
.SH "RETURN"
Waits up to timeout seconds for the IOC to
become operational. Returns 0 if IOC is present
and operational; otherwise returns -EFAULT.
