.TH "mpt3sas_free_enclosure_list" 9 "mpt3sas_free_enclosure_list" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt3sas_free_enclosure_list \- release memory
.SH SYNOPSIS
.B "void" mpt3sas_free_enclosure_list
.BI "(struct MPT3SAS_ADAPTER *ioc "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.SH "DESCRIPTION"
Free memory allocated during encloure add.
