.TH "mpt3sas_base_scsi_enclosure_processor" 9 "mpt3sas_base_scsi_enclosure_processor" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt3sas_base_scsi_enclosure_processor \- sending request to sep device
.SH SYNOPSIS
.B "int" mpt3sas_base_scsi_enclosure_processor
.BI "(struct MPT3SAS_ADAPTER *ioc "  ","
.BI "Mpi2SepReply_t *mpi_reply "  ","
.BI "Mpi2SepRequest_t *mpi_request "  ");"
.SH ARGUMENTS
.IP "ioc" 12
per adapter object
.IP "mpi_reply" 12
the reply payload from FW
.IP "mpi_request" 12
the request payload sent to FW
.SH "DESCRIPTION"
The SCSI Enclosure Processor request message causes the IOC to
communicate with SES devices to control LED status signals.
.SH "RETURN"
0 for success, non-zero for failure.
