.TH "mpt_alloc_fw_memory" 9 "mpt_alloc_fw_memory" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt_alloc_fw_memory \- allocate firmware memory
.SH SYNOPSIS
.B "int" mpt_alloc_fw_memory
.BI "(MPT_ADAPTER *ioc "  ","
.BI "int size "  ");"
.SH ARGUMENTS
.IP "ioc" 12
Pointer to MPT_ADAPTER structure
.IP "size" 12
total FW bytes

If memory has already been allocated, the same (cached) value
is returned.

Return 0 if successful, or non-zero for failure
