.TH "mpt_adapter_dispose" 9 "mpt_adapter_dispose" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mpt_adapter_dispose \- Free all resources associated with an MPT adapter
.SH SYNOPSIS
.B "void" mpt_adapter_dispose
.BI "(MPT_ADAPTER *ioc "  ");"
.SH ARGUMENTS
.IP "ioc" 12
Pointer to MPT adapter structure

This routine unregisters h/w resources and frees all alloc'd memory
associated with a MPT adapter structure.
