.TH "mptcp_token_new_request" 9 "mptcp_token_new_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mptcp_token_new_request \- create new key/idsn/token for subflow_request
.SH SYNOPSIS
.B "int" mptcp_token_new_request
.BI "(struct request_sock *req "  ");"
.SH ARGUMENTS
.IP "req" 12
the request socket
.SH "DESCRIPTION"
This function is called when a new mptcp connection is coming in.

It creates a unique token to identify the new mptcp connection,
a secret local key and the initial data sequence number (idsn).

Returns 0 on success.
