.TH "mptscsih_info_scsiio" 9 "mptscsih_info_scsiio" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mptscsih_info_scsiio \- debug print info on reply frame
.SH SYNOPSIS
.B "void" mptscsih_info_scsiio
.BI "(MPT_ADAPTER *ioc "  ","
.BI "struct scsi_cmnd *sc "  ","
.BI "SCSIIOReply_t * pScsiReply "  ");"
.SH ARGUMENTS
.IP "ioc" 12
Pointer to MPT_ADAPTER structure
.IP "sc" 12
original scsi cmnd pointer
.IP "pScsiReply" 12
Pointer to MPT reply frame

MPT_DEBUG_REPLY needs to be enabled to obtain this info

Refer to lsi/mpi.h.
