.TH "mptsas_send_expander_event" 9 "mptsas_send_expander_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mptsas_send_expander_event \- expanders events
.SH SYNOPSIS
.B "void" mptsas_send_expander_event
.BI "(struct fw_event_work *fw_event "  ");"
.SH ARGUMENTS
.IP "fw_event" 12
-- undescribed --
.SH "DESCRIPTION"
This function handles adding, removing, and refreshing
device handles within the expander objects.
