.TH "mraid_mm_teardown_dma_pools" 9 "mraid_mm_teardown_dma_pools" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mraid_mm_teardown_dma_pools \- Free all per adapter dma buffers
.SH SYNOPSIS
.B "void" mraid_mm_teardown_dma_pools
.BI "(mraid_mmadp_t *adp "  ");"
.SH ARGUMENTS
.IP "adp" 12
Adapter softstate
