.TH "mraid_mm_adapter_app_handle" 9 "mraid_mm_adapter_app_handle" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mraid_mm_adapter_app_handle \- return the application handle for this adapter
.SH SYNOPSIS
.B "uint32_t" mraid_mm_adapter_app_handle
.BI "(uint32_t unique_id "  ");"
.SH ARGUMENTS
.IP "unique_id" 12
adapter unique identifier
.SH "DESCRIPTION"
For the given driver data, locate the adapter in our global list and
return the corresponding handle, which is also used by applications to
uniquely identify an adapter.

Return adapter handle if found in the list.
Return 0 if adapter could not be located, should never happen though.
