.TH "mraid_mm_unregister_adp" 9 "mraid_mm_unregister_adp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mraid_mm_unregister_adp \- Unregister routine for low level drivers
.SH SYNOPSIS
.B "int" mraid_mm_unregister_adp
.BI "(uint32_t unique_id "  ");"
.SH ARGUMENTS
.IP "unique_id" 12
UID of the adpater
.SH "DESCRIPTION"
Assumes no outstanding ioctls to llds.
