.TH "mraid_mm_get_adapter" 9 "mraid_mm_get_adapter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mraid_mm_get_adapter \- Returns corresponding adapters for the mimd packet
.SH SYNOPSIS
.B "mraid_mmadp_t *" mraid_mm_get_adapter
.BI "(mimd_t __user *umimd "  ","
.BI "int *rval "  ");"
.SH ARGUMENTS
.IP "umimd" 12
User space mimd_t ioctl packet
.IP "rval" 12
returned success/error status
.SH "DESCRIPTION"
The function return value is a pointer to the located \fIadapter\fP.
