.TH "msc_buffer_contig_alloc" 9 "msc_buffer_contig_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
msc_buffer_contig_alloc \- allocate a contiguous buffer for SINGLE mode
.SH SYNOPSIS
.B "int" msc_buffer_contig_alloc
.BI "(struct msc *msc "  ","
.BI "unsigned long size "  ");"
.SH ARGUMENTS
.IP "msc" 12
MSC device
.IP "size" 12
allocation size in bytes
.SH "DESCRIPTION"
This modifies msc::base, which requires msc::buf_mutex to serialize, so the
caller is expected to hold it.
.SH "RETURN"
0 on success, -errno otherwise.
