.TH "msi_domain_set_affinity" 9 "msi_domain_set_affinity" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
msi_domain_set_affinity \- Generic affinity setter function for MSI domains
.SH SYNOPSIS
.B "int" msi_domain_set_affinity
.BI "(struct irq_data *irq_data "  ","
.BI "const struct cpumask *mask "  ","
.BI "bool force "  ");"
.SH ARGUMENTS
.IP "irq_data" 12
The irq data associated to the interrupt
.IP "mask" 12
The affinity mask to set
.IP "force" 12
Flag to enforce setting (disable online checks)
.SH "DESCRIPTION"
Intended to be used by MSI interrupt controllers which are
implemented with hierarchical domains.
