.TH "mutex_lock_io" 9 "mutex_lock_io" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mutex_lock_io \- Acquire the mutex and mark the process as waiting for I/O
.SH SYNOPSIS
.B "void" mutex_lock_io
.BI "(struct mutex *lock "  ");"
.SH ARGUMENTS
.IP "lock" 12
The mutex to be acquired.
.SH "DESCRIPTION"
Lock the mutex like \fBmutex_lock\fP.  While the task is waiting for this
mutex, it will be accounted as being in the IO wait state by the
scheduler.
.SH "CONTEXT"
Process context.
