.TH "mux_release_port" 9 "mux_release_port" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mux_release_port \- Release memory and IO regions.
.SH SYNOPSIS
.B "void" mux_release_port
.BI "(struct uart_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
Ptr to the uart_port.
.SH "DESCRIPTION"
Release any memory and IO region resources currently in use by
the port.
