.TH "mux_set_mctrl" 9 "mux_set_mctrl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mux_set_mctrl \- Set the current state of the modem control inputs.
.SH SYNOPSIS
.B "void" mux_set_mctrl
.BI "(struct uart_port *port "  ","
.BI "unsigned int mctrl "  ");"
.SH ARGUMENTS
.IP "port" 12
-- undescribed --
.IP "mctrl" 12
Modem control bits.
.SH "DESCRIPTION"
The Serial MUX does not support CTS, DCD or DSR so this function
is ignored.
