.TH "mv_init_host" 9 "mv_init_host" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mv_init_host \- Perform some early initialization of the host.
.SH SYNOPSIS
.B "int" mv_init_host
.BI "(struct ata_host *host "  ");"
.SH ARGUMENTS
.IP "host" 12
ATA host to initialize

If possible, do an early global reset of the host.  Then do
our port init and clear/unmask all/relevant host interrupts.

LOCKING:
Inherited from caller.
