.TH "mvumi_make_sgl" 9 "mvumi_make_sgl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mvumi_make_sgl \- Prepares SGL
.SH SYNOPSIS
.B "int" mvumi_make_sgl
.BI "(struct mvumi_hba *mhba "  ","
.BI "struct scsi_cmnd *scmd "  ","
.BI "void *sgl_p "  ","
.BI "unsigned char *sg_count "  ");"
.SH ARGUMENTS
.IP "mhba" 12
Adapter soft state
.IP "scmd" 12
SCSI command from the mid-layer
.IP "sgl_p" 12
SGL to be filled in
\fIsg_count\fP            return the number of SG elements
.IP "sg_count" 12
-- undescribed --
.SH "DESCRIPTION"
If successful, this function returns 0. otherwise, it returns -1.
