.TH "mx3fb_set_par" 9 "mx3fb_set_par" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
mx3fb_set_par \- set framebuffer parameters and change the operating mode.
.SH SYNOPSIS
.B "int" mx3fb_set_par
.BI "(struct fb_info *fbi "  ");"
.SH ARGUMENTS
.IP "fbi" 12
framebuffer information pointer.
.SH "RETURN"
0 on success or negative error code on failure.
