.TH "myrb_get_ldev_info" 9 "myrb_get_ldev_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
myrb_get_ldev_info \- retrieves the logical device table from the controller
.SH SYNOPSIS
.B "unsigned short" myrb_get_ldev_info
.BI "(struct myrb_hba *cb "  ");"
.SH ARGUMENTS
.IP "cb" 12
-- undescribed --
.SH "DESCRIPTION"

Executes a type 3 command and updates the logical device table.
.SH "RETURN"
command status
