.TH "n_hdlc_tty_write" 9 "n_hdlc_tty_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
n_hdlc_tty_write \- write a single frame of data to device
.SH SYNOPSIS
.B "ssize_t" n_hdlc_tty_write
.BI "(struct tty_struct *tty "  ","
.BI "struct file *file "  ","
.BI "const unsigned char *data "  ","
.BI "size_t count "  ");"
.SH ARGUMENTS
.IP "tty" 12
pointer to associated tty device instance data
.IP "file" 12
pointer to file object data
.IP "data" 12
pointer to transmit data (one frame)
.IP "count" 12
size of transmit frame in bytes
.SH "DESCRIPTION"
Returns the number of bytes written (or error code).
