.TH "n_tty_receive_parity_error" 9 "n_tty_receive_parity_error" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
n_tty_receive_parity_error \- error notifier
.SH SYNOPSIS
.B "void" n_tty_receive_parity_error
.BI "(struct tty_struct *tty "  ","
.BI "unsigned char c "  ");"
.SH ARGUMENTS
.IP "tty" 12
terminal device
.IP "c" 12
character

Process a parity error and queue the right data to indicate
the error case if necessary.

\fBn_tty_receive_buf\fP/producer path:
caller holds non-exclusive termios_rwsem
