.TH "nand_ecc_sw_hamming_calculate" 9 "nand_ecc_sw_hamming_calculate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_ecc_sw_hamming_calculate \- Calculate 3-byte ECC for 256/512-byte block
.SH SYNOPSIS
.B "int" nand_ecc_sw_hamming_calculate
.BI "(struct nand_device *nand "  ","
.BI "const unsigned char *buf "  ","
.BI "unsigned char *code "  ");"
.SH ARGUMENTS
.IP "nand" 12
NAND device
.IP "buf" 12
Input buffer with raw data
.IP "code" 12
Output buffer with ECC
