.TH "nand_extract_bits" 9 "nand_extract_bits" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_extract_bits \- Copy unaligned bits from one buffer to another one
.SH SYNOPSIS
.B "void" nand_extract_bits
.BI "(u8 *dst "  ","
.BI "unsigned int dst_off "  ","
.BI "const u8 *src "  ","
.BI "unsigned int src_off "  ","
.BI "unsigned int nbits "  ");"
.SH ARGUMENTS
.IP "dst" 12
destination buffer
.IP "dst_off" 12
bit offset at which the writing starts
.IP "src" 12
source buffer
.IP "src_off" 12
bit offset at which the reading starts
.IP "nbits" 12
number of bits to copy from \fIsrc\fP to \fIdst\fP
.SH "DESCRIPTION"
Copy bits from one memory region to another (overlap authorized).
