.TH "nanddev_ecc_engine_cleanup" 9 "nanddev_ecc_engine_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nanddev_ecc_engine_cleanup \- Cleanup ECC engine initializations
.SH SYNOPSIS
.B "void" nanddev_ecc_engine_cleanup
.BI "(struct nand_device *nand "  ");"
.SH ARGUMENTS
.IP "nand" 12
NAND device
