.TH "nand_shutdown" 9 "nand_shutdown" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_shutdown \- [MTD Interface] Finish the current NAND operation and prevent further operations
.SH SYNOPSIS
.B "void" nand_shutdown
.BI "(struct mtd_info *mtd "  ");"
.SH ARGUMENTS
.IP "mtd" 12
MTD device structure
