.TH "nand_wait_ready" 9 "nand_wait_ready" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_wait_ready \- [GENERIC] Wait for the ready pin after commands.
.SH SYNOPSIS
.B "void" nand_wait_ready
.BI "(struct nand_chip *chip "  ");"
.SH ARGUMENTS
.IP "chip" 12
NAND chip object
.SH "DESCRIPTION"
Wait for the ready pin after a command, and warn if a timeout occurs.
