.TH "nand_ecc_finish_io_req" 9 "nand_ecc_finish_io_req" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_ecc_finish_io_req \- Finish an I/O request
.SH SYNOPSIS
.B "int" nand_ecc_finish_io_req
.BI "(struct nand_device *nand "  ","
.BI "struct nand_page_io_req *req "  ");"
.SH ARGUMENTS
.IP "nand" 12
the NAND device
.IP "req" 12
the I/O request
