.TH "nanddev_bbt_cleanup" 9 "nanddev_bbt_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nanddev_bbt_cleanup \- Cleanup the BBT (Bad Block Table)
.SH SYNOPSIS
.B "void" nanddev_bbt_cleanup
.BI "(struct nand_device *nand "  ");"
.SH ARGUMENTS
.IP "nand" 12
NAND device
.SH "DESCRIPTION"
Undoes what has been done in \fBnanddev_bbt_init\fP
