.TH "nand_write_page_syndrome" 9 "nand_write_page_syndrome" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nand_write_page_syndrome \- [REPLACEABLE] hardware ECC syndrome based page write
.SH SYNOPSIS
.B "int" nand_write_page_syndrome
.BI "(struct nand_chip *chip "  ","
.BI "const uint8_t *buf "  ","
.BI "int oob_required "  ","
.BI "int page "  ");"
.SH ARGUMENTS
.IP "chip" 12
nand chip info structure
.IP "buf" 12
data buffer
.IP "oob_required" 12
must write chip->oob_poi to OOB
.IP "page" 12
page number to write
.SH "DESCRIPTION"
The hw generator calculates the error syndrome automatically. Therefore we
need a special oob layout and handling.
