.TH "nau8824_set_tdm_slot" 9 "nau8824_set_tdm_slot" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nau8824_set_tdm_slot \- configure DAI TDM.
.SH SYNOPSIS
.B "int" nau8824_set_tdm_slot
.BI "(struct snd_soc_dai *dai "  ","
.BI "unsigned int tx_mask "  ","
.BI "unsigned int rx_mask "  ","
.BI "int slots "  ","
.BI "int slot_width "  ");"
.SH ARGUMENTS
.IP "dai" 12
DAI
.IP "tx_mask" 12
Bitmask representing active TX slots. Ex.
0xf for normal 4 channel TDM.
0xf0 for shifted 4 channel TDM
.IP "rx_mask" 12
Bitmask [0:1] representing active DACR RX slots.
Bitmask [2:3] representing active DACL RX slots.
00=CH0,01=CH1,10=CH2,11=CH3. Ex.
0xf for DACL/R selecting TDM CH3.
0xf0 for DACL/R selecting shifted TDM CH3.
.IP "slots" 12
Number of slots in use.
.IP "slot_width" 12
Width in bits for each slot.
.SH "DESCRIPTION"
Configures a DAI for TDM operation. Only support 4 slots TDM.
