.TH "NCR5380_init" 9 "NCR5380_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
NCR5380_init \- initialise an NCR5380
.SH SYNOPSIS
.B "int" NCR5380_init
.BI "(struct Scsi_Host *instance "  ","
.BI "int flags "  ");"
.SH ARGUMENTS
.IP "instance" 12
adapter to configure
.IP "flags" 12
control flags
.SH "DESCRIPTION"
Initializes *instance and corresponding 5380 chip,
with flags OR'd into the initial flags value.

Returns 0 for success
.SH "NOTES"
I assume that the host, hostno, and id bits have been
set correctly. I don't care about the irq and other fields.
