.TH "ne_check_enclaves_created" 9 "ne_check_enclaves_created" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ne_check_enclaves_created \- Verify if at least one enclave has been created.
.SH SYNOPSIS
.B "bool" ne_check_enclaves_created
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "CONTEXT"
Process context.
.SH "RETURN"
* True if at least one enclave is created.
* False otherwise.
