.TH "netdev_upper_dev_link" 9 "netdev_upper_dev_link" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
netdev_upper_dev_link \- Add a link to the upper device
.SH SYNOPSIS
.B "int" netdev_upper_dev_link
.BI "(struct net_device *dev "  ","
.BI "struct net_device *upper_dev "  ","
.BI "struct netlink_ext_ack *extack "  ");"
.SH ARGUMENTS
.IP "dev" 12
device
.IP "upper_dev" 12
new upper device
.IP "extack" 12
netlink extended ack
.SH "DESCRIPTION"
Adds a link to device which is upper to this one. The caller must hold
the RTNL lock. On a failure a negative errno code is returned.
On success the reference counts are adjusted and the function
returns zero.
