.TH "netlbl_cfg_map_del" 9 "netlbl_cfg_map_del" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
netlbl_cfg_map_del \- Remove a NetLabel/LSM domain mapping
.SH SYNOPSIS
.B "int" netlbl_cfg_map_del
.BI "(const char *domain "  ","
.BI "u16 family "  ","
.BI "const void *addr "  ","
.BI "const void *mask "  ","
.BI "struct netlbl_audit *audit_info "  ");"
.SH ARGUMENTS
.IP "domain" 12
the domain mapping to remove
.IP "family" 12
address family
.IP "addr" 12
IP address
.IP "mask" 12
IP address mask
.IP "audit_info" 12
NetLabel audit information
.SH "DESCRIPTION"
Removes a NetLabel/LSM domain mapping.  A \fIdomain\fP value of NULL causes the
default domain mapping to be removed.  Returns zero on success, negative
values on failure.
