.TH "next_nnode" 9 "next_nnode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
next_nnode \- find the next nnode in memory.
.SH SYNOPSIS
.B "struct ubifs_nnode *" next_nnode
.BI "(struct ubifs_info *c "  ","
.BI "struct ubifs_nnode *nnode "  ","
.BI "int *hght "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "nnode" 12
nnode from which to start.
.IP "hght" 12
height of tree where nnode is, is passed and returned here
.SH "DESCRIPTION"
This function returns a pointer to the nnode found or NULL if no nnode is
found. This function is a helper to '\fBubifs_lpt_free\fP'.
