.TH "nfc_alloc_recv_skb" 9 "nfc_alloc_recv_skb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfc_alloc_recv_skb \- allocate a skb for data exchange responses
.SH SYNOPSIS
.B "struct sk_buff *" nfc_alloc_recv_skb
.BI "(unsigned int size "  ","
.BI "gfp_t gfp "  ");"
.SH ARGUMENTS
.IP "size" 12
size to allocate
.IP "gfp" 12
gfp flags
