.TH "nfp_cpp_area_release_free" 9 "nfp_cpp_area_release_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_cpp_area_release_free \- release CPP area and free it
.SH SYNOPSIS
.B "void" nfp_cpp_area_release_free
.BI "(struct nfp_cpp_area *area "  ");"
.SH ARGUMENTS
.IP "area" 12
CPP area handle
.SH "DESCRIPTION"
Releases CPP area and frees up memory resources held by the it.
