.TH "nfp_fw_load" 9 "nfp_fw_load" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_fw_load \- Load the firmware image
.SH SYNOPSIS
.B "int" nfp_fw_load
.BI "(struct pci_dev *pdev "  ","
.BI "struct nfp_pf *pf "  ","
.BI "struct nfp_nsp *nsp "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI Device structure
.IP "pf" 12
NFP PF Device structure
.IP "nsp" 12
NFP SP handle
.SH "RETURN"
-ERRNO, 0 for no firmware loaded, 1 for firmware loaded
