.TH "nfp_eth_read_ports" 9 "nfp_eth_read_ports" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_eth_read_ports \- retrieve port information
.SH SYNOPSIS
.B "struct nfp_eth_table *" nfp_eth_read_ports
.BI "(struct nfp_cpp *cpp "  ");"
.SH ARGUMENTS
.IP "cpp" 12
NFP CPP handle
.SH "DESCRIPTION"
Read the port information from the device.  Returned structure should
be freed with \fBkfree\fP once no longer needed.
.SH "RETURN"
populated ETH table or NULL on error.
