.TH "nfp_net_rx_give_one" 9 "nfp_net_rx_give_one" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_net_rx_give_one \- Put mapped skb on the software and hardware rings
.SH SYNOPSIS
.B "void" nfp_net_rx_give_one
.BI "(const struct nfp_net_dp *dp "  ","
.BI "struct nfp_net_rx_ring *rx_ring "  ","
.BI "void *frag "  ","
.BI "dma_addr_t dma_addr "  ");"
.SH ARGUMENTS
.IP "dp" 12
NFP Net data path struct
.IP "rx_ring" 12
RX ring structure
.IP "frag" 12
page fragment buffer
.IP "dma_addr" 12
DMA address of skb mapping
