.TH "nfp_cpp_area_write" 9 "nfp_cpp_area_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_cpp_area_write \- write data to CPP area
.SH SYNOPSIS
.B "int" nfp_cpp_area_write
.BI "(struct nfp_cpp_area *area "  ","
.BI "unsigned long offset "  ","
.BI "const void *kernel_vaddr "  ","
.BI "size_t length "  ");"
.SH ARGUMENTS
.IP "area" 12
CPP area handle
.IP "offset" 12
offset into CPP area
.IP "kernel_vaddr" 12
kernel address to read data from
.IP "length" 12
number of bytes to write
.SH "DESCRIPTION"
Write data to indicated CPP region.
.SH "NOTE"
\fIoffset\fP and \fIlength\fP must be 32-bit aligned values.
Area must have been locked down with an 'acquire'.
.SH "RETURN"
length of io, or -ERRNO
