.TH "nfp_net_irq_rxtx" 9 "nfp_net_irq_rxtx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfp_net_irq_rxtx \- Interrupt service routine for RX/TX rings.
.SH SYNOPSIS
.B "irqreturn_t" nfp_net_irq_rxtx
.BI "(int irq "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "irq" 12
Interrupt
.IP "data" 12
Opaque data structure
.SH "RETURN"
Indicate if the interrupt has been handled.
