.TH "nfs_expire_unused_delegation_types" 9 "nfs_expire_unused_delegation_types" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfs_expire_unused_delegation_types \- 
.SH SYNOPSIS
.B "void" nfs_expire_unused_delegation_types
.BI "(struct nfs_client *clp "  ","
.BI "fmode_t flags "  ");"
.SH ARGUMENTS
.IP "clp" 12
client to process
.IP "flags" 12
delegation types to expire
