.TH "nfs_async_iocounter_wait" 9 "nfs_async_iocounter_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfs_async_iocounter_wait \- wait on a rpc_waitqueue for I/O to complete
.SH SYNOPSIS
.B "bool" nfs_async_iocounter_wait
.BI "(struct rpc_task *task "  ","
.BI "struct nfs_lock_context *l_ctx "  ");"
.SH ARGUMENTS
.IP "task" 12
the rpc_task that should wait
.IP "l_ctx" 12
nfs_lock_context with io_counter to check
.SH "DESCRIPTION"
Returns true if there is outstanding I/O to wait on and the
task has been put to sleep.
