.TH "nfsacl_decode" 9 "nfsacl_decode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nfsacl_decode \- Decode an NFSv3 ACL
.SH SYNOPSIS
.B "int" nfsacl_decode
.BI "(struct xdr_buf *buf "  ","
.BI "unsigned int base "  ","
.BI "unsigned int *aclcnt "  ","
.BI "struct posix_acl **pacl "  ");"
.SH ARGUMENTS
.IP "buf" 12
xdr_buf containing XDR'd ACL data to decode
.IP "base" 12
byte offset in xdr_buf where XDR'd ACL begins
.IP "aclcnt" 12
count of ACEs in decoded posix_acl
.IP "pacl" 12
buffer in which to place decoded posix_acl
.SH "DESCRIPTION"
Returns the length of the decoded ACL in bytes, or a negative errno value.
