.TH "nft_pipapo_deactivate" 9 "nft_pipapo_deactivate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nft_pipapo_deactivate \- Call pipapo_deactivate() to make element inactive
.SH SYNOPSIS
.B "void *" nft_pipapo_deactivate
.BI "(const struct net *net "  ","
.BI "const struct nft_set *set "  ","
.BI "const struct nft_set_elem *elem "  ");"
.SH ARGUMENTS
.IP "net" 12
Network namespace
.IP "set" 12
nftables API set representation
.IP "elem" 12
nftables API element representation containing key data
.SH "RETURN"
deactivated element if found, NULL otherwise.
