.TH "nilfs_scan_dsync_log" 9 "nilfs_scan_dsync_log" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nilfs_scan_dsync_log \- get block information of a log written for data sync
.SH SYNOPSIS
.B "int" nilfs_scan_dsync_log
.BI "(struct the_nilfs *nilfs "  ","
.BI "sector_t start_blocknr "  ","
.BI "struct nilfs_segment_summary *sum "  ","
.BI "struct list_head *head "  ");"
.SH ARGUMENTS
.IP "nilfs" 12
nilfs object
.IP "start_blocknr" 12
start block number of the log
.IP "sum" 12
log summary information
.IP "head" 12
list head to add nilfs_recovery_block struct
