.TH "nilfs_cpfile_get_cpinfo" 9 "nilfs_cpfile_get_cpinfo" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nilfs_cpfile_get_cpinfo \- 
.SH SYNOPSIS
.B "ssize_t" nilfs_cpfile_get_cpinfo
.BI "(struct inode *cpfile "  ","
.BI "__u64 *cnop "  ","
.BI "int mode "  ","
.BI "void *buf "  ","
.BI "unsigned int cisz "  ","
.BI "size_t nci "  ");"
.SH ARGUMENTS
.IP "cpfile" 12
-- undescribed --
.IP "cnop" 12
-- undescribed --
.IP "mode" 12
-- undescribed --
.IP "buf" 12
-- undescribed --
.IP "cisz" 12
-- undescribed --
.IP "nci" 12
-- undescribed --
