.TH "ns87415_irq_clear" 9 "ns87415_irq_clear" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ns87415_irq_clear \- Clear interrupt
.SH SYNOPSIS
.B "void" ns87415_irq_clear
.BI "(struct ata_port *ap "  ");"
.SH ARGUMENTS
.IP "ap" 12
Channel to clear

Erratum: Due to a chip bug regisers 02 and 0A bit 1 and 2 (the
error bits) are reset by writing to register 00 or 08.
