.TH "ntfs_index_ctx_get" 9 "ntfs_index_ctx_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ntfs_index_ctx_get \- allocate and initialize a new index context
.SH SYNOPSIS
.B "ntfs_index_context *" ntfs_index_ctx_get
.BI "(ntfs_inode *idx_ni "  ");"
.SH ARGUMENTS
.IP "idx_ni" 12
ntfs index inode with which to initialize the context
.SH "DESCRIPTION"
Allocate a new index context, initialize it with \fIidx_ni\fP and return it.
Return NULL if allocation failed.

Locking:  Caller must hold i_mutex on the index inode.
