.TH "ntfs_is_logfile_clean" 9 "ntfs_is_logfile_clean" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ntfs_is_logfile_clean \- check in the journal if the volume is clean
.SH SYNOPSIS
.B "bool" ntfs_is_logfile_clean
.BI "(struct inode *log_vi "  ","
.BI "const RESTART_PAGE_HEADER *rp "  ");"
.SH ARGUMENTS
.IP "log_vi" 12
struct inode of loaded journal $LogFile to check
.IP "rp" 12
copy of the current restart page
.SH "DESCRIPTION"
Analyze the $LogFile journal and return 'true' if it indicates the volume was
shutdown cleanly and 'false' if not.

At present we only look at the two restart pages and ignore the log record
pages.  This is a little bit crude in that there will be a very small number
of cases where we think that a volume is dirty when in fact it is clean.
This should only affect volumes that have not been shutdown cleanly but did
not have any pending, non-check-pointed i/o, i.e. they were completely idle
at least for the five seconds preceding the unclean shutdown.

This function assumes that the $LogFile journal has already been consistency
checked by a call to \fBntfs_check_logfile\fP and in particular if the $LogFile
is empty this function requires that \fBNVolLogFileEmpty\fP is true otherwise an
empty volume will be reported as dirty.
