.TH "ntfs_attr_find_in_attrdef" 9 "ntfs_attr_find_in_attrdef" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ntfs_attr_find_in_attrdef \- find an attribute in the $AttrDef system file
.SH SYNOPSIS
.B "ATTR_DEF *" ntfs_attr_find_in_attrdef
.BI "(const ntfs_volume *vol "  ","
.BI "const ATTR_TYPE type "  ");"
.SH ARGUMENTS
.IP "vol" 12
ntfs volume to which the attribute belongs
.IP "type" 12
attribute type which to find
.SH "DESCRIPTION"
Search for the attribute definition record corresponding to the attribute
\fItype\fP in the $AttrDef system file.

Return the attribute type definition record if found and NULL if not found.
