.TH "numa_reset_distance" 9 "numa_reset_distance" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
numa_reset_distance \- Reset NUMA distance table
.SH SYNOPSIS
.B "void" numa_reset_distance
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

The current table is freed.  The next \fBnuma_set_distance\fP call will
create a new one.
