.TH "nv_update_linkspeed" 9 "nv_update_linkspeed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nv_update_linkspeed \- Setup the MAC according to the link partner
.SH SYNOPSIS
.B "int" nv_update_linkspeed
.BI "(struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Network device to be configured
.SH "DESCRIPTION"
The function queries the PHY and checks if there is a link partner.
If yes, then it sets up the MAC accordingly. Otherwise, the MAC is
set to 10 MBit HD.

The function returns 0 if there is no link partner and 1 if there is
a good link partner.
