.TH "nvmem_dev_name" 9 "nvmem_dev_name" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nvmem_dev_name \- Get the name of a given nvmem device.
.SH SYNOPSIS
.B "const char *" nvmem_dev_name
.BI "(struct nvmem_device *nvmem "  ");"
.SH ARGUMENTS
.IP "nvmem" 12
nvmem device.
.SH "RETURN"
name of the nvmem device.
