.TH "nx_register_algs" 9 "nx_register_algs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
nx_register_algs \- register algorithms with the crypto API
.SH SYNOPSIS
.B "int" nx_register_algs
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Called from \fBnx_probe\fP

If all OF properties are in an acceptable state, the driver flags will
indicate that we're ready and we'll create our debugfs files and register
out crypto algorithms.
