.TH "objagg_obj_root_priv" 9 "objagg_obj_root_priv" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
objagg_obj_root_priv \- obtains root private for an object
.SH SYNOPSIS
.B "const void *" objagg_obj_root_priv
.BI "(const struct objagg_obj *objagg_obj "  ");"
.SH ARGUMENTS
.IP "objagg_obj" 12
objagg object instance
.SH "NOTE"
all locking must be provided by the caller.
.SH "DESCRIPTION"
Either the object is root itself when the private is returned
directly, or the parent is root and its private is returned
instead.

Returns a user private root pointer.
