.TH "ocxlflash_start_work" 9 "ocxlflash_start_work" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ocxlflash_start_work \- start a user context
.SH SYNOPSIS
.B "int" ocxlflash_start_work
.BI "(void *ctx_cookie "  ","
.BI "u64 num_irqs "  ");"
.SH ARGUMENTS
.IP "ctx_cookie" 12
Context to be started.
.IP "num_irqs" 12
Number of interrupts requested.
.SH "RETURN"
0 on success, -errno on failure
