.TH "ocxlflash_afu_irq" 9 "ocxlflash_afu_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ocxlflash_afu_irq \- interrupt handler for user contexts
.SH SYNOPSIS
.B "irqreturn_t" ocxlflash_afu_irq
.BI "(int irq "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "irq" 12
Interrupt number.
.IP "data" 12
Private data provided at interrupt registration, the context.
.SH "RETURN"
Always return IRQ_HANDLED.
