.TH "ocxlflash_config_afu" 9 "ocxlflash_config_afu" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ocxlflash_config_afu \- configure the host AFU
.SH SYNOPSIS
.B "int" ocxlflash_config_afu
.BI "(struct pci_dev *pdev "  ","
.BI "struct ocxl_hw_afu *afu "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device associated with the host.
.IP "afu" 12
AFU associated with the host.
.SH "DESCRIPTION"
Must be called _after_ host function configuration.
.SH "RETURN"
0 on success, -errno on failure
