.TH "ocxlflash_dev_context_init" 9 "ocxlflash_dev_context_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ocxlflash_dev_context_init \- allocate and initialize an adapter context
.SH SYNOPSIS
.B "void *" ocxlflash_dev_context_init
.BI "(struct pci_dev *pdev "  ","
.BI "void *afu_cookie "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device associated with the host.
.IP "afu_cookie" 12
Hardware AFU associated with the host.
.SH "RETURN"
returns the adapter context on success, ERR_PTR on failure
