.TH "of_address_to_resource" 9 "of_address_to_resource" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_address_to_resource \- Translate device tree address and return as resource
.SH SYNOPSIS
.B "int" of_address_to_resource
.BI "(struct device_node *dev "  ","
.BI "int index "  ","
.BI "struct resource *r "  ");"
.SH ARGUMENTS
.IP "dev" 12
-- undescribed --
.IP "index" 12
-- undescribed --
.IP "r" 12
-- undescribed --
.SH "DESCRIPTION"

Note that if your address is a PIO address, the conversion will fail if
the physical address can't be internally converted to an IO token with
\fBpci_address_to_pio\fP, that is because it's either called too early or it
can't be matched to any host bridge IO space
