.TH "of_alias_scan" 9 "of_alias_scan" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_alias_scan \- Scan all properties of the 'aliases' node
.SH SYNOPSIS
.B "void" of_alias_scan
.BI "(void * (*dt_alloc)(u64 size, u64 align) "  ");"
.SH ARGUMENTS
.IP "dt_alloc" 12
An allocator that provides a virtual address to memory
for storing the resulting tree
.SH "DESCRIPTION"

The function scans all the properties of the 'aliases' node and populates
the global lookup table with the properties.  It returns the
number of alias properties found, or an error code in case of failure.
