.TH "of_clk_get_from_provider" 9 "of_clk_get_from_provider" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_clk_get_from_provider \- Lookup a clock from a clock provider
.SH SYNOPSIS
.B "struct clk *" of_clk_get_from_provider
.BI "(struct of_phandle_args *clkspec "  ");"
.SH ARGUMENTS
.IP "clkspec" 12
pointer to a clock specifier data structure
.SH "DESCRIPTION"
This function looks up a struct clk from the registered list of clock
providers, an input is a clock specifier data structure as returned
from the \fBof_parse_phandle_with_args\fP function call.
