.TH "of_find_last_cache_level" 9 "of_find_last_cache_level" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_find_last_cache_level \- Find the level at which the last cache is present for the given logical cpu
.SH SYNOPSIS
.B "int" of_find_last_cache_level
.BI "(unsigned int cpu "  ");"
.SH ARGUMENTS
.IP "cpu" 12
cpu number(logical index) for which the last cache level is needed
.SH "DESCRIPTION"
Returns the the level at which the last cache is present. It is exactly
same as  the total number of cache levels for the given logical cpu.
