.TH "of_fpga_region_find" 9 "of_fpga_region_find" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_fpga_region_find \- find FPGA region
.SH SYNOPSIS
.B "struct fpga_region *" of_fpga_region_find
.BI "(struct device_node *np "  ");"
.SH ARGUMENTS
.IP "np" 12
device node of FPGA Region
.SH "DESCRIPTION"
Caller will need to put_device(\fIregion->dev\fP) when done.

Returns FPGA Region struct or NULL
