.TH "of_fpga_mgr_get" 9 "of_fpga_mgr_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_fpga_mgr_get \- Given a device node, get a reference to a fpga mgr.
.SH SYNOPSIS
.B "struct fpga_manager *" of_fpga_mgr_get
.BI "(struct device_node *node "  ");"
.SH ARGUMENTS
.IP "node" 12
device node
.SH "RETURN"
fpga manager struct or \fBIS_ERR\fP condition containing error code.
