.TH "of_graph_parse_endpoint" 9 "of_graph_parse_endpoint" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_graph_parse_endpoint \- parse common endpoint node properties
.SH SYNOPSIS
.B "int" of_graph_parse_endpoint
.BI "(const struct device_node *node "  ","
.BI "struct of_endpoint *endpoint "  ");"
.SH ARGUMENTS
.IP "node" 12
pointer to endpoint device_node
.IP "endpoint" 12
pointer to the OF endpoint data structure
.SH "DESCRIPTION"
The caller should hold a reference to \fInode\fP.
