.TH "of_get_flat_dt_prop" 9 "of_get_flat_dt_prop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_get_flat_dt_prop \- Given a node in the flat blob, return the property ptr
.SH SYNOPSIS
.B "const void *" of_get_flat_dt_prop
.BI "(unsigned long node "  ","
.BI "const char *name "  ","
.BI "int *size "  ");"
.SH ARGUMENTS
.IP "node" 12
-- undescribed --
.IP "name" 12
-- undescribed --
.IP "size" 12
-- undescribed --
.SH "DESCRIPTION"

This function can be used within scan_flattened_dt callback to get
access to properties
