.TH "of_irq_to_resource_table" 9 "of_irq_to_resource_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_irq_to_resource_table \- Fill in resource table with node's IRQ info
.SH SYNOPSIS
.B "int" of_irq_to_resource_table
.BI "(struct device_node *dev "  ","
.BI "struct resource *res "  ","
.BI "int nr_irqs "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to device tree node
.IP "res" 12
array of resources to fill in
.IP "nr_irqs" 12
the number of IRQs (and upper bound for num of \fIres\fP elements)
.SH "DESCRIPTION"
Returns the size of the filled in table (up to \fInr_irqs\fP).
