.TH "of_pci_get_devfn" 9 "of_pci_get_devfn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_pci_get_devfn \- Get device and function numbers for a device node
.SH SYNOPSIS
.B "int" of_pci_get_devfn
.BI "(struct device_node *np "  ");"
.SH ARGUMENTS
.IP "np" 12
device node
.SH "DESCRIPTION"
Parses a standard 5-cell PCI resource and returns an 8-bit value that can
be passed to the \fBPCI_SLOT\fP and \fBPCI_FUNC\fP macros to extract the device
and function numbers respectively. On error a negative error code is
returned.
