.TH "of_parse_phandle" 9 "of_parse_phandle" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_parse_phandle \- Resolve a phandle property to a device_node pointer
.SH SYNOPSIS
.B "struct device_node *" of_parse_phandle
.BI "(const struct device_node *np "  ","
.BI "const char *phandle_name "  ","
.BI "int index "  ");"
.SH ARGUMENTS
.IP "np" 12
Pointer to device node holding phandle property
.IP "phandle_name" 12
Name of property holding a phandle value
.IP "index" 12
For properties holding a table of phandles, this is the index into
the table
.SH "DESCRIPTION"
Returns the device_node pointer with refcount incremented.  Use
\fBof_node_put\fP on it when done.
