.TH "of_ti_dpll_setup" 9 "of_ti_dpll_setup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
of_ti_dpll_setup \- Setup function for OMAP DPLL clocks
.SH SYNOPSIS
.B "void" of_ti_dpll_setup
.BI "(struct device_node *node "  ","
.BI "const struct clk_ops *ops "  ","
.BI "const struct dpll_data *ddt "  ");"
.SH ARGUMENTS
.IP "node" 12
device node containing the DPLL info
.IP "ops" 12
ops for the DPLL
.IP "ddt" 12
DPLL data template to use
.SH "DESCRIPTION"
Initializes a DPLL clock from device tree data.
