.TH "ofdt_write" 9 "ofdt_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ofdt_write \- perform operations on the Open Firmware device tree
.SH SYNOPSIS
.B "ssize_t" ofdt_write
.BI "(struct file *file "  ","
.BI "const char __user *buf "  ","
.BI "size_t count "  ","
.BI "loff_t *off "  ");"
.SH ARGUMENTS
.IP "file" 12
not used
.IP "buf" 12
command and arguments
.IP "count" 12
size of the command buffer
.IP "off" 12
not used
.SH "DESCRIPTION"
Operations supported at this time are addition and removal of
whole nodes along with their properties.  Operations on individual
properties are not implemented (yet).
