.TH "ohci_hcd_pxa27x_probe" 9 "ohci_hcd_pxa27x_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ohci_hcd_pxa27x_probe \- initialize pxa27x-based HCDs
.SH SYNOPSIS
.B "int" ohci_hcd_pxa27x_probe
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
USB Host controller to probe
.SH "CONTEXT"
task context, might sleep
.SH "DESCRIPTION"
Allocates basic resources for this USB host controller, and
then invokes the \fBstart\fP method for the HCD associated with it
through the hotplug entry's driver_data.
