.TH "omap_vp_enable" 9 "omap_vp_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_vp_enable \- API to enable a particular VP
.SH SYNOPSIS
.B "void" omap_vp_enable
.BI "(struct voltagedomain *voltdm "  ");"
.SH ARGUMENTS
.IP "voltdm" 12
pointer to the VDD whose VP is to be enabled.
.SH "DESCRIPTION"
This API enables a particular voltage processor. Needed by the smartreflex
class drivers.
