.TH "omap_vc_config_channel" 9 "omap_vc_config_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_vc_config_channel \- configure VC channel to PMIC mappings
.SH SYNOPSIS
.B "int" omap_vc_config_channel
.BI "(struct voltagedomain *voltdm "  ");"
.SH ARGUMENTS
.IP "voltdm" 12
pointer to voltagdomain defining the desired VC channel
.SH "DESCRIPTION"
Configures the VC channel to PMIC mappings for the following
PMIC settings
- i2c slave address (SA)
- voltage configuration address (RAV)
- command configuration address (RAC) and enable bit (RACEN)
- command values for ON, ONLP, RET and OFF (CMD)

This function currently only allows flexible configuration of the
non-default channel.  Starting with OMAP4, there are more than 2
channels, with one defined as the default (on OMAP4, it's MPU.)
Only the non-default channel can be configured.
