.TH "omap_prm_base_init" 9 "omap_prm_base_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_prm_base_init \- Populates the prm partitions
.SH SYNOPSIS
.B "void" omap_prm_base_init
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Populates the base addresses of the _prm_bases
array used for read/write of prm module registers.
