.TH "omap_control_usb_set_sessionend" 9 "omap_control_usb_set_sessionend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_control_usb_set_sessionend \- Enable SESSIONEND and IDIG to high impedance
.SH SYNOPSIS
.B "void" omap_control_usb_set_sessionend
.BI "(struct omap_control_phy *ctrl_phy "  ");"
.SH ARGUMENTS
.IP "ctrl_phy" 12
struct omap_control_phy *
.SH "DESCRIPTION"
Writes to the mailbox register to notify the usb core it's now in
disconnected state.
