.TH "omap_voltage_late_init" 9 "omap_voltage_late_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_voltage_late_init \- Init the various voltage parameters
.SH SYNOPSIS
.B "int" omap_voltage_late_init
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This API is to be called in the later stages of the
system boot to init the voltage controller and
voltage processors.
