.TH "omap3_ctrl_setup_d2d_padconf" 9 "omap3_ctrl_setup_d2d_padconf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap3_ctrl_setup_d2d_padconf \- setup stacked modem pads for idle
.SH SYNOPSIS
.B "void" omap3_ctrl_setup_d2d_padconf
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Sets up the pads controlling the stacked modem in such way that the
device can enter idle.
