.TH "omap_prcm_register_chain_handler" 9 "omap_prcm_register_chain_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_prcm_register_chain_handler \- initializes the prcm chained interrupt handler based on provided parameters
.SH SYNOPSIS
.B "int" omap_prcm_register_chain_handler
.BI "(struct omap_prcm_irq_setup *irq_setup "  ");"
.SH ARGUMENTS
.IP "irq_setup" 12
hardware data about the underlying PRM/PRCM
.SH "DESCRIPTION"
Set up the PRCM chained interrupt handler on the PRCM IRQ.  Sets up
one generic IRQ chip per PRM interrupt status/enable register pair.
Returns 0 upon success, -EINVAL if called twice or if invalid
arguments are passed, or -ENOMEM on any other error.
