.TH "omap3xxx_prm_clear_global_cold_reset" 9 "omap3xxx_prm_clear_global_cold_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap3xxx_prm_clear_global_cold_reset \- checks the global cold reset status and clears it if asserted
.SH SYNOPSIS
.B "int" omap3xxx_prm_clear_global_cold_reset
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Checks if cold-reset has occurred and clears the status bit if yes. Returns
1 if cold-reset has occurred, 0 otherwise.
