.TH "omap3_dpll_recalc" 9 "omap3_dpll_recalc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap3_dpll_recalc \- recalculate DPLL rate
.SH SYNOPSIS
.B "unsigned long" omap3_dpll_recalc
.BI "(struct clk_hw *hw "  ","
.BI "unsigned long parent_rate "  ");"
.SH ARGUMENTS
.IP "hw" 12
struct clk_hw containing the DPLL struct clk
.IP "parent_rate" 12
clock rate of the DPLL parent
.SH "DESCRIPTION"
Recalculate and propagate the DPLL rate.
