.TH "omap_voltage_get_volttable" 9 "omap_voltage_get_volttable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_voltage_get_volttable \- API to get the voltage table associated with a particular voltage domain.
.SH SYNOPSIS
.B "void" omap_voltage_get_volttable
.BI "(struct voltagedomain *voltdm "  ","
.BI "struct omap_volt_data **volt_data "  ");"
.SH ARGUMENTS
.IP "voltdm" 12
pointer to the VDD for which the voltage table is required
.IP "volt_data" 12
the voltage table for the particular vdd which is to be
populated by this API
.SH "DESCRIPTION"
This API populates the voltage table associated with a VDD into the
passed parameter pointer. Returns the count of distinct voltages
supported by this vdd.
