.TH "omap_control_pcie_pcs" 9 "omap_control_pcie_pcs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
omap_control_pcie_pcs \- set the PCS delay count
.SH SYNOPSIS
.B "void" omap_control_pcie_pcs
.BI "(struct device *dev "  ","
.BI "u8 delay "  ");"
.SH ARGUMENTS
.IP "dev" 12
the control module device
.IP "delay" 12
8 bit delay value
