.TH "onenand_read_fact_prot_reg" 9 "onenand_read_fact_prot_reg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
onenand_read_fact_prot_reg \- [MTD Interface] Read factory OTP area
.SH SYNOPSIS
.B "int" onenand_read_fact_prot_reg
.BI "(struct mtd_info *mtd "  ","
.BI "loff_t from "  ","
.BI "size_t len "  ","
.BI "size_t *retlen "  ","
.BI "u_char *buf "  ");"
.SH ARGUMENTS
.IP "mtd" 12
MTD device structure
.IP "from" 12
The offset to read
.IP "len" 12
number of bytes to read
.IP "retlen" 12
pointer to variable to store the number of read bytes
.IP "buf" 12
the databuffer to put/get data
.SH "DESCRIPTION"
Read factory OTP area.
