.TH "orc_reset_scsi_bus" 9 "orc_reset_scsi_bus" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
orc_reset_scsi_bus \- perform bus reset
.SH SYNOPSIS
.B "int" orc_reset_scsi_bus
.BI "(struct orc_host * host "  ");"
.SH ARGUMENTS
.IP "host" 12
host being reset

Perform a full bus reset on the adapter.
