.TH "other_cnt_show" 9 "other_cnt_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
other_cnt_show \- other io count - this is the number of I/O requests other than read and write requests. Typically these are tape movement requests but will include driver tape movement. This includes only requests issued by the st driver.
.SH SYNOPSIS
.B "ssize_t" other_cnt_show
.BI "(struct device *dev "  ","
.BI "struct device_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "dev" 12
struct device
.IP "attr" 12
attribute structure
.IP "buf" 12
buffer to return formatted data in
