.TH "p4d_set_huge" 9 "p4d_set_huge" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
p4d_set_huge \- setup kernel P4D mapping
.SH SYNOPSIS
.B "int" p4d_set_huge
.BI "(p4d_t *p4d "  ","
.BI "phys_addr_t addr "  ","
.BI "pgprot_t prot "  ");"
.SH ARGUMENTS
.IP "p4d" 12
-- undescribed --
.IP "addr" 12
-- undescribed --
.IP "prot" 12
-- undescribed --
.SH "DESCRIPTION"

No 512GB pages yet -- always return 0
