.TH "p9_client_flush" 9 "p9_client_flush" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
p9_client_flush \- flush (cancel) a request
.SH SYNOPSIS
.B "int" p9_client_flush
.BI "(struct p9_client *c "  ","
.BI "struct p9_req_t *oldreq "  ");"
.SH ARGUMENTS
.IP "c" 12
client state
.IP "oldreq" 12
request to cancel
.SH "DESCRIPTION"
This sents a flush for a particular request and links
the flush request to the original request.  The current
code only supports a single flush request although the protocol
allows for multiple flush requests to be sent for a single request.
