.TH "p9_tag_remove" 9 "p9_tag_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
p9_tag_remove \- Remove a tag.
.SH SYNOPSIS
.B "int" p9_tag_remove
.BI "(struct p9_client *c "  ","
.BI "struct p9_req_t *r "  ");"
.SH ARGUMENTS
.IP "c" 12
Client session.
.IP "r" 12
Request of reference.
.SH "CONTEXT"
Any context.
