.TH "palmas_pwron_probe" 9 "palmas_pwron_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
palmas_pwron_probe \- probe
.SH SYNOPSIS
.B "int" palmas_pwron_probe
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
platform device for the button
.SH "RETURN"
0 for successful probe else appropriate error
