.TH "parport_ip32_clear_epp_timeout" 9 "parport_ip32_clear_epp_timeout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parport_ip32_clear_epp_timeout \- clear Timeout bit in EPP mode
.SH SYNOPSIS
.B "unsigned int" parport_ip32_clear_epp_timeout
.BI "(struct parport *p "  ");"
.SH ARGUMENTS
.IP "p" 12
pointer to \fIstruct parport\fP
.SH "DESCRIPTION"
Returns 1 if the Timeout bit is clear, and 0 otherwise.
