.TH "parport_ip32_dma_get_residue" 9 "parport_ip32_dma_get_residue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parport_ip32_dma_get_residue \- get residue from last DMA transfer
.SH SYNOPSIS
.B "size_t" parport_ip32_dma_get_residue
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Returns the number of bytes remaining from last DMA transfer.
