.TH "parport_get_port" 9 "parport_get_port" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parport_get_port \- increment a port's reference count
.SH SYNOPSIS
.B "struct parport *" parport_get_port
.BI "(struct parport *port "  ");"
.SH ARGUMENTS
.IP "port" 12
the port

This ensures that a struct parport pointer remains valid
until the matching \fBparport_put_port\fP call.
