.TH "parse_opts" 9 "parse_opts" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
parse_opts \- parse mount options into rdma options structure
.SH SYNOPSIS
.B "int" parse_opts
.BI "(char *params "  ","
.BI "struct p9_rdma_opts *opts "  ");"
.SH ARGUMENTS
.IP "params" 12
options string passed from mount
.IP "opts" 12
rdma transport-specific structure to parse options into
.SH "DESCRIPTION"
Returns 0 upon success, -ERRNO upon failure
