.TH "path_put" 9 "path_put" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
path_put \- put a reference to a path
.SH SYNOPSIS
.B "void" path_put
.BI "(const struct path *path "  ");"
.SH ARGUMENTS
.IP "path" 12
path to put the reference to
.SH "DESCRIPTION"
Given a path decrement the reference count to the dentry and the vfsmount.
