.TH "path_has_submounts" 9 "path_has_submounts" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
path_has_submounts \- check for mounts over a dentry in the current namespace.
.SH SYNOPSIS
.B "int" path_has_submounts
.BI "(const struct path *parent "  ");"
.SH ARGUMENTS
.IP "parent" 12
path to check.
.SH "DESCRIPTION"
Return true if the parent or its subdirectories contain
a mount point in the current namespace.
