.TH "pcc_parse_subspace_irq" 9 "pcc_parse_subspace_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcc_parse_subspace_irq \- Parse the PCC IRQ and PCC ACK register There should be one entry per PCC client.
.SH SYNOPSIS
.B "int" pcc_parse_subspace_irq
.BI "(int id "  ","
.BI "struct acpi_pcct_hw_reduced *pcct_ss "  ");"
.SH ARGUMENTS
.IP "id" 12
PCC subspace index.
.IP "pcct_ss" 12
Pointer to the ACPI subtable header under the PCCT.
.SH "RETURN"
0 for Success, else errno.
.SH "DESCRIPTION"
This gets called for each entry in the PCC table.
