.TH "pch_udc_pcd_ep_enable" 9 "pch_udc_pcd_ep_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_udc_pcd_ep_enable \- This API enables the endpoint. It is called from gadget driver
.SH SYNOPSIS
.B "int" pch_udc_pcd_ep_enable
.BI "(struct usb_ep *usbep "  ","
.BI "const struct usb_endpoint_descriptor *desc "  ");"
.SH ARGUMENTS
.IP "usbep" 12
Reference to the USB endpoint structure
.IP "desc" 12
Reference to the USB endpoint descriptor structure
.SH "DESCRIPTION"
Return codes:
0:              Success
-EINVAL:
-ESHUTDOWN:
