.TH "pch_gbe_setup_rx_resources" 9 "pch_gbe_setup_rx_resources" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_gbe_setup_rx_resources \- Allocate Rx resources (Descriptors)
.SH SYNOPSIS
.B "int" pch_gbe_setup_rx_resources
.BI "(struct pch_gbe_adapter *adapter "  ","
.BI "struct pch_gbe_rx_ring *rx_ring "  ");"
.SH ARGUMENTS
.IP "adapter" 12
Board private structure
.IP "rx_ring" 12
Rx descriptor ring (for a specific queue) to setup
.SH "RETURN"
0:              Successfully
Negative value: Failed
