.TH "pch_vbus_gpio_irq" 9 "pch_vbus_gpio_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_vbus_gpio_irq \- IRQ handler for GPIO interrupt for changing VBUS
.SH SYNOPSIS
.B "irqreturn_t" pch_vbus_gpio_irq
.BI "(int irq "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "irq" 12
Interrupt request number
.IP "data" 12
Reference to the device structure
.SH "DESCRIPTION"
Return codes:
0: Success
-EINVAL: GPIO port is invalid or can't be initialized.
