.TH "pch_gbe_alloc_rx_buffers" 9 "pch_gbe_alloc_rx_buffers" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_gbe_alloc_rx_buffers \- Replace used receive buffers; legacy & extended
.SH SYNOPSIS
.B "void" pch_gbe_alloc_rx_buffers
.BI "(struct pch_gbe_adapter *adapter "  ","
.BI "struct pch_gbe_rx_ring *rx_ring "  ","
.BI "int cleaned_count "  ");"
.SH ARGUMENTS
.IP "adapter" 12
Board private structure
.IP "rx_ring" 12
Rx descriptor ring
.IP "cleaned_count" 12
Cleaned count
