.TH "pch_gbe_validate_option" 9 "pch_gbe_validate_option" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pch_gbe_validate_option \- Validate option
.SH SYNOPSIS
.B "int" pch_gbe_validate_option
.BI "(int *value "  ","
.BI "const struct pch_gbe_option *opt "  ","
.BI "struct pch_gbe_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "value" 12
value
.IP "opt" 12
option
.IP "adapter" 12
Board private structure
.SH "RETURN"
0:                      Successful.
Negative value:         Failed.
