.TH "pci_free_irq_vectors" 9 "pci_free_irq_vectors" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_free_irq_vectors \- free previously allocated IRQs for a device
.SH SYNOPSIS
.B "void" pci_free_irq_vectors
.BI "(struct pci_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
PCI device to operate on
.SH "DESCRIPTION"
Undoes the allocations and enabling in \fBpci_alloc_irq_vectors\fP.
