.TH "pci_get_legacy_mem" 9 "pci_get_legacy_mem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_get_legacy_mem \- generic legacy mem routine
.SH SYNOPSIS
.B "char *" pci_get_legacy_mem
.BI "(struct pci_bus *bus "  ");"
.SH ARGUMENTS
.IP "bus" 12
bus to get legacy memory base address for
.SH "DESCRIPTION"
Find the base of legacy memory for \fIbus\fP.  This is typically the first
megabyte of bus address space for \fIbus\fP or is simply 0 on platforms whose
chipsets support legacy I/O and memory routing.  Returns the base address
or an error pointer if an error occurred.

This is the ia64 generic version of this routine.  Other platforms
are free to override it with a machine vector.
