.TH "pci_create_resource_files" 9 "pci_create_resource_files" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_create_resource_files \- create resource files in sysfs for @dev
.SH SYNOPSIS
.B "int" pci_create_resource_files
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
dev in question
.SH "DESCRIPTION"
Walk the resources in \fIpdev\fP creating files for each resource available.
