.TH "pci_epc_set_msi" 9 "pci_epc_set_msi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_epc_set_msi \- set the number of MSI interrupt numbers required
.SH SYNOPSIS
.B "int" pci_epc_set_msi
.BI "(struct pci_epc *epc "  ","
.BI "u8 func_no "  ","
.BI "u8 interrupts "  ");"
.SH ARGUMENTS
.IP "epc" 12
the EPC device on which MSI has to be configured
.IP "func_no" 12
the endpoint function number in the EPC device
.IP "interrupts" 12
number of MSI interrupts required by the EPF
.SH "DESCRIPTION"
Invoke to set the required number of MSI interrupts.
