.TH "pci_configure_ari" 9 "pci_configure_ari" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_configure_ari \- enable or disable ARI forwarding
.SH SYNOPSIS
.B "void" pci_configure_ari
.BI "(struct pci_dev *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
the PCI device
.SH "DESCRIPTION"
If \fIdev\fP and its upstream bridge both support ARI, enable ARI in the
bridge.  Otherwise, disable ARI in the bridge.
