.TH "pci_epf_free_space" 9 "pci_epf_free_space" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_epf_free_space \- free the allocated PCI EPF register space
.SH SYNOPSIS
.B "void" pci_epf_free_space
.BI "(struct pci_epf *epf "  ","
.BI "void *addr "  ","
.BI "enum pci_barno bar "  ","
.BI "enum pci_epc_interface_type type "  ");"
.SH ARGUMENTS
.IP "epf" 12
the EPF device from whom to free the memory
.IP "addr" 12
the virtual address of the PCI EPF register space
.IP "bar" 12
the BAR number corresponding to the register space
.IP "type" 12
Identifies if the allocated space is for primary EPC or secondary EPC
.SH "DESCRIPTION"
Invoke to free the allocated PCI EPF register space.
