.TH "pci_mmap_legacy_page_range" 9 "pci_mmap_legacy_page_range" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_mmap_legacy_page_range \- map legacy memory space to userland
.SH SYNOPSIS
.B "int" pci_mmap_legacy_page_range
.BI "(struct pci_bus *bus "  ","
.BI "struct vm_area_struct *vma "  ","
.BI "enum pci_mmap_state mmap_state "  ");"
.SH ARGUMENTS
.IP "bus" 12
bus whose legacy space we're mapping
.IP "vma" 12
vma passed in by mmap
.IP "mmap_state" 12
-- undescribed --
.SH "DESCRIPTION"
Map legacy memory space for this device back to userspace using a machine
vector to get the base address.
