.TH "pci_epc_mem_free_addr" 9 "pci_epc_mem_free_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_epc_mem_free_addr \- free the allocated memory address
.SH SYNOPSIS
.B "void" pci_epc_mem_free_addr
.BI "(struct pci_epc *epc "  ","
.BI "phys_addr_t phys_addr "  ","
.BI "void __iomem *virt_addr "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "epc" 12
the EPC device on which memory was allocated
.IP "phys_addr" 12
the allocated physical address
.IP "virt_addr" 12
virtual address of the allocated mem space
.IP "size" 12
the size of the allocated address space
.SH "DESCRIPTION"
Invoke to free the memory allocated using pci_epc_mem_alloc_addr.
