.TH "pci_msi_get_device_domain" 9 "pci_msi_get_device_domain" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_msi_get_device_domain \- Get the MSI domain for a given PCI device
.SH SYNOPSIS
.B "struct irq_domain *" pci_msi_get_device_domain
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
The PCI device
.SH "DESCRIPTION"
Use the firmware data to find a device-specific MSI domain
(i.e. not one that is set as a default).
.SH "RETURN"
The corresponding MSI domain or NULL if none has been found.
