.TH "pci_epc_map_addr" 9 "pci_epc_map_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_epc_map_addr \- map CPU address to PCI address
.SH SYNOPSIS
.B "int" pci_epc_map_addr
.BI "(struct pci_epc *epc "  ","
.BI "u8 func_no "  ","
.BI "phys_addr_t phys_addr "  ","
.BI "u64 pci_addr "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "epc" 12
the EPC device on which address is allocated
.IP "func_no" 12
the endpoint function number in the EPC device
.IP "phys_addr" 12
physical address of the local system
.IP "pci_addr" 12
PCI address to which the physical address should be mapped
.IP "size" 12
the size of the allocation
.SH "DESCRIPTION"
Invoke to map CPU address with PCI address.
