.TH "pci_find_resource" 9 "pci_find_resource" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_find_resource \- Return matching PCI device resource
.SH SYNOPSIS
.B "struct resource *" pci_find_resource
.BI "(struct pci_dev *dev "  ","
.BI "struct resource *res "  ");"
.SH ARGUMENTS
.IP "dev" 12
PCI device to query
.IP "res" 12
Resource to look for
.SH "DESCRIPTION"
Goes over standard PCI resources (BARs) and checks if the given resource
is partially or fully contained in any of them. In that case the
matching resource is returned, NULL otherwise.
