.TH "pci_epc_get_msi" 9 "pci_epc_get_msi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_epc_get_msi \- get the number of MSI interrupt numbers allocated
.SH SYNOPSIS
.B "int" pci_epc_get_msi
.BI "(struct pci_epc *epc "  ","
.BI "u8 func_no "  ");"
.SH ARGUMENTS
.IP "epc" 12
the EPC device to which MSI interrupts was requested
.IP "func_no" 12
the endpoint function number in the EPC device
.SH "DESCRIPTION"
Invoke to get the number of MSI interrupts allocated by the RC
