.TH "pci_mmap_resource" 9 "pci_mmap_resource" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pci_mmap_resource \- map a PCI resource into user memory space
.SH SYNOPSIS
.B "int" pci_mmap_resource
.BI "(struct kobject *kobj "  ","
.BI "struct bin_attribute *attr "  ","
.BI "struct vm_area_struct *vma "  ","
.BI "int write_combine "  ");"
.SH ARGUMENTS
.IP "kobj" 12
kobject for mapping
.IP "attr" 12
struct bin_attribute for the file being mapped
.IP "vma" 12
struct vm_area_struct passed into the mmap
.IP "write_combine" 12
1 for write_combine mapping
.SH "DESCRIPTION"
Use the regular PCI mapping routines to map a PCI resource into userspace.
