.TH "pcie_init_service_irqs" 9 "pcie_init_service_irqs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcie_init_service_irqs \- initialize irqs for PCI Express port services
.SH SYNOPSIS
.B "int" pcie_init_service_irqs
.BI "(struct pci_dev *dev "  ","
.BI "int *irqs "  ","
.BI "int mask "  ");"
.SH ARGUMENTS
.IP "dev" 12
PCI Express port to handle
.IP "irqs" 12
Array of irqs to populate
.IP "mask" 12
Bitmask of port capabilities returned by \fBget_port_device_capability\fP
.SH "DESCRIPTION"
Return value: Interrupt mode associated with the port
