.TH "pcie_set_readrq" 9 "pcie_set_readrq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcie_set_readrq \- set PCI Express maximum memory read request
.SH SYNOPSIS
.B "int" pcie_set_readrq
.BI "(struct pci_dev *dev "  ","
.BI "int rq "  ");"
.SH ARGUMENTS
.IP "dev" 12
PCI device to query
.IP "rq" 12
maximum memory read count in bytes
valid values are 128, 256, 512, 1024, 2048, 4096
.SH "DESCRIPTION"
If possible sets maximum memory read request in bytes
