.TH "pcim_pin_device" 9 "pcim_pin_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcim_pin_device \- Pin managed PCI device
.SH SYNOPSIS
.B "void" pcim_pin_device
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
PCI device to pin
.SH "DESCRIPTION"
Pin managed PCI device \fIpdev\fP.  Pinned device won't be disabled on
driver detach.  \fIpdev\fP must have been enabled with
\fBpcim_enable_device\fP.
