.TH "pcm_pointer" 9 "pcm_pointer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcm_pointer \- implements pointer callback function for PCM middle layer
.SH SYNOPSIS
.B "snd_pcm_uframes_t" pcm_pointer
.BI "(struct snd_pcm_substream *substream "  ");"
.SH ARGUMENTS
.IP "substream" 12
substream pointer
.SH "DESCRIPTION"
This callback is called when the PCM middle layer inquires the current
hardware position on the buffer. The position must be returned in frames,
ranging from 0 to buffer_size-1.
