.TH "pcmcia_map_mem_page" 9 "pcmcia_map_mem_page" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcmcia_map_mem_page \- modify iomem window to point to a different offset
.SH SYNOPSIS
.B "int" pcmcia_map_mem_page
.BI "(struct pcmcia_device *p_dev "  ","
.BI "struct resource *res "  ","
.BI "unsigned int offset "  ");"
.SH ARGUMENTS
.IP "p_dev" 12
pcmcia device
.IP "res" 12
iomem resource already enabled by \fBpcmcia_request_window\fP
.IP "offset" 12
card_offset to map
.SH "DESCRIPTION"
\fBpcmcia_map_mem_page\fP modifies what can be read and written by accessing
an iomem range previously enabled by \fBpcmcia_request_window\fP, by setting
the card_offset value to \fIoffset\fP.
