.TH "pcmcia_nonstatic_validate_mem" 9 "pcmcia_nonstatic_validate_mem" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcmcia_nonstatic_validate_mem \- try to validate iomem for PCMCIA use
.SH SYNOPSIS
.B "int" pcmcia_nonstatic_validate_mem
.BI "(struct pcmcia_socket *s "  ");"
.SH ARGUMENTS
.IP "s" 12
PCMCIA socket to validate
.SH "DESCRIPTION"
This is tricky... when we set up CIS memory, we try to validate
the memory window space allocations.

Locking note: Must be called with skt_mutex held!
