.TH "pcmcia_do_get_tuple" 9 "pcmcia_do_get_tuple" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcmcia_do_get_tuple \- internal helper for pcmcia_get_tuple()
.SH SYNOPSIS
.B "int" pcmcia_do_get_tuple
.BI "(struct pcmcia_device *p_dev "  ","
.BI "tuple_t *tuple "  ","
.BI "void *priv "  ");"
.SH ARGUMENTS
.IP "p_dev" 12
-- undescribed --
.IP "tuple" 12
-- undescribed --
.IP "priv" 12
-- undescribed --
.SH "DESCRIPTION"

\fBpcmcia_do_get_tuple\fP is the internal callback for the call from
\fBpcmcia_get_tuple\fP to \fBpcmcia_loop_tuple\fP. As we're only interested in
the first tuple, return 0 unconditionally. Create a memory buffer large
enough to hold the content of the tuple, and fill it with the tuple data.
The caller is responsible to free the buffer.
