.TH "pcpu_dump_alloc_info" 9 "pcpu_dump_alloc_info" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcpu_dump_alloc_info \- print out information about pcpu_alloc_info
.SH SYNOPSIS
.B "void" pcpu_dump_alloc_info
.BI "(const char *lvl "  ","
.BI "const struct pcpu_alloc_info *ai "  ");"
.SH ARGUMENTS
.IP "lvl" 12
loglevel
.IP "ai" 12
allocation info to dump
.SH "DESCRIPTION"
Print out information about \fIai\fP using loglevel \fIlvl\fP.
