.TH "pcs_allocate_pin_table" 9 "pcs_allocate_pin_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcs_allocate_pin_table \- adds all the pins for the pinctrl driver
.SH SYNOPSIS
.B "int" pcs_allocate_pin_table
.BI "(struct pcs_device *pcs "  ");"
.SH ARGUMENTS
.IP "pcs" 12
pcs driver instance
.SH "DESCRIPTION"
In case of errors, resources are freed in pcs_free_resources.

If your hardware needs holes in the address space, then just set
up multiple driver instances.
