.TH "pcs_quirk_missing_pinctrl_cells" 9 "pcs_quirk_missing_pinctrl_cells" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pcs_quirk_missing_pinctrl_cells \- handle legacy binding
.SH SYNOPSIS
.B "int" pcs_quirk_missing_pinctrl_cells
.BI "(struct pcs_device *pcs "  ","
.BI "struct device_node *np "  ","
.BI "int cells "  ");"
.SH ARGUMENTS
.IP "pcs" 12
pinctrl driver instance
.IP "np" 12
device tree node
.IP "cells" 12
number of cells
.SH "DESCRIPTION"
Handle legacy binding with no #pinctrl-cells. This should be
always two pinctrl-single,bit-per-mux and one for others.
At some point we may want to consider removing this.
