.TH "pdc2026x_dev_config" 9 "pdc2026x_dev_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc2026x_dev_config \- device setup hook
.SH SYNOPSIS
.B "void" pdc2026x_dev_config
.BI "(struct ata_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
newly found device

Perform chip specific early setup. We need to lock the transfer
sizes to 8bit to avoid making the state engine on the 2026x cards
barf.
