.TH "pdc2027x_init_one" 9 "pdc2027x_init_one" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc2027x_init_one \- PCI probe function Called when an instance of PCI adapter is inserted. This function checks whether the hardware is supported, initialize hardware and register an instance of ata_host to libata. (implements struct pci_driver.probe() )
.SH SYNOPSIS
.B "int" pdc2027x_init_one
.BI "(struct pci_dev *pdev "  ","
.BI "const struct pci_device_id *ent "  ");"
.SH ARGUMENTS
.IP "pdev" 12
instance of pci_dev found
.IP "ent" 12
matching entry in the id_tbl[]
