.TH "pdc2027x_set_mode" 9 "pdc2027x_set_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc2027x_set_mode \- Set the timing registers back to correct values.
.SH SYNOPSIS
.B "int" pdc2027x_set_mode
.BI "(struct ata_link *link "  ","
.BI "struct ata_device **r_failed "  ");"
.SH ARGUMENTS
.IP "link" 12
link to configure
.IP "r_failed" 12
Returned device for failure

The pdc2027x hardware will look at "SET FEATURES" and change the timing registers
automatically. The values set by the hardware might be incorrect, under 133Mhz PLL.
This function overwrites the possibly incorrect values set by the hardware to be correct.
