.TH "pdc_pat_cell_get_number" 9 "pdc_pat_cell_get_number" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_pat_cell_get_number \- Returns the cell number.
.SH SYNOPSIS
.B "int" pdc_pat_cell_get_number
.BI "(struct pdc_pat_cell_num *cell_info "  ");"
.SH ARGUMENTS
.IP "cell_info" 12
The return buffer.
.SH "DESCRIPTION"
This PDC call returns the cell number of the cell from which the call
is made.
