.TH "pdc_build_rxd" 9 "pdc_build_rxd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_build_rxd \- Build DMA descriptor to receive SPU result.
.SH SYNOPSIS
.B "void" pdc_build_rxd
.BI "(struct pdc_state *pdcs "  ","
.BI "dma_addr_t dma_addr "  ","
.BI "u32 buf_len "  ","
.BI "u32 flags "  ");"
.SH ARGUMENTS
.IP "pdcs" 12
PDC state for SPU that will generate result
.IP "dma_addr" 12
DMA address of buffer that descriptor is being built for
.IP "buf_len" 12
Length of the receive buffer, in bytes
.IP "flags" 12
Flags to be stored in descriptor
