.TH "pdc_rings_full" 9 "pdc_rings_full" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_rings_full \- Check whether the tx ring has room for tx_cnt descriptors and the rx ring has room for rx_cnt descriptors.
.SH SYNOPSIS
.B "bool" pdc_rings_full
.BI "(struct pdc_state *pdcs "  ","
.BI "int tx_cnt "  ","
.BI "int rx_cnt "  ");"
.SH ARGUMENTS
.IP "pdcs" 12
PDC state
.IP "tx_cnt" 12
The number of descriptors required in the tx ring
.IP "rx_cnt" 12
The number of descriptors required i the rx ring
.SH "RETURN"
true if one of the rings does not have enough space
false if sufficient space is available in both rings
