.TH "pdc_chassis_setup" 9 "pdc_chassis_setup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pdc_chassis_setup \- Enable/disable pdc_chassis code at boot time. @str configuration param: 0 to disable chassis log @return 1
.SH SYNOPSIS
.B "int" pdc_chassis_setup
.BI "(char *str "  ");"
.SH ARGUMENTS
.IP "str" 12
-- undescribed --
