.TH "perf_event_create_kernel_counter" 9 "perf_event_create_kernel_counter" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
perf_event_create_kernel_counter \- 
.SH SYNOPSIS
.B "struct perf_event *" perf_event_create_kernel_counter
.BI "(struct perf_event_attr *attr "  ","
.BI "int cpu "  ","
.BI "struct task_struct *task "  ","
.BI "perf_overflow_handler_t overflow_handler "  ","
.BI "void *context "  ");"
.SH ARGUMENTS
.IP "attr" 12
attributes of the counter to create
.IP "cpu" 12
cpu in which the counter is bound
.IP "task" 12
task to profile (NULL for percpu)
.IP "overflow_handler" 12
-- undescribed --
.IP "context" 12
-- undescribed --
