.TH "phy_disconnect" 9 "phy_disconnect" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_disconnect \- disable interrupts, stop state machine, and detach a PHY device
.SH SYNOPSIS
.B "void" phy_disconnect
.BI "(struct phy_device *phydev "  ");"
.SH ARGUMENTS
.IP "phydev" 12
target phy_device struct
