.TH "phy_device_register" 9 "phy_device_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_device_register \- Register the phy device on the MDIO bus
.SH SYNOPSIS
.B "int" phy_device_register
.BI "(struct phy_device *phydev "  ");"
.SH ARGUMENTS
.IP "phydev" 12
phy_device structure to be added to the MDIO bus
