.TH "phy_ethtool_get_eee" 9 "phy_ethtool_get_eee" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_ethtool_get_eee \- get EEE supported and status
.SH SYNOPSIS
.B "int" phy_ethtool_get_eee
.BI "(struct phy_device *phydev "  ","
.BI "struct ethtool_eee *data "  ");"
.SH ARGUMENTS
.IP "phydev" 12
target phy_device struct
.IP "data" 12
ethtool_eee data
.SH "DESCRIPTION"
it reportes the Supported/Advertisement/LP Advertisement
capabilities.
