.TH "phy_check_link_status" 9 "phy_check_link_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_check_link_status \- check link status and set state accordingly
.SH SYNOPSIS
.B "int" phy_check_link_status
.BI "(struct phy_device *phydev "  ");"
.SH ARGUMENTS
.IP "phydev" 12
the phy_device struct
.SH "DESCRIPTION"
Check for link and whether autoneg was triggered / is running
and set state accordingly
