.TH "phy_detach" 9 "phy_detach" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_detach \- detach a PHY device from its network device
.SH SYNOPSIS
.B "void" phy_detach
.BI "(struct phy_device *phydev "  ");"
.SH ARGUMENTS
.IP "phydev" 12
target phy_device struct
.SH "DESCRIPTION"
This detaches the phy device from its network device and the phy
driver, and drops the reference count taken in \fBphy_attach_direct\fP.
