.TH "phy_speed_up" 9 "phy_speed_up" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_speed_up \- (re)set advertised speeds to all supported speeds
.SH SYNOPSIS
.B "int" phy_speed_up
.BI "(struct phy_device *phydev "  ");"
.SH ARGUMENTS
.IP "phydev" 12
the phy_device struct
.SH "DESCRIPTION"
Used to revert the effect of phy_speed_down
