.TH "phy_get_pause" 9 "phy_get_pause" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_get_pause \- resolve negotiated pause modes
.SH SYNOPSIS
.B "void" phy_get_pause
.BI "(struct phy_device *phydev "  ","
.BI "bool *tx_pause "  ","
.BI "bool *rx_pause "  ");"
.SH ARGUMENTS
.IP "phydev" 12
phy_device struct
.IP "tx_pause" 12
pointer to bool to indicate whether transmit pause should be
enabled.
.IP "rx_pause" 12
pointer to bool to indicate whether receive pause should be
enabled.
.SH "DESCRIPTION"
Resolve and return the flow control modes according to the negotiation
result. This includes checking that we are operating in full duplex mode.
See \fBlinkmode_resolve_pause\fP for further details.
