.TH "phy_remove_lookup" 9 "phy_remove_lookup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_remove_lookup \- find and remove PHY/device association
.SH SYNOPSIS
.B "void" phy_remove_lookup
.BI "(struct phy *phy "  ","
.BI "const char *con_id "  ","
.BI "const char *dev_id "  ");"
.SH ARGUMENTS
.IP "phy" 12
the phy of the association
.IP "con_id" 12
connection ID string on device
.IP "dev_id" 12
the device of the association
.SH "DESCRIPTION"
Finds and unregisters phy_lookup entry that was created with
\fBphy_create_lookup\fP.
