.TH "phy_disable_interrupts" 9 "phy_disable_interrupts" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phy_disable_interrupts \- Disable the PHY interrupts from the PHY side
.SH SYNOPSIS
.B "int" phy_disable_interrupts
.BI "(struct phy_device *phydev "  ");"
.SH ARGUMENTS
.IP "phydev" 12
target phy_device struct
