.TH "phylink_speed_down" 9 "phylink_speed_down" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phylink_speed_down \- set the non-SFP PHY to lowest speed supported by both link partners
.SH SYNOPSIS
.B "int" phylink_speed_down
.BI "(struct phylink *pl "  ","
.BI "bool sync "  ");"
.SH ARGUMENTS
.IP "pl" 12
a pointer to a \fIstruct phylink\fP returned from \fBphylink_create\fP
.IP "sync" 12
perform action synchronously
.SH "DESCRIPTION"
If we have a PHY that is not part of a SFP module, then set the speed
as described in the \fBphy_speed_down\fP function. Please see this function
for a description of the \fIsync\fP parameter.

Returns zero if there is no PHY, otherwise as per \fBphy_speed_down\fP.
