.TH "phylink_get_eee_err" 9 "phylink_get_eee_err" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
phylink_get_eee_err \- read the energy efficient ethernet error counter
.SH SYNOPSIS
.B "int" phylink_get_eee_err
.BI "(struct phylink *pl "  ");"
.SH ARGUMENTS
.IP "pl" 12
a pointer to a \fIstruct phylink\fP returned from \fBphylink_create\fP.
.SH "DESCRIPTION"
Read the Energy Efficient Ethernet error counter from the PHY associated
with the phylink instance specified by \fIpl\fP.

Returns positive error counter value, or negative error code.
