.TH "pinctrl_register_and_init" 9 "pinctrl_register_and_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pinctrl_register_and_init \- register and init pin controller device
.SH SYNOPSIS
.B "int" pinctrl_register_and_init
.BI "(struct pinctrl_desc *pctldesc "  ","
.BI "struct device *dev "  ","
.BI "void *driver_data "  ","
.BI "struct pinctrl_dev **pctldev "  ");"
.SH ARGUMENTS
.IP "pctldesc" 12
descriptor for this pin controller
.IP "dev" 12
parent device for this pin controller
.IP "driver_data" 12
private pin controller data for this pin controller
.IP "pctldev" 12
pin controller device
.SH "DESCRIPTION"
Note that \fBpinctrl_enable\fP still needs to be manually called after
this once the driver is ready.
