.TH "pinconf_generic_parse_dt_config" 9 "pinconf_generic_parse_dt_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pinconf_generic_parse_dt_config \- 
.SH SYNOPSIS
.B "int" pinconf_generic_parse_dt_config
.BI "(struct device_node *np "  ","
.BI "struct pinctrl_dev *pctldev "  ","
.BI "unsigned long **configs "  ","
.BI "unsigned int *nconfigs "  ");"
.SH ARGUMENTS
.IP "np" 12
node containing the pinconfig properties
.IP "pctldev" 12
pincontrol device
.IP "configs" 12
array with nconfigs entries containing the generic pinconf values
must be freed when no longer necessary.
.IP "nconfigs" 12
number of configurations
.SH "DESCRIPTION"
parse the config properties into generic pinconfig values.
