.TH "pinctrl_generic_add_group" 9 "pinctrl_generic_add_group" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pinctrl_generic_add_group \- adds a new pin group
.SH SYNOPSIS
.B "int" pinctrl_generic_add_group
.BI "(struct pinctrl_dev *pctldev "  ","
.BI "const char *name "  ","
.BI "int *pins "  ","
.BI "int num_pins "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "pctldev" 12
pin controller device
.IP "name" 12
name of the pin group
.IP "pins" 12
pins in the pin group
.IP "num_pins" 12
number of pins in the pin group
.IP "data" 12
pin controller driver specific data
.SH "DESCRIPTION"
Note that the caller must take care of locking.
