.TH "pinctrl_init_controller" 9 "pinctrl_init_controller" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pinctrl_init_controller \- init a pin controller device
.SH SYNOPSIS
.B "struct pinctrl_dev *" pinctrl_init_controller
.BI "(struct pinctrl_desc *pctldesc "  ","
.BI "struct device *dev "  ","
.BI "void *driver_data "  ");"
.SH ARGUMENTS
.IP "pctldesc" 12
descriptor for this pin controller
.IP "dev" 12
parent device for this pin controller
.IP "driver_data" 12
private pin controller data for this pin controller
