.TH "pinmux_generic_get_function" 9 "pinmux_generic_get_function" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pinmux_generic_get_function \- returns a function based on the number
.SH SYNOPSIS
.B "struct function_desc *" pinmux_generic_get_function
.BI "(struct pinctrl_dev *pctldev "  ","
.BI "unsigned int selector "  ");"
.SH ARGUMENTS
.IP "pctldev" 12
pin controller device
.IP "selector" 12
function number
