.TH "platform_msi_domain_alloc_irqs" 9 "platform_msi_domain_alloc_irqs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
platform_msi_domain_alloc_irqs \- Allocate MSI interrupts for @dev
.SH SYNOPSIS
.B "int" platform_msi_domain_alloc_irqs
.BI "(struct device *dev "  ","
.BI "unsigned int nvec "  ","
.BI "irq_write_msi_msg_t write_msi_msg "  ");"
.SH ARGUMENTS
.IP "dev" 12
The device for which to allocate interrupts
.IP "nvec" 12
The number of interrupts to allocate
.IP "write_msi_msg" 12
Callback to write an interrupt message for \fIdev\fP
.SH "RETURN"
Zero for success, or an error code in case of failure
