.TH "platform_add_devices" 9 "platform_add_devices" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
platform_add_devices \- add a numbers of platform devices
.SH SYNOPSIS
.B "int" platform_add_devices
.BI "(struct platform_device **devs "  ","
.BI "int num "  ");"
.SH ARGUMENTS
.IP "devs" 12
array of platform devices to add
.IP "num" 12
number of platform devices in array
