.TH "pm8001_chip_interrupt_enable" 9 "pm8001_chip_interrupt_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pm8001_chip_interrupt_enable \- enable PM8001 chip interrupt
.SH SYNOPSIS
.B "void" pm8001_chip_interrupt_enable
.BI "(struct pm8001_hba_info *pm8001_ha "  ","
.BI "u8 vec "  ");"
.SH ARGUMENTS
.IP "pm8001_ha" 12
our hba card information
.IP "vec" 12
unused
