.TH "pm8001_find_dev" 9 "pm8001_find_dev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pm8001_find_dev \- find a matching pm8001_device
.SH SYNOPSIS
.B "struct pm8001_device *" pm8001_find_dev
.BI "(struct pm8001_hba_info *pm8001_ha "  ","
.BI "u32 device_id "  ");"
.SH ARGUMENTS
.IP "pm8001_ha" 12
our hba card information
.IP "device_id" 12
device ID to match against
