.TH "pm8001_interrupt_handler_intx" 9 "pm8001_interrupt_handler_intx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pm8001_interrupt_handler_intx \- main INTx interrupt handler.
.SH SYNOPSIS
.B "irqreturn_t" pm8001_interrupt_handler_intx
.BI "(int irq "  ","
.BI "void *dev_id "  ");"
.SH ARGUMENTS
.IP "irq" 12
interrupt number
.IP "dev_id" 12
sas_ha structure. The HBA is retrieved from sas_has structure.
