.TH "pm_runtime_put_suppliers" 9 "pm_runtime_put_suppliers" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pm_runtime_put_suppliers \- Drop references to supplier devices.
.SH SYNOPSIS
.B "void" pm_runtime_put_suppliers
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Consumer device.
