.TH "pm_suspend_timer_fn" 9 "pm_suspend_timer_fn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pm_suspend_timer_fn \- Timer function for pm_schedule_suspend().
.SH SYNOPSIS
.B "enum hrtimer_restart" pm_suspend_timer_fn
.BI "(struct hrtimer *timer "  ");"
.SH ARGUMENTS
.IP "timer" 12
-- undescribed --
.SH "DESCRIPTION"
Check if the time is right and queue a suspend request.
