.TH "pm_wakeup_dev_event" 9 "pm_wakeup_dev_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pm_wakeup_dev_event \- Notify the PM core of a wakeup event.
.SH SYNOPSIS
.B "void" pm_wakeup_dev_event
.BI "(struct device *dev "  ","
.BI "unsigned int msec "  ","
.BI "bool hard "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device the wakeup event is related to.
.IP "msec" 12
Anticipated event processing time (in milliseconds).
.IP "hard" 12
If set, abort suspends in progress and wake up from suspend-to-idle.
.SH "DESCRIPTION"
Call \fBpm_wakeup_ws_event\fP for the \fIdev\fP's wakeup source object.
