.TH "pm_wakeup_timer_fn" 9 "pm_wakeup_timer_fn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pm_wakeup_timer_fn \- Delayed finalization of a wakeup event.
.SH SYNOPSIS
.B "void" pm_wakeup_timer_fn
.BI "(struct timer_list *t "  ");"
.SH ARGUMENTS
.IP "t" 12
-- undescribed --
.SH "DESCRIPTION"
Call \fBwakeup_source_deactivate\fP for the wakeup source whose address is stored
in \fIdata\fP if it is currently active and its timer has not been canceled and
the expiration time of the timer is not in future.
