.TH "pmcraid_expose_resource" 9 "pmcraid_expose_resource" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_expose_resource \- check if the resource can be exposed to OS
.SH SYNOPSIS
.B "int" pmcraid_expose_resource
.BI "(u16 fw_version "  ","
.BI "struct pmcraid_config_table_entry *cfgte "  ");"
.SH ARGUMENTS
.IP "fw_version" 12
firmware version code
.IP "cfgte" 12
pointer to configuration table entry of the resource
.SH "DESCRIPTION"
Return value:
true if resource can be added to midlayer, false(0) otherwise
