.TH "pmcraid_handle_error_log" 9 "pmcraid_handle_error_log" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_handle_error_log \- Handle a config change (error log) from the IOA
.SH SYNOPSIS
.B "void" pmcraid_handle_error_log
.BI "(struct pmcraid_instance *pinstance "  ");"
.SH ARGUMENTS
.IP "pinstance" 12
pointer to per adapter instance structure
.SH "DESCRIPTION"
Return value:
none
