.TH "pmcraid_get_dump" 9 "pmcraid_get_dump" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_get_dump \- retrieves IOA dump in case of Unit Check interrupt
.SH SYNOPSIS
.B "void" pmcraid_get_dump
.BI "(struct pmcraid_instance *pinstance "  ");"
.SH ARGUMENTS
.IP "pinstance" 12
pointer to adapter instance structure
.SH "DESCRIPTION"
Return Value
none
