.TH "pmcraid_request_sense" 9 "pmcraid_request_sense" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pmcraid_request_sense \- Send request sense to a device
.SH SYNOPSIS
.B "void" pmcraid_request_sense
.BI "(struct pmcraid_cmd *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
pmcraid command struct
.SH "DESCRIPTION"
This function sends a request sense to a device as a result of a check
condition. This method re-uses the same command block that failed earlier.
