.TH "port_chk_shift" 9 "port_chk_shift" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
port_chk_shift \- check port bit
.SH SYNOPSIS
.B "int" port_chk_shift
.BI "(struct ksz_hw *hw "  ","
.BI "int port "  ","
.BI "u32 addr "  ","
.BI "int shift "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware instance.
.IP "port" 12
The port index.
.IP "addr" 12
The offset of the register.
.IP "shift" 12
Number of bits to shift.
.SH "DESCRIPTION"
This function checks whether the specified port is set in the register or
not.

Return 0 if the port is not set.
