.TH "port_get_def_vid" 9 "port_get_def_vid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
port_get_def_vid \- get port default VID.
.SH SYNOPSIS
.B "void" port_get_def_vid
.BI "(struct ksz_hw *hw "  ","
.BI "int port "  ","
.BI "u16 *vid "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware instance.
.IP "port" 12
The port index.
.IP "vid" 12
Buffer to store the VID.
.SH "DESCRIPTION"
This routine retrieves the default VID of the port.
