.TH "power_allocator_bind" 9 "power_allocator_bind" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
power_allocator_bind \- bind the power_allocator governor to a thermal zone
.SH SYNOPSIS
.B "int" power_allocator_bind
.BI "(struct thermal_zone_device *tz "  ");"
.SH ARGUMENTS
.IP "tz" 12
thermal zone to bind it to
.SH "DESCRIPTION"
Initialize the PID controller parameters and bind it to the thermal
zone.
.SH "RETURN"
0 on success, or -ENOMEM if we ran out of memory, or -EINVAL
when there are unsupported cooling devices in the \fItz\fP.
