.TH "powernow_k6_target" 9 "powernow_k6_target" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
powernow_k6_target \- set the PowerNow! multiplier
.SH SYNOPSIS
.B "int" powernow_k6_target
.BI "(struct cpufreq_policy *policy "  ","
.BI "unsigned int best_i "  ");"
.SH ARGUMENTS
.IP "policy" 12
-- undescribed --
.IP "best_i" 12
clock_ratio[best_i] is the target multiplier

Tries to change the PowerNow! multiplier
