.TH "prepare_api_cmd" 9 "prepare_api_cmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
prepare_api_cmd \- prepare API CMD command
.SH SYNOPSIS
.B "void" prepare_api_cmd
.BI "(struct hinic_api_cmd_chain *chain "  ","
.BI "enum hinic_node_id dest "  ","
.BI "void *cmd "  ","
.BI "u16 cmd_size "  ");"
.SH ARGUMENTS
.IP "chain" 12
chain for the command
.IP "dest" 12
destination node on the card that will receive the command
.IP "cmd" 12
command data
.IP "cmd_size" 12
the command size
