.TH "printk_safe_flush" 9 "printk_safe_flush" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
printk_safe_flush \- flush all per-cpu nmi buffers.
.SH SYNOPSIS
.B "void" printk_safe_flush
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

The buffers are flushed automatically via IRQ work. This function
is useful only when someone wants to be sure that all buffers have
been flushed at some point.
