.TH "proc_put_long" 9 "proc_put_long" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
proc_put_long \- converts an integer to a decimal ASCII formatted string
.SH SYNOPSIS
.B "void" proc_put_long
.BI "(void **buf "  ","
.BI "size_t *size "  ","
.BI "unsigned long val "  ","
.BI "bool neg "  ");"
.SH ARGUMENTS
.IP "buf" 12
the user buffer
.IP "size" 12
the size of the user buffer
.IP "val" 12
the integer to be converted
.IP "neg" 12
sign of the number, TRUE for negative
.SH "DESCRIPTION"
In case of success \fIbuf\fP and \fIsize\fP are updated with the amount of bytes
written.
