.TH "ps3_lpm_copy_tb" 9 "ps3_lpm_copy_tb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ps3_lpm_copy_tb \- Copy data from the trace buffer to a kernel buffer.
.SH SYNOPSIS
.B "int" ps3_lpm_copy_tb
.BI "(unsigned long offset "  ","
.BI "void *buf "  ","
.BI "unsigned long count "  ","
.BI "unsigned long *bytes_copied "  ");"
.SH ARGUMENTS
.IP "offset" 12
Offset in bytes from the start of the trace buffer.
.IP "buf" 12
Copy destination.
.IP "count" 12
Maximum count of bytes to copy.
.IP "bytes_copied" 12
Pointer to a variable that will receive the number of
bytes copied to \fIbuf\fP.
.SH "DESCRIPTION"
On error \fIbuf\fP will contain any successfully copied trace buffer data
and bytes_copied will be set to the number of bytes successfully copied.
