.TH "ps3_virq_setup" 9 "ps3_virq_setup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ps3_virq_setup \- virq related setup.
.SH SYNOPSIS
.B "int" ps3_virq_setup
.BI "(enum ps3_cpu_binding cpu "  ","
.BI "unsigned long outlet "  ","
.BI "unsigned int *virq "  ");"
.SH ARGUMENTS
.IP "cpu" 12
enum ps3_cpu_binding indicating the cpu the interrupt should be
serviced on.
.IP "outlet" 12
The HV outlet from the various create outlet routines.
.IP "virq" 12
The assigned Linux virq.
.SH "DESCRIPTION"
Calls \fBirq_create_mapping\fP to get a virq and sets the chip data to
ps3_private data.
