.TH "pseries_eeh_pe_get_parent" 9 "pseries_eeh_pe_get_parent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pseries_eeh_pe_get_parent \- Retrieve the parent PE
.SH SYNOPSIS
.B "struct eeh_pe *" pseries_eeh_pe_get_parent
.BI "(struct eeh_dev *edev "  ");"
.SH ARGUMENTS
.IP "edev" 12
EEH device
.SH "DESCRIPTION"
The whole PEs existing in the system are organized as hierarchy
tree. The function is used to retrieve the parent PE according
to the parent EEH device.
