.TH "pseries_eeh_phb_reset" 9 "pseries_eeh_phb_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pseries_eeh_phb_reset \- Reset the specified PHB
.SH SYNOPSIS
.B "int" pseries_eeh_phb_reset
.BI "(struct pci_controller *phb "  ","
.BI "int config_addr "  ","
.BI "int option "  ");"
.SH ARGUMENTS
.IP "phb" 12
PCI controller
.IP "config_addr" 12
-- undescribed --
.IP "option" 12
reset option
.SH "DESCRIPTION"
Reset the specified PHB/PE
