.TH "pseries_eeh_reset" 9 "pseries_eeh_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pseries_eeh_reset \- Reset the specified PE
.SH SYNOPSIS
.B "int" pseries_eeh_reset
.BI "(struct eeh_pe *pe "  ","
.BI "int option "  ");"
.SH ARGUMENTS
.IP "pe" 12
EEH PE
.IP "option" 12
reset option
.SH "DESCRIPTION"
Reset the specified PE
