.TH "pt_read_offset" 9 "pt_read_offset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pt_read_offset \- translate registers into buffer pointers
.SH SYNOPSIS
.B "void" pt_read_offset
.BI "(struct pt_buffer *buf "  ");"
.SH ARGUMENTS
.IP "buf" 12
PT buffer.
.SH "DESCRIPTION"
Set buffer's output pointers from MSR values.
