.TH "put_io_context_active" 9 "put_io_context_active" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
put_io_context_active \- put active reference on ioc
.SH SYNOPSIS
.B "void" put_io_context_active
.BI "(struct io_context *ioc "  ");"
.SH ARGUMENTS
.IP "ioc" 12
ioc of interest
.SH "DESCRIPTION"
Undo \fBget_io_context_active\fP.  If active reference reaches zero after
put, \fIioc\fP can never issue further IOs and ioscheds are notified.
