.TH "put_io_context" 9 "put_io_context" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
put_io_context \- put a reference of io_context
.SH SYNOPSIS
.B "void" put_io_context
.BI "(struct io_context *ioc "  ");"
.SH ARGUMENTS
.IP "ioc" 12
io_context to put
.SH "DESCRIPTION"
Decrement reference count of \fIioc\fP and release it if the count reaches
zero.
