.TH "put_pages_list" 9 "put_pages_list" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
put_pages_list \- release a list of pages
.SH SYNOPSIS
.B "void" put_pages_list
.BI "(struct list_head *pages "  ");"
.SH ARGUMENTS
.IP "pages" 12
list of pages threaded on page->lru
.SH "DESCRIPTION"
Release a list of pages which are strung together on page.lru.  Currently
used by \fBread_cache_pages\fP and related error recovery code.
