.TH "pvrdma_destroy_srq" 9 "pvrdma_destroy_srq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pvrdma_destroy_srq \- destroy shared receive queue
.SH SYNOPSIS
.B "int" pvrdma_destroy_srq
.BI "(struct ib_srq *srq "  ","
.BI "struct ib_udata *udata "  ");"
.SH ARGUMENTS
.IP "srq" 12
the shared receive queue to destroy
.IP "udata" 12
user data or null for kernel object
.SH "RETURN"
0 for success.
