.TH "pwm_omap_dmtimer_set_polarity" 9 "pwm_omap_dmtimer_set_polarity" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pwm_omap_dmtimer_set_polarity \- Changes the polarity of the pwm dm timer.
.SH SYNOPSIS
.B "void" pwm_omap_dmtimer_set_polarity
.BI "(struct pwm_chip *chip "  ","
.BI "struct pwm_device *pwm "  ","
.BI "enum pwm_polarity polarity "  ");"
.SH ARGUMENTS
.IP "chip" 12
Pointer to PWM controller
.IP "pwm" 12
Pointer to PWM channel
.IP "polarity" 12
New pwm polarity to be set
