.TH "pxa_ep_disable" 9 "pxa_ep_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
pxa_ep_disable \- Disable usb endpoint
.SH SYNOPSIS
.B "int" pxa_ep_disable
.BI "(struct usb_ep *_ep "  ");"
.SH ARGUMENTS
.IP "_ep" 12
usb endpoint
.SH "DESCRIPTION"
Same as for pxa_ep_enable, no physical endpoint configuration can be
changed.
Function flushes the endpoint and related requests.
