.TH "q6afe_i2s_port_prepare" 9 "q6afe_i2s_port_prepare" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
q6afe_i2s_port_prepare \- Prepare i2s afe port.
.SH SYNOPSIS
.B "int" q6afe_i2s_port_prepare
.BI "(struct q6afe_port *port "  ","
.BI "struct q6afe_i2s_cfg *cfg "  ");"
.SH ARGUMENTS
.IP "port" 12
Instance of afe port
.IP "cfg" 12
I2S configuration for the afe port
.SH "RETURN"
Will be an negative on error and zero on success.
