.TH "q6afe_port_stop" 9 "q6afe_port_stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
q6afe_port_stop \- Stop a afe port
.SH SYNOPSIS
.B "int" q6afe_port_stop
.BI "(struct q6afe_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
Instance of port to stop
.SH "RETURN"
Will be an negative on packet size on success.
