.TH "q6asm_write_async" 9 "q6asm_write_async" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
q6asm_write_async \- non blocking write
.SH SYNOPSIS
.B "int" q6asm_write_async
.BI "(struct audio_client *ac "  ","
.BI "uint32_t stream_id "  ","
.BI "uint32_t len "  ","
.BI "uint32_t msw_ts "  ","
.BI "uint32_t lsw_ts "  ","
.BI "uint32_t wflags "  ");"
.SH ARGUMENTS
.IP "ac" 12
audio client pointer
.IP "stream_id" 12
stream id
.IP "len" 12
length in bytes
.IP "msw_ts" 12
timestamp msw
.IP "lsw_ts" 12
timestamp lsw
.IP "wflags" 12
flags associated with write
.SH "RETURN"
Will be an negative value on error or zero on success
