.TH "qbman_swp_dqrr_consume" 9 "qbman_swp_dqrr_consume" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qbman_swp_dqrr_consume \- Consume DQRR entries previously returned from qbman_swp_dqrr_next().
.SH SYNOPSIS
.B "void" qbman_swp_dqrr_consume
.BI "(struct qbman_swp *s "  ","
.BI "const struct dpaa2_dq *dq "  ");"
.SH ARGUMENTS
.IP "s" 12
the software portal object
.IP "dq" 12
the DQRR entry to be consumed
