.TH "qcom_scm_ocmem_unlock" 9 "qcom_scm_ocmem_unlock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qcom_scm_ocmem_unlock \- call OCMEM unlock interface to release an OCMEM region from the specified initiator
.SH SYNOPSIS
.B "int" qcom_scm_ocmem_unlock
.BI "(enum qcom_scm_ocmem_client id "  ","
.BI "u32 offset "  ","
.BI "u32 size "  ");"
.SH ARGUMENTS
.IP "id" 12
tz initiator id
.IP "offset" 12
OCMEM offset
.IP "size" 12
OCMEM size
