.TH "qcom_scm_ocmem_lock_available" 9 "qcom_scm_ocmem_lock_available" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qcom_scm_ocmem_lock_available \- is OCMEM lock/unlock interface available
.SH SYNOPSIS
.B "bool" qcom_scm_ocmem_lock_available
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
