.TH "qcom_smem_alloc" 9 "qcom_smem_alloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qcom_smem_alloc \- allocate space for a smem item
.SH SYNOPSIS
.B "int" qcom_smem_alloc
.BI "(unsigned host "  ","
.BI "unsigned item "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "host" 12
remote processor id, or -1
.IP "item" 12
smem item handle
.IP "size" 12
number of bytes to be allocated
.SH "DESCRIPTION"
Allocate space for a given smem item of size \fIsize\fP, given that the item is
not yet allocated.
