.TH "qcom_smem_state_register" 9 "qcom_smem_state_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qcom_smem_state_register \- register a new state
.SH SYNOPSIS
.B "struct qcom_smem_state *" qcom_smem_state_register
.BI "(struct device_node *of_node "  ","
.BI "const struct qcom_smem_state_ops *ops "  ","
.BI "void *priv "  ");"
.SH ARGUMENTS
.IP "of_node" 12
of_node used for matching client lookups
.IP "ops" 12
implementation ops
.IP "priv" 12
implementation specific private data
