.TH "qdio_do_eqbs" 9 "qdio_do_eqbs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qdio_do_eqbs \- extract buffer states for QEBSM
.SH SYNOPSIS
.B "int" qdio_do_eqbs
.BI "(struct qdio_q *q "  ","
.BI "unsigned char *state "  ","
.BI "int start "  ","
.BI "int count "  ","
.BI "int auto_ack "  ");"
.SH ARGUMENTS
.IP "q" 12
queue to manipulate
.IP "state" 12
state of the extracted buffers
.IP "start" 12
buffer number to start at
.IP "count" 12
count of buffers to examine
.IP "auto_ack" 12
automatically acknowledge buffers
.SH "DESCRIPTION"
Returns the number of successfully extracted equal buffer states.
Stops processing if a state is different from the last buffers state.
