.TH "qib_6120_init_hwerrors" 9 "qib_6120_init_hwerrors" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qib_6120_init_hwerrors \- enable hardware errors
.SH SYNOPSIS
.B "void" qib_6120_init_hwerrors
.BI "(struct qib_devdata *dd "  ");"
.SH ARGUMENTS
.IP "dd" 12
the qlogic_ib device
.SH "DESCRIPTION"
now that we have finished initializing everything that might reasonably
cause a hardware error, and cleared those errors bits as they occur,
we can enable hardware errors in the mask (potentially enabling
freeze mode), and enable hardware errors as errors (along with
everything else) in errormask
