.TH "qla2x00_erase_flash_sector" 9 "qla2x00_erase_flash_sector" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla2x00_erase_flash_sector \- Erase a flash sector.
.SH SYNOPSIS
.B "int" qla2x00_erase_flash_sector
.BI "(struct qla_hw_data *ha "  ","
.BI "uint32_t addr "  ","
.BI "uint32_t sec_mask "  ","
.BI "uint8_t man_id "  ","
.BI "uint8_t flash_id "  ");"
.SH ARGUMENTS
.IP "ha" 12
HA context
.IP "addr" 12
Flash sector to erase
.IP "sec_mask" 12
Sector address mask
.IP "man_id" 12
Flash manufacturer ID
.IP "flash_id" 12
Flash ID
.SH "DESCRIPTION"
Returns 0 on success, else non-zero.
