.TH "qla4xxx_eh_device_reset" 9 "qla4xxx_eh_device_reset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla4xxx_eh_device_reset \- callback for target reset.
.SH SYNOPSIS
.B "int" qla4xxx_eh_device_reset
.BI "(struct scsi_cmnd *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
Pointer to Linux's SCSI command structure
.SH "DESCRIPTION"
This routine is called by the Linux OS to reset all luns on the
specified target.
