.TH "qla4xxx_get_bidi_chap" 9 "qla4xxx_get_bidi_chap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla4xxx_get_bidi_chap \- Get a BIDI CHAP user and password
.SH SYNOPSIS
.B "int" qla4xxx_get_bidi_chap
.BI "(struct scsi_qla_host *ha "  ","
.BI "char *username "  ","
.BI "char *password "  ");"
.SH ARGUMENTS
.IP "ha" 12
pointer to adapter structure
.IP "username" 12
CHAP username to be returned
.IP "password" 12
CHAP password to be returned
.SH "DESCRIPTION"
If a boot entry has BIDI CHAP enabled then we need to set the BIDI CHAP
user and password in the sysfs entry in /sys/firmware/iscsi_boot#/.
So from the CHAP cache find the first BIDI CHAP entry and set it
to the boot record in sysfs.
