.TH "qla4_83xx_intr_handler" 9 "qla4_83xx_intr_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qla4_83xx_intr_handler \- hardware interrupt handler.
.SH SYNOPSIS
.B "irqreturn_t" qla4_83xx_intr_handler
.BI "(int irq "  ","
.BI "void *dev_id "  ");"
.SH ARGUMENTS
.IP "irq" 12
Unused
.IP "dev_id" 12
Pointer to host adapter structure
