.TH "qlafx00_multistatus_entry" 9 "qlafx00_multistatus_entry" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qlafx00_multistatus_entry \- Process Multi response queue entries.
.SH SYNOPSIS
.B "void" qlafx00_multistatus_entry
.BI "(struct scsi_qla_host *vha "  ","
.BI "struct rsp_que *rsp "  ","
.BI "void *pkt "  ");"
.SH ARGUMENTS
.IP "vha" 12
SCSI driver HA context
.IP "rsp" 12
response queue
.IP "pkt" 12
received packet
