.TH "qlcnic_83xx_init_mgmt_vnic" 9 "qlcnic_83xx_init_mgmt_vnic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qlcnic_83xx_init_mgmt_vnic \- 
.SH SYNOPSIS
.B "int" qlcnic_83xx_init_mgmt_vnic
.BI "(struct qlcnic_adapter *adapter "  ");"
.SH ARGUMENTS
.IP "adapter" 12
adapter structure
Management virtual NIC sets the operational mode of other vNIC's and
configures embedded switch (ESWITCH).
.SH "RETURN"
Success(0) or error code.
