.TH "qlge_update_mac_hdr_len" 9 "qlge_update_mac_hdr_len" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qlge_update_mac_hdr_len \- helper routine to update the mac header length based on vlan tags if present
.SH SYNOPSIS
.B "void" qlge_update_mac_hdr_len
.BI "(struct qlge_adapter *qdev "  ","
.BI "struct qlge_ib_mac_iocb_rsp *ib_mac_rsp "  ","
.BI "void *page "  ","
.BI "size_t *len "  ");"
.SH ARGUMENTS
.IP "qdev" 12
-- undescribed --
.IP "ib_mac_rsp" 12
-- undescribed --
.IP "page" 12
-- undescribed --
.IP "len" 12
-- undescribed --
