.TH "qmi_recv_new_server" 9 "qmi_recv_new_server" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qmi_recv_new_server \- handler of NEW_SERVER control message
.SH SYNOPSIS
.B "void" qmi_recv_new_server
.BI "(struct qmi_handle *qmi "  ","
.BI "unsigned int service "  ","
.BI "unsigned int instance "  ","
.BI "unsigned int node "  ","
.BI "unsigned int port "  ");"
.SH ARGUMENTS
.IP "qmi" 12
qmi handle
.IP "service" 12
service id of the new server
.IP "instance" 12
instance id of the new server
.IP "node" 12
node of the new server
.IP "port" 12
port of the new server
.SH "DESCRIPTION"
Calls the new_server callback to inform the client about a newly registered
server matching the currently registered service lookup.
