.TH "qp_iter_print" 9 "qp_iter_print" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
qp_iter_print \- print the qp information to seq_file
.SH SYNOPSIS
.B "void" qp_iter_print
.BI "(struct seq_file *s "  ","
.BI "struct rvt_qp_iter *iter "  ");"
.SH ARGUMENTS
.IP "s" 12
the seq_file to emit the qp information on
.IP "iter" 12
the iterator for the qp hash list
