.TH "r600_dma_ring_test" 9 "r600_dma_ring_test" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
r600_dma_ring_test \- simple async dma engine test
.SH SYNOPSIS
.B "int" r600_dma_ring_test
.BI "(struct radeon_device *rdev "  ","
.BI "struct radeon_ring *ring "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ring" 12
radeon_ring structure holding ring information
.SH "DESCRIPTION"
Test the DMA engine by writing using it to write an
value to memory. (r6xx-SI).
Returns 0 for success, error for failure.
