.TH "radeon_vce_fence_emit" 9 "radeon_vce_fence_emit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_vce_fence_emit \- add a fence command to the ring
.SH SYNOPSIS
.B "void" radeon_vce_fence_emit
.BI "(struct radeon_device *rdev "  ","
.BI "struct radeon_fence *fence "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "fence" 12
the fence
