.TH "radeon_acpi_pcie_notify_device_ready" 9 "radeon_acpi_pcie_notify_device_ready" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_acpi_pcie_notify_device_ready \- 
.SH SYNOPSIS
.B "int" radeon_acpi_pcie_notify_device_ready
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.SH "DESCRIPTION"
Executes the PCIE_DEVICE_READY_NOTIFICATION method
(all asics).
returns 0 on success, error on failure.
