.TH "radeon_ib_free" 9 "radeon_ib_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_ib_free \- free an IB (Indirect Buffer)
.SH SYNOPSIS
.B "void" radeon_ib_free
.BI "(struct radeon_device *rdev "  ","
.BI "struct radeon_ib *ib "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ib" 12
IB object to free
.SH "DESCRIPTION"
Free an IB (all asics).
