.TH "radeon_register_accessor_init" 9 "radeon_register_accessor_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_register_accessor_init \- sets up the register accessor callbacks
.SH SYNOPSIS
.B "void" radeon_register_accessor_init
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon device pointer
.SH "DESCRIPTION"
Sets up the register accessor callbacks for various register
apertures.  Not all asics have all apertures (all asics).
