.TH "radeon_asic_init" 9 "radeon_asic_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_asic_init \- register asic specific callbacks
.SH SYNOPSIS
.B "int" radeon_asic_init
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon device pointer
.SH "DESCRIPTION"
Registers the appropriate asic specific callbacks for each
chip family.  Also sets other asics specific info like the number
of crtcs and the register aperture accessors (all asics).
Returns 0 for success.
