.TH "radeon_driver_open_kms" 9 "radeon_driver_open_kms" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_driver_open_kms \- drm callback for open
.SH SYNOPSIS
.B "int" radeon_driver_open_kms
.BI "(struct drm_device *dev "  ","
.BI "struct drm_file *file_priv "  ");"
.SH ARGUMENTS
.IP "dev" 12
drm dev pointer
.IP "file_priv" 12
drm file
.SH "DESCRIPTION"
On device open, init vm on cayman+ (all asics).
Returns 0 on success, error on failure.
