.TH "radeon_irq_kms_fini" 9 "radeon_irq_kms_fini" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_irq_kms_fini \- tear down driver interrupt info
.SH SYNOPSIS
.B "void" radeon_irq_kms_fini
.BI "(struct radeon_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon device pointer
.SH "DESCRIPTION"
Tears down the work irq handlers, vblank handlers, MSIs, etc. (all asics).
