.TH "radeon_mn_unregister" 9 "radeon_mn_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_mn_unregister \- unregister a BO for notifier updates
.SH SYNOPSIS
.B "void" radeon_mn_unregister
.BI "(struct radeon_bo *bo "  ");"
.SH ARGUMENTS
.IP "bo" 12
radeon buffer object
.SH "DESCRIPTION"
Remove any registration of MMU notifier updates from the buffer object.
