.TH "radeon_ib_get" 9 "radeon_ib_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_ib_get \- request an IB (Indirect Buffer)
.SH SYNOPSIS
.B "int" radeon_ib_get
.BI "(struct radeon_device *rdev "  ","
.BI "int ring "  ","
.BI "struct radeon_ib *ib "  ","
.BI "struct radeon_vm *vm "  ","
.BI "unsigned size "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ring" 12
ring index the IB is associated with
.IP "ib" 12
IB object returned
.IP "vm" 12
requested vm
.IP "size" 12
requested IB size
.SH "DESCRIPTION"
Request an IB (all asics).  IBs are allocated using the
suballocator.
Returns 0 on success, error on failure.
