.TH "radeon_vm_frag_ptes" 9 "radeon_vm_frag_ptes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_vm_frag_ptes \- add fragment information to PTEs
.SH SYNOPSIS
.B "void" radeon_vm_frag_ptes
.BI "(struct radeon_device *rdev "  ","
.BI "struct radeon_ib *ib "  ","
.BI "uint64_t pe_start "  ","
.BI "uint64_t pe_end "  ","
.BI "uint64_t addr "  ","
.BI "uint32_t flags "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon_device pointer
.IP "ib" 12
IB for the update
.IP "pe_start" 12
first PTE to handle
.IP "pe_end" 12
last PTE to handle
.IP "addr" 12
addr those PTEs should point to
.IP "flags" 12
hw mapping flags
.SH "DESCRIPTION"
Global and local mutex must be locked!
