.TH "radeon_irq_kms_sw_irq_get_delayed" 9 "radeon_irq_kms_sw_irq_get_delayed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radeon_irq_kms_sw_irq_get_delayed \- enable software interrupt
.SH SYNOPSIS
.B "bool" radeon_irq_kms_sw_irq_get_delayed
.BI "(struct radeon_device *rdev "  ","
.BI "int ring "  ");"
.SH ARGUMENTS
.IP "rdev" 12
radeon device pointer
.IP "ring" 12
ring whose interrupt you want to enable
.SH "DESCRIPTION"
Enables the software interrupt for a specific ring (all asics).
The software interrupt is generally used to signal a fence on
a particular ring.
