.TH "radix_tree_next_chunk" 9 "radix_tree_next_chunk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
radix_tree_next_chunk \- find next chunk of slots for iteration
.SH SYNOPSIS
.B "void __rcu **" radix_tree_next_chunk
.BI "(const struct radix_tree_root *root "  ","
.BI "struct radix_tree_iter *iter "  ","
.BI "unsigned flags "  ");"
.SH ARGUMENTS
.IP "root" 12
radix tree root
.IP "iter" 12
iterator state
.IP "flags" 12
RADIX_TREE_ITER_* flags and tag index
.SH "RETURN"
pointer to chunk first slot, or NULL if iteration is over
