.TH "rc_validate_scancode" 9 "rc_validate_scancode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rc_validate_scancode \- checks that a scancode is valid for a protocol. For nec, it should do the opposite of ir_nec_bytes_to_scancode()
.SH SYNOPSIS
.B "bool" rc_validate_scancode
.BI "(enum rc_proto proto "  ","
.BI "u32 scancode "  ");"
.SH ARGUMENTS
.IP "proto" 12
protocol
.IP "scancode" 12
scancode
