.TH "rcu_is_watching" 9 "rcu_is_watching" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rcu_is_watching \- see if RCU thinks that the current CPU is not idle
.SH SYNOPSIS
.B "notrace bool" rcu_is_watching
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Return true if RCU is watching the running CPU, which means that this
CPU can safely enter RCU read-side critical sections.  In other words,
if the current CPU is not in its idle loop or is in an interrupt or
NMI handler, return true.

Make notrace because it can be called by the internal functions of
ftrace, and making this notrace removes unnecessary recursion calls.
