.TH "rdma_user_mmap_entry_get" 9 "rdma_user_mmap_entry_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rdma_user_mmap_entry_get \- Get an entry from the mmap_xa
.SH SYNOPSIS
.B "struct rdma_user_mmap_entry *" rdma_user_mmap_entry_get
.BI "(struct ib_ucontext *ucontext "  ","
.BI "struct vm_area_struct *vma "  ");"
.SH ARGUMENTS
.IP "ucontext" 12
associated user context
.IP "vma" 12
the vma being mmap'd into
.SH "DESCRIPTION"
This function is like \fBrdma_user_mmap_entry_get_pgoff\fP except that it also
checks that the VMA is correct.
