.TH "rdma_create_trans" 9 "rdma_create_trans" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rdma_create_trans \- Transport method for creating a transport instance
.SH SYNOPSIS
.B "int" rdma_create_trans
.BI "(struct p9_client *client "  ","
.BI "const char *addr "  ","
.BI "char *args "  ");"
.SH ARGUMENTS
.IP "client" 12
client instance
.IP "addr" 12
IP address string
.IP "args" 12
Mount options string
