.TH "read_mod_write" 9 "read_mod_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
read_mod_write \- Calculate the IRQ register index and set/clear the bits
.SH SYNOPSIS
.B "void" read_mod_write
.BI "(struct hfi1_devdata *dd "  ","
.BI "u16 src "  ","
.BI "u64 bits "  ","
.BI "bool set "  ");"
.SH ARGUMENTS
.IP "dd" 12
valid devdata
.IP "src" 12
IRQ source to determine register index from
.IP "bits" 12
the bits to set or clear
.IP "set" 12
true == set the bits, false == clear the bits
