.TH "read_main_config_table" 9 "read_main_config_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
read_main_config_table \- read the configure table and save it.
.SH SYNOPSIS
.B "void" read_main_config_table
.BI "(struct pm8001_hba_info *pm8001_ha "  ");"
.SH ARGUMENTS
.IP "pm8001_ha" 12
our hba card information
