.TH "read_bbt" 9 "read_bbt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
read_bbt \- [GENERIC] Read the bad block table starting from page
.SH SYNOPSIS
.B "int" read_bbt
.BI "(struct nand_chip *this "  ","
.BI "uint8_t *buf "  ","
.BI "int page "  ","
.BI "int num "  ","
.BI "struct nand_bbt_descr *td "  ","
.BI "int offs "  ");"
.SH ARGUMENTS
.IP "this" 12
NAND chip object
.IP "buf" 12
temporary buffer
.IP "page" 12
the starting page
.IP "num" 12
the number of bbt descriptors to read
.IP "td" 12
the bbt describtion table
.IP "offs" 12
block number offset in the table
.SH "DESCRIPTION"
Read the bad block table starting from page.
