.TH "read_sysfs_string" 9 "read_sysfs_string" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
read_sysfs_string \- read a string from file
.SH SYNOPSIS
.B "int" read_sysfs_string
.BI "(const char *filename "  ","
.BI "const char *basedir "  ","
.BI "char *str "  ");"
.SH ARGUMENTS
.IP "filename" 12
name of file to read from
.IP "basedir" 12
the sysfs directory in which the file is to be found
.IP "str" 12
output the read string
.SH "DESCRIPTION"
Returns a value >= 0 on success, otherwise a negative error code.
