.TH "recv_ishtp_cl_msg" 9 "recv_ishtp_cl_msg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
recv_ishtp_cl_msg \- Receive client message
.SH SYNOPSIS
.B "void" recv_ishtp_cl_msg
.BI "(struct ishtp_device *dev "  ","
.BI "struct ishtp_msg_hdr *ishtp_hdr "  ");"
.SH ARGUMENTS
.IP "dev" 12
ISHTP device instance
.IP "ishtp_hdr" 12
Pointer to message header
.SH "DESCRIPTION"
Receive and dispatch ISHTP client messages. This function executes in ISR
or work queue context
