.TH "recycle_rx_buf" 9 "recycle_rx_buf" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
recycle_rx_buf \- recycle a receive buffer
.SH SYNOPSIS
.B "void" recycle_rx_buf
.BI "(struct adapter *adap "  ","
.BI "struct sge_fl *q "  ","
.BI "unsigned int idx "  ");"
.SH ARGUMENTS
.IP "adap" 12
the adapter
.IP "q" 12
the SGE free list
.IP "idx" 12
index of buffer to recycle

Recycles the specified buffer on the given free list by adding it at
the next available slot on the list.
