.TH "regcache_read" 9 "regcache_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regcache_read \- Fetch the value of a given register from the cache.
.SH SYNOPSIS
.B "int" regcache_read
.BI "(struct regmap *map "  ","
.BI "unsigned int reg "  ","
.BI "unsigned int *value "  ");"
.SH ARGUMENTS
.IP "map" 12
map to configure.
.IP "reg" 12
The register index.
.IP "value" 12
The value to be returned.
.SH "DESCRIPTION"
Return a negative value on failure, 0 on success.
