.TH "regs_get_kernel_stack_nth" 9 "regs_get_kernel_stack_nth" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regs_get_kernel_stack_nth \- get Nth entry of the stack
.SH SYNOPSIS
.B "unsigned long" regs_get_kernel_stack_nth
.BI "(struct pt_regs *regs "  ","
.BI "unsigned int n "  ");"
.SH ARGUMENTS
.IP "regs" 12
pt_regs which contains kernel stack pointer.
.IP "n" 12
stack entry number.
.SH "DESCRIPTION"
\fBregs_get_kernel_stack_nth\fP returns \fIn\fP th entry of the kernel stack which
is specified by \fIregs\fP. If the \fIn\fP th entry is NOT in the kernel stack,
this returns 0.
