.TH "regulator_map_voltage_ascend" 9 "regulator_map_voltage_ascend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regulator_map_voltage_ascend \- map_voltage() for ascendant voltage list
.SH SYNOPSIS
.B "int" regulator_map_voltage_ascend
.BI "(struct regulator_dev *rdev "  ","
.BI "int min_uV "  ","
.BI "int max_uV "  ");"
.SH ARGUMENTS
.IP "rdev" 12
Regulator to operate on
.IP "min_uV" 12
Lower bound for voltage
.IP "max_uV" 12
Upper bound for voltage
.SH "DESCRIPTION"
Drivers that have ascendant voltage list can use this as their
\fBmap_voltage\fP operation.
