.TH "regulator_set_voltage_sel_pickable_regmap" 9 "regulator_set_voltage_sel_pickable_regmap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regulator_set_voltage_sel_pickable_regmap \- pickable range set_voltage_sel
.SH SYNOPSIS
.B "int" regulator_set_voltage_sel_pickable_regmap
.BI "(struct regulator_dev *rdev "  ","
.BI "unsigned int sel "  ");"
.SH ARGUMENTS
.IP "rdev" 12
regulator to operate on
.IP "sel" 12
Selector to set
.SH "DESCRIPTION"
Regulators that use regmap for their register I/O and use pickable
ranges can set the vsel_reg, vsel_mask, vsel_range_reg and vsel_range_mask
fields in their descriptor and then use this as their set_voltage_vsel
operation, saving some code.
