.TH "regulator_bulk_register_supply_alias" 9 "regulator_bulk_register_supply_alias" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regulator_bulk_register_supply_alias \- register multiple aliases
.SH SYNOPSIS
.B "int" regulator_bulk_register_supply_alias
.BI "(struct device *dev "  ","
.BI "const char *const *id "  ","
.BI "struct device *alias_dev "  ","
.BI "const char *const *alias_id "  ","
.BI "int num_id "  ");"
.SH ARGUMENTS
.IP "dev" 12
device that will be given as the regulator "consumer"
.IP "id" 12
List of supply names or regulator IDs
.IP "alias_dev" 12
device that should be used to lookup the supply
.IP "alias_id" 12
List of supply names or regulator IDs that should be used to
lookup the supply
.IP "num_id" 12
Number of aliases to register
.SH "DESCRIPTION"
\fIreturn\fP 0 on success, an errno on failure.

This helper function allows drivers to register several supply
aliases in one operation.  If any of the aliases cannot be
registered any aliases that were registered will be removed
before returning to the caller.
