.TH "regulator_register" 9 "regulator_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regulator_register \- register regulator
.SH SYNOPSIS
.B "struct regulator_dev *" regulator_register
.BI "(const struct regulator_desc *regulator_desc "  ","
.BI "const struct regulator_config *cfg "  ");"
.SH ARGUMENTS
.IP "regulator_desc" 12
regulator to register
.IP "cfg" 12
runtime configuration for regulator
.SH "DESCRIPTION"
Called by regulator drivers to register a regulator.
Returns a valid pointer to struct regulator_dev on success
or an \fBERR_PTR\fP on error.
