.TH "regulator_get_linear_step" 9 "regulator_get_linear_step" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
regulator_get_linear_step \- return the voltage step size between VSEL values
.SH SYNOPSIS
.B "unsigned int" regulator_get_linear_step
.BI "(struct regulator *regulator "  ");"
.SH ARGUMENTS
.IP "regulator" 12
regulator source
.SH "DESCRIPTION"
Returns the voltage step size between VSEL values for linear
regulators, or return 0 if the regulator isn't a linear regulator.
