.TH "remap_io_mapping" 9 "remap_io_mapping" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
remap_io_mapping \- remap an IO mapping to userspace
.SH SYNOPSIS
.B "int" remap_io_mapping
.BI "(struct vm_area_struct *vma "  ","
.BI "unsigned long addr "  ","
.BI "unsigned long pfn "  ","
.BI "unsigned long size "  ","
.BI "struct io_mapping *iomap "  ");"
.SH ARGUMENTS
.IP "vma" 12
user vma to map to
.IP "addr" 12
target user address to start at
.IP "pfn" 12
physical address of kernel memory
.IP "size" 12
size of map area
.IP "iomap" 12
the source io_mapping
.SH "NOTE"
this is only safe if the mm semaphore is held when called.
