.TH "rename_volumes" 9 "rename_volumes" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rename_volumes \- rename UBI volumes.
.SH SYNOPSIS
.B "int" rename_volumes
.BI "(struct ubi_device *ubi "  ","
.BI "struct ubi_rnvol_req *req "  ");"
.SH ARGUMENTS
.IP "ubi" 12
UBI device description object
.IP "req" 12
volumes re-name request
.SH "DESCRIPTION"
This is a helper function for the volume re-name IOCTL which validates the
the request, opens the volume and calls corresponding volumes management
function. Returns zero in case of success and a negative error code in case
of failure.
