.TH "replay_bud" 9 "replay_bud" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
replay_bud \- replay a bud logical eraseblock.
.SH SYNOPSIS
.B "int" replay_bud
.BI "(struct ubifs_info *c "  ","
.BI "struct bud_entry *b "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "b" 12
bud entry which describes the bud
.SH "DESCRIPTION"
This function replays bud \fIbud\fP, recovers it if needed, and adds all nodes
from this bud to the replay list. Returns zero in case of success and a
negative error code in case of failure.
