.TH "reset_select_slave" 9 "reset_select_slave" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
reset_select_slave \- reset and select a slave
.SH SYNOPSIS
.B "int" reset_select_slave
.BI "(struct w1_slave *sl "  ");"
.SH ARGUMENTS
.IP "sl" 12
the slave to select
.SH "DESCRIPTION"
Resets the bus and select the slave by sending a ROM MATCH cmd
\fBw1_reset_select_slave\fP from w1_io.c could not be used here because
it sent a SKIP ROM command if only one device is on the line.
At the beginning of the such process, sl->master->slave_count is 1 even if
more devices are on the line, causing collision on the line.
.SH "CONTEXT"
The w1 master lock must be held.
.SH "RETURN"
0 if success, negative kernel error code otherwise.
