.TH "reset_bios_show" 9 "reset_bios_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
reset_bios_show \- sysfs implementaton for read reset_bios
.SH SYNOPSIS
.B "ssize_t" reset_bios_show
.BI "(struct kobject *kobj "  ","
.BI "struct kobj_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "kobj" 12
Kernel object for this attribute
.IP "attr" 12
Kernel object attribute
.IP "buf" 12
The buffer to display to userspace
