.TH "restart_ctrlq" 9 "restart_ctrlq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
restart_ctrlq \- restart a suspended control queue
.SH SYNOPSIS
.B "void" restart_ctrlq
.BI "(struct tasklet_struct *t "  ");"
.SH ARGUMENTS
.IP "t" 12
pointer to the tasklet associated with this handler

Resumes transmission on a suspended Tx control queue.
