.TH "rhine_set_vlan_cam" 9 "rhine_set_vlan_cam" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rhine_set_vlan_cam \- set CAM VLAN filters
.SH SYNOPSIS
.B "void" rhine_set_vlan_cam
.BI "(void __iomem *ioaddr "  ","
.BI "int idx "  ","
.BI "u8 *addr "  ");"
.SH ARGUMENTS
.IP "ioaddr" 12
register block of this Rhine
.IP "idx" 12
VLAN CAM index [0..VCAM_SIZE-1]
.IP "addr" 12
VLAN ID (2 bytes)
.SH "DESCRIPTION"
Load addresses into VLAN filters.
