.TH "ring_buffer_record_on" 9 "ring_buffer_record_on" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ring_buffer_record_on \- restart writes into the buffer
.SH SYNOPSIS
.B "void" ring_buffer_record_on
.BI "(struct trace_buffer *buffer "  ");"
.SH ARGUMENTS
.IP "buffer" 12
The ring buffer to start writes to.
.SH "DESCRIPTION"
This enables all writes to the buffer that was disabled by
\fBring_buffer_record_off\fP.

This is different than \fBring_buffer_record_enable\fP as
it works like an on/off switch, where as the \fBenable\fP version
must be paired with a \fBdisable\fP.
