.TH "rio_register_driver" 9 "rio_register_driver" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rio_register_driver \- register a new RIO driver
.SH SYNOPSIS
.B "int" rio_register_driver
.BI "(struct rio_driver *rdrv "  ");"
.SH ARGUMENTS
.IP "rdrv" 12
the RIO driver structure to register

Adds a \fIstruct rio_driver\fP to the list of registered drivers.
Returns a negative value on error, otherwise 0. If no error
occurred, the driver remains registered even if no device
was claimed during registration.
