.TH "rio_dma_prep_xfer" 9 "rio_dma_prep_xfer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rio_dma_prep_xfer \- RapidIO specific wrapper for device_prep_slave_sg callback defined by DMAENGINE.
.SH SYNOPSIS
.B "struct dma_async_tx_descriptor *" rio_dma_prep_xfer
.BI "(struct dma_chan *dchan "  ","
.BI "u16 destid "  ","
.BI "struct rio_dma_data *data "  ","
.BI "enum dma_transfer_direction direction "  ","
.BI "unsigned long flags "  ");"
.SH ARGUMENTS
.IP "dchan" 12
DMA channel to configure
.IP "destid" 12
target RapidIO device destination ID
.IP "data" 12
RIO specific data descriptor
.IP "direction" 12
DMA data transfer direction (TO or FROM the device)
.IP "flags" 12
dmaengine defined flags
.SH "DESCRIPTION"
Initializes RapidIO capable DMA channel for the specified data transfer.
Uses DMA channel private extension to pass information related to remote
target RIO device.
.SH "RETURN"
pointer to DMA transaction descriptor if successful,
error-valued pointer or NULL if failed.
