.TH "rio_match_bus" 9 "rio_match_bus" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rio_match_bus \- Tell if a RIO device structure has a matching RIO driver device id structure
.SH SYNOPSIS
.B "int" rio_match_bus
.BI "(struct device *dev "  ","
.BI "struct device_driver *drv "  ");"
.SH ARGUMENTS
.IP "dev" 12
the standard device structure to match against
.IP "drv" 12
the standard driver structure containing the ids to match against

Used by a driver to check whether a RIO device present in the
system is in its list of supported devices. Returns 1 if
there is a matching \fIstruct rio_device_id\fP or 0 if there is
no match.
