.TH "rio_enum_peer" 9 "rio_enum_peer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rio_enum_peer \- Recursively enumerate a RIO network through a master port
.SH SYNOPSIS
.B "int" rio_enum_peer
.BI "(struct rio_net *net "  ","
.BI "struct rio_mport *port "  ","
.BI "u8 hopcount "  ","
.BI "struct rio_dev *prev "  ","
.BI "int prev_port "  ");"
.SH ARGUMENTS
.IP "net" 12
RIO network being enumerated
.IP "port" 12
Master port to send transactions
.IP "hopcount" 12
Number of hops into the network
.IP "prev" 12
Previous RIO device connected to the enumerated one
.IP "prev_port" 12
Port on previous RIO device
.SH "DESCRIPTION"
Recursively enumerates a RIO network.  Transactions are sent via the
master port passed in \fIport\fP.
