.TH "rio_add_device" 9 "rio_add_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rio_add_device \- Adds a RIO device to the device model
.SH SYNOPSIS
.B "int" rio_add_device
.BI "(struct rio_dev *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
RIO device
.SH "DESCRIPTION"
Adds the RIO device to the global device list and adds the RIO
device to the RIO device list.  Creates the generic sysfs nodes
for an RIO device.
