.TH "rio_release_inb_pwrite" 9 "rio_release_inb_pwrite" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rio_release_inb_pwrite \- release inbound port-write message service associated with specific RapidIO device
.SH SYNOPSIS
.B "int" rio_release_inb_pwrite
.BI "(struct rio_dev *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
RIO device which registered for inbound port-write callback
.SH "DESCRIPTION"
Removes callback from the rio_dev structure. Returns 0 if the request
has been satisfied.
