.TH "rmi_unregister_function_handler" 9 "rmi_unregister_function_handler" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rmi_unregister_function_handler \- unregister given RMI function handler
.SH SYNOPSIS
.B "void" rmi_unregister_function_handler
.BI "(struct rmi_function_handler *handler "  ");"
.SH ARGUMENTS
.IP "handler" 12
RMI handler that should be unregistered.
.SH "DESCRIPTION"
This function unregisters given function handler from RMI core which
causes it to be unbound from the function devices.
