.TH "rmi_driver_set_input_params" 9 "rmi_driver_set_input_params" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rmi_driver_set_input_params \- set input device id and other data.
.SH SYNOPSIS
.B "int" rmi_driver_set_input_params
.BI "(struct rmi_device *rmi_dev "  ","
.BI "struct input_dev *input "  ");"
.SH ARGUMENTS
.IP "rmi_dev" 12
Pointer to an RMI device
.IP "input" 12
Pointer to input device
