.TH "rpc_pton" 9 "rpc_pton" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpc_pton \- Construct a sockaddr in @sap
.SH SYNOPSIS
.B "size_t" rpc_pton
.BI "(struct net *net "  ","
.BI "const char *buf "  ","
.BI "const size_t buflen "  ","
.BI "struct sockaddr *sap "  ","
.BI "const size_t salen "  ");"
.SH ARGUMENTS
.IP "net" 12
applicable network namespace
.IP "buf" 12
C string containing presentation format IP address
.IP "buflen" 12
length of presentation address in bytes
.IP "sap" 12
buffer into which to plant socket address
.IP "salen" 12
size of buffer in bytes
.SH "DESCRIPTION"
Returns the size of the socket address if successful; otherwise
zero is returned.

Plants a socket address in \fIsap\fP and returns the size of the
socket address, if successful.  Returns zero if an error
occurred.
