.TH "rpc_init_pipe_dir_head" 9 "rpc_init_pipe_dir_head" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpc_init_pipe_dir_head \- initialise a struct rpc_pipe_dir_head
.SH SYNOPSIS
.B "void" rpc_init_pipe_dir_head
.BI "(struct rpc_pipe_dir_head *pdh "  ");"
.SH ARGUMENTS
.IP "pdh" 12
pointer to struct rpc_pipe_dir_head
