.TH "rpcauth_unwrap_resp_decode" 9 "rpcauth_unwrap_resp_decode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpcauth_unwrap_resp_decode \- Invoke XDR decode function
.SH SYNOPSIS
.B "int" rpcauth_unwrap_resp_decode
.BI "(struct rpc_task *task "  ","
.BI "struct xdr_stream *xdr "  ");"
.SH ARGUMENTS
.IP "task" 12
controlling RPC task
.IP "xdr" 12
stream where the Reply message resides
.SH "DESCRIPTION"
Returns zero on success; otherwise a negative errno is returned.
