.TH "rpcauth_wrap_req_encode" 9 "rpcauth_wrap_req_encode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpcauth_wrap_req_encode \- XDR encode the RPC procedure
.SH SYNOPSIS
.B "int" rpcauth_wrap_req_encode
.BI "(struct rpc_task *task "  ","
.BI "struct xdr_stream *xdr "  ");"
.SH ARGUMENTS
.IP "task" 12
controlling RPC task
.IP "xdr" 12
stream where on-the-wire bytes are to be marshalled
.SH "DESCRIPTION"
On success, \fIxdr\fP contains the encoded and wrapped message.
Otherwise, \fIxdr\fP is in an undefined state.
