.TH "rpm_callback" 9 "rpm_callback" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpm_callback \- Run a given runtime PM callback for a given device.
.SH SYNOPSIS
.B "int" rpm_callback
.BI "(int (*cb)(struct device *) "  ","
.BI "struct device *dev "  ");"
.SH ARGUMENTS
.IP "cb" 12
Runtime PM callback to run.
.IP "dev" 12
Device to run the callback for.
