.TH "rpmh_flush" 9 "rpmh_flush" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rpmh_flush \- Flushes the buffered sleep and wake sets to TCSes
.SH SYNOPSIS
.B "int" rpmh_flush
.BI "(struct rpmh_ctrlr *ctrlr "  ");"
.SH ARGUMENTS
.IP "ctrlr" 12
Controller making request to flush cached data
.SH "RETURN"
* 0          - Success
* Error code - Otherwise
