.TH "rproc_alloc_carveout" 9 "rproc_alloc_carveout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rproc_alloc_carveout \- allocated specified carveout
.SH SYNOPSIS
.B "int" rproc_alloc_carveout
.BI "(struct rproc *rproc "  ","
.BI "struct rproc_mem_entry *mem "  ");"
.SH ARGUMENTS
.IP "rproc" 12
rproc handle
.IP "mem" 12
the memory entry to allocate
.SH "DESCRIPTION"
This function allocate specified memory entry \fImem\fP using
\fBdma_alloc_coherent\fP as default allocator
