.TH "rproc_elf_get_boot_addr" 9 "rproc_elf_get_boot_addr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rproc_elf_get_boot_addr \- Get rproc's boot address.
.SH SYNOPSIS
.B "u64" rproc_elf_get_boot_addr
.BI "(struct rproc *rproc "  ","
.BI "const struct firmware *fw "  ");"
.SH ARGUMENTS
.IP "rproc" 12
the remote processor handle
.IP "fw" 12
the ELF firmware image
.SH "DESCRIPTION"
This function returns the entry point address of the ELF
image.

Note that the boot address is not a configurable property of all remote
processors. Some will always boot at a specific hard-coded address.
