.TH "rproc_elf_load_rsc_table" 9 "rproc_elf_load_rsc_table" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rproc_elf_load_rsc_table \- load the resource table
.SH SYNOPSIS
.B "int" rproc_elf_load_rsc_table
.BI "(struct rproc *rproc "  ","
.BI "const struct firmware *fw "  ");"
.SH ARGUMENTS
.IP "rproc" 12
the rproc handle
.IP "fw" 12
the ELF firmware image
.SH "DESCRIPTION"
This function finds the resource table inside the remote processor's
firmware, load it into the \fIcached_table\fP and update \fItable_ptr\fP.
.SH "RETURN"
0 on success, negative errno on failure.
