.TH "rsi_tx_scheduler_thread" 9 "rsi_tx_scheduler_thread" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_tx_scheduler_thread \- This function is a kernel thread to send the packets to the device.
.SH SYNOPSIS
.B "void" rsi_tx_scheduler_thread
.BI "(struct rsi_common *common "  ");"
.SH ARGUMENTS
.IP "common" 12
Pointer to the driver private structure.
.SH "RETURN"
None.
