.TH "rsi_cmd52writebyte" 9 "rsi_cmd52writebyte" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_cmd52writebyte \- This function issues cmd52 byte write onto the card.
.SH SYNOPSIS
.B "int" rsi_cmd52writebyte
.BI "(struct mmc_card *card "  ","
.BI "u32 address "  ","
.BI "u8 byte "  ");"
.SH ARGUMENTS
.IP "card" 12
Pointer to the mmc_card.
.IP "address" 12
Address to write.
.IP "byte" 12
Data to write.
.SH "RETURN"
Write status.
