.TH "rsi_get_num_pkts_dequeue" 9 "rsi_get_num_pkts_dequeue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_get_num_pkts_dequeue \- This function determines the number of packets to be dequeued based on the number of bytes calculated using txop.
.SH SYNOPSIS
.B "u32" rsi_get_num_pkts_dequeue
.BI "(struct rsi_common *common "  ","
.BI "u8 q_num "  ");"
.SH ARGUMENTS
.IP "common" 12
Pointer to the driver private structure.
.IP "q_num" 12
the queue from which pkts have to be dequeued
.SH "RETURN"
pkt_num: Number of pkts to be dequeued.
