.TH "rsi_load_radio_caps" 9 "rsi_load_radio_caps" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_load_radio_caps \- This function is used to send radio capabilities values to firmware.
.SH SYNOPSIS
.B "int" rsi_load_radio_caps
.BI "(struct rsi_common *common "  ");"
.SH ARGUMENTS
.IP "common" 12
Pointer to the driver private structure.
.SH "RETURN"
0 on success, corresponding negative error code on failure.
