.TH "rsi_reset_card" 9 "rsi_reset_card" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_reset_card \- This function resets and re-initializes the card.
.SH SYNOPSIS
.B "void" rsi_reset_card
.BI "(struct sdio_func *pfunction "  ");"
.SH ARGUMENTS
.IP "pfunction" 12
Pointer to the sdio_func structure.
.SH "RETURN"
None.
