.TH "rsi_mac80211_set_key" 9 "rsi_mac80211_set_key" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rsi_mac80211_set_key \- This function sets type of key to be loaded.
.SH SYNOPSIS
.B "int" rsi_mac80211_set_key
.BI "(struct ieee80211_hw *hw "  ","
.BI "enum set_key_cmd cmd "  ","
.BI "struct ieee80211_vif *vif "  ","
.BI "struct ieee80211_sta *sta "  ","
.BI "struct ieee80211_key_conf *key "  ");"
.SH ARGUMENTS
.IP "hw" 12
Pointer to the ieee80211_hw structure.
.IP "cmd" 12
enum set_key_cmd.
.IP "vif" 12
Pointer to the ieee80211_vif structure.
.IP "sta" 12
Pointer to the ieee80211_sta structure.
.IP "key" 12
Pointer to the ieee80211_key_conf structure.
.SH "RETURN"
status: 0 on success, negative error code on failure.
