.TH "rt5677_dsp_mode_i2c_write" 9 "rt5677_dsp_mode_i2c_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rt5677_dsp_mode_i2c_write \- Write register on DSP mode.
.SH SYNOPSIS
.B "int" rt5677_dsp_mode_i2c_write
.BI "(struct rt5677_priv *rt5677 "  ","
.BI "unsigned int reg "  ","
.BI "unsigned int value "  ");"
.SH ARGUMENTS
.IP "rt5677" 12
Private Data.
.IP "reg" 12
Register index.
.IP "value" 12
Register data.
.SH "DESCRIPTION"
Returns 0 for success or negative error code.
