.TH "rtas_activate_firmware" 9 "rtas_activate_firmware" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rtas_activate_firmware \- Activate a new version of firmware.
.SH SYNOPSIS
.B "void" rtas_activate_firmware
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Activate a new version of partition firmware. The OS must call this
after resuming from a partition hibernation or migration in order
to maintain the ability to perform live firmware updates. It's not
catastrophic for this method to be absent or to fail; just log the
condition in that case.
.SH "CONTEXT"
This function may sleep.
