.TH "rtc_timer_remove" 9 "rtc_timer_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rtc_timer_remove \- Removes a rtc_timer from the rtc_device timerqueue
.SH SYNOPSIS
.B "void" rtc_timer_remove
.BI "(struct rtc_device *rtc "  ","
.BI "struct rtc_timer *timer "  ");"
.SH ARGUMENTS
.IP "rtc" 12
rtc device
.IP "timer" 12
timer being removed.
.SH "DESCRIPTION"
Removes a timer onto the rtc devices timerqueue and sets
the next alarm event appropriately.

Clears the enabled bit on the removed timer.

Must hold ops_lock for proper serialization of timerqueue
