.TH "rtrs_addr_to_sockaddr" 9 "rtrs_addr_to_sockaddr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rtrs_addr_to_sockaddr \- convert path string "src,dst" or "src@dst" to sockaddreses
.SH SYNOPSIS
.B "int" rtrs_addr_to_sockaddr
.BI "(const char *str "  ","
.BI "size_t len "  ","
.BI "u16 port "  ","
.BI "struct rtrs_addr *addr "  ");"
.SH ARGUMENTS
.IP "str" 12
string containing source and destination addr of a path
separated by ',' or '\fI\fP' I.e. "ip:1.1.1.1,ip:1.1.1.2" or
"ip:1.1.1.1\fIip\fP:1.1.1.2". If str contains only one address it's
considered to be destination.
.IP "len" 12
string length
.IP "port" 12
Destination port number.
.IP "addr" 12
will be set to the source/destination address or to NULL
if str doesn't contain any source address.
.SH "DESCRIPTION"
Returns zero if conversion successful. Non-zero otherwise.
