.TH "rtw_get_wps_ie" 9 "rtw_get_wps_ie" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rtw_get_wps_ie \- Search WPS IE from a series of ies
.SH SYNOPSIS
.B "u8 *" rtw_get_wps_ie
.BI "(u8 *in_ie "  ","
.BI "uint in_len "  ","
.BI "u8 *wps_ie "  ","
.BI "uint *wps_ielen "  ");"
.SH ARGUMENTS
.IP "in_ie" 12
Address of ies to search
.IP "in_len" 12
Length limit from in_ie
.IP "wps_ie" 12
If not NULL and WPS IE is found, WPS IE will be copied to the buf starting from wps_ie
.IP "wps_ielen" 12
If not NULL and WPS IE is found, will set to the length of the entire WPS IE
.SH "RETURN"
The address of the WPS IE found, or NULL
