.TH "rvt_set_page" 9 "rvt_set_page" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rvt_set_page \- page assignment function called by ib_sg_to_pages
.SH SYNOPSIS
.B "int" rvt_set_page
.BI "(struct ib_mr *ibmr "  ","
.BI "u64 addr "  ");"
.SH ARGUMENTS
.IP "ibmr" 12
memory region
.IP "addr" 12
dma address of mapped page
.SH "RETURN"
0 on success
