.TH "rvt_swqe_has_lkey" 9 "rvt_swqe_has_lkey" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rvt_swqe_has_lkey \- return true if lkey is used by swqe
.SH SYNOPSIS
.B "bool" rvt_swqe_has_lkey
.BI "(struct rvt_swqe *wqe "  ","
.BI "u32 lkey "  ");"
.SH ARGUMENTS
.IP "wqe" 12
the send wqe
.IP "lkey" 12
the lkey
.SH "DESCRIPTION"
Test the swqe for using lkey
