.TH "rvt_restart_sge" 9 "rvt_restart_sge" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rvt_restart_sge \- rewind the sge state for a wqe
.SH SYNOPSIS
.B "u32" rvt_restart_sge
.BI "(struct rvt_sge_state *ss "  ","
.BI "struct rvt_swqe *wqe "  ","
.BI "u32 len "  ");"
.SH ARGUMENTS
.IP "ss" 12
the sge state pointer
.IP "wqe" 12
the wqe to rewind
.IP "len" 12
the data length from the start of the wqe in bytes
.SH "DESCRIPTION"
Returns the remaining data length.
