.TH "rvt_qp_mr_clean" 9 "rvt_qp_mr_clean" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rvt_qp_mr_clean \- clean up remote ops for lkey
.SH SYNOPSIS
.B "void" rvt_qp_mr_clean
.BI "(struct rvt_qp *qp "  ","
.BI "u32 lkey "  ");"
.SH ARGUMENTS
.IP "qp" 12
the qp
.IP "lkey" 12
the lkey that is being de-registered
.SH "DESCRIPTION"
This routine checks if the lkey is being used by
the qp.

If so, the qp is put into an error state to elminate
any references from the qp.
