.TH "rvt_dealloc_device" 9 "rvt_dealloc_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
rvt_dealloc_device \- deallocate rdi
.SH SYNOPSIS
.B "void" rvt_dealloc_device
.BI "(struct rvt_dev_info *rdi "  ");"
.SH ARGUMENTS
.IP "rdi" 12
structure to free
.SH "DESCRIPTION"
Free a structure allocated with \fBrvt_alloc_device\fP
