.TH "s2io_ethtool_setpause_data" 9 "s2io_ethtool_setpause_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s2io_ethtool_setpause_data \- set/reset pause frame generation.
.SH SYNOPSIS
.B "int" s2io_ethtool_setpause_data
.BI "(struct net_device *dev "  ","
.BI "struct ethtool_pauseparam *ep "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to netdev
.IP "ep" 12
pointer to the structure with pause parameters given by ethtool.
.SH "DESCRIPTION"
It can be used to set or reset Pause frame generation or reception
support of the NIC.
Return value:
int, returns 0 on Success
