.TH "s3c24xx_spi_initfiq" 9 "s3c24xx_spi_initfiq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c24xx_spi_initfiq \- setup the information for the FIQ core
.SH SYNOPSIS
.B "void" s3c24xx_spi_initfiq
.BI "(struct s3c24xx_spi *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware state.
.SH "DESCRIPTION"
Setup the fiq_handler block to pass to the FIQ core.
