.TH "s3c2412_print_timing" 9 "s3c2412_print_timing" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c2412_print_timing \- print timing information via printk.
.SH SYNOPSIS
.B "void" s3c2412_print_timing
.BI "(const char *pfx "  ","
.BI "struct s3c_iotimings *iot "  ");"
.SH ARGUMENTS
.IP "pfx" 12
The prefix to print each line with.
.IP "iot" 12
The IO timing information
