.TH "s3c_fb_align_word" 9 "s3c_fb_align_word" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c_fb_align_word \- align pixel count to word boundary
.SH SYNOPSIS
.B "int" s3c_fb_align_word
.BI "(unsigned int bpp "  ","
.BI "unsigned int pix "  ");"
.SH ARGUMENTS
.IP "bpp" 12
The number of bits per pixel
.IP "pix" 12
The value to be aligned.
.SH "DESCRIPTION"
Align the given pixel count so that it will start on an 32bit word
boundary.
