.TH "s3c_fb_alloc_memory" 9 "s3c_fb_alloc_memory" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c_fb_alloc_memory \- allocate display memory for framebuffer window
.SH SYNOPSIS
.B "int" s3c_fb_alloc_memory
.BI "(struct s3c_fb *sfb "  ","
.BI "struct s3c_fb_win *win "  ");"
.SH ARGUMENTS
.IP "sfb" 12
The base resources for the hardware.
.IP "win" 12
The window to initialise memory for.
.SH "DESCRIPTION"
Allocate memory for the given framebuffer.
