.TH "s3c_fb_blank" 9 "s3c_fb_blank" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s3c_fb_blank \- blank or unblank the given window
.SH SYNOPSIS
.B "int" s3c_fb_blank
.BI "(int blank_mode "  ","
.BI "struct fb_info *info "  ");"
.SH ARGUMENTS
.IP "blank_mode" 12
The blank state from FB_BLANK_*
.IP "info" 12
The framebuffer to blank.
.SH "DESCRIPTION"
Framebuffer layer request to change the power state.
