.TH "s5p_hash_handle_queue" 9 "s5p_hash_handle_queue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
s5p_hash_handle_queue \- handle hash queue
.SH SYNOPSIS
.B "int" s5p_hash_handle_queue
.BI "(struct s5p_aes_dev *dd "  ","
.BI "struct ahash_request *req "  ");"
.SH ARGUMENTS
.IP "dd" 12
device s5p_aes_dev
.IP "req" 12
AHASH request
.SH "DESCRIPTION"
If req!=NULL enqueue it on dd->queue, if FLAGS_BUSY is not set on the
device then processes the first request from the dd->queue
.SH "RETURN"
see s5p_hash_final below.
