.TH "san_dgpu_notifier_register" 9 "san_dgpu_notifier_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
san_dgpu_notifier_register \- Register a SAN dGPU notifier.
.SH SYNOPSIS
.B "int" san_dgpu_notifier_register
.BI "(struct notifier_block *nb "  ");"
.SH ARGUMENTS
.IP "nb" 12
The notifier-block to register.
.SH "DESCRIPTION"
Registers a SAN dGPU notifier, receiving any new SAN dGPU events sent from
ACPI. The registered notifier will be called with \fIstruct san_dgpu_event\fP
as notifier data and the command ID of that event as notifier action.
