.TH "sas_init_disc" 9 "sas_init_disc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sas_init_disc \- initialize the discovery struct in the port
.SH SYNOPSIS
.B "void" sas_init_disc
.BI "(struct sas_discovery *disc "  ","
.BI "struct asd_sas_port *port "  ");"
.SH ARGUMENTS
.IP "disc" 12
port discovery structure
.IP "port" 12
pointer to struct port
.SH "DESCRIPTION"
Called when the ports are being initialized.
