.TH "sas_phy_free" 9 "sas_phy_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sas_phy_free \- free a SAS PHY
.SH SYNOPSIS
.B "void" sas_phy_free
.BI "(struct sas_phy *phy "  ");"
.SH ARGUMENTS
.IP "phy" 12
SAS PHY to free
.SH "DESCRIPTION"
Frees the specified SAS PHY.
.SH "NOTE"
This function must only be called on a PHY that has not
successfully been added using \fBsas_phy_add\fP.
