.TH "sas_address_show" 9 "sas_address_show" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sas_address_show \- sas address
.SH SYNOPSIS
.B "ssize_t" sas_address_show
.BI "(struct device *dev "  ","
.BI "struct device_attribute *attr "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "dev" 12
pointer to embedded class device
.IP "attr" 12
?
.IP "buf" 12
the buffer returned
.SH "DESCRIPTION"
This is the sas address for the target

A sysfs 'read-only' shost attribute.
