.TH "sata_scr_valid" 9 "sata_scr_valid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sata_scr_valid \- test whether SCRs are accessible
.SH SYNOPSIS
.B "int" sata_scr_valid
.BI "(struct ata_link *link "  ");"
.SH ARGUMENTS
.IP "link" 12
ATA link to test SCR accessibility for

Test whether SCRs are accessible for \fIlink\fP.

LOCKING:
None.
.SH "RETURN"
1 if SCRs are accessible, 0 otherwise.
