.TH "sata_pmp_read_gscr" 9 "sata_pmp_read_gscr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sata_pmp_read_gscr \- read GSCR block of SATA PMP
.SH SYNOPSIS
.B "int" sata_pmp_read_gscr
.BI "(struct ata_device *dev "  ","
.BI "u32 *gscr "  ");"
.SH ARGUMENTS
.IP "dev" 12
PMP device
.IP "gscr" 12
buffer to read GSCR block into

Read selected PMP GSCRs from the PMP at \fIdev\fP.  This will serve
as configuration and identification info for the PMP.

LOCKING:
Kernel thread context (may sleep).
.SH "RETURN"
0 on success, -errno on failure.
