.TH "sb_permission" 9 "sb_permission" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sb_permission \- Check superblock-level permissions
.SH SYNOPSIS
.B "int" sb_permission
.BI "(struct super_block *sb "  ","
.BI "struct inode *inode "  ","
.BI "int mask "  ");"
.SH ARGUMENTS
.IP "sb" 12
Superblock of inode to check permission on
.IP "inode" 12
Inode to check permission on
.IP "mask" 12
Right to check for (MAY_READ, MAY_WRITE, MAY_EXEC)
.SH "DESCRIPTION"
Separate out file-system wide checks from inode-specific permission checks.
