.TH "sbi_console_putchar" 9 "sbi_console_putchar" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sbi_console_putchar \- Writes given character to the console device.
.SH SYNOPSIS
.B "void" sbi_console_putchar
.BI "(int ch "  ");"
.SH ARGUMENTS
.IP "ch" 12
The data to be written to the console.
.SH "RETURN"
None
