.TH "scan_for_leb_for_idx" 9 "scan_for_leb_for_idx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scan_for_leb_for_idx \- scan for a free LEB for the index.
.SH SYNOPSIS
.B "const struct ubifs_lprops *" scan_for_leb_for_idx
.BI "(struct ubifs_info *c "  ");"
.SH ARGUMENTS
.IP "c" 12
the UBIFS file-system description object
