.TH "scancode_to_u64" 9 "scancode_to_u64" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scancode_to_u64 \- converts scancode in &struct input_keymap_entry
.SH SYNOPSIS
.B "int" scancode_to_u64
.BI "(const struct input_keymap_entry *ke "  ","
.BI "u64 *scancode "  ");"
.SH ARGUMENTS
.IP "ke" 12
keymap entry containing scancode to be converted.
.IP "scancode" 12
pointer to the location where converted scancode should
be stored.
.SH "DESCRIPTION"
This function is a version of input_scancode_to_scalar specialized for
rc-core.
