.TH "sci_remote_device_construct" 9 "sci_remote_device_construct" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sci_remote_device_construct \- common construction
.SH SYNOPSIS
.B "void" sci_remote_device_construct
.BI "(struct isci_port *iport "  ","
.BI "struct isci_remote_device *idev "  ");"
.SH ARGUMENTS
.IP "iport" 12
-- undescribed --
.IP "idev" 12
-- undescribed --
.SH "DESCRIPTION"
This routine just performs benign initialization and does not
allocate the remote_node_context which is left to
sci_remote_device_[de]\fBa_construct\fP.  \fBsci_remote_device_destruct\fP
frees the remote_node_context(s) for the device.
