.TH "scmi_dump_header_dbg" 9 "scmi_dump_header_dbg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scmi_dump_header_dbg \- Helper to dump a message header.
.SH SYNOPSIS
.B "void" scmi_dump_header_dbg
.BI "(struct device *dev "  ","
.BI "struct scmi_msg_hdr *hdr "  ");"
.SH ARGUMENTS
.IP "dev" 12
Device pointer corresponding to the SCMI entity
.IP "hdr" 12
pointer to header.
