.TH "scmi_reset_assert" 9 "scmi_reset_assert" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scmi_reset_assert \- assert device reset
.SH SYNOPSIS
.B "int" scmi_reset_assert
.BI "(struct reset_controller_dev *rcdev "  ","
.BI "unsigned long id "  ");"
.SH ARGUMENTS
.IP "rcdev" 12
reset controller entity
.IP "id" 12
ID of the reset to be asserted
.SH "DESCRIPTION"
This function implements the reset driver op to assert a device's reset
using the ARM SCMI protocol.
.SH "RETURN"
0 for successful request, else a corresponding error value
