.TH "scmi_base_attributes_get" 9 "scmi_base_attributes_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scmi_base_attributes_get \- gets the implementation details that are associated with the base protocol.
.SH SYNOPSIS
.B "int" scmi_base_attributes_get
.BI "(const struct scmi_handle *handle "  ");"
.SH ARGUMENTS
.IP "handle" 12
SCMI entity handle
.SH "RETURN"
0 on success, else appropriate SCMI error.
