.TH "scsi_device_resume" 9 "scsi_device_resume" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_device_resume \- Restart user issued commands to a quiesced device.
.SH SYNOPSIS
.B "void" scsi_device_resume
.BI "(struct scsi_device *sdev "  ");"
.SH ARGUMENTS
.IP "sdev" 12
scsi device to resume.

Moves the device from quiesced back to running and restarts the
queues.

Must be called with user context, may sleep.
