.TH "scsi_check_sense" 9 "scsi_check_sense" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_check_sense \- Examine scsi cmd sense
.SH SYNOPSIS
.B "int" scsi_check_sense
.BI "(struct scsi_cmnd *scmd "  ");"
.SH ARGUMENTS
.IP "scmd" 12
Cmd to have sense checked.
.SH "DESCRIPTION"
Return value:
SUCCESS or FAILED or NEEDS_RETRY or ADD_TO_MLQUEUE
.SH "NOTES"
When a deferred error is detected the current command has
not been executed and needs retrying.
