.TH "scsi_set_sense_information" 9 "scsi_set_sense_information" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
scsi_set_sense_information \- set the information field in a formatted sense data buffer
.SH SYNOPSIS
.B "int" scsi_set_sense_information
.BI "(u8 *buf "  ","
.BI "int buf_len "  ","
.BI "u64 info "  ");"
.SH ARGUMENTS
.IP "buf" 12
Where to build sense data
.IP "buf_len" 12
buffer length
.IP "info" 12
64-bit information value to be set
.SH "DESCRIPTION"
Return value:
0 on success or -EINVAL for invalid sense buffer length
