.TH "sdio_uart_cleanup" 9 "sdio_uart_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sdio_uart_cleanup \- called on the last tty kref drop
.SH SYNOPSIS
.B "void" sdio_uart_cleanup
.BI "(struct tty_struct *tty "  ");"
.SH ARGUMENTS
.IP "tty" 12
the tty being destroyed

Called asynchronously when the last reference to the tty is dropped.
We cannot destroy the tty->driver_data port kref until this point
