.TH "sdw_release_slave_stream" 9 "sdw_release_slave_stream" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sdw_release_slave_stream \- Free Slave(s) runtime handle
.SH SYNOPSIS
.B "void" sdw_release_slave_stream
.BI "(struct sdw_slave *slave "  ","
.BI "struct sdw_stream_runtime *stream "  ");"
.SH ARGUMENTS
.IP "slave" 12
Slave handle.
.IP "stream" 12
Stream runtime handle.
.SH "DESCRIPTION"
This function is to be called with bus_lock held.
