.TH "sdw_intel_probe" 9 "sdw_intel_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sdw_intel_probe \- SoundWire Intel probe routine
.SH SYNOPSIS
.B "struct sdw_intel_ctx *" sdw_intel_probe
.BI "(struct sdw_intel_res *res "  ");"
.SH ARGUMENTS
.IP "res" 12
resource data
.SH "DESCRIPTION"
This registers a platform device for each Master handled by the controller,
and SoundWire Master and Slave devices will be created by the platform
device probe. All the information necessary is stored in the context, and
the res argument pointer can be freed after this step.
This function will be called after \fBsdw_intel_acpi_scan\fP by SOF probe.
