.TH "sdw_cdns_enable_interrupt" 9 "sdw_cdns_enable_interrupt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sdw_cdns_enable_interrupt \- Enable SDW interrupts
.SH SYNOPSIS
.B "int" sdw_cdns_enable_interrupt
.BI "(struct sdw_cdns *cdns "  ","
.BI "bool state "  ");"
.SH ARGUMENTS
.IP "cdns" 12
Cadence instance
.IP "state" 12
True if we are trying to enable interrupt.
