.TH "search_extent_mapping" 9 "search_extent_mapping" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
search_extent_mapping \- find a nearby extent map
.SH SYNOPSIS
.B "struct extent_map *" search_extent_mapping
.BI "(struct extent_map_tree *tree "  ","
.BI "u64 start "  ","
.BI "u64 len "  ");"
.SH ARGUMENTS
.IP "tree" 12
tree to lookup in
.IP "start" 12
byte offset to start the search
.IP "len" 12
length of the lookup range
.SH "DESCRIPTION"
Find and return the first extent_map struct in \fItree\fP that intersects the
[start, len] range.

If one can't be found, any nearby extent may be returned
