.TH "search_inode" 9 "search_inode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
search_inode \- search inode in the RB-tree of inodes.
.SH SYNOPSIS
.B "struct fsck_inode *" search_inode
.BI "(struct fsck_data *fsckd "  ","
.BI "ino_t inum "  ");"
.SH ARGUMENTS
.IP "fsckd" 12
FS checking information
.IP "inum" 12
inode number to search
.SH "DESCRIPTION"
This is a helper function for '\fBcheck_leaf\fP' which searches inode \fIinum\fP in
the RB-tree of inodes and returns an inode information pointer or NULL if
the inode was not found.
