.TH "sel_netnode_sid_slow" 9 "sel_netnode_sid_slow" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sel_netnode_sid_slow \- Lookup the SID of a network address using the policy
.SH SYNOPSIS
.B "int" sel_netnode_sid_slow
.BI "(void *addr "  ","
.BI "u16 family "  ","
.BI "u32 *sid "  ");"
.SH ARGUMENTS
.IP "addr" 12
the IP address
.IP "family" 12
the address family
.IP "sid" 12
node SID
.SH "DESCRIPTION"
This function determines the SID of a network address by querying the
security policy.  The result is added to the network address table to
speedup future queries.  Returns zero on success, negative values on
failure.
