.TH "sel_netport_insert" 9 "sel_netport_insert" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sel_netport_insert \- Insert a new port into the table
.SH SYNOPSIS
.B "void" sel_netport_insert
.BI "(struct sel_netport *port "  ");"
.SH ARGUMENTS
.IP "port" 12
the new port record
.SH "DESCRIPTION"
Add a new port record to the network address hash table.
