.TH "sel_netif_kill" 9 "sel_netif_kill" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sel_netif_kill \- Remove an entry from the network interface table
.SH SYNOPSIS
.B "void" sel_netif_kill
.BI "(const struct net *ns "  ","
.BI "int ifindex "  ");"
.SH ARGUMENTS
.IP "ns" 12
the network namespace
.IP "ifindex" 12
the network interface
.SH "DESCRIPTION"
This function removes the entry matching \fIifindex\fP from the network interface
table if it exists.
