.TH "selinux_netlbl_option" 9 "selinux_netlbl_option" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
selinux_netlbl_option \- Is this a NetLabel option
.SH SYNOPSIS
.B "int" selinux_netlbl_option
.BI "(int level "  ","
.BI "int optname "  ");"
.SH ARGUMENTS
.IP "level" 12
the socket level or protocol
.IP "optname" 12
the socket option name
.SH "DESCRIPTION"
Returns true if \fIlevel\fP and \fIoptname\fP refer to a NetLabel option.
Helper for \fBselinux_netlbl_socket_setsockopt\fP.
