.TH "selinux_netlbl_sctp_sk_clone" 9 "selinux_netlbl_sctp_sk_clone" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
selinux_netlbl_sctp_sk_clone \- Copy state to the newly created sock
.SH SYNOPSIS
.B "void" selinux_netlbl_sctp_sk_clone
.BI "(struct sock *sk "  ","
.BI "struct sock *newsk "  ");"
.SH ARGUMENTS
.IP "sk" 12
current sock
.IP "newsk" 12
the new sock
.SH "DESCRIPTION"
Called whenever a new socket is created by accept(2) or sctp_peeloff(3).
