.TH "send_srp_login" 9 "send_srp_login" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
send_srp_login \- - Sends the srp login
.SH SYNOPSIS
.B "int" send_srp_login
.BI "(struct ibmvscsi_host_data *hostdata "  ");"
.SH ARGUMENTS
.IP "hostdata" 12
ibmvscsi_host_data of host
.SH "DESCRIPTION"
Returns zero if successful.
