.TH "serial8250_em485_config" 9 "serial8250_em485_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
serial8250_em485_config \- generic ->rs485_config() callback
.SH SYNOPSIS
.B "int" serial8250_em485_config
.BI "(struct uart_port *port "  ","
.BI "struct serial_rs485 *rs485 "  ");"
.SH ARGUMENTS
.IP "port" 12
uart port
.IP "rs485" 12
rs485 settings
.SH "DESCRIPTION"
Generic callback usable by 8250 uart drivers to activate rs485 settings
if the uart is incapable of driving RTS as a Transmit Enable signal in
hardware, relying on software emulation instead.
