.TH "set_channel" 9 "set_channel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
set_channel \- Set NIC media channel
.SH SYNOPSIS
.B "bool" set_channel
.BI "(struct vnt_private *priv "  ","
.BI "struct ieee80211_channel *ch "  ");"
.SH ARGUMENTS
.IP "priv" 12
-- undescribed --
.IP "ch" 12
-- undescribed --
.SH "DESCRIPTION"
Return Value: true if succeeded; false if failed.
