.TH "set_color_bitfields" 9 "set_color_bitfields" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
set_color_bitfields \- sets rgba fields
.SH SYNOPSIS
.B "void" set_color_bitfields
.BI "(struct fb_var_screeninfo *var "  ");"
.SH ARGUMENTS
.IP "var" 12
pointer to fb_var_screeninfo
.SH "DESCRIPTION"
The length, offset and ordering  for each color field 
(red, green, blue)  will be set as specified 
by the hardware
