.TH "set_platform_caps" 9 "set_platform_caps" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
set_platform_caps \- Private Function used during initialization.
.SH SYNOPSIS
.B "int" set_platform_caps
.BI "(struct pp_hwmgr *hwmgr "  ","
.BI "uint32_t powerplay_caps "  ");"
.SH ARGUMENTS
.IP "hwmgr" 12
Pointer to the hardware manager.
.IP "powerplay_caps" 12
the bit array (from BIOS) of capability bits.
Exception:  the current implementation always returns 1.
