.TH "set_orig_insn" 9 "set_orig_insn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
set_orig_insn \- Restore the original instruction.
.SH SYNOPSIS
.B "int" set_orig_insn
.BI "(struct arch_uprobe *auprobe "  ","
.BI "struct mm_struct *mm "  ","
.BI "unsigned long vaddr "  ");"
.SH ARGUMENTS
.IP "auprobe" 12
arch specific probepoint information.
.IP "mm" 12
the probed process address space.
.IP "vaddr" 12
the virtual address to insert the opcode.
.SH "DESCRIPTION"
For mm \fImm\fP, restore the original opcode (opcode) at \fIvaddr\fP.
Return 0 (success) or a negative errno.
