.TH "setup_percpu_irq" 9 "setup_percpu_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
setup_percpu_irq \- setup a per-cpu interrupt
.SH SYNOPSIS
.B "int" setup_percpu_irq
.BI "(unsigned int irq "  ","
.BI "struct irqaction *act "  ");"
.SH ARGUMENTS
.IP "irq" 12
Interrupt line to setup
.IP "act" 12
irqaction for the interrupt
.SH "DESCRIPTION"
Used to statically setup per-cpu interrupts in the early boot process.
