.TH "sfp_parse_support" 9 "sfp_parse_support" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sfp_parse_support \- Parse the eeprom id for supported link modes
.SH SYNOPSIS
.B "void" sfp_parse_support
.BI "(struct sfp_bus *bus "  ","
.BI "const struct sfp_eeprom_id *id "  ","
.BI "unsigned long *support "  ");"
.SH ARGUMENTS
.IP "bus" 12
a pointer to the \fIstruct sfp_bus\fP structure for the sfp module
.IP "id" 12
a pointer to the module's \fIstruct sfp_eeprom_id\fP
.IP "support" 12
pointer to an array of unsigned long for the ethtool support mask
.SH "DESCRIPTION"
Parse the EEPROM identification information and derive the supported
ethtool link modes for the module.
