.TH "sge_timer_tx" 9 "sge_timer_tx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sge_timer_tx \- perform periodic maintenance of an SGE qset
.SH SYNOPSIS
.B "void" sge_timer_tx
.BI "(struct timer_list *t "  ");"
.SH ARGUMENTS
.IP "t" 12
a timer list containing the SGE queue set to maintain

Runs periodically from a timer to perform maintenance of an SGE queue
set.  It performs two tasks:

Cleans up any completed Tx descriptors that may still be pending.
Normal descriptor cleanup happens when new packets are added to a Tx
queue so this timer is relatively infrequent and does any cleanup only
if the Tx queue has not seen any new packets in a while.  We make a
best effort attempt to reclaim descriptors, in that we don't wait
around if we cannot get a queue's lock (which most likely is because
someone else is queueing new packets and so will also handle the clean
up).  Since control queues use immediate data exclusively we don't
bother cleaning them up here.
