.TH "sgl_free_order" 9 "sgl_free_order" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sgl_free_order \- free a scatterlist and its pages
.SH SYNOPSIS
.B "void" sgl_free_order
.BI "(struct scatterlist *sgl "  ","
.BI "int order "  ");"
.SH ARGUMENTS
.IP "sgl" 12
Scatterlist with one or more elements
.IP "order" 12
Second argument for \fB__free_pages\fP
