.TH "sh_early_platform_driver_register" 9 "sh_early_platform_driver_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sh_early_platform_driver_register \- register early platform driver
.SH SYNOPSIS
.B "int" sh_early_platform_driver_register
.BI "(struct sh_early_platform_driver *epdrv "  ","
.BI "char *buf "  ");"
.SH ARGUMENTS
.IP "epdrv" 12
sh_early_platform driver structure
.IP "buf" 12
string passed from \fBearly_param\fP
.SH "DESCRIPTION"
Helper function for \fBsh_early_platform_init\fP / \fBsh_early_platform_init_buffer\fP
