.TH "si476x_core_pronounce_dead" 9 "si476x_core_pronounce_dead" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
si476x_core_pronounce_dead \- 
.SH SYNOPSIS
.B "void" si476x_core_pronounce_dead
.BI "(struct si476x_core *core "  ");"
.SH ARGUMENTS
.IP "core" 12
Core device structure
.SH "DESCRIPTION"
Mark the device as being dead and wake up all potentially waiting
threads of execution.
