.TH "si570_update_rfreq" 9 "si570_update_rfreq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
si570_update_rfreq \- Update clock multiplier
.SH SYNOPSIS
.B "int" si570_update_rfreq
.BI "(struct clk_si570 *data "  ");"
.SH ARGUMENTS
.IP "data" 12
Driver data structure
Passes on \fBregmap_bulk_write\fP return value.
