.TH "sil680_set_piomode" 9 "sil680_set_piomode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sil680_set_piomode \- set PIO mode data
.SH SYNOPSIS
.B "void" sil680_set_piomode
.BI "(struct ata_port *ap "  ","
.BI "struct ata_device *adev "  ");"
.SH ARGUMENTS
.IP "ap" 12
ATA interface
.IP "adev" 12
ATA device

Program the SIL680 registers for PIO mode. Note that the task speed
registers are shared between the devices so we must pick the lowest
mode for command work.
