.TH "sil680_seldev" 9 "sil680_seldev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sil680_seldev \- return register base
.SH SYNOPSIS
.B "unsigned long" sil680_seldev
.BI "(struct ata_port *ap "  ","
.BI "struct ata_device *adev "  ","
.BI "int r "  ");"
.SH ARGUMENTS
.IP "ap" 12
ATA interface
.IP "adev" 12
-- undescribed --
.IP "r" 12
config offset

Turn a config register offset into the right address in PCI space
to access the control register in question including accounting for
the unit shift.
