.TH "sis900_set_wol" 9 "sis900_set_wol" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sis900_set_wol \- Set up Wake on Lan registers
.SH SYNOPSIS
.B "int" sis900_set_wol
.BI "(struct net_device *net_dev "  ","
.BI "struct ethtool_wolinfo *wol "  ");"
.SH ARGUMENTS
.IP "net_dev" 12
the net device to probe
.IP "wol" 12
container for info passed to the driver

Process ethtool command "wol" to setup wake on lan features.
SiS900 supports sending WoL events if a correct packet is received,
but there is no simple way to filter them to only a subset (broadcast,
multicast, unicast or arp).
