.TH "sk_set_memalloc" 9 "sk_set_memalloc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sk_set_memalloc \- sets %SOCK_MEMALLOC
.SH SYNOPSIS
.B "void" sk_set_memalloc
.BI "(struct sock *sk "  ");"
.SH ARGUMENTS
.IP "sk" 12
socket to set it on
.SH "DESCRIPTION"
Set SOCK_MEMALLOC on a socket for access to emergency reserves.
It's the responsibility of the admin to adjust min_free_kbytes
to meet the requirements
