.TH "skb_gso_transport_seglen" 9 "skb_gso_transport_seglen" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
skb_gso_transport_seglen \- Return length of individual segments of a gso packet
.SH SYNOPSIS
.B "unsigned int" skb_gso_transport_seglen
.BI "(const struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "skb" 12
GSO skb
.SH "DESCRIPTION"
skb_gso_transport_seglen is used to determine the real size of the
individual segments, including Layer4 headers (TCP/UDP).

The MAC/L2 or network (IP, IPv6) headers are not accounted for.
