.TH "slim_stream_enable" 9 "slim_stream_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
slim_stream_enable \- Enable a prepared SLIMbus Stream
.SH SYNOPSIS
.B "int" slim_stream_enable
.BI "(struct slim_stream_runtime *stream "  ");"
.SH ARGUMENTS
.IP "stream" 12
instance of slim stream runtime to enable
.SH "DESCRIPTION"
This API will enable all the ports and channels associated with
SLIMbus stream
.SH "RETURN"
zero on success and error code on failure. From ASoC DPCM framework,
this state is linked to \fBtrigger\fP start operation.
