.TH "smack_task_kill" 9 "smack_task_kill" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smack_task_kill \- Smack check on signal delivery
.SH SYNOPSIS
.B "int" smack_task_kill
.BI "(struct task_struct *p "  ","
.BI "struct kernel_siginfo *info "  ","
.BI "int sig "  ","
.BI "const struct cred *cred "  ");"
.SH ARGUMENTS
.IP "p" 12
the task object
.IP "info" 12
unused
.IP "sig" 12
unused
.IP "cred" 12
identifies the cred to use in lieu of current's
.SH "DESCRIPTION"
Return 0 if write access is permitted
