.TH "smack_key_permission" 9 "smack_key_permission" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smack_key_permission \- Smack access on a key
.SH SYNOPSIS
.B "int" smack_key_permission
.BI "(key_ref_t key_ref "  ","
.BI "const struct cred *cred "  ","
.BI "enum key_need_perm need_perm "  ");"
.SH ARGUMENTS
.IP "key_ref" 12
gets to the object
.IP "cred" 12
the credentials to use
.IP "need_perm" 12
requested key permission
.SH "DESCRIPTION"
Return 0 if the task has read and write to the object,
an error code otherwise
