.TH "smk_list_swap_rcu" 9 "smk_list_swap_rcu" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smk_list_swap_rcu \- swap public list with a private one in RCU-safe way The caller must hold appropriate mutex to prevent concurrent modifications to the public list. Private list is assumed to be not accessible to other threads yet.
.SH SYNOPSIS
.B "void" smk_list_swap_rcu
.BI "(struct list_head *public "  ","
.BI "struct list_head *private "  ");"
.SH ARGUMENTS
.IP "public" 12
public list
.IP "private" 12
private list
