.TH "smk_write_revoke_subj" 9 "smk_write_revoke_subj" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smk_write_revoke_subj \- write() for /smack/revoke-subject
.SH SYNOPSIS
.B "ssize_t" smk_write_revoke_subj
.BI "(struct file *file "  ","
.BI "const char __user *buf "  ","
.BI "size_t count "  ","
.BI "loff_t *ppos "  ");"
.SH ARGUMENTS
.IP "file" 12
file pointer
.IP "buf" 12
data from user space
.IP "count" 12
bytes sent
.IP "ppos" 12
where to start - must be 0
