.TH "smu_v11_0_i2c_transmit" 9 "smu_v11_0_i2c_transmit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
smu_v11_0_i2c_transmit \- Send a block of data over the I2C bus to a slave device.
.SH SYNOPSIS
.B "uint32_t" smu_v11_0_i2c_transmit
.BI "(struct i2c_adapter *control "  ","
.BI "uint8_t address "  ","
.BI "uint8_t *data "  ","
.BI "uint32_t numbytes "  ","
.BI "uint32_t i2c_flag "  ");"
.SH ARGUMENTS
.IP "control" 12
I2C adapter reference
.IP "address" 12
The I2C address of the slave device.
.IP "data" 12
The data to transmit over the bus.
.IP "numbytes" 12
The amount of data to transmit.
.IP "i2c_flag" 12
Flags for transmission
.SH "DESCRIPTION"
Returns 0 on success or error.
