.TH "snake_inventory" 9 "snake_inventory" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snake_inventory \- 
.SH SYNOPSIS
.B "void" snake_inventory
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Before PDC_SYSTEM_MAP was invented, the PDC_MEM_MAP call was used.
To use it, we initialise the mod_path.bc to 0xff and try all values of
mod to get the HPA for the top-level devices.  Bus adapters may have
sub-devices which are discovered by setting bc[5] to 0 and bc[4] to the
module, then trying all possible functions.
