.TH "snd_hda_gen_parse_auto_config" 9 "snd_hda_gen_parse_auto_config" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hda_gen_parse_auto_config \- Parse the given BIOS configuration and set up the hda_gen_spec
.SH SYNOPSIS
.B "int" snd_hda_gen_parse_auto_config
.BI "(struct hda_codec *codec "  ","
.BI "struct auto_pin_cfg *cfg "  ");"
.SH ARGUMENTS
.IP "codec" 12
the HDA codec
.IP "cfg" 12
Parsed pin configuration
.SH "DESCRIPTION"
return 1 if successful, 0 if the proper config is not found,
or a negative error code
