.TH "snd_hdac_regmap_init" 9 "snd_hdac_regmap_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hdac_regmap_init \- Initialize regmap for HDA register accesses
.SH SYNOPSIS
.B "int" snd_hdac_regmap_init
.BI "(struct hdac_device *codec "  ");"
.SH ARGUMENTS
.IP "codec" 12
the codec object
.SH "DESCRIPTION"
Returns zero for success or a negative error code.
