.TH "snd_rawmidi_set_ops" 9 "snd_rawmidi_set_ops" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_rawmidi_set_ops \- set the rawmidi operators
.SH SYNOPSIS
.B "void" snd_rawmidi_set_ops
.BI "(struct snd_rawmidi *rmidi "  ","
.BI "int stream "  ","
.BI "const struct snd_rawmidi_ops *ops "  ");"
.SH ARGUMENTS
.IP "rmidi" 12
the rawmidi instance
.IP "stream" 12
the stream direction, SNDRV_RAWMIDI_STREAM_XXX
.IP "ops" 12
the operator table
.SH "DESCRIPTION"
Sets the rawmidi operators for the given stream direction.
