.TH "snd_soc_runtime_set_dai_fmt" 9 "snd_soc_runtime_set_dai_fmt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_soc_runtime_set_dai_fmt \- Change DAI link format for a ASoC runtime
.SH SYNOPSIS
.B "int" snd_soc_runtime_set_dai_fmt
.BI "(struct snd_soc_pcm_runtime *rtd "  ","
.BI "unsigned int dai_fmt "  ");"
.SH ARGUMENTS
.IP "rtd" 12
The runtime for which the DAI link format should be changed
.IP "dai_fmt" 12
The new DAI link format
.SH "DESCRIPTION"
This function updates the DAI link format for all DAIs connected to the DAI
link for the specified runtime.

Returns 0 on success, otherwise a negative error code.
.SH "NOTE"
For setups with a static format set the dai_fmt field in the
corresponding snd_dai_link struct instead of using this function.
