.TH "snd_hda_shutup_pins" 9 "snd_hda_shutup_pins" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hda_shutup_pins \- Shut up all pins
.SH SYNOPSIS
.B "void" snd_hda_shutup_pins
.BI "(struct hda_codec *codec "  ");"
.SH ARGUMENTS
.IP "codec" 12
the HDA codec
.SH "DESCRIPTION"
Clear all pin controls to shup up before suspend for avoiding click noise.
The controls aren't cached so that they can be resumed properly.
