.TH "snd_hda_multi_out_analog_prepare" 9 "snd_hda_multi_out_analog_prepare" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hda_multi_out_analog_prepare \- Preapre the analog outputs.
.SH SYNOPSIS
.B "int" snd_hda_multi_out_analog_prepare
.BI "(struct hda_codec *codec "  ","
.BI "struct hda_multi_out *mout "  ","
.BI "unsigned int stream_tag "  ","
.BI "unsigned int format "  ","
.BI "struct snd_pcm_substream *substream "  ");"
.SH ARGUMENTS
.IP "codec" 12
the HDA codec
.IP "mout" 12
hda_multi_out object
.IP "stream_tag" 12
stream tag to assign
.IP "format" 12
format id to assign
.IP "substream" 12
PCM substream to assign
.SH "DESCRIPTION"
Set up the i/o for analog out.
When the digital out is available, copy the front out to digital out, too.
