.TH "snd_pcm_hw_constraint_integer" 9 "snd_pcm_hw_constraint_integer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_pcm_hw_constraint_integer \- apply an integer constraint to an interval
.SH SYNOPSIS
.B "int" snd_pcm_hw_constraint_integer
.BI "(struct snd_pcm_runtime *runtime "  ","
.BI "snd_pcm_hw_param_t var "  ");"
.SH ARGUMENTS
.IP "runtime" 12
PCM runtime instance
.IP "var" 12
hw_params variable to apply the integer constraint
.SH "DESCRIPTION"
Apply the constraint of integer to an interval parameter.
.SH "RETURN"
Positive if the value is changed, zero if it's not changed, or a
negative error code.
