.TH "snd_soc_unregister_card" 9 "snd_soc_unregister_card" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_soc_unregister_card \- Unregister a card with the ASoC core
.SH SYNOPSIS
.B "int" snd_soc_unregister_card
.BI "(struct snd_soc_card *card "  ");"
.SH ARGUMENTS
.IP "card" 12
Card to unregister
