.TH "snd_hda_ext_driver_register" 9 "snd_hda_ext_driver_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hda_ext_driver_register \- register a driver for ext hda devices
.SH SYNOPSIS
.B "int" snd_hda_ext_driver_register
.BI "(struct hdac_driver *drv "  ");"
.SH ARGUMENTS
.IP "drv" 12
ext hda driver structure
