.TH "snd_soc_dai_set_sysclk" 9 "snd_soc_dai_set_sysclk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_soc_dai_set_sysclk \- configure DAI system or master clock.
.SH SYNOPSIS
.B "int" snd_soc_dai_set_sysclk
.BI "(struct snd_soc_dai *dai "  ","
.BI "int clk_id "  ","
.BI "unsigned int freq "  ","
.BI "int dir "  ");"
.SH ARGUMENTS
.IP "dai" 12
DAI
.IP "clk_id" 12
DAI specific clock ID
.IP "freq" 12
new clock frequency in Hz
.IP "dir" 12
new clock direction - input/output.
.SH "DESCRIPTION"
Configures the DAI master (MCLK) or system (SYSCLK) clocking.
