.TH "snd_soc_dapm_force_enable_pin" 9 "snd_soc_dapm_force_enable_pin" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_soc_dapm_force_enable_pin \- force a pin to be enabled
.SH SYNOPSIS
.B "int" snd_soc_dapm_force_enable_pin
.BI "(struct snd_soc_dapm_context *dapm "  ","
.BI "const char *pin "  ");"
.SH ARGUMENTS
.IP "dapm" 12
DAPM context
.IP "pin" 12
pin name
.SH "DESCRIPTION"
Enables input/output pin regardless of any other state.  This is
intended for use with microphone bias supplies used in microphone
jack detection.
.SH "NOTE"
\fBsnd_soc_dapm_sync\fP needs to be called after this for DAPM to
do any widget power switching.
