.TH "snd_hdac_ext_stream_set_spib" 9 "snd_hdac_ext_stream_set_spib" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hdac_ext_stream_set_spib \- sets the spib value of a stream
.SH SYNOPSIS
.B "int" snd_hdac_ext_stream_set_spib
.BI "(struct hdac_bus *bus "  ","
.BI "struct hdac_ext_stream *stream "  ","
.BI "u32 value "  ");"
.SH ARGUMENTS
.IP "bus" 12
HD-audio core bus
.IP "stream" 12
hdac_ext_stream
.IP "value" 12
spib value to set
