.TH "snd_hda_get_path_idx" 9 "snd_hda_get_path_idx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hda_get_path_idx \- get the index number corresponding to the path instance
.SH SYNOPSIS
.B "int" snd_hda_get_path_idx
.BI "(struct hda_codec *codec "  ","
.BI "struct nid_path *path "  ");"
.SH ARGUMENTS
.IP "codec" 12
the HDA codec
.IP "path" 12
nid_path object
.SH "DESCRIPTION"
The returned index starts from 1, i.e. the actual array index with offset 1,
and zero is handled as an invalid path
