.TH "snd_pcm_prepare" 9 "snd_pcm_prepare" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_pcm_prepare \- prepare the PCM substream to be triggerable
.SH SYNOPSIS
.B "int" snd_pcm_prepare
.BI "(struct snd_pcm_substream *substream "  ","
.BI "struct file *file "  ");"
.SH ARGUMENTS
.IP "substream" 12
the PCM substream instance
.IP "file" 12
file to refer f_flags
.SH "RETURN"
Zero if successful, or a negative error code.
