.TH "snd_hda_gen_build_controls" 9 "snd_hda_gen_build_controls" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hda_gen_build_controls \- Build controls from the parsed results
.SH SYNOPSIS
.B "int" snd_hda_gen_build_controls
.BI "(struct hda_codec *codec "  ");"
.SH ARGUMENTS
.IP "codec" 12
the HDA codec
.SH "DESCRIPTION"
Pass this to build_controls patch_ops.
