.TH "snd_hdac_stream_cleanup" 9 "snd_hdac_stream_cleanup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hdac_stream_cleanup \- cleanup a stream
.SH SYNOPSIS
.B "void" snd_hdac_stream_cleanup
.BI "(struct hdac_stream *azx_dev "  ");"
.SH ARGUMENTS
.IP "azx_dev" 12
HD-audio core stream to clean up
