.TH "snd_device_free" 9 "snd_device_free" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_device_free \- release the device from the card
.SH SYNOPSIS
.B "void" snd_device_free
.BI "(struct snd_card *card "  ","
.BI "void *device_data "  ");"
.SH ARGUMENTS
.IP "card" 12
the card instance
.IP "device_data" 12
the data pointer to release
.SH "DESCRIPTION"
Removes the device from the list on the card and invokes the
callbacks, dev_disconnect and dev_free, corresponding to the state.
Then release the device.
