.TH "snd_hdac_stream_sync_trigger" 9 "snd_hdac_stream_sync_trigger" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hdac_stream_sync_trigger \- turn on/off stream sync register
.SH SYNOPSIS
.B "void" snd_hdac_stream_sync_trigger
.BI "(struct hdac_stream *azx_dev "  ","
.BI "bool set "  ","
.BI "unsigned int streams "  ","
.BI "unsigned int reg "  ");"
.SH ARGUMENTS
.IP "azx_dev" 12
HD-audio core stream (master stream)
.IP "set" 12
true = set, false = clear
.IP "streams" 12
bit flags of streams to sync
.IP "reg" 12
the stream sync register address
