.TH "snd_hda_jack_tbl_get_mst" 9 "snd_hda_jack_tbl_get_mst" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_hda_jack_tbl_get_mst \- query the jack-table entry for the given NID
.SH SYNOPSIS
.B "struct hda_jack_tbl *" snd_hda_jack_tbl_get_mst
.BI "(struct hda_codec *codec "  ","
.BI "hda_nid_t nid "  ","
.BI "int dev_id "  ");"
.SH ARGUMENTS
.IP "codec" 12
the HDA codec
.IP "nid" 12
pin NID to refer to
.IP "dev_id" 12
pin device entry id
