.TH "snd_interval_div" 9 "snd_interval_div" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_interval_div \- refine the interval value with division
.SH SYNOPSIS
.B "void" snd_interval_div
.BI "(const struct snd_interval *a "  ","
.BI "const struct snd_interval *b "  ","
.BI "struct snd_interval *c "  ");"
.SH ARGUMENTS
.IP "a" 12
dividend
.IP "b" 12
divisor
.IP "c" 12
quotient
.SH "DESCRIPTION"
c = a / b

Returns non-zero if the value is changed, zero if not changed.
