.TH "snd_request_card" 9 "snd_request_card" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
snd_request_card \- try to load the card module
.SH SYNOPSIS
.B "void" snd_request_card
.BI "(int card "  ");"
.SH ARGUMENTS
.IP "card" 12
the card number
.SH "DESCRIPTION"
Tries to load the module "snd-card-X" for the given card number
via request_module.  Returns immediately if already loaded.
