.TH "sockaddr_to_str" 9 "sockaddr_to_str" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sockaddr_to_str \- convert sockaddr to a string.
.SH SYNOPSIS
.B "int" sockaddr_to_str
.BI "(const struct sockaddr *addr "  ","
.BI "char *buf "  ","
.BI "size_t len "  ");"
.SH ARGUMENTS
.IP "addr" 12
the sockadddr structure to be converted.
.IP "buf" 12
string containing socket addr.
.IP "len" 12
string length.
.SH "DESCRIPTION"
The return value is the number of characters written into buf not
including the trailing '\0'. If len is == 0 the function returns 0..
