.TH "spear_smi_hw_init" 9 "spear_smi_hw_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spear_smi_hw_init \- initializes the smi controller.
.SH SYNOPSIS
.B "void" spear_smi_hw_init
.BI "(struct spear_smi *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
structure of smi device
.SH "DESCRIPTION"
this routine initializes the smi controller wit the default values
