.TH "spi_get_gpio_descs" 9 "spi_get_gpio_descs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_get_gpio_descs \- grab chip select GPIOs for the master
.SH SYNOPSIS
.B "int" spi_get_gpio_descs
.BI "(struct spi_controller *ctlr "  ");"
.SH ARGUMENTS
.IP "ctlr" 12
The SPI master to grab GPIO descriptors for
