.TH "spi_nor_region_next" 9 "spi_nor_region_next" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_nor_region_next \- get the next spi nor region
.SH SYNOPSIS
.B "struct spi_nor_erase_region *" spi_nor_region_next
.BI "(struct spi_nor_erase_region *region "  ");"
.SH ARGUMENTS
.IP "region" 12
pointer to a structure that describes a SPI NOR erase region
.SH "RETURN"
the next spi nor region or NULL if last region.
