.TH "spi_nor_get_map_in_use" 9 "spi_nor_get_map_in_use" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_nor_get_map_in_use \- get the configuration map in use
.SH SYNOPSIS
.B "const u32 *" spi_nor_get_map_in_use
.BI "(struct spi_nor *nor "  ","
.BI "const u32 *smpt "  ","
.BI "u8 smpt_len "  ");"
.SH ARGUMENTS
.IP "nor" 12
pointer to a 'struct spi_nor'
.IP "smpt" 12
pointer to the sector map parameter table
.IP "smpt_len" 12
sector map parameter table length
.SH "RETURN"
pointer to the map in use, ERR_PTR(-errno) otherwise.
