.TH "spi_nor_map_cmp_erase_type" 9 "spi_nor_map_cmp_erase_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_nor_map_cmp_erase_type \- compare the map's erase types by size
.SH SYNOPSIS
.B "int" spi_nor_map_cmp_erase_type
.BI "(const void *l "  ","
.BI "const void *r "  ");"
.SH ARGUMENTS
.IP "l" 12
member in the left half of the map's erase_type array
.IP "r" 12
member in the right half of the map's erase_type array
.SH "DESCRIPTION"
Comparison function used in the \fBsort\fP call to sort in ascending order the
map's erase types, the smallest erase type size being the first member in the
sorted erase_type array.
.SH "RETURN"
the result of \fIl->size\fP - \fIr->size\fP
