.TH "spi_nor_find_erase_region" 9 "spi_nor_find_erase_region" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_nor_find_erase_region \- find the region of the serial flash memory in which the offset fits
.SH SYNOPSIS
.B "struct spi_nor_erase_region *" spi_nor_find_erase_region
.BI "(const struct spi_nor_erase_map *map "  ","
.BI "u64 addr "  ");"
.SH ARGUMENTS
.IP "map" 12
the erase map of the SPI NOR
.IP "addr" 12
offset in the serial flash memory
.SH "RETURN"
a pointer to the spi_nor_erase_region struct, ERR_PTR(-errno)
otherwise.
