.TH "spi_nor_cypress_octal_dtr_enable" 9 "spi_nor_cypress_octal_dtr_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spi_nor_cypress_octal_dtr_enable \- Enable octal DTR on Cypress flashes.
.SH SYNOPSIS
.B "int" spi_nor_cypress_octal_dtr_enable
.BI "(struct spi_nor *nor "  ","
.BI "bool enable "  ");"
.SH ARGUMENTS
.IP "nor" 12
pointer to a 'struct spi_nor'
.IP "enable" 12
whether to enable or disable Octal DTR
.SH "DESCRIPTION"
This also sets the memory access latency cycles to 24 to allow the flash to
run at up to 200MHz.
.SH "RETURN"
0 on success, -errno otherwise.
