.TH "spinand_upd_cfg" 9 "spinand_upd_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spinand_upd_cfg \- Update the configuration register
.SH SYNOPSIS
.B "int" spinand_upd_cfg
.BI "(struct spinand_device *spinand "  ","
.BI "u8 mask "  ","
.BI "u8 val "  ");"
.SH ARGUMENTS
.IP "spinand" 12
the spinand device
.IP "mask" 12
the mask encoding the bits to update in the config reg
.IP "val" 12
the new value to apply
.SH "DESCRIPTION"
Update the configuration register.
.SH "RETURN"
0 on success, a negative error code otherwise.
