.TH "split_token_from_name" 9 "split_token_from_name" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
split_token_from_name \- separate a string of form <token>^<name>
.SH SYNOPSIS
.B "char *" split_token_from_name
.BI "(const char *op "  ","
.BI "char *args "  ","
.BI "u64 *token "  ");"
.SH ARGUMENTS
.IP "op" 12
operation being checked
.IP "args" 12
string to parse  (NOT NULL)
.IP "token" 12
stores returned parsed token value  (NOT NULL)
.SH "RETURN"
start position of name after token else NULL on failure
