.TH "spu2_hash_xlate" 9 "spu2_hash_xlate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spu2_hash_xlate \- Convert a hash {alg/mode/type} triple to a SPU2 hash type and mode.
.SH SYNOPSIS
.B "int" spu2_hash_xlate
.BI "(enum hash_alg hash_alg "  ","
.BI "enum hash_mode hash_mode "  ","
.BI "enum hash_type hash_type "  ","
.BI "enum spu_cipher_type ciph_type "  ","
.BI "enum spu2_hash_type *spu2_type "  ","
.BI "enum spu2_hash_mode *spu2_mode "  ");"
.SH ARGUMENTS
.IP "hash_alg" 12
[in] hash algorithm value from software enumeration
.IP "hash_mode" 12
[in] hash mode value from software enumeration
.IP "hash_type" 12
[in] hash type value from software enumeration
.IP "ciph_type" 12
[in] cipher type value from software enumeration
.IP "spu2_type" 12
[out] hash type value used by SPU2 hardware
.IP "spu2_mode" 12
[out] hash mode value used by SPU2 hardware
.SH "RETURN"
0 if successful
