.TH "spu_rx_callback" 9 "spu_rx_callback" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spu_rx_callback \- Callback from mailbox framework with a SPU response.
.SH SYNOPSIS
.B "void" spu_rx_callback
.BI "(struct mbox_client *cl "  ","
.BI "void *msg "  ");"
.SH ARGUMENTS
.IP "cl" 12
mailbox client structure for SPU driver
.IP "msg" 12
mailbox message containing SPU response
