.TH "spum_wordalign_padlen" 9 "spum_wordalign_padlen" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
spum_wordalign_padlen \- Given the length of a data field, determine the padding required to align the data following this field on a 4-byte boundary.
.SH SYNOPSIS
.B "u32" spum_wordalign_padlen
.BI "(u32 data_size "  ");"
.SH ARGUMENTS
.IP "data_size" 12
length of data field in bytes
.SH "RETURN"
length of status field padding, in bytes
