.TH "srcu_batches_completed" 9 "srcu_batches_completed" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
srcu_batches_completed \- return batches completed.
.SH SYNOPSIS
.B "unsigned long" srcu_batches_completed
.BI "(struct srcu_struct *ssp "  ");"
.SH ARGUMENTS
.IP "ssp" 12
srcu_struct on which to report batch completion.
.SH "DESCRIPTION"
Report the number of batches, correlated with, but not necessarily
precisely the same as, the number of grace periods that have elapsed.
