.TH "srpt_make_tport" 9 "srpt_make_tport" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
srpt_make_tport \- configfs callback invoked for mkdir /sys/kernel/config/target/$driver/$port
.SH SYNOPSIS
.B "struct se_wwn *" srpt_make_tport
.BI "(struct target_fabric_configfs *tf "  ","
.BI "struct config_group *group "  ","
.BI "const char *name "  ");"
.SH ARGUMENTS
.IP "tf" 12
Not used.
.IP "group" 12
Not used.
.IP "name" 12
$port.
