.TH "srpt_queue_response" 9 "srpt_queue_response" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
srpt_queue_response \- transmit the response to a SCSI command
.SH SYNOPSIS
.B "void" srpt_queue_response
.BI "(struct se_cmd *cmd "  ");"
.SH ARGUMENTS
.IP "cmd" 12
SCSI target command.
.SH "DESCRIPTION"
Callback function called by the TCM core. Must not block since it can be
invoked on the context of the IB completion handler.
