.TH "ssam_event_matches_notifier" 9 "ssam_event_matches_notifier" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssam_event_matches_notifier \- Test if an event matches a notifier.
.SH SYNOPSIS
.B "bool" ssam_event_matches_notifier
.BI "(const struct ssam_event_notifier *n "  ","
.BI "const struct ssam_event *event "  ");"
.SH ARGUMENTS
.IP "n" 12
The event notifier to test against.
.IP "event" 12
The event to test.
.SH "RETURN"
Returns true if the given event matches the given notifier
according to the rules set in the notifier's event mask, false otherwise.
