.TH "ssam_device_id_compatible" 9 "ssam_device_id_compatible" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssam_device_id_compatible \- Check if a device ID matches a UID.
.SH SYNOPSIS
.B "bool" ssam_device_id_compatible
.BI "(const struct ssam_device_id *id "  ","
.BI "struct ssam_device_uid uid "  ");"
.SH ARGUMENTS
.IP "id" 12
The device ID as potential match.
.IP "uid" 12
The device UID matching against.
.SH "DESCRIPTION"
Check if the given ID is a match for the given UID, i.e. if a device with
the provided UID is compatible to the given ID following the match rules
described in its \fIssam_device_id.match_flags\fP member.
.SH "RETURN"
Returns true if the given UID is compatible to the match rule
described by the given ID, false otherwise.
