.TH "ssam_event_queue_is_empty" 9 "ssam_event_queue_is_empty" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssam_event_queue_is_empty \- Check if the event queue is empty.
.SH SYNOPSIS
.B "bool" ssam_event_queue_is_empty
.BI "(struct ssam_event_queue *q "  ");"
.SH ARGUMENTS
.IP "q" 12
The event queue.
