.TH "ssctl_new_server" 9 "ssctl_new_server" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ssctl_new_server \- QMI callback indicating a new service
.SH SYNOPSIS
.B "int" ssctl_new_server
.BI "(struct qmi_handle *qmi "  ","
.BI "struct qmi_service *svc "  ");"
.SH ARGUMENTS
.IP "qmi" 12
QMI handle
.IP "svc" 12
service information
.SH "RETURN"
0 if we're interested in this service, -EINVAL otherwise.
