.TH "sti_gdp_get_dst" 9 "sti_gdp_get_dst" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sti_gdp_get_dst \- 
.SH SYNOPSIS
.B "int" sti_gdp_get_dst
.BI "(struct device *dev "  ","
.BI "int dst "  ","
.BI "int src "  ");"
.SH ARGUMENTS
.IP "dev" 12
device
.IP "dst" 12
requested destination size
.IP "src" 12
source size
.SH "DESCRIPTION"
Return the cropped / clamped destination size
.SH "RETURN"
cropped / clamped destination size
