.TH "stm32h7_spi_get_bpw_mask" 9 "stm32h7_spi_get_bpw_mask" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stm32h7_spi_get_bpw_mask \- Return bits per word mask
.SH SYNOPSIS
.B "int" stm32h7_spi_get_bpw_mask
.BI "(struct stm32_spi *spi "  ");"
.SH ARGUMENTS
.IP "spi" 12
pointer to the spi controller data structure
