.TH "stm32f4_i2c_handle_read" 9 "stm32f4_i2c_handle_read" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stm32f4_i2c_handle_read \- Handle FIFO empty interrupt in case of read
.SH SYNOPSIS
.B "void" stm32f4_i2c_handle_read
.BI "(struct stm32f4_i2c_dev *i2c_dev "  ");"
.SH ARGUMENTS
.IP "i2c_dev" 12
Controller's private data
.SH "DESCRIPTION"
This function is called when a new data is received in data register
