.TH "stm32_dfsdm_stop_dfsdm" 9 "stm32_dfsdm_stop_dfsdm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stm32_dfsdm_stop_dfsdm \- stop global DFSDM interface.
.SH SYNOPSIS
.B "int" stm32_dfsdm_stop_dfsdm
.BI "(struct stm32_dfsdm *dfsdm "  ");"
.SH ARGUMENTS
.IP "dfsdm" 12
Handle used to retrieve dfsdm context.
.SH "DESCRIPTION"

Disable interface if n_active_ch is null
