.TH "stmmac_pci_remove" 9 "stmmac_pci_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stmmac_pci_remove \- 
.SH SYNOPSIS
.B "void" stmmac_pci_remove
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
platform device pointer
.SH "DESCRIPTION"
this function calls the main to free the net resources
and releases the PCI resources.
