.TH "stmmac_dma_operation_mode" 9 "stmmac_dma_operation_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stmmac_dma_operation_mode \- HW DMA operation mode
.SH SYNOPSIS
.B "void" stmmac_dma_operation_mode
.BI "(struct stmmac_priv *priv "  ");"
.SH ARGUMENTS
.IP "priv" 12
driver private structure
.SH "DESCRIPTION"
it is used for configuring the DMA operation mode register in
order to program the tx/rx DMA thresholds or Store-And-Forward mode.
