.TH "stmmac_resume" 9 "stmmac_resume" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stmmac_resume \- resume callback
.SH SYNOPSIS
.B "int" stmmac_resume
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device pointer
.SH "DESCRIPTION"
when resume this function is invoked to setup the DMA and CORE
in a usable state.
