.TH "stmmac_enable_eee_mode" 9 "stmmac_enable_eee_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stmmac_enable_eee_mode \- check and enter in LPI mode
.SH SYNOPSIS
.B "void" stmmac_enable_eee_mode
.BI "(struct stmmac_priv *priv "  ");"
.SH ARGUMENTS
.IP "priv" 12
driver private structure
.SH "DESCRIPTION"
this function is to verify and enter in LPI mode in case of
EEE.
