.TH "stop_kthread" 9 "stop_kthread" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
stop_kthread \- Inform the hardware latency samping/detector kthread to stop
.SH SYNOPSIS
.B "void" stop_kthread
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

This kicks the running hardware latency sampling/detector kernel thread and
tells it to stop sampling now. Use this on unload and at system shutdown.
