.TH "strcspn" 9 "strcspn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
strcspn \- Calculate the length of the initial substring of @s which does not contain letters in @reject
.SH SYNOPSIS
.B "size_t" strcspn
.BI "(const char *s "  ","
.BI "const char *reject "  ");"
.SH ARGUMENTS
.IP "s" 12
The string to be searched
.IP "reject" 12
The string to avoid
