.TH "strrchr" 9 "strrchr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
strrchr \- Find the last occurrence of a character in a string
.SH SYNOPSIS
.B "char *" strrchr
.BI "(const char *s "  ","
.BI "int c "  ");"
.SH ARGUMENTS
.IP "s" 12
The string to be searched
.IP "c" 12
The character to search for
