.TH "submit_bio" 9 "submit_bio" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
submit_bio \- submit a bio to the block device layer for I/O
.SH SYNOPSIS
.B "blk_qc_t" submit_bio
.BI "(struct bio *bio "  ");"
.SH ARGUMENTS
.IP "bio" 12
The \fIstruct bio\fP which describes the I/O
.SH "DESCRIPTION"
\fBsubmit_bio\fP is used to submit I/O requests to block devices.  It is passed a
fully set up \fIstruct bio\fP that describes the I/O that needs to be done.  The
bio will be send to the device described by the bi_bdev field.

The success/failure status of the request, along with notification of
completion, is delivered asynchronously through the ->\fBbi_end_io\fP callback
in \fIbio\fP.  The bio must NOT be touched by thecaller until ->\fBbi_end_io\fP has
been called.
