.TH "sunxi_ccu_set_mmc_timing_mode" 9 "sunxi_ccu_set_mmc_timing_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sunxi_ccu_set_mmc_timing_mode \- Configure the MMC clock timing mode
.SH SYNOPSIS
.B "int" sunxi_ccu_set_mmc_timing_mode
.BI "(struct clk *clk "  ","
.BI "bool new_mode "  ");"
.SH ARGUMENTS
.IP "clk" 12
clock to be configured
.IP "new_mode" 12
true for new timing mode introduced in A83T and later
.SH "DESCRIPTION"
Returns 0 on success, -ENOTSUPP if the clock does not support
switching modes.
