.TH "sunxi_rsb_device_create" 9 "sunxi_rsb_device_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sunxi_rsb_device_create \- allocate and add an RSB device
.SH SYNOPSIS
.B "struct sunxi_rsb_device *" sunxi_rsb_device_create
.BI "(struct sunxi_rsb *rsb "  ","
.BI "struct device_node *node "  ","
.BI "u16 hwaddr "  ","
.BI "u8 rtaddr "  ");"
.SH ARGUMENTS
.IP "rsb" 12
RSB controller
.IP "node" 12
RSB slave device node
.IP "hwaddr" 12
RSB slave hardware address
.IP "rtaddr" 12
RSB slave runtime address
