.TH "sunxi_rsb_device_unregister" 9 "sunxi_rsb_device_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sunxi_rsb_device_unregister \- unregister an RSB device
.SH SYNOPSIS
.B "void" sunxi_rsb_device_unregister
.BI "(struct sunxi_rsb_device *rdev "  ");"
.SH ARGUMENTS
.IP "rdev" 12
rsb_device to be removed
