.TH "svc_tcp_sendto" 9 "svc_tcp_sendto" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
svc_tcp_sendto \- Send out a reply on a TCP socket
.SH SYNOPSIS
.B "int" svc_tcp_sendto
.BI "(struct svc_rqst *rqstp "  ");"
.SH ARGUMENTS
.IP "rqstp" 12
completed svc_rqst
.SH "DESCRIPTION"
xpt_mutex ensures \fIrqstp\fP's whole message is written to the socket
without interruption.

Returns the number of bytes sent, or a negative errno.
