.TH "svc_rdma_xb_write" 9 "svc_rdma_xb_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
svc_rdma_xb_write \- Construct RDMA Writes to write an xdr_buf
.SH SYNOPSIS
.B "int" svc_rdma_xb_write
.BI "(const struct xdr_buf *xdr "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "xdr" 12
xdr_buf to write
.IP "data" 12
pointer to write arguments
.SH "RETURN"
On succes, returns zero
-E2BIG if the client-provided Write chunk is too small
-ENOMEM if a resource has been exhausted
-EIO if an rdma-rw error occurred
