.TH "svc_udp_release_rqst" 9 "svc_udp_release_rqst" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
svc_udp_release_rqst \- Release transport-related resources
.SH SYNOPSIS
.B "void" svc_udp_release_rqst
.BI "(struct svc_rqst *rqstp "  ");"
.SH ARGUMENTS
.IP "rqstp" 12
request structure with resources to be released
