.TH "svc_rdma_post_recvs" 9 "svc_rdma_post_recvs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
svc_rdma_post_recvs \- Post initial set of Recv WRs
.SH SYNOPSIS
.B "bool" svc_rdma_post_recvs
.BI "(struct svcxprt_rdma *rdma "  ");"
.SH ARGUMENTS
.IP "rdma" 12
fresh svcxprt_rdma
.SH "DESCRIPTION"
Returns true if successful, otherwise false.
