.TH "svcxdr_decode_fhandle" 9 "svcxdr_decode_fhandle" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
svcxdr_decode_fhandle \- Decode an NFSv2 file handle
.SH SYNOPSIS
.B "bool" svcxdr_decode_fhandle
.BI "(struct xdr_stream *xdr "  ","
.BI "struct svc_fh *fhp "  ");"
.SH ARGUMENTS
.IP "xdr" 12
XDR stream positioned at an encoded NFSv2 FH
.IP "fhp" 12
OUT: filled-in server file handle
.SH "DESCRIPTION"
Return values:
false: The encoded file handle was not valid
true: \fIfhp\fP has been initialized
