.TH "sw_cfg_broad_storm" 9 "sw_cfg_broad_storm" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sw_cfg_broad_storm \- configure broadcast storm threshold
.SH SYNOPSIS
.B "void" sw_cfg_broad_storm
.BI "(struct ksz_hw *hw "  ","
.BI "u8 percent "  ");"
.SH ARGUMENTS
.IP "hw" 12
The hardware instance.
.IP "percent" 12
Broadcast storm threshold in percent of transmit rate.
.SH "DESCRIPTION"
This routine configures the broadcast storm threshold of the switch.
