.TH "switch_leds" 9 "switch_leds" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
switch_leds \- switch the leds, go from one site to the other.
.SH SYNOPSIS
.B "void" switch_leds
.BI "(struct controller *ctrl "  ","
.BI "const int num_of_slots "  ","
.BI "u32 *work_LED "  ","
.BI "const int direction "  ");"
.SH ARGUMENTS
.IP "ctrl" 12
controller to use
.IP "num_of_slots" 12
number of slots to use
.IP "work_LED" 12
LED control value
.IP "direction" 12
1 to start from the left side, 0 to start right.
