.TH "sync_completion" 9 "sync_completion" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sync_completion \- Signal that a synchronous command has completed Note that after returning from this call, the evt_struct is freed. the caller waiting on this completion shouldn't touch the evt_struct again.
.SH SYNOPSIS
.B "void" sync_completion
.BI "(struct srp_event_struct *evt_struct "  ");"
.SH ARGUMENTS
.IP "evt_struct" 12
-- undescribed --
