.TH "sync_file_merge" 9 "sync_file_merge" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sync_file_merge \- merge two sync_files
.SH SYNOPSIS
.B "struct sync_file *" sync_file_merge
.BI "(const char *name "  ","
.BI "struct sync_file *a "  ","
.BI "struct sync_file *b "  ");"
.SH ARGUMENTS
.IP "name" 12
name of new fence
.IP "a" 12
sync_file a
.IP "b" 12
sync_file b
.SH "DESCRIPTION"
Creates a new sync_file which contains copies of all the fences in both
\fIa\fP and \fIb\fP.  \fIa\fP and \fIb\fP remain valid, independent sync_file. Returns the
new merged sync_file or NULL in case of error.
