.TH "sysfs_create_link_nowarn" 9 "sysfs_create_link_nowarn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
sysfs_create_link_nowarn \- create symlink between two objects.
.SH SYNOPSIS
.B "int" sysfs_create_link_nowarn
.BI "(struct kobject *kobj "  ","
.BI "struct kobject *target "  ","
.BI "const char *name "  ");"
.SH ARGUMENTS
.IP "kobj" 12
object whose directory we're creating the link in.
.IP "target" 12
object we're pointing to.
.IP "name" 12
name of the symlink.

This function does the same as \fBsysfs_create_link\fP, but it
doesn't warn if the link already exists.
