.TH "t3_get_tp_version" 9 "t3_get_tp_version" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t3_get_tp_version \- read the tp sram version
.SH SYNOPSIS
.B "int" t3_get_tp_version
.BI "(struct adapter *adapter "  ","
.BI "u32 *vers "  ");"
.SH ARGUMENTS
.IP "adapter" 12
the adapter
.IP "vers" 12
where to place the version

Reads the protocol sram version from sram.
