.TH "t3_sge_disable_fl" 9 "t3_sge_disable_fl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t3_sge_disable_fl \- disable an SGE free-buffer list
.SH SYNOPSIS
.B "int" t3_sge_disable_fl
.BI "(struct adapter *adapter "  ","
.BI "unsigned int id "  ");"
.SH ARGUMENTS
.IP "adapter" 12
the adapter
.IP "id" 12
the free list context id

Disable an SGE free-buffer list.  The caller is responsible for
ensuring only one context operation occurs at a time.
