.TH "t3_sge_stop" 9 "t3_sge_stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t3_sge_stop \- disable SGE operation completly
.SH SYNOPSIS
.B "void" t3_sge_stop
.BI "(struct adapter *adap "  ");"
.SH ARGUMENTS
.IP "adap" 12
the adapter

Called from process context. Disables the DMA engine and any
pending queue restart tasklets.
