.TH "t3_sge_prep" 9 "t3_sge_prep" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t3_sge_prep \- one-time SGE initialization
.SH SYNOPSIS
.B "void" t3_sge_prep
.BI "(struct adapter *adap "  ","
.BI "struct sge_params *p "  ");"
.SH ARGUMENTS
.IP "adap" 12
the associated adapter
.IP "p" 12
SGE parameters

Performs one-time initialization of SGE SW state.  Includes determining
defaults for the assorted SGE parameters, which admins can change until
they are used to initialize the SGE.
