.TH "t4_free_ofld_rxqs" 9 "t4_free_ofld_rxqs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4_free_ofld_rxqs \- free a block of consecutive Rx queues
.SH SYNOPSIS
.B "void" t4_free_ofld_rxqs
.BI "(struct adapter *adap "  ","
.BI "int n "  ","
.BI "struct sge_ofld_rxq *q "  ");"
.SH ARGUMENTS
.IP "adap" 12
the adapter
.IP "n" 12
number of queues
.IP "q" 12
pointer to first queue

Release the resources of a consecutive block of offload Rx queues.
