.TH "t4_fwcache" 9 "t4_fwcache" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4_fwcache \- firmware cache operation
.SH SYNOPSIS
.B "int" t4_fwcache
.BI "(struct adapter *adap "  ","
.BI "enum fw_params_param_dev_fwcache op "  ");"
.SH ARGUMENTS
.IP "adap" 12
the adapter
.IP "op" 12
the operation (flush or flush and invalidate)
