.TH "t4_link_acaps" 9 "t4_link_acaps" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4_link_acaps \- compute Link Advertised Port Capabilities
.SH SYNOPSIS
.B "fw_port_cap32_t" t4_link_acaps
.BI "(struct adapter *adapter "  ","
.BI "unsigned int port "  ","
.BI "struct link_config *lc "  ");"
.SH ARGUMENTS
.IP "adapter" 12
the adapter
.IP "port" 12
the Port ID
.IP "lc" 12
the Port's Link Configuration

Synthesize the Advertised Port Capabilities we'll be using based on
the base Advertised Port Capabilities (which have been filtered by
ADVERT_MASK) plus the individual controls for things like Pause
Frames, Forward Error Correction, MDI, etc.
