.TH "t4_rx_hststamp" 9 "t4_rx_hststamp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4_rx_hststamp \- Recv PTP Event Message
.SH SYNOPSIS
.B "int" t4_rx_hststamp
.BI "(struct adapter *adapter "  ","
.BI "const __be64 *rsp "  ","
.BI "struct sge_eth_rxq *rxq "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "adapter" 12
the adapter
.IP "rsp" 12
the response queue descriptor holding the RX_PKT message
.IP "rxq" 12
the response queue holding the RX_PKT message
.IP "skb" 12
the packet

PTP enabled and MPS packet, read HW timestamp
