.TH "t4_sge_stop" 9 "t4_sge_stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4_sge_stop \- disable SGE operation
.SH SYNOPSIS
.B "void" t4_sge_stop
.BI "(struct adapter *adap "  ");"
.SH ARGUMENTS
.IP "adap" 12
the adapter

Stop tasklets and timers associated with the DMA engine.  Note that
this is effective only if measures have been taken to disable any HW
events that may restart them.
