.TH "t4vf_enable_vi" 9 "t4vf_enable_vi" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4vf_enable_vi \- enable/disable a virtual interface
.SH SYNOPSIS
.B "int" t4vf_enable_vi
.BI "(struct adapter *adapter "  ","
.BI "unsigned int viid "  ","
.BI "bool rx_en "  ","
.BI "bool tx_en "  ");"
.SH ARGUMENTS
.IP "adapter" 12
the adapter
.IP "viid" 12
the Virtual Interface ID
.IP "rx_en" 12
1=enable Rx, 0=disable Rx
.IP "tx_en" 12
1=enable Tx, 0=disable Tx

Enables/disables a virtual interface.
