.TH "t4vf_eth_xmit" 9 "t4vf_eth_xmit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
t4vf_eth_xmit \- add a packet to an Ethernet TX queue
.SH SYNOPSIS
.B "netdev_tx_t" t4vf_eth_xmit
.BI "(struct sk_buff *skb "  ","
.BI "struct net_device *dev "  ");"
.SH ARGUMENTS
.IP "skb" 12
the packet
.IP "dev" 12
the egress net device

Add a packet to an SGE Ethernet TX queue.  Runs with softirqs disabled.
