.TH "target_get_sess_cmd" 9 "target_get_sess_cmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
target_get_sess_cmd \- Verify the session is accepting cmds and take ref
.SH SYNOPSIS
.B "int" target_get_sess_cmd
.BI "(struct se_cmd *se_cmd "  ","
.BI "bool ack_kref "  ");"
.SH ARGUMENTS
.IP "se_cmd" 12
command descriptor to add
.IP "ack_kref" 12
Signal that fabric will perform an ack \fBtarget_put_sess_cmd\fP
