.TH "tb_domain_approve_switch" 9 "tb_domain_approve_switch" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_domain_approve_switch \- Approve switch
.SH SYNOPSIS
.B "int" tb_domain_approve_switch
.BI "(struct tb *tb "  ","
.BI "struct tb_switch *sw "  ");"
.SH ARGUMENTS
.IP "tb" 12
Domain the switch belongs to
.IP "sw" 12
Switch to approve
.SH "DESCRIPTION"
This will approve switch by connection manager specific means. In
case of success the connection manager will create PCIe tunnel from
parent to \fIsw\fP.
