.TH "tb_property_find" 9 "tb_property_find" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_property_find \- Find a property from a directory
.SH SYNOPSIS
.B "struct tb_property *" tb_property_find
.BI "(struct tb_property_dir *dir "  ","
.BI "const char *key "  ","
.BI "enum tb_property_type type "  ");"
.SH ARGUMENTS
.IP "dir" 12
Directory where the property is searched
.IP "key" 12
Key to look for
.IP "type" 12
Type of the property
.SH "DESCRIPTION"
Finds and returns property from the given directory. Does not recurse
into sub-directories. Returns NULL if the property was not found.
