.TH "tb_switch_tmu_enable" 9 "tb_switch_tmu_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_switch_tmu_enable \- Enable TMU on a switch
.SH SYNOPSIS
.B "int" tb_switch_tmu_enable
.BI "(struct tb_switch *sw "  ");"
.SH ARGUMENTS
.IP "sw" 12
Switch whose TMU to enable
.SH "DESCRIPTION"
Enables TMU of a switch to be in bi-directional, HiFi mode. In this mode
all tunneling should work.
