.TH "tb_switch_add" 9 "tb_switch_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_switch_add \- Add a switch to the domain
.SH SYNOPSIS
.B "int" tb_switch_add
.BI "(struct tb_switch *sw "  ");"
.SH ARGUMENTS
.IP "sw" 12
Switch to add
.SH "DESCRIPTION"
This is the last step in adding switch to the domain. It will read
identification information from DROM and initializes ports so that
they can be used to connect other switches. The switch will be
exposed to the userspace when this function successfully returns. To
remove and release the switch, call \fBtb_switch_remove\fP.
.SH "RETURN"
0 in case of success and negative errno in case of failure
