.TH "tb_tunnel_reclaim_available_bandwidth" 9 "tb_tunnel_reclaim_available_bandwidth" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tb_tunnel_reclaim_available_bandwidth \- Reclaim available bandwidth
.SH SYNOPSIS
.B "void" tb_tunnel_reclaim_available_bandwidth
.BI "(struct tb_tunnel *tunnel "  ","
.BI "int *available_up "  ","
.BI "int *available_down "  ");"
.SH ARGUMENTS
.IP "tunnel" 12
Tunnel reclaiming available bandwidth
.IP "available_up" 12
Available upstream bandwidth (in Mb/s)
.IP "available_down" 12
Available downstream bandwidth (in Mb/s)
.SH "DESCRIPTION"
Reclaims bandwidth from \fIavailable_up\fP and \fIavailable_down\fP and updates
the variables accordingly (e.g decreases both according to what was
reclaimed by the tunnel). If nothing was reclaimed the values are
kept as is.
