.TH "tcs_tx_done" 9 "tcs_tx_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tcs_tx_done \- TX Done interrupt handler.
.SH SYNOPSIS
.B "irqreturn_t" tcs_tx_done
.BI "(int irq "  ","
.BI "void *p "  ");"
.SH ARGUMENTS
.IP "irq" 12
The IRQ number (ignored).
.IP "p" 12
Pointer to "struct rsc_drv".
.SH "DESCRIPTION"
Called for ACTIVE_ONLY transfers (those are the only ones we enable the
IRQ for) when a transfer is done.
.SH "RETURN"
IRQ_HANDLED
