.TH "tee_bnxt_fw_load" 9 "tee_bnxt_fw_load" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tee_bnxt_fw_load \- Load the bnxt firmware Uses an OP-TEE call to start a secure boot process. Returns 0 on success, negative errno otherwise.
.SH SYNOPSIS
.B "int" tee_bnxt_fw_load
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
