.TH "tegra_dc_state_setup_clock" 9 "tegra_dc_state_setup_clock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tegra_dc_state_setup_clock \- check clock settings and store them in atomic state
.SH SYNOPSIS
.B "int" tegra_dc_state_setup_clock
.BI "(struct tegra_dc *dc "  ","
.BI "struct drm_crtc_state *crtc_state "  ","
.BI "struct clk *clk "  ","
.BI "unsigned long pclk "  ","
.BI "unsigned int div "  ");"
.SH ARGUMENTS
.IP "dc" 12
display controller
.IP "crtc_state" 12
CRTC atomic state
.IP "clk" 12
parent clock for display controller
.IP "pclk" 12
pixel clock
.IP "div" 12
shift clock divider
.SH "RETURN"
0 on success or a negative error-code on failure.
