.TH "telemetry_get_sampling_period" 9 "telemetry_get_sampling_period" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
telemetry_get_sampling_period \- Get IOSS & PSS min & max sampling period
.SH SYNOPSIS
.B "int" telemetry_get_sampling_period
.BI "(u8 *pss_min_period "  ","
.BI "u8 *pss_max_period "  ","
.BI "u8 *ioss_min_period "  ","
.BI "u8 *ioss_max_period "  ");"
.SH ARGUMENTS
.IP "pss_min_period" 12
placeholder for PSS Min Period supported
.IP "pss_max_period" 12
placeholder for PSS Max Period supported
.IP "ioss_min_period" 12
placeholder for IOSS Min Period supported
.IP "ioss_max_period" 12
placeholder for IOSS Max Period supported
.SH "DESCRIPTION"
All values should be in the form of:
bits[6:3] -> value; bits [0:2]-> Exponent; Period = (Value *16^Exponent)
.SH "RETURN"
0 success, < 0 for failure
