.TH "tep_test_flag" 9 "tep_test_flag" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tep_test_flag \- check the state of event parser flag
.SH SYNOPSIS
.B "bool" tep_test_flag
.BI "(struct tep_handle *tep "  ","
.BI "enum tep_flag flag "  ");"
.SH ARGUMENTS
.IP "tep" 12
a handle to the tep_handle
.IP "flag" 12
flag to be checked
.SH "DESCRIPTION"
This returns the state of the requested tep flag.
.SH "RETURN"
true if the flag is set, false otherwise.
