.TH "term_mc" 9 "term_mc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
term_mc \- terminates the master context
.SH SYNOPSIS
.B "void" term_mc
.BI "(struct cxlflash_cfg *cfg "  ","
.BI "u32 index "  ");"
.SH ARGUMENTS
.IP "cfg" 12
Internal structure associated with the host.
.IP "index" 12
Index of the hardware queue.
.SH "DESCRIPTION"
Safe to call with AFU/MC in partially allocated/initialized state.
