.TH "tfrc_invert_loss_event_rate" 9 "tfrc_invert_loss_event_rate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tfrc_invert_loss_event_rate \- Compute p so that 10^6 corresponds to 100% When @loss_event_rate is large, there is a chance that p is truncated to 0. To avoid re-entering slow-start in that case, we set p = TFRC_SMALLEST_P > 0.
.SH SYNOPSIS
.B "u32" tfrc_invert_loss_event_rate
.BI "(u32 loss_event_rate "  ");"
.SH ARGUMENTS
.IP "loss_event_rate" 12
-- undescribed --
