.TH "thermal_of_get_trip_type" 9 "thermal_of_get_trip_type" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
thermal_of_get_trip_type \- Get phy mode for given device_node
.SH SYNOPSIS
.B "int" thermal_of_get_trip_type
.BI "(struct device_node *np "  ","
.BI "enum thermal_trip_type *type "  ");"
.SH ARGUMENTS
.IP "np" 12
Pointer to the given device_node
.IP "type" 12
Pointer to resulting trip type
.SH "DESCRIPTION"
The function gets trip type string from property 'type',
and store its index in trip_types table in \fItype\fP,
.SH "RETURN"
0 on success, or errno in error case.
