.TH "throttlectl_cpu_level_cfg" 9 "throttlectl_cpu_level_cfg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
throttlectl_cpu_level_cfg \- programs CCROC NV_THERM level config
.SH SYNOPSIS
.B "void" throttlectl_cpu_level_cfg
.BI "(struct tegra_soctherm *ts "  ","
.BI "int level "  ");"
.SH ARGUMENTS
.IP "ts" 12
pointer to a struct tegra_soctherm
.IP "level" 12
describing the level LOW/MED/HIGH of throttling
.SH "DESCRIPTION"
It's necessary to set up the CPU-local CCROC NV_THERM instance with
the M/N values desired for each level. This function does this.

This function pre-programs the CCROC NV_THERM levels in terms of
pre-configured "Low", "Medium" or "Heavy" throttle levels which are
mapped to THROT_LEVEL_LOW, THROT_LEVEL_MED and THROT_LEVEL_HVY.
