.TH "throtl_add_bio_tg" 9 "throtl_add_bio_tg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
throtl_add_bio_tg \- add a bio to the specified throtl_grp
.SH SYNOPSIS
.B "void" throtl_add_bio_tg
.BI "(struct bio *bio "  ","
.BI "struct throtl_qnode *qn "  ","
.BI "struct throtl_grp *tg "  ");"
.SH ARGUMENTS
.IP "bio" 12
bio to add
.IP "qn" 12
qnode to use
.IP "tg" 12
the target throtl_grp
.SH "DESCRIPTION"
Add \fIbio\fP to \fItg\fP's service_queue using \fIqn\fP.  If \fIqn\fP is not specified,
tg->qnode_on_self[] is used.
