.TH "ti_clk_add_aliases" 9 "ti_clk_add_aliases" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_clk_add_aliases \- setup clock aliases
.SH SYNOPSIS
.B "void" ti_clk_add_aliases
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Sets up any missing clock aliases. No return value.
