.TH "ti_clk_add_component" 9 "ti_clk_add_component" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_clk_add_component \- add a component clock to the pool
.SH SYNOPSIS
.B "int" ti_clk_add_component
.BI "(struct device_node *node "  ","
.BI "struct clk_hw *hw "  ","
.BI "int type "  ");"
.SH ARGUMENTS
.IP "node" 12
device node of the component clock
.IP "hw" 12
hardware clock definition for the component clock
.IP "type" 12
type of the component clock
.SH "DESCRIPTION"
Adds a component clock to the list of available components, so that
it can be registered by a composite clock.
