.TH "ti_dt_clk_init_retry_clks" 9 "ti_dt_clk_init_retry_clks" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_dt_clk_init_retry_clks \- init clocks from the retry list
.SH SYNOPSIS
.B "void" ti_dt_clk_init_retry_clks
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Initializes any clocks that have failed to initialize before,
reasons being missing parent node(s) during earlier init. This
typically happens only for DPLLs which need to have both of their
parent clocks ready during init.
