.TH "ti_msgmgr_of_xlate" 9 "ti_msgmgr_of_xlate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_msgmgr_of_xlate \- Translation of phandle to queue
.SH SYNOPSIS
.B "struct mbox_chan *" ti_msgmgr_of_xlate
.BI "(struct mbox_controller *mbox "  ","
.BI "const struct of_phandle_args *p "  ");"
.SH ARGUMENTS
.IP "mbox" 12
Mailbox controller
.IP "p" 12
phandle pointer
.SH "RETURN"
Mailbox channel corresponding to the queue, else return error
pointer.
