.TH "ti_msgmgr_send_data" 9 "ti_msgmgr_send_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_msgmgr_send_data \- Send data
.SH SYNOPSIS
.B "int" ti_msgmgr_send_data
.BI "(struct mbox_chan *chan "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "chan" 12
Channel Pointer
.IP "data" 12
ti_msgmgr_message * Message Pointer
.SH "RETURN"
0 if all goes good, else appropriate error messages.
