.TH "ti_sci_clk_remove" 9 "ti_sci_clk_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_sci_clk_remove \- Remove TI SCI clock device
.SH SYNOPSIS
.B "int" ti_sci_clk_remove
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
platform device pointer for the device to be removed
.SH "DESCRIPTION"
Removes the TI SCI device. Unregisters the clock provider registered
via common clock framework. Any memory allocated for the device will
be free'd silently via the devm framework. Returns 0 always.
