.TH "ti_sci_cmd_proc_request" 9 "ti_sci_cmd_proc_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_sci_cmd_proc_request \- Command to request a physical processor control
.SH SYNOPSIS
.B "int" ti_sci_cmd_proc_request
.BI "(const struct ti_sci_handle *handle "  ","
.BI "u8 proc_id "  ");"
.SH ARGUMENTS
.IP "handle" 12
Pointer to TI SCI handle
.IP "proc_id" 12
Processor ID this request is for
.SH "RETURN"
0 if all went well, else returns appropriate error value.
