.TH "ti_sci_do_xfer" 9 "ti_sci_do_xfer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ti_sci_do_xfer \- Do one transfer
.SH SYNOPSIS
.B "int" ti_sci_do_xfer
.BI "(struct ti_sci_info *info "  ","
.BI "struct ti_sci_xfer *xfer "  ");"
.SH ARGUMENTS
.IP "info" 12
Pointer to SCI entity information
.IP "xfer" 12
Transfer to initiate and wait for response
.SH "RETURN"
-ETIMEDOUT in case of no response, if transmit error,
return corresponding error, else if all goes well,
return 0.
