.TH "timerqueue_add" 9 "timerqueue_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
timerqueue_add \- Adds timer to timerqueue.
.SH SYNOPSIS
.B "bool" timerqueue_add
.BI "(struct timerqueue_head *head "  ","
.BI "struct timerqueue_node *node "  ");"
.SH ARGUMENTS
.IP "head" 12
head of timerqueue
.IP "node" 12
timer node to be added
.SH "DESCRIPTION"
Adds the timer node to the timerqueue, sorted by the node's expires
value. Returns true if the newly added timer is the first expiring timer in
the queue.
