.TH "timekeeping_inject_offset" 9 "timekeeping_inject_offset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
timekeeping_inject_offset \- Adds or subtracts from the current time.
.SH SYNOPSIS
.B "int" timekeeping_inject_offset
.BI "(const struct timespec64 *ts "  ");"
.SH ARGUMENTS
.IP "ts" 12
Pointer to the timespec variable containing the offset
.SH "DESCRIPTION"
Adds or subtracts an offset value from the current time.
