.TH "timekeeping_notify" 9 "timekeeping_notify" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
timekeeping_notify \- Install a new clock source
.SH SYNOPSIS
.B "int" timekeeping_notify
.BI "(struct clocksource *clock "  ");"
.SH ARGUMENTS
.IP "clock" 12
pointer to the clock source
.SH "DESCRIPTION"
This function is called from clocksource.c after a new, better clock
source has been registered. The caller holds the clocksource_mutex.
