.TH "timekeeping_forward_now" 9 "timekeeping_forward_now" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
timekeeping_forward_now \- update clock to the current time
.SH SYNOPSIS
.B "void" timekeeping_forward_now
.BI "(struct timekeeper *tk "  ");"
.SH ARGUMENTS
.IP "tk" 12
Pointer to the timekeeper to update
.SH "DESCRIPTION"
Forward the current clock to update its state since the last call to
\fBupdate_wall_time\fP. This is useful before significant clock changes,
as it avoids having to deal with this time offset explicitly.
