.TH "timed_wait_for_timeout" 9 "timed_wait_for_timeout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
timed_wait_for_timeout \- wait special event with timeout
.SH SYNOPSIS
.B "int" timed_wait_for_timeout
.BI "(struct ishtp_device *dev "  ","
.BI "int condition "  ","
.BI "unsigned int timeinc "  ","
.BI "unsigned int timeout "  ");"
.SH ARGUMENTS
.IP "dev" 12
ISHTP device pointer
.IP "condition" 12
indicate the condition for waiting
.IP "timeinc" 12
time slice for every wait cycle, in ms
.IP "timeout" 12
time in ms for timeout
.SH "DESCRIPTION"
This function will check special event to be ready in a loop, the loop
period is specificd in timeinc. Wait timeout will causes failure.
.SH "RETURN"
0 for success else failure code
