.TH "tipc_sk_backlog_rcv" 9 "tipc_sk_backlog_rcv" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tipc_sk_backlog_rcv \- handle incoming message from backlog queue
.SH SYNOPSIS
.B "int" tipc_sk_backlog_rcv
.BI "(struct sock *sk "  ","
.BI "struct sk_buff *skb "  ");"
.SH ARGUMENTS
.IP "sk" 12
socket
.IP "skb" 12
message
.SH "DESCRIPTION"
Caller must hold socket lock
