.TH "tipc_sk_rcv" 9 "tipc_sk_rcv" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tipc_sk_rcv \- handle a chain of incoming buffers
.SH SYNOPSIS
.B "void" tipc_sk_rcv
.BI "(struct net *net "  ","
.BI "struct sk_buff_head *inputq "  ");"
.SH ARGUMENTS
.IP "net" 12
the associated network namespace
.IP "inputq" 12
buffer list containing the buffers
Consumes all buffers in list until inputq is empty
.SH "NOTE"
may be called in multiple threads referring to the same queue
