.TH "tk_setup_internals" 9 "tk_setup_internals" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tk_setup_internals \- Set up internals to use clocksource clock.
.SH SYNOPSIS
.B "void" tk_setup_internals
.BI "(struct timekeeper *tk "  ","
.BI "struct clocksource *clock "  ");"
.SH ARGUMENTS
.IP "tk" 12
The target timekeeper to setup.
.IP "clock" 12
Pointer to clocksource.
.SH "DESCRIPTION"
Calculates a fixed cycle/nsec interval for a given clocksource/adjustment
pair and interval request.

Unless you're the timekeeping code, you should not be using this!
