.TH "tomoyo_update_stat" 9 "tomoyo_update_stat" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_update_stat \- Update statistic counters.
.SH SYNOPSIS
.B "void" tomoyo_update_stat
.BI "(const u8 index "  ");"
.SH ARGUMENTS
.IP "index" 12
Index for policy type.
.SH "DESCRIPTION"
Returns nothing.
