.TH "tomoyo_path_matches_group" 9 "tomoyo_path_matches_group" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_path_matches_group \- Check whether the given pathname matches members of the given pathname group.
.SH SYNOPSIS
.B "const struct tomoyo_path_info *" tomoyo_path_matches_group
.BI "(const struct tomoyo_path_info *pathname "  ","
.BI "const struct tomoyo_group *group "  ");"
.SH ARGUMENTS
.IP "pathname" 12
The name of pathname.
.IP "group" 12
Pointer to "struct tomoyo_path_group".
.SH "DESCRIPTION"
Returns matched member's pathname if \fIpathname\fP matches pathnames in \fIgroup\fP,
NULL otherwise.

Caller holds \fBtomoyo_read_lock\fP.
