.TH "tomoyo_get_dqword" 9 "tomoyo_get_dqword" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_get_dqword \- tomoyo_get_name() for a quoted string.
.SH SYNOPSIS
.B "const struct tomoyo_path_info *" tomoyo_get_dqword
.BI "(char *start "  ");"
.SH ARGUMENTS
.IP "start" 12
String to save.
.SH "DESCRIPTION"
Returns pointer to "struct tomoyo_path_info" on success, NULL otherwise.
