.TH "tomoyo_file_fcntl" 9 "tomoyo_file_fcntl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_file_fcntl \- Target for security_file_fcntl().
.SH SYNOPSIS
.B "int" tomoyo_file_fcntl
.BI "(struct file *file "  ","
.BI "unsigned int cmd "  ","
.BI "unsigned long arg "  ");"
.SH ARGUMENTS
.IP "file" 12
Pointer to "struct file".
.IP "cmd" 12
Command for \fBfcntl\fP.
.IP "arg" 12
Argument for \fIcmd\fP.
.SH "DESCRIPTION"
Returns 0 on success, negative value otherwise.
