.TH "tomoyo_cred_prepare" 9 "tomoyo_cred_prepare" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_cred_prepare \- Target for security_prepare_creds().
.SH SYNOPSIS
.B "int" tomoyo_cred_prepare
.BI "(struct cred *new "  ","
.BI "const struct cred *old "  ","
.BI "gfp_t gfp "  ");"
.SH ARGUMENTS
.IP "new" 12
Pointer to "struct cred".
.IP "old" 12
Pointer to "struct cred".
.IP "gfp" 12
Memory allocation flags.
.SH "DESCRIPTION"
Returns 0.
