.TH "tomoyo_bprm_check_security" 9 "tomoyo_bprm_check_security" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_bprm_check_security \- Target for security_bprm_check().
.SH SYNOPSIS
.B "int" tomoyo_bprm_check_security
.BI "(struct linux_binprm *bprm "  ");"
.SH ARGUMENTS
.IP "bprm" 12
Pointer to "struct linux_binprm".
.SH "DESCRIPTION"
Returns 0 on success, negative value otherwise.
