.TH "tomoyo_same_path_acl" 9 "tomoyo_same_path_acl" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_same_path_acl \- Check for duplicated "struct tomoyo_path_acl" entry.
.SH SYNOPSIS
.B "bool" tomoyo_same_path_acl
.BI "(const struct tomoyo_acl_info *a "  ","
.BI "const struct tomoyo_acl_info *b "  ");"
.SH ARGUMENTS
.IP "a" 12
Pointer to "struct tomoyo_acl_info".
.IP "b" 12
Pointer to "struct tomoyo_acl_info".
.SH "DESCRIPTION"
Returns true if \fIa\fP == \fIb\fP except permission bits, false otherwise.
