.TH "tomoyo_commit_condition" 9 "tomoyo_commit_condition" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_commit_condition \- Commit "struct tomoyo_condition".
.SH SYNOPSIS
.B "struct tomoyo_condition *" tomoyo_commit_condition
.BI "(struct tomoyo_condition *entry "  ");"
.SH ARGUMENTS
.IP "entry" 12
Pointer to "struct tomoyo_condition".
.SH "DESCRIPTION"
Returns pointer to "struct tomoyo_condition" on success, NULL otherwise.

This function merges duplicated entries. This function returns NULL if
\fIentry\fP is not duplicated but memory quota for policy has exceeded.
