.TH "tomoyo_find_domain_by_qid" 9 "tomoyo_find_domain_by_qid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_find_domain_by_qid \- Get domain by query id.
.SH SYNOPSIS
.B "struct tomoyo_domain_info *" tomoyo_find_domain_by_qid
.BI "(unsigned int serial "  ");"
.SH ARGUMENTS
.IP "serial" 12
Query ID assigned by \fBtomoyo_supervisor\fP.
.SH "DESCRIPTION"
Returns pointer to "struct tomoyo_domain_info" if found, NULL otherwise.
