.TH "tomoyo_audit_net_log" 9 "tomoyo_audit_net_log" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_audit_net_log \- Audit network log.
.SH SYNOPSIS
.B "int" tomoyo_audit_net_log
.BI "(struct tomoyo_request_info *r "  ","
.BI "const char *family "  ","
.BI "const u8 protocol "  ","
.BI "const u8 operation "  ","
.BI "const char *address "  ");"
.SH ARGUMENTS
.IP "r" 12
Pointer to "struct tomoyo_request_info".
.IP "family" 12
Name of socket family ("inet" or "unix").
.IP "protocol" 12
Name of protocol in \fIfamily\fP.
.IP "operation" 12
Name of socket operation.
.IP "address" 12
Name of address.
.SH "DESCRIPTION"
Returns 0 on success, negative value otherwise.
