.TH "tomoyo_str_starts" 9 "tomoyo_str_starts" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tomoyo_str_starts \- Check whether the given string starts with the given keyword.
.SH SYNOPSIS
.B "bool" tomoyo_str_starts
.BI "(char **src "  ","
.BI "const char *find "  ");"
.SH ARGUMENTS
.IP "src" 12
Pointer to pointer to the string.
.IP "find" 12
Pointer to the keyword.
.SH "DESCRIPTION"
Returns true if \fIsrc\fP starts with \fIfind\fP, false otherwise.

The \fIsrc\fP is updated to point the first character after the \fIfind\fP
if \fIsrc\fP starts with \fIfind\fP.
