.TH "topology_phys_to_logical_pkg" 9 "topology_phys_to_logical_pkg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
topology_phys_to_logical_pkg \- Map a physical package id to a logical
.SH SYNOPSIS
.B "int" topology_phys_to_logical_pkg
.BI "(unsigned int phys_pkg "  ");"
.SH ARGUMENTS
.IP "phys_pkg" 12
-- undescribed --
.SH "DESCRIPTION"

Returns logical package id or -1 if not found
