.TH "touchscreen_set_mt_pos" 9 "touchscreen_set_mt_pos" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
touchscreen_set_mt_pos \- Set input_mt_pos coordinates
.SH SYNOPSIS
.B "void" touchscreen_set_mt_pos
.BI "(struct input_mt_pos *pos "  ","
.BI "const struct touchscreen_properties *prop "  ","
.BI "unsigned int x "  ","
.BI "unsigned int y "  ");"
.SH ARGUMENTS
.IP "pos" 12
input_mt_pos to set coordinates of
.IP "prop" 12
pointer to a struct touchscreen_properties
.IP "x" 12
X coordinate to store in pos
.IP "y" 12
Y coordinate to store in pos
.SH "DESCRIPTION"
Adjust the passed in x and y values applying any axis inversion and
swapping requested in the passed in touchscreen_properties and store
the result in a struct input_mt_pos.
