.TH "tpm1_pm_suspend" 9 "tpm1_pm_suspend" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tpm1_pm_suspend \- pm suspend handler
.SH SYNOPSIS
.B "int" tpm1_pm_suspend
.BI "(struct tpm_chip *chip "  ","
.BI "u32 tpm_suspend_pcr "  ");"
.SH ARGUMENTS
.IP "chip" 12
TPM chip to use.
.IP "tpm_suspend_pcr" 12
flush pcr for buggy TPM chips.
.SH "DESCRIPTION"
The functions saves the TPM state to be restored on resume.
.SH "RETURN"
* 0 on success,
* < 0 on error.
