.TH "tpm_class_shutdown" 9 "tpm_class_shutdown" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tpm_class_shutdown \- prepare the TPM device for loss of power.
.SH SYNOPSIS
.B "int" tpm_class_shutdown
.BI "(struct device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
device to which the chip is associated.
.SH "DESCRIPTION"
Issues a TPM2_Shutdown command prior to loss of power, as required by the
TPM 2.0 spec. Then, calls bus- and device- specific shutdown code.
.SH "RETURN"
always 0 (i.e. success)
