.TH "tpm_ibmvtpm_probe" 9 "tpm_ibmvtpm_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tpm_ibmvtpm_probe \- ibm vtpm initialize entry point
.SH SYNOPSIS
.B "int" tpm_ibmvtpm_probe
.BI "(struct vio_dev *vio_dev "  ","
.BI "const struct vio_device_id *id "  ");"
.SH ARGUMENTS
.IP "vio_dev" 12
vio device struct
.IP "id" 12
vio device id struct
.SH "RETURN"
0 on success.
Non-zero on failure.
