.TH "trace_array_init_printk" 9 "trace_array_init_printk" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
trace_array_init_printk \- Initialize buffers for trace_array_printk()
.SH SYNOPSIS
.B "int" trace_array_init_printk
.BI "(struct trace_array *tr "  ");"
.SH ARGUMENTS
.IP "tr" 12
The trace array to initialize the buffers for
.SH "DESCRIPTION"
As \fBtrace_array_printk\fP only writes into instances, they are OK to
have in the kernel (unlike \fBtrace_printk\fP). This needs to be called
before \fBtrace_array_printk\fP can be used on a trace_array.
