.TH "trace_buffered_event_disable" 9 "trace_buffered_event_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
trace_buffered_event_disable \- disable buffering events
.SH SYNOPSIS
.B "void" trace_buffered_event_disable
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

When a filter is removed, it is faster to not use the buffered
events, and to commit directly into the ring buffer. Free up
the temp buffers when there are no more users. This requires
special synchronization with current events.
