.TH "transport_class_register" 9 "transport_class_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
transport_class_register \- register an initial transport class
.SH SYNOPSIS
.B "int" transport_class_register
.BI "(struct transport_class *tclass "  ");"
.SH ARGUMENTS
.IP "tclass" 12
a pointer to the transport class structure to be initialised
.SH "DESCRIPTION"
The transport class contains an embedded class which is used to
identify it.  The caller should initialise this structure with
zeros and then generic class must have been initialised with the
actual transport class unique name.  There's a macro
\fBDECLARE_TRANSPORT_CLASS\fP to do this (declared classes still must
be registered).

Returns 0 on success or error on failure.
