.TH "triflex_prereset" 9 "triflex_prereset" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
triflex_prereset \- probe begin
.SH SYNOPSIS
.B "int" triflex_prereset
.BI "(struct ata_link *link "  ","
.BI "unsigned long deadline "  ");"
.SH ARGUMENTS
.IP "link" 12
ATA link
.IP "deadline" 12
deadline jiffies for the operation

Set up cable type and use generic probe init
