.TH "trms1040_get_data" 9 "trms1040_get_data" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
trms1040_get_data \- get a single byte from the eeprom
.SH SYNOPSIS
.B "u8" trms1040_get_data
.BI "(unsigned long io_port "  ","
.BI "u8 addr "  ");"
.SH ARGUMENTS
.IP "io_port" 12
base I/O address
.IP "addr" 12
offset into SEEPROM
.SH "DESCRIPTION"

Called from read all to read a single byte into the SSEEPROM
Which is done one bit at a time.

Returns the byte read.
