.TH "try_rgrp_unlink" 9 "try_rgrp_unlink" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
try_rgrp_unlink \- Look for any unlinked, allocated, but unused inodes
.SH SYNOPSIS
.B "void" try_rgrp_unlink
.BI "(struct gfs2_rgrpd *rgd "  ","
.BI "u64 *last_unlinked "  ","
.BI "u64 skip "  ");"
.SH ARGUMENTS
.IP "rgd" 12
The rgrp
.IP "last_unlinked" 12
block address of the last dinode we unlinked
.IP "skip" 12
block address we should explicitly not unlink
.SH "RETURN"
0 if no error
The inode, if one has been found, in inode.
