.TH "tsi721_close_outb_mbox" 9 "tsi721_close_outb_mbox" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tsi721_close_outb_mbox \- Close Tsi721 outbound mailbox
.SH SYNOPSIS
.B "void" tsi721_close_outb_mbox
.BI "(struct rio_mport *mport "  ","
.BI "int mbox "  ");"
.SH ARGUMENTS
.IP "mport" 12
Master port implementing the outbound message unit
.IP "mbox" 12
Mailbox to close
