.TH "tsi721_lcwrite" 9 "tsi721_lcwrite" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tsi721_lcwrite \- write into local SREP config space
.SH SYNOPSIS
.B "int" tsi721_lcwrite
.BI "(struct rio_mport *mport "  ","
.BI "int index "  ","
.BI "u32 offset "  ","
.BI "int len "  ","
.BI "u32 data "  ");"
.SH ARGUMENTS
.IP "mport" 12
RapidIO master port info
.IP "index" 12
ID of RapdiIO interface
.IP "offset" 12
Offset into configuration space
.IP "len" 12
Length (in bytes) of the maintenance transaction
.IP "data" 12
Value to be written
.SH "DESCRIPTION"
Generates a local write into SREP configuration space. Returns 0 on
success or -EINVAL on failure.
