.TH "tty_wait_until_sent" 9 "tty_wait_until_sent" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tty_wait_until_sent \- wait for I/O to finish
.SH SYNOPSIS
.B "void" tty_wait_until_sent
.BI "(struct tty_struct *tty "  ","
.BI "long timeout "  ");"
.SH ARGUMENTS
.IP "tty" 12
tty we are waiting for
.IP "timeout" 12
how long we will wait

Wait for characters pending in a tty driver to hit the wire, or
for a timeout to occur (eg due to flow control)

Locking: none
