.TH "tty_reopen" 9 "tty_reopen" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tty_reopen \- fast re-open of an open tty
.SH SYNOPSIS
.B "int" tty_reopen
.BI "(struct tty_struct *tty "  ");"
.SH ARGUMENTS
.IP "tty" 12
the tty to open

Return 0 on success, -errno on error.
Re-opens on master ptys are not allowed and return -EIO.

Locking: Caller must hold tty_lock
