.TH "tty_port_tty_set" 9 "tty_port_tty_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tty_port_tty_set \- set the tty of a port
.SH SYNOPSIS
.B "void" tty_port_tty_set
.BI "(struct tty_port *port "  ","
.BI "struct tty_struct *tty "  ");"
.SH ARGUMENTS
.IP "port" 12
tty port
.IP "tty" 12
the tty

Associate the port and tty pair. Manages any internal refcounts.
Pass NULL to deassociate a port
