.TH "tuner_g_tuner" 9 "tuner_g_tuner" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tuner_g_tuner \- Fill in tuner information
.SH SYNOPSIS
.B "int" tuner_g_tuner
.BI "(struct v4l2_subdev *sd "  ","
.BI "struct v4l2_tuner *vt "  ");"
.SH ARGUMENTS
.IP "sd" 12
pointer to struct v4l2_subdev
.IP "vt" 12
pointer to struct v4l2_tuner
.SH "DESCRIPTION"
At return, the structure vt will be filled with tuner information
if the tuner matches vt->type.
.SH "NOTE"
vt->type should be initialized before calling it.
This is done by either video_ioctl2 or by the bridge driver.
