.TH "tvp514x_write_regs" 9 "tvp514x_write_regs" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tvp514x_write_regs \- Initializes a list of TVP5146/47 registers
.SH SYNOPSIS
.B "int" tvp514x_write_regs
.BI "(struct v4l2_subdev *sd "  ","
.BI "const struct tvp514x_reg reglist[] "  ");"
.SH ARGUMENTS
.IP "sd" 12
ptr to v4l2_subdev struct
.IP "reglist" 12
list of TVP5146/47 registers and values
.SH "DESCRIPTION"
Initializes a list of TVP5146/47 registers:-
if token is TOK_TERM, then entire write operation terminates
if token is TOK_DELAY, then a delay of 'val' msec is introduced
if token is TOK_SKIP, then the register write is skipped
if token is TOK_WRITE, then the register write is performed
Returns zero if successful, or non-zero otherwise.
