.TH "tx_map_skb" 9 "tx_map_skb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tx_map_skb \- dma mapping for skb and return sges
.SH SYNOPSIS
.B "int" tx_map_skb
.BI "(struct hinic_dev *nic_dev "  ","
.BI "struct sk_buff *skb "  ","
.BI "struct hinic_sge *sges "  ");"
.SH ARGUMENTS
.IP "nic_dev" 12
nic device
.IP "skb" 12
the skb
.IP "sges" 12
returned sges
.SH "DESCRIPTION"
Return 0 - Success, negative - Failure
