.TH "tx_unmap_skb" 9 "tx_unmap_skb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
tx_unmap_skb \- unmap the dma address of the skb
.SH SYNOPSIS
.B "void" tx_unmap_skb
.BI "(struct hinic_dev *nic_dev "  ","
.BI "struct sk_buff *skb "  ","
.BI "struct hinic_sge *sges "  ");"
.SH ARGUMENTS
.IP "nic_dev" 12
nic device
.IP "skb" 12
the skb
.IP "sges" 12
the sges that are connected to the skb
