.TH "typec_unregister_port" 9 "typec_unregister_port" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
typec_unregister_port \- Unregister a USB Type-C Port
.SH SYNOPSIS
.B "void" typec_unregister_port
.BI "(struct typec_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
The port to be unregistered
.SH "DESCRIPTION"
Unregister device created with \fBtypec_register_port\fP.
