.TH "uart_dtr_rts" 9 "uart_dtr_rts" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uart_dtr_rts \- port helper to set uart signals
.SH SYNOPSIS
.B "void" uart_dtr_rts
.BI "(struct tty_port *tport "  ","
.BI "int onoff "  ");"
.SH ARGUMENTS
.IP "tport" 12
tty port to be updated
.IP "onoff" 12
set to turn on DTR/RTS

Called by the tty port helpers when the modem signals need to be
adjusted during an open, close and hangup.
