.TH "uart_console_write" 9 "uart_console_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uart_console_write \- write a console message to a serial port
.SH SYNOPSIS
.B "void" uart_console_write
.BI "(struct uart_port *port "  ","
.BI "const char *s "  ","
.BI "unsigned int count "  ","
.BI "void (*putchar)(struct uart_port *, int) "  ");"
.SH ARGUMENTS
.IP "port" 12
the port to write the message
.IP "s" 12
array of characters
.IP "count" 12
number of characters in string to write
.IP "putchar" 12
function to write character to port
