.TH "ubi_calculate_reserved" 9 "ubi_calculate_reserved" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubi_calculate_reserved \- calculate how many PEBs must be reserved for bad eraseblock handling.
.SH SYNOPSIS
.B "void" ubi_calculate_reserved
.BI "(struct ubi_device *ubi "  ");"
.SH ARGUMENTS
.IP "ubi" 12
UBI device description object
