.TH "ubi_check_pattern" 9 "ubi_check_pattern" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubi_check_pattern \- check if buffer contains only a certain byte pattern.
.SH SYNOPSIS
.B "int" ubi_check_pattern
.BI "(const void *buf "  ","
.BI "uint8_t patt "  ","
.BI "int size "  ");"
.SH ARGUMENTS
.IP "buf" 12
buffer to check
.IP "patt" 12
the pattern to check
.IP "size" 12
buffer size in bytes
.SH "DESCRIPTION"
This function returns 1 in there are only \fIpatt\fP bytes in \fIbuf\fP, and 0 if
something else was also found.
