.TH "ubifs_debugging_init" 9 "ubifs_debugging_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubifs_debugging_init \- initialize UBIFS debugging.
.SH SYNOPSIS
.B "int" ubifs_debugging_init
.BI "(struct ubifs_info *c "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.SH "DESCRIPTION"
This function initializes debugging-related data for the file system.
Returns zero in case of success and a negative error code in case of
failure.
