.TH "ubifs_log_end_commit" 9 "ubifs_log_end_commit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubifs_log_end_commit \- end commit.
.SH SYNOPSIS
.B "int" ubifs_log_end_commit
.BI "(struct ubifs_info *c "  ","
.BI "int ltail_lnum "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "ltail_lnum" 12
new log tail LEB number
.SH "DESCRIPTION"
This function is called on when the commit operation was finished. It
moves log tail to new position and updates the master node so that it stores
the new log tail LEB number. Returns zero in case of success and a negative
error code in case of failure.
