.TH "ubifs_ro_mode" 9 "ubifs_ro_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubifs_ro_mode \- switch UBIFS to read read-only mode.
.SH SYNOPSIS
.B "void" ubifs_ro_mode
.BI "(struct ubifs_info *c "  ","
.BI "int err "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "err" 12
error code which is the reason of switching to R/O mode
