.TH "ubifs_tnc_read_node" 9 "ubifs_tnc_read_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubifs_tnc_read_node \- read a leaf node from the flash media.
.SH SYNOPSIS
.B "int" ubifs_tnc_read_node
.BI "(struct ubifs_info *c "  ","
.BI "struct ubifs_zbranch *zbr "  ","
.BI "void *node "  ");"
.SH ARGUMENTS
.IP "c" 12
UBIFS file-system description object
.IP "zbr" 12
key and position of the node
.IP "node" 12
node is returned here
.SH "DESCRIPTION"
This function reads a node defined by \fIzbr\fP from the flash media. Returns
zero in case of success or a negative error code in case of failure.
