.TH "ubifs_read_one_lp" 9 "ubifs_read_one_lp" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubifs_read_one_lp \- read LEB properties.
.SH SYNOPSIS
.B "int" ubifs_read_one_lp
.BI "(struct ubifs_info *c "  ","
.BI "int lnum "  ","
.BI "struct ubifs_lprops *lp "  ");"
.SH ARGUMENTS
.IP "c" 12
the UBIFS file-system description object
.IP "lnum" 12
LEB to read properties for
.IP "lp" 12
where to store read properties
.SH "DESCRIPTION"
This helper function reads properties of a LEB \fIlnum\fP and stores them in \fIlp\fP.
Returns zero in case of success and a negative error code in case of
failure.
