.TH "ubifs_save_dirty_idx_lnums" 9 "ubifs_save_dirty_idx_lnums" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ubifs_save_dirty_idx_lnums \- save an array of the most dirty index LEB nos.
.SH SYNOPSIS
.B "int" ubifs_save_dirty_idx_lnums
.BI "(struct ubifs_info *c "  ");"
.SH ARGUMENTS
.IP "c" 12
the UBIFS file-system description object
.SH "DESCRIPTION"
This function is called each commit to create an array of LEB numbers of
dirty index LEBs sorted in order of dirty and free space.  This is used by
the in-the-gaps method of TNC commit.
