.TH "ufshcd_wait_for_uic_cmd" 9 "ufshcd_wait_for_uic_cmd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_wait_for_uic_cmd \- Wait complectioin of UIC command
.SH SYNOPSIS
.B "int" ufshcd_wait_for_uic_cmd
.BI "(struct ufs_hba *hba "  ","
.BI "struct uic_command *uic_cmd "  ");"
.SH ARGUMENTS
.IP "hba" 12
per adapter instance
.IP "uic_cmd" 12
UIC command
.SH "DESCRIPTION"
Must be called with mutex held.
Returns 0 only if success.
