.TH "ufshcd_disable_intr_aggr" 9 "ufshcd_disable_intr_aggr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_disable_intr_aggr \- Disables interrupt aggregation.
.SH SYNOPSIS
.B "void" ufshcd_disable_intr_aggr
.BI "(struct ufs_hba *hba "  ");"
.SH ARGUMENTS
.IP "hba" 12
per adapter instance
