.TH "ufshcd_send_command" 9 "ufshcd_send_command" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_send_command \- Send SCSI or device management commands
.SH SYNOPSIS
.B "void" ufshcd_send_command
.BI "(struct ufs_hba *hba "  ","
.BI "unsigned int task_tag "  ");"
.SH ARGUMENTS
.IP "hba" 12
per adapter instance
.IP "task_tag" 12
Task tag of the command
