.TH "ufshcd_make_hba_operational" 9 "ufshcd_make_hba_operational" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_make_hba_operational \- Make UFS controller operational
.SH SYNOPSIS
.B "int" ufshcd_make_hba_operational
.BI "(struct ufs_hba *hba "  ");"
.SH ARGUMENTS
.IP "hba" 12
per adapter instance
.SH "DESCRIPTION"
To bring UFS host controller to operational state,
1. Enable required interrupts
2. Configure interrupt aggregation
3. Program UTRL and UTMRL base address
4. Configure run-stop-registers

Returns 0 on success, non-zero value on failure
