.TH "ufshcd_reset_and_restore" 9 "ufshcd_reset_and_restore" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
ufshcd_reset_and_restore \- reset and re-initialize host/device
.SH SYNOPSIS
.B "int" ufshcd_reset_and_restore
.BI "(struct ufs_hba *hba "  ");"
.SH ARGUMENTS
.IP "hba" 12
per-adapter instance
.SH "DESCRIPTION"
Reset and recover device, host and re-establish link. This
is helpful to recover the communication in fatal error conditions.

Returns zero on success, non-zero on failure
