.TH "unexpected_offload" 9 "unexpected_offload" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
unexpected_offload \- handle an unexpected offload packet
.SH SYNOPSIS
.B "void" unexpected_offload
.BI "(struct adapter *adapter "  ","
.BI "struct freelQ *fl "  ");"
.SH ARGUMENTS
.IP "adapter" 12
the adapter
.IP "fl" 12
the free list that received the packet

Called when we receive an unexpected offload packet (e.g., the TOE
function is disabled or the card is a NIC).  Prints a message and
recycles the buffer.
