.TH "unpoison_memory" 9 "unpoison_memory" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
unpoison_memory \- Unpoison a previously poisoned page
.SH SYNOPSIS
.B "int" unpoison_memory
.BI "(unsigned long pfn "  ");"
.SH ARGUMENTS
.IP "pfn" 12
Page number of the to be unpoisoned page
.SH "DESCRIPTION"
Software-unpoison a page that has been poisoned by
\fBmemory_failure\fP earlier.

This is only done on the software-level, so it only works
for linux injected failures, not real hardware failures

Returns 0 for success, otherwise -errno.
