.TH "unwind_trap" 9 "unwind_trap" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
unwind_trap \- Unwind through a system trap, that stored previous state on the stack.
.SH SYNOPSIS
.B "void" unwind_trap
.BI "(struct task_struct *task "  ","
.BI "unsigned long pc "  ","
.BI "unsigned long fp "  ","
.BI "struct stack_trace *trace "  ","
.BI "const char *loglvl "  ");"
.SH ARGUMENTS
.IP "task" 12
-- undescribed --
.IP "pc" 12
-- undescribed --
.IP "fp" 12
-- undescribed --
.IP "trace" 12
-- undescribed --
.IP "loglvl" 12
-- undescribed --
