.TH "update_fastmap_work_fn" 9 "update_fastmap_work_fn" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
update_fastmap_work_fn \- calls ubi_update_fastmap from a work queue
.SH SYNOPSIS
.B "void" update_fastmap_work_fn
.BI "(struct work_struct *wrk "  ");"
.SH ARGUMENTS
.IP "wrk" 12
the work description object
