.TH "usb4_usb3_port_actual_link_rate" 9 "usb4_usb3_port_actual_link_rate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb4_usb3_port_actual_link_rate \- Established USB3 link rate
.SH SYNOPSIS
.B "int" usb4_usb3_port_actual_link_rate
.BI "(struct tb_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
USB3 adapter port
.SH "DESCRIPTION"
Return actual established link rate of a USB3 adapter in Mb/s. If the
link is not up returns 0 and negative errno in case of failure.
