.TH "usb4_port_retimer_is_last" 9 "usb4_port_retimer_is_last" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb4_port_retimer_is_last \- Is the retimer last on-board retimer
.SH SYNOPSIS
.B "int" usb4_port_retimer_is_last
.BI "(struct tb_port *port "  ","
.BI "u8 index "  ");"
.SH ARGUMENTS
.IP "port" 12
USB4 port
.IP "index" 12
Retimer index
.SH "DESCRIPTION"
If the retimer at \fIindex\fP is last one (connected directly to the
Type-C port) this function returns 1. If it is not returns 0. If
the retimer is not present returns -ENODEV. Otherwise returns
negative errno.
