.TH "usb4_usb3_port_allocated_bandwidth" 9 "usb4_usb3_port_allocated_bandwidth" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb4_usb3_port_allocated_bandwidth \- Bandwidth allocated for USB3
.SH SYNOPSIS
.B "int" usb4_usb3_port_allocated_bandwidth
.BI "(struct tb_port *port "  ","
.BI "int *upstream_bw "  ","
.BI "int *downstream_bw "  ");"
.SH ARGUMENTS
.IP "port" 12
USB3 adapter port
.IP "upstream_bw" 12
Allocated upstream bandwidth is stored here
.IP "downstream_bw" 12
Allocated downstream bandwidth is stored here
.SH "DESCRIPTION"
Stores currently allocated USB3 bandwidth into \fIupstream_bw\fP and
\fIdownstream_bw\fP in Mb/s. Returns 0 in case of success and negative
errno in failure.
