.TH "usb_ep_clear_halt" 9 "usb_ep_clear_halt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_ep_clear_halt \- clears endpoint halt, and resets toggle
.SH SYNOPSIS
.B "int" usb_ep_clear_halt
.BI "(struct usb_ep *ep "  ");"
.SH ARGUMENTS
.IP "ep" 12
the bulk or interrupt endpoint being reset
.SH "DESCRIPTION"
Use this when responding to the standard usb "set interface" request,
for endpoints that aren't reconfigured, after clearing any other state
in the endpoint's i/o queue.

This routine may be called in interrupt context.

Returns zero, or a negative error code.  On success, this call clears
the underlying hardware state reflecting endpoint halt and data toggle.
Note that some hardware can't support this request (like pxa2xx_udc),
and accordingly can't correctly implement interface altsettings.
