.TH "usb_role_switch_unregister" 9 "usb_role_switch_unregister" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_role_switch_unregister \- Unregsiter USB Role Switch
.SH SYNOPSIS
.B "void" usb_role_switch_unregister
.BI "(struct usb_role_switch *sw "  ");"
.SH ARGUMENTS
.IP "sw" 12
USB Role Switch
.SH "DESCRIPTION"
Unregister switch that was registered with \fBusb_role_switch_register\fP.
