.TH "usb_find_alt_setting" 9 "usb_find_alt_setting" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_find_alt_setting \- Given a configuration, find the alternate setting for the given interface.
.SH SYNOPSIS
.B "struct usb_host_interface *" usb_find_alt_setting
.BI "(struct usb_host_config *config "  ","
.BI "unsigned int iface_num "  ","
.BI "unsigned int alt_num "  ");"
.SH ARGUMENTS
.IP "config" 12
the configuration to search (not necessarily the current config).
.IP "iface_num" 12
interface number to search in
.IP "alt_num" 12
alternate interface setting number to search for.
.SH "DESCRIPTION"
Search the configuration's interface cache for the given alt setting.
.SH "RETURN"
The alternate setting, if found. NULL otherwise.
