.TH "usb_gadget_giveback_request" 9 "usb_gadget_giveback_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_gadget_giveback_request \- give the request back to the gadget layer
.SH SYNOPSIS
.B "void" usb_gadget_giveback_request
.BI "(struct usb_ep *ep "  ","
.BI "struct usb_request *req "  ");"
.SH ARGUMENTS
.IP "ep" 12
the endpoint to be used with with the request
.IP "req" 12
the request being given back
.SH "DESCRIPTION"
This is called by device controller drivers in order to return the
completed request back to the gadget layer.
