.TH "usb_remove_hcd" 9 "usb_remove_hcd" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_remove_hcd \- shutdown processing for generic HCDs
.SH SYNOPSIS
.B "void" usb_remove_hcd
.BI "(struct usb_hcd *hcd "  ");"
.SH ARGUMENTS
.IP "hcd" 12
the usb_hcd structure to remove
.SH "CONTEXT"
task context, might sleep.
.SH "DESCRIPTION"
Disconnects the root hub, then reverses the effects of \fBusb_add_hcd\fP,
invoking the HCD's \fBstop\fP method.
