.TH "usb_get_urb" 9 "usb_get_urb" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_get_urb \- increments the reference count of the urb
.SH SYNOPSIS
.B "struct urb *" usb_get_urb
.BI "(struct urb *urb "  ");"
.SH ARGUMENTS
.IP "urb" 12
pointer to the urb to modify, may be NULL
.SH "DESCRIPTION"
This must be  called whenever a urb is transferred from a device driver to a
host controller driver.  This allows proper reference counting to happen
for urbs.
.SH "RETURN"
A pointer to the urb with the incremented reference counter.
