.TH "usb_get_gadget_udc_name" 9 "usb_get_gadget_udc_name" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
usb_get_gadget_udc_name \- get the name of the first UDC controller This functions returns the name of the first UDC controller in the system. Please note that this interface is usefull only for legacy drivers which assume that there is only one UDC controller in the system and they need to get its name before initialization. There is no guarantee that the UDC of the returned name will be still available, when gadget driver registers itself.
.SH SYNOPSIS
.B "char *" usb_get_gadget_udc_name
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

Returns pointer to string with UDC controller name on success, NULL
otherwise. Caller should \fBkfree\fP returned string.
