.TH "user_exp_rcv_invalid" 9 "user_exp_rcv_invalid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
user_exp_rcv_invalid \- Invalidate the given tid rcv list
.SH SYNOPSIS
.B "int" user_exp_rcv_invalid
.BI "(struct hfi1_filedata *fd "  ","
.BI "unsigned long arg "  ","
.BI "u32 len "  ");"
.SH ARGUMENTS
.IP "fd" 12
file data of the current driver instance
.IP "arg" 12
ioctl argumnent for user space information
.IP "len" 12
length of data structure associated with ioctl command
.SH "DESCRIPTION"
Wrapper to validate ioctl information before doing _rcv_invalid.
