.TH "uvd_v7_0_ring_emit_hdp_flush" 9 "uvd_v7_0_ring_emit_hdp_flush" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uvd_v7_0_ring_emit_hdp_flush \- skip HDP flushing
.SH SYNOPSIS
.B "void" uvd_v7_0_ring_emit_hdp_flush
.BI "(struct amdgpu_ring *ring "  ");"
.SH ARGUMENTS
.IP "ring" 12
amdgpu_ring pointer
