.TH "uvd_v5_0_mc_resume" 9 "uvd_v5_0_mc_resume" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uvd_v5_0_mc_resume \- memory controller programming
.SH SYNOPSIS
.B "void" uvd_v5_0_mc_resume
.BI "(struct amdgpu_device *adev "  ");"
.SH ARGUMENTS
.IP "adev" 12
amdgpu_device pointer
.SH "DESCRIPTION"
Let the UVD memory controller know it's offsets
