.TH "uvd_v7_0_enc_get_destroy_msg" 9 "uvd_v7_0_enc_get_destroy_msg" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
uvd_v7_0_enc_get_destroy_msg \- generate a UVD ENC destroy msg
.SH SYNOPSIS
.B "int" uvd_v7_0_enc_get_destroy_msg
.BI "(struct amdgpu_ring *ring "  ","
.BI "uint32_t handle "  ","
.BI "struct amdgpu_bo *bo "  ","
.BI "struct dma_fence **fence "  ");"
.SH ARGUMENTS
.IP "ring" 12
ring we should submit the msg to
.IP "handle" 12
session handle to use
.IP "bo" 12
amdgpu object for which we query the offset
.IP "fence" 12
optional fence to return
.SH "DESCRIPTION"
Close up a stream for HW test or if userspace failed to do so
