.TH "v4l2_jpeg_parse_huffman_tables" 9 "v4l2_jpeg_parse_huffman_tables" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
v4l2_jpeg_parse_huffman_tables \- parse huffman tables segment
.SH SYNOPSIS
.B "int" v4l2_jpeg_parse_huffman_tables
.BI "(void *buf "  ","
.BI "size_t len "  ","
.BI "struct v4l2_jpeg_reference *huffman_tables "  ");"
.SH ARGUMENTS
.IP "buf" 12
address of the Huffman table segment, after the DHT marker
.IP "len" 12
length of the Huffman table segment
.IP "huffman_tables" 12
returns four references into the buffer for the
four possible Huffman table destinations, in
the order DC0, DC1, AC0, AC1
.SH "DESCRIPTION"
Returns 0 or negative error if parsing failed.
