.TH "v4l2_m2m_try_run" 9 "v4l2_m2m_try_run" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
v4l2_m2m_try_run \- select next job to perform and run it if possible
.SH SYNOPSIS
.B "void" v4l2_m2m_try_run
.BI "(struct v4l2_m2m_dev *m2m_dev "  ");"
.SH ARGUMENTS
.IP "m2m_dev" 12
per-device context
.SH "DESCRIPTION"
Get next transaction (if present) from the waiting jobs list and run it.

Note that this function can run on a given v4l2_m2m_ctx context,
but call .device_run for another context.
