.TH "v9fs_set_super" 9 "v9fs_set_super" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
v9fs_set_super \- set the superblock
.SH SYNOPSIS
.B "int" v9fs_set_super
.BI "(struct super_block *s "  ","
.BI "void *data "  ");"
.SH ARGUMENTS
.IP "s" 12
super block
.IP "data" 12
file system specific data
