.TH "vcc_event" 9 "vcc_event" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vcc_event \- LDC event processing engine
.SH SYNOPSIS
.B "void" vcc_event
.BI "(void *arg "  ","
.BI "int event "  ");"
.SH ARGUMENTS
.IP "arg" 12
VCC private data
.IP "event" 12
LDC event
.SH "DESCRIPTION"
Handles LDC events for VCC
