.TH "vcn_v1_0_dec_ring_insert_start" 9 "vcn_v1_0_dec_ring_insert_start" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vcn_v1_0_dec_ring_insert_start \- insert a start command
.SH SYNOPSIS
.B "void" vcn_v1_0_dec_ring_insert_start
.BI "(struct amdgpu_ring *ring "  ");"
.SH ARGUMENTS
.IP "ring" 12
amdgpu_ring pointer
.SH "DESCRIPTION"
Write a start command to the ring.
