.TH "vega10_fan_ctrl_set_default_mode" 9 "vega10_fan_ctrl_set_default_mode" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vega10_fan_ctrl_set_default_mode \- Reset Fan Speed Control to default mode.
.SH SYNOPSIS
.B "int" vega10_fan_ctrl_set_default_mode
.BI "(struct pp_hwmgr *hwmgr "  ");"
.SH ARGUMENTS
.IP "hwmgr" 12
the address of the powerplay hardware manager.
Exception: Should always succeed.
