.TH "vega20_thermal_enable_alert" 9 "vega20_thermal_enable_alert" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vega20_thermal_enable_alert \- Enable thermal alerts on the RV770 thermal controller.
.SH SYNOPSIS
.B "int" vega20_thermal_enable_alert
.BI "(struct pp_hwmgr *hwmgr "  ");"
.SH ARGUMENTS
.IP "hwmgr" 12
The address of the hardware manager.
