.TH "vema_register" 9 "vema_register" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vema_register \- - Registers agent
.SH SYNOPSIS
.B "int" vema_register
.BI "(struct opa_vnic_ctrl_port *cport "  ");"
.SH ARGUMENTS
.IP "cport" 12
pointer to control port
.SH "DESCRIPTION"
This function registers the handlers for the VEMA MADs
.SH "RETURN"
returns 0 on success. non zero otherwise
