.TH "vfree_atomic" 9 "vfree_atomic" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vfree_atomic \- release memory allocated by vmalloc()
.SH SYNOPSIS
.B "void" vfree_atomic
.BI "(const void *addr "  ");"
.SH ARGUMENTS
.IP "addr" 12
memory base address
.SH "DESCRIPTION"
This one is just like \fBvfree\fP but can be called in any atomic context
except NMIs.
