.TH "vfs_cancel_lock" 9 "vfs_cancel_lock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vfs_cancel_lock \- file byte range unblock lock
.SH SYNOPSIS
.B "int" vfs_cancel_lock
.BI "(struct file *filp "  ","
.BI "struct file_lock *fl "  ");"
.SH ARGUMENTS
.IP "filp" 12
The file to apply the unblock to
.IP "fl" 12
The lock to be unblocked
.SH "DESCRIPTION"
Used by lock managers to cancel blocked requests
