.TH "vga_switcheroo_unregister_client" 9 "vga_switcheroo_unregister_client" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vga_switcheroo_unregister_client \- unregister client
.SH SYNOPSIS
.B "void" vga_switcheroo_unregister_client
.BI "(struct pci_dev *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
client pci device
.SH "DESCRIPTION"
Unregister client. Disable vga_switcheroo if this is a vga client (GPU).
