.TH "vhost_iotlb_itree_first" 9 "vhost_iotlb_itree_first" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vhost_iotlb_itree_first \- return the first overlapped range
.SH SYNOPSIS
.B "struct vhost_iotlb_map *" vhost_iotlb_itree_first
.BI "(struct vhost_iotlb *iotlb "  ","
.BI "u64 start "  ","
.BI "u64 last "  ");"
.SH ARGUMENTS
.IP "iotlb" 12
the IOTLB
.IP "start" 12
start of IOVA range
.IP "last" 12
last byte in IOVA range
