.TH "videobuf_dma_contig_user_get" 9 "videobuf_dma_contig_user_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
videobuf_dma_contig_user_get \- setup user space memory pointer
.SH SYNOPSIS
.B "int" videobuf_dma_contig_user_get
.BI "(struct videobuf_dma_contig_memory *mem "  ","
.BI "struct videobuf_buffer *vb "  ");"
.SH ARGUMENTS
.IP "mem" 12
per-buffer private videobuf-dma-contig data
.IP "vb" 12
video buffer to map
.SH "DESCRIPTION"
This function validates and sets up a pointer to user space memory.
Only physically contiguous pfn-mapped memory is accepted.

Returns 0 if successful.
