.TH "vimc_streamer_pipeline_init" 9 "vimc_streamer_pipeline_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vimc_streamer_pipeline_init \- Initializes the stream structure
.SH SYNOPSIS
.B "int" vimc_streamer_pipeline_init
.BI "(struct vimc_stream *stream "  ","
.BI "struct vimc_ent_device *ved "  ");"
.SH ARGUMENTS
.IP "stream" 12
the pointer to the stream structure to be initialized
.IP "ved" 12
the pointer to the vimc entity initializing the stream
.SH "DESCRIPTION"
Initializes the stream structure. Walks through the entity graph to
construct the pipeline used later on the streamer thread.
Calls \fBvimc_streamer_s_stream\fP to enable stream in all entities of
the pipeline.
.SH "RETURN"
0 if success, error code otherwise.
