.TH "visorchannel_signalinsert" 9 "visorchannel_signalinsert" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
visorchannel_signalinsert \- inserts a message into the designated channel/queue
.SH SYNOPSIS
.B "int" visorchannel_signalinsert
.BI "(struct visorchannel *channel "  ","
.BI "u32 queue "  ","
.BI "void *msg "  ");"
.SH ARGUMENTS
.IP "channel" 12
the channel the message will be added to
.IP "queue" 12
the queue the message will be added to
.IP "msg" 12
the message to insert
.SH "RETURN"
integer error code indicating the status of the insertion
