.TH "vm_unmap_ram" 9 "vm_unmap_ram" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vm_unmap_ram \- unmap linear kernel address space set up by vm_map_ram
.SH SYNOPSIS
.B "void" vm_unmap_ram
.BI "(const void *mem "  ","
.BI "unsigned int count "  ");"
.SH ARGUMENTS
.IP "mem" 12
the pointer returned by vm_map_ram
.IP "count" 12
the count passed to that vm_map_ram call (cannot unmap partial)
