.TH "vmalloc_node" 9 "vmalloc_node" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmalloc_node \- allocate memory on a specific node
.SH SYNOPSIS
.B "void *" vmalloc_node
.BI "(unsigned long size "  ","
.BI "int node "  ");"
.SH ARGUMENTS
.IP "size" 12
allocation size
.IP "node" 12
numa node
.SH "DESCRIPTION"
Allocate enough pages to cover \fIsize\fP from the page level
allocator and map them into contiguous kernel virtual space.

For tight control over page level allocator and protection flags
use \fB__vmalloc\fP instead.
.SH "RETURN"
pointer to the allocated memory or NULL on error
