.TH "vmballoon_status_page" 9 "vmballoon_status_page" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmballoon_status_page \- returns the status of (un)lock operation
.SH SYNOPSIS
.B "unsigned long" vmballoon_status_page
.BI "(struct vmballoon *b "  ","
.BI "int idx "  ","
.BI "struct page **p "  ");"
.SH ARGUMENTS
.IP "b" 12
pointer to the balloon.
.IP "idx" 12
index for the page for which the operation is performed.
.IP "p" 12
pointer to where the page struct is returned.
.SH "DESCRIPTION"
Following a lock or unlock operation, returns the status of the operation for
an individual page. Provides the page that the operation was performed on on
the \fIpage\fP argument.
.SH "RETURN"
The status of a lock or unlock operation for an individual page.
