.TH "vmballoon_send_get_target" 9 "vmballoon_send_get_target" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmballoon_send_get_target \- Retrieve desired balloon size from the host.
.SH SYNOPSIS
.B "int" vmballoon_send_get_target
.BI "(struct vmballoon *b "  ");"
.SH ARGUMENTS
.IP "b" 12
pointer to the balloon.
.SH "RETURN"
zero on success, EINVAL if limit does not fit in 32-bit, as required
by the host-guest protocol and EIO if an error occurred in communicating with
the host.
