.TH "vme_dma_list_exec" 9 "vme_dma_list_exec" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vme_dma_list_exec \- Queue a VME DMA list for execution.
.SH SYNOPSIS
.B "int" vme_dma_list_exec
.BI "(struct vme_dma_list *list "  ");"
.SH ARGUMENTS
.IP "list" 12
Pointer to VME list.
.SH "DESCRIPTION"
Queue the provided VME DMA list for execution. The call will return once the
list has been executed.
.SH "RETURN"
Zero on success, -EINVAL if operation is not supported on this
device. Hardware specific errors also possible.
