.TH "vme_lm_count" 9 "vme_lm_count" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vme_lm_count \- Determine number of VME Addresses monitored
.SH SYNOPSIS
.B "int" vme_lm_count
.BI "(struct vme_resource *resource "  ");"
.SH ARGUMENTS
.IP "resource" 12
Pointer to VME location monitor resource.
.SH "DESCRIPTION"
The number of contiguous addresses monitored is hardware dependent.
Return the number of contiguous addresses monitored by the
location monitor.
.SH "RETURN"
Count of addresses monitored or -EINVAL when provided with an
invalid location monitor resource.
