.TH "vmmouse_detect" 9 "vmmouse_detect" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmmouse_detect \- Probe whether vmmouse is available
.SH SYNOPSIS
.B "int" vmmouse_detect
.BI "(struct psmouse *psmouse "  ","
.BI "bool set_properties "  ");"
.SH ARGUMENTS
.IP "psmouse" 12
Pointer to the psmouse struct
.IP "set_properties" 12
Whether to set psmouse name and vendor
.SH "DESCRIPTION"
Returns 0 if vmmouse channel is available. Negative error code if not.
