.TH "vmw_view_id_ok" 9 "vmw_view_id_ok" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_view_id_ok \- Basic view id and type range checks.
.SH SYNOPSIS
.B "bool" vmw_view_id_ok
.BI "(u32 user_key "  ","
.BI "enum vmw_view_type view_type "  ");"
.SH ARGUMENTS
.IP "user_key" 12
The user-space id used for the view.
.IP "view_type" 12
The view type.
.SH "DESCRIPTION"
Checks that the view id and type (typically provided by user-space) is
valid.
