.TH "vmw_guess_mode_timing" 9 "vmw_guess_mode_timing" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_guess_mode_timing \- Provide fake timings for a 60Hz vrefresh mode.
.SH SYNOPSIS
.B "void" vmw_guess_mode_timing
.BI "(struct drm_display_mode *mode "  ");"
.SH ARGUMENTS
.IP "mode" 12
-- undescribed --
.SH "DESCRIPTION"

\fImode\fP - Pointer to a struct drm_display_mode with hdisplay and vdisplay
members filled in.
