.TH "vmw_user_bo_release" 9 "vmw_user_bo_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_user_bo_release \- TTM reference base object release callback for vmw user buffer objects
.SH SYNOPSIS
.B "void" vmw_user_bo_release
.BI "(struct ttm_base_object **p_base "  ");"
.SH ARGUMENTS
.IP "p_base" 12
The TTM base object pointer about to be unreferenced.
.SH "DESCRIPTION"
Clears the TTM base object pointer and drops the reference the
base object has on the underlying struct vmw_buffer_object.
