.TH "vmw_dx_streamoutput_lookup" 9 "vmw_dx_streamoutput_lookup" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_dx_streamoutput_lookup \- Do a streamoutput resource lookup by user key.
.SH SYNOPSIS
.B "struct vmw_resource *" vmw_dx_streamoutput_lookup
.BI "(struct vmw_cmdbuf_res_manager *man "  ","
.BI "u32 user_key "  ");"
.SH ARGUMENTS
.IP "man" 12
Command buffer managed resource manager for current context.
.IP "user_key" 12
User-space identifier for lookup.
.SH "RETURN"
Valid refcounted vmw_resource on success, error pointer on failure.
