.TH "vmw_bo_get_guest_ptr" 9 "vmw_bo_get_guest_ptr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_bo_get_guest_ptr \- Get the guest ptr representing the current placement of a buffer.
.SH SYNOPSIS
.B "void" vmw_bo_get_guest_ptr
.BI "(const struct ttm_buffer_object *bo "  ","
.BI "SVGAGuestPtr *ptr "  ");"
.SH ARGUMENTS
.IP "bo" 12
Pointer to a struct ttm_buffer_object. Must be pinned or reserved.
.IP "ptr" 12
SVGAGuestPtr returning the result.
