.TH "vmw_dx_shader_create" 9 "vmw_dx_shader_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_dx_shader_create \- The DX shader create callback
.SH SYNOPSIS
.B "int" vmw_dx_shader_create
.BI "(struct vmw_resource *res "  ");"
.SH ARGUMENTS
.IP "res" 12
The DX shader resource
.SH "DESCRIPTION"
The create callback is called as part of resource validation and
makes sure that we unscrub the shader if it's previously been scrubbed.
