.TH "vmw_context_binding_state" 9 "vmw_context_binding_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_context_binding_state \-  Return a pointer to a context binding state structure
.SH SYNOPSIS
.B "struct vmw_ctx_binding_state *" vmw_context_binding_state
.BI "(struct vmw_resource *ctx "  ");"
.SH ARGUMENTS
.IP "ctx" 12
The context resource
.SH "DESCRIPTION"
Returns the current state of bindings of the given context. Note that
this state becomes stale as soon as the dev_priv::binding_mutex is unlocked.
