.TH "vmw_cotable_destroy" 9 "vmw_cotable_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_cotable_destroy \- Cotable resource destroy callback
.SH SYNOPSIS
.B "int" vmw_cotable_destroy
.BI "(struct vmw_resource *res "  ");"
.SH ARGUMENTS
.IP "res" 12
Pointer to the cotable resource.
.SH "DESCRIPTION"
There is no device cotable destroy command, so this function only
makes sure that the resource id is set to invalid.
