.TH "vmw_kms_lost_device" 9 "vmw_kms_lost_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_kms_lost_device \- Notify kms that modesetting capabilities will be lost
.SH SYNOPSIS
.B "void" vmw_kms_lost_device
.BI "(struct drm_device *dev "  ");"
.SH ARGUMENTS
.IP "dev" 12
Pointer to the drm device
