.TH "vmw_stdu_define_st" 9 "vmw_stdu_define_st" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_stdu_define_st \- Defines a Screen Target
.SH SYNOPSIS
.B "int" vmw_stdu_define_st
.BI "(struct vmw_private *dev_priv "  ","
.BI "struct vmw_screen_target_display_unit *stdu "  ","
.BI "struct drm_display_mode *mode "  ","
.BI "int crtc_x "  ","
.BI "int crtc_y "  ");"
.SH ARGUMENTS
.IP "dev_priv" 12
VMW DRM device
.IP "stdu" 12
display unit to create a Screen Target for
.IP "mode" 12
The mode to set.
.IP "crtc_x" 12
X coordinate of screen target relative to framebuffer origin.
.IP "crtc_y" 12
Y coordinate of screen target relative to framebuffer origin.
.SH "DESCRIPTION"
Creates a STDU that we can used later.  This function is called whenever the
framebuffer size changes.
.SH "RETURN"
0 on success, error code on failure
