.TH "vmw_view_key" 9 "vmw_view_key" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_view_key \- Compute a view key suitable for the cmdbuf resource manager
.SH SYNOPSIS
.B "u32" vmw_view_key
.BI "(u32 user_key "  ","
.BI "enum vmw_view_type view_type "  ");"
.SH ARGUMENTS
.IP "user_key" 12
The user-space id used for the view.
.IP "view_type" 12
The view type.
.SH "DESCRIPTION"
Destroy a hardware view if it's still present.
