.TH "vmw_sou_surface_fifo_commit" 9 "vmw_sou_surface_fifo_commit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_sou_surface_fifo_commit \- Callback to fill in and submit a blit surface to screen command.
.SH SYNOPSIS
.B "void" vmw_sou_surface_fifo_commit
.BI "(struct vmw_kms_dirty *dirty "  ");"
.SH ARGUMENTS
.IP "dirty" 12
The closure structure.
.SH "DESCRIPTION"
Fills in the missing fields in the command, and translates the cliprects
to match the destination bounding box encoded.
