.TH "vmw_res_to_dx_shader" 9 "vmw_res_to_dx_shader" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_res_to_dx_shader \- typecast a struct vmw_resource to a struct vmw_dx_shader
.SH SYNOPSIS
.B "struct vmw_dx_shader *" vmw_res_to_dx_shader
.BI "(struct vmw_resource *res "  ");"
.SH ARGUMENTS
.IP "res" 12
Pointer to the struct vmw_resource.
