.TH "vmw_binding_emit_dirty_ps" 9 "vmw_binding_emit_dirty_ps" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_binding_emit_dirty_ps \- Issue delayed per shader binding commands
.SH SYNOPSIS
.B "int" vmw_binding_emit_dirty_ps
.BI "(struct vmw_ctx_binding_state *cbs "  ");"
.SH ARGUMENTS
.IP "cbs" 12
Pointer to the context's struct vmw_ctx_binding_state
