.TH "vmw_execbuf_res_size" 9 "vmw_execbuf_res_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_execbuf_res_size \- calculate extra size fore the resource validation node
.SH SYNOPSIS
.B "unsigned int" vmw_execbuf_res_size
.BI "(struct vmw_private *dev_priv "  ","
.BI "enum vmw_res_type res_type "  ");"
.SH ARGUMENTS
.IP "dev_priv" 12
Pointer to the device private struct.
.IP "res_type" 12
The resource type.
.SH "DESCRIPTION"
Guest-backed contexts and DX contexts require extra size to store execbuf
private information in the validation node. Typically the binding manager
associated data structures.
.SH "RETURN"
The extra size requirement based on resource type.
