.TH "vmw_dx_streamoutput_add" 9 "vmw_dx_streamoutput_add" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vmw_dx_streamoutput_add \- Add a streamoutput as a cmd buf managed resource.
.SH SYNOPSIS
.B "int" vmw_dx_streamoutput_add
.BI "(struct vmw_cmdbuf_res_manager *man "  ","
.BI "struct vmw_resource *ctx "  ","
.BI "u32 user_key "  ","
.BI "struct list_head *list "  ");"
.SH ARGUMENTS
.IP "man" 12
Command buffer managed resource manager for current context.
.IP "ctx" 12
Pointer to context resource.
.IP "user_key" 12
The identifier for this streamoutput.
.IP "list" 12
The list of staged command buffer managed resources.
.SH "RETURN"
0 on success, negative error code on failure.
