.TH "vpbe_get_output" 9 "vpbe_get_output" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vpbe_get_output \- Get output
.SH SYNOPSIS
.B "unsigned int" vpbe_get_output
.BI "(struct vpbe_device *vpbe_dev "  ");"
.SH ARGUMENTS
.IP "vpbe_dev" 12
vpbe device ptr
.SH "DESCRIPTION"
return current vpbe output to the the index
