.TH "vpfe_schedule_next_buffer" 9 "vpfe_schedule_next_buffer" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vpfe_schedule_next_buffer \- set next buffer address for capture
.SH SYNOPSIS
.B "void" vpfe_schedule_next_buffer
.BI "(struct vpfe_device *vpfe "  ");"
.SH ARGUMENTS
.IP "vpfe" 12
ptr to vpfe device
.SH "DESCRIPTION"
This function will get next buffer from the dma queue and
set the buffer address in the vpfe register for capture.
the buffer is marked active
