.TH "vpif_output_to_subdev" 9 "vpif_output_to_subdev" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vpif_output_to_subdev \- Maps output to sub device
.SH SYNOPSIS
.B "int" vpif_output_to_subdev
.BI "(struct vpif_display_config *vpif_cfg "  ","
.BI "struct vpif_display_chan_config *chan_cfg "  ","
.BI "int index "  ");"
.SH ARGUMENTS
.IP "vpif_cfg" 12
global config ptr
.IP "chan_cfg" 12
channel config ptr
.IP "index" 12
Given output index from application
.SH "DESCRIPTION"
lookup the sub device information for a given output index.
we report all the output to application. output table also
has sub device name for the each output
