.TH "vpif_stop_streaming" 9 "vpif_stop_streaming" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vpif_stop_streaming \- Stop the DMA engine
.SH SYNOPSIS
.B "void" vpif_stop_streaming
.BI "(struct vb2_queue *vq "  ");"
.SH ARGUMENTS
.IP "vq" 12
ptr to vb2_queue
.SH "DESCRIPTION"
This callback stops the DMA engine and any remaining buffers
in the DMA queue are released.
