.TH "vpif_get_default_field" 9 "vpif_get_default_field" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vpif_get_default_field \- Get default field type based on interface
.SH SYNOPSIS
.B "enum v4l2_field" vpif_get_default_field
.BI "(struct vpif_interface *iface "  ");"
.SH ARGUMENTS
.IP "iface" 12
ptr to vpif interface
