.TH "vsp1_dl_body_put" 9 "vsp1_dl_body_put" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vsp1_dl_body_put \- Return a body back to its pool
.SH SYNOPSIS
.B "void" vsp1_dl_body_put
.BI "(struct vsp1_dl_body *dlb "  ");"
.SH ARGUMENTS
.IP "dlb" 12
The display list body
.SH "DESCRIPTION"
Return a body back to the pool, and reset the num_entries to clear the list.
