.TH "vsp1_dl_list_put" 9 "vsp1_dl_list_put" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vsp1_dl_list_put \- Release a display list
.SH SYNOPSIS
.B "void" vsp1_dl_list_put
.BI "(struct vsp1_dl_list *dl "  ");"
.SH ARGUMENTS
.IP "dl" 12
The display list
.SH "DESCRIPTION"
Release the display list and return it to the pool of free lists.

Passing a NULL pointer to this function is safe, in that case no operation
will be performed.
