.TH "vsp1_dl_cmd_pool_create" 9 "vsp1_dl_cmd_pool_create" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vsp1_dl_cmd_pool_create \- Create a pool of commands from a single allocation
.SH SYNOPSIS
.B "struct vsp1_dl_cmd_pool *" vsp1_dl_cmd_pool_create
.BI "(struct vsp1_device *vsp1 "  ","
.BI "enum vsp1_extcmd_type type "  ","
.BI "unsigned int num_cmds "  ");"
.SH ARGUMENTS
.IP "vsp1" 12
The VSP1 device
.IP "type" 12
The command pool type
.IP "num_cmds" 12
The number of commands to allocate
.SH "DESCRIPTION"
Allocate a pool of commands each with enough memory to contain the private
data of each command. The allocation sizes are dependent upon the command
type.

Return a pointer to the pool on success or NULL if memory can't be allocated.
