.TH "vt_event_wait" 9 "vt_event_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vt_event_wait \- wait for an event
.SH SYNOPSIS
.B "void" vt_event_wait
.BI "(struct vt_event_wait *vw "  ");"
.SH ARGUMENTS
.IP "vw" 12
our event

Waits for an event to occur which completes our vt_event_wait
structure. On return the structure has wv->done set to 1 for success
or 0 if some event such as a signal ended the wait.
