.TH "vt_set_led_state" 9 "vt_set_led_state" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vt_set_led_state \- set LED state of a console
.SH SYNOPSIS
.B "void" vt_set_led_state
.BI "(int console "  ","
.BI "int leds "  ");"
.SH ARGUMENTS
.IP "console" 12
console to set
.IP "leds" 12
LED bits

Set the LEDs on a console. This is a wrapper for the VT layer
so that we can keep kbd knowledge internal
