.TH "vxge_hw_vpath_msix_unmask" 9 "vxge_hw_vpath_msix_unmask" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxge_hw_vpath_msix_unmask \- Unmask the MSIX Vector.
.SH SYNOPSIS
.B "void" vxge_hw_vpath_msix_unmask
.BI "(struct __vxge_hw_vpath_handle *vp "  ","
.BI "int msix_id "  ");"
.SH ARGUMENTS
.IP "vp" 12
Virtual Path handle.
.IP "msix_id" 12
MSI ID
.SH "DESCRIPTION"
The function unmasks the msix interrupt for the given msix_id
.SH "RETURN"
0,
Otherwise, VXGE_HW_ERR_WRONG_IRQ if the msix index is out of range
status.
See also:
