.TH "vxge_hw_vpath_mcast_enable" 9 "vxge_hw_vpath_mcast_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxge_hw_vpath_mcast_enable \- Enable multicast addresses.
.SH SYNOPSIS
.B "enum vxge_hw_status" vxge_hw_vpath_mcast_enable
.BI "(struct __vxge_hw_vpath_handle *vp "  ");"
.SH ARGUMENTS
.IP "vp" 12
Vpath handle.
.SH "DESCRIPTION"
Enable Titan-e multicast addresses.
.SH "RETURN"
VXGE_HW_OK on success.
