.TH "vxge_hw_device_hw_info_get" 9 "vxge_hw_device_hw_info_get" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
vxge_hw_device_hw_info_get \- Get the hw information
.SH SYNOPSIS
.B "enum vxge_hw_status" vxge_hw_device_hw_info_get
.BI "(void __iomem *bar0 "  ","
.BI "struct vxge_hw_device_hw_info *hw_info "  ");"
.SH ARGUMENTS
.IP "bar0" 12
the bar
.IP "hw_info" 12
the hw_info struct
.SH "DESCRIPTION"
Returns the vpath mask that has the bits set for each vpath allocated
for the driver, FW version information, and the first mac address for
each vpath
