.TH "w1_poll_completion" 9 "w1_poll_completion" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
w1_poll_completion \- Poll for operation completion, with timeout
.SH SYNOPSIS
.B "int" w1_poll_completion
.BI "(struct w1_master *dev_master "  ","
.BI "int tout_ms "  ");"
.SH ARGUMENTS
.IP "dev_master" 12
the device master of the bus
.IP "tout_ms" 12
timeout in milliseconds
.SH "DESCRIPTION"
The device is answering 0's while an operation is in progress and 1's after it completes
Timeout may happen if the previous command was not recognised due to a line noise
.SH "RETURN"
0 - OK, negative error - timeout
