.TH "w1_remove_master_device" 9 "w1_remove_master_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
w1_remove_master_device \- unregister a master device
.SH SYNOPSIS
.B "void" w1_remove_master_device
.BI "(struct w1_bus_master *bm "  ");"
.SH ARGUMENTS
.IP "bm" 12
master bus device to remove
