.TH "w_send_dblock" 9 "w_send_dblock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
w_send_dblock \- Worker callback to send a P_DATA packet in order to mirror a write request
.SH SYNOPSIS
.B "int" w_send_dblock
.BI "(struct drbd_work *w "  ","
.BI "int cancel "  ");"
.SH ARGUMENTS
.IP "w" 12
work object.
.IP "cancel" 12
The connection will be closed anyways
