.TH "wait_for_owner_exiting" 9 "wait_for_owner_exiting" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wait_for_owner_exiting \- Block until the owner has exited
.SH SYNOPSIS
.B "void" wait_for_owner_exiting
.BI "(int ret "  ","
.BI "struct task_struct *exiting "  ");"
.SH ARGUMENTS
.IP "ret" 12
owner's current futex lock status
.IP "exiting" 12
Pointer to the exiting task
.SH "DESCRIPTION"
Caller must hold a refcount on \fIexiting\fP.
