.TH "wdrtas_exit" 9 "wdrtas_exit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wdrtas_exit \- exit function of the watchdog driver
.SH SYNOPSIS
.B "void __exit" wdrtas_exit
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

unregisters the file handlers and the reboot notifier
