.TH "wdrtas_timer_stop" 9 "wdrtas_timer_stop" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wdrtas_timer_stop \- stops watchdog
.SH SYNOPSIS
.B "void" wdrtas_timer_stop
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
.SH "DESCRIPTION"

wdrtas_timer_stop stops the watchdog timer by calling the RTAS function
set-interval (surveillance)
