.TH "wdt_supports_disable" 9 "wdt_supports_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wdt_supports_disable \- determine if we are accessing a iop13xx watchdog or iop3xx by whether it has a disable command
.SH SYNOPSIS
.B "int" wdt_supports_disable
.BI "(void "  ");"
.SH ARGUMENTS
.IP "void" 12
no arguments
