.TH "wdt_set_timeout" 9 "wdt_set_timeout" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wdt_set_timeout \- set a new timeout value with watchdog ioctl
.SH SYNOPSIS
.B "int" wdt_set_timeout
.BI "(struct watchdog_device *wdd "  ","
.BI "unsigned int t "  ");"
.SH ARGUMENTS
.IP "wdd" 12
-- undescribed --
.IP "t" 12
timeout value in seconds

The hardware device has a 8 or 16 bit watchdog timer (depends on
chip version) that can be configured to count seconds or minutes.

Used within WDIOC_SETTIMEOUT watchdog device ioctl.
