.TH "wilco_ec_checksum" 9 "wilco_ec_checksum" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wilco_ec_checksum \- Compute 8-bit checksum over data range.
.SH SYNOPSIS
.B "u8" wilco_ec_checksum
.BI "(const void *data "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "data" 12
Data to checksum.
.IP "size" 12
Number of bytes to checksum.
.SH "RETURN"
8-bit checksum of provided data.
