.TH "wl3501_set_to_wla" 9 "wl3501_set_to_wla" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wl3501_set_to_wla \- Move 'size' bytes from PC to card
.SH SYNOPSIS
.B "void" wl3501_set_to_wla
.BI "(struct wl3501_card *this "  ","
.BI "u16 dest "  ","
.BI "void *src "  ","
.BI "int size "  ");"
.SH ARGUMENTS
.IP "this" 12
Card
.IP "dest" 12
Card addressing space
.IP "src" 12
PC addressing space
.IP "size" 12
Bytes to move
.SH "DESCRIPTION"
Move 'size' bytes from PC to card. (Shouldn't be interrupted)
