.TH "wm831x_reg_unlock" 9 "wm831x_reg_unlock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wm831x_reg_unlock \- Unlock user keyed registers
.SH SYNOPSIS
.B "int" wm831x_reg_unlock
.BI "(struct wm831x *wm831x "  ");"
.SH ARGUMENTS
.IP "wm831x" 12
pointer to local driver data structure
.SH "DESCRIPTION"

The WM831x has a user key preventing writes to particularly
critical registers.  This function locks those registers,
preventing spurious writes.
