.TH "wmi_has_guid" 9 "wmi_has_guid" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
wmi_has_guid \- Check if a GUID is available
.SH SYNOPSIS
.B "bool" wmi_has_guid
.BI "(const char *guid_string "  ");"
.SH ARGUMENTS
.IP "guid_string" 12
36 char string of the form fa50ff2b-f2e8-45de-83fa-65417f2f49ba
.SH "DESCRIPTION"
Check if a given GUID is defined by _WDG
