.TH "write_dscr" 9 "write_dscr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
write_dscr \- Update the cpu specific DSCR default
.SH SYNOPSIS
.B "void" write_dscr
.BI "(void *val "  ");"
.SH ARGUMENTS
.IP "val" 12
New cpu specific DSCR default value to update
.SH "DESCRIPTION"
This function updates the per cpu DSCR default value
for any cpu which is contained in it's PACA structure.
