.TH "write_csr" 9 "write_csr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
write_csr \- write CSR at the indicated offset
.SH SYNOPSIS
.B "void" write_csr
.BI "(const struct hfi1_devdata *dd "  ","
.BI "u32 offset "  ","
.BI "u64 value "  ");"
.SH ARGUMENTS
.IP "dd" 12
the dd device
.IP "offset" 12
the offset of the CSR within bar0
.IP "value" 12
value to write
