.TH "xcan_set_bittiming" 9 "xcan_set_bittiming" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xcan_set_bittiming \- CAN set bit timing routine
.SH SYNOPSIS
.B "int" xcan_set_bittiming
.BI "(struct net_device *ndev "  ");"
.SH ARGUMENTS
.IP "ndev" 12
Pointer to net_device structure
.SH "DESCRIPTION"
This is the driver set bittiming  routine.
.SH "RETURN"
0 on success and failure value on error
