.TH "xcan_open" 9 "xcan_open" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xcan_open \- Driver open routine
.SH SYNOPSIS
.B "int" xcan_open
.BI "(struct net_device *ndev "  ");"
.SH ARGUMENTS
.IP "ndev" 12
Pointer to net_device structure
.SH "DESCRIPTION"
This is the driver open routine.
.SH "RETURN"
0 on success and failure value on error
