.TH "xcan_write_reg_be" 9 "xcan_write_reg_be" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xcan_write_reg_be \- Write a value to the device register big endian
.SH SYNOPSIS
.B "void" xcan_write_reg_be
.BI "(const struct xcan_priv *priv "  ","
.BI "enum xcan_reg reg "  ","
.BI "u32 val "  ");"
.SH ARGUMENTS
.IP "priv" 12
Driver private data structure
.IP "reg" 12
Register offset
.IP "val" 12
Value to write at the Register offset
.SH "DESCRIPTION"
Write data to the paricular CAN register
