.TH "xdr_stream_decode_string" 9 "xdr_stream_decode_string" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xdr_stream_decode_string \- Decode variable length string
.SH SYNOPSIS
.B "ssize_t" xdr_stream_decode_string
.BI "(struct xdr_stream *xdr "  ","
.BI "char *str "  ","
.BI "size_t size "  ");"
.SH ARGUMENTS
.IP "xdr" 12
pointer to xdr_stream
.IP "str" 12
location to store string
.IP "size" 12
size of storage buffer \fIstr\fP
.SH "DESCRIPTION"
Return values:
On success, returns length of NUL-terminated string stored in *\fIstr\fP
-EBADMSG on XDR buffer overflow
-EMSGSIZE on overflow of storage buffer \fIstr\fP
