.TH "xdr_init_decode_pages" 9 "xdr_init_decode_pages" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xdr_init_decode_pages \- Initialize an xdr_stream for decoding into pages
.SH SYNOPSIS
.B "void" xdr_init_decode_pages
.BI "(struct xdr_stream *xdr "  ","
.BI "struct xdr_buf *buf "  ","
.BI "struct page **pages "  ","
.BI "unsigned int len "  ");"
.SH ARGUMENTS
.IP "xdr" 12
pointer to xdr_stream struct
.IP "buf" 12
pointer to XDR buffer from which to decode data
.IP "pages" 12
list of pages to decode into
.IP "len" 12
length in bytes of buffer in pages
