.TH "xdr_buf_trim" 9 "xdr_buf_trim" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xdr_buf_trim \- lop at most "len" bytes off the end of "buf"
.SH SYNOPSIS
.B "void" xdr_buf_trim
.BI "(struct xdr_buf *buf "  ","
.BI "unsigned int len "  ");"
.SH ARGUMENTS
.IP "buf" 12
buf to be trimmed
.IP "len" 12
number of bytes to reduce "buf" by
.SH "DESCRIPTION"
Trim an xdr_buf by the given number of bytes by fixing up the lengths. Note
that it's possible that we'll trim less than that amount if the xdr_buf is
too small, or if (for instance) it's all in the head and the parser has
already read too far into it.
