.TH "xemaclite_mdio_wait" 9 "xemaclite_mdio_wait" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xemaclite_mdio_wait \- Wait for the MDIO to be ready to use
.SH SYNOPSIS
.B "int" xemaclite_mdio_wait
.BI "(struct net_local *lp "  ");"
.SH ARGUMENTS
.IP "lp" 12
Pointer to the Emaclite device private data
.SH "DESCRIPTION"
This function waits till the device is ready to accept a new MDIO
request.
.SH "RETURN"
0 for success or ETIMEDOUT for a timeout
