.TH "xfs_btree_sblock_verify" 9 "xfs_btree_sblock_verify" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xfs_btree_sblock_verify \- - verify a short-format btree block
.SH SYNOPSIS
.B "xfs_failaddr_t" xfs_btree_sblock_verify
.BI "(struct xfs_buf *bp "  ","
.BI "unsigned int max_recs "  ");"
.SH ARGUMENTS
.IP "bp" 12
buffer containing the btree block
.IP "max_recs" 12
maximum records allowed in this btree node
