.TH "xgene_ahci_poll_reg_val" 9 "xgene_ahci_poll_reg_val" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xgene_ahci_poll_reg_val \- Poll a register on a specific value.
.SH SYNOPSIS
.B "int" xgene_ahci_poll_reg_val
.BI "(struct ata_port *ap "  ","
.BI "void __iomem *reg "  ","
.BI "unsigned int val "  ","
.BI "unsigned long interval "  ","
.BI "unsigned long timeout "  ");"
.SH ARGUMENTS
.IP "ap" 12
ATA port of interest.
.IP "reg" 12
Register of interest.
.IP "val" 12
Value to be attained.
.IP "interval" 12
waiting interval for polling.
.IP "timeout" 12
timeout for achieving the value.
