.TH "xgpio_dir_in" 9 "xgpio_dir_in" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xgpio_dir_in \- Set the direction of the specified GPIO signal as input.
.SH SYNOPSIS
.B "int" xgpio_dir_in
.BI "(struct gpio_chip *gc "  ","
.BI "unsigned int gpio "  ");"
.SH ARGUMENTS
.IP "gc" 12
Pointer to gpio_chip device structure.
.IP "gpio" 12
GPIO signal number.
.SH "RETURN"
0 - if direction of GPIO signals is set as input
otherwise it returns negative error value.
