.TH "xilinx_dma_tx_status" 9 "xilinx_dma_tx_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xilinx_dma_tx_status \- Get DMA transaction status
.SH SYNOPSIS
.B "enum dma_status" xilinx_dma_tx_status
.BI "(struct dma_chan *dchan "  ","
.BI "dma_cookie_t cookie "  ","
.BI "struct dma_tx_state *txstate "  ");"
.SH ARGUMENTS
.IP "dchan" 12
DMA channel
.IP "cookie" 12
Transaction identifier
.IP "txstate" 12
Transaction state
.SH "RETURN"
DMA transaction status
