.TH "xilinx_dpdma_enable_irq" 9 "xilinx_dpdma_enable_irq" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xilinx_dpdma_enable_irq \- Enable interrupts
.SH SYNOPSIS
.B "void" xilinx_dpdma_enable_irq
.BI "(struct xilinx_dpdma_device *xdev "  ");"
.SH ARGUMENTS
.IP "xdev" 12
DPDMA device
.SH "DESCRIPTION"
Enable interrupts.
