.TH "xilinx_dpdma_chan_free_sw_desc" 9 "xilinx_dpdma_chan_free_sw_desc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xilinx_dpdma_chan_free_sw_desc \- Free a software descriptor
.SH SYNOPSIS
.B "void" xilinx_dpdma_chan_free_sw_desc
.BI "(struct xilinx_dpdma_chan *chan "  ","
.BI "struct xilinx_dpdma_sw_desc *sw_desc "  ");"
.SH ARGUMENTS
.IP "chan" 12
DPDMA channel
.IP "sw_desc" 12
software descriptor to free
.SH "DESCRIPTION"
Free a software descriptor from the channel's descriptor pool.
