.TH "xilinx_dma_child_probe" 9 "xilinx_dma_child_probe" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xilinx_dma_child_probe \- Per child node probe It get number of dma-channels per child node from device-tree and initializes all the channels.
.SH SYNOPSIS
.B "int" xilinx_dma_child_probe
.BI "(struct xilinx_dma_device *xdev "  ","
.BI "struct device_node *node "  ");"
.SH ARGUMENTS
.IP "xdev" 12
Driver specific device structure
.IP "node" 12
Device node
.SH "RETURN"
0 always.
