.TH "xilinx_dma_free_desc_list" 9 "xilinx_dma_free_desc_list" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xilinx_dma_free_desc_list \- Free descriptors list
.SH SYNOPSIS
.B "void" xilinx_dma_free_desc_list
.BI "(struct xilinx_dma_chan *chan "  ","
.BI "struct list_head *list "  ");"
.SH ARGUMENTS
.IP "chan" 12
Driver specific DMA channel
.IP "list" 12
List to parse and delete the descriptor
