.TH "xprt_request_enqueue_transmit" 9 "xprt_request_enqueue_transmit" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_request_enqueue_transmit \- queue a task for transmission
.SH SYNOPSIS
.B "void" xprt_request_enqueue_transmit
.BI "(struct rpc_task *task "  ");"
.SH ARGUMENTS
.IP "task" 12
pointer to rpc_task
.SH "DESCRIPTION"
Add a task to the transmission queue.
