.TH "xprt_disconnect_done" 9 "xprt_disconnect_done" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_disconnect_done \- mark a transport as disconnected
.SH SYNOPSIS
.B "void" xprt_disconnect_done
.BI "(struct rpc_xprt *xprt "  ");"
.SH ARGUMENTS
.IP "xprt" 12
transport to flag for disconnect
