.TH "xprt_rdma_inject_disconnect" 9 "xprt_rdma_inject_disconnect" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_rdma_inject_disconnect \- inject a connection fault
.SH SYNOPSIS
.B "void" xprt_rdma_inject_disconnect
.BI "(struct rpc_xprt *xprt "  ");"
.SH ARGUMENTS
.IP "xprt" 12
transport context
.SH "DESCRIPTION"
If \fIxprt\fP is connected, disconnect it to simulate spurious connection
loss.
