.TH "xprt_rdma_bc_destroy" 9 "xprt_rdma_bc_destroy" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_rdma_bc_destroy \- Release resources for handling backchannel requests
.SH SYNOPSIS
.B "void" xprt_rdma_bc_destroy
.BI "(struct rpc_xprt *xprt "  ","
.BI "unsigned int reqs "  ");"
.SH ARGUMENTS
.IP "xprt" 12
transport associated with these backchannel resources
.IP "reqs" 12
number of incoming requests to destroy; ignored
