.TH "xprt_destroy_backchannel" 9 "xprt_destroy_backchannel" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xprt_destroy_backchannel \- Destroys the backchannel preallocated structures.
.SH SYNOPSIS
.B "void" xprt_destroy_backchannel
.BI "(struct rpc_xprt *xprt "  ","
.BI "unsigned int max_reqs "  ");"
.SH ARGUMENTS
.IP "xprt" 12
the transport holding the preallocated strucures
.IP "max_reqs" 12
the maximum number of preallocated structures to destroy
.SH "DESCRIPTION"
Since these structures may have been allocated by multiple calls
to xprt_setup_backchannel, we only destroy up to the maximum number
of reqs specified by the caller.
