.TH "xs_local_setup_socket" 9 "xs_local_setup_socket" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xs_local_setup_socket \- create AF_LOCAL socket, connect to a local endpoint
.SH SYNOPSIS
.B "int" xs_local_setup_socket
.BI "(struct sock_xprt *transport "  ");"
.SH ARGUMENTS
.IP "transport" 12
socket transport to connect
