.TH "xs_udp_send_request" 9 "xs_udp_send_request" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xs_udp_send_request \- write an RPC request to a UDP socket
.SH SYNOPSIS
.B "int" xs_udp_send_request
.BI "(struct rpc_rqst *req "  ");"
.SH ARGUMENTS
.IP "req" 12
pointer to RPC request
.SH "DESCRIPTION"
Return values:
0:    The request has been sent
EAGAIN:    The socket was blocked, please call again later to
complete the request
ENOTCONN:    Caller needs to invoke connect logic then call again
other:    Some other error occurred, the request was not sent
