.TH "xs_udp_set_buffer_size" 9 "xs_udp_set_buffer_size" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xs_udp_set_buffer_size \- set send and receive limits
.SH SYNOPSIS
.B "void" xs_udp_set_buffer_size
.BI "(struct rpc_xprt *xprt "  ","
.BI "size_t sndsize "  ","
.BI "size_t rcvsize "  ");"
.SH ARGUMENTS
.IP "xprt" 12
generic transport
.IP "sndsize" 12
requested size of send buffer, in bytes
.IP "rcvsize" 12
requested size of receive buffer, in bytes
.SH "DESCRIPTION"
Set socket send and receive buffer size limits.
