.TH "xudc_eptxrx" 9 "xudc_eptxrx" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xudc_eptxrx \- Transmits or receives data to or from an endpoint.
.SH SYNOPSIS
.B "int" xudc_eptxrx
.BI "(struct xusb_ep *ep "  ","
.BI "struct xusb_req *req "  ","
.BI "u8 *bufferptr "  ","
.BI "u32 bufferlen "  ");"
.SH ARGUMENTS
.IP "ep" 12
pointer to the usb endpoint configuration structure.
.IP "req" 12
pointer to the usb request structure.
.IP "bufferptr" 12
pointer to buffer containing the data to be sent.
.IP "bufferlen" 12
The number of data bytes to be sent.
.SH "RETURN"
0 on success, -EAGAIN if no buffer is free.
.SH "DESCRIPTION"
This function copies the transmit/receive data to/from the end point buffer
and enables the buffer for transmission/reception.
