.TH "xudc_ep_disable" 9 "xudc_ep_disable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xudc_ep_disable \- Disables the given endpoint.
.SH SYNOPSIS
.B "int" xudc_ep_disable
.BI "(struct usb_ep *_ep "  ");"
.SH ARGUMENTS
.IP "_ep" 12
pointer to the usb endpoint structure.
.SH "RETURN"
0 for success and error value on failure
