.TH "xudc_ep_dequeue" 9 "xudc_ep_dequeue" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xudc_ep_dequeue \- Removes the request from the queue.
.SH SYNOPSIS
.B "int" xudc_ep_dequeue
.BI "(struct usb_ep *_ep "  ","
.BI "struct usb_request *_req "  ");"
.SH ARGUMENTS
.IP "_ep" 12
pointer to the usb device endpoint structure.
.IP "_req" 12
pointer to the usb request structure.
.SH "RETURN"
0 for success and error value on failure
