.TH "xvip_enum_mbus_code" 9 "xvip_enum_mbus_code" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xvip_enum_mbus_code \- Enumerate the media format code
.SH SYNOPSIS
.B "int" xvip_enum_mbus_code
.BI "(struct v4l2_subdev *subdev "  ","
.BI "struct v4l2_subdev_pad_config *cfg "  ","
.BI "struct v4l2_subdev_mbus_code_enum *code "  ");"
.SH ARGUMENTS
.IP "subdev" 12
V4L2 subdevice
.IP "cfg" 12
V4L2 subdev pad configuration
.IP "code" 12
returning media bus code
.SH "DESCRIPTION"
Enumerate the media bus code of the subdevice. Return the corresponding
pad format code. This function only works for subdevices with fixed format
on all pads. Subdevices with multiple format should have their own
function to enumerate mbus codes.
.SH "RETURN"
0 if the media bus code is found, or -EINVAL if the format index
is not valid.
