.TH "xvip_get_format_by_code" 9 "xvip_get_format_by_code" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xvip_get_format_by_code \- Retrieve format information for a media bus code
.SH SYNOPSIS
.B "const struct xvip_video_format *" xvip_get_format_by_code
.BI "(unsigned int code "  ");"
.SH ARGUMENTS
.IP "code" 12
the format media bus code
.SH "RETURN"
a pointer to the format information structure corresponding to the
given V4L2 media bus format \fIcode\fP, or ERR_PTR if no corresponding format can
be found.
