.TH "xvip_get_format_by_fourcc" 9 "xvip_get_format_by_fourcc" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xvip_get_format_by_fourcc \- Retrieve format information for a 4CC
.SH SYNOPSIS
.B "const struct xvip_video_format *" xvip_get_format_by_fourcc
.BI "(u32 fourcc "  ");"
.SH ARGUMENTS
.IP "fourcc" 12
the format 4CC
.SH "RETURN"
a pointer to the format information structure corresponding to the
given V4L2 format \fIfourcc\fP, or ERR_PTR if no corresponding format can be
found.
