.TH "xvip_clr_and_set" 9 "xvip_clr_and_set" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xvip_clr_and_set \- Clear and set the register with a bitmask
.SH SYNOPSIS
.B "void" xvip_clr_and_set
.BI "(struct xvip_device *xvip "  ","
.BI "u32 addr "  ","
.BI "u32 clr "  ","
.BI "u32 set "  ");"
.SH ARGUMENTS
.IP "xvip" 12
Xilinx Video IP device
.IP "addr" 12
address of register
.IP "clr" 12
bitmask to be cleared
.IP "set" 12
bitmask to be set
.SH "DESCRIPTION"
Clear a bit(s) of mask \fIclr\fP in the register at address \fIaddr\fP, then set
a bit(s) of mask \fIset\fP in the register after.
