.TH "xxxfb_sync" 9 "xxxfb_sync" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
xxxfb_sync \- NOT a required function. Normally the accel engine for a graphics card take a specific amount of time. Often we have to wait for the accelerator to finish its operation before we can write to the framebuffer so we can have consistent display output. 
.SH SYNOPSIS
.B "int" xxxfb_sync
.BI "(struct fb_info *info "  ");"
.SH ARGUMENTS
.IP "info" 12
frame buffer structure that represents a single frame buffer

If the driver has implemented its own hardware-based drawing function,
implementing this function is highly recommended.
