.TH "yama_ptrace_access_check" 9 "yama_ptrace_access_check" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
yama_ptrace_access_check \- validate PTRACE_ATTACH calls
.SH SYNOPSIS
.B "int" yama_ptrace_access_check
.BI "(struct task_struct *child "  ","
.BI "unsigned int mode "  ");"
.SH ARGUMENTS
.IP "child" 12
task that current task is attempting to ptrace
.IP "mode" 12
ptrace attach mode
.SH "DESCRIPTION"
Returns 0 if following the ptrace is allowed, -ve on error.
