.TH "z8530_rtsdtr" 9 "z8530_rtsdtr" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
z8530_rtsdtr \- Control the outgoing DTS/RTS line
.SH SYNOPSIS
.B "void" z8530_rtsdtr
.BI "(struct z8530_channel *c "  ","
.BI "int set "  ");"
.SH ARGUMENTS
.IP "c" 12
The Z8530 channel to control;
.IP "set" 12
1 to set, 0 to clear

Sets or clears DTR/RTS on the requested line. All locking is handled
by the caller. For now we assume all boards use the actual RTS/DTR
on the chip. Apparently one or two don't. We'll scream about them
later.
