.TH "zcrypt_release" 9 "zcrypt_release" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zcrypt_release \- Count number of users.
.SH SYNOPSIS
.B "int" zcrypt_release
.BI "(struct inode *inode "  ","
.BI "struct file *filp "  ");"
.SH ARGUMENTS
.IP "inode" 12
-- undescribed --
.IP "filp" 12
-- undescribed --
.SH "DESCRIPTION"

Device close function to count number of users.
