.TH "zfcp_fsf_fcp_task_mgmt" 9 "zfcp_fsf_fcp_task_mgmt" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_fsf_fcp_task_mgmt \- Send SCSI task management command (TMF).
.SH SYNOPSIS
.B "struct zfcp_fsf_req *" zfcp_fsf_fcp_task_mgmt
.BI "(struct scsi_device *sdev "  ","
.BI "u8 tm_flags "  ");"
.SH ARGUMENTS
.IP "sdev" 12
Pointer to SCSI device to send the task management command to.
.IP "tm_flags" 12
Unsigned byte for task management flags.
.SH "RETURN"
On success pointer to struct zfcp_fsf_req, NULL otherwise.
