.TH "zfcp_fc_test_link" 9 "zfcp_fc_test_link" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_fc_test_link \- lightweight link test procedure
.SH SYNOPSIS
.B "void" zfcp_fc_test_link
.BI "(struct zfcp_port *port "  ");"
.SH ARGUMENTS
.IP "port" 12
port to be tested
.SH "DESCRIPTION"
Test status of a link to a remote port using the ELS command ADISC.
If there is a problem with the remote port, error recovery steps
will be triggered.
