.TH "zfcp_erp_clear_lun_status" 9 "zfcp_erp_clear_lun_status" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_erp_clear_lun_status \- clear lun status bits
.SH SYNOPSIS
.B "void" zfcp_erp_clear_lun_status
.BI "(struct scsi_device *sdev "  ","
.BI "u32 mask "  ");"
.SH ARGUMENTS
.IP "sdev" 12
SCSi device / lun to clear the status bits
.IP "mask" 12
status bits to change
