.TH "zfcp_dbf_san_in_els" 9 "zfcp_dbf_san_in_els" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_dbf_san_in_els \- trace event for incoming ELS
.SH SYNOPSIS
.B "void" zfcp_dbf_san_in_els
.BI "(char *tag "  ","
.BI "struct zfcp_fsf_req *fsf "  ");"
.SH ARGUMENTS
.IP "tag" 12
identifier for event
.IP "fsf" 12
request containing received ELS data
