.TH "zfcp_scsi_dif_sense_error" 9 "zfcp_scsi_dif_sense_error" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_scsi_dif_sense_error \- Report DIF/DIX error as driver sense error
.SH SYNOPSIS
.B "void" zfcp_scsi_dif_sense_error
.BI "(struct scsi_cmnd *scmd "  ","
.BI "int ascq "  ");"
.SH ARGUMENTS
.IP "scmd" 12
The SCSI command to report the error for
.IP "ascq" 12
The ASCQ to put in the sense buffer
.SH "DESCRIPTION"
See the error handling in sd_done for the sense codes used here.
Set DID_SOFT_ERROR to retry the request, if possible.
