.TH "zfcp_erp_port_forced_reopen" 9 "zfcp_erp_port_forced_reopen" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_erp_port_forced_reopen \- Forced close of port and open again
.SH SYNOPSIS
.B "void" zfcp_erp_port_forced_reopen
.BI "(struct zfcp_port *port "  ","
.BI "int clear "  ","
.BI "char *dbftag "  ");"
.SH ARGUMENTS
.IP "port" 12
Port to force close and to reopen.
.IP "clear" 12
Status flags to clear.
.IP "dbftag" 12
Tag for debug trace event.
