.TH "zfcp_dbf_rec_trig_lock" 9 "zfcp_dbf_rec_trig_lock" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zfcp_dbf_rec_trig_lock \- trace event related to triggered recovery with lock
.SH SYNOPSIS
.B "void" zfcp_dbf_rec_trig_lock
.BI "(char *tag "  ","
.BI "struct zfcp_adapter *adapter "  ","
.BI "struct zfcp_port *port "  ","
.BI "struct scsi_device *sdev "  ","
.BI "u8 want "  ","
.BI "u8 need "  ");"
.SH ARGUMENTS
.IP "tag" 12
identifier for event
.IP "adapter" 12
adapter on which the erp_action should run
.IP "port" 12
remote port involved in the erp_action
.IP "sdev" 12
scsi device involved in the erp_action
.IP "want" 12
wanted erp_action
.IP "need" 12
required erp_action
.SH "DESCRIPTION"
The adapter->erp_lock must not be held.
