.TH "zip_get_device" 9 "zip_get_device" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zip_get_device \- Get ZIP device based on node id of cpu
.SH SYNOPSIS
.B "struct zip_device *" zip_get_device
.BI "(int node "  ");"
.SH ARGUMENTS
.IP "node" 12
Node id of the current cpu
.SH "RETURN"
Pointer to Zip device structure
