.TH "zpa2326_dequeue_pressure" 9 "zpa2326_dequeue_pressure" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zpa2326_dequeue_pressure \- Retrieve the most recent pressure sample from hardware FIFO.
.SH SYNOPSIS
.B "int" zpa2326_dequeue_pressure
.BI "(const struct iio_dev *indio_dev "  ","
.BI "u32 *pressure "  ");"
.SH ARGUMENTS
.IP "indio_dev" 12
The IIO device associated with the sampling hardware.
.IP "pressure" 12
Sampled pressure output.
.SH "DESCRIPTION"
Note that ZPA2326 hardware FIFO stores pressure samples only.
.SH "RETURN"
Zero when successful, a negative error code otherwise.
