.TH "zynq_gpio_get_bank_pin" 9 "zynq_gpio_get_bank_pin" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynq_gpio_get_bank_pin \- Get the bank number and pin number within that bank for a given pin in the GPIO device
.SH SYNOPSIS
.B "void" zynq_gpio_get_bank_pin
.BI "(unsigned int pin_num "  ","
.BI "unsigned int *bank_num "  ","
.BI "unsigned int *bank_pin_num "  ","
.BI "struct zynq_gpio *gpio "  ");"
.SH ARGUMENTS
.IP "pin_num" 12
gpio pin number within the device
.IP "bank_num" 12
an output parameter used to return the bank number of the gpio
pin
.IP "bank_pin_num" 12
an output parameter used to return pin number within a bank
for the given gpio pin
.IP "gpio" 12
gpio device data structure
.SH "DESCRIPTION"
Returns the bank number and pin offset within the bank.
