.TH "zynqmp_register_clocks" 9 "zynqmp_register_clocks" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_register_clocks \- Register clocks
.SH SYNOPSIS
.B "int" zynqmp_register_clocks
.BI "(struct device_node *np "  ");"
.SH ARGUMENTS
.IP "np" 12
Device node
.SH "RETURN"
0 on success else error code
