.TH "zynq_slcr_write" 9 "zynq_slcr_write" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynq_slcr_write \- Write to a register in SLCR block
.SH SYNOPSIS
.B "int" zynq_slcr_write
.BI "(u32 val "  ","
.BI "u32 offset "  ");"
.SH ARGUMENTS
.IP "val" 12
Value to write to the register
.IP "offset" 12
Register offset in SLCR block
.SH "RETURN"
a negative value on error, 0 on success
