.TH "zynq_secondary_init" 9 "zynq_secondary_init" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynq_secondary_init \- Initialize secondary CPU cores
.SH SYNOPSIS
.B "void" zynq_secondary_init
.BI "(unsigned int cpu "  ");"
.SH ARGUMENTS
.IP "cpu" 12
CPU that is initialized
.SH "DESCRIPTION"
This function is in the hotplug path. Don't move it into the
init section!!
