.TH "zynqmp_pm_clock_getrate" 9 "zynqmp_pm_clock_getrate" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_pm_clock_getrate \- Get the clock rate for given id
.SH SYNOPSIS
.B "int" zynqmp_pm_clock_getrate
.BI "(u32 clock_id "  ","
.BI "u64 *rate "  ");"
.SH ARGUMENTS
.IP "clock_id" 12
ID of the clock
.IP "rate" 12
rate value in hz
.SH "DESCRIPTION"
This function is used by master to get rate
for any clock.
.SH "RETURN"
Returns status, either success or error+reason
