.TH "zynqmp_clk_gate_enable" 9 "zynqmp_clk_gate_enable" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_clk_gate_enable \- Enable clock
.SH SYNOPSIS
.B "int" zynqmp_clk_gate_enable
.BI "(struct clk_hw *hw "  ");"
.SH ARGUMENTS
.IP "hw" 12
handle between common and hardware-specific interfaces
.SH "RETURN"
0 on success else error code
