.TH "zynqmp_disp_layer_set_format" 9 "zynqmp_disp_layer_set_format" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_disp_layer_set_format \- Set the layer format
.SH SYNOPSIS
.B "void" zynqmp_disp_layer_set_format
.BI "(struct zynqmp_disp_layer *layer "  ","
.BI "struct drm_plane_state *state "  ");"
.SH ARGUMENTS
.IP "layer" 12
The layer
.IP "state" 12
The plane state
.SH "DESCRIPTION"
Set the format for \fIlayer\fP based on \fIstate->fb->format\fP. The layer must be
disabled.
