.TH "zynqmp_dp_disable_vblank" 9 "zynqmp_dp_disable_vblank" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_dp_disable_vblank \- Disable vblank
.SH SYNOPSIS
.B "void" zynqmp_dp_disable_vblank
.BI "(struct zynqmp_dp *dp "  ");"
.SH ARGUMENTS
.IP "dp" 12
DisplayPort IP core structure
.SH "DESCRIPTION"
Disable vblank interrupt
