.TH "zynqmp_qspi_write_op" 9 "zynqmp_qspi_write_op" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_qspi_write_op \- This function sets up the GENFIFO entries, TX FIFO, and fills the TX FIFO with as many bytes as possible.
.SH SYNOPSIS
.B "void" zynqmp_qspi_write_op
.BI "(struct zynqmp_qspi *xqspi "  ","
.BI "u8 tx_nbits "  ","
.BI "u32 genfifoentry "  ");"
.SH ARGUMENTS
.IP "xqspi" 12
Pointer to the GQSPI instance.
.IP "tx_nbits" 12
Transfer buswidth.
.IP "genfifoentry" 12
Variable in which GENFIFO mask is returned
to calling function
