.TH "zynqmp_dp_enable_vblank" 9 "zynqmp_dp_enable_vblank" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynqmp_dp_enable_vblank \- Enable vblank
.SH SYNOPSIS
.B "void" zynqmp_dp_enable_vblank
.BI "(struct zynqmp_dp *dp "  ");"
.SH ARGUMENTS
.IP "dp" 12
DisplayPort IP core structure
.SH "DESCRIPTION"
Enable vblank interrupt
