.TH "zynq_qspi_remove" 9 "zynq_qspi_remove" "May 2021" "Kernel Hacker's Manual" LINUX
.SH NAME
zynq_qspi_remove \- Remove method for the QSPI driver
.SH SYNOPSIS
.B "int" zynq_qspi_remove
.BI "(struct platform_device *pdev "  ");"
.SH ARGUMENTS
.IP "pdev" 12
Pointer to the platform_device structure
.SH "DESCRIPTION"
This function is called if a device is physically removed from the system or
if the driver module is being unloaded. It frees all resources allocated to
the device.
.SH "RETURN"
0 on success and error value on failure
